import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Vives para el qué dirán?', en: 'Do you live for what people will say?', fr: 'Vis-tu pour ce qu\'on dira de toi ?', de: 'Lebst du für das, was andere sagen?', it: 'Vivi per il cosa diranno?', pt: 'Você vive para o que vão dizer?' },
  description: { es: 'La opinión ajena es poderosa. ¿Cuánto poder le das tú?', en: 'The opinion of others is powerful. How much power do you give it?', fr: 'L\'opinion des autres est puissante. Combien de pouvoir lui donnes-tu ?', de: 'Die Meinung anderer ist mächtig. Wie viel Macht gibst du ihr?', it: 'L\'opinione altrui è potente. Quanto potere gli dai?', pt: 'A opinião alheia é poderosa. Quanto poder você lhe dá?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { Q: 'Qué Dirán', A: 'Aprobación', I: 'Independencia', A2: 'Autenticidad' },
    en: { Q: 'What They\'ll Say', A: 'Approval', I: 'Independence', A2: 'Authenticity' },
    fr: { Q: 'Ce Qu\'ils Diront', A: 'Approbation', I: 'Indépendance', A2: 'Authenticité' },
    de: { Q: 'Was Sie Sagen', A: 'Zustimmung', I: 'Unabhängigkeit', A2: 'Authentizität' },
    it: { Q: 'Cosa Diranno', A: 'Approvazione', I: 'Indipendenza', A2: 'Autenticità' },
    pt: { Q: 'O Que Vão Dizer', A: 'Aprovação', I: 'Independência', A2: 'Autenticidade' },
  },
  questions: [
    { id: 1, situation: { es: 'Quieres cambiar de carrera a algo que otros considerarían "un paso atrás". ¿Qué determina tu decisión?', en: 'You want to change careers to something others would consider "a step back." What determines your decision?', fr: 'Tu veux changer de carrière pour quelque chose que d\'autres considèreraient comme "un pas en arrière". Qu\'est-ce qui détermine ta décision ?', de: 'Du möchtest die Karriere wechseln zu etwas, das andere als "Rückschritt" betrachten würden. Was bestimmt deine Entscheidung?', it: 'Vuoi cambiare carriera verso qualcosa che altri considererebbero "un passo indietro". Cosa determina la tua decisione?', pt: 'Você quer mudar de carreira para algo que outros considerariam "um passo atrás". O que determina sua decisão?' }, options: [
      { text: { es: 'La opinión de mi círculo cercano. No quiero decepcionar a quienes invirtieron en mí.', en: 'The opinion of my close circle. I don\'t want to disappoint those who invested in me.', fr: 'L\'opinion de mon cercle proche. Je ne veux pas décevoir ceux qui ont investi en moi.', de: 'Die Meinung meines engen Kreises. Ich möchte die nicht enttäuschen, die in mich investiert haben.', it: 'L\'opinione del mio cerchio vicino. Non voglio deludere chi ha investito in me.', pt: 'A opinião do meu círculo próximo. Não quero decepcionar quem investiu em mim.' }, dimension: 'Q' },
      { text: { es: 'Si la gente me va a respetar igual o no. El respeto externo importa.', en: 'Whether people will respect me the same or not. External respect matters.', fr: 'Si les gens vont me respecter autant ou non. Le respect externe compte.', de: 'Ob die Menschen mich gleichermaßen respektieren werden oder nicht. Äußerer Respekt ist wichtig.', it: 'Se le persone mi rispetteranno comunque o no. Il rispetto esterno conta.', pt: 'Se as pessoas vão me respeitar da mesma forma ou não. O respeito externo importa.' }, dimension: 'A' },
      { text: { es: 'Solo lo que yo quiera. Las opiniones ajenas no son relevantes para mis decisiones de vida.', en: 'Only what I want. The opinions of others are not relevant to my life decisions.', fr: 'Uniquement ce que je veux. Les opinions des autres ne sont pas pertinentes pour mes décisions de vie.', de: 'Nur das, was ich will. Die Meinungen anderer sind nicht relevant für meine Lebensentscheidungen.', it: 'Solo quello che voglio io. Le opinioni altrui non sono rilevanti per le mie decisioni di vita.', pt: 'Somente o que eu quiser. As opiniões alheias não são relevantes para minhas decisões de vida.' }, dimension: 'I' },
      { text: { es: 'Lo que sea auténtico para mí, aunque nadie lo entienda al principio.', en: 'Whatever is authentic for me, even if nobody understands it at first.', fr: 'Ce qui est authentique pour moi, même si personne ne le comprend au début.', de: 'Was auch immer für mich authentisch ist, auch wenn es am Anfang niemand versteht.', it: 'Qualunque cosa sia autentica per me, anche se all\'inizio nessuno la capisce.', pt: 'O que for autêntico para mim, mesmo que ninguém entenda no início.' }, dimension: 'A2' },
    ] },
    { id: 2, situation: { es: 'Publicas algo personal en redes y recibe poca respuesta. ¿Cómo te afecta?', en: 'You post something personal on social media and it gets little response. How does it affect you?', fr: 'Tu publies quelque chose de personnel sur les réseaux et ça reçoit peu de réponse. Comment ça t\'affecte ?', de: 'Du postest etwas Persönliches in sozialen Medien und es bekommt wenig Resonanz. Wie betrifft dich das?', it: 'Pubblichi qualcosa di personale sui social e riceve poca risposta. Come ti colpisce?', pt: 'Você publica algo pessoal nas redes e recebe pouca resposta. Como isso te afeta?' }, options: [
      { text: { es: 'Me pregunto si hice algo mal o si hay algo en mí que no conecta.', en: 'I wonder if I did something wrong or if there\'s something about me that doesn\'t connect.', fr: 'Je me demande si j\'ai fait quelque chose de mal ou s\'il y a quelque chose en moi qui ne connecte pas.', de: 'Ich frage mich, ob ich etwas falsch gemacht habe oder ob es etwas in mir gibt, das nicht verbindet.', it: 'Mi chiedo se ho fatto qualcosa di sbagliato o se c\'è qualcosa in me che non connette.', pt: 'Me pergunto se fiz algo errado ou se há algo em mim que não conecta.' }, dimension: 'Q' },
      { text: { es: 'Me afecta. La validación de los otros confirma que lo que hago vale.', en: 'It affects me. The validation of others confirms that what I do is worth it.', fr: 'Ça m\'affecte. La validation des autres confirme que ce que je fais vaut quelque chose.', de: 'Es betrifft mich. Die Bestätigung der anderen bestätigt, dass das, was ich tue, es wert ist.', it: 'Mi colpisce. La validazione degli altri conferma che quello che faccio vale.', pt: 'Me afeta. A validação dos outros confirma que o que faço vale.' }, dimension: 'A' },
      { text: { es: 'Nada. Publiqué porque quería compartir, no para recibir likes.', en: 'Nothing. I posted because I wanted to share, not to receive likes.', fr: 'Rien. J\'ai publié parce que je voulais partager, pas pour recevoir des likes.', de: 'Nichts. Ich habe gepostet, weil ich teilen wollte, nicht um Likes zu bekommen.', it: 'Niente. Ho pubblicato perché volevo condividere, non per ricevere like.', pt: 'Nada. Publiquei porque queria compartilhar, não para receber curtidas.' }, dimension: 'I' },
      { text: { es: 'Me recuerda que publicar para recibir validación no es lo que quiero.', en: 'It reminds me that posting for validation is not what I want.', fr: 'Ça me rappelle que publier pour recevoir de la validation n\'est pas ce que je veux.', de: 'Es erinnert mich daran, dass das Posten für Bestätigung nicht das ist, was ich will.', it: 'Mi ricorda che pubblicare per ricevere validazione non è quello che voglio.', pt: 'Me lembra que publicar para receber validação não é o que quero.' }, dimension: 'A2' },
    ] },
    { id: 3, situation: { es: 'Tomas una decisión importante. Tus amigos más cercanos están en desacuerdo.', en: 'You make an important decision. Your closest friends disagree.', fr: 'Tu prends une décision importante. Tes amis les plus proches ne sont pas d\'accord.', de: 'Du triffst eine wichtige Entscheidung. Deine engsten Freunde sind nicht einverstanden.', it: 'Prendi una decisione importante. I tuoi amici più stretti non sono d\'accordo.', pt: 'Você toma uma decisão importante. Seus amigos mais próximos discordam.' }, options: [
      { text: { es: 'Me genera mucha duda. Si todos me dicen lo mismo, quizás tienen razón.', en: 'It creates a lot of doubt for me. If everyone tells me the same thing, maybe they\'re right.', fr: 'Ça me génère beaucoup de doute. Si tout le monde me dit la même chose, peut-être qu\'ils ont raison.', de: 'Es erzeugt viel Zweifel bei mir. Wenn alle mir dasselbe sagen, haben sie vielleicht recht.', it: 'Mi genera molta incertezza. Se tutti mi dicono la stessa cosa, forse hanno ragione.', pt: 'Me gera muita dúvida. Se todos me dizem a mesma coisa, talvez tenham razão.' }, dimension: 'Q' },
      { text: { es: 'Necesito entender por qué no están de acuerdo antes de proceder.', en: 'I need to understand why they disagree before proceeding.', fr: 'J\'ai besoin de comprendre pourquoi ils ne sont pas d\'accord avant de procéder.', de: 'Ich muss verstehen, warum sie nicht einverstanden sind, bevor ich fortfahre.', it: 'Ho bisogno di capire perché non sono d\'accordo prima di procedere.', pt: 'Preciso entender por que discordam antes de prosseguir.' }, dimension: 'A' },
      { text: { es: 'Escucho sus perspectivas, pero la decisión final es mía.', en: 'I listen to their perspectives, but the final decision is mine.', fr: 'J\'écoute leurs perspectives, mais la décision finale est la mienne.', de: 'Ich höre ihre Perspektiven, aber die endgültige Entscheidung liegt bei mir.', it: 'Ascolto le loro prospettive, ma la decisione finale è mia.', pt: 'Ouço as perspectivas deles, mas a decisão final é minha.' }, dimension: 'I' },
      { text: { es: 'El desacuerdo ajeno no cambia lo que sé que es correcto para mí.', en: 'The disagreement of others doesn\'t change what I know is right for me.', fr: 'Le désaccord des autres ne change pas ce que je sais être juste pour moi.', de: 'Die Meinungsverschiedenheit anderer ändert nichts daran, was ich weiß, dass es für mich richtig ist.', it: 'Il disaccordo altrui non cambia quello che so essere giusto per me.', pt: 'O desacordo alheio não muda o que sei que é certo para mim.' }, dimension: 'A2' },
    ] },
    { id: 4, situation: { es: 'Alguien que no conoces bien hace un comentario crítico sobre algo de tu vida. ¿Cuánto peso tiene?', en: 'Someone you don\'t know well makes a critical comment about something in your life. How much weight does it carry?', fr: 'Quelqu\'un que tu ne connais pas bien fait un commentaire critique sur quelque chose de ta vie. Combien de poids ça a ?', de: 'Jemand, den du kaum kennst, macht einen kritischen Kommentar über etwas in deinem Leben. Wie viel Gewicht hat das?', it: 'Qualcuno che non conosci bene fa un commento critico su qualcosa della tua vita. Quanto peso ha?', pt: 'Alguém que você não conhece bem faz um comentário crítico sobre algo da sua vida. Quanto peso tem?' }, options: [
      { text: { es: 'Más del que quisiera. No logro ignorarlo fácilmente.', en: 'More than I\'d like. I can\'t ignore it easily.', fr: 'Plus que je ne le voudrais. Je n\'arrive pas à l\'ignorer facilement.', de: 'Mehr als ich möchte. Ich kann es nicht leicht ignorieren.', it: 'Più di quanto vorrei. Non riesco a ignorarlo facilmente.', pt: 'Mais do que gostaria. Não consigo ignorar facilmente.' }, dimension: 'Q' },
      { text: { es: 'Depende de quién sea. Si es alguien respetado, me afecta más.', en: 'Depends on who they are. If they\'re respected, it affects me more.', fr: 'Ça dépend de qui c\'est. Si c\'est quelqu\'un de respecté, ça m\'affecte plus.', de: 'Hängt davon ab, wer es ist. Wenn sie respektiert werden, betrifft es mich mehr.', it: 'Dipende da chi sia. Se è qualcuno rispettato, mi colpisce di più.', pt: 'Depende de quem seja. Se for alguém respeitado, me afeta mais.' }, dimension: 'A' },
      { text: { es: 'Poco. La opinión de alguien que no me conoce tiene información limitada.', en: 'Little. The opinion of someone who doesn\'t know me has limited information.', fr: 'Peu. L\'opinion de quelqu\'un qui ne me connaît pas a une information limitée.', de: 'Wenig. Die Meinung von jemandem, der mich nicht kennt, hat begrenzte Informationen.', it: 'Poco. L\'opinione di qualcuno che non mi conosce ha informazioni limitate.', pt: 'Pouco. A opinião de alguém que não me conhece tem informação limitada.' }, dimension: 'I' },
      { text: { es: 'Ninguno. No he pedido su perspectiva y no la he invitado a mi vida.', en: 'None. I haven\'t asked for their perspective and haven\'t invited it into my life.', fr: 'Aucun. Je n\'ai pas demandé leur perspective et ne l\'ai pas invitée dans ma vie.', de: 'Keines. Ich habe nicht nach ihrer Perspektive gefragt und sie nicht in mein Leben eingeladen.', it: 'Nessuno. Non ho chiesto la loro prospettiva e non l\'ho invitata nella mia vita.', pt: 'Nenhum. Não pedi a perspectiva deles e não os convidei para minha vida.' }, dimension: 'A2' },
    ] },
    { id: 5, situation: { es: 'Tienes un estilo o pasión que es considerada rara o poco cool. ¿Cómo lo manejas?', en: 'You have a style or passion that is considered weird or uncool. How do you handle it?', fr: 'Tu as un style ou une passion qui est considérée comme étrange ou pas cool. Comment le gères-tu ?', de: 'Du hast einen Stil oder eine Leidenschaft, die als seltsam oder uncool gilt. Wie gehst du damit um?', it: 'Hai uno stile o una passione considerata strana o poco cool. Come la gestisci?', pt: 'Você tem um estilo ou paixão que é considerada estranha ou pouco cool. Como você lida com isso?' }, options: [
      { text: { es: 'Lo guardo un poco. No quiero ser el raro del grupo.', en: 'I hide it a bit. I don\'t want to be the weird one in the group.', fr: 'Je le cache un peu. Je ne veux pas être l\'original du groupe.', de: 'Ich halte es ein bisschen verborgen. Ich möchte nicht der Sonderling der Gruppe sein.', it: 'Lo tengo un po\' nascosto. Non voglio essere il tipo strano del gruppo.', pt: 'Escondo um pouco. Não quero ser o esquisito do grupo.' }, dimension: 'Q' },
      { text: { es: 'Lo comparto solo con personas que sé que lo van a recibir bien.', en: 'I share it only with people I know will receive it well.', fr: 'Je le partage uniquement avec des personnes dont je sais qu\'elles le recevront bien.', de: 'Ich teile es nur mit Menschen, von denen ich weiß, dass sie es gut aufnehmen werden.', it: 'Lo condivido solo con persone che so che lo recepiranno bene.', pt: 'Compartilho apenas com pessoas que sei que vão receber bem.' }, dimension: 'A' },
      { text: { es: 'Lo vivo con naturalidad. Si es raro, que sea raro.', en: 'I live it naturally. If it\'s weird, let it be weird.', fr: 'Je le vis naturellement. Si c\'est bizarre, que ce soit bizarre.', de: 'Ich lebe es natürlich. Wenn es seltsam ist, soll es seltsam sein.', it: 'Lo vivo con naturalezza. Se è strano, che sia strano.', pt: 'Vivo com naturalidade. Se é estranho, que seja estranho.' }, dimension: 'I' },
      { text: { es: 'Lo comparto abiertamente. Es parte de quien soy y no necesito aprobación para eso.', en: 'I share it openly. It\'s part of who I am and I don\'t need approval for that.', fr: 'Je le partage ouvertement. Ça fait partie de qui je suis et je n\'ai pas besoin d\'approbation pour ça.', de: 'Ich teile es offen. Es ist Teil davon, wer ich bin, und ich brauche dafür keine Zustimmung.', it: 'Lo condivido apertamente. È parte di chi sono e non ho bisogno di approvazione per questo.', pt: 'Compartilho abertamente. É parte de quem sou e não preciso de aprovação para isso.' }, dimension: 'A2' },
    ] },
    { id: 6, situation: { es: '¿Cuánto cambia tu comportamiento según quién te esté observando?', en: 'How much does your behavior change depending on who is watching you?', fr: 'Combien ton comportement change-t-il selon qui t\'observe ?', de: 'Wie sehr ändert sich dein Verhalten, je nachdem, wer dich beobachtet?', it: 'Quanto cambia il tuo comportamento in base a chi ti sta osservando?', pt: 'Quanto o seu comportamento muda dependendo de quem está te observando?' }, options: [
      { text: { es: 'Bastante. Ajusto mi forma de hablar, actuar y presentarme según el público.', en: 'Quite a bit. I adjust how I talk, act, and present myself based on the audience.', fr: 'Pas mal. J\'ajuste ma façon de parler, d\'agir et de me présenter selon le public.', de: 'Ziemlich. Ich passe an, wie ich spreche, handele und mich präsentiere, je nach Publikum.', it: 'Abbastanza. Adatto il modo di parlare, agire e presentarmi in base al pubblico.', pt: 'Bastante. Ajusto como falo, ajo e me apresento baseado no público.' }, dimension: 'Q' },
      { text: { es: 'Algo. Todos lo hacemos para encajar mejor en distintos contextos.', en: 'A bit. We all do it to fit better in different contexts.', fr: 'Un peu. Nous le faisons tous pour mieux s\'intégrer dans différents contextes.', de: 'Etwas. Wir alle tun es, um besser in verschiedene Kontexte zu passen.', it: 'Qualcosa. Lo facciamo tutti per adattarci meglio a diversi contesti.', pt: 'Algo. Todos fazemos isso para nos encaixar melhor em diferentes contextos.' }, dimension: 'A' },
      { text: { es: 'Muy poco. Soy esencialmente la misma persona en todos los contextos.', en: 'Very little. I\'m essentially the same person in all contexts.', fr: 'Très peu. Je suis essentiellement la même personne dans tous les contextes.', de: 'Sehr wenig. Ich bin im Wesentlichen dieselbe Person in allen Kontexten.', it: 'Molto poco. Sono essenzialmente la stessa persona in tutti i contesti.', pt: 'Muito pouco. Sou essencialmente a mesma pessoa em todos os contextos.' }, dimension: 'I' },
      { text: { es: 'No. Si alguien no me acepta como soy, el problema no es mío.', en: 'No. If someone doesn\'t accept me as I am, the problem isn\'t mine.', fr: 'Non. Si quelqu\'un ne m\'accepte pas comme je suis, le problème n\'est pas le mien.', de: 'Nein. Wenn jemand mich nicht so akzeptiert, wie ich bin, ist das Problem nicht meins.', it: 'No. Se qualcuno non mi accetta come sono, il problema non è mio.', pt: 'Não. Se alguém não me aceita como sou, o problema não é meu.' }, dimension: 'A2' },
    ] },
    { id: 7, situation: { es: 'Alguien te pide algo que no quieres hacer. ¿Qué tan difícil te resulta decir que no?', en: 'Someone asks you to do something you don\'t want to do. How hard is it for you to say no?', fr: 'Quelqu\'un te demande quelque chose que tu ne veux pas faire. À quel point est-ce difficile pour toi de dire non ?', de: 'Jemand bittet dich, etwas zu tun, das du nicht tun möchtest. Wie schwer fällt es dir, nein zu sagen?', it: 'Qualcuno ti chiede qualcosa che non vuoi fare. Quanto è difficile per te dire no?', pt: 'Alguém te pede algo que você não quer fazer. Quão difícil é para você dizer não?' }, options: [
      { text: { es: 'Muy difícil. Me preocupa que piensen mal de mí o que se desilusionen.', en: 'Very hard. I worry they\'ll think badly of me or be disappointed.', fr: 'Très difficile. Je m\'inquiète qu\'ils pensent mal de moi ou soient déçus.', de: 'Sehr schwer. Ich mache mir Sorgen, dass sie schlecht über mich denken oder enttäuscht sind.', it: 'Molto difficile. Mi preoccupo che pensino male di me o che rimangano delusi.', pt: 'Muito difícil. Me preocupo que pensem mal de mim ou que fiquem desapontados.' }, dimension: 'Q' },
      { text: { es: 'Difícil. No quiero perder su aprobación o que cambien su imagen de mí.', en: 'Hard. I don\'t want to lose their approval or have them change their image of me.', fr: 'Difficile. Je ne veux pas perdre leur approbation ou qu\'ils changent l\'image qu\'ils ont de moi.', de: 'Schwer. Ich möchte nicht ihre Zustimmung verlieren oder dass sich ihr Bild von mir ändert.', it: 'Difficile. Non voglio perdere la loro approvazione o che cambino la loro immagine di me.', pt: 'Difícil. Não quero perder a aprovação deles ou que mudem a imagem que têm de mim.' }, dimension: 'A' },
      { text: { es: 'No especialmente difícil. El no es una respuesta válida sin necesitar justificación.', en: 'Not especially hard. No is a valid answer without needing justification.', fr: 'Pas particulièrement difficile. Non est une réponse valide sans avoir besoin de justification.', de: 'Nicht besonders schwer. Nein ist eine gültige Antwort, ohne Rechtfertigung zu benötigen.', it: 'Non particolarmente difficile. No è una risposta valida senza bisogno di giustificazione.', pt: 'Não especialmente difícil. Não é uma resposta válida sem precisar de justificação.' }, dimension: 'I' },
      { text: { es: 'Fácil. Prefiero el malestar de un no honesto que el de un sí que no quiero dar.', en: 'Easy. I prefer the discomfort of an honest no over the discomfort of a yes I don\'t want to give.', fr: 'Facile. Je préfère l\'inconfort d\'un non honnête à celui d\'un oui que je ne veux pas donner.', de: 'Einfach. Ich bevorzuge das Unbehagen eines ehrlichen Neins gegenüber dem Unbehagen eines Jas, das ich nicht geben möchte.', it: 'Facile. Preferisco il disagio di un no onesto a quello di un sì che non voglio dare.', pt: 'Fácil. Prefiro o desconforto de um não honesto ao de um sim que não quero dar.' }, dimension: 'A2' },
    ] },
    { id: 8, situation: { es: 'Tu estilo de vida es diferente al de tu familia. ¿Cómo navegas eso?', en: 'Your lifestyle is different from your family\'s. How do you navigate that?', fr: 'Ton style de vie est différent de celui de ta famille. Comment navigues-tu ça ?', de: 'Dein Lebensstil unterscheidet sich von dem deiner Familie. Wie navigierst du das?', it: 'Il tuo stile di vita è diverso da quello della tua famiglia. Come lo navighi?', pt: 'Seu estilo de vida é diferente do da sua família. Como você navega isso?' }, options: [
      { text: { es: 'Con mucha tensión. Me cuesta que no aprueben mis decisiones.', en: 'With a lot of tension. It\'s hard for me that they don\'t approve of my decisions.', fr: 'Avec beaucoup de tension. Il m\'est difficile qu\'ils n\'approuvent pas mes décisions.', de: 'Mit viel Spannung. Es fällt mir schwer, dass sie meine Entscheidungen nicht billigen.', it: 'Con molta tensione. Mi costa che non approvino le mie decisioni.', pt: 'Com muita tensão. Me custa que não aprovem minhas decisões.' }, dimension: 'Q' },
      { text: { es: 'Busco su comprensión aunque no espero su aprobación total.', en: 'I seek their understanding even though I don\'t expect their full approval.', fr: 'Je cherche leur compréhension même si je n\'attends pas leur approbation totale.', de: 'Ich suche ihr Verständnis, auch wenn ich nicht ihre volle Zustimmung erwarte.', it: 'Cerco la loro comprensione anche se non mi aspetto la loro approvazione totale.', pt: 'Busco a compreensão deles mesmo que não espere aprovação total.' }, dimension: 'A' },
      { text: { es: 'Vivo mi vida y espero que con el tiempo lo entiendan. Si no, es su proceso.', en: 'I live my life and hope they\'ll understand with time. If not, that\'s their process.', fr: 'Je vis ma vie et j\'espère qu\'avec le temps ils comprendront. Sinon, c\'est leur processus.', de: 'Ich lebe mein Leben und hoffe, dass sie es mit der Zeit verstehen. Wenn nicht, ist das ihr Prozess.', it: 'Vivo la mia vita e spero che con il tempo lo capiscano. Se no, è il loro processo.', pt: 'Vivo minha vida e espero que com o tempo entendam. Se não, é o processo deles.' }, dimension: 'I' },
      { text: { es: 'Con claridad. Ellos tienen su vida y yo la mía. El amor puede coexistir con la diferencia.', en: 'With clarity. They have their life and I have mine. Love can coexist with difference.', fr: 'Avec clarté. Ils ont leur vie et j\'ai la mienne. L\'amour peut coexister avec la différence.', de: 'Mit Klarheit. Sie haben ihr Leben und ich habe meins. Liebe kann mit Unterschieden koexistieren.', it: 'Con chiarezza. Loro hanno la loro vita e io la mia. L\'amore può coesistere con la differenza.', pt: 'Com clareza. Eles têm a vida deles e eu tenho a minha. O amor pode coexistir com a diferença.' }, dimension: 'A2' },
    ] },
    { id: 9, situation: { es: '¿Qué tanto influye lo que "se supone" que deberías hacer en tus decisiones reales?', en: 'How much does what you "should" do influence your real decisions?', fr: 'Dans quelle mesure ce que tu "devrais" faire influence-t-il tes vraies décisions ?', de: 'Wie sehr beeinflusst das, was du "solltest", deine tatsächlichen Entscheidungen?', it: 'Quanto influisce quello che "dovresti" fare nelle tue decisioni reali?', pt: 'Quanto o que você "deveria" fazer influencia suas decisões reais?' }, options: [
      { text: { es: 'Bastante. Las expectativas sociales tienen un peso real en cómo planifico mi vida.', en: 'Quite a bit. Social expectations have a real weight in how I plan my life.', fr: 'Pas mal. Les attentes sociales ont un poids réel dans la façon dont je planifie ma vie.', de: 'Ziemlich. Soziale Erwartungen haben ein reales Gewicht darin, wie ich mein Leben plane.', it: 'Abbastanza. Le aspettative sociali hanno un peso reale nel modo in cui planifico la mia vita.', pt: 'Bastante. As expectativas sociais têm um peso real em como planeio minha vida.' }, dimension: 'Q' },
      { text: { es: 'Algo. Prefiero decisiones que el entorno pueda comprender y validar.', en: 'Something. I prefer decisions that the environment can understand and validate.', fr: 'Quelque chose. Je préfère des décisions que l\'environnement peut comprendre et valider.', de: 'Etwas. Ich bevorzuge Entscheidungen, die das Umfeld verstehen und bestätigen kann.', it: 'Qualcosa. Preferisco decisioni che l\'ambiente possa capire e validare.', pt: 'Algo. Prefiro decisões que o ambiente possa compreender e validar.' }, dimension: 'A' },
      { text: { es: 'Poco. Lo que "se supone" es el promedio de las expectativas ajenas. No me interesa.', en: 'Little. What "should" be is the average of others\' expectations. That doesn\'t interest me.', fr: 'Peu. Ce qui est "censé être" est la moyenne des attentes des autres. Ça ne m\'intéresse pas.', de: 'Wenig. Was "sein sollte" ist der Durchschnitt der Erwartungen anderer. Das interessiert mich nicht.', it: 'Poco. Quello che "si suppone" è la media delle aspettative altrui. Non mi interessa.', pt: 'Pouco. O que "se supõe" é a média das expectativas alheias. Não me interessa.' }, dimension: 'I' },
      { text: { es: 'Nada. Vivo según lo que tiene sentido para mí, no según el guión social.', en: 'Nothing. I live according to what makes sense for me, not according to the social script.', fr: 'Rien. Je vis selon ce qui a du sens pour moi, pas selon le scénario social.', de: 'Nichts. Ich lebe nach dem, was für mich Sinn ergibt, nicht nach dem sozialen Drehbuch.', it: 'Niente. Vivo secondo quello che ha senso per me, non secondo il copione sociale.', pt: 'Nada. Vivo segundo o que faz sentido para mim, não segundo o roteiro social.' }, dimension: 'A2' },
    ] },
    { id: 10, situation: { es: 'Imagina que nadie supiera nada de lo que haces ni lo juzgara. ¿Cambiaría algo en tu vida?', en: 'Imagine that nobody knew anything about what you do or judged it. Would anything change in your life?', fr: 'Imagine que personne ne sache rien de ce que tu fais ni ne le juge. Quelque chose changerait-il dans ta vie ?', de: 'Stell dir vor, niemand würde etwas über das wissen, was du tust, und es nicht beurteilen. Würde sich etwas in deinem Leben ändern?', it: 'Immagina che nessuno sapesse niente di quello che fai né lo giudicasse. Cambierebbe qualcosa nella tua vita?', pt: 'Imagine que ninguém soubesse nada do que você faz nem o julgasse. Mudaria algo na sua vida?' }, options: [
      { text: { es: 'Bastantes cosas. Hay decisiones que tomé pensando en cómo se verían.', en: 'Quite a few things. There are decisions I made thinking about how they would look.', fr: 'Pas mal de choses. Il y a des décisions que j\'ai prises en pensant à leur apparence.', de: 'Einige Dinge. Es gibt Entscheidungen, die ich getroffen habe und dabei dachte, wie sie aussehen würden.', it: 'Abbastanza cose. Ci sono decisioni che ho preso pensando a come sarebbero apparse.', pt: 'Bastante coisa. Há decisões que tomei pensando em como seriam vistas.' }, dimension: 'Q' },
      { text: { es: 'Algo. Sin la mirada ajena, me permitiría algunas cosas que hoy no me permito.', en: 'Something. Without the gaze of others, I\'d allow myself some things I don\'t allow myself today.', fr: 'Quelque chose. Sans le regard des autres, je me permettrais certaines choses que je ne me permets pas aujourd\'hui.', de: 'Etwas. Ohne den Blick anderer würde ich mir einige Dinge erlauben, die ich mir heute nicht erlaube.', it: 'Qualcosa. Senza lo sguardo altrui, mi permetterei alcune cose che oggi non mi permetto.', pt: 'Algo. Sem o olhar alheio, me permitiria algumas coisas que hoje não me permito.' }, dimension: 'A' },
      { text: { es: 'Poco. Mi vida ya está bastante alineada con lo que quiero, no con lo que se espera.', en: 'Little. My life is already quite aligned with what I want, not with what\'s expected.', fr: 'Peu. Ma vie est déjà assez alignée avec ce que je veux, pas avec ce qui est attendu.', de: 'Wenig. Mein Leben ist bereits ziemlich auf das ausgerichtet, was ich will, nicht auf das, was erwartet wird.', it: 'Poco. La mia vita è già abbastanza allineata con quello che voglio, non con quello che ci si aspetta.', pt: 'Pouco. Minha vida já está bastante alinhada com o que quero, não com o que se espera.' }, dimension: 'I' },
      { text: { es: 'Nada. Vivo de la misma forma que viviría si nadie mirara.', en: 'Nothing. I live the same way I would if nobody was watching.', fr: 'Rien. Je vis de la même façon que je vivrais si personne ne regardait.', de: 'Nichts. Ich lebe auf dieselbe Weise, wie ich es tun würde, wenn niemand zuschauen würde.', it: 'Niente. Vivo allo stesso modo in cui vivrei se nessuno guardasse.', pt: 'Nada. Vivo da mesma forma que viveria se ninguém estivesse olhando.' }, dimension: 'A2' },
    ] },
  ],
  characters: [
    { name: { es: 'El Esclavo del Qué Dirán', en: 'The Slave of What They\'ll Say', fr: 'L\'Esclave du Qu\'en-dira-t-on', de: 'Der Sklave des Was-werden-sie-sagen', it: 'Lo Schiavo del Cosa Diranno', pt: 'O Escravo do O Que Vão Dizer' }, dimensions: ['Q'], photo: '/characters/what-will-they-say.jpg', description: { es: 'Su vida es una serie de decisiones diseñadas para la audiencia.', en: 'Their life is a series of decisions designed for the audience.', fr: 'Sa vie est une série de décisions conçues pour le public.', de: 'Sein/Ihr Leben ist eine Reihe von Entscheidungen, die für das Publikum entwickelt wurden.', it: 'La sua vita è una serie di decisioni progettate per il pubblico.', pt: 'Sua vida é uma série de decisões projetadas para a audiência.' }, philosophy: { es: 'Llevas una vida parcialmente vivida para otros. No por debilidad — sino porque te importan las relaciones y el tejido social. El costo es que a veces no sabes si las decisiones son tuyas o de la audiencia que imaginaste.', en: 'You lead a life partially lived for others. Not out of weakness — but because relationships and the social fabric matter to you. The cost is that sometimes you don\'t know if the decisions are yours or the audience you imagined.', fr: 'Tu mènes une vie partiellement vécue pour les autres. Pas par faiblesse — mais parce que les relations et le tissu social t\'importent. Le coût est que parfois tu ne sais pas si les décisions sont les tiennes ou celles du public que tu as imaginé.', de: 'Du führst ein Leben, das teilweise für andere gelebt wird. Nicht aus Schwäche — sondern weil dir Beziehungen und das soziale Gefüge wichtig sind. Der Preis ist, dass du manchmal nicht weißt, ob die Entscheidungen deine sind oder die des Publikums, das du dir vorgestellt hast.', it: 'Conduci una vita parzialmente vissuta per gli altri. Non per debolezza — ma perché le relazioni e il tessuto sociale ti importano. Il costo è che a volte non sai se le decisioni sono tue o del pubblico che hai immaginato.', pt: 'Você leva uma vida parcialmente vivida para os outros. Não por fraqueza — mas porque as relações e o tecido social importam para você. O custo é que às vezes você não sabe se as decisões são suas ou da audiência que imaginou.' } },
    { name: { es: 'El Buscador de Aprobación', en: 'The Approval Seeker', fr: 'Le Chercheur d\'Approbation', de: 'Der Zustimmungssuchende', it: 'Il Cercatore di Approvazione', pt: 'O Buscador de Aprovação' }, dimensions: ['A'], photo: '/characters/approval-seeker.jpg', description: { es: 'La validación ajena es su combustible.', en: 'The validation of others is their fuel.', fr: 'La validation des autres est son carburant.', de: 'Die Bestätigung anderer ist sein/ihr Treibstoff.', it: 'La validazione altrui è il suo carburante.', pt: 'A validação alheia é seu combustível.' }, philosophy: { es: 'Necesitas que el exterior confirme lo que el interior todavía no está seguro de sostener solo. No es que no tengas valor propio — es que no has aprendido a verlo sin el espejo de los demás.', en: 'You need the outside to confirm what the inside isn\'t yet sure it can hold alone. It\'s not that you have no self-worth — it\'s that you haven\'t learned to see it without the mirror of others.', fr: 'Tu as besoin que l\'extérieur confirme ce que l\'intérieur n\'est pas encore sûr de soutenir seul. Ce n\'est pas que tu n\'as pas de valeur propre — c\'est que tu n\'as pas appris à la voir sans le miroir des autres.', de: 'Du brauchst, dass das Äußere bestätigt, was das Innere noch nicht sicher ist, allein zu tragen. Es ist nicht so, dass du keinen Eigenwert hast — es ist so, dass du es nicht gelernt hast, ihn ohne den Spiegel der anderen zu sehen.', it: 'Hai bisogno che l\'esterno confermi quello che l\'interno non è ancora sicuro di sostenere da solo. Non è che non hai valore proprio — è che non hai imparato a vederlo senza lo specchio degli altri.', pt: 'Você precisa que o exterior confirme o que o interior ainda não tem certeza de sustentar sozinho. Não é que você não tenha valor próprio — é que não aprendeu a vê-lo sem o espelho dos outros.' } },
    { name: { es: 'El Independiente Interior', en: 'The Inner Independent', fr: 'L\'Indépendant Intérieur', de: 'Der Innere Unabhängige', it: 'L\'Indipendente Interiore', pt: 'O Independente Interior' }, dimensions: ['I'], photo: '/characters/inner-independent.jpg', description: { es: 'Su brújula es interna. Las opiniones ajenas son información, no veredictos.', en: 'Their compass is internal. The opinions of others are information, not verdicts.', fr: 'Sa boussole est interne. Les opinions des autres sont de l\'information, pas des verdicts.', de: 'Sein/Ihr Kompass ist intern. Die Meinungen anderer sind Informationen, keine Urteile.', it: 'La sua bussola è interna. Le opinioni altrui sono informazioni, non verdetti.', pt: 'Sua bússola é interna. As opiniões alheias são informação, não veredictos.' }, philosophy: { es: 'Has desarrollado una relación sólida con tu propio juicio. Las opiniones ajenas pueden ser útiles — pero no son determinantes. Tu centro no se mueve con cada viento social.', en: 'You\'ve developed a solid relationship with your own judgment. The opinions of others can be useful — but they\'re not decisive. Your center doesn\'t move with every social wind.', fr: 'Tu as développé une relation solide avec ton propre jugement. Les opinions des autres peuvent être utiles — mais elles ne sont pas déterminantes. Ton centre ne se déplace pas avec chaque vent social.', de: 'Du hast eine solide Beziehung zu deinem eigenen Urteil entwickelt. Die Meinungen anderer können nützlich sein — aber sie sind nicht entscheidend. Dein Zentrum bewegt sich nicht mit jedem sozialen Wind.', it: 'Hai sviluppato una relazione solida con il tuo giudizio. Le opinioni altrui possono essere utili — ma non sono determinanti. Il tuo centro non si muove con ogni vento sociale.', pt: 'Você desenvolveu uma relação sólida com o seu próprio julgamento. As opiniões alheias podem ser úteis — mas não são determinantes. Seu centro não se move com cada vento social.' } },
    { name: { es: 'El Auténtico Radical', en: 'The Radical Authentic', fr: 'L\'Authentique Radical', de: 'Der Radikal Authentische', it: 'L\'Autentico Radicale', pt: 'O Autêntico Radical' }, dimensions: ['A2'], photo: '/characters/radical-authentic.jpg', description: { es: 'Vive en sus propios términos sin disculparse.', en: 'Lives on their own terms without apologizing.', fr: 'Vit selon ses propres termes sans s\'excuser.', de: 'Lebt zu seinen eigenen Bedingungen ohne sich zu entschuldigen.', it: 'Vive secondo i propri termini senza scusarsi.', pt: 'Vive em seus próprios termos sem se desculpar.' }, philosophy: { es: 'Para ti, la autenticidad no es un valor abstracto — es una práctica diaria. Vives de la misma forma que vivirías si nadie estuviera mirando, porque esa es la única forma de vivir que te parece real.', en: 'For you, authenticity is not an abstract value — it\'s a daily practice. You live the same way you would if nobody was watching, because that\'s the only way of living that seems real to you.', fr: 'Pour toi, l\'authenticité n\'est pas une valeur abstraite — c\'est une pratique quotidienne. Tu vis de la même façon que tu vivrais si personne ne regardait, parce que c\'est la seule façon de vivre qui te semble réelle.', de: 'Für dich ist Authentizität kein abstrakter Wert — es ist eine tägliche Praxis. Du lebst auf dieselbe Weise, wie du es tun würdest, wenn niemand zuschauen würde, weil das die einzige Lebensweise ist, die dir real erscheint.', it: 'Per te, l\'autenticità non è un valore astratto — è una pratica quotidiana. Vivi allo stesso modo in cui vivresti se nessuno stesse guardando, perché è l\'unico modo di vivere che ti sembra reale.', pt: 'Para você, a autenticidade não é um valor abstrato — é uma prática diária. Você vive da mesma forma que viveria se ninguém estivesse olhando, porque essa é a única forma de viver que parece real para você.' } },
    { name: { es: 'El Conformista Atrapado', en: 'The Trapped Conformist', fr: 'Le Conformiste Piégé', de: 'Der Gefangene Konformist', it: 'Il Conformista Intrappolato', pt: 'O Conformista Preso' }, dimensions: ['Q', 'A'], photo: '/characters/trapped-conformist.jpg', description: { es: 'Vive para la audiencia y necesita que la aplauda.', en: 'Lives for the audience and needs it to applaud.', fr: 'Vit pour le public et a besoin qu\'il l\'applaudisse.', de: 'Lebt für das Publikum und braucht dessen Applaus.', it: 'Vive per il pubblico e ha bisogno che lo applaudisca.', pt: 'Vive para a audiência e precisa que ela aplauda.' }, philosophy: { es: 'Estás en una doble trampa: te importa qué dicen y también necesitas que lo que dicen sea positivo. Cada decisión pasa por dos filtros externos antes de ser tuya. Hay mucho de ti que nadie ha visto todavía.', en: 'You\'re in a double trap: you care about what they say and also need what they say to be positive. Every decision passes through two external filters before becoming yours. There\'s much of you that nobody has seen yet.', fr: 'Tu es dans un double piège : tu te soucies de ce qu\'ils disent et tu as aussi besoin que ce qu\'ils disent soit positif. Chaque décision passe par deux filtres externes avant d\'être la tienne. Il y a beaucoup de toi que personne n\'a encore vu.', de: 'Du steckst in einer Doppelfalle: Es ist dir wichtig, was sie sagen, und du brauchst auch, dass das, was sie sagen, positiv ist. Jede Entscheidung durchläuft zwei externe Filter, bevor sie deine ist. Es gibt viel von dir, das noch niemand gesehen hat.', it: 'Sei in una doppia trappola: ti importa quello che dicono e hai anche bisogno che quello che dicono sia positivo. Ogni decisione passa attraverso due filtri esterni prima di essere tua. C\'è molto di te che nessuno ha ancora visto.', pt: 'Você está em uma dupla armadilha: importa-se com o que dizem e também precisa que o que dizem seja positivo. Cada decisão passa por dois filtros externos antes de ser sua. Há muito de você que ninguém ainda viu.' } },
    { name: { es: 'El Libre con Tacto', en: 'The Free with Tact', fr: 'Le Libre avec Tact', de: 'Der Freie mit Takt', it: 'Il Libero con Tatto', pt: 'O Livre com Tato' }, dimensions: ['I', 'A'], photo: '/characters/free-with-tact.jpg', description: { es: 'Independiente, pero no indiferente a cómo lo perciben.', en: 'Independent, but not indifferent to how they\'re perceived.', fr: 'Indépendant(e), mais pas indifférent(e) à la façon dont ils sont perçus.', de: 'Unabhängig, aber nicht gleichgültig gegenüber der eigenen Wahrnehmung.', it: 'Indipendente, ma non indifferente a come viene percepito/a.', pt: 'Independente, mas não indiferente a como é percebido/a.' }, philosophy: { es: 'Vives desde tu propio centro pero no eres indiferente a las relaciones. Puedes decir no, puedes vivir diferente — y también te importa mantener conexiones. No son incompatibles.', en: 'You live from your own center but you\'re not indifferent to relationships. You can say no, you can live differently — and maintaining connections still matters to you. They\'re not incompatible.', fr: 'Tu vis depuis ton propre centre mais tu n\'es pas indifférent(e) aux relations. Tu peux dire non, tu peux vivre différemment — et maintenir des connexions t\'importe aussi. Ce ne sont pas des choses incompatibles.', de: 'Du lebst aus deiner eigenen Mitte heraus, aber du bist nicht gleichgültig gegenüber Beziehungen. Du kannst nein sagen, du kannst anders leben — und es ist dir auch wichtig, Verbindungen aufrechtzuerhalten. Das schließt sich nicht aus.', it: 'Vivi dal tuo centro ma non sei indifferente alle relazioni. Puoi dire no, puoi vivere diversamente — e mantenere le connessioni ti importa ancora. Non sono incompatibili.', pt: 'Você vive a partir do seu próprio centro mas não é indiferente às relações. Pode dizer não, pode viver diferente — e manter conexões ainda importa para você. Não são incompatíveis.' } },
    { name: { es: 'El Auténtico en Proceso', en: 'The Authentic in Progress', fr: 'L\'Authentique en Processus', de: 'Der Authentische im Prozess', it: 'L\'Autentico in Progressione', pt: 'O Autêntico em Processo' }, dimensions: ['Q', 'A2'], photo: '/characters/authentic-in-progress.jpg', description: { es: 'Quiere ser auténtico pero todavía lucha con las expectativas.', en: 'Wants to be authentic but still struggles with expectations.', fr: 'Veut être authentique mais lutte encore avec les attentes.', de: 'Möchte authentisch sein, kämpft aber noch mit Erwartungen.', it: 'Vuole essere autentico/a ma lotta ancora con le aspettative.', pt: 'Quer ser autêntico/a mas ainda luta com as expectativas.' }, philosophy: { es: 'Valoras la autenticidad y todavía te pesa el qué dirán. Esa tensión es el espacio donde ocurre el cambio. Cada vez que eliges lo auténtico sobre lo esperado, el músculo de la independencia crece.', en: 'You value authenticity and the "what will they say" still weighs on you. That tension is the space where change happens. Each time you choose authenticity over what\'s expected, the independence muscle grows.', fr: 'Tu valorises l\'authenticité et le "qu\'en dira-t-on" pèse encore sur toi. Cette tension est l\'espace où le changement se produit. Chaque fois que tu choisis l\'authentique sur ce qui est attendu, le muscle de l\'indépendance grandit.', de: 'Du schätzt Authentizität und "was werden sie sagen" belastet dich noch. Diese Spannung ist der Raum, in dem Veränderung stattfindet. Jedes Mal, wenn du das Authentische über das Erwartete wählst, wächst der Unabhängigkeitsmuskel.', it: 'Valorizzi l\'autenticità e il "cosa diranno" pesa ancora su di te. Quella tensione è lo spazio in cui avviene il cambiamento. Ogni volta che scegli l\'autentico sull\'atteso, il muscolo dell\'indipendenza cresce.', pt: 'Você valoriza a autenticidade e o "o que vão dizer" ainda pesa sobre você. Essa tensão é o espaço onde a mudança acontece. Cada vez que você escolhe o autêntico sobre o esperado, o músculo da independência cresce.' } },
    { name: { es: 'El Auténtico Libre', en: 'The Authentically Free', fr: 'L\'Authentiquement Libre', de: 'Der Authentisch Freie', it: 'L\'Autenticamente Libero', pt: 'O Autenticamente Livre' }, dimensions: ['I', 'A2'], photo: '/characters/authentic-free.jpg', description: { es: 'Independiente y auténtico. La combinación más difícil de mantener.', en: 'Independent and authentic. The hardest combination to maintain.', fr: 'Indépendant(e) et authentique. La combinaison la plus difficile à maintenir.', de: 'Unabhängig und authentisch. Die schwierigste Kombination, die es aufrechtzuerhalten gilt.', it: 'Indipendente e autentico/a. La combinazione più difficile da mantenere.', pt: 'Independente e autêntico/a. A combinação mais difícil de manter.' }, philosophy: { es: 'Vives según tu propio diseño, sin necesitar permiso ni validación para hacerlo. Eso no significa que no te importen las personas — significa que tu bienestar no depende de su aprobación. Es una forma de libertad que se construye, no se hereda.', en: 'You live according to your own design, without needing permission or validation to do so. That doesn\'t mean people don\'t matter to you — it means your wellbeing doesn\'t depend on their approval. It\'s a form of freedom that is built, not inherited.', fr: 'Tu vis selon ton propre design, sans avoir besoin de permission ni de validation pour le faire. Ça ne veut pas dire que les gens ne t\'importent pas — ça veut dire que ton bien-être ne dépend pas de leur approbation. C\'est une forme de liberté qui se construit, pas qui s\'hérite.', de: 'Du lebst nach deinem eigenen Design, ohne Erlaubnis oder Bestätigung zu benötigen. Das bedeutet nicht, dass dir die Menschen egal sind — es bedeutet, dass dein Wohlbefinden nicht von ihrer Zustimmung abhängt. Es ist eine Form der Freiheit, die aufgebaut, nicht geerbt wird.', it: 'Vivi secondo il tuo design, senza aver bisogno di permesso né di validazione per farlo. Questo non significa che le persone non ti importino — significa che il tuo benessere non dipende dalla loro approvazione. È una forma di libertà che si costruisce, non si eredita.', pt: 'Você vive segundo o seu próprio design, sem precisar de permissão ou validação para fazê-lo. Isso não significa que as pessoas não importam para você — significa que seu bem-estar não depende da aprovação delas. É uma forma de liberdade que se constrói, não se herda.' } },
  ],
};

export async function seedPeoplePleaser(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'people-pleaser' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'people-pleaser',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['lifestyle'],
      sortOrder: 6,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
