import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan boomer eres?', en: 'How boomer are you?', fr: 'À quel point es-tu boomer ?', de: 'Wie sehr bist du ein Boomer?', it: 'Quanto sei boomer?', pt: 'O quanto você é boomer?' },
  description: { es: 'El boomerismo no es de edad — es de mentalidad. ¿Cuánto hay en la tuya?', en: 'Boomerness is not about age — it\'s about mindset. How much is in yours?', fr: 'Le boomerisme n\'est pas une question d\'âge — c\'est une question de mentalité. Combien y en a-t-il dans la tienne ?', de: 'Boomer-Sein ist keine Altersfrage — es ist eine Frage der Einstellung. Wie viel steckt in dir?', it: 'Il boomerismo non è questione di età — è di mentalità. Quanto ce n\'è nella tua?', pt: 'O boomerismo não é de idade — é de mentalidade. Quanto há na sua?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Atemporal' },
    en: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Timeless' },
    fr: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Intemporel' },
    de: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Zeitlos' },
    it: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Atemporale' },
    pt: { B: 'Boomer', M: 'Millennial', Z: 'Gen Z', A: 'Atemporal' },
  },
  questions: [
    { id: 1, situation: { es: 'Alguien de la generación siguiente se queja de que el mundo es difícil.', en: 'Someone from the next generation complains that the world is hard.', fr: 'Quelqu\'un de la génération suivante se plaint que le monde est difficile.', de: 'Jemand aus der nächsten Generation beklagt sich, dass die Welt schwer ist.', it: 'Qualcuno della generazione successiva si lamenta che il mondo è difficile.', pt: 'Alguém da geração seguinte reclama que o mundo é difícil.' }, options: [
      { text: { es: 'En mi época también era difícil y nadie se quejaba tanto.', en: 'In my day it was also hard and nobody complained so much.', fr: 'À mon époque c\'était aussi difficile et personne ne se plaignait autant.', de: 'Zu meiner Zeit war es auch schwer und niemand hat so viel geklagt.', it: 'Ai miei tempi era anche difficile e nessuno si lamentava tanto.', pt: 'Na minha época também era difícil e ninguém reclamava tanto.' }, dimension: 'B' },
      { text: { es: 'Es cierto, pero también hay que saber aprovechar las oportunidades que existen.', en: 'True, but you also need to know how to take advantage of the opportunities that exist.', fr: 'C\'est vrai, mais il faut aussi savoir profiter des opportunités qui existent.', de: 'Stimmt, aber man muss auch die vorhandenen Chancen nutzen können.', it: 'È vero, ma bisogna anche saper sfruttare le opportunità che esistono.', pt: 'É verdade, mas também é preciso saber aproveitar as oportunidades que existem.' }, dimension: 'M' },
      { text: { es: 'El mundo es objetivamente más difícil para las nuevas generaciones en muchos aspectos.', en: 'The world is objectively harder for new generations in many ways.', fr: 'Le monde est objectivement plus difficile pour les nouvelles générations à bien des égards.', de: 'Die Welt ist für neue Generationen in vielerlei Hinsicht objektiv schwieriger.', it: 'Il mondo è oggettivamente più difficile per le nuove generazioni sotto molti aspetti.', pt: 'O mundo é objetivamente mais difícil para as novas gerações em muitos aspectos.' }, dimension: 'Z' },
      { text: { es: 'Cada época tiene sus dificultades específicas. Difícilmente comparables.', en: 'Every era has its specific difficulties. Hardly comparable.', fr: 'Chaque époque a ses difficultés spécifiques. Difficilement comparables.', de: 'Jede Epoche hat ihre spezifischen Schwierigkeiten. Kaum vergleichbar.', it: 'Ogni epoca ha le sue difficoltà specifiche. Difficilmente comparabili.', pt: 'Cada época tem suas dificuldades específicas. Dificilmente comparáveis.' }, dimension: 'A' },
    ] },
    { id: 2, situation: { es: 'Ves que los jóvenes de hoy no saben hacer cosas "básicas" como cocinar o arreglar algo en casa.', en: 'You see that today\'s youth don\'t know how to do "basic" things like cooking or fixing something at home.', fr: 'Tu constates que les jeunes d\'aujourd\'hui ne savent pas faire des choses "basiques" comme cuisiner ou réparer quelque chose à la maison.', de: 'Du siehst, dass heutige Jugendliche keine "grundlegenden" Dinge wie Kochen oder Heimreparaturen beherrschen.', it: 'Vedi che i giovani di oggi non sanno fare cose "basiche" come cucinare o aggiustare qualcosa in casa.', pt: 'Você vê que os jovens de hoje não sabem fazer coisas "básicas" como cozinhar ou consertar algo em casa.' }, options: [
      { text: { es: 'Es un problema real. La dependencia tecnológica los hace incapaces.', en: 'It\'s a real problem. Technological dependence makes them incapable.', fr: 'C\'est un problème réel. La dépendance technologique les rend incapables.', de: 'Es ist ein echtes Problem. Technologische Abhängigkeit macht sie unfähig.', it: 'È un problema reale. La dipendenza tecnologica li rende incapaci.', pt: 'É um problema real. A dependência tecnológica os torna incapazes.' }, dimension: 'B' },
      { text: { es: 'Es preocupante, pero se puede remediar cuando la necesidad llegue.', en: 'It\'s concerning, but it can be remedied when necessity comes.', fr: 'C\'est préoccupant, mais ça peut se remédier quand la nécessité se présente.', de: 'Es ist besorgniserregend, aber es kann behoben werden, wenn die Notwendigkeit kommt.', it: 'È preoccupante, ma può essere rimediato quando arriva la necessità.', pt: 'É preocupante, mas pode ser remediado quando a necessidade chegar.' }, dimension: 'M' },
      { text: { es: 'Son habilidades diferentes. Saben hacer cosas que las generaciones anteriores nunca imaginaron.', en: 'They\'re different skills. They know how to do things previous generations never imagined.', fr: 'Ce sont des compétences différentes. Ils savent faire des choses que les générations précédentes n\'auraient jamais imaginées.', de: 'Es sind andere Fähigkeiten. Sie können Dinge, die sich frühere Generationen nie vorgestellt hätten.', it: 'Sono abilità diverse. Sanno fare cose che le generazioni precedenti non avrebbero mai immaginato.', pt: 'São habilidades diferentes. Sabem fazer coisas que as gerações anteriores nunca imaginaram.' }, dimension: 'Z' },
      { text: { es: 'Cada generación desarrolla las habilidades que su contexto requiere.', en: 'Each generation develops the skills their context requires.', fr: 'Chaque génération développe les compétences que son contexte exige.', de: 'Jede Generation entwickelt die Fähigkeiten, die ihr Kontext erfordert.', it: 'Ogni generazione sviluppa le abilità che il suo contesto richiede.', pt: 'Cada geração desenvolve as habilidades que seu contexto exige.' }, dimension: 'A' },
    ] },
    { id: 3, situation: { es: 'Un empleado joven pide trabajo remoto y horario flexible desde el primer día.', en: 'A young employee asks for remote work and flexible hours from day one.', fr: 'Un jeune employé demande le télétravail et des horaires flexibles dès le premier jour.', de: 'Ein junger Mitarbeiter bittet ab dem ersten Tag um Remote-Arbeit und flexible Zeiten.', it: 'Un giovane dipendente chiede lavoro da remoto e orario flessibile dal primo giorno.', pt: 'Um funcionário jovem pede trabalho remoto e horário flexível desde o primeiro dia.' }, options: [
      { text: { es: 'Tiene que ganarse eso. Los derechos se ganan con tiempo y desempeño.', en: 'They have to earn that. Rights are earned with time and performance.', fr: 'Il/elle doit le mériter. Les droits se gagnent avec le temps et les performances.', de: 'Das muss er/sie sich verdienen. Rechte werden durch Zeit und Leistung erworben.', it: 'Deve guadagnarselo. I diritti si guadagnano con il tempo e le prestazioni.', pt: 'Precisa ganhar isso. Os direitos se conquistam com tempo e desempenho.' }, dimension: 'B' },
      { text: { es: 'Depende del rol y de los resultados. La flexibilidad puede coexistir con la responsabilidad.', en: 'Depends on the role and results. Flexibility can coexist with responsibility.', fr: 'Ça dépend du rôle et des résultats. La flexibilité peut coexister avec la responsabilité.', de: 'Hängt von der Rolle und den Ergebnissen ab. Flexibilität kann mit Verantwortung koexistieren.', it: 'Dipende dal ruolo e dai risultati. La flessibilità può coesistere con la responsabilità.', pt: 'Depende do papel e dos resultados. A flexibilidade pode coexistir com a responsabilidade.' }, dimension: 'M' },
      { text: { es: 'Es una demanda legítima y los empleadores que no la entiendan van a perder talento.', en: 'It\'s a legitimate demand and employers who don\'t understand it will lose talent.', fr: 'C\'est une demande légitime et les employeurs qui ne la comprennent pas vont perdre des talents.', de: 'Es ist eine legitime Forderung und Arbeitgeber, die das nicht verstehen, werden Talente verlieren.', it: 'È una richiesta legittima e i datori di lavoro che non la capiscono perderanno talenti.', pt: 'É uma demanda legítima e os empregadores que não entenderem vão perder talentos.' }, dimension: 'Z' },
      { text: { es: 'Depende de la cultura del equipo, el rol y el contrato. No hay una respuesta universal.', en: 'Depends on team culture, the role, and the contract. There\'s no universal answer.', fr: 'Ça dépend de la culture de l\'équipe, du rôle et du contrat. Il n\'y a pas de réponse universelle.', de: 'Hängt von der Teamkultur, der Rolle und dem Vertrag ab. Es gibt keine universelle Antwort.', it: 'Dipende dalla cultura del team, dal ruolo e dal contratto. Non c\'è una risposta universale.', pt: 'Depende da cultura da equipe, do papel e do contrato. Não há uma resposta universal.' }, dimension: 'A' },
    ] },
    { id: 4, situation: { es: 'Las redes sociales y los influencers como trabajo.', en: 'Social media and influencers as a job.', fr: 'Les réseaux sociaux et les influenceurs comme travail.', de: 'Soziale Medien und Influencer als Beruf.', it: 'I social media e gli influencer come lavoro.', pt: 'As redes sociais e os influencers como trabalho.' }, options: [
      { text: { es: 'No es un trabajo de verdad. El trabajo real implica esfuerzo físico o intelectual real.', en: 'It\'s not a real job. Real work involves physical or intellectual effort.', fr: 'Ce n\'est pas un vrai travail. Le vrai travail implique un effort physique ou intellectuel réel.', de: 'Es ist kein echter Job. Echte Arbeit beinhaltet körperliche oder intellektuelle Anstrengung.', it: 'Non è un vero lavoro. Il lavoro vero implica uno sforzo fisico o intellettuale reale.', pt: 'Não é um trabalho de verdade. O trabalho real envolve esforço físico ou intelectual real.' }, dimension: 'B' },
      { text: { es: 'Puede serlo, pero hay mucho que se exagera. El mercado ya lo regulará.', en: 'It can be, but a lot is exaggerated. The market will regulate it.', fr: 'Ça peut l\'être, mais beaucoup de choses sont exagérées. Le marché va le réguler.', de: 'Es kann sein, aber vieles ist übertrieben. Der Markt wird es regulieren.', it: 'Può esserlo, ma c\'è molto che viene esagerato. Il mercato lo regolerà.', pt: 'Pode ser, mas muito é exagerado. O mercado vai regulá-lo.' }, dimension: 'M' },
      { text: { es: 'Es un trabajo como cualquier otro, con sus habilidades y exigencias específicas.', en: 'It\'s a job like any other, with its own skills and specific demands.', fr: 'C\'est un travail comme un autre, avec ses compétences et exigences spécifiques.', de: 'Es ist ein Job wie jeder andere, mit seinen eigenen Fähigkeiten und spezifischen Anforderungen.', it: 'È un lavoro come qualsiasi altro, con le sue abilità e richieste specifiche.', pt: 'É um trabalho como qualquer outro, com suas habilidades e exigências específicas.' }, dimension: 'Z' },
      { text: { es: 'Depende del contenido, el impacto y la sostenibilidad. Como cualquier actividad económica.', en: 'Depends on the content, impact, and sustainability. Like any economic activity.', fr: 'Ça dépend du contenu, de l\'impact et de la durabilité. Comme toute activité économique.', de: 'Hängt von Inhalt, Wirkung und Nachhaltigkeit ab. Wie jede wirtschaftliche Tätigkeit.', it: 'Dipende dal contenuto, dall\'impatto e dalla sostenibilità. Come qualsiasi attività economica.', pt: 'Depende do conteúdo, do impacto e da sustentabilidade. Como qualquer atividade econômica.' }, dimension: 'A' },
    ] },
    { id: 5, situation: { es: 'La salud mental como tema de conversación frecuente entre jóvenes.', en: 'Mental health as a frequent conversation topic among young people.', fr: 'La santé mentale comme sujet de conversation fréquent chez les jeunes.', de: 'Psychische Gesundheit als häufiges Gesprächsthema unter Jugendlichen.', it: 'La salute mentale come argomento di conversazione frequente tra i giovani.', pt: 'A saúde mental como tema de conversa frequente entre jovens.' }, options: [
      { text: { es: 'En mi época también había problemas pero nadie hacía tanto show.', en: 'In my day there were problems too but nobody made such a show.', fr: 'À mon époque il y avait aussi des problèmes mais personne ne faisait autant de spectacle.', de: 'Zu meiner Zeit gab es auch Probleme, aber niemand hat so ein Theater gemacht.', it: 'Ai miei tempi c\'erano anche problemi ma nessuno faceva tanto spettacolo.', pt: 'Na minha época também havia problemas mas ninguém fazia tanto espetáculo.' }, dimension: 'B' },
      { text: { es: 'Es importante hablarlo, aunque a veces se lleva a extremos que no ayudan.', en: 'It\'s important to talk about it, although sometimes it\'s taken to extremes that don\'t help.', fr: 'C\'est important d\'en parler, même si parfois c\'est poussé à des extrêmes qui n\'aident pas.', de: 'Es ist wichtig, darüber zu sprechen, obwohl es manchmal zu Extremen geführt wird, die nicht helfen.', it: 'È importante parlarne, anche se a volte viene portato a estremi che non aiutano.', pt: 'É importante falar sobre isso, embora às vezes seja levado a extremos que não ajudam.' }, dimension: 'M' },
      { text: { es: 'La normalización del tema es un avance real. El silencio anterior causó mucho daño.', en: 'Normalizing the topic is real progress. Previous silence caused much harm.', fr: 'La normalisation du sujet est une vraie avancée. Le silence précédent a causé beaucoup de dommages.', de: 'Die Normalisierung des Themas ist echter Fortschritt. Das vorherige Schweigen hat viel Schaden angerichtet.', it: 'La normalizzazione del tema è un vero progresso. Il silenzio precedente ha causato molto danno.', pt: 'A normalização do tema é um avanço real. O silêncio anterior causou muito dano.' }, dimension: 'Z' },
      { text: { es: 'La salud mental siempre fue importante. Ahora hay más lenguaje para hablar de ello.', en: 'Mental health has always been important. Now there\'s more language to talk about it.', fr: 'La santé mentale a toujours été importante. Maintenant il y a plus de langage pour en parler.', de: 'Psychische Gesundheit war schon immer wichtig. Jetzt gibt es mehr Sprache, um darüber zu sprechen.', it: 'La salute mentale è sempre stata importante. Ora c\'è più linguaggio per parlarne.', pt: 'A saúde mental sempre foi importante. Agora há mais linguagem para falar sobre isso.' }, dimension: 'A' },
    ] },
    { id: 6, situation: { es: 'Alguien dice que el amor romántico es una construcción social que no funciona.', en: 'Someone says romantic love is a social construct that doesn\'t work.', fr: 'Quelqu\'un dit que l\'amour romantique est une construction sociale qui ne fonctionne pas.', de: 'Jemand sagt, romantische Liebe sei ein soziales Konstrukt, das nicht funktioniert.', it: 'Qualcuno dice che l\'amore romantico è una costruzione sociale che non funziona.', pt: 'Alguém diz que o amor romântico é uma construção social que não funciona.' }, options: [
      { text: { es: 'Tonterías modernas. El amor y el compromiso han existido siempre y tienen valor.', en: 'Modern nonsense. Love and commitment have always existed and have value.', fr: 'Des bêtises modernes. L\'amour et l\'engagement ont toujours existé et ont de la valeur.', de: 'Moderner Unsinn. Liebe und Engagement haben immer existiert und haben Wert.', it: 'Sciocchezze moderne. L\'amore e l\'impegno sono sempre esistiti e hanno valore.', pt: 'Bobagens modernas. O amor e o compromisso sempre existiram e têm valor.' }, dimension: 'B' },
      { text: { es: 'Hay algo de cierto en cuestionar los modelos tradicionales, pero el amor sigue siendo real.', en: 'There\'s some truth in questioning traditional models, but love remains real.', fr: 'Il y a quelque chose de vrai dans le questionnement des modèles traditionnels, mais l\'amour reste réel.', de: 'Es steckt etwas Wahres darin, traditionelle Modelle zu hinterfragen, aber Liebe bleibt real.', it: 'C\'è del vero nel mettere in discussione i modelli tradizionali, ma l\'amore rimane reale.', pt: 'Há algo de verdadeiro em questionar os modelos tradicionais, mas o amor continua real.' }, dimension: 'M' },
      { text: { es: 'El modelo tradicional de pareja tiene problemas reales. Tiene sentido cuestionarlo.', en: 'The traditional couple model has real problems. It makes sense to question it.', fr: 'Le modèle traditionnel de couple a des problèmes réels. Il est logique de le remettre en question.', de: 'Das traditionelle Paarmodell hat echte Probleme. Es macht Sinn, es zu hinterfragen.', it: 'Il modello tradizionale di coppia ha problemi reali. Ha senso metterlo in discussione.', pt: 'O modelo tradicional de casal tem problemas reais. Faz sentido questioná-lo.' }, dimension: 'Z' },
      { text: { es: 'El amor como experiencia es real; sus formas de organización son construcciones que evolucionan.', en: 'Love as an experience is real; its forms of organization are constructs that evolve.', fr: 'L\'amour en tant qu\'expérience est réel; ses formes d\'organisation sont des constructions qui évoluent.', de: 'Liebe als Erfahrung ist real; ihre Organisationsformen sind Konstrukte, die sich entwickeln.', it: 'L\'amore come esperienza è reale; le sue forme di organizzazione sono costruzioni che si evolvono.', pt: 'O amor como experiência é real; suas formas de organização são construções que evoluem.' }, dimension: 'A' },
    ] },
    { id: 7, situation: { es: '¿Qué piensas de los pronombres neutros o no binarios?', en: 'What do you think about neutral or non-binary pronouns?', fr: 'Que penses-tu des pronoms neutres ou non binaires ?', de: 'Was denkst du über neutrale oder nicht-binäre Pronomen?', it: 'Cosa pensi dei pronomi neutri o non binari?', pt: 'O que você pensa sobre os pronomes neutros ou não-binários?' }, options: [
      { text: { es: 'Es una exageración. Hay hombre y mujer y eso ha funcionado bien.', en: 'It\'s an exaggeration. There\'s man and woman and that has worked fine.', fr: 'C\'est une exagération. Il y a homme et femme et ça a bien fonctionné.', de: 'Es ist eine Übertreibung. Es gibt Mann und Frau und das hat gut funktioniert.', it: 'È un\'esagerazione. C\'è uomo e donna e questo ha funzionato bene.', pt: 'É um exagero. Há homem e mulher e isso funcionou bem.' }, dimension: 'B' },
      { text: { es: 'Puede respetarse sin necesitar entenderlo del todo.', en: 'It can be respected without needing to fully understand it.', fr: 'Ça peut se respecter sans avoir besoin de le comprendre entièrement.', de: 'Es kann respektiert werden, ohne es vollständig verstehen zu müssen.', it: 'Può essere rispettato senza dover capirlo completamente.', pt: 'Pode ser respeitado sem precisar entendê-lo completamente.' }, dimension: 'M' },
      { text: { es: 'Es una evolución necesaria del lenguaje para reflejar la diversidad real.', en: 'It\'s a necessary evolution of language to reflect real diversity.', fr: 'C\'est une évolution nécessaire du langage pour refléter la diversité réelle.', de: 'Es ist eine notwendige Entwicklung der Sprache, um echte Vielfalt widerzuspiegeln.', it: 'È un\'evoluzione necessaria del linguaggio per riflettere la diversità reale.', pt: 'É uma evolução necessária da linguagem para refletir a diversidade real.' }, dimension: 'Z' },
      { text: { es: 'El lenguaje evoluciona con las culturas. Lo importante es el respeto a las personas.', en: 'Language evolves with cultures. What matters is respect for people.', fr: 'Le langage évolue avec les cultures. L\'important est le respect des personnes.', de: 'Sprache entwickelt sich mit Kulturen. Was zählt, ist der Respekt für Menschen.', it: 'Il linguaggio si evolve con le culture. L\'importante è il rispetto delle persone.', pt: 'A linguagem evolui com as culturas. O importante é o respeito pelas pessoas.' }, dimension: 'A' },
    ] },
    { id: 8, situation: { es: 'Los jóvenes no compran casas ni se casan a los 30 como antes.', en: 'Young people don\'t buy houses or get married at 30 like before.', fr: 'Les jeunes n\'achètent pas de maisons ni ne se marient à 30 ans comme avant.', de: 'Junge Leute kaufen keine Häuser mehr und heiraten nicht mehr mit 30 wie früher.', it: 'I giovani non comprano case né si sposano a 30 anni come prima.', pt: 'Os jovens não compram casas nem se casam aos 30 como antes.' }, options: [
      { text: { es: 'Es falta de sacrificio y planeación. Si se propusieran, podrían.', en: 'It\'s lack of sacrifice and planning. If they set their minds to it, they could.', fr: 'C\'est un manque de sacrifice et de planification. S\'ils s\'y mettaient, ils pourraient.', de: 'Es ist ein Mangel an Opferbereitschaft und Planung. Wenn sie es wollten, könnten sie.', it: 'È mancanza di sacrificio e pianificazione. Se ci si impegnassero, potrebbero.', pt: 'É falta de sacrifício e planejamento. Se se propusessem, poderiam.' }, dimension: 'B' },
      { text: { es: 'El mercado está más difícil, pero también hay prioridades diferentes hoy.', en: 'The market is harder, but there are also different priorities today.', fr: 'Le marché est plus difficile, mais il y a aussi des priorités différentes aujourd\'hui.', de: 'Der Markt ist schwieriger, aber es gibt heute auch andere Prioritäten.', it: 'Il mercato è più difficile, ma ci sono anche priorità diverse oggi.', pt: 'O mercado está mais difícil, mas também há prioridades diferentes hoje.' }, dimension: 'M' },
      { text: { es: 'El sistema económico hace esas cosas inaccesibles para muchos. No es falta de esfuerzo.', en: 'The economic system makes those things inaccessible for many. It\'s not lack of effort.', fr: 'Le système économique rend ces choses inaccessibles pour beaucoup. Ce n\'est pas un manque d\'effort.', de: 'Das Wirtschaftssystem macht diese Dinge für viele unzugänglich. Es ist kein Mangel an Mühe.', it: 'Il sistema economico rende quelle cose inaccessibili per molti. Non è mancanza di sforzo.', pt: 'O sistema econômico torna essas coisas inacessíveis para muitos. Não é falta de esforço.' }, dimension: 'Z' },
      { text: { es: 'Una combinación de cambios económicos estructurales y evolución cultural de los valores.', en: 'A combination of structural economic changes and cultural evolution of values.', fr: 'Une combinaison de changements économiques structurels et d\'évolution culturelle des valeurs.', de: 'Eine Kombination aus strukturellen wirtschaftlichen Veränderungen und kultureller Werteentwicklung.', it: 'Una combinazione di cambiamenti economici strutturali ed evoluzione culturale dei valori.', pt: 'Uma combinação de mudanças econômicas estruturais e evolução cultural dos valores.' }, dimension: 'A' },
    ] },
    { id: 9, situation: { es: '¿Qué tan seguido dices o piensas "antes las cosas eran mejores"?', en: 'How often do you say or think "things were better before"?', fr: 'À quelle fréquence dis-tu ou penses-tu "les choses étaient mieux avant" ?', de: 'Wie oft sagst oder denkst du "früher war alles besser"?', it: 'Quanto spesso dici o pensi "prima le cose erano meglio"?', pt: 'Com que frequência você diz ou pensa "antes as coisas eram melhores"?' }, options: [
      { text: { es: 'Con frecuencia. Hay cosas del pasado que eran genuinamente más simples y mejores.', en: 'Often. There are things from the past that were genuinely simpler and better.', fr: 'Fréquemment. Il y a des choses du passé qui étaient vraiment plus simples et meilleures.', de: 'Häufig. Es gibt Dinge aus der Vergangenheit, die wirklich einfacher und besser waren.', it: 'Spesso. Ci sono cose del passato che erano genuinamente più semplici e migliori.', pt: 'Com frequência. Há coisas do passado que eram genuinamente mais simples e melhores.' }, dimension: 'B' },
      { text: { es: 'A veces. Hay cosas que han mejorado y otras que se han perdido.', en: 'Sometimes. Some things have improved and others have been lost.', fr: 'Parfois. Certaines choses se sont améliorées et d\'autres ont été perdues.', de: 'Manchmal. Manche Dinge haben sich verbessert und andere sind verloren gegangen.', it: 'A volte. Alcune cose sono migliorate e altre si sono perse.', pt: 'Às vezes. Há coisas que melhoraram e outras que se perderam.' }, dimension: 'M' },
      { text: { es: 'Casi nunca. La nostalgia suele ser una lectura selectiva del pasado.', en: 'Almost never. Nostalgia is usually a selective reading of the past.', fr: 'Presque jamais. La nostalgie est souvent une lecture sélective du passé.', de: 'Fast nie. Nostalgie ist meistens eine selektive Lesart der Vergangenheit.', it: 'Quasi mai. La nostalgia è solitamente una lettura selettiva del passato.', pt: 'Quase nunca. A nostalgia costuma ser uma leitura seletiva do passado.' }, dimension: 'Z' },
      { text: { es: 'Raramente. El pasado y el presente tienen cosas valiosas y problemáticas.', en: 'Rarely. Past and present both have valuable and problematic aspects.', fr: 'Rarement. Le passé et le présent ont tous deux des aspects précieux et problématiques.', de: 'Selten. Vergangenheit und Gegenwart haben beide wertvolle und problematische Aspekte.', it: 'Raramente. Il passato e il presente hanno entrambi aspetti preziosi e problematici.', pt: 'Raramente. O passado e o presente têm aspectos valiosos e problemáticos.' }, dimension: 'A' },
    ] },
    { id: 10, situation: { es: 'Los jóvenes de hoy tienen acceso a toda la información del mundo pero parecen saber menos.', en: 'Today\'s youth have access to all the world\'s information but seem to know less.', fr: 'Les jeunes d\'aujourd\'hui ont accès à toute l\'information du monde mais semblent moins en savoir.', de: 'Die Jugend von heute hat Zugang zu allen Informationen der Welt, scheint aber weniger zu wissen.', it: 'I giovani di oggi hanno accesso a tutte le informazioni del mondo ma sembrano sapere meno.', pt: 'Os jovens de hoje têm acesso a todas as informações do mundo mas parecem saber menos.' }, options: [
      { text: { es: 'Exacto. Tener información no es lo mismo que tener conocimiento o criterio.', en: 'Exactly. Having information is not the same as having knowledge or judgment.', fr: 'Exactement. Avoir des informations ne signifie pas avoir des connaissances ou du jugement.', de: 'Genau. Informationen zu haben ist nicht dasselbe wie Wissen oder Urteilsvermögen zu haben.', it: 'Esatto. Avere informazioni non è lo stesso che avere conoscenza o giudizio.', pt: 'Exatamente. Ter informação não é o mesmo que ter conhecimento ou critério.' }, dimension: 'B' },
      { text: { es: 'Hay un problema de filtrado de información. No todo acceso es igualmente valioso.', en: 'There\'s an information filtering problem. Not all access is equally valuable.', fr: 'Il y a un problème de filtrage de l\'information. Tout accès n\'est pas également précieux.', de: 'Es gibt ein Problem mit der Informationsfilterung. Nicht jeder Zugang ist gleich wertvoll.', it: 'C\'è un problema di filtraggio delle informazioni. Non tutto l\'accesso è ugualmente prezioso.', pt: 'Há um problema de filtragem de informação. Nem todo acesso tem igual valor.' }, dimension: 'M' },
      { text: { es: 'Es un desafío nuevo que las generaciones anteriores no tuvieron que enfrentar.', en: 'It\'s a new challenge that previous generations didn\'t have to face.', fr: 'C\'est un nouveau défi que les générations précédentes n\'avaient pas à affronter.', de: 'Es ist eine neue Herausforderung, der sich frühere Generationen nicht stellen mussten.', it: 'È una nuova sfida che le generazioni precedenti non hanno dovuto affrontare.', pt: 'É um desafio novo que as gerações anteriores não tiveram que enfrentar.' }, dimension: 'Z' },
      { text: { es: 'El volumen de información crea nuevos desafíos cognitivos que requieren nuevas habilidades.', en: 'The volume of information creates new cognitive challenges requiring new skills.', fr: 'Le volume d\'information crée de nouveaux défis cognitifs nécessitant de nouvelles compétences.', de: 'Das Informationsvolumen schafft neue kognitive Herausforderungen, die neue Fähigkeiten erfordern.', it: 'Il volume di informazioni crea nuove sfide cognitive che richiedono nuove abilità.', pt: 'O volume de informação cria novos desafios cognitivos que requerem novas habilidades.' }, dimension: 'A' },
    ] },
  ],
  characters: [
    { name: { es: 'El Boomer Clásico', en: 'The Classic Boomer', fr: 'Le Boomer Classique', de: 'Der Klassische Boomer', it: 'Il Boomer Classico', pt: 'O Boomer Clássico' }, dimensions: ['B'], photo: '/characters/boomer.jpg', description: { es: '"En mi época..." es su frase de cabecera.', en: '"Back in my day..." is their go-to phrase.', fr: '"À mon époque..." est sa phrase habituelle.', de: '"Früher..." ist sein/ihr Standardsatz.', it: '"Ai miei tempi..." è la sua frase di apertura.', pt: '"Na minha época..." é sua frase de cabeça.' }, philosophy: { es: 'Para ti, el pasado tenía algo que el presente ha perdido. No necesariamente estás equivocado/a — pero la nostalgia tiene un sesgo selectivo que a veces convierte el ayer en un paraíso que nunca fue del todo así.', en: 'For you, the past had something the present has lost. You\'re not necessarily wrong — but nostalgia has a selective bias that sometimes turns yesterday into a paradise it never fully was.', fr: 'Pour toi, le passé avait quelque chose que le présent a perdu. Tu n\'as pas nécessairement tort — mais la nostalgie a un biais sélectif qui transforme parfois hier en un paradis qu\'il n\'était jamais vraiment.', de: 'Für dich hatte die Vergangenheit etwas, das die Gegenwart verloren hat. Du liegst nicht unbedingt falsch — aber Nostalgie hat einen selektiven Bias, der das Gestern manchmal in ein Paradies verwandelt, das es so nie ganz war.', it: 'Per te, il passato aveva qualcosa che il presente ha perso. Non hai necessariamente torto — ma la nostalgia ha un bias selettivo che a volte trasforma ieri in un paradiso che non era mai stato del tutto tale.', pt: 'Para você, o passado tinha algo que o presente perdeu. Você não está necessariamente errado/a — mas a nostalgia tem um viés seletivo que às vezes transforma o ontem em um paraíso que nunca foi totalmente assim.' } },
    { name: { es: 'El Millennial Pragmático', en: 'The Pragmatic Millennial', fr: 'Le Millennial Pragmatique', de: 'Der Pragmatische Millennial', it: 'Il Millennial Pragmatico', pt: 'O Millennial Pragmático' }, dimensions: ['M'], photo: '/characters/millennial.jpg', description: { es: 'Ve lo bueno y lo malo de cada época. El eterno "depende".', en: 'Sees the good and bad in each era. The eternal "it depends".', fr: 'Voit le bon et le mauvais de chaque époque. L\'éternel "ça dépend".', de: 'Sieht das Gute und das Schlechte jeder Epoche. Das ewige "kommt drauf an".', it: 'Vede il bene e il male di ogni epoca. L\'eterno "dipende".', pt: 'Vê o bom e o ruim de cada época. O eterno "depende".' }, philosophy: { es: 'Estás en el medio: entiendes la crítica de los más jóvenes y también el valor de lo que hay que ganar con esfuerzo. Tu posición no siempre es cómoda pero es probablemente la más realista.', en: 'You\'re in the middle: you understand the criticism of the younger ones and also the value of what must be earned through effort. Your position isn\'t always comfortable but it\'s probably the most realistic.', fr: 'Tu es au milieu : tu comprends la critique des plus jeunes et aussi la valeur de ce qui doit être gagné par l\'effort. Ta position n\'est pas toujours confortable mais c\'est probablement la plus réaliste.', de: 'Du bist in der Mitte: Du verstehst die Kritik der Jüngeren und auch den Wert dessen, was durch Mühe verdient werden muss. Deine Position ist nicht immer angenehm, aber wahrscheinlich die realistischste.', it: 'Sei nel mezzo: capisci la critica dei più giovani e anche il valore di ciò che deve essere guadagnato con sforzo. La tua posizione non è sempre comoda ma è probabilmente la più realistica.', pt: 'Você está no meio: entende a crítica dos mais jovens e também o valor do que deve ser conquistado com esforço. Sua posição nem sempre é confortável, mas é provavelmente a mais realista.' } },
    { name: { es: 'La Gen Z Disruptora', en: 'The Disruptive Gen Z', fr: 'La Gen Z Disruptrice', de: 'Die Disruptive Gen Z', it: 'La Gen Z Dirompente', pt: 'A Gen Z Disruptora' }, dimensions: ['Z'], photo: '/characters/gen-z.jpg', description: { es: 'Cuestiona las estructuras que otros dan por sentadas.', en: 'Questions the structures others take for granted.', fr: 'Remet en question les structures que les autres tiennent pour acquises.', de: 'Hinterfragt Strukturen, die andere für selbstverständlich halten.', it: 'Mette in discussione le strutture che gli altri danno per scontate.', pt: 'Questiona as estruturas que outros dão por certas.' }, philosophy: { es: 'Para ti, muchas de las "verdades" generacionales son simplemente consensos que nadie cuestionó suficientemente. Tu mirada crítica puede incomodar, pero también trae perspectivas necesarias.', en: 'For you, many generational "truths" are simply consensuses nobody questioned enough. Your critical view can be uncomfortable, but it also brings necessary perspectives.', fr: 'Pour toi, beaucoup de "vérités" générationnelles sont simplement des consensus que personne n\'a suffisamment remis en question. Ton regard critique peut déranger, mais il apporte aussi des perspectives nécessaires.', de: 'Für dich sind viele generationelle "Wahrheiten" einfach Konsense, die niemand ausreichend hinterfragt hat. Dein kritischer Blick kann unbequem sein, bringt aber auch notwendige Perspektiven.', it: 'Per te, molte "verità" generazionali sono semplicemente consensi che nessuno ha messo sufficientemente in discussione. Il tuo sguardo critico può essere scomodo, ma porta anche prospettive necessarie.', pt: 'Para você, muitas "verdades" geracionais são simplesmente consensos que ninguém questionou o suficiente. Seu olhar crítico pode incomodar, mas também traz perspectivas necessárias.' } },
    { name: { es: 'El Atemporal', en: 'The Timeless One', fr: 'L\'Intemporel', de: 'Der Zeitlose', it: 'L\'Atemporale', pt: 'O Atemporal' }, dimensions: ['A'], photo: '/characters/timeless.jpg', description: { es: 'No se identifica con generaciones. Cada época tiene sus razones.', en: 'Doesn\'t identify with generations. Every era has its reasons.', fr: 'Ne s\'identifie pas aux générations. Chaque époque a ses raisons.', de: 'Identifiziert sich nicht mit Generationen. Jede Epoche hat ihre Gründe.', it: 'Non si identifica con le generazioni. Ogni epoca ha le sue ragioni.', pt: 'Não se identifica com gerações. Cada época tem seus motivos.' }, philosophy: { es: 'Para ti, las guerras generacionales son en gran parte malentendidos contextuales. Cada generación enfrenta sus condiciones y responde según sus herramientas. El juicio intergeneracional dice más del juzgador que del juzgado.', en: 'For you, generational wars are largely contextual misunderstandings. Each generation faces its conditions and responds with its tools. Intergenerational judgment says more about the judge than the judged.', fr: 'Pour toi, les guerres générationnelles sont en grande partie des malentendus contextuels. Chaque génération fait face à ses conditions et répond avec ses outils. Le jugement intergénérationnel en dit plus sur le juge que sur le jugé.', de: 'Für dich sind Generationskonflikte größtenteils kontextuelle Missverständnisse. Jede Generation steht ihren Bedingungen gegenüber und antwortet mit ihren Werkzeugen. Das Generationsurteil sagt mehr über den Richtenden als den Beurteilten.', it: 'Per te, le guerre generazionali sono in gran parte malintesi contestuali. Ogni generazione affronta le proprie condizioni e risponde con i propri strumenti. Il giudizio intergenerazionale dice più del giudicante che del giudicato.', pt: 'Para você, as guerras geracionais são em grande parte mal-entendidos contextuais. Cada geração enfrenta suas condições e responde com suas ferramentas. O julgamento intergeracional diz mais sobre quem julga do que sobre o julgado.' } },
    { name: { es: 'El Boomer Nostálgico', en: 'The Nostalgic Boomer', fr: 'Le Boomer Nostalgique', de: 'Der Nostalgische Boomer', it: 'Il Boomer Nostalgico', pt: 'O Boomer Nostálgico' }, dimensions: ['B', 'M'], photo: '/characters/nostalgic-boomer.jpg', description: { es: 'Nostálgico pero pragmático. Añora el pasado pero navega el presente.', en: 'Nostalgic but pragmatic. Yearns for the past but navigates the present.', fr: 'Nostalgique mais pragmatique. Aspire au passé mais navigue dans le présent.', de: 'Nostalgisch aber pragmatisch. Sehnt sich nach der Vergangenheit, navigiert aber die Gegenwart.', it: 'Nostalgico ma pragmatico. Rimpiange il passato ma naviga il presente.', pt: 'Nostálgico mas pragmático. Saudoso do passado mas navega o presente.' }, philosophy: { es: 'Valoras lo que fue y al mismo tiempo te adaptas a lo que es. La nostalgia no te paraliza — es más un color de fondo que una prisión. Puedes añorar y avanzar al mismo tiempo.', en: 'You value what was and at the same time adapt to what is. Nostalgia doesn\'t paralyze you — it\'s more a background color than a prison. You can yearn and advance at the same time.', fr: 'Tu valorises ce qui était et en même temps tu t\'adaptes à ce qui est. La nostalgie ne te paralyse pas — c\'est plus une couleur de fond qu\'une prison. Tu peux regretter et avancer en même temps.', de: 'Du schätzt, was war, und passt dich gleichzeitig dem an, was ist. Nostalgie lähmt dich nicht — sie ist eher eine Hintergrundfarbe als ein Gefängnis. Du kannst sehnen und vorwärtsgehen gleichzeitig.', it: 'Valorizzi ciò che era e allo stesso tempo ti adatti a ciò che è. La nostalgia non ti paralizza — è più un colore di sfondo che una prigione. Puoi rimpiangere e avanzare allo stesso tempo.', pt: 'Você valoriza o que foi e ao mesmo tempo se adapta ao que é. A nostalgia não te paralisa — é mais uma cor de fundo do que uma prisão. Você pode sentir saudade e avançar ao mesmo tempo.' } },
    { name: { es: 'El Crítico Constructivo', en: 'The Constructive Critic', fr: 'Le Critique Constructif', de: 'Der Konstruktive Kritiker', it: 'Il Critico Costruttivo', pt: 'O Crítico Construtivo' }, dimensions: ['M', 'A'], photo: '/characters/constructive-critic.jpg', description: { es: 'Cuestiona sin nostalgia y sin extremismos.', en: 'Questions without nostalgia and without extremism.', fr: 'Questionne sans nostalgie et sans extrémismes.', de: 'Hinterfragt ohne Nostalgie und ohne Extremismus.', it: 'Mette in discussione senza nostalgia e senza estremismi.', pt: 'Questiona sem nostalgia e sem extremismos.' }, philosophy: { es: 'Tu análisis de los cambios generacionales no viene ni de la nostalgia ni del radicalismo. Ves las tensiones reales y buscas entenderlas con matices. Eso te hace menos entretenido pero más útil.', en: 'Your analysis of generational changes comes neither from nostalgia nor radicalism. You see the real tensions and seek to understand them with nuance. That makes you less entertaining but more useful.', fr: 'Ton analyse des changements générationnels ne vient ni de la nostalgie ni du radicalisme. Tu vois les tensions réelles et cherches à les comprendre avec nuances. Ça te rend moins divertissant mais plus utile.', de: 'Deine Analyse der Generationsveränderungen kommt weder von Nostalgie noch von Radikalismus. Du siehst die echten Spannungen und versuchst sie mit Nuancen zu verstehen. Das macht dich weniger unterhaltsam aber nützlicher.', it: 'La tua analisi dei cambiamenti generazionali non viene né dalla nostalgia né dal radicalismo. Vedi le tensioni reali e cerchi di comprenderle con sfumature. Questo ti rende meno divertente ma più utile.', pt: 'Sua análise das mudanças geracionais não vem nem da nostalgia nem do radicalismo. Você vê as tensões reais e busca entendê-las com nuances. Isso te torna menos divertido mas mais útil.' } },
    { name: { es: 'El Progresista Reflexivo', en: 'The Reflective Progressive', fr: 'Le Progressiste Réflexif', de: 'Der Reflektierte Progressive', it: 'Il Progressista Riflessivo', pt: 'O Progressista Reflexivo' }, dimensions: ['Z', 'A'], photo: '/characters/reflective-progressive.jpg', description: { es: 'Abierto al cambio y al mismo tiempo consciente de la complejidad.', en: 'Open to change and at the same time aware of complexity.', fr: 'Ouvert au changement et en même temps conscient de la complexité.', de: 'Offen für Wandel und gleichzeitig bewusst über Komplexität.', it: 'Aperto al cambiamento e allo stesso tempo consapevole della complessità.', pt: 'Aberto à mudança e ao mesmo tempo consciente da complexidade.' }, philosophy: { es: 'Apoyas el cambio porque lo ves necesario, y al mismo tiempo entiendes que los cambios tienen costos y resistencias legítimas. No eres ingenuo/a sobre la complejidad del progreso.', en: 'You support change because you see it as necessary, and at the same time understand that changes have costs and legitimate resistances. You\'re not naive about the complexity of progress.', fr: 'Tu soutiens le changement parce que tu le vois nécessaire, et en même temps tu comprends que les changements ont des coûts et des résistances légitimes. Tu n\'es pas naïf/ve sur la complexité du progrès.', de: 'Du unterstützt Wandel, weil du ihn für notwendig hältst, und verstehst gleichzeitig, dass Veränderungen Kosten und legitime Widerstände haben. Du bist nicht naiv über die Komplexität des Fortschritts.', it: 'Sostieni il cambiamento perché lo vedi necessario, e allo stesso tempo capisci che i cambiamenti hanno costi e resistenze legittime. Non sei ingenuo/a sulla complessità del progresso.', pt: 'Você apoia a mudança porque a vê como necessária, e ao mesmo tempo entende que as mudanças têm custos e resistências legítimas. Você não é ingênuo/a sobre a complexidade do progresso.' } },
    { name: { es: 'El Renovador Moderado', en: 'The Moderate Renewer', fr: 'Le Rénovateur Modéré', de: 'Der Moderate Erneuerer', it: 'Il Rinnovatore Moderato', pt: 'O Renovador Moderado' }, dimensions: ['M', 'Z'], photo: '/characters/moderate-renewer.jpg', description: { es: 'Millennial y Gen Z juntos: flexibilidad y cuestionamiento.', en: 'Millennial and Gen Z together: flexibility and questioning.', fr: 'Millennial et Gen Z ensemble : flexibilité et questionnement.', de: 'Millennial und Gen Z zusammen: Flexibilität und Hinterfragen.', it: 'Millennial e Gen Z insieme: flessibilità e messa in discussione.', pt: 'Millennial e Gen Z juntos: flexibilidade e questionamento.' }, philosophy: { es: 'Combinas la pragmática de quien vivió la transición digital con la disposición de quien creció cuestionando todo. Esa combinación te hace especialmente útil en conversaciones intergeneracionales.', en: 'You combine the pragmatism of someone who lived the digital transition with the disposition of someone who grew up questioning everything. That combination makes you especially useful in intergenerational conversations.', fr: 'Tu combines le pragmatisme de quelqu\'un qui a vécu la transition numérique avec la disposition de quelqu\'un qui a grandi en questionnant tout. Cette combinaison te rend particulièrement utile dans les conversations intergénérationnelles.', de: 'Du kombinierst den Pragmatismus von jemandem, der den digitalen Wandel erlebt hat, mit der Disposition von jemandem, der alles in Frage gestellt hat. Diese Kombination macht dich in intergenerationellen Gesprächen besonders nützlich.', it: 'Combini il pragmatismo di chi ha vissuto la transizione digitale con la disposizione di chi è cresciuto mettendo tutto in discussione. Quella combinazione ti rende particolarmente utile nelle conversazioni intergenerazionali.', pt: 'Você combina o pragmatismo de quem viveu a transição digital com a disposição de quem cresceu questionando tudo. Essa combinação te torna especialmente útil em conversas intergeracionais.' } },
  ],
};

export async function seedBoomer(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'boomer' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'boomer',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['pop-culture'],
      sortOrder: 2,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
