import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan psicópata eres?', en: 'How much of a psychopath are you?', fr: 'À quel point es-tu psychopathe ?', de: 'Wie sehr bist du ein Psychopath?', it: 'Quanto sei psicopatico/a?', pt: 'O quanto você é psicopata?' },
  description: { es: 'No todos los psicópatas son asesinos. Algunos dirigen empresas. Descubre qué tipo de mente tienes en situaciones límite.', en: 'Not all psychopaths are killers. Some run companies. Discover what type of mind you have in extreme situations.', fr: 'Tous les psychopathes ne sont pas des tueurs. Certains dirigent des entreprises. Découvrez quel type d\'esprit vous avez dans les situations limites.', de: 'Nicht alle Psychopathen sind Mörder. Einige leiten Unternehmen. Entdecke, welche Art von Geist du in Extremsituationen hast.', it: 'Non tutti i psicopatici sono assassini. Alcuni dirigono aziende. Scopri che tipo di mente hai nelle situazioni limite.', pt: 'Nem todos os psicopatas são assassinos. Alguns dirigem empresas. Descubra que tipo de mente você tem em situações extremas.' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { F: 'Frialdad', M: 'Manipulación', I: 'Impulsividad', E: 'Empatía' },
    en: { F: 'Coldness', M: 'Manipulation', I: 'Impulsivity', E: 'Empathy' },
    fr: { F: 'Froideur', M: 'Manipulation', I: 'Impulsivité', E: 'Empathie' },
    de: { F: 'Kälte', M: 'Manipulation', I: 'Impulsivität', E: 'Empathie' },
    it: { F: 'Freddezza', M: 'Manipolazione', I: 'Impulsività', E: 'Empatia' },
    pt: { F: 'Frieza', M: 'Manipulação', I: 'Impulsividade', E: 'Empatia' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu empresa está en crisis. Si despides a 50 empleados hoy, puedes salvar a 200. Los 50 son buenos trabajadores con familias. ¿Qué haces?', en: 'Your company is in crisis. If you fire 50 employees today, you can save 200. The 50 are good workers with families. What do you do?', fr: 'Ton entreprise est en crise. Si tu licencies 50 employés aujourd\'hui, tu peux en sauver 200. Les 50 sont de bons travailleurs avec des familles. Que fais-tu ?', de: 'Dein Unternehmen ist in der Krise. Wenn du heute 50 Mitarbeiter entlässt, kannst du 200 retten. Die 50 sind gute Arbeiter mit Familien. Was tust du?', it: 'La tua azienda è in crisi. Se licenzi 50 dipendenti oggi, puoi salvarne 200. I 50 sono buoni lavoratori con famiglie. Cosa fai?', pt: 'Sua empresa está em crise. Se você demitir 50 funcionários hoje, pode salvar 200. Os 50 são bons trabalhadores com famílias. O que você faz?' }, options: [
      { text: { es: 'Los despido hoy. Es matemática simple: 200 > 50.', en: 'I fire them today. It\'s simple math: 200 > 50.', fr: 'Je les licencie aujourd\'hui. C\'est des maths simples: 200 > 50.', de: 'Ich entlasse sie heute. Es ist einfache Mathematik: 200 > 50.', it: 'Li licenzio oggi. È matematica semplice: 200 > 50.', pt: 'Os demito hoje. É matemática simples: 200 > 50.' }, dimension: 'F' },
      { text: { es: 'Primero los convenzo de que es por el bien de todos, luego los despido.', en: 'First I convince them it\'s for everyone\'s good, then I fire them.', fr: 'D\'abord je les convaincs que c\'est pour le bien de tous, puis je les licencie.', de: 'Zuerst überzeuge ich sie, dass es für alle gut ist, dann entlasse ich sie.', it: 'Prima li convinco che è per il bene di tutti, poi li licenzio.', pt: 'Primeiro os convenço de que é para o bem de todos, depois os demito.' }, dimension: 'M' },
      { text: { es: 'Espero hasta el último momento y luego actúo de golpe cuando no hay alternativa.', en: 'I wait until the last moment and then act all at once when there\'s no alternative.', fr: 'J\'attends jusqu\'au dernier moment et agis d\'un coup quand il n\'y a pas d\'alternative.', de: 'Ich warte bis zum letzten Moment und handle dann auf einmal, wenn es keine Alternative gibt.', it: 'Aspetto fino all\'ultimo momento e poi agisco di colpo quando non c\'è alternativa.', pt: 'Espero até o último momento e depois ajo de uma vez quando não há alternativa.' }, dimension: 'I' },
      { text: { es: 'Busco alternativas durante semanas aunque sea más costoso para la empresa.', en: 'I look for alternatives for weeks even if it\'s more costly for the company.', fr: 'Je cherche des alternatives pendant des semaines même si c\'est plus coûteux pour l\'entreprise.', de: 'Ich suche wochenlang nach Alternativen, auch wenn es für das Unternehmen teurer ist.', it: 'Cerco alternative per settimane anche se è più costoso per l\'azienda.', pt: 'Busco alternativas por semanas mesmo que seja mais custoso para a empresa.' }, dimension: 'E' },
    ] },
    { id: 2, situation: { es: 'En una negociación importante, descubres que la otra parte tiene una debilidad personal (una crisis familiar). ¿Qué haces?', en: 'In an important negotiation, you discover the other party has a personal weakness (a family crisis). What do you do?', fr: 'Dans une négociation importante, tu découvres que l\'autre partie a une faiblesse personnelle (une crise familiale). Que fais-tu ?', de: 'In einer wichtigen Verhandlung entdeckst du, dass die andere Partei eine persönliche Schwäche hat (eine Familienkrise). Was tust du?', it: 'In una trattativa importante, scopri che l\'altra parte ha una debolezza personale (una crisi familiare). Cosa fai?', pt: 'Em uma negociação importante, você descobre que a outra parte tem uma fraqueza pessoal (uma crise familiar). O que você faz?' }, options: [
      { text: { es: 'Nada. Las debilidades personales no son relevantes para una negociación profesional.', en: 'Nothing. Personal weaknesses are not relevant to a professional negotiation.', fr: 'Rien. Les faiblesses personnelles ne sont pas pertinentes pour une négociation professionnelle.', de: 'Nichts. Persönliche Schwächen sind für eine professionelle Verhandlung nicht relevant.', it: 'Niente. Le debolezze personali non sono rilevanti per una trattativa professionale.', pt: 'Nada. Fraquezas pessoais não são relevantes para uma negociação profissional.' }, dimension: 'F' },
      { text: { es: 'La uso estratégicamente para obtener mejores términos. Todo es información.', en: 'I use it strategically to get better terms. Everything is information.', fr: 'Je l\'utilise stratégiquement pour obtenir de meilleures conditions. Tout est information.', de: 'Ich nutze es strategisch, um bessere Konditionen zu erzielen. Alles ist Information.', it: 'La uso strategicamente per ottenere termini migliori. Tutto è informazione.', pt: 'Uso estrategicamente para obter melhores termos. Tudo é informação.' }, dimension: 'M' },
      { text: { es: 'Sin pensar demasiado, la menciono directamente en la mesa.', en: 'Without thinking too much, I mention it directly at the table.', fr: 'Sans trop réfléchir, je la mentionne directement à la table.', de: 'Ohne zu viel nachzudenken, erwähne ich sie direkt am Tisch.', it: 'Senza pensarci troppo, la menziono direttamente al tavolo.', pt: 'Sem pensar muito, menciono diretamente na mesa.' }, dimension: 'I' },
      { text: { es: 'Pregunto discretamente si está bien antes de comenzar. Las personas primero.', en: 'I discreetly ask if they\'re okay before starting. People first.', fr: 'Je demande discrètement si tout va bien avant de commencer. Les personnes d\'abord.', de: 'Ich frage diskret, ob alles gut ist, bevor ich beginne. Menschen zuerst.', it: 'Chiedo discretamente se sta bene prima di iniziare. Le persone prima di tutto.', pt: 'Pergunto discretamente se está bem antes de começar. As pessoas primeiro.' }, dimension: 'E' },
    ] },
    { id: 3, situation: { es: 'Tu mejor amigo te pide que lo cubras en una mentira con su pareja. Sabes que está equivocado.', en: 'Your best friend asks you to cover for them in a lie to their partner. You know they\'re wrong.', fr: 'Ton meilleur ami te demande de le couvrir dans un mensonge envers sa partenaire. Tu sais qu\'il a tort.', de: 'Dein bester Freund bittet dich, ihn in einer Lüge gegenüber seinem Partner zu decken. Du weißt, dass er falsch liegt.', it: 'Il tuo migliore amico ti chiede di coprirlo in una bugia con il suo partner. Sai che ha torto.', pt: 'Seu melhor amigo pede que você o cubra em uma mentira com o parceiro. Você sabe que ele está errado.' }, options: [
      { text: { es: 'Evalúo los riesgos para mí. Si me conviene cubrirlo, lo hago. Si no, no.', en: 'I evaluate the risks for me. If it\'s worth it to cover him, I do. If not, I don\'t.', fr: 'J\'évalue les risques pour moi. Si ça me convient de le couvrir, je le fais. Sinon, non.', de: 'Ich bewerte die Risiken für mich. Wenn es sich lohnt, ihn zu decken, tue ich es. Wenn nicht, nicht.', it: 'Valuto i rischi per me. Se mi conviene coprirlo, lo faccio. Se no, no.', pt: 'Avalio os riscos para mim. Se me convém cobri-lo, faço. Se não, não.' }, dimension: 'F' },
      { text: { es: 'Lo cubro, pero después lo uso para pedirle un favor importante.', en: 'I cover him, but then use it to ask him for an important favor.', fr: 'Je le couvre, mais ensuite je l\'utilise pour lui demander une faveur importante.', de: 'Ich decke ihn, benutze es aber dann, um ihn um einen wichtigen Gefallen zu bitten.', it: 'Lo copro, ma poi lo uso per chiedergli un favore importante.', pt: 'Cubro, mas depois uso isso para pedir um favor importante.' }, dimension: 'M' },
      { text: { es: 'Le digo que sí impulsivamente y después me arrepiento.', en: 'I say yes impulsively and then regret it.', fr: 'Je dis oui impulsivement et puis je le regrette.', de: 'Ich sage impulsiv Ja und bereue es dann.', it: 'Dico sì impulsivamente e poi me ne pento.', pt: 'Digo que sim impulsivamente e depois me arrependo.' }, dimension: 'I' },
      { text: { es: 'Me niego suavemente. No quiero quedar en medio de su relación.', en: 'I gently refuse. I don\'t want to get caught in the middle of their relationship.', fr: 'Je refuse gentiment. Je ne veux pas me retrouver au milieu de leur relation.', de: 'Ich lehne sanft ab. Ich will nicht in die Mitte ihrer Beziehung geraten.', it: 'Rifiuto gentilmente. Non voglio finire in mezzo alla loro relazione.', pt: 'Recuso gentilmente. Não quero ficar no meio da relação deles.' }, dimension: 'E' },
    ] },
    { id: 4, situation: { es: 'Estás en una fila y alguien se cuela delante de ti con una excusa obvia. Llevas esperando 40 minutos.', en: 'You\'re in a line and someone cuts in front of you with an obvious excuse. You\'ve been waiting 40 minutes.', fr: 'Tu es dans une file d\'attente et quelqu\'un se glisse devant toi avec une excuse évidente. Tu attends depuis 40 minutes.', de: 'Du stehst in einer Warteschlange und jemand drängt sich mit einer offensichtlichen Ausrede vor dir ein. Du wartest schon 40 Minuten.', it: 'Sei in fila e qualcuno si inserisce davanti a te con una scusa ovvia. Aspetti da 40 minuti.', pt: 'Você está na fila e alguém fura na sua frente com uma desculpa óbvia. Você espera há 40 minutos.' }, options: [
      { text: { es: 'No digo nada. No vale el desgaste emocional discutir con desconocidos.', en: 'I say nothing. It\'s not worth the emotional wear to argue with strangers.', fr: 'Je ne dis rien. Ça ne vaut pas l\'usure émotionnelle de se disputer avec des inconnus.', de: 'Ich sage nichts. Es lohnt sich nicht, den emotionalen Aufwand zu betreiben, mit Fremden zu streiten.', it: 'Non dico niente. Non vale lo sforzo emotivo discutere con sconosciuti.', pt: 'Não digo nada. Não vale o desgaste emocional discutir com desconhecidos.' }, dimension: 'F' },
      { text: { es: 'Consigo que otras personas de la fila lo hagan salir. Que lo presionen ellos.', en: 'I get other people in the line to make them leave. Let them apply the pressure.', fr: 'Je fais en sorte que d\'autres personnes de la file le fassent partir. Que ce soient eux qui fassent pression.', de: 'Ich sorge dafür, dass andere Personen in der Schlange sie zum Gehen bringen. Sollen sie den Druck ausüben.', it: 'Faccio in modo che altre persone della fila lo facciano uscire. Che facciano pressione loro.', pt: 'Consigo que outras pessoas da fila o façam sair. Que apliquem pressão eles.' }, dimension: 'M' },
      { text: { es: 'Le digo directamente y enérgicamente que se vaya al final. Sin contemplaciones.', en: 'I tell them directly and forcefully to go to the end. No contemplation.', fr: 'Je lui dis directement et énergiquement d\'aller à la fin. Sans ménagement.', de: 'Ich sage ihm direkt und energisch, er soll ans Ende gehen. Ohne Umschweife.', it: 'Gli dico direttamente ed energicamente di andare in fondo. Senza esitazioni.', pt: 'Digo direta e energeticamente que vá para o final. Sem contemplação.' }, dimension: 'I' },
      { text: { es: 'Le explico amablemente que todos estamos esperando y le pido que respete el orden.', en: 'I kindly explain that we\'re all waiting and ask them to respect the order.', fr: 'Je lui explique gentiment que nous attendons tous et lui demande de respecter l\'ordre.', de: 'Ich erkläre freundlich, dass wir alle warten, und bitte sie, die Reihenfolge zu respektieren.', it: 'Gli spiego gentilmente che stiamo tutti aspettando e gli chiedo di rispettare l\'ordine.', pt: 'Explico gentilmente que todos estamos esperando e peço que respeite a ordem.' }, dimension: 'E' },
    ] },
    { id: 5, situation: { es: 'Sabes que podrías ganar un ascenso si haces ver a un colega como incompetente ante tu jefe. El colega es buena persona pero sí es menos eficiente que tú.', en: 'You know you could get a promotion by making a colleague look incompetent to your boss. The colleague is a good person but is less efficient than you.', fr: 'Tu sais que tu pourrais obtenir une promotion en faisant paraître un collègue incompétent aux yeux de ton patron. Le collègue est une bonne personne mais moins efficace que toi.', de: 'Du weißt, dass du befördert werden könntest, wenn du einen Kollegen vor deinem Chef inkompetent aussehen lässt. Der Kollege ist eine gute Person, aber weniger effizient als du.', it: 'Sai che potresti ottenere una promozione facendo sembrare un collega incompetente al tuo capo. Il collega è una buona persona ma è meno efficiente di te.', pt: 'Você sabe que poderia ganhar uma promoção fazendo um colega parecer incompetente ao seu chefe. O colega é uma boa pessoa mas é menos eficiente que você.' }, options: [
      { text: { es: 'No haría nada activamente. Mi trabajo habla por sí solo.', en: 'I wouldn\'t do anything actively. My work speaks for itself.', fr: 'Je ne ferais rien activement. Mon travail parle de lui-même.', de: 'Ich würde nichts aktiv tun. Meine Arbeit spricht für sich.', it: 'Non farei nulla attivamente. Il mio lavoro parla da solo.', pt: 'Não faria nada ativamente. Meu trabalho fala por si só.' }, dimension: 'F' },
      { text: { es: 'Preparo una presentación que destaca mis logros junto a sus errores. Sutil pero efectivo.', en: 'I prepare a presentation that highlights my achievements alongside their errors. Subtle but effective.', fr: 'Je prépare une présentation qui met en avant mes réussites à côté de ses erreurs. Subtil mais efficace.', de: 'Ich bereite eine Präsentation vor, die meine Leistungen neben ihren Fehlern hervorhebt. Subtil aber effektiv.', it: 'Preparo una presentazione che evidenzia i miei successi accanto ai suoi errori. Sottile ma efficace.', pt: 'Preparo uma apresentação que destaca minhas conquistas junto com os erros dele. Sutil mas eficaz.' }, dimension: 'M' },
      { text: { es: 'En alguna reunión, señalo directamente sus errores delante del jefe.', en: 'In some meeting, I directly point out their errors in front of the boss.', fr: 'Dans une réunion, je signale directement ses erreurs devant le patron.', de: 'In irgendeiner Besprechung weise ich direkt auf seine Fehler vor dem Chef hin.', it: 'In qualche riunione, segnalo direttamente i suoi errori davanti al capo.', pt: 'Em alguma reunião, aponto diretamente os erros dele na frente do chefe.' }, dimension: 'I' },
      { text: { es: 'No haría nada que lo dañe. Busco ascender por mis propios méritos.', en: 'I wouldn\'t do anything to harm them. I seek to advance by my own merits.', fr: 'Je ne ferais rien qui lui nuise. Je cherche à avancer par mes propres mérites.', de: 'Ich würde nichts tun, was ihm schadet. Ich suche durch meine eigenen Verdienste voranzukommen.', it: 'Non farei nulla che lo danneggi. Cerco di avanzare per i miei propri meriti.', pt: 'Não faria nada que o prejudique. Busco avançar pelos meus próprios méritos.' }, dimension: 'E' },
    ] },
    { id: 6, situation: { es: 'Una persona te pide dinero en la calle contándote una historia muy triste. No sabes si es verdad.', en: 'A person asks you for money on the street telling you a very sad story. You don\'t know if it\'s true.', fr: 'Une personne te demande de l\'argent dans la rue en te racontant une histoire très triste. Tu ne sais pas si c\'est vrai.', de: 'Eine Person bittet dich auf der Straße um Geld und erzählt dir eine sehr traurige Geschichte. Du weißt nicht, ob sie wahr ist.', it: 'Una persona ti chiede soldi per strada raccontandoti una storia molto triste. Non sai se è vera.', pt: 'Uma pessoa te pede dinheiro na rua contando uma história muito triste. Você não sabe se é verdade.' }, options: [
      { text: { es: 'Calculo la probabilidad de que sea cierto y actúo según el riesgo de ser engañado.', en: 'I calculate the probability of it being true and act based on the risk of being deceived.', fr: 'Je calcule la probabilité que ce soit vrai et agis selon le risque d\'être trompé.', de: 'Ich berechne die Wahrscheinlichkeit, dass es wahr ist, und handle entsprechend dem Risiko, betrogen zu werden.', it: 'Calcolo la probabilità che sia vero e agisco in base al rischio di essere ingannato.', pt: 'Calculo a probabilidade de ser verdade e ajo de acordo com o risco de ser enganado.' }, dimension: 'F' },
      { text: { es: 'Observo sus gestos y lenguaje corporal para detectar si miente antes de decidir.', en: 'I observe their gestures and body language to detect if they\'re lying before deciding.', fr: 'J\'observe ses gestes et son langage corporel pour détecter s\'il ment avant de décider.', de: 'Ich beobachte seine Gesten und Körpersprache, um festzustellen, ob er lügt, bevor ich entscheide.', it: 'Osservo i suoi gesti e il linguaggio del corpo per rilevare se mente prima di decidere.', pt: 'Observo os gestos e linguagem corporal para detectar se mente antes de decidir.' }, dimension: 'M' },
      { text: { es: 'Le doy algo sin pensar mucho. Mejor equivocarse por generoso que por tacaño.', en: 'I give them something without thinking much. Better to be wrong by being generous than stingy.', fr: 'Je lui donne quelque chose sans trop réfléchir. Mieux vaut se tromper par générosité que par avarice.', de: 'Ich gebe ihm etwas ohne viel nachzudenken. Besser, durch Großzügigkeit falsch zu liegen als durch Knauserigkeit.', it: 'Do qualcosa senza pensarci molto. Meglio sbagliare per generosità che per avarizia.', pt: 'Dou algo sem pensar muito. Melhor errar por generosidade do que por avareza.' }, dimension: 'I' },
      { text: { es: 'Le doy lo que puedo. Si me engaña, el problema es suyo, no mío.', en: 'I give what I can. If they deceive me, the problem is theirs, not mine.', fr: 'Je donne ce que je peux. S\'il me trompe, c\'est son problème, pas le mien.', de: 'Ich gebe was ich kann. Wenn er mich täuscht, ist das sein Problem, nicht meins.', it: 'Do quello che posso. Se mi inganna, il problema è suo, non mio.', pt: 'Dou o que posso. Se me engana, o problema é dele, não meu.' }, dimension: 'E' },
    ] },
    { id: 7, situation: { es: 'Estás en una relación y tu pareja hace algo que te molesta mucho. ¿Cómo reaccionas?', en: 'You\'re in a relationship and your partner does something that bothers you a lot. How do you react?', fr: 'Tu es en relation et ton partenaire fait quelque chose qui t\'agace beaucoup. Comment réagis-tu ?', de: 'Du bist in einer Beziehung und dein Partner tut etwas, das dich sehr stört. Wie reagierst du?', it: 'Sei in una relazione e il tuo partner fa qualcosa che ti infastidisce molto. Come reagisci?', pt: 'Você está em um relacionamento e seu parceiro faz algo que te incomoda muito. Como você reage?' }, options: [
      { text: { es: 'No reacciono en el momento. Anoto mentalmente el incidente para una conversación posterior.', en: 'I don\'t react at the moment. I mentally note the incident for a later conversation.', fr: 'Je ne réagis pas sur le moment. Je note mentalement l\'incident pour une conversation ultérieure.', de: 'Ich reagiere nicht sofort. Ich notiere den Vorfall gedanklich für ein späteres Gespräch.', it: 'Non reagisco nel momento. Annoto mentalmente l\'incidente per una conversazione successiva.', pt: 'Não reajo no momento. Anoto mentalmente o incidente para uma conversa posterior.' }, dimension: 'F' },
      { text: { es: 'Espero el momento oportuno para traerlo a colación cuando me sea más útil.', en: 'I wait for the right moment to bring it up when it\'s most useful to me.', fr: 'J\'attends le bon moment pour le soulever quand c\'est le plus utile pour moi.', de: 'Ich warte auf den richtigen Moment, es anzusprechen, wenn es für mich am nützlichsten ist.', it: 'Aspetto il momento opportuno per tirarlo fuori quando mi è più utile.', pt: 'Espero o momento oportuno para trazer à tona quando for mais útil para mim.' }, dimension: 'M' },
      { text: { es: 'Lo digo en el momento, aunque sea en un mal momento.', en: 'I say it at the moment, even if it\'s a bad moment.', fr: 'Je le dis sur le moment, même si c\'est un mauvais moment.', de: 'Ich sage es im Moment, auch wenn es ein schlechter Moment ist.', it: 'Lo dico nel momento, anche se è un momento sbagliato.', pt: 'Digo no momento, mesmo que seja um mau momento.' }, dimension: 'I' },
      { text: { es: 'Le digo que me molestó y trato de entender su perspectiva.', en: 'I tell them it bothered me and try to understand their perspective.', fr: 'Je lui dis que ça m\'a agacé et essaie de comprendre son point de vue.', de: 'Ich sage ihm, dass es mich gestört hat, und versuche seine Perspektive zu verstehen.', it: 'Gli dico che mi ha infastidito e cerco di capire la sua prospettiva.', pt: 'Digo que me incomodou e tento entender a perspectiva dele.' }, dimension: 'E' },
    ] },
    { id: 8, situation: { es: 'Un empleado tuyo comete un error grave que le cuesta un cliente importante a la empresa. Primera vez que falla.', en: 'An employee of yours makes a serious mistake that costs the company an important client. It\'s the first time they\'ve failed.', fr: 'Un de tes employés commet une erreur grave qui coûte un client important à l\'entreprise. C\'est la première fois qu\'il échoue.', de: 'Einer deiner Mitarbeiter macht einen schwerwiegenden Fehler, der die Firma einen wichtigen Kunden kostet. Es ist das erste Mal, dass er versagt.', it: 'Un tuo dipendente commette un errore grave che costa un cliente importante all\'azienda. È la prima volta che fallisce.', pt: 'Um funcionário seu comete um erro grave que custa um cliente importante à empresa. É a primeira vez que falha.' }, options: [
      { text: { es: 'Lo despido. No puedo permitir ese nivel de error. Las emociones no son parte de la ecuación.', en: 'I fire them. I can\'t allow that level of error. Emotions are not part of the equation.', fr: 'Je le licencie. Je ne peux pas permettre ce niveau d\'erreur. Les émotions ne font pas partie de l\'équation.', de: 'Ich entlasse ihn. Ich kann dieses Fehlerniveau nicht erlauben. Emotionen sind nicht Teil der Gleichung.', it: 'Lo licenzio. Non posso permettere quel livello di errore. Le emozioni non fanno parte dell\'equazione.', pt: 'Demito. Não posso permitir esse nível de erro. As emoções não fazem parte da equação.' }, dimension: 'F' },
      { text: { es: 'No lo despido, pero lo dejo saber que su posición ahora depende de compensar este error.', en: 'I don\'t fire them, but I let them know their position now depends on making up for this error.', fr: 'Je ne le licencie pas, mais je lui fais savoir que sa position dépend maintenant de compenser cette erreur.', de: 'Ich entlasse ihn nicht, aber ich lasse ihn wissen, dass seine Position nun davon abhängt, diesen Fehler auszugleichen.', it: 'Non lo licenzio, ma gli faccio sapere che la sua posizione ora dipende dal compensare questo errore.', pt: 'Não demito, mas deixo saber que sua posição agora depende de compensar esse erro.' }, dimension: 'M' },
      { text: { es: 'Reacciono inmediatamente con enojo y lo confronto delante del equipo.', en: 'I immediately react with anger and confront them in front of the team.', fr: 'Je réagis immédiatement avec colère et le confronte devant l\'équipe.', de: 'Ich reagiere sofort mit Ärger und konfrontiere ihn vor dem Team.', it: 'Reagisco immediatamente con rabbia e lo confronto davanti al team.', pt: 'Reajo imediatamente com raiva e o confronto na frente da equipe.' }, dimension: 'I' },
      { text: { es: 'Hablo con él en privado, entiendo qué pasó y diseñamos juntos cómo evitarlo.', en: 'I talk to them privately, understand what happened, and we design together how to avoid it.', fr: 'Je lui parle en privé, comprends ce qui s\'est passé et nous concevons ensemble comment l\'éviter.', de: 'Ich spreche privat mit ihm, verstehe was passiert ist, und wir entwerfen gemeinsam, wie wir es vermeiden können.', it: 'Parlo con lui in privato, capisco cosa è successo e progettiamo insieme come evitarlo.', pt: 'Falo com ele em particular, entendo o que aconteceu e planejamos juntos como evitar.' }, dimension: 'E' },
    ] },
    { id: 9, situation: { es: 'Ves un video viral de alguien humillado públicamente. La mayoría lo encuentra gracioso.', en: 'You see a viral video of someone being publicly humiliated. Most people find it funny.', fr: 'Tu vois une vidéo virale de quelqu\'un humilié publiquement. La plupart la trouve drôle.', de: 'Du siehst ein virales Video, in dem jemand öffentlich gedemütigt wird. Die meisten finden es lustig.', it: 'Vedi un video virale di qualcuno umiliato pubblicamente. La maggior parte lo trova divertente.', pt: 'Você vê um vídeo viral de alguém humilhado publicamente. A maioria acha engraçado.' }, options: [
      { text: { es: 'Lo miro con curiosidad pero sin emoción particular. Me pregunto qué llevó a esa situación.', en: 'I watch it with curiosity but no particular emotion. I wonder what led to that situation.', fr: 'Je le regarde avec curiosité mais sans émotion particulière. Je me demande ce qui a conduit à cette situation.', de: 'Ich schaue es mit Neugier aber ohne besondere Emotion an. Ich frage mich, was zu dieser Situation geführt hat.', it: 'Lo guardo con curiosità ma senza emozione particolare. Mi chiedo cosa ha portato a quella situazione.', pt: 'Assisto com curiosidade mas sem emoção particular. Me pergunto o que levou a essa situação.' }, dimension: 'F' },
      { text: { es: 'Lo analizo: ¿quién publicó esto? ¿qué obtienen con ello?', en: 'I analyze it: who posted this? What do they get from it?', fr: 'Je l\'analyse: qui a publié ça? Qu\'est-ce qu\'ils en tirent ?', de: 'Ich analysiere es: Wer hat das gepostet? Was bekommen sie dafür?', it: 'Lo analizzo: chi ha pubblicato questo? Cosa ottengono da ciò?', pt: 'Analiso: quem postou isso? O que ganham com isso?' }, dimension: 'M' },
      { text: { es: 'Si es gracioso, me río. Si no, lo cierro. Reacciono en el momento sin pensarlo.', en: 'If it\'s funny, I laugh. If not, I close it. I react at the moment without thinking.', fr: 'Si c\'est drôle, je ris. Sinon, je le ferme. Je réagis sur le moment sans réfléchir.', de: 'Wenn es lustig ist, lache ich. Wenn nicht, schließe ich es. Ich reagiere im Moment ohne nachzudenken.', it: 'Se è divertente, rido. Se no, lo chiudo. Reagisco nel momento senza pensarci.', pt: 'Se for engraçado, rio. Se não, fecho. Reajo no momento sem pensar.' }, dimension: 'I' },
      { text: { es: 'Me incomoda. Pienso en cómo se siente esa persona al ver su peor momento viralizado.', en: 'It makes me uncomfortable. I think about how that person feels seeing their worst moment go viral.', fr: 'Ça me dérange. Je pense à comment cette personne se sent en voyant son pire moment viraliser.', de: 'Es macht mich unwohl. Ich denke darüber nach, wie sich diese Person fühlt, wenn sie ihren schlimmsten Moment viral gehen sieht.', it: 'Mi mette a disagio. Penso a come si sente quella persona nel vedere il suo peggior momento diventare virale.', pt: 'Me incomoda. Penso em como essa pessoa se sente ao ver seu pior momento viralizado.' }, dimension: 'E' },
    ] },
    { id: 10, situation: { es: 'Descubres que un buen amigo habló mal de ti a tus espaldas con un grupo de personas.', en: 'You discover that a good friend bad-mouthed you behind your back with a group of people.', fr: 'Tu découvres qu\'un bon ami t\'a critiqué dans ton dos devant un groupe de personnes.', de: 'Du entdeckst, dass ein guter Freund hinter deinem Rücken schlecht über dich vor einer Gruppe gesprochen hat.', it: 'Scopri che un buon amico ha parlato male di te alle tue spalle con un gruppo di persone.', pt: 'Você descobre que um bom amigo falou mal de você pelas suas costas com um grupo de pessoas.' }, options: [
      { text: { es: 'No reacciono de inmediato. Evalúo si esta persona sigue siendo útil en mi red social.', en: 'I don\'t react immediately. I evaluate whether this person is still useful in my social network.', fr: 'Je ne réagis pas immédiatement. J\'évalue si cette personne est encore utile dans mon réseau social.', de: 'Ich reagiere nicht sofort. Ich bewerte, ob diese Person noch nützlich in meinem sozialen Netzwerk ist.', it: 'Non reagisco immediatamente. Valuto se questa persona è ancora utile nella mia rete sociale.', pt: 'Não reajo imediatamente. Avalio se essa pessoa ainda é útil na minha rede social.' }, dimension: 'F' },
      { text: { es: 'Actúo como si no supiera nada y espero el momento ideal para devolverle el favor.', en: 'I act as if I don\'t know anything and wait for the ideal moment to return the favor.', fr: 'J\'agis comme si je ne savais rien et attends le moment idéal pour lui rendre la pareille.', de: 'Ich tue so, als wüsste ich nichts, und warte auf den idealen Moment, um es zu erwidern.', it: 'Agisco come se non sapessi niente e aspetto il momento ideale per ricambiare il favore.', pt: 'Ajo como se não soubesse nada e espero o momento ideal para devolver o favor.' }, dimension: 'M' },
      { text: { es: 'Lo confronto inmediatamente, enojado y directo.', en: 'I confront them immediately, angry and direct.', fr: 'Je le confronte immédiatement, en colère et direct.', de: 'Ich konfrontiere ihn sofort, wütend und direkt.', it: 'Lo confronto immediatamente, arrabbiato e diretto.', pt: 'Confronto imediatamente, com raiva e direto.' }, dimension: 'I' },
      { text: { es: 'Lo confronto con tristeza, no con rabia. Quiero entender por qué lo hizo.', en: 'I confront them with sadness, not anger. I want to understand why they did it.', fr: 'Je le confronte avec tristesse, pas avec colère. Je veux comprendre pourquoi il l\'a fait.', de: 'Ich konfrontiere ihn mit Traurigkeit, nicht mit Wut. Ich möchte verstehen, warum er es getan hat.', it: 'Lo confronto con tristezza, non con rabbia. Voglio capire perché l\'ha fatto.', pt: 'Confronto com tristeza, não com raiva. Quero entender por que fez isso.' }, dimension: 'E' },
    ] },
  ],
  characters: [
    { name: { es: 'Steve Jobs', en: 'Steve Jobs', fr: 'Steve Jobs', de: 'Steve Jobs', it: 'Steve Jobs', pt: 'Steve Jobs' }, dimensions: ['F'], photo: '/characters/jobs.jpg', description: { es: 'Visionario glacial: brillante, cruel cuando lo consideraba necesario.', en: 'Glacial visionary: brilliant, cruel when he considered it necessary.', fr: 'Visionnaire glacial: brillant, cruel quand il le jugeait nécessaire.', de: 'Eisiger Visionär: brillant, grausam wenn er es für nötig hielt.', it: 'Visionario glaciale: brillante, crudele quando lo riteneva necessario.', pt: 'Visionário glacial: brilhante, cruel quando considerava necessário.' }, philosophy: { es: 'Tu mente es una máquina de alta precisión. Las emociones son ruido. Las relaciones son recursos. No eres malvado — eres simplemente claro sobre lo que quieres, y el camino más corto siempre te parece el correcto.', en: 'Your mind is a high-precision machine. Emotions are noise. Relationships are resources. You\'re not evil — you\'re simply clear about what you want, and the shortest path always seems correct to you.', fr: 'Ton esprit est une machine de haute précision. Les émotions sont du bruit. Les relations sont des ressources. Tu n\'es pas malveillant — tu es simplement clair sur ce que tu veux, et le chemin le plus court te semble toujours correct.', de: 'Dein Geist ist eine hochpräzise Maschine. Emotionen sind Lärm. Beziehungen sind Ressourcen. Du bist nicht böse — du bist einfach klar darüber, was du willst, und der kürzeste Weg scheint dir immer richtig.', it: 'La tua mente è una macchina ad alta precisione. Le emozioni sono rumore. Le relazioni sono risorse. Non sei malvagio — sei semplicemente chiaro su quello che vuoi, e il percorso più breve ti sembra sempre quello corretto.', pt: 'Sua mente é uma máquina de alta precisão. As emoções são ruído. Os relacionamentos são recursos. Você não é mau — você é simplesmente claro sobre o que quer, e o caminho mais curto sempre parece correto para você.' } },
    { name: { es: 'Maquiavelo', en: 'Machiavelli', fr: 'Machiavel', de: 'Machiavelli', it: 'Machiavelli', pt: 'Maquiavel' }, dimensions: ['M'], photo: '/characters/machiavelli.jpg', description: { es: 'El arquitecto de la manipulación política: nunca actúa sin calcular el efecto sobre los demás.', en: 'The architect of political manipulation: never acts without calculating the effect on others.', fr: 'L\'architecte de la manipulation politique: n\'agit jamais sans calculer l\'effet sur les autres.', de: 'Der Architekt politischer Manipulation: handelt nie ohne den Effekt auf andere zu berechnen.', it: 'L\'architetto della manipolazione politica: non agisce mai senza calcolare l\'effetto sugli altri.', pt: 'O arquiteto da manipulação política: nunca age sem calcular o efeito sobre os outros.' }, philosophy: { es: 'Para ti, entender cómo funciona la gente es una herramienta, no un defecto. No engañas por placer — engañas por eficiencia. El poder no es malo; lo malo es no saber usarlo.', en: 'For you, understanding how people work is a tool, not a flaw. You don\'t deceive for pleasure — you deceive for efficiency. Power is not bad; what\'s bad is not knowing how to use it.', fr: 'Pour toi, comprendre comment fonctionnent les gens est un outil, pas un défaut. Tu ne trompes pas par plaisir — tu trompes par efficacité. Le pouvoir n\'est pas mauvais; ce qui est mauvais c\'est de ne pas savoir l\'utiliser.', de: 'Für dich ist das Verstehen, wie Menschen funktionieren, ein Werkzeug, kein Fehler. Du täuschst nicht zum Vergnügen — du täuschst der Effizienz halber. Macht ist nicht schlecht; schlecht ist es, nicht zu wissen, wie man sie einsetzt.', it: 'Per te, capire come funzionano le persone è uno strumento, non un difetto. Non inganni per piacere — inganni per efficienza. Il potere non è cattivo; ciò che è cattivo è non saper usarlo.', pt: 'Para você, entender como as pessoas funcionam é uma ferramenta, não um defeito. Você não engana por prazer — engana por eficiência. O poder não é ruim; o que é ruim é não saber usá-lo.' } },
    { name: { es: 'Mike Tyson', en: 'Mike Tyson', fr: 'Mike Tyson', de: 'Mike Tyson', it: 'Mike Tyson', pt: 'Mike Tyson' }, dimensions: ['I'], photo: '/characters/tyson.jpg', description: { es: 'Explosivo, sin filtros, actúa antes de pensar y lo sabe perfectamente.', en: 'Explosive, unfiltered, acts before thinking and knows it perfectly.', fr: 'Explosif, sans filtre, agit avant de réfléchir et le sait parfaitement.', de: 'Explosiv, ungefiltert, handelt bevor er denkt und weiß es genau.', it: 'Esplosivo, senza filtri, agisce prima di pensare e lo sa perfettamente.', pt: 'Explosivo, sem filtros, age antes de pensar e sabe disso perfeitamente.' }, philosophy: { es: 'Tu fuerza y tu debilidad son la misma cosa: el fuego. Sientes todo con intensidad máxima y reaccionas antes de que la mente pueda mediar. A veces eso es una superpotencia. A veces, un desastre.', en: 'Your strength and your weakness are the same thing: fire. You feel everything at maximum intensity and react before the mind can mediate. Sometimes that\'s a superpower. Sometimes, a disaster.', fr: 'Ta force et ta faiblesse sont la même chose: le feu. Tu ressens tout avec une intensité maximale et réagis avant que l\'esprit puisse servir de médiateur. Parfois c\'est un superpouvoir. Parfois, un désastre.', de: 'Deine Stärke und deine Schwäche sind dasselbe: Feuer. Du fühlst alles mit maximaler Intensität und reagierst, bevor der Geist vermitteln kann. Manchmal ist das eine Superkraft. Manchmal eine Katastrophe.', it: 'La tua forza e la tua debolezza sono la stessa cosa: il fuoco. Senti tutto con intensità massima e reagisci prima che la mente possa mediare. A volte è un superpotere. A volte, un disastro.', pt: 'Sua força e sua fraqueza são a mesma coisa: o fogo. Você sente tudo com intensidade máxima e reage antes que a mente possa mediar. Às vezes isso é um superpoder. Às vezes, um desastre.' } },
    { name: { es: 'Brené Brown', en: 'Brené Brown', fr: 'Brené Brown', de: 'Brené Brown', it: 'Brené Brown', pt: 'Brené Brown' }, dimensions: ['E'], photo: '/characters/brene.jpg', description: { es: 'Investigadora de la vulnerabilidad que convirtió la empatía en su mayor fortaleza.', en: 'Vulnerability researcher who turned empathy into her greatest strength.', fr: 'Chercheuse sur la vulnérabilité qui a fait de l\'empathie sa plus grande force.', de: 'Vulnerabilitätsforscherin, die Empathie zu ihrer größten Stärke gemacht hat.', it: 'Ricercatrice della vulnerabilità che ha fatto dell\'empatia la sua più grande forza.', pt: 'Pesquisadora da vulnerabilidade que transformou a empatia em sua maior força.' }, philosophy: { es: 'Tu capacidad de sentir lo que sienten otros no es una debilidad — es tu radar más preciso. Lees las salas con precisión emocional que la mayoría no tiene. La conexión humana es tu lenguaje nativo.', en: 'Your ability to feel what others feel is not a weakness — it\'s your most precise radar. You read rooms with emotional precision most don\'t have. Human connection is your native language.', fr: 'Ta capacité à ressentir ce que ressentent les autres n\'est pas une faiblesse — c\'est ton radar le plus précis. Tu lis les pièces avec une précision émotionnelle que la plupart n\'ont pas. La connexion humaine est ta langue maternelle.', de: 'Deine Fähigkeit, zu fühlen, was andere fühlen, ist keine Schwäche — es ist dein präzisestes Radar. Du liest Räume mit emotionaler Präzision, die die meisten nicht haben. Menschliche Verbindung ist deine Muttersprache.', it: 'La tua capacità di sentire ciò che sentono gli altri non è una debolezza — è il tuo radar più preciso. Leggi le stanze con precisione emotiva che la maggior parte non ha. La connessione umana è la tua lingua madre.', pt: 'Sua capacidade de sentir o que os outros sentem não é uma fraqueza — é seu radar mais preciso. Você lê as salas com precisão emocional que a maioria não tem. A conexão humana é sua língua nativa.' } },
    { name: { es: 'Pablo Escobar', en: 'Pablo Escobar', fr: 'Pablo Escobar', de: 'Pablo Escobar', it: 'Pablo Escobar', pt: 'Pablo Escobar' }, dimensions: ['F', 'M'], photo: '/characters/escobar.jpg', description: { es: 'Frío con los enemigos, calculadoramente encantador con los aliados.', en: 'Cold with enemies, calculatingly charming with allies.', fr: 'Froid avec les ennemis, calculablement charmant avec les alliés.', de: 'Kalt mit Feinden, berechnend charmant mit Verbündeten.', it: 'Freddo con i nemici, calcolatamente affascinante con gli alleati.', pt: 'Frio com os inimigos, calculadamente charmoso com os aliados.' }, philosophy: { es: 'Tu mente combina distancia emocional con inteligencia social. Sabes exactamente qué decir y cuándo, y no te cuesta nada actuar de forma diferente según quién tengas enfrente.', en: 'Your mind combines emotional distance with social intelligence. You know exactly what to say and when, and it costs you nothing to act differently depending on who you\'re facing.', fr: 'Ton esprit combine distance émotionnelle et intelligence sociale. Tu sais exactement quoi dire et quand, et ça ne te coûte rien d\'agir différemment selon la personne en face de toi.', de: 'Dein Geist kombiniert emotionale Distanz mit sozialer Intelligenz. Du weißt genau, was du wann sagen sollst, und es kostet dich nichts, anders zu handeln, je nachdem, wen du dir gegenübersiehst.', it: 'La tua mente combina distanza emotiva con intelligenza sociale. Sai esattamente cosa dire e quando, e non ti costa niente agire diversamente a seconda di chi hai di fronte.', pt: 'Sua mente combina distância emocional com inteligência social. Você sabe exatamente o que dizer e quando, e não custa nada agir de forma diferente dependendo de quem tem à frente.' } },
    { name: { es: 'Napoleón Bonaparte', en: 'Napoleon Bonaparte', fr: 'Napoléon Bonaparte', de: 'Napoleon Bonaparte', it: 'Napoleone Bonaparte', pt: 'Napoleão Bonaparte' }, dimensions: ['F', 'I'], photo: '/characters/napoleon.jpg', description: { es: 'Estratega implacable con destellos de impulsividad que lo perdieron.', en: 'Relentless strategist with flashes of impulsivity that undid him.', fr: 'Stratège implacable avec des éclairs d\'impulsivité qui l\'ont perdu.', de: 'Unerbittlicher Stratege mit Aufblitzen von Impulsivität, die ihn ruinierten.', it: 'Stratega implacabile con lampi di impulsività che lo hanno distrutto.', pt: 'Estrategista implacável com flashes de impulsividade que o perderam.' }, philosophy: { es: 'Tu mente piensa a largo plazo, pero tus emociones a veces explotan en el peor momento. Eres más calculador de lo que pareces y más impulsivo de lo que quisieras. Una combinación volátil y poderosa.', en: 'Your mind thinks long-term, but your emotions sometimes explode at the worst moment. You\'re more calculating than you appear and more impulsive than you\'d like. A volatile and powerful combination.', fr: 'Ton esprit pense à long terme, mais tes émotions explosent parfois au pire moment. Tu es plus calculateur que tu n\'en as l\'air et plus impulsif que tu ne le voudrais. Une combinaison volatile et puissante.', de: 'Dein Geist denkt langfristig, aber deine Emotionen explodieren manchmal im schlimmsten Moment. Du bist berechnender als du aussieht und impulsiver als du möchtest. Eine volatile und kraftvolle Kombination.', it: 'La tua mente pensa a lungo termine, ma le tue emozioni a volte esplodono nel momento peggiore. Sei più calcolatore di quanto sembri e più impulsivo di quanto vorresti. Una combinazione volatile e potente.', pt: 'Sua mente pensa a longo prazo, mas suas emoções às vezes explodem no pior momento. Você é mais calculista do que parece e mais impulsivo do que gostaria. Uma combinação volátil e poderosa.' } },
    { name: { es: 'Frank Underwood', en: 'Frank Underwood', fr: 'Frank Underwood', de: 'Frank Underwood', it: 'Frank Underwood', pt: 'Frank Underwood' }, dimensions: ['M', 'I'], photo: '/characters/underwood.jpg', description: { es: 'Manipulador brillante que a veces quema sus puentes por impaciencia.', en: 'Brilliant manipulator who sometimes burns his bridges out of impatience.', fr: 'Manipulateur brillant qui brûle parfois ses ponts par impatience.', de: 'Brillanter Manipulator, der manchmal seine Brücken aus Ungeduld abbrennt.', it: 'Manipolatore brillante che a volte brucia i suoi ponti per impazienza.', pt: 'Manipulador brilhante que às vezes queima suas pontes por impaciência.' }, philosophy: { es: 'Sabes exactamente qué botones presionar en cada persona — y a veces los presionas antes de tiempo solo porque puedes. Tu mayor defecto es tu mayor talento: la impaciencia de quien sabe que siempre tiene razón.', en: 'You know exactly which buttons to push in each person — and sometimes you push them prematurely just because you can. Your greatest flaw is your greatest talent: the impatience of someone who knows they\'re always right.', fr: 'Tu sais exactement quels boutons appuyer chez chaque personne — et parfois tu les appuies prématurément juste parce que tu peux. Ton plus grand défaut est ton plus grand talent: l\'impatience de celui qui sait toujours avoir raison.', de: 'Du weißt genau, welche Knöpfe du bei jeder Person drücken musst — und manchmal drückst du sie vorzeitig nur weil du kannst. Dein größter Fehler ist dein größtes Talent: die Ungeduld dessen, der weiß, dass er immer Recht hat.', it: 'Sai esattamente quali pulsanti premere in ogni persona — e a volte li premi prematuramente solo perché puoi. Il tuo più grande difetto è il tuo più grande talento: l\'impazienza di chi sa di avere sempre ragione.', pt: 'Você sabe exatamente quais botões apertar em cada pessoa — e às vezes os aperta antes do tempo só porque pode. Seu maior defeito é seu maior talento: a impaciência de quem sabe que sempre tem razão.' } },
    { name: { es: 'Bill Clinton', en: 'Bill Clinton', fr: 'Bill Clinton', de: 'Bill Clinton', it: 'Bill Clinton', pt: 'Bill Clinton' }, dimensions: ['M', 'E'], photo: '/characters/clinton.jpg', description: { es: 'El político más empático de su generación — que también sabía manipular perfectamente esa empatía.', en: 'The most empathetic politician of his generation — who also knew how to perfectly manipulate that empathy.', fr: 'Le politicien le plus empathique de sa génération — qui savait aussi parfaitement manipuler cette empathie.', de: 'Der empathischste Politiker seiner Generation — der auch wusste, wie er diese Empathie perfekt manipulieren konnte.', it: 'Il politico più empatico della sua generazione — che sapeva anche manipolare perfettamente quell\'empatia.', pt: 'O político mais empático de sua geração — que também sabia manipular perfeitamente essa empatia.' }, philosophy: { es: 'Sientes genuinamente lo que sienten los demás, y eso te hace magnético. También sabes cómo usar esa conexión estratégicamente. No es hipocresía — es ser humano al máximo nivel de complejidad.', en: 'You genuinely feel what others feel, and that makes you magnetic. You also know how to use that connection strategically. It\'s not hypocrisy — it\'s being human at the highest level of complexity.', fr: 'Tu ressens genuinement ce que ressentent les autres, et ça te rend magnétique. Tu sais aussi comment utiliser cette connexion stratégiquement. Ce n\'est pas de l\'hypocrisie — c\'est être humain au niveau maximum de complexité.', de: 'Du fühlst aufrichtig, was andere fühlen, und das macht dich magnetisch. Du weißt auch, wie du diese Verbindung strategisch nutzen kannst. Das ist keine Heuchelei — es ist Menschsein auf höchstem Komplexitätsniveau.', it: 'Senti genuinamente ciò che sentono gli altri, e questo ti rende magnetico. Sai anche come usare quella connessione strategicamente. Non è ipocrisia — è essere umani al massimo livello di complessità.', pt: 'Você sente genuinamente o que os outros sentem, e isso te torna magnético. Você também sabe como usar essa conexão estrategicamente. Não é hipocrisia — é ser humano no nível máximo de complexidade.' } },
  ],
};

export async function seedPsychopath(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'psychopath' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'psychopath',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['dark-personality'],
      sortOrder: 1,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
