import type { PrismaClient } from '../../generated/prisma/client.js';

export async function seedClassist(prisma: PrismaClient, catMap: Record<string, string>) {
  const data = {
    slug: 'classist',
    title: { es: '¿Qué tan clasista eres?', en: 'How classist are you?', fr: 'À quel point êtes-vous classiste ?', de: 'Wie klassenbewusst bist du?', it: 'Quanto sei classista?', pt: 'Quão classista você é?' },
    description: { es: 'El clasismo es el privilegio invisible. Cuanto más cómodo estás, menos lo ves.', en: 'Classism is invisible privilege. The more comfortable you are, the less you see it.', fr: 'Le classisme est le privilège invisible. Plus vous êtes à l\'aise, moins vous le voyez.', de: 'Klassismus ist das unsichtbare Privileg. Je komfortabler du bist, desto weniger siehst du es.', it: 'Il classismo è il privilegio invisibile. Più sei a tuo agio, meno lo vedi.', pt: 'O classismo é o privilégio invisível. Quanto mais confortável você está, menos o vê.' },
    scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
    categoryId: catMap['moral'],
    sortOrder: 2,
    dimensionLabels: {
      es: { C: 'Clasismo', E: 'Empatía de Clase', M: 'Meritocracia', S: 'Solidaridad' },
      en: { C: 'Classism', E: 'Class Empathy', M: 'Meritocracy', S: 'Solidarity' },
      fr: { C: 'Classisme', E: 'Empathie de Classe', M: 'Méritocratie', S: 'Solidarité' },
      de: { C: 'Klassismus', E: 'Klassenempathie', M: 'Meritokratie', S: 'Solidarität' },
      it: { C: 'Classismo', E: 'Empatia di Classe', M: 'Meritocrazia', S: 'Solidarietà' },
      pt: { C: 'Classismo', E: 'Empatia de Classe', M: 'Meritocracia', S: 'Solidariedade' },
    },
    questions: [
      {
        id: 1,
        situation: { es: 'Alguien que trabaja en servicio al cliente te da una respuesta que sientes que podría mejorar.', en: 'A customer service worker gives you a response you feel could be better.', fr: 'Un employé du service client vous donne une réponse que vous trouvez perfectible.', de: 'Ein Kundendienstmitarbeiter gibt dir eine Antwort, von der du findest, dass sie besser sein könnte.', it: 'Un addetto al servizio clienti ti dà una risposta che senti potrebbe essere migliore.', pt: 'Um atendente de serviço ao cliente te dá uma resposta que você acha que poderia ser melhor.' },
        options: [
          { text: { es: 'Soy más exigente de lo habitual. Espero un nivel de servicio específico.', en: 'I\'m more demanding than usual. I expect a specific level of service.', fr: 'Je suis plus exigeant(e) que d\'habitude. J\'attends un certain niveau de service.', de: 'Ich bin anspruchsvoller als sonst. Ich erwarte ein bestimmtes Serviceniveau.', it: 'Sono più esigente del solito. Mi aspetto un livello specifico di servizio.', pt: 'Sou mais exigente do que o habitual. Espero um nível específico de serviço.' }, dimension: 'C' },
          { text: { es: 'Pienso en las condiciones de trabajo de esa persona antes de juzgar su desempeño.', en: 'I think about that person\'s working conditions before judging their performance.', fr: 'Je pense aux conditions de travail de cette personne avant de juger ses performances.', de: 'Ich denke an die Arbeitsbedingungen dieser Person, bevor ich ihre Leistung beurteile.', it: 'Penso alle condizioni lavorative di quella persona prima di giudicare le sue prestazioni.', pt: 'Penso nas condições de trabalho dessa pessoa antes de julgar seu desempenho.' }, dimension: 'E' },
          { text: { es: 'Evalúo el servicio por sus méritos, independientemente de quien lo presta.', en: 'I evaluate the service on its merits, regardless of who provides it.', fr: 'J\'évalue le service selon ses mérites, indépendamment de qui le fournit.', de: 'Ich bewerte den Service nach seinen Verdiensten, unabhängig davon, wer ihn erbringt.', it: 'Valuto il servizio per i suoi meriti, indipendentemente da chi lo fornisce.', pt: 'Avalio o serviço pelos seus méritos, independentemente de quem o presta.' }, dimension: 'M' },
          { text: { es: 'Soy especialmente paciente. Las personas en esos trabajos merecen más paciencia, no menos.', en: 'I\'m especially patient. People in those jobs deserve more patience, not less.', fr: 'Je suis particulièrement patient(e). Les personnes dans ces emplois méritent plus de patience, pas moins.', de: 'Ich bin besonders geduldig. Menschen in diesen Jobs verdienen mehr Geduld, nicht weniger.', it: 'Sono particolarmente paziente. Le persone in quei lavori meritano più pazienza, non meno.', pt: 'Sou especialmente paciente. As pessoas nesses trabalhos merecem mais paciência, não menos.' }, dimension: 'S' },
        ],
      },
      {
        id: 2,
        situation: { es: 'Alguien llega a una reunión con ropa claramente de menor costo. ¿Cómo afecta tu percepción inicial?', en: 'Someone arrives at a meeting wearing clearly inexpensive clothes. How does that affect your initial perception?', fr: 'Quelqu\'un arrive à une réunion avec des vêtements clairement bon marché. Comment cela affecte-t-il votre perception initiale ?', de: 'Jemand kommt zu einem Meeting mit offensichtlich günstiger Kleidung. Wie beeinflusst das deine erste Wahrnehmung?', it: 'Qualcuno arriva a una riunione con abiti chiaramente economici. Come influisce sulla tua percezione iniziale?', pt: 'Alguém chega a uma reunião com roupas claramente de menor custo. Como isso afeta sua percepção inicial?' },
        options: [
          { text: { es: 'Sin quererlo, formo una primera impresión menos favorable.', en: 'Without meaning to, I form a less favorable first impression.', fr: 'Sans le vouloir, je me fais une première impression moins favorable.', de: 'Ohne es zu wollen, bilde ich einen weniger günstigen ersten Eindruck.', it: 'Senza volerlo, mi formo una prima impressione meno favorevole.', pt: 'Sem querer, formo uma primeira impressão menos favorável.' }, dimension: 'C' },
          { text: { es: 'Noto si tengo esa reacción y la cuestiono.', en: 'I notice if I have that reaction and question it.', fr: 'Je remarque si j\'ai cette réaction et je la questionne.', de: 'Ich bemerke, ob ich diese Reaktion habe, und hinterfrage sie.', it: 'Noto se ho quella reazione e la metto in discussione.', pt: 'Noto se tenho essa reação e a questiono.' }, dimension: 'E' },
          { text: { es: 'No me afecta. La ropa no dice nada de las capacidades de alguien.', en: 'It doesn\'t affect me. Clothing says nothing about someone\'s abilities.', fr: 'Ça ne m\'affecte pas. Les vêtements ne disent rien des capacités de quelqu\'un.', de: 'Es beeinflusst mich nicht. Kleidung sagt nichts über die Fähigkeiten von jemandem aus.', it: 'Non mi influisce. I vestiti non dicono nulla delle capacità di qualcuno.', pt: 'Não me afeta. A roupa não diz nada sobre as capacidades de alguém.' }, dimension: 'M' },
          { text: { es: 'Hago un esfuerzo activo de conectar con esa persona para compensar sesgos sociales existentes.', en: 'I make an active effort to connect with that person to counteract existing social biases.', fr: 'Je fais un effort actif pour me connecter avec cette personne afin de compenser les biais sociaux existants.', de: 'Ich bemühe mich aktiv, mit dieser Person in Kontakt zu treten, um bestehende soziale Vorurteile auszugleichen.', it: 'Faccio uno sforzo attivo per connettermi con quella persona per compensare i pregiudizi sociali esistenti.', pt: 'Faço um esforço ativo para me conectar com essa pessoa para compensar os preconceitos sociais existentes.' }, dimension: 'S' },
        ],
      },
      {
        id: 3,
        situation: { es: 'Una persona que trabaja en construcción da una opinión política en una conversación. ¿Cómo la recibes?', en: 'A construction worker shares a political opinion in conversation. How do you receive it?', fr: 'Une personne travaillant dans le bâtiment donne un avis politique dans une conversation. Comment le recevez-vous ?', de: 'Eine Person, die im Baugewerbe arbeitet, gibt bei einem Gespräch eine politische Meinung ab. Wie nimmst du sie auf?', it: 'Una persona che lavora nell\'edilizia esprime un\'opinione politica in una conversazione. Come la ricevi?', pt: 'Uma pessoa que trabalha na construção civil dá uma opinião política em uma conversa. Como você a recebe?' },
        options: [
          { text: { es: 'Internamente le doy menos peso que si la dijera un profesional universitario.', en: 'Internally I give it less weight than if a university-educated professional said it.', fr: 'Intérieurement, je lui accorde moins de poids que si un professionnel universitaire l\'avait dit.', de: 'Innerlich gebe ich ihr weniger Gewicht, als wenn es ein Hochschulabsolvent gesagt hätte.', it: 'Internamente le attribuisco meno peso di quanto farei se lo dicesse un professionista universitario.', pt: 'Internamente dou menos peso do que se fosse dita por um profissional universitário.' }, dimension: 'C' },
          { text: { es: 'Me pregunto si hay sesgos en cómo escucho según quién habla.', en: 'I ask myself if there are biases in how I listen depending on who is speaking.', fr: 'Je me demande s\'il y a des biais dans ma façon d\'écouter selon qui parle.', de: 'Ich frage mich, ob es Vorurteile darin gibt, wie ich zuhöre, je nachdem wer spricht.', it: 'Mi chiedo se ci siano pregiudizi nel modo in cui ascolto a seconda di chi parla.', pt: 'Me pergunto se há preconceitos em como ouço dependendo de quem fala.' }, dimension: 'E' },
          { text: { es: 'La evalúo por el argumento, no por quien la dice.', en: 'I evaluate it by the argument, not by who says it.', fr: 'Je l\'évalue par l\'argument, pas par celui qui le dit.', de: 'Ich bewerte es nach dem Argument, nicht danach, wer es sagt.', it: 'La valuto per l\'argomento, non per chi la dice.', pt: 'A avalio pelo argumento, não por quem a diz.' }, dimension: 'M' },
          { text: { es: 'La recibo con el mismo valor que cualquier otra. La experiencia de vida es conocimiento.', en: 'I receive it with the same value as any other. Life experience is knowledge.', fr: 'Je la reçois avec la même valeur que n\'importe quelle autre. L\'expérience de vie est une forme de connaissance.', de: 'Ich nehme sie mit dem gleichen Wert wie jede andere auf. Lebenserfahrung ist Wissen.', it: 'La ricevo con lo stesso valore di qualsiasi altra. L\'esperienza di vita è conoscenza.', pt: 'Recebo com o mesmo valor que qualquer outra. A experiência de vida é conhecimento.' }, dimension: 'S' },
        ],
      },
      {
        id: 4,
        situation: { es: 'Escuchas que alguien compró algo que considera un lujo pero que para ti sería muy básico. ¿Qué piensas?', en: 'You hear that someone bought something they consider a luxury, but which would be very basic for you. What do you think?', fr: 'Vous apprenez que quelqu\'un a acheté quelque chose qu\'il considère comme un luxe, mais qui serait très basique pour vous. Qu\'en pensez-vous ?', de: 'Du erfährst, dass jemand etwas gekauft hat, das er als Luxus betrachtet, das für dich aber sehr einfach wäre. Was denkst du?', it: 'Senti che qualcuno ha comprato qualcosa che considera un lusso ma che per te sarebbe molto basilare. Cosa pensi?', pt: 'Você ouve que alguém comprou algo que considera um luxo, mas que para você seria muito básico. O que você pensa?' },
        options: [
          { text: { es: 'Pienso que sus prioridades económicas no son las más inteligentes.', en: 'I think their financial priorities aren\'t the smartest.', fr: 'Je pense que ses priorités économiques ne sont pas les plus intelligentes.', de: 'Ich denke, dass seine wirtschaftlichen Prioritäten nicht die klügsten sind.', it: 'Penso che le sue priorità economiche non siano le più intelligenti.', pt: 'Penso que suas prioridades econômicas não são as mais inteligentes.' }, dimension: 'C' },
          { text: { es: 'Recuerdo que el lujo es completamente relativo al contexto económico de cada quien.', en: 'I remind myself that luxury is entirely relative to each person\'s economic context.', fr: 'Je me rappelle que le luxe est complètement relatif au contexte économique de chacun.', de: 'Ich erinnere mich, dass Luxus vollständig relativ zum wirtschaftlichen Kontext jedes Einzelnen ist.', it: 'Ricordo a me stesso che il lusso è completamente relativo al contesto economico di ognuno.', pt: 'Lembro que o luxo é completamente relativo ao contexto econômico de cada um.' }, dimension: 'E' },
          { text: { es: 'Si le alcanzó el dinero y era lo que quería, está bien.', en: 'If they had the money and it\'s what they wanted, that\'s fine.', fr: 'S\'ils avaient l\'argent et que c\'est ce qu\'ils voulaient, c\'est très bien.', de: 'Wenn sie das Geld hatten und es das war, was sie wollten, ist das in Ordnung.', it: 'Se avevano i soldi e era quello che volevano, va bene.', pt: 'Se tinha dinheiro e era o que queria, está bem.' }, dimension: 'M' },
          { text: { es: 'Me parece bien. El acceso al placer y los pequeños lujos no debe ser monopolio de nadie.', en: 'I think it\'s great. Access to pleasure and small luxuries shouldn\'t be anyone\'s monopoly.', fr: 'Je trouve ça bien. L\'accès au plaisir et aux petits luxes ne doit pas être le monopole de personne.', de: 'Ich finde das gut. Der Zugang zu Genuss und kleinen Luxusgütern sollte niemandes Monopol sein.', it: 'Mi sembra giusto. L\'accesso al piacere e ai piccoli lussi non deve essere monopolio di nessuno.', pt: 'Acho ótimo. O acesso ao prazer e aos pequenos luxos não deve ser monopólio de ninguém.' }, dimension: 'S' },
        ],
      },
      {
        id: 5,
        situation: { es: '¿Cuál es tu explicación favorita para la pobreza?', en: 'What\'s your go-to explanation for poverty?', fr: 'Quelle est votre explication préférée de la pauvreté ?', de: 'Was ist deine bevorzugte Erklärung für Armut?', it: 'Qual è la tua spiegazione preferita per la povertà?', pt: 'Qual é sua explicação favorita para a pobreza?' },
        options: [
          { text: { es: 'En parte, malas decisiones o falta de esfuerzo. No todo es el sistema.', en: 'Partly bad decisions or lack of effort. Not everything is the system.', fr: 'En partie, de mauvaises décisions ou un manque d\'effort. Tout n\'est pas à mettre sur le compte du système.', de: 'Zum Teil schlechte Entscheidungen oder mangelnder Einsatz. Nicht alles ist das System.', it: 'In parte, cattive decisioni o mancanza di impegno. Non tutto è il sistema.', pt: 'Em parte, más decisões ou falta de esforço. Nem tudo é o sistema.' }, dimension: 'C' },
          { text: { es: 'Factores sistémicos tienen un peso enorme que los privilegiados solemos subestimar.', en: 'Systemic factors carry enormous weight that those of us with privilege tend to underestimate.', fr: 'Les facteurs systémiques ont un poids énorme que nous, les privilégiés, avons tendance à sous-estimer.', de: 'Systemische Faktoren haben ein enormes Gewicht, das wir Privilegierten oft unterschätzen.', it: 'I fattori sistemici hanno un peso enorme che noi privilegiati tendiamo a sottovalutare.', pt: 'Fatores sistêmicos têm um peso enorme que os privilegiados costumamos subestimar.' }, dimension: 'E' },
          { text: { es: 'Una combinación de factores: algunos sistémicos, algunos individuales.', en: 'A combination of factors: some systemic, some individual.', fr: 'Une combinaison de facteurs : certains systémiques, certains individuels.', de: 'Eine Kombination von Faktoren: einige systemische, einige individuelle.', it: 'Una combinazione di fattori: alcuni sistemici, alcuni individuali.', pt: 'Uma combinação de fatores: alguns sistêmicos, alguns individuais.' }, dimension: 'M' },
          { text: { es: 'Fundamentalmente estructural. Sin cambios sistémicos, el esfuerzo individual tiene límites reales.', en: 'Fundamentally structural. Without systemic changes, individual effort has real limits.', fr: 'Fondamentalement structurelle. Sans changements systémiques, l\'effort individuel a des limites réelles.', de: 'Grundlegend strukturell. Ohne systemische Veränderungen hat individueller Einsatz echte Grenzen.', it: 'Fondamentalmente strutturale. Senza cambiamenti sistemici, lo sforzo individuale ha limiti reali.', pt: 'Fundamentalmente estrutural. Sem mudanças sistêmicas, o esforço individual tem limites reais.' }, dimension: 'S' },
        ],
      },
      {
        id: 6,
        situation: { es: 'Un amigo de clase trabajadora usa un vocabulario diferente al tuyo. ¿Cómo lo procesas?', en: 'A working-class friend uses a different vocabulary than yours. How do you process that?', fr: 'Un ami de classe ouvrière utilise un vocabulaire différent du vôtre. Comment le percevez-vous ?', de: 'Ein Freund aus der Arbeiterklasse verwendet ein anderes Vokabular als du. Wie verarbeitest du das?', it: 'Un amico della classe operaia usa un vocabolario diverso dal tuo. Come lo elabori?', pt: 'Um amigo da classe trabalhadora usa um vocabulário diferente do seu. Como você processa isso?' },
        options: [
          { text: { es: 'Me cuesta no notarlo o no sentirlo como una diferencia significativa.', en: 'I struggle not to notice it or feel it as a significant difference.', fr: 'J\'ai du mal à ne pas le remarquer ou à ne pas le ressentir comme une différence significative.', de: 'Ich fällt es schwer, es nicht zu bemerken oder es nicht als bedeutenden Unterschied zu empfinden.', it: 'Faccio fatica a non notarlo o a non sentirlo come una differenza significativa.', pt: 'Tenho dificuldade de não notar ou não sentir como uma diferença significativa.' }, dimension: 'C' },
          { text: { es: 'Recuerdo que el vocabulario es producto del acceso a educación, no de inteligencia.', en: 'I remind myself that vocabulary is a product of access to education, not intelligence.', fr: 'Je me rappelle que le vocabulaire est le produit de l\'accès à l\'éducation, pas de l\'intelligence.', de: 'Ich erinnere mich daran, dass Vokabular ein Produkt des Zugangs zu Bildung ist, nicht der Intelligenz.', it: 'Ricordo a me stesso che il vocabolario è il prodotto dell\'accesso all\'istruzione, non dell\'intelligenza.', pt: 'Lembro que o vocabulário é produto do acesso à educação, não da inteligência.' }, dimension: 'E' },
          { text: { es: 'No me genera ninguna respuesta particular. La gente habla como habla.', en: 'It doesn\'t generate any particular response in me. People speak however they speak.', fr: 'Ça ne me génère aucune réaction particulière. Les gens parlent comme ils parlent.', de: 'Es erzeugt keine besondere Reaktion bei mir. Menschen reden so, wie sie reden.', it: 'Non mi genera nessuna risposta particolare. Le persone parlano come parlano.', pt: 'Não me gera nenhuma resposta particular. As pessoas falam como falam.' }, dimension: 'M' },
          { text: { es: 'Me interesa la perspectiva que tiene, que probablemente sea diferente y valiosa.', en: 'I\'m interested in their perspective, which is probably different and valuable.', fr: 'Je m\'intéresse à sa perspective, qui est probablement différente et précieuse.', de: 'Mich interessiert die Perspektive dieser Person, die wahrscheinlich anders und wertvoll ist.', it: 'Mi interessa la prospettiva che ha, che probabilmente è diversa e preziosa.', pt: 'Me interessa a perspectiva que tem, que provavelmente é diferente e valiosa.' }, dimension: 'S' },
        ],
      },
      {
        id: 7,
        situation: { es: 'Una persona llega tarde a un compromiso porque tomó transporte público y hubo un retraso.', en: 'A person arrives late to a commitment because they took public transport and there was a delay.', fr: 'Une personne arrive en retard à un engagement parce qu\'elle a pris les transports en commun et qu\'il y a eu un retard.', de: 'Eine Person kommt zu einer Verabredung zu spät, weil sie öffentliche Verkehrsmittel benutzt hat und es eine Verspätung gab.', it: 'Una persona arriva in ritardo a un impegno perché ha preso i mezzi pubblici e c\'è stato un ritardo.', pt: 'Uma pessoa chega atrasada a um compromisso porque pegou transporte público e houve um atraso.' },
        options: [
          { text: { es: 'Internamente me resulta difícil entender por qué no salió antes si sabía que era complicado.', en: 'Internally I find it hard to understand why they didn\'t leave earlier if they knew it was complicated.', fr: 'Intérieurement, j\'ai du mal à comprendre pourquoi cette personne n\'est pas partie plus tôt si elle savait que c\'était compliqué.', de: 'Innerlich fällt es mir schwer zu verstehen, warum die Person nicht früher gegangen ist, wenn sie wusste, dass es kompliziert war.', it: 'Internamente mi risulta difficile capire perché non sia partita prima se sapeva che era complicato.', pt: 'Internamente acho difícil entender por que não saiu antes se sabia que era complicado.' }, dimension: 'C' },
          { text: { es: 'Recuerdo que no todo el mundo tiene las mismas opciones de transporte.', en: 'I remind myself that not everyone has the same transportation options.', fr: 'Je me rappelle que tout le monde n\'a pas les mêmes options de transport.', de: 'Ich erinnere mich, dass nicht jeder die gleichen Transportmöglichkeiten hat.', it: 'Ricordo che non tutti hanno le stesse opzioni di trasporto.', pt: 'Lembro que nem todos têm as mesmas opções de transporte.' }, dimension: 'E' },
          { text: { es: 'La tardanza es la tardanza. Pero entiendo que el contexto importa.', en: 'Lateness is lateness. But I understand that context matters.', fr: 'Le retard est le retard. Mais je comprends que le contexte compte.', de: 'Verspätung ist Verspätung. Aber ich verstehe, dass der Kontext eine Rolle spielt.', it: 'Il ritardo è ritardo. Ma capisco che il contesto conta.', pt: 'Atraso é atraso. Mas entendo que o contexto importa.' }, dimension: 'M' },
          { text: { es: 'No hay problema. La falta de acceso a transporte privado no debería penalizarse socialmente.', en: 'No problem. The lack of access to private transport shouldn\'t be a social penalty.', fr: 'Pas de problème. Le manque d\'accès aux transports privés ne devrait pas être socialement pénalisé.', de: 'Kein Problem. Der fehlende Zugang zu privatem Transport sollte sozial nicht bestraft werden.', it: 'Nessun problema. La mancanza di accesso ai trasporti privati non dovrebbe essere penalizzata socialmente.', pt: 'Sem problema. A falta de acesso a transporte privado não deveria ser penalizada socialmente.' }, dimension: 'S' },
        ],
      },
      {
        id: 8,
        situation: { es: '¿Qué piensas de las políticas de acción afirmativa para personas de bajos recursos?', en: 'What do you think of affirmative action policies for people with lower incomes?', fr: 'Que pensez-vous des politiques d\'action positive pour les personnes à faibles revenus ?', de: 'Was denkst du über Maßnahmen zur positiven Diskriminierung für einkommensschwache Menschen?', it: 'Cosa pensi delle politiche di azione affermativa per le persone a basso reddito?', pt: 'O que você pensa sobre políticas de ação afirmativa para pessoas de baixa renda?' },
        options: [
          { text: { es: 'Me generan incomodidad. Prefiero un sistema de méritos puros.', en: 'They make me uncomfortable. I prefer a system of pure merit.', fr: 'Elles me mettent mal à l\'aise. Je préfère un système basé sur le mérite pur.', de: 'Sie machen mir Unbehagen. Ich bevorzuge ein System reiner Verdienste.', it: 'Mi generano disagio. Preferisco un sistema basato sul merito puro.', pt: 'Me geram desconforto. Prefiro um sistema de méritos puros.' }, dimension: 'C' },
          { text: { es: 'Las entiendo como una corrección de desigualdades históricas y estructurales.', en: 'I understand them as a correction for historical and structural inequalities.', fr: 'Je les comprends comme une correction des inégalités historiques et structurelles.', de: 'Ich verstehe sie als Korrektur historischer und struktureller Ungleichheiten.', it: 'Le capisco come una correzione delle disuguaglianze storiche e strutturali.', pt: 'Entendo como uma correção de desigualdades históricas e estruturais.' }, dimension: 'E' },
          { text: { es: 'Depende de la implementación. El mérito importa, pero el punto de partida también.', en: 'It depends on the implementation. Merit matters, but the starting point does too.', fr: 'Ça dépend de la mise en œuvre. Le mérite compte, mais le point de départ aussi.', de: 'Es hängt von der Umsetzung ab. Verdienst ist wichtig, aber der Ausgangspunkt auch.', it: 'Dipende dall\'implementazione. Il merito conta, ma anche il punto di partenza.', pt: 'Depende da implementação. O mérito importa, mas o ponto de partida também.' }, dimension: 'M' },
          { text: { es: 'Son necesarias. Sin intervenciones activas, las brechas no se cierran solas.', en: 'They\'re necessary. Without active interventions, gaps don\'t close on their own.', fr: 'Elles sont nécessaires. Sans interventions actives, les écarts ne se comblent pas d\'eux-mêmes.', de: 'Sie sind notwendig. Ohne aktive Eingriffe schließen sich die Lücken nicht von selbst.', it: 'Sono necessarie. Senza interventi attivi, i divari non si chiudono da soli.', pt: 'São necessárias. Sem intervenções ativas, as brechas não se fecham sozinhas.' }, dimension: 'S' },
        ],
      },
      {
        id: 9,
        situation: { es: 'Te enteras de que un amigo tiene deudas por gastos que consideras innecesarios.', en: 'You find out a friend has debt from expenses you consider unnecessary.', fr: 'Vous apprenez qu\'un ami a des dettes en raison de dépenses que vous jugez inutiles.', de: 'Du erfährst, dass ein Freund Schulden durch Ausgaben hat, die du für unnötig hältst.', it: 'Vieni a sapere che un amico ha debiti per spese che consideri non necessarie.', pt: 'Você descobre que um amigo tem dívidas por gastos que considera desnecessários.' },
        options: [
          { text: { es: 'Pienso que debería haber priorizado mejor. La falta de educación financiera tiene consecuencias.', en: 'I think they should have prioritized better. Lack of financial education has consequences.', fr: 'Je pense qu\'il aurait dû mieux prioriser. Le manque d\'éducation financière a des conséquences.', de: 'Ich denke, sie hätten besser priorisieren sollen. Mangelnde Finanzbildung hat Konsequenzen.', it: 'Penso che avrebbe dovuto dare le priorità meglio. La mancanza di educazione finanziaria ha conseguenze.', pt: 'Penso que deveria ter priorizado melhor. A falta de educação financeira tem consequências.' }, dimension: 'C' },
          { text: { es: 'Recuerdo que la educación financiera no se distribuye igual en todos los contextos socioeconómicos.', en: 'I remind myself that financial education isn\'t distributed equally across all socioeconomic contexts.', fr: 'Je me rappelle que l\'éducation financière n\'est pas distribuée de manière égale dans tous les contextes socioéconomiques.', de: 'Ich erinnere mich, dass Finanzbildung nicht in allen sozioökonomischen Kontexten gleich verteilt ist.', it: 'Ricordo che l\'educazione finanziaria non è distribuita allo stesso modo in tutti i contesti socioeconomici.', pt: 'Lembro que a educação financeira não se distribui igualmente em todos os contextos socioeconômicos.' }, dimension: 'E' },
          { text: { es: 'Es su decisión. Solo es relevante si me pide ayuda.', en: 'It\'s their decision. It only becomes relevant if they ask for my help.', fr: 'C\'est sa décision. C\'est uniquement pertinent s\'il me demande de l\'aide.', de: 'Es ist ihre Entscheidung. Es ist nur relevant, wenn sie mich um Hilfe bitten.', it: 'È la sua decisione. È rilevante solo se mi chiede aiuto.', pt: 'É decisão dele. Só é relevante se me pedir ajuda.' }, dimension: 'M' },
          { text: { es: 'No juzgo. El acceso a información y a herramientas financieras es muy desigual.', en: 'I don\'t judge. Access to information and financial tools is very unequal.', fr: 'Je ne juge pas. L\'accès à l\'information et aux outils financiers est très inégal.', de: 'Ich urteile nicht. Der Zugang zu Informationen und Finanzinstrumenten ist sehr ungleich.', it: 'Non giudico. L\'accesso alle informazioni e agli strumenti finanziari è molto disuguale.', pt: 'Não julgo. O acesso a informações e ferramentas financeiras é muito desigual.' }, dimension: 'S' },
        ],
      },
      {
        id: 10,
        situation: { es: 'Alguien hace algo incómodo socialmente en un contexto "de clase media-alta". ¿Cómo lo lees?', en: 'Someone does something socially awkward in an upper-middle-class setting. How do you read it?', fr: 'Quelqu\'un fait quelque chose de gênant socialement dans un contexte de "classe moyenne-supérieure". Comment l\'interprétez-vous ?', de: 'Jemand tut etwas sozial Unangenehmes in einem "oberen Mittelschicht"-Kontext. Wie liest du das?', it: 'Qualcuno fa qualcosa di socialmente imbarazzante in un contesto "di classe media-alta". Come lo interpreti?', pt: 'Alguém faz algo socialmente desconfortável em um contexto de "classe média-alta". Como você o interpreta?' },
        options: [
          { text: { es: 'Inconscientemente lo interpreto como "no sabe cómo moverse en estos espacios".', en: 'Unconsciously I interpret it as "they don\'t know how to move in these spaces".', fr: 'Inconsciemment, je l\'interprète comme "il ne sait pas comment se comporter dans ces espaces".', de: 'Unbewusst interpretiere ich es als "sie wissen nicht, wie man sich in diesen Räumen bewegt".', it: 'Inconsapevolmente lo interpreto come "non sa come muoversi in questi spazi".', pt: 'Inconscientemente interpreto como "não sabe como se mover nesses espaços".' }, dimension: 'C' },
          { text: { es: 'Reconozco que los códigos de clase son arbitrarios y construidos.', en: 'I recognize that class codes are arbitrary and constructed.', fr: 'Je reconnais que les codes de classe sont arbitraires et construits.', de: 'Ich erkenne, dass Klassencodes arbiträr und konstruiert sind.', it: 'Riconosco che i codici di classe sono arbitrari e costruiti.', pt: 'Reconheço que os códigos de classe são arbitrários e construídos.' }, dimension: 'E' },
          { text: { es: 'No lo evalúo socialmente, solo factualmente.', en: 'I don\'t evaluate it socially, only factually.', fr: 'Je ne l\'évalue pas socialement, seulement factuellement.', de: 'Ich bewerte es nicht sozial, sondern nur sachlich.', it: 'Non lo valuto socialmente, solo fattualmente.', pt: 'Não avalio socialmente, apenas factualmente.' }, dimension: 'M' },
          { text: { es: 'Los códigos de clase son muros invisibles y me incomoda cuando alguien los usa para excluir.', en: 'Class codes are invisible walls and it makes me uncomfortable when someone uses them to exclude others.', fr: 'Les codes de classe sont des murs invisibles et ça me dérange quand quelqu\'un les utilise pour exclure.', de: 'Klassencodes sind unsichtbare Mauern und es macht mich unwohl, wenn jemand sie benutzt, um andere auszuschließen.', it: 'I codici di classe sono muri invisibili e mi mette a disagio quando qualcuno li usa per escludere.', pt: 'Os códigos de classe são muros invisíveis e me incomoda quando alguém os usa para excluir.' }, dimension: 'S' },
        ],
      },
    ],
    characters: [
      { name: { es: 'El Clasista No Consciente', en: 'The Unconscious Classist', fr: 'Le Classiste Inconscient', de: 'Der Unbewusste Klassist', it: 'Il Classista Inconsapevole', pt: 'O Classista Inconsciente' }, dimensions: ['C'], photo: '/characters/classist.jpg', description: { es: 'No lo llama clasismo. Lo llama "estándares".', en: 'Doesn\'t call it classism. Calls it "standards".', fr: 'Ne l\'appelle pas classisme. L\'appelle "normes".', de: 'Nennt es nicht Klassismus. Nennt es "Standards".', it: 'Non lo chiama classismo. Lo chiama "standard".', pt: 'Não chama de classismo. Chama de "padrões".' }, philosophy: { es: 'Tus juicios sobre las personas según su clase socioeconómica son tan naturalizados que casi no los ves. No crees ser mejor que nadie — simplemente tienes "criterios". Ese es exactamente el punto.', en: 'Your judgments about people based on their socioeconomic class are so naturalized you barely see them. You don\'t think you\'re better than anyone — you simply have "standards". That\'s exactly the point.', fr: 'Vos jugements sur les personnes selon leur classe socioéconomique sont tellement naturalisés que vous les voyez à peine. Vous ne croyez pas être meilleur que quiconque — vous avez simplement des "critères". C\'est précisément là l\'enjeu.', de: 'Deine Urteile über Menschen aufgrund ihrer sozioökonomischen Klasse sind so naturalisiert, dass du sie kaum siehst. Du glaubst nicht, besser als irgendjemand zu sein — du hast einfach "Maßstäbe". Das ist genau der Punkt.', it: 'I tuoi giudizi sulle persone in base alla loro classe socioeconomica sono così naturalizzati che quasi non li vedi. Non credi di essere migliore di nessuno — hai semplicemente dei "criteri". Questo è esattamente il punto.', pt: 'Seus julgamentos sobre as pessoas segundo sua classe socioeconômica são tão naturalizados que você quase não os vê. Você não acha que é melhor do que ninguém — simplesmente tem "critérios". Esse é exatamente o ponto.' } },
      { name: { es: 'El Empático de Clase', en: 'The Class Empath', fr: 'L\'Empathique de Classe', de: 'Der Klassen-Empath', it: 'L\'Empatico di Classe', pt: 'O Empático de Classe' }, dimensions: ['E'], photo: '/characters/class-empathy.jpg', description: { es: 'Entiende que el privilegio distorsiona la perspectiva.', en: 'Understands that privilege distorts perspective.', fr: 'Comprend que le privilège distord la perspective.', de: 'Versteht, dass Privileg die Perspektive verzerrt.', it: 'Capisce che il privilegio distorce la prospettiva.', pt: 'Entende que o privilégio distorce a perspectiva.' }, philosophy: { es: 'Has trabajado para ver más allá de tu punto de partida. Entiendes que el clasismo no requiere malas intenciones — solo la ceguera cómoda de quien nunca ha tenido que pensarlo.', en: 'You\'ve worked to see beyond your starting point. You understand that classism doesn\'t require bad intentions — just the comfortable blindness of someone who\'s never had to think about it.', fr: 'Vous avez travaillé pour voir au-delà de votre point de départ. Vous comprenez que le classisme ne nécessite pas de mauvaises intentions — seulement l\'aveuglement confortable de celui qui n\'a jamais eu à y penser.', de: 'Du hast daran gearbeitet, über deinen Ausgangspunkt hinaus zu sehen. Du verstehst, dass Klassismus keine bösen Absichten erfordert — nur die bequeme Blindheit derer, die nie darüber nachdenken mussten.', it: 'Hai lavorato per vedere oltre il tuo punto di partenza. Capisci che il classismo non richiede cattive intenzioni — solo la cieca comodità di chi non ha mai dovuto pensarci.', pt: 'Você trabalhou para ver além do seu ponto de partida. Entende que o classismo não requer más intenções — apenas a cegueira confortável de quem nunca precisou pensar nisso.' } },
      { name: { es: 'El Meritocrático', en: 'The Meritocrat', fr: 'Le Méritocrate', de: 'Der Meritokrat', it: 'Il Meritocratico', pt: 'O Meritocrático' }, dimensions: ['M'], photo: '/characters/meritocratic.jpg', description: { es: 'Cree en el esfuerzo individual pero puede subestimar las estructuras.', en: 'Believes in individual effort but may underestimate structural barriers.', fr: 'Croit en l\'effort individuel mais peut sous-estimer les structures.', de: 'Glaubt an individuelle Anstrengung, kann aber Strukturen unterschätzen.', it: 'Crede nello sforzo individuale ma può sottovalutare le strutture.', pt: 'Acredita no esforço individual, mas pode subestimar as estruturas.' }, philosophy: { es: 'Para ti, el mérito es la variable más importante. Crees que con esfuerzo suficiente cualquiera puede llegar donde quiera. Eso es parcialmente cierto — y parcialmente una racionalización del privilegio.', en: 'For you, merit is the most important variable. You believe that with enough effort anyone can reach wherever they want. That\'s partially true — and partially a rationalization of privilege.', fr: 'Pour vous, le mérite est la variable la plus importante. Vous croyez qu\'avec suffisamment d\'effort, n\'importe qui peut aller où il veut. C\'est partiellement vrai — et partiellement une rationalisation du privilège.', de: 'Für dich ist Verdienst die wichtigste Variable. Du glaubst, dass jeder mit genug Einsatz erreichen kann, wo er hin will. Das stimmt teilweise — und ist teilweise eine Rationalisierung von Privilegien.', it: 'Per te il merito è la variabile più importante. Credi che con abbastanza impegno chiunque possa arrivare dove vuole. È parzialmente vero — e parzialmente una razionalizzazione del privilegio.', pt: 'Para você, o mérito é a variável mais importante. Acredita que com esforço suficiente qualquer um pode chegar onde quiser. Isso é parcialmente verdade — e parcialmente uma racionalização do privilégio.' } },
      { name: { es: 'El Solidario de Clase', en: 'The Class Solidarity', fr: 'Le Solidaire de Classe', de: 'Der Klassensolidarische', it: 'Il Solidale di Classe', pt: 'O Solidário de Classe' }, dimensions: ['S'], photo: '/characters/class-solidarity.jpg', description: { es: 'Ve las estructuras y actúa para cambiarlas.', en: 'Sees the structures and acts to change them.', fr: 'Voit les structures et agit pour les changer.', de: 'Sieht die Strukturen und handelt, um sie zu verändern.', it: 'Vede le strutture e agisce per cambiarle.', pt: 'Vê as estruturas e age para mudá-las.' }, philosophy: { es: 'Entiendes que las brechas de clase no son accidentes — son el resultado de sistemas que se reproducen activamente. Y eso te genera no solo empatía, sino la necesidad de actuar.', en: 'You understand that class gaps aren\'t accidents — they\'re the result of actively reproducing systems. And that generates not just empathy in you, but the need to act.', fr: 'Vous comprenez que les écarts de classe ne sont pas des accidents — ils sont le résultat de systèmes qui se reproduisent activement. Et cela génère en vous non seulement de l\'empathie, mais la nécessité d\'agir.', de: 'Du verstehst, dass Klassengefälle keine Zufälle sind — sie sind das Ergebnis von Systemen, die sich aktiv reproduzieren. Und das erzeugt in dir nicht nur Empathie, sondern die Notwendigkeit zu handeln.', it: 'Capisci che i divari di classe non sono accidenti — sono il risultato di sistemi che si riproducono attivamente. E questo genera in te non solo empatia, ma la necessità di agire.', pt: 'Você entende que as brechas de classe não são acidentes — são o resultado de sistemas que se reproduzem ativamente. E isso gera em você não apenas empatia, mas a necessidade de agir.' } },
      { name: { es: 'El Clasista que Aprende', en: 'The Classist Who Is Learning', fr: 'Le Classiste qui Apprend', de: 'Der Lernende Klassist', it: 'Il Classista che Impara', pt: 'O Classista que Aprende' }, dimensions: ['C', 'E'], photo: '/characters/learning-classist.jpg', description: { es: 'Tiene sesgos de clase pero los está cuestionando.', en: 'Has class biases but is questioning them.', fr: 'A des biais de classe mais les questionne.', de: 'Hat Klassenvorurteile, aber hinterfragt sie.', it: 'Ha pregiudizi di classe ma li sta mettendo in discussione.', pt: 'Tem preconceitos de classe, mas os está questionando.' }, philosophy: { es: 'Empiezas a ver las grietas en tu perspectiva. Los juicios automáticos siguen apareciendo, pero ahora los notas. Ese espacio entre el juicio y la acción es donde ocurre el cambio.', en: 'You\'re starting to see the cracks in your perspective. Automatic judgments keep appearing, but now you notice them. That space between judgment and action is where change happens.', fr: 'Vous commencez à voir les fissures dans votre perspective. Les jugements automatiques continuent d\'apparaître, mais maintenant vous les remarquez. Cet espace entre le jugement et l\'action est là où le changement se produit.', de: 'Du beginnst, die Risse in deiner Perspektive zu sehen. Automatische Urteile tauchen weiterhin auf, aber jetzt bemerkst du sie. Dieser Raum zwischen Urteil und Handlung ist der Ort, an dem Veränderung stattfindet.', it: 'Inizi a vedere le crepe nella tua prospettiva. I giudizi automatici continuano ad apparire, ma ora li noti. Quello spazio tra il giudizio e l\'azione è dove avviene il cambiamento.', pt: 'Você começa a ver as rachaduras na sua perspectiva. Os julgamentos automáticos continuam aparecendo, mas agora você os nota. Esse espaço entre o julgamento e a ação é onde a mudança acontece.' } },
      { name: { es: 'El Meritocrático Empático', en: 'The Empathic Meritocrat', fr: 'Le Méritocrate Empathique', de: 'Der Empathische Meritokrat', it: 'Il Meritocratico Empatico', pt: 'O Meritocrático Empático' }, dimensions: ['M', 'E'], photo: '/characters/empathic-meritocrat.jpg', description: { es: 'Valora el esfuerzo pero reconoce que el punto de partida importa.', en: 'Values effort but recognizes that the starting point matters.', fr: 'Valorise l\'effort mais reconnaît que le point de départ compte.', de: 'Schätzt Einsatz, erkennt aber, dass der Ausgangspunkt eine Rolle spielt.', it: 'Valorizza lo sforzo ma riconosce che il punto di partenza conta.', pt: 'Valoriza o esforço, mas reconhece que o ponto de partida importa.' }, philosophy: { es: 'No niegas el rol del esfuerzo individual, pero tampoco ignoras que las condiciones de partida no son iguales. Esa doble visión es más honesta que cualquiera de los dos extremos.', en: 'You don\'t deny the role of individual effort, but you don\'t ignore that starting conditions aren\'t equal either. That double vision is more honest than either extreme.', fr: 'Vous ne niez pas le rôle de l\'effort individuel, mais vous n\'ignorez pas non plus que les conditions de départ ne sont pas égales. Cette double vision est plus honnête que l\'un ou l\'autre des deux extrêmes.', de: 'Du leugnest nicht die Rolle individueller Anstrengung, aber du ignorierst auch nicht, dass die Ausgangsbedingungen nicht gleich sind. Diese doppelte Sichtweise ist ehrlicher als jeder der beiden Extreme.', it: 'Non neghi il ruolo dello sforzo individuale, ma non ignori nemmeno che le condizioni di partenza non sono uguali. Quella doppia visione è più onesta di entrambi gli estremi.', pt: 'Você não nega o papel do esforço individual, mas também não ignora que as condições de partida não são iguais. Essa visão dupla é mais honesta do que qualquer um dos dois extremos.' } },
      { name: { es: 'El Crítico Solidario', en: 'The Critical Solidary', fr: 'Le Critique Solidaire', de: 'Der Kritisch Solidarische', it: 'Il Critico Solidale', pt: 'O Crítico Solidário' }, dimensions: ['E', 'S'], photo: '/characters/critical-solidary.jpg', description: { es: 'Análisis estructural + acción concreta.', en: 'Structural analysis + concrete action.', fr: 'Analyse structurelle + action concrète.', de: 'Strukturelle Analyse + konkrete Handlung.', it: 'Analisi strutturale + azione concreta.', pt: 'Análise estrutural + ação concreta.' }, philosophy: { es: 'Entiendes las causas y actúas sobre ellas. No te quedas en el análisis — lo conectas con prácticas concretas de solidaridad. Eso es más difícil de lo que parece.', en: 'You understand the causes and act on them. You don\'t stay in analysis — you connect it to concrete solidarity practices. That\'s harder than it looks.', fr: 'Vous comprenez les causes et agissez en conséquence. Vous ne restez pas dans l\'analyse — vous la connectez à des pratiques concrètes de solidarité. C\'est plus difficile qu\'il n\'y paraît.', de: 'Du verstehst die Ursachen und handelst danach. Du bleibst nicht bei der Analyse — du verbindest sie mit konkreten Solidaritätspraktiken. Das ist schwieriger als es aussieht.', it: 'Capisci le cause e agisci su di esse. Non rimani nell\'analisi — la colleghi a pratiche concrete di solidarietà. È più difficile di quanto sembri.', pt: 'Você entende as causas e age sobre elas. Não fica na análise — a conecta com práticas concretas de solidariedade. Isso é mais difícil do que parece.' } },
      { name: { es: 'El Igualitario Práctico', en: 'The Practical Egalitarian', fr: 'L\'Égalitaire Pratique', de: 'Der Praktische Egalitäre', it: 'L\'Egualitario Pratico', pt: 'O Igualitário Prático' }, dimensions: ['M', 'S'], photo: '/characters/practical-equality.jpg', description: { es: 'Busca la equidad desde el mérito pero con correcciones estructurales.', en: 'Seeks equity through merit but with structural corrections.', fr: 'Recherche l\'équité à travers le mérite mais avec des corrections structurelles.', de: 'Sucht Gerechtigkeit durch Verdienst, aber mit strukturellen Korrekturen.', it: 'Cerca l\'equità attraverso il merito ma con correzioni strutturali.', pt: 'Busca equidade através do mérito, mas com correções estruturais.' }, philosophy: { es: 'Para ti, el mérito importa y las estructuras también. No son contradictorios — son complementarios. Quieres un sistema donde el esfuerzo cuente, pero donde el punto de partida no condene.', en: 'For you, merit matters and so do structures. They\'re not contradictory — they\'re complementary. You want a system where effort counts, but where the starting point doesn\'t condemn.', fr: 'Pour vous, le mérite compte et les structures aussi. Ils ne sont pas contradictoires — ils sont complémentaires. Vous voulez un système où l\'effort compte, mais où le point de départ ne condamne pas.', de: 'Für dich ist Verdienst wichtig und Strukturen auch. Sie sind nicht widersprüchlich — sie sind komplementär. Du möchtest ein System, in dem Einsatz zählt, aber der Ausgangspunkt nicht verurteilt.', it: 'Per te il merito conta e le strutture pure. Non sono contraddittori — sono complementari. Vuoi un sistema in cui lo sforzo conti, ma in cui il punto di partenza non condanni.', pt: 'Para você, o mérito importa e as estruturas também. Não são contraditórios — são complementares. Você quer um sistema onde o esforço conte, mas onde o ponto de partida não condene.' } },
    ],
  };

  await prisma.quiz.upsert({
    where: { slug: 'classist' },
    update: {
      title: data.title,
      description: data.description,
      scenarioLabel: data.scenarioLabel,
      dimensionLabels: data.dimensionLabels,
      questions: data.questions,
      characters: data.characters,
    },
    create: data,
  });
}
