import type { PrismaClient } from '../../generated/prisma/client.js';

export async function seedSuperficial(prisma: PrismaClient, catMap: Record<string, string>) {
  const data = {
    slug: 'superficial',
    title: { es: '¿Qué tan superficial eres?', en: 'How superficial are you?', fr: 'À quel point êtes-vous superficiel(le) ?', de: 'Wie oberflächlich bist du?', it: 'Quanto sei superficiale?', pt: 'Quão superficial você é?' },
    description: { es: 'Todos juzgamos por la apariencia más de lo que admitimos. ¿Cuánto?', en: 'We all judge by appearances more than we admit. By how much?', fr: 'Nous jugeons tous sur les apparences plus que nous ne l\'admettons. De combien ?', de: 'Wir alle urteilen mehr nach dem Äußeren, als wir zugeben. Um wie viel?', it: 'Tutti giudichiamo dall\'apparenza più di quanto ammettiamo. Quanto?', pt: 'Todos julgamos pela aparência mais do que admitimos. Quanto?' },
    scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
    categoryId: catMap['moral'],
    sortOrder: 5,
    dimensionLabels: {
      es: { S: 'Superficialidad', P: 'Profundidad', A: 'Apariencia', V: 'Valores' },
      en: { S: 'Superficiality', P: 'Depth', A: 'Appearance', V: 'Values' },
      fr: { S: 'Superficialité', P: 'Profondeur', A: 'Apparence', V: 'Valeurs' },
      de: { S: 'Oberflächlichkeit', P: 'Tiefe', A: 'Äußerlichkeit', V: 'Werte' },
      it: { S: 'Superficialità', P: 'Profondità', A: 'Apparenza', V: 'Valori' },
      pt: { S: 'Superficialidade', P: 'Profundidade', A: 'Aparência', V: 'Valores' },
    },
    questions: [
      {
        id: 1,
        situation: { es: 'Conoces a alguien nuevo. ¿Qué te genera la primera impresión más fuerte?', en: 'You meet someone new. What gives you the strongest first impression?', fr: 'Vous rencontrez quelqu\'un de nouveau. Qu\'est-ce qui vous donne la première impression la plus forte ?', de: 'Du triffst jemanden neu. Was gibt dir den stärksten ersten Eindruck?', it: 'Conosci qualcuno di nuovo. Cosa ti genera la prima impressione più forte?', pt: 'Você conhece alguém novo. O que te gera a primeira impressão mais forte?' },
        options: [
          { text: { es: 'Su estilo: ropa, pelo, cómo se presenta físicamente.', en: 'Their style: clothes, hair, how they present themselves physically.', fr: 'Son style : vêtements, coiffure, présentation physique.', de: 'Ihr Stil: Kleidung, Haare, wie sie sich physisch präsentieren.', it: 'Il suo stile: vestiti, capelli, come si presenta fisicamente.', pt: 'Seu estilo: roupas, cabelo, como se apresenta fisicamente.' }, dimension: 'S' },
          { text: { es: 'Cómo habla, qué dice, qué preguntas hace.', en: 'How they speak, what they say, what questions they ask.', fr: 'Comment il parle, ce qu\'il dit, quelles questions il pose.', de: 'Wie sie sprechen, was sie sagen, welche Fragen sie stellen.', it: 'Come parla, cosa dice, che domande fa.', pt: 'Como fala, o que diz, que perguntas faz.' }, dimension: 'P' },
          { text: { es: 'Su atractivo físico, aunque no lo admita siempre.', en: 'Their physical attractiveness, even if I don\'t always admit it.', fr: 'Son attrait physique, même si je ne l\'admets pas toujours.', de: 'Ihre körperliche Attraktivität, auch wenn ich es nicht immer zugebe.', it: 'La sua attrattiva fisica, anche se non lo ammetto sempre.', pt: 'Sua atratividade física, embora não admita sempre.' }, dimension: 'A' },
          { text: { es: 'La energía que proyecta: amabilidad, confianza, autenticidad.', en: 'The energy they project: kindness, confidence, authenticity.', fr: 'L\'énergie qu\'il projette : amabilité, confiance, authenticité.', de: 'Die Energie, die sie ausstrahlen: Freundlichkeit, Selbstvertrauen, Authentizität.', it: 'L\'energia che proietta: gentilezza, fiducia, autenticità.', pt: 'A energia que projeta: amabilidade, confiança, autenticidade.' }, dimension: 'V' },
        ],
      },
      {
        id: 2,
        situation: { es: '¿Qué tan importante es la apariencia física en una posible pareja romántica?', en: 'How important is physical appearance in a potential romantic partner?', fr: 'Quelle importance accordez-vous à l\'apparence physique chez un partenaire romantique potentiel ?', de: 'Wie wichtig ist das äußere Erscheinungsbild bei einem möglichen Liebespartner?', it: 'Quanto è importante l\'aspetto fisico in un potenziale partner romantico?', pt: 'Quão importante é a aparência física em um possível parceiro romântico?' },
        options: [
          { text: { es: 'Muy importante. La atracción física es la base de todo lo demás.', en: 'Very important. Physical attraction is the foundation for everything else.', fr: 'Très important. L\'attraction physique est la base de tout le reste.', de: 'Sehr wichtig. Körperliche Anziehung ist die Grundlage für alles andere.', it: 'Molto importante. L\'attrazione fisica è la base di tutto il resto.', pt: 'Muito importante. A atração física é a base de tudo o mais.' }, dimension: 'S' },
          { text: { es: 'Importante pero no determinante. La personalidad puede cambiar completamente mi percepción.', en: 'Important but not decisive. Personality can completely change my perception.', fr: 'Important mais pas déterminant. La personnalité peut complètement changer ma perception.', de: 'Wichtig, aber nicht ausschlaggebend. Persönlichkeit kann meine Wahrnehmung völlig verändern.', it: 'Importante ma non determinante. La personalità può cambiare completamente la mia percezione.', pt: 'Importante, mas não determinante. A personalidade pode mudar completamente minha percepção.' }, dimension: 'P' },
          { text: { es: 'Necesito sentir atracción. Sin eso, no hay base.', en: 'I need to feel attraction. Without that, there\'s no foundation.', fr: 'J\'ai besoin de ressentir de l\'attraction. Sans ça, il n\'y a pas de base.', de: 'Ich muss Anziehung spüren. Ohne das gibt es keine Grundlage.', it: 'Ho bisogno di sentire attrazione. Senza quello, non c\'è base.', pt: 'Preciso sentir atração. Sem isso, não há base.' }, dimension: 'A' },
          { text: { es: 'Lo más importante es que tenga valores que se alineen con los míos.', en: 'The most important thing is that they have values that align with mine.', fr: 'Le plus important est qu\'elle ait des valeurs qui s\'alignent avec les miennes.', de: 'Am wichtigsten ist, dass sie Werte hat, die mit meinen übereinstimmen.', it: 'La cosa più importante è che abbia valori che si allineino con i miei.', pt: 'O mais importante é que tenha valores alinhados com os meus.' }, dimension: 'V' },
        ],
      },
      {
        id: 3,
        situation: { es: 'Alguien muy atractivo dice algo sin sentido. ¿Cómo lo procesas?', en: 'Someone very attractive says something nonsensical. How do you process it?', fr: 'Une personne très séduisante dit quelque chose qui n\'a pas de sens. Comment le traitez-vous ?', de: 'Jemand sehr Attraktives sagt etwas Unsinniges. Wie verarbeitest du das?', it: 'Qualcuno di molto attraente dice qualcosa di privo di senso. Come lo elabori?', pt: 'Alguém muito atraente diz algo sem sentido. Como você processa isso?' },
        options: [
          { text: { es: 'Le doy el beneficio de la duda más fácilmente que si fuera menos atractivo/a.', en: 'I give them the benefit of the doubt more easily than if they were less attractive.', fr: 'Je lui accorde le bénéfice du doute plus facilement que si elle était moins attrayante.', de: 'Ich gebe ihnen den Vorteil des Zweifels leichter als wenn sie weniger attraktiv wären.', it: 'Gli do il beneficio del dubbio più facilmente di quanto farei se fosse meno attraente.', pt: 'Dou o benefício da dúvida mais facilmente do que se fosse menos atraente.' }, dimension: 'S' },
          { text: { es: 'Lo noto como algo incongruente. El atractivo no compensa la falta de sustancia.', en: 'I notice it as incongruent. Attractiveness doesn\'t compensate for lack of substance.', fr: 'Je le remarque comme quelque chose d\'incongruent. L\'attrait ne compense pas le manque de substance.', de: 'Ich bemerke es als inkongruent. Attraktivität kompensiert nicht den Mangel an Substanz.', it: 'Lo noto come qualcosa di incongruente. L\'attrattiva non compensa la mancanza di sostanza.', pt: 'Noto como algo incongruente. A atratividade não compensa a falta de substância.' }, dimension: 'P' },
          { text: { es: 'Me afecta un poco. Es más difícil juzgar negativamente a alguien atractivo.', en: 'It affects me a little. It\'s harder to judge someone attractive negatively.', fr: 'Ça m\'affecte un peu. Il est plus difficile de juger négativement une personne attrayante.', de: 'Es betrifft mich ein wenig. Es ist schwieriger, jemanden Attraktives negativ zu beurteilen.', it: 'Mi influisce un po\'. È più difficile giudicare negativamente qualcuno di attraente.', pt: 'Me afeta um pouco. É mais difícil julgar negativamente alguém atraente.' }, dimension: 'A' },
          { text: { es: 'Evalúo lo que dijo independientemente de cómo se ve.', en: 'I evaluate what they said independently of how they look.', fr: 'J\'évalue ce qu\'elle a dit indépendamment de son apparence.', de: 'Ich bewerte das Gesagte unabhängig davon, wie sie aussehen.', it: 'Valuto ciò che ha detto indipendentemente da come appare.', pt: 'Avalio o que disse independentemente de como se parece.' }, dimension: 'V' },
        ],
      },
      {
        id: 4,
        situation: { es: '¿Cómo decides seguir o dejar de seguir a alguien en redes sociales?', en: 'How do you decide to follow or unfollow someone on social media?', fr: 'Comment décidez-vous de suivre ou de ne plus suivre quelqu\'un sur les réseaux sociaux ?', de: 'Wie entscheidest du, jemandem in sozialen Medien zu folgen oder nicht mehr zu folgen?', it: 'Come decidi di seguire o smettere di seguire qualcuno sui social media?', pt: 'Como você decide seguir ou deixar de seguir alguém nas redes sociais?' },
        options: [
          { text: { es: 'Principalmente por la calidad visual del contenido y la estética del perfil.', en: 'Mainly by the visual quality of the content and the aesthetic of the profile.', fr: 'Principalement pour la qualité visuelle du contenu et l\'esthétique du profil.', de: 'Hauptsächlich nach der visuellen Qualität des Inhalts und der Ästhetik des Profils.', it: 'Principalmente per la qualità visiva del contenuto e l\'estetica del profilo.', pt: 'Principalmente pela qualidade visual do conteúdo e a estética do perfil.' }, dimension: 'S' },
          { text: { es: 'Por qué aporta el contenido: ¿aprendo algo? ¿me genera reflexiones?', en: 'By what the content contributes: Do I learn something? Does it make me think?', fr: 'Par ce qu\'apporte le contenu : est-ce que j\'apprends quelque chose ? Est-ce que ça me fait réfléchir ?', de: 'Danach, was der Inhalt beiträgt: Lerne ich etwas? Bringt er mich zum Nachdenken?', it: 'Per ciò che apporta il contenuto: imparo qualcosa? Mi genera riflessioni?', pt: 'Pelo que o conteúdo agrega: aprendo algo? Me gera reflexões?' }, dimension: 'P' },
          { text: { es: 'Una combinación de valor del contenido y si la persona me parece atractiva o interesante visualmente.', en: 'A combination of content value and whether the person is visually attractive or interesting to me.', fr: 'Une combinaison de la valeur du contenu et de si la personne me semble attrayante ou intéressante visuellement.', de: 'Eine Kombination aus Inhaltswert und ob die Person für mich optisch attraktiv oder interessant ist.', it: 'Una combinazione del valore del contenuto e se la persona mi sembra attraente o interessante visivamente.', pt: 'Uma combinação do valor do conteúdo e se a pessoa me parece atraente ou interessante visualmente.' }, dimension: 'A' },
          { text: { es: 'Por si los valores que proyecta se alinean con los que tengo.', en: 'By whether the values they project align with the ones I hold.', fr: 'Par si les valeurs qu\'il projette s\'alignent avec les miennes.', de: 'Danach, ob die Werte, die sie projizieren, mit meinen übereinstimmen.', it: 'Per se i valori che proietta si allineano con quelli che ho.', pt: 'Se os valores que projeta se alinham com os que tenho.' }, dimension: 'V' },
        ],
      },
      {
        id: 5,
        situation: { es: '¿Cuánto tiempo dedicas a tu apariencia física versus otras formas de desarrollo personal?', en: 'How much time do you dedicate to your physical appearance versus other forms of personal development?', fr: 'Combien de temps consacrez-vous à votre apparence physique par rapport à d\'autres formes de développement personnel ?', de: 'Wie viel Zeit widmest du deinem äußeren Erscheinungsbild im Vergleich zu anderen Formen der persönlichen Entwicklung?', it: 'Quanto tempo dedichi al tuo aspetto fisico rispetto ad altre forme di sviluppo personale?', pt: 'Quanto tempo você dedica à sua aparência física versus outras formas de desenvolvimento pessoal?' },
        options: [
          { text: { es: 'Bastante. La imagen que proyecto importa mucho para cómo me perciben.', en: 'Quite a lot. The image I project matters a lot for how others perceive me.', fr: 'Beaucoup. L\'image que je projette est très importante pour la façon dont les autres me perçoivent.', de: 'Ziemlich viel. Das Bild, das ich projiziere, ist sehr wichtig dafür, wie andere mich wahrnehmen.', it: 'Abbastanza. L\'immagine che proietto conta molto per come gli altri mi percepiscono.', pt: 'Bastante. A imagem que projeto importa muito para como sou percebido.' }, dimension: 'S' },
          { text: { es: 'Menos de lo que debería quizás. Me cuesta priorizar lo físico sobre lo intelectual.', en: 'Less than I probably should. I find it hard to prioritize the physical over the intellectual.', fr: 'Moins que je ne devrais peut-être. J\'ai du mal à prioriser le physique sur l\'intellectuel.', de: 'Weniger als vielleicht nötig. Mir fällt es schwer, das Physische über das Intellektuelle zu stellen.', it: 'Meno di quanto dovrei forse. Faccio fatica a dare priorità al fisico sull\'intellettuale.', pt: 'Menos do que talvez devesse. Tenho dificuldade em priorizar o físico sobre o intelectual.' }, dimension: 'P' },
          { text: { es: 'Significativo tiempo. Cuidarme físicamente me da confianza y eso se traslada a todo.', en: 'A significant amount. Taking care of myself physically gives me confidence and that carries over into everything.', fr: 'Un temps significatif. Prendre soin de moi physiquement me donne confiance et ça se reflète dans tout.', de: 'Erheblich viel. Mich körperlich zu pflegen gibt mir Selbstvertrauen und das überträgt sich auf alles.', it: 'Tempo significativo. Prendermi cura di me fisicamente mi dà fiducia e questo si trasferisce in tutto.', pt: 'Tempo significativo. Cuidar de mim fisicamente me dá confiança e isso se reflete em tudo.' }, dimension: 'A' },
          { text: { es: 'El tiempo justo. El físico importa como parte del bienestar, no como fin.', en: 'Just enough. The physical matters as part of well-being, not as an end in itself.', fr: 'Juste assez. Le physique compte en tant que partie du bien-être, pas comme une fin en soi.', de: 'Gerade genug. Das Physische ist Teil des Wohlbefindens, nicht Selbstzweck.', it: 'Il tempo giusto. Il fisico conta come parte del benessere, non come fine.', pt: 'O tempo certo. O físico importa como parte do bem-estar, não como fim.' }, dimension: 'V' },
        ],
      },
      {
        id: 6,
        situation: { es: 'Un restaurante tiene comida excelente pero un local muy sencillo. ¿Cómo lo vives?', en: 'A restaurant has excellent food but a very simple space. How do you experience it?', fr: 'Un restaurant a une excellente cuisine mais un local très simple. Comment le vivez-vous ?', de: 'Ein Restaurant hat ausgezeichnetes Essen, aber ein sehr einfaches Lokal. Wie erlebst du das?', it: 'Un ristorante ha un cibo eccellente ma un locale molto semplice. Come lo vivi?', pt: 'Um restaurante tem comida excelente, mas um local muito simples. Como você o vive?' },
        options: [
          { text: { es: 'Me cuesta disfrutarlo si el ambiente no está a la altura. El ambiente forma parte de la experiencia.', en: 'I find it hard to enjoy if the ambiance isn\'t up to par. The atmosphere is part of the experience.', fr: 'J\'ai du mal à en profiter si l\'ambiance n\'est pas à la hauteur. L\'ambiance fait partie de l\'expérience.', de: 'Ich finde es schwer zu genießen, wenn die Atmosphäre nicht stimmt. Das Ambiente ist Teil des Erlebnisses.', it: 'Faccio fatica a godermelo se l\'ambiente non è all\'altezza. L\'atmosfera fa parte dell\'esperienza.', pt: 'Tenho dificuldade em aproveitar se o ambiente não está à altura. O ambiente faz parte da experiência.' }, dimension: 'S' },
          { text: { es: 'La comida es lo central. El lugar es accesorio.', en: 'The food is what matters. The place is secondary.', fr: 'La nourriture est l\'essentiel. Le lieu est accessoire.', de: 'Das Essen ist das Zentrale. Der Ort ist Beiwerk.', it: 'Il cibo è l\'elemento centrale. Il posto è accessorio.', pt: 'A comida é o central. O lugar é acessório.' }, dimension: 'P' },
          { text: { es: 'Prefiero ambos, pero puedo disfrutar la comida aunque el lugar no sea especial.', en: 'I prefer both, but I can enjoy the food even if the place isn\'t special.', fr: 'Je préfère les deux, mais je peux profiter de la nourriture même si le lieu n\'est pas exceptionnel.', de: 'Ich bevorzuge beides, aber ich kann das Essen genießen, auch wenn der Ort nicht besonders ist.', it: 'Preferisco entrambi, ma posso godere del cibo anche se il posto non è speciale.', pt: 'Prefiro os dois, mas posso aproveitar a comida mesmo que o lugar não seja especial.' }, dimension: 'A' },
          { text: { es: 'Me alegra. La buena comida sin pretensiones es lo mejor.', en: 'It pleases me. Good unpretentious food is the best.', fr: 'Ça me réjouit. La bonne cuisine sans prétention, c\'est ce qu\'il y a de mieux.', de: 'Es freut mich. Gutes Essen ohne Schnickschnack ist das Beste.', it: 'Mi fa piacere. Il buon cibo senza pretese è il meglio.', pt: 'Me alegra. Boa comida sem pretensão é o melhor.' }, dimension: 'V' },
        ],
      },
      {
        id: 7,
        situation: { es: 'Alguien muy bien vestido y otro en ropa muy simple piden el mismo favor. ¿Hay diferencia en cómo respondes?', en: 'Someone very well dressed and someone in very simple clothes ask for the same favor. Is there a difference in how you respond?', fr: 'Une personne très bien habillée et une autre en vêtements très simples demandent le même service. Y a-t-il une différence dans votre réponse ?', de: 'Jemand sehr gut gekleidet und jemand in sehr einfacher Kleidung bitten um denselben Gefallen. Gibt es einen Unterschied in deiner Reaktion?', it: 'Qualcuno molto ben vestito e un altro in abiti molto semplici chiedono lo stesso favore. C\'è differenza nel modo in cui rispondi?', pt: 'Alguém muito bem vestido e outro com roupas muito simples pedem o mesmo favor. Há diferença em como você responde?' },
        options: [
          { text: { es: 'Probablemente sí, aunque no me guste admitirlo.', en: 'Probably yes, even if I don\'t like admitting it.', fr: 'Probablement oui, même si je n\'aime pas l\'admettre.', de: 'Wahrscheinlich ja, auch wenn ich es nicht gerne zugebe.', it: 'Probabilmente sì, anche se non mi piace ammetterlo.', pt: 'Provavelmente sim, embora não goste de admitir.' }, dimension: 'S' },
          { text: { es: 'Intento que no, aunque reconozco que el sesgo puede operar sin que lo note.', en: 'I try not to, although I acknowledge that bias can operate without my noticing.', fr: 'J\'essaie que non, bien que je reconnaisse que le biais peut agir sans que je le remarque.', de: 'Ich versuche es nicht, obwohl ich erkenne, dass der Bias wirken kann, ohne dass ich es bemerke.', it: 'Cerco di no, anche se riconosco che il pregiudizio può agire senza che me ne accorga.', pt: 'Procuro que não, embora reconheça que o preconceito pode operar sem que eu perceba.' }, dimension: 'P' },
          { text: { es: 'La presentación sí me afecta un poco. Es difícil no ser influido/a.', en: 'Presentation does affect me a little. It\'s hard not to be influenced.', fr: 'La présentation m\'affecte un peu. Il est difficile de ne pas être influencé(e).', de: 'Die Präsentation beeinflusst mich schon ein wenig. Es ist schwer, sich nicht beeinflussen zu lassen.', it: 'La presentazione mi influisce un po\'. È difficile non essere influenzati.', pt: 'A apresentação me afeta um pouco. É difícil não ser influenciado.' }, dimension: 'A' },
          { text: { es: 'No. Mi respuesta debería depender del favor en sí, no de quien lo pide.', en: 'No. My response should depend on the favor itself, not on who\'s asking.', fr: 'Non. Ma réponse devrait dépendre du service en lui-même, pas de qui le demande.', de: 'Nein. Meine Reaktion sollte vom Gefallen selbst abhängen, nicht davon, wer ihn bittet.', it: 'No. La mia risposta dovrebbe dipendere dal favore in sé, non da chi lo chiede.', pt: 'Não. Minha resposta deveria depender do favor em si, não de quem o pede.' }, dimension: 'V' },
        ],
      },
      {
        id: 8,
        situation: { es: '¿Cuánto te importa que tus amigos tengan buena presencia?', en: 'How much does it matter to you that your friends have a good presence?', fr: 'Dans quelle mesure est-il important pour vous que vos amis aient une bonne présentation ?', de: 'Wie wichtig ist es dir, dass deine Freunde eine gute Ausstrahlung haben?', it: 'Quanto ti importa che i tuoi amici abbiano una buona presenza?', pt: 'Quanto importa para você que seus amigos tenham boa presença?' },
        options: [
          { text: { es: 'Bastante. La imagen que proyectan mis amigos dice algo de mí también.', en: 'Quite a lot. The image my friends project says something about me too.', fr: 'Beaucoup. L\'image que projettent mes amis en dit aussi long sur moi.', de: 'Ziemlich viel. Das Bild, das meine Freunde projizieren, sagt auch etwas über mich aus.', it: 'Abbastanza. L\'immagine che proiettano i miei amici dice qualcosa anche di me.', pt: 'Bastante. A imagem que meus amigos projetam diz algo sobre mim também.' }, dimension: 'S' },
          { text: { es: 'Nada. Los amigos los elijo por lo que son, no por cómo se ven.', en: 'Not at all. I choose friends for who they are, not how they look.', fr: 'Rien du tout. Je choisis mes amis pour ce qu\'ils sont, pas pour leur apparence.', de: 'Gar nicht. Freunde wähle ich danach aus, wer sie sind, nicht wie sie aussehen.', it: 'Per niente. Scelgo gli amici per quello che sono, non per come appaiono.', pt: 'Nada. Escolho amigos pelo que são, não por como aparecem.' }, dimension: 'P' },
          { text: { es: 'Algo. Prefiero no tener que justificar a mis amigos ante otros.', en: 'Somewhat. I prefer not having to justify my friends to others.', fr: 'Un peu. Je préfère ne pas avoir à justifier mes amis auprès des autres.', de: 'Etwas. Ich bevorzuge es, meine Freunde nicht vor anderen erklären zu müssen.', it: 'Qualcosa. Preferisco non dover giustificare i miei amici di fronte ad altri.', pt: 'Um pouco. Prefiro não ter que justificar meus amigos perante outros.' }, dimension: 'A' },
          { text: { es: 'No me importa. Lo que importa es si son buena gente.', en: 'It doesn\'t matter to me. What matters is whether they\'re good people.', fr: 'Ça ne m\'importe pas. Ce qui compte, c\'est s\'ils sont de bonnes personnes.', de: 'Es ist mir egal. Was zählt, ist ob sie gute Menschen sind.', it: 'Non mi importa. Ciò che conta è se sono buone persone.', pt: 'Não me importa. O que importa é se são boas pessoas.' }, dimension: 'V' },
        ],
      },
      {
        id: 9,
        situation: { es: 'Ves un perfil de una persona sin fotos en una app de citas. ¿Qué haces?', en: 'You see a profile with no photos on a dating app. What do you do?', fr: 'Vous voyez un profil sans photos sur une application de rencontres. Que faites-vous ?', de: 'Du siehst ein Profil ohne Fotos auf einer Dating-App. Was machst du?', it: 'Vedi un profilo senza foto su un\'app di incontri. Cosa fai?', pt: 'Você vê um perfil sem fotos em um aplicativo de relacionamento. O que você faz?' },
        options: [
          { text: { es: 'Paso inmediatamente. Sin foto, no hay posibilidad.', en: 'I skip immediately. No photo, no possibility.', fr: 'Je passe immédiatement. Sans photo, pas de possibilité.', de: 'Ich überspringe sofort. Ohne Foto keine Möglichkeit.', it: 'Passo immediatamente. Senza foto, nessuna possibilità.', pt: 'Passo imediatamente. Sem foto, sem possibilidade.' }, dimension: 'S' },
          { text: { es: 'Leo el perfil. Si el texto es interesante, le escribo.', en: 'I read the profile. If the text is interesting, I write to them.', fr: 'Je lis le profil. Si le texte est intéressant, je lui écris.', de: 'Ich lese das Profil. Wenn der Text interessant ist, schreibe ich.', it: 'Leggo il profilo. Se il testo è interessante, gli scrivo.', pt: 'Leio o perfil. Se o texto for interessante, escrevo.' }, dimension: 'P' },
          { text: { es: 'Necesito ver una foto. La atracción física es necesaria para que valga la pena.', en: 'I need to see a photo. Physical attraction is necessary for it to be worth pursuing.', fr: 'J\'ai besoin de voir une photo. L\'attraction physique est nécessaire pour que ça vaille la peine.', de: 'Ich muss ein Foto sehen. Körperliche Anziehung ist notwendig, damit es sich lohnt.', it: 'Ho bisogno di vedere una foto. L\'attrazione fisica è necessaria perché valga la pena.', pt: 'Preciso ver uma foto. A atração física é necessária para que valha a pena.' }, dimension: 'A' },
          { text: { es: 'Podría escribir si el perfil muestra quién es. La foto es menos importante que lo que proyecta.', en: 'I might write if the profile shows who they are. The photo is less important than what they project.', fr: 'Je pourrais écrire si le profil montre qui est la personne. La photo est moins importante que ce qu\'elle projette.', de: 'Ich könnte schreiben, wenn das Profil zeigt, wer sie sind. Das Foto ist weniger wichtig als das, was sie projizieren.', it: 'Potrei scrivere se il profilo mostra chi è. La foto è meno importante di ciò che proietta.', pt: 'Poderia escrever se o perfil mostra quem é. A foto é menos importante do que o que projeta.' }, dimension: 'V' },
        ],
      },
      {
        id: 10,
        situation: { es: 'Alguien te da un regalo que claramente es caro pero horrible según tu gusto. ¿Cómo reaccionas internamente?', en: 'Someone gives you a gift that\'s clearly expensive but terrible according to your taste. How do you react internally?', fr: 'Quelqu\'un vous offre un cadeau qui est clairement cher mais horrible selon vos goûts. Comment réagissez-vous intérieurement ?', de: 'Jemand gibt dir ein Geschenk, das eindeutig teuer, aber nach deinem Geschmack schrecklich ist. Wie reagierst du innerlich?', it: 'Qualcuno ti fa un regalo che è chiaramente caro ma orribile secondo i tuoi gusti. Come reagisci internamente?', pt: 'Alguém te dá um presente que claramente é caro, mas horrível segundo seu gosto. Como você reage internamente?' },
        options: [
          { text: { es: 'El gesto está ahí, pero no puedo evitar pensar que gastó en algo que nunca voy a usar.', en: 'The gesture is there, but I can\'t help thinking they spent on something I\'ll never use.', fr: 'Le geste est là, mais je ne peux m\'empêcher de penser qu\'il a dépensé pour quelque chose que je n\'utiliserai jamais.', de: 'Die Geste ist da, aber ich kann nicht aufhören zu denken, dass sie Geld für etwas ausgegeben haben, das ich nie benutzen werde.', it: 'Il gesto c\'è, ma non posso fare a meno di pensare che ha speso per qualcosa che non userò mai.', pt: 'O gesto está lá, mas não consigo evitar pensar que gastou em algo que nunca usarei.' }, dimension: 'S' },
          { text: { es: 'Me emocionó el gesto. El objeto es lo de menos.', en: 'The gesture moved me. The object is the least important thing.', fr: 'Le geste m\'a ému(e). L\'objet est ce qui compte le moins.', de: 'Die Geste hat mich bewegt. Das Objekt ist das Unwichtigste.', it: 'Mi ha emozionato il gesto. L\'oggetto è la cosa meno importante.', pt: 'O gesto me emocionou. O objeto é o menos importante.' }, dimension: 'P' },
          { text: { es: 'Aprecio el esfuerzo pero sí me importa si voy a poder usarlo o no.', en: 'I appreciate the effort but it does matter to me whether I\'ll be able to use it or not.', fr: 'J\'apprécie l\'effort, mais ça m\'importe quand même de savoir si je pourrai l\'utiliser ou non.', de: 'Ich schätze die Mühe, aber es ist mir schon wichtig, ob ich es benutzen kann oder nicht.', it: 'Apprezzo lo sforzo ma mi importa se riuscirò ad usarlo o no.', pt: 'Aprecio o esforço, mas me importa se vou poder usá-lo ou não.' }, dimension: 'A' },
          { text: { es: 'Lo que me importa es el cariño detrás. Cualquier expresión de eso es valiosa.', en: 'What matters to me is the affection behind it. Any expression of that is valuable.', fr: 'Ce qui m\'importe, c\'est l\'affection derrière. Toute expression de cela est précieuse.', de: 'Was mir wichtig ist, ist die Zuneigung dahinter. Jeder Ausdruck davon ist wertvoll.', it: 'Ciò che mi importa è l\'affetto dietro. Qualsiasi espressione di quello è preziosa.', pt: 'O que me importa é o carinho por trás. Qualquer expressão disso é valiosa.' }, dimension: 'V' },
        ],
      },
    ],
    characters: [
      { name: { es: 'El Superficial Puro', en: 'The Pure Superficial', fr: 'Le Superficiel Pur', de: 'Der Reine Oberflächliche', it: 'Il Superficiale Puro', pt: 'O Superficial Puro' }, dimensions: ['S'], photo: '/characters/superficial.jpg', description: { es: 'La imagen lo es todo. El fondo, decorativo.', en: 'Image is everything. The depth, decorative.', fr: 'L\'image est tout. Le fond, décoratif.', de: 'Das Image ist alles. Der Inhalt, dekorativ.', it: 'L\'immagine è tutto. Il contenuto, decorativo.', pt: 'A imagem é tudo. O fundo, decorativo.' }, philosophy: { es: 'Para ti, lo que se ve importa más que lo que hay detrás. No porque seas malo/a — sino porque el mundo en el que vives recompensa la apariencia constantemente. Esa es una verdad incómoda que comparte contigo mucha gente.', en: 'For you, what\'s visible matters more than what lies beneath. Not because you\'re bad — but because the world you live in constantly rewards appearance. That\'s an uncomfortable truth shared by many.', fr: 'Pour vous, ce qui se voit importe plus que ce qui se trouve en dessous. Non pas parce que vous êtes mauvais(e) — mais parce que le monde dans lequel vous vivez récompense constamment l\'apparence. C\'est une vérité inconfortable que beaucoup partagent avec vous.', de: 'Für dich ist wichtiger, was man sieht, als was dahinter steckt. Nicht weil du schlecht bist — sondern weil die Welt, in der du lebst, das Äußere ständig belohnt. Das ist eine unbequeme Wahrheit, die viele mit dir teilen.', it: 'Per te, ciò che si vede conta più di ciò che c\'è dietro. Non perché tu sia cattivo/a — ma perché il mondo in cui vivi premia costantemente l\'apparenza. Questa è una verità scomoda che molti condividono con te.', pt: 'Para você, o que se vê importa mais do que o que há por trás. Não porque seja mau/má — mas porque o mundo em que você vive recompensa constantemente a aparência. Essa é uma verdade desconfortável que muitas pessoas compartilham.' } },
      { name: { es: 'El Buscador de Profundidad', en: 'The Depth Seeker', fr: 'Le Chercheur de Profondeur', de: 'Der Tiefe Sucher', it: 'Il Cercatore di Profondità', pt: 'O Buscador de Profundidade' }, dimensions: ['P'], photo: '/characters/depth-seeker.jpg', description: { es: 'Le interesan las personas por lo que son, no por cómo se ven.', en: 'Interested in people for who they are, not how they look.', fr: 'S\'intéresse aux personnes pour ce qu\'elles sont, pas pour leur apparence.', de: 'Interessiert sich für Menschen dafür, wer sie sind, nicht wie sie aussehen.', it: 'Si interessa alle persone per quello che sono, non per come appaiono.', pt: 'Se interessa pelas pessoas pelo que são, não por como se parecem.' }, philosophy: { es: 'Para ti, la sustancia es lo que importa. Puedes mirar más allá de la imagen con una facilidad que no todo el mundo tiene. Eso te da acceso a conversaciones, relaciones y perspectivas que los superficiales nunca llegan a ver.', en: 'For you, substance is what matters. You can look beyond the image with an ease not everyone has. That gives you access to conversations, relationships, and perspectives that superficial people never get to see.', fr: 'Pour vous, la substance est ce qui compte. Vous pouvez regarder au-delà de l\'image avec une facilité que tout le monde n\'a pas. Cela vous donne accès à des conversations, des relations et des perspectives que les superficiels ne voient jamais.', de: 'Für dich ist Substanz das, was zählt. Du kannst mit einer Leichtigkeit über das Äußere hinaussehen, die nicht jeder hat. Das gibt dir Zugang zu Gesprächen, Beziehungen und Perspektiven, die Oberflächliche nie sehen.', it: 'Per te, la sostanza è ciò che conta. Puoi guardare oltre l\'immagine con una facilità che non tutti hanno. Questo ti dà accesso a conversazioni, relazioni e prospettive che i superficiali non arrivano mai a vedere.', pt: 'Para você, a substância é o que importa. Você consegue olhar além da imagem com uma facilidade que nem todos têm. Isso te dá acesso a conversas, relações e perspectivas que os superficiais nunca chegam a ver.' } },
      { name: { es: 'El Estético Honesto', en: 'The Honest Aesthetic', fr: 'L\'Esthète Honnête', de: 'Der Ehrliche Ästhet', it: 'L\'Estetico Onesto', pt: 'O Estético Honesto' }, dimensions: ['A'], photo: '/characters/aesthetic-honest.jpg', description: { es: 'Le importa la apariencia y lo reconoce sin pretextos.', en: 'Cares about appearance and admits it without pretexts.', fr: 'L\'apparence compte pour lui et il le reconnaît sans prétextes.', de: 'Das Äußere ist ihm wichtig und er gibt es ohne Vorwände zu.', it: 'Gli interessa l\'apparenza e lo riconosce senza pretesti.', pt: 'Se importa com a aparência e o reconhece sem pretextos.' }, philosophy: { es: 'Eres honesto/a: la atracción visual importa y no lo niegas. No moralizar sobre ello no te hace superficial — te hace realista. La clave está en si eso es lo único que te importa.', en: 'You\'re honest: visual attraction matters and you don\'t deny it. Not moralizing about it doesn\'t make you superficial — it makes you realistic. The key is whether that\'s the only thing you care about.', fr: 'Vous êtes honnête : l\'attraction visuelle compte et vous ne le niez pas. Ne pas moraliser à ce sujet ne vous rend pas superficiel(le) — cela vous rend réaliste. La clé est de savoir si c\'est la seule chose qui vous importe.', de: 'Du bist ehrlich: visuelle Anziehung ist wichtig und du leugnest es nicht. Darüber nicht zu moralisieren macht dich nicht oberflächlich — es macht dich realistisch. Der Schlüssel liegt darin, ob das das Einzige ist, was dir wichtig ist.', it: 'Sei onesto/a: l\'attrazione visiva conta e non lo neghi. Non moralizzare su questo non ti rende superficiale — ti rende realista. La chiave sta nel se questa è l\'unica cosa che ti importa.', pt: 'Você é honesto/a: a atração visual importa e não nega isso. Não moralizar sobre isso não te torna superficial — te torna realista. A chave está em se isso é a única coisa que te importa.' } },
      { name: { es: 'El Orientado a Valores', en: 'The Values-Oriented', fr: 'L\'Orienté vers les Valeurs', de: 'Der Werteorientierte', it: 'L\'Orientato ai Valori', pt: 'O Orientado a Valores' }, dimensions: ['V'], photo: '/characters/values-oriented.jpg', description: { es: 'Lo que guía sus elecciones son los valores, no la imagen.', en: 'What guides their choices are values, not image.', fr: 'Ce qui guide ses choix, ce sont les valeurs, pas l\'image.', de: 'Was seine Entscheidungen leitet, sind Werte, nicht das Äußere.', it: 'Ciò che guida le sue scelte sono i valori, non l\'immagine.', pt: 'O que guia suas escolhas são os valores, não a imagem.' }, philosophy: { es: 'Para ti, el carácter de una persona — lo que valora, cómo trata a los demás, qué lo mueve — es lo que define si merece tu tiempo y tu atención. La imagen es información secundaria.', en: 'For you, a person\'s character — what they value, how they treat others, what moves them — is what determines whether they deserve your time and attention. Image is secondary information.', fr: 'Pour vous, le caractère d\'une personne — ce qu\'elle valorise, comment elle traite les autres, ce qui la motive — est ce qui détermine si elle mérite votre temps et votre attention. L\'image est une information secondaire.', de: 'Für dich ist der Charakter einer Person — was sie schätzt, wie sie andere behandelt, was sie bewegt — das, was bestimmt, ob sie deine Zeit und Aufmerksamkeit verdient. Das Äußere ist sekundäre Information.', it: 'Per te, il carattere di una persona — ciò che valorizza, come tratta gli altri, cosa la muove — è ciò che determina se merita il tuo tempo e la tua attenzione. L\'immagine è informazione secondaria.', pt: 'Para você, o caráter de uma pessoa — o que valoriza, como trata os outros, o que a move — é o que define se merece seu tempo e atenção. A imagem é informação secundária.' } },
      { name: { es: 'El Superficial con Conciencia', en: 'The Superficial with Awareness', fr: 'Le Superficiel Conscient', de: 'Der Oberflächliche mit Bewusstsein', it: 'Il Superficiale Consapevole', pt: 'O Superficial com Consciência' }, dimensions: ['S', 'P'], photo: '/characters/superficial-aware.jpg', description: { es: 'Juzga por la apariencia pero sabe que no debería.', en: 'Judges by appearance but knows they shouldn\'t.', fr: 'Juge sur les apparences mais sait qu\'il ne devrait pas.', de: 'Urteilt nach dem Äußeren, weiß aber, dass er es nicht sollte.', it: 'Giudica dall\'apparenza ma sa che non dovrebbe.', pt: 'Julga pela aparência, mas sabe que não deveria.' }, philosophy: { es: 'Te importa la imagen más de lo que quisiera. Lo reconoces. Hay una tensión entre lo que valoras en teoría y cómo actúas en práctica. Esa tensión es incómoda pero es lo que permite el cambio.', en: 'Image matters to you more than you\'d like. You recognize that. There\'s a tension between what you value in theory and how you act in practice. That tension is uncomfortable but it\'s what allows for change.', fr: 'L\'image vous importe plus que vous ne le souhaiteriez. Vous le reconnaissez. Il y a une tension entre ce que vous valorisez en théorie et comment vous agissez en pratique. Cette tension est inconfortable, mais c\'est elle qui permet le changement.', de: 'Das Image ist dir mehr wichtig, als du es gerne hättest. Du erkennst das. Es gibt eine Spannung zwischen dem, was du in der Theorie wertschätzt, und wie du in der Praxis handelst. Diese Spannung ist unbequem, aber sie ermöglicht Veränderung.', it: 'L\'immagine ti importa più di quanto vorresti. Lo riconosci. C\'è una tensione tra ciò che valorizzi in teoria e come agisci in pratica. Quella tensione è scomoda ma è ciò che permette il cambiamento.', pt: 'A imagem te importa mais do que você gostaria. Você reconhece isso. Há uma tensão entre o que você valoriza na teoria e como age na prática. Essa tensão é desconfortável, mas é o que permite a mudança.' } },
      { name: { es: 'El Estético Profundo', en: 'The Deep Aesthetic', fr: 'L\'Esthète Profond', de: 'Der Tiefe Ästhet', it: 'L\'Estetico Profondo', pt: 'O Estético Profundo' }, dimensions: ['A', 'P'], photo: '/characters/aesthetic-deep.jpg', description: { es: 'Aprecia la belleza y la profundidad por igual.', en: 'Appreciates beauty and depth equally.', fr: 'Apprécie la beauté et la profondeur de manière égale.', de: 'Schätzt Schönheit und Tiefe gleichermaßen.', it: 'Apprezza la bellezza e la profondità in egual misura.', pt: 'Aprecia a beleza e a profundidade igualmente.' }, philosophy: { es: 'No te parece que profundidad y apariencia sean opuestos. Puedes valorar la estética y al mismo tiempo buscar sustancia. Para ti, la belleza en todas sus formas — visual, intelectual, humana — vale la pena.', en: 'You don\'t see depth and appearance as opposites. You can appreciate aesthetics and seek substance at the same time. For you, beauty in all its forms — visual, intellectual, human — is worth it.', fr: 'Vous ne pensez pas que la profondeur et l\'apparence soient des opposés. Vous pouvez valoriser l\'esthétique tout en recherchant la substance. Pour vous, la beauté sous toutes ses formes — visuelle, intellectuelle, humaine — vaut la peine.', de: 'Du siehst Tiefe und Äußerlichkeit nicht als Gegensätze. Du kannst Ästhetik schätzen und gleichzeitig Substanz suchen. Für dich ist Schönheit in all ihren Formen — visuell, intellektuell, menschlich — es wert.', it: 'Non ti sembra che profondità e apparenza siano opposti. Puoi valorizzare l\'estetica e allo stesso tempo cercare sostanza. Per te, la bellezza in tutte le sue forme — visiva, intellettuale, umana — vale la pena.', pt: 'Não te parece que profundidade e aparência sejam opostos. Você consegue valorizar a estética e ao mesmo tempo buscar substância. Para você, a beleza em todas as suas formas — visual, intelectual, humana — vale a pena.' } },
      { name: { es: 'El Selectivo Estético', en: 'The Selective Aesthetic', fr: 'L\'Esthète Sélectif', de: 'Der Selektive Ästhet', it: 'L\'Estetico Selettivo', pt: 'O Seletivo Estético' }, dimensions: ['S', 'V'], photo: '/characters/selective-aesthetic.jpg', description: { es: 'Le importa la imagen pero también los valores. Los dos.', en: 'Cares about image but also values. Both.', fr: 'L\'image lui importe, mais aussi les valeurs. Les deux.', de: 'Das Image ist ihm wichtig, aber auch die Werte. Beides.', it: 'Gli importa l\'immagine ma anche i valori. Entrambi.', pt: 'Importa-se com a imagem, mas também com os valores. Os dois.' }, philosophy: { es: 'Tienes estándares en dos dimensiones: quieres que la persona sea buena y que tenga presencia. Para ti, no son intercambiables. No cedes en la imagen por valores ni en valores por imagen.', en: 'You have standards in two dimensions: you want the person to be good and to have presence. For you, they\'re not interchangeable. You don\'t give up image for values or values for image.', fr: 'Vous avez des critères dans deux dimensions : vous voulez que la personne soit bonne et qu\'elle ait une présence. Pour vous, elles ne sont pas interchangeables. Vous ne cédez pas sur l\'image au profit des valeurs, ni sur les valeurs au profit de l\'image.', de: 'Du hast Maßstäbe in zwei Dimensionen: Du möchtest, dass die Person gut ist und Ausstrahlung hat. Für dich sind sie nicht austauschbar. Du gibst nicht Image für Werte auf noch Werte für Image.', it: 'Hai standard in due dimensioni: vuoi che la persona sia buona e che abbia presenza. Per te, non sono intercambiabili. Non cedi sull\'immagine per i valori né sui valori per l\'immagine.', pt: 'Você tem padrões em duas dimensões: quer que a pessoa seja boa e que tenha presença. Para você, não são intercambiáveis. Não cede na imagem pelos valores nem nos valores pela imagem.' } },
      { name: { es: 'El Equilibrado Real', en: 'The Truly Balanced', fr: 'L\'Équilibré Réel', de: 'Der Wirklich Ausgeglichene', it: 'L\'Equilibrato Reale', pt: 'O Equilibrado Real' }, dimensions: ['P', 'V'], photo: '/characters/real-balanced.jpg', description: { es: 'Profundidad y valores. La apariencia es lo de menos.', en: 'Depth and values. Appearance is the least of it.', fr: 'Profondeur et valeurs. L\'apparence est le cadet de ses soucis.', de: 'Tiefe und Werte. Das Äußere ist das Unwichtigste.', it: 'Profondità e valori. L\'apparenza è la cosa meno importante.', pt: 'Profundidade e valores. A aparência é o menos importante.' }, philosophy: { es: 'Para ti, lo que una persona es — sus ideas, sus valores, cómo trata a otros — es infinitamente más interesante que cómo se ve. Eso te da acceso a un mundo mucho más rico.', en: 'For you, what a person is — their ideas, their values, how they treat others — is infinitely more interesting than how they look. That gives you access to a much richer world.', fr: 'Pour vous, ce qu\'une personne est — ses idées, ses valeurs, comment elle traite les autres — est infiniment plus intéressant que son apparence. Cela vous donne accès à un monde bien plus riche.', de: 'Für dich ist das, was eine Person ist — ihre Ideen, ihre Werte, wie sie andere behandelt — unendlich interessanter als ihr Aussehen. Das gibt dir Zugang zu einer viel reicheren Welt.', it: 'Per te, ciò che una persona è — le sue idee, i suoi valori, come tratta gli altri — è infinitamente più interessante di come appare. Questo ti dà accesso a un mondo molto più ricco.', pt: 'Para você, o que uma pessoa é — suas ideias, seus valores, como trata os outros — é infinitamente mais interessante do que como se parece. Isso te dá acesso a um mundo muito mais rico.' } },
    ],
  };

  await prisma.quiz.upsert({
    where: { slug: 'superficial' },
    update: {
      title: data.title,
      description: data.description,
      scenarioLabel: data.scenarioLabel,
      dimensionLabels: data.dimensionLabels,
      questions: data.questions,
      characters: data.characters,
    },
    create: data,
  });
}
