import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Realidad o Virtualidad?', en: 'Reality or Virtuality?', fr: 'Réalité ou Virtualité ?', de: 'Realität oder Virtualität?', it: 'Realtà o Virtualità?', pt: 'Realidade ou Virtualidade?' },
  description: { es: '10 escenarios donde la realidad virtual ofrece alternativas tentadoras. Descubre qué valoras más y dónde está tu punto de inflexión entre lo real y lo virtual.', en: '10 scenarios where virtual reality offers tempting alternatives. Discover what you value most and where your tipping point between the real and the virtual lies.', fr: '10 scénarios où la réalité virtuelle offre des alternatives tentantes. Découvrez ce que vous valorisez le plus et où se trouve votre point de basculement.', de: '10 Szenarien, in denen virtuelle Realität verlockende Alternativen bietet. Entdecke, was du am meisten schätzt und wo dein Wendepunkt zwischen Real und Virtuell liegt.', it: '10 scenari in cui la realtà virtuale offre alternative allettanti. Scopri cosa apprezzi di più e dove si trova il tuo punto di svolta tra il reale e il virtuale.', pt: '10 cenários em que a realidade virtual oferece alternativas tentadoras. Descubra o que você valoriza mais e onde está seu ponto de inflexão entre o real e o virtual.' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { A: 'Autenticidad', P: 'Placer', V: 'Vínculo', S: 'Sentido' },
    en: { A: 'Authenticity', P: 'Pleasure', V: 'Connection', S: 'Meaning' },
    fr: { A: 'Authenticité', P: 'Plaisir', V: 'Lien', S: 'Sens' },
    de: { A: 'Authentizität', P: 'Vergnügen', V: 'Verbindung', S: 'Bedeutung' },
    it: { A: 'Autenticità', P: 'Piacere', V: 'Legame', S: 'Senso' },
    pt: { A: 'Autenticidade', P: 'Prazer', V: 'Vínculo', S: 'Sentido' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu pareja falleció hace un año. Una empresa ofrece una simulación perfecta: su voz, sus gestos, sus recuerdos. Puedes cenar con ella cada noche. ¿Qué haces?', en: 'Your partner passed away a year ago. A company offers a perfect simulation: their voice, gestures, memories. You can dine with them every night. What do you do?', fr: 'Ton partenaire est décédé il y a un an. Une entreprise propose une simulation parfaite: sa voix, ses gestes, ses souvenirs. Tu peux dîner avec lui/elle chaque soir. Que fais-tu ?', de: 'Dein Partner ist vor einem Jahr gestorben. Ein Unternehmen bietet eine perfekte Simulation an: seine Stimme, Gesten, Erinnerungen. Du kannst jeden Abend mit ihr/ihm speisen. Was machst du?', it: 'Il tuo partner è morto un anno fa. Un\'azienda offre una simulazione perfetta: la sua voce, i suoi gesti, i suoi ricordi. Puoi cenare con lui/lei ogni sera. Cosa fai?', pt: 'Seu parceiro faleceu há um ano. Uma empresa oferece uma simulação perfeita: sua voz, gestos, memórias. Você pode jantar com ele/ela toda noite. O que você faz?' }, options: [
      { text: { es: 'Lo rechazo. Por más perfecta que sea la copia, no es ella. Prefiero el dolor real al consuelo artificial.', en: 'I refuse. No matter how perfect the copy, it\'s not them. I prefer real pain to artificial comfort.', fr: 'Je refuse. Aussi parfaite que soit la copie, ce n\'est pas lui/elle. Je préfère la douleur réelle au réconfort artificiel.', de: 'Ich lehne ab. Egal wie perfekt die Kopie ist, sie ist es nicht. Ich bevorzuge echten Schmerz vor künstlichem Trost.', it: 'Rifiuto. Per quanto perfetta sia la copia, non è lei/lui. Preferisco il dolore reale al conforto artificiale.', pt: 'Recuso. Por mais perfeita que seja a cópia, não é ela. Prefiro a dor real ao conforto artificial.' }, dimension: 'A' },
      { text: { es: 'Lo acepto sin dudarlo. Si la experiencia es indistinguible, el bienestar que me da es real.', en: 'I accept without hesitation. If the experience is indistinguishable, the well-being it gives me is real.', fr: 'J\'accepte sans hésiter. Si l\'expérience est indiscernable, le bien-être qu\'elle me procure est réel.', de: 'Ich akzeptiere ohne Zögern. Wenn die Erfahrung nicht zu unterscheiden ist, ist das Wohlbefinden, das sie mir gibt, real.', it: 'Accetto senza esitare. Se l\'esperienza è indistinguibile, il benessere che mi dona è reale.', pt: 'Aceito sem hesitar. Se a experiência é indistinguível, o bem-estar que me proporciona é real.' }, dimension: 'P' },
      { text: { es: 'Lo rechazo. Esa simulación no puede amarme de vuelta. Sin reciprocidad, es un monólogo.', en: 'I refuse. That simulation cannot love me back. Without reciprocity, it\'s a monologue.', fr: 'Je refuse. Cette simulation ne peut pas m\'aimer en retour. Sans réciprocité, c\'est un monologue.', de: 'Ich lehne ab. Diese Simulation kann mich nicht zurücklieben. Ohne Gegenseitigkeit ist es ein Monolog.', it: 'Rifiuto. Quella simulazione non può amarmi in cambio. Senza reciprocità, è un monologo.', pt: 'Recuso. Essa simulação não pode me amar de volta. Sem reciprocidade, é um monólogo.' }, dimension: 'V' },
      { text: { es: 'Lo rechazo. El duelo es parte de haber amado. Evitar el dolor traicionaría lo que significó esa relación.', en: 'I refuse. Grief is part of having loved. Avoiding pain would betray what that relationship meant.', fr: 'Je refuse. Le deuil fait partie d\'avoir aimé. Éviter la douleur trahirait ce que cette relation a signifié.', de: 'Ich lehne ab. Trauer ist ein Teil des Liebens. Den Schmerz zu vermeiden würde das verraten, was diese Beziehung bedeutet hat.', it: 'Rifiuto. Il dolore fa parte dell\'aver amato. Evitare il dolore tradirebbe ciò che ha significato quella relazione.', pt: 'Recuso. O luto faz parte de ter amado. Evitar a dor trairia o que aquele relacionamento significou.' }, dimension: 'S' },
    ] },
    { id: 2, situation: { es: 'Puedes tener el trabajo de tus sueños en una simulación — liderar proyectos, ser reconocido — o quedarte con tu trabajo real, mediocre pero tangible.', en: 'You can have your dream job in a simulation — leading projects, being recognized — or keep your real job, mediocre but tangible.', fr: 'Tu peux avoir le travail de tes rêves dans une simulation — diriger des projets, être reconnu — ou garder ton vrai travail, médiocre mais tangible.', de: 'Du kannst deinen Traumjob in einer Simulation haben — Projekte leiten, anerkannt werden — oder deinen echten Job behalten, mittelmäßig aber greifbar.', it: 'Puoi avere il lavoro dei tuoi sogni in una simulazione — guidare progetti, essere riconosciuto — oppure tenere il tuo lavoro reale, mediocre ma tangibile.', pt: 'Você pode ter o emprego dos seus sonhos em uma simulação — liderar projetos, ser reconhecido — ou ficar com seu emprego real, medíocre mas tangível.' }, options: [
      { text: { es: 'Me quedo con lo real. Un logro simulado es una mentira que me cuento a mí mismo.', en: 'I stay with reality. A simulated achievement is a lie I tell myself.', fr: 'Je reste avec la réalité. Une réussite simulée est un mensonge que je me raconte.', de: 'Ich bleibe beim Echten. Eine simulierte Leistung ist eine Lüge, die ich mir selbst erzähle.', it: 'Resto con il reale. Un risultato simulato è una bugia che mi racconto.', pt: 'Fico com o real. Uma conquista simulada é uma mentira que conto para mim mesmo.' }, dimension: 'A' },
      { text: { es: 'Elijo lo virtual. Si la satisfacción se siente real, ¿qué más da dónde ocurre?', en: 'I choose virtual. If the satisfaction feels real, what does it matter where it happens?', fr: 'Je choisis le virtuel. Si la satisfaction est réelle, qu\'importe où cela se passe ?', de: 'Ich wähle das Virtuelle. Wenn sich die Befriedigung real anfühlt, spielt es keine Rolle, wo sie stattfindet.', it: 'Scelgo il virtuale. Se la soddisfazione si sente reale, che importa dove avviene?', pt: 'Escolho o virtual. Se a satisfação é real, que importa onde ocorre?' }, dimension: 'P' },
      { text: { es: 'Me quedo con lo real. Prefiero el reconocimiento de personas reales que la admiración programada.', en: 'I stay with the real. I prefer recognition from real people over programmed admiration.', fr: 'Je reste avec la réalité. Je préfère la reconnaissance de vraies personnes à l\'admiration programmée.', de: 'Ich bleibe beim Echten. Ich bevorzuge Anerkennung von echten Menschen gegenüber programmierter Bewunderung.', it: 'Resto con il reale. Preferisco il riconoscimento di persone reali all\'ammirazione programmata.', pt: 'Fico com o real. Prefiro o reconhecimento de pessoas reais à admiração programada.' }, dimension: 'V' },
      { text: { es: 'Me quedo con lo real. La frustración del trabajo mediocre me impulsa a mejorar.', en: 'I stay with the real. The frustration of a mediocre job drives me to improve.', fr: 'Je reste avec la réalité. La frustration du travail médiocre m\'incite à m\'améliorer.', de: 'Ich bleibe beim Echten. Die Frustration des mittelmäßigen Jobs treibt mich dazu an, mich zu verbessern.', it: 'Resto con il reale. La frustrazione del lavoro mediocre mi spinge a migliorare.', pt: 'Fico com o real. A frustração do trabalho medíocre me impulsiona a melhorar.' }, dimension: 'S' },
    ] },
    { id: 3, situation: { es: 'Te ofrecen un avatar virtual: un cuerpo que nunca envejece, nunca se enferma. Tu cuerpo real seguirá deteriorándose. ¿Qué eliges?', en: 'You\'re offered a virtual avatar: a body that never ages, never gets sick. Your real body will keep deteriorating. What do you choose?', fr: 'On te propose un avatar virtuel: un corps qui ne vieillit jamais, ne tombe jamais malade. Ton vrai corps continuera à se détériorer. Que choisis-tu ?', de: 'Dir wird ein virtueller Avatar angeboten: ein Körper, der nie altert, nie krank wird. Dein echter Körper wird sich weiter verschlechtern. Was wählst du?', it: 'Ti viene offerto un avatar virtuale: un corpo che non invecchia mai, non si ammala mai. Il tuo corpo reale continuerà a deteriorarsi. Cosa scegli?', pt: 'É oferecido um avatar virtual: um corpo que nunca envelhece, nunca adoece. Seu corpo real continuará se deteriorando. O que você escolhe?' }, options: [
      { text: { es: 'Me quedo con mi cuerpo real. Mis cicatrices y arrugas cuentan mi historia.', en: 'I stay with my real body. My scars and wrinkles tell my story.', fr: 'Je reste avec mon vrai corps. Mes cicatrices et mes rides racontent mon histoire.', de: 'Ich bleibe bei meinem echten Körper. Meine Narben und Falten erzählen meine Geschichte.', it: 'Resto con il mio corpo reale. Le mie cicatrici e rughe raccontano la mia storia.', pt: 'Fico com meu corpo real. Minhas cicatrizes e rugas contam minha história.' }, dimension: 'A' },
      { text: { es: 'Acepto el avatar. Si puedo vivir sin dolor físico ni limitaciones, ¿por qué no?', en: 'I accept the avatar. If I can live without physical pain or limitations, why not?', fr: 'J\'accepte l\'avatar. Si je peux vivre sans douleur physique ni limitations, pourquoi pas ?', de: 'Ich akzeptiere den Avatar. Wenn ich ohne körperliche Schmerzen oder Einschränkungen leben kann, warum nicht?', it: 'Accetto l\'avatar. Se posso vivere senza dolore fisico né limitazioni, perché no?', pt: 'Aceito o avatar. Se posso viver sem dor física nem limitações, por que não?' }, dimension: 'P' },
      { text: { es: 'Me quedo con lo real. Quiero que las personas me conozcan como soy, no idealizado.', en: 'I stay with the real. I want people to know me as I am, not idealized.', fr: 'Je reste avec la réalité. Je veux que les gens me connaissent tel que je suis, pas idéalisé.', de: 'Ich bleibe beim Echten. Ich möchte, dass die Menschen mich so kennen, wie ich bin, nicht idealisiert.', it: 'Resto con il reale. Voglio che le persone mi conoscano così come sono, non idealizzato.', pt: 'Fico com o real. Quero que as pessoas me conheçam como sou, não idealizado.' }, dimension: 'V' },
      { text: { es: 'Me quedo con lo real. Las limitaciones del cuerpo me enseñan disciplina y gratitud.', en: 'I stay with the real. The body\'s limitations teach me discipline and gratitude.', fr: 'Je reste avec la réalité. Les limitations du corps m\'enseignent la discipline et la gratitude.', de: 'Ich bleibe beim Echten. Die Grenzen des Körpers lehren mich Disziplin und Dankbarkeit.', it: 'Resto con il reale. Le limitazioni del corpo mi insegnano disciplina e gratitudine.', pt: 'Fico com o real. As limitações do corpo me ensinam disciplina e gratidão.' }, dimension: 'S' },
    ] },
    { id: 4, situation: { es: 'Puedes tener amigos virtuales perfectamente compatibles: nunca te traicionan, siempre disponibles. ¿O prefieres tus amistades reales con sus defectos?', en: 'You can have perfectly compatible virtual friends: they never betray you, always available. Or do you prefer your real friendships with their flaws?', fr: 'Tu peux avoir des amis virtuels parfaitement compatibles: ils ne te trahissent jamais, toujours disponibles. Ou préfères-tu tes vraies amitiés avec leurs défauts ?', de: 'Du kannst perfekt kompatible virtuelle Freunde haben: Sie verraten dich nie, immer verfügbar. Oder bevorzugst du deine echten Freundschaften mit ihren Fehlern?', it: 'Puoi avere amici virtuali perfettamente compatibili: non ti tradiscono mai, sempre disponibili. O preferisci le tue amicizie reali con i loro difetti?', pt: 'Você pode ter amigos virtuais perfeitamente compatíveis: nunca te traem, sempre disponíveis. Ou você prefere suas amizades reais com seus defeitos?' }, options: [
      { text: { es: 'Me quedo con lo real. Una amistad sin riesgo de decepción no es amistad.', en: 'I stay with the real. A friendship without the risk of disappointment is not friendship.', fr: 'Je reste avec la réalité. Une amitié sans risque de déception n\'est pas une amitié.', de: 'Ich bleibe beim Echten. Eine Freundschaft ohne das Risiko der Enttäuschung ist keine Freundschaft.', it: 'Resto con il reale. Un\'amicizia senza rischio di delusione non è amicizia.', pt: 'Fico com o real. Uma amizade sem risco de decepção não é amizade.' }, dimension: 'A' },
      { text: { es: 'Acepto las virtuales. Si me hacen sentir acompañado y comprendido, cumplen la función.', en: 'I accept the virtual ones. If they make me feel accompanied and understood, they serve their purpose.', fr: 'J\'accepte les virtuelles. Si elles me font sentir accompagné et compris, elles remplissent la fonction.', de: 'Ich akzeptiere die virtuellen. Wenn sie mich begleitet und verstanden fühlen lassen, erfüllen sie ihren Zweck.', it: 'Accetto le virtuali. Se mi fanno sentire accompagnato e capito, assolvono la funzione.', pt: 'Aceito as virtuais. Se me fazem sentir acompanhado e compreendido, cumprem a função.' }, dimension: 'P' },
      { text: { es: 'Me quedo con lo real. Necesito saber que el otro elige estar conmigo.', en: 'I stay with the real. I need to know the other chooses to be with me.', fr: 'Je reste avec la réalité. J\'ai besoin de savoir que l\'autre choisit d\'être avec moi.', de: 'Ich bleibe beim Echten. Ich muss wissen, dass der andere sich dafür entscheidet, mit mir zu sein.', it: 'Resto con il reale. Ho bisogno di sapere che l\'altro sceglie di stare con me.', pt: 'Fico com o real. Preciso saber que o outro escolhe estar comigo.' }, dimension: 'V' },
      { text: { es: 'Me quedo con lo real. Los conflictos con amigos me han hecho crecer más que cualquier conversación fácil.', en: 'I stay with the real. Conflicts with friends have made me grow more than any easy conversation.', fr: 'Je reste avec la réalité. Les conflits avec des amis m\'ont fait grandir plus que toute conversation facile.', de: 'Ich bleibe beim Echten. Konflikte mit Freunden haben mich mehr wachsen lassen als jedes leichte Gespräch.', it: 'Resto con il reale. I conflitti con gli amici mi hanno fatto crescere più di qualsiasi conversazione facile.', pt: 'Fico com o real. Conflitos com amigos me fizeram crescer mais do que qualquer conversa fácil.' }, dimension: 'S' },
    ] },
    { id: 5, situation: { es: 'En la virtualidad puedes crear obras maestras al instante. En la realidad, luchas meses para algo mediocre. ¿Qué eliges?', en: 'In virtuality you can create masterpieces instantly. In reality, you struggle months for something mediocre. What do you choose?', fr: 'Dans la virtualité tu peux créer des chefs-d\'œuvre instantanément. Dans la réalité, tu luttes des mois pour quelque chose de médiocre. Que choisis-tu ?', de: 'In der Virtualität kannst du sofort Meisterwerke erschaffen. In der Realität kämpfst du monatelang für etwas Mittelmäßiges. Was wählst du?', it: 'Nella virtualità puoi creare capolavori all\'istante. Nella realtà, lotti per mesi per qualcosa di mediocre. Cosa scegli?', pt: 'Na virtualidade você pode criar obras-primas instantaneamente. Na realidade, você luta meses por algo medíocre. O que você escolhe?' }, options: [
      { text: { es: 'Lo real. Una obra que no costó esfuerzo no es mía.', en: 'The real. A work that cost no effort is not mine.', fr: 'La réalité. Une œuvre qui n\'a pas coûté d\'effort n\'est pas la mienne.', de: 'Das Echte. Ein Werk, das keine Mühe gekostet hat, ist nicht meins.', it: 'Il reale. Un\'opera che non è costata sforzo non è mia.', pt: 'O real. Uma obra que não custou esforço não é minha.' }, dimension: 'A' },
      { text: { es: 'Lo virtual. Si la alegría de crear es la misma, prefiero producir más.', en: 'The virtual. If the joy of creating is the same, I prefer to produce more.', fr: 'Le virtuel. Si la joie de créer est la même, je préfère en produire plus.', de: 'Das Virtuelle. Wenn die Freude am Erschaffen dieselbe ist, produziere ich lieber mehr.', it: 'Il virtuale. Se la gioia di creare è la stessa, preferisco produrne di più.', pt: 'O virtual. Se a alegria de criar é a mesma, prefiro produzir mais.' }, dimension: 'P' },
      { text: { es: 'Lo real. Quiero que mi arte conecte desde la imperfección humana compartida.', en: 'The real. I want my art to connect through shared human imperfection.', fr: 'La réalité. Je veux que mon art connecte à travers l\'imperfection humaine partagée.', de: 'Das Echte. Ich möchte, dass meine Kunst durch geteilte menschliche Unvollkommenheit verbindet.', it: 'Il reale. Voglio che la mia arte si connetta attraverso l\'imperfezione umana condivisa.', pt: 'O real. Quero que minha arte se conecte através da imperfeição humana compartilhada.' }, dimension: 'V' },
      { text: { es: 'Lo real. La lucha creativa me define. Cada borrador fallido me enseña algo sobre mí.', en: 'The real. The creative struggle defines me. Every failed draft teaches me something about myself.', fr: 'La réalité. La lutte créative me définit. Chaque brouillon raté m\'apprend quelque chose sur moi.', de: 'Das Echte. Der kreative Kampf definiert mich. Jeder gescheiterte Entwurf lehrt mich etwas über mich.', it: 'Il reale. La lotta creativa mi definisce. Ogni bozza fallita mi insegna qualcosa su me stesso.', pt: 'O real. A luta criativa me define. Cada rascunho fracassado me ensina algo sobre mim.' }, dimension: 'S' },
    ] },
    { id: 6, situation: { es: 'Existe un mundo virtual donde nadie sufre. El mundo real sigue siendo un lugar de dolor inevitable. ¿A cuál te vas?', en: 'There is a virtual world where no one suffers. The real world remains a place of inevitable pain. Which do you go to?', fr: 'Il existe un monde virtuel où personne ne souffre. Le monde réel reste un endroit de douleur inévitable. Lequel choisis-tu ?', de: 'Es gibt eine virtuelle Welt, in der niemand leidet. Die echte Welt bleibt ein Ort des unvermeidlichen Schmerzes. Wohin gehst du?', it: 'Esiste un mondo virtuale dove nessuno soffre. Il mondo reale rimane un luogo di dolore inevitabile. Dove vai?', pt: 'Existe um mundo virtual onde ninguém sofre. O mundo real continua sendo um lugar de dor inevitável. Para qual você vai?' }, options: [
      { text: { es: 'Me quedo en la realidad. Un mundo sin sufrimiento es hermoso pero no es verdadero.', en: 'I stay in reality. A world without suffering is beautiful but not true.', fr: 'Je reste dans la réalité. Un monde sans souffrance est beau mais pas vrai.', de: 'Ich bleibe in der Realität. Eine Welt ohne Leiden ist schön, aber nicht wahr.', it: 'Resto nella realtà. Un mondo senza sofferenza è bello ma non è vero.', pt: 'Fico na realidade. Um mundo sem sofrimento é bonito mas não é verdadeiro.' }, dimension: 'A' },
      { text: { es: 'Me voy al virtual. Si puedo evitar el sufrimiento de todos, sería inmoral no hacerlo.', en: 'I go to the virtual. If I can avoid everyone\'s suffering, it would be immoral not to.', fr: 'Je vais au virtuel. Si je peux éviter la souffrance de tous, il serait immoral de ne pas le faire.', de: 'Ich gehe ins Virtuelle. Wenn ich das Leiden aller vermeiden kann, wäre es unmoralisch, es nicht zu tun.', it: 'Vado al virtuale. Se posso evitare la sofferenza di tutti, sarebbe immorale non farlo.', pt: 'Vou para o virtual. Se posso evitar o sofrimento de todos, seria imoral não fazê-lo.' }, dimension: 'P' },
      { text: { es: 'Me quedo en la realidad. Prefiero consolar a alguien real que celebrar con fantasmas digitales.', en: 'I stay in reality. I prefer comforting a real person to celebrating with digital ghosts.', fr: 'Je reste dans la réalité. Je préfère consoler quelqu\'un de réel que célébrer avec des fantômes numériques.', de: 'Ich bleibe in der Realität. Ich tröste lieber jemanden Echten, als mit digitalen Gespenstern zu feiern.', it: 'Resto nella realtà. Preferisco consolare qualcuno di reale che celebrare con fantasmi digitali.', pt: 'Fico na realidade. Prefiro consolar alguém real a celebrar com fantasmas digitais.' }, dimension: 'V' },
      { text: { es: 'Me quedo en la realidad. El sufrimiento es el precio de una vida con significado.', en: 'I stay in reality. Suffering is the price of a meaningful life.', fr: 'Je reste dans la réalité. La souffrance est le prix d\'une vie qui a du sens.', de: 'Ich bleibe in der Realität. Leiden ist der Preis eines bedeutungsvollen Lebens.', it: 'Resto nella realtà. La sofferenza è il prezzo di una vita con significato.', pt: 'Fico na realidade. O sofrimento é o preço de uma vida com significado.' }, dimension: 'S' },
    ] },
    { id: 7, situation: { es: 'Puedes tener hijos virtuales: perfectamente sanos, felices, que te aman incondicionalmente. ¿O hijos reales con toda su incertidumbre?', en: 'You can have virtual children: perfectly healthy, happy, who love you unconditionally. Or real children with all their uncertainty?', fr: 'Tu peux avoir des enfants virtuels: parfaitement sains, heureux, qui t\'aiment inconditionnellement. Ou de vrais enfants avec toute leur incertitude ?', de: 'Du kannst virtuelle Kinder haben: perfekt gesund, glücklich, die dich bedingungslos lieben. Oder echte Kinder mit all ihrer Unsicherheit?', it: 'Puoi avere figli virtuali: perfettamente sani, felici, che ti amano incondizionatamente. O figli reali con tutta la loro incertezza?', pt: 'Você pode ter filhos virtuais: perfeitamente saudáveis, felizes, que te amam incondicionalmente. Ou filhos reais com toda a sua incerteza?' }, options: [
      { text: { es: 'Hijos reales. Un hijo que no puede desobedecerme no es un hijo, es un juguete.', en: 'Real children. A child who cannot disobey me is not a child, it\'s a toy.', fr: 'De vrais enfants. Un enfant qui ne peut pas me désobéir n\'est pas un enfant, c\'est un jouet.', de: 'Echte Kinder. Ein Kind, das mir nicht gehorchen kann, ist kein Kind, es ist ein Spielzeug.', it: 'Figli reali. Un figlio che non può disubbidirmi non è un figlio, è un giocattolo.', pt: 'Filhos reais. Um filho que não pode me desobedecer não é filho, é um brinquedo.' }, dimension: 'A' },
      { text: { es: 'Hijos virtuales. Si puedo garantizar su felicidad y la mía, ¿por qué arriesgarme?', en: 'Virtual children. If I can guarantee their happiness and mine, why take the risk?', fr: 'Des enfants virtuels. Si je peux garantir leur bonheur et le mien, pourquoi prendre le risque ?', de: 'Virtuelle Kinder. Wenn ich ihr Glück und meins garantieren kann, warum das Risiko eingehen?', it: 'Figli virtuali. Se posso garantire la loro felicità e la mia, perché rischiare?', pt: 'Filhos virtuais. Se posso garantir a felicidade deles e a minha, por que me arriscar?' }, dimension: 'P' },
      { text: { es: 'Hijos reales. Quiero verlos elegir su propio camino, aunque sea diferente al que imaginé.', en: 'Real children. I want to see them choose their own path, even if it\'s different from what I imagined.', fr: 'De vrais enfants. Je veux les voir choisir leur propre chemin, même si c\'est différent de ce que j\'imaginais.', de: 'Echte Kinder. Ich möchte sie ihren eigenen Weg wählen sehen, auch wenn er anders ist als ich es mir vorgestellt habe.', it: 'Figli reali. Voglio vederli scegliere il loro cammino, anche se diverso da quello che ho immaginato.', pt: 'Filhos reais. Quero vê-los escolher seu próprio caminho, mesmo que diferente do que imaginei.' }, dimension: 'V' },
      { text: { es: 'Hijos reales. Las noches sin dormir, las peleas, los miedos — todo eso es ser padre de verdad.', en: 'Real children. The sleepless nights, the fights, the fears — all of that is what being a parent really means.', fr: 'De vrais enfants. Les nuits sans sommeil, les disputes, les peurs — tout ça c\'est être vraiment parent.', de: 'Echte Kinder. Die schlaflosen Nächte, die Kämpfe, die Ängste — all das ist wirklich Elternsein.', it: 'Figli reali. Le notti insonni, le liti, le paure — tutto ciò è essere genitori davvero.', pt: 'Filhos reais. As noites sem dormir, as brigas, os medos — tudo isso é ser pai de verdade.' }, dimension: 'S' },
    ] },
    { id: 8, situation: { es: 'En la virtualidad tienes todo el conocimiento al instante. En la realidad, cada descubrimiento te emociona. ¿Qué prefieres?', en: 'In virtuality you have all knowledge instantly. In reality, each discovery excites you. What do you prefer?', fr: 'Dans la virtualité tu as toute la connaissance instantanément. Dans la réalité, chaque découverte t\'émeut. Que préfères-tu ?', de: 'In der Virtualität hast du sofort alles Wissen. In der Realität begeistert dich jede Entdeckung. Was bevorzugst du?', it: 'Nella virtualità hai tutta la conoscenza all\'istante. Nella realtà, ogni scoperta ti emoziona. Cosa preferisci?', pt: 'Na virtualidade você tem todo o conhecimento instantaneamente. Na realidade, cada descoberta te emociona. O que você prefere?' }, options: [
      { text: { es: 'La realidad. El conocimiento sin el proceso de descubrirlo es información vacía.', en: 'Reality. Knowledge without the process of discovering it is empty information.', fr: 'La réalité. La connaissance sans le processus de la découvrir est une information vide.', de: 'Die Realität. Wissen ohne den Prozess es zu entdecken ist leere Information.', it: 'La realtà. La conoscenza senza il processo di scoprirla è informazione vuota.', pt: 'A realidade. O conhecimento sem o processo de descobri-lo é informação vazia.' }, dimension: 'A' },
      { text: { es: 'Lo virtual. Más conocimiento significa mejores decisiones y más capacidad de hacer el bien.', en: 'The virtual. More knowledge means better decisions and more capacity to do good.', fr: 'Le virtuel. Plus de connaissances signifie de meilleures décisions et plus de capacité à faire le bien.', de: 'Das Virtuelle. Mehr Wissen bedeutet bessere Entscheidungen und mehr Kapazität, Gutes zu tun.', it: 'Il virtuale. Più conoscenza significa migliori decisioni e più capacità di fare del bene.', pt: 'O virtual. Mais conhecimento significa melhores decisões e mais capacidade de fazer o bem.' }, dimension: 'P' },
      { text: { es: 'La realidad. Prefiero aprender algo de alguien, en conversación, que recibir datos de un servidor.', en: 'Reality. I prefer learning something from someone, in conversation, than receiving data from a server.', fr: 'La réalité. Je préfère apprendre quelque chose de quelqu\'un, en conversation, que recevoir des données d\'un serveur.', de: 'Die Realität. Ich lerne lieber etwas von jemandem, im Gespräch, als Daten von einem Server zu empfangen.', it: 'La realtà. Preferisco imparare qualcosa da qualcuno, in conversazione, che ricevere dati da un server.', pt: 'A realidade. Prefiro aprender algo de alguém, em conversa, do que receber dados de um servidor.' }, dimension: 'V' },
      { text: { es: 'La realidad. La emoción de descubrir algo después de años de búsqueda no tiene precio.', en: 'Reality. The excitement of discovering something after years of searching is priceless.', fr: 'La réalité. L\'émotion de découvrir quelque chose après des années de recherche n\'a pas de prix.', de: 'Die Realität. Die Aufregung, nach Jahren der Suche etwas zu entdecken, ist unbezahlbar.', it: 'La realtà. L\'emozione di scoprire qualcosa dopo anni di ricerca non ha prezzo.', pt: 'A realidade. A emoção de descobrir algo após anos de busca não tem preço.' }, dimension: 'S' },
    ] },
    { id: 9, situation: { es: 'Puedes vivir en una sociedad virtual utópica: justicia perfecta, igualdad total. ¿O quedarte en la sociedad real con la posibilidad de cambiarla?', en: 'You can live in a virtual utopian society: perfect justice, total equality. Or stay in real society with the possibility of changing it?', fr: 'Tu peux vivre dans une société virtuelle utopique: justice parfaite, égalité totale. Ou rester dans la société réelle avec la possibilité de la changer ?', de: 'Du kannst in einer virtuellen utopischen Gesellschaft leben: perfekte Gerechtigkeit, totale Gleichheit. Oder in der echten Gesellschaft bleiben mit der Möglichkeit, sie zu verändern?', it: 'Puoi vivere in una società virtuale utopica: giustizia perfetta, uguaglianza totale. O restare nella società reale con la possibilità di cambiarla?', pt: 'Você pode viver em uma sociedade virtual utópica: justiça perfeita, igualdade total. Ou ficar na sociedade real com a possibilidade de mudá-la?' }, options: [
      { text: { es: 'La realidad. Una justicia que nadie construyó no es justicia, es decorado.', en: 'Reality. Justice that nobody built is not justice, it\'s decoration.', fr: 'La réalité. Une justice que personne n\'a construite n\'est pas de la justice, c\'est de la décoration.', de: 'Die Realität. Eine Gerechtigkeit, die niemand aufgebaut hat, ist keine Gerechtigkeit, sie ist Dekoration.', it: 'La realtà. Una giustizia che nessuno ha costruito non è giustizia, è decorazione.', pt: 'A realidade. Uma justiça que ninguém construiu não é justiça, é decoração.' }, dimension: 'A' },
      { text: { es: 'Lo virtual. Si el resultado es un mundo justo, el origen importa menos que el efecto.', en: 'The virtual. If the result is a just world, the origin matters less than the effect.', fr: 'Le virtuel. Si le résultat est un monde juste, l\'origine importe moins que l\'effet.', de: 'Das Virtuelle. Wenn das Ergebnis eine gerechte Welt ist, ist der Ursprung weniger wichtig als die Wirkung.', it: 'Il virtuale. Se il risultato è un mondo giusto, l\'origine importa meno dell\'effetto.', pt: 'O virtual. Se o resultado é um mundo justo, a origem importa menos que o efeito.' }, dimension: 'P' },
      { text: { es: 'La realidad. Prefiero luchar junto a otros por un mundo mejor que habitarlo perfecto y solo.', en: 'Reality. I prefer to fight alongside others for a better world than to inhabit a perfect one alone.', fr: 'La réalité. Je préfère lutter aux côtés des autres pour un monde meilleur que d\'habiter un monde parfait et seul.', de: 'Die Realität. Ich kämpfe lieber mit anderen für eine bessere Welt, als sie perfekt und allein zu bewohnen.', it: 'La realtà. Preferisco lottare insieme agli altri per un mondo migliore che abitarlo perfetto e solo.', pt: 'A realidade. Prefiro lutar junto com os outros por um mundo melhor do que habitá-lo perfeito e sozinho.' }, dimension: 'V' },
      { text: { es: 'La realidad. La lucha contra la injusticia es lo que da sentido a la vida en sociedad.', en: 'Reality. The fight against injustice is what gives meaning to life in society.', fr: 'La réalité. La lutte contre l\'injustice est ce qui donne du sens à la vie en société.', de: 'Die Realität. Der Kampf gegen Ungerechtigkeit ist das, was dem Leben in der Gesellschaft Bedeutung gibt.', it: 'La realtà. La lotta contro l\'ingiustizia è ciò che dà senso alla vita in società.', pt: 'A realidade. A luta contra a injustiça é o que dá sentido à vida em sociedade.' }, dimension: 'S' },
    ] },
    { id: 10, situation: { es: 'Última oferta: inmersión total y permanente en una virtualidad perfecta. Todo lo que siempre quisiste, para siempre. ¿Aceptas?', en: 'Final offer: total and permanent immersion in a perfect virtuality. Everything you ever wanted, forever. Do you accept?', fr: 'Dernière offre: immersion totale et permanente dans une virtualité parfaite. Tout ce que tu as toujours voulu, pour toujours. Acceptes-tu ?', de: 'Letztes Angebot: vollständige und dauerhafte Eintauchen in eine perfekte Virtualität. Alles, was du je wolltest, für immer. Nimmst du an?', it: 'Ultima offerta: immersione totale e permanente in una virtualità perfetta. Tutto quello che hai sempre voluto, per sempre. Accetti?', pt: 'Última oferta: imersão total e permanente em uma virtualidade perfeita. Tudo o que sempre quis, para sempre. Você aceita?' }, options: [
      { text: { es: 'No acepto. Prefiero una vida real imperfecta a una eternidad de ilusiones perfectas.', en: 'I don\'t accept. I prefer a real imperfect life to an eternity of perfect illusions.', fr: 'Je n\'accepte pas. Je préfère une vie réelle imparfaite à une éternité d\'illusions parfaites.', de: 'Ich akzeptiere nicht. Ich bevorzuge ein echtes unvollkommenes Leben vor einer Ewigkeit perfekter Illusionen.', it: 'Non accetto. Preferisco una vita reale imperfetta a un\'eternità di illusioni perfette.', pt: 'Não aceito. Prefiro uma vida real imperfeita a uma eternidade de ilusões perfeitas.' }, dimension: 'A' },
      { text: { es: 'Acepto. Si la experiencia subjetiva es todo lo que tenemos, elegiría la mejor versión posible.', en: 'I accept. If subjective experience is all we have, I\'d choose the best possible version.', fr: 'J\'accepte. Si l\'expérience subjective est tout ce que nous avons, je choisirais la meilleure version possible.', de: 'Ich akzeptiere. Wenn subjektive Erfahrung alles ist, was wir haben, würde ich die bestmögliche Version wählen.', it: 'Accetto. Se l\'esperienza soggettiva è tutto ciò che abbiamo, sceglierei la versione migliore possibile.', pt: 'Aceito. Se a experiência subjetiva é tudo o que temos, escolheria a melhor versão possível.' }, dimension: 'P' },
      { text: { es: 'No acepto. No puedo abandonar a las personas reales que me necesitan.', en: 'I don\'t accept. I can\'t abandon the real people who need me.', fr: 'Je n\'accepte pas. Je ne peux pas abandonner les vraies personnes qui ont besoin de moi.', de: 'Ich akzeptiere nicht. Ich kann die echten Menschen, die mich brauchen, nicht verlassen.', it: 'Non accetto. Non posso abbandonare le persone reali che hanno bisogno di me.', pt: 'Não aceito. Não posso abandonar as pessoas reais que precisam de mim.' }, dimension: 'V' },
      { text: { es: 'No acepto. Una vida sin obstáculos no es vida. Necesito la posibilidad de fracasar.', en: 'I don\'t accept. A life without obstacles is not life. I need the possibility of failing.', fr: 'Je n\'accepte pas. Une vie sans obstacles n\'est pas une vie. J\'ai besoin de la possibilité d\'échouer.', de: 'Ich akzeptiere nicht. Ein Leben ohne Hindernisse ist kein Leben. Ich brauche die Möglichkeit zu scheitern.', it: 'Non accetto. Una vita senza ostacoli non è vita. Ho bisogno della possibilità di fallire.', pt: 'Não aceito. Uma vida sem obstáculos não é vida. Preciso da possibilidade de fracassar.' }, dimension: 'S' },
    ] },
  ],
  characters: [
    { name: { es: 'Aristóteles', en: 'Aristotle', fr: 'Aristote', de: 'Aristoteles', it: 'Aristotele', pt: 'Aristóteles' }, dimensions: ['A'], photo: '/characters/aristoteles.jpg', description: { es: 'Defensor de la vida auténtica y la virtud practicada en el mundo real.', en: 'Advocate for authentic life and virtue practiced in the real world.', fr: 'Défenseur de la vie authentique et de la vertu pratiquée dans le monde réel.', de: 'Befürworter des authentischen Lebens und der im echten Leben praktizierten Tugend.', it: 'Sostenitore della vita autentica e della virtù praticata nel mondo reale.', pt: 'Defensor da vida autêntica e da virtude praticada no mundo real.' }, philosophy: { es: 'Para ti, la buena vida requiere autenticidad. No basta con sentir placer — necesitas saber que tus experiencias son genuinas. La eudaimonía solo se alcanza viviendo según la virtud en el mundo real.', en: 'For you, the good life requires authenticity. It\'s not enough to feel pleasure — you need to know your experiences are genuine. Eudaimonia is only achieved by living virtuously in the real world.', fr: 'Pour toi, la bonne vie requiert l\'authenticité. Il ne suffit pas de ressentir du plaisir — tu dois savoir que tes expériences sont genuines. L\'eudémonie n\'est atteinte qu\'en vivant selon la vertu dans le monde réel.', de: 'Für dich erfordert das gute Leben Authentizität. Es reicht nicht, Vergnügen zu fühlen — du musst wissen, dass deine Erfahrungen echt sind. Eudaimonia wird nur durch tugendhaftes Leben in der echten Welt erreicht.', it: 'Per te, la buona vita richiede autenticità. Non basta sentire piacere — devi sapere che le tue esperienze sono genuine. L\'eudaimonia si raggiunge solo vivendo virtuosamente nel mondo reale.', pt: 'Para você, a boa vida requer autenticidade. Não basta sentir prazer — você precisa saber que suas experiências são genuínas. A eudaimonia só é alcançada vivendo virtuosamente no mundo real.' } },
    { name: { es: 'Epicuro', en: 'Epicurus', fr: 'Épicure', de: 'Epikur', it: 'Epicuro', pt: 'Epicuro' }, dimensions: ['P'], photo: '/characters/epicuro.jpg', description: { es: 'Filósofo del placer que evalúa la experiencia por su calidad, no su origen.', en: 'Philosopher of pleasure who evaluates experience by its quality, not its origin.', fr: 'Philosophe du plaisir qui évalue l\'expérience par sa qualité, pas son origine.', de: 'Philosoph des Vergnügens, der Erfahrungen nach ihrer Qualität, nicht ihrem Ursprung bewertet.', it: 'Filosofo del piacere che valuta l\'esperienza per la sua qualità, non la sua origine.', pt: 'Filósofo do prazer que avalia a experiência pela sua qualidade, não pela sua origem.' }, philosophy: { es: 'Para ti, lo que importa es la calidad de la experiencia. Si una simulación produce bienestar genuino, su origen artificial es irrelevante. El sumo bien es el placer tranquilo, y no discriminas su fuente.', en: 'For you, what matters is the quality of the experience. If a simulation produces genuine well-being, its artificial origin is irrelevant. The highest good is tranquil pleasure, and you don\'t discriminate by source.', fr: 'Pour toi, ce qui compte c\'est la qualité de l\'expérience. Si une simulation produit un bien-être genuino, son origine artificielle est sans importance. Le souverain bien est le plaisir tranquille.', de: 'Für dich zählt die Qualität der Erfahrung. Wenn eine Simulation echtes Wohlbefinden erzeugt, ist ihr künstlicher Ursprung irrelevant. Das höchste Gut ist ruhiges Vergnügen, und du diskriminierst nicht nach Quelle.', it: 'Per te, ciò che conta è la qualità dell\'esperienza. Se una simulazione produce benessere genuino, la sua origine artificiale è irrilevante. Il sommo bene è il piacere tranquillo, e non discrimini la fonte.', pt: 'Para você, o que importa é a qualidade da experiência. Se uma simulação produz bem-estar genuíno, sua origem artificial é irrelevante. O sumo bem é o prazer tranquilo, e você não discrimina a fonte.' } },
    { name: { es: 'Martin Buber', en: 'Martin Buber', fr: 'Martin Buber', de: 'Martin Buber', it: 'Martin Buber', pt: 'Martin Buber' }, dimensions: ['V'], photo: '/characters/buber.jpg', description: { es: 'Filósofo del diálogo que prioriza las conexiones humanas genuinas.', en: 'Philosopher of dialogue who prioritizes genuine human connections.', fr: 'Philosophe du dialogue qui privilégie les vraies connexions humaines.', de: 'Dialogphilosoph, der echte menschliche Verbindungen priorisiert.', it: 'Filosofo del dialogo che privilegia le connessioni umane genuine.', pt: 'Filósofo do diálogo que prioriza as conexões humanas genuínas.' }, philosophy: { es: 'Para ti, el significado emerge del encuentro genuino con el otro. Ninguna simulación puede replicar la relación Yo-Tú. Sin reciprocidad real, toda experiencia es un monólogo vacío.', en: 'For you, meaning emerges from genuine encounter with the other. No simulation can replicate the I-Thou relationship. Without real reciprocity, every experience is an empty monologue.', fr: 'Pour toi, le sens émerge de la rencontre genuine avec l\'autre. Aucune simulation ne peut reproduire la relation Je-Tu. Sans réciprocité réelle, toute expérience est un monologue vide.', de: 'Für dich entsteht Bedeutung aus der echten Begegnung mit dem anderen. Keine Simulation kann die Ich-Du-Beziehung replizieren. Ohne echte Gegenseitigkeit ist jede Erfahrung ein leerer Monolog.', it: 'Per te, il significato emerge dall\'incontro genuino con l\'altro. Nessuna simulazione può replicare la relazione Io-Tu. Senza reciprocità reale, ogni esperienza è un monologo vuoto.', pt: 'Para você, o significado emerge do encontro genuíno com o outro. Nenhuma simulação pode replicar a relação Eu-Tu. Sem reciprocidade real, toda experiência é um monólogo vazio.' } },
    { name: { es: 'Viktor Frankl', en: 'Viktor Frankl', fr: 'Viktor Frankl', de: 'Viktor Frankl', it: 'Viktor Frankl', pt: 'Viktor Frankl' }, dimensions: ['S'], photo: '/characters/frankl.jpg', description: { es: 'Psiquiatra que encontró sentido en el sufrimiento y la adversidad.', en: 'Psychiatrist who found meaning in suffering and adversity.', fr: 'Psychiatre qui a trouvé du sens dans la souffrance et l\'adversité.', de: 'Psychiater, der Bedeutung in Leiden und Widrigkeiten fand.', it: 'Psichiatra che ha trovato senso nella sofferenza e nell\'avversità.', pt: 'Psiquiatra que encontrou sentido no sofrimento e na adversidade.' }, philosophy: { es: 'Para ti, el sufrimiento no es un error a corregir sino un camino hacia el sentido. Evitar toda adversidad vaciaría la vida de propósito. Quien tiene un "por qué" puede soportar cualquier "cómo".', en: 'For you, suffering is not an error to correct but a path to meaning. Avoiding all adversity would empty life of purpose. He who has a "why" can bear almost any "how".', fr: 'Pour toi, la souffrance n\'est pas une erreur à corriger mais un chemin vers le sens. Éviter toute adversité viderait la vie de son but. Celui qui a un "pourquoi" peut supporter presque n\'importe quel "comment".', de: 'Für dich ist Leiden kein Fehler, der korrigiert werden muss, sondern ein Weg zum Sinn. Das Vermeiden aller Widrigkeiten würde das Leben seines Zwecks berauben. Wer ein "Warum" hat, kann fast jedes "Wie" ertragen.', it: 'Per te, la sofferenza non è un errore da correggere ma un cammino verso il senso. Evitare ogni avversità svuoterebbe la vita di scopo. Chi ha un "perché" può sopportare quasi qualsiasi "come".', pt: 'Para você, o sofrimento não é um erro a corrigir, mas um caminho para o sentido. Evitar toda adversidade esvaziaria a vida de propósito. Quem tem um "por quê" pode suportar quase qualquer "como".' } },
    { name: { es: 'Albert Camus', en: 'Albert Camus', fr: 'Albert Camus', de: 'Albert Camus', it: 'Albert Camus', pt: 'Albert Camus' }, dimensions: ['A', 'S'], photo: '/characters/camus.jpg', description: { es: 'Rebelde que abraza lo absurdo de la realidad con autenticidad radical.', en: 'Rebel who embraces the absurdity of reality with radical authenticity.', fr: 'Rebelle qui embrasse l\'absurdité de la réalité avec une authenticité radicale.', de: 'Rebell, der die Absurdität der Realität mit radikaler Authentizität umarmt.', it: 'Ribelle che abbraccia l\'assurdità della realtà con autenticità radicale.', pt: 'Rebelde que abraça o absurdo da realidade com autenticidade radical.' }, philosophy: { es: 'Para ti, hay que imaginar a Sísifo feliz. La vida es absurda y difícil, pero enfrentarla con honestidad es el único acto de rebeldía que vale. Rechazas los paraísos artificiales porque la lucha misma basta.', en: 'For you, one must imagine Sisyphus happy. Life is absurd and difficult, but facing it honestly is the only act of rebellion worth doing. You reject artificial paradises because the struggle itself is enough.', fr: 'Pour toi, il faut imaginer Sisyphe heureux. La vie est absurde et difficile, mais y faire face honnêtement est le seul acte de rébellion qui vaille. Tu rejettes les paradis artificiels car la lutte elle-même suffit.', de: 'Für dich muss man sich Sisyphus als glücklich vorstellen. Das Leben ist absurd und schwierig, aber es ehrlich zu begegnen ist der einzige Akt der Revolte, der sich lohnt. Du lehnst künstliche Paradiese ab, weil der Kampf selbst genug ist.', it: 'Per te, bisogna immaginare Sisifo felice. La vita è assurda e difficile, ma affrontarla con onestà è l\'unico atto di ribellione che vale. Rifiuti i paradisi artificiali perché la lotta stessa basta.', pt: 'Para você, é preciso imaginar Sísifo feliz. A vida é absurda e difícil, mas enfrentá-la honestamente é o único ato de rebeldia que vale. Você rejeita os paraísos artificiais porque a própria luta basta.' } },
    { name: { es: 'John Stuart Mill', en: 'John Stuart Mill', fr: 'John Stuart Mill', de: 'John Stuart Mill', it: 'John Stuart Mill', pt: 'John Stuart Mill' }, dimensions: ['P', 'V'], photo: '/characters/mill.jpg', description: { es: 'Utilitarista que calcula el bienestar considerando los vínculos sociales.', en: 'Utilitarian who calculates well-being taking social bonds into account.', fr: 'Utilitariste qui calcule le bien-être en tenant compte des liens sociaux.', de: 'Utilitarist, der das Wohlbefinden unter Berücksichtigung sozialer Bindungen berechnet.', it: 'Utilitarista che calcola il benessere tenendo conto dei legami sociali.', pt: 'Utilitarista que calcula o bem-estar considerando os laços sociais.' }, philosophy: { es: 'Para ti, el bienestar se mide en sus efectos sobre personas reales. Aceptas la tecnología cuando mejora vidas, pero nunca a costa de los vínculos genuinos. Distingues entre placeres superiores e inferiores.', en: 'For you, well-being is measured by its effects on real people. You accept technology when it improves lives, but never at the cost of genuine bonds. You distinguish between higher and lower pleasures.', fr: 'Pour toi, le bien-être se mesure à ses effets sur de vraies personnes. Tu acceptes la technologie quand elle améliore des vies, mais jamais au détriment des vrais liens. Tu distingues entre les plaisirs supérieurs et inférieurs.', de: 'Für dich wird Wohlbefinden an seinen Auswirkungen auf echte Menschen gemessen. Du akzeptierst Technologie, wenn sie Leben verbessert, aber nie auf Kosten echter Bindungen. Du unterscheidest zwischen höheren und niedrigeren Vergnügen.', it: 'Per te, il benessere si misura nei suoi effetti sulle persone reali. Accetti la tecnologia quando migliora le vite, ma mai a scapito dei legami genuini. Distingui tra piaceri superiori e inferiori.', pt: 'Para você, o bem-estar é medido em seus efeitos sobre pessoas reais. Você aceita a tecnologia quando melhora vidas, mas nunca à custa de vínculos genuínos. Você distingue entre prazeres superiores e inferiores.' } },
    { name: { es: 'Simone de Beauvoir', en: 'Simone de Beauvoir', fr: 'Simone de Beauvoir', de: 'Simone de Beauvoir', it: 'Simone de Beauvoir', pt: 'Simone de Beauvoir' }, dimensions: ['V', 'S'], photo: '/characters/beauvoir.jpg', description: { es: 'Existencialista que une la lucha personal con la conexión auténtica.', en: 'Existentialist who unites personal struggle with authentic connection.', fr: 'Existentialiste qui unit la lutte personnelle avec la connexion authentique.', de: 'Existentialistin, die persönlichen Kampf mit authentischer Verbindung vereint.', it: 'Esistenzialista che unisce la lotta personale con la connessione autentica.', pt: 'Existencialista que une a luta pessoal com a conexão autêntica.' }, philosophy: { es: 'Para ti, existir es comprometerse con otros en la lucha compartida. La libertad no se disfruta sola ni sin esfuerzo. La existencia auténtica requiere tanto vínculos genuinos como voluntad de enfrentar la adversidad.', en: 'For you, to exist is to commit to others in shared struggle. Freedom is not enjoyed alone or without effort. Authentic existence requires both genuine bonds and the will to face adversity.', fr: 'Pour toi, exister c\'est s\'engager avec les autres dans la lutte commune. La liberté ne se savoure pas seule ni sans effort. L\'existence authentique requiert à la fois des liens genuins et la volonté d\'affronter l\'adversité.', de: 'Für dich bedeutet Existieren, sich mit anderen im gemeinsamen Kampf zu engagieren. Freiheit wird nicht allein oder ohne Anstrengung genossen. Authentische Existenz erfordert sowohl echte Bindungen als auch den Willen, Widrigkeiten zu begegnen.', it: 'Per te, esistere è impegnarsi con gli altri nella lotta condivisa. La libertà non si gode da soli né senza sforzo. L\'esistenza autentica richiede sia legami genuini che volontà di affrontare l\'avversità.', pt: 'Para você, existir é se comprometer com os outros na luta compartilhada. A liberdade não se desfruta sozinha nem sem esforço. A existência autêntica requer tanto vínculos genuínos quanto vontade de enfrentar a adversidade.' } },
    { name: { es: 'Robert Nozick', en: 'Robert Nozick', fr: 'Robert Nozick', de: 'Robert Nozick', it: 'Robert Nozick', pt: 'Robert Nozick' }, dimensions: ['A', 'P'], photo: '/characters/nozick.jpg', description: { es: 'Creador de la Máquina de Experiencias que eligió la realidad con pragmatismo.', en: 'Creator of the Experience Machine who chose reality with pragmatism.', fr: 'Créateur de la Machine à Expériences qui a choisi la réalité avec pragmatisme.', de: 'Schöpfer der Erfahrungsmaschine, der die Realität pragmatisch wählte.', it: 'Creatore della Macchina delle Esperienze che ha scelto la realtà con pragmatismo.', pt: 'Criador da Máquina de Experiências que escolheu a realidade com pragmatismo.' }, philosophy: { es: 'Para ti, la realidad importa, pero no eres dogmático. Valoras lo auténtico y reconoces el peso del bienestar. Inventaste el dilema y concluiste que sí, preferimos la realidad — pero entiendes por qué alguien elegiría la máquina.', en: 'For you, reality matters, but you\'re not dogmatic. You value authenticity and recognize the weight of well-being. You invented the dilemma and concluded that yes, we prefer reality — but you understand why someone would choose the machine.', fr: 'Pour toi, la réalité compte, mais tu n\'es pas dogmatique. Tu valorises l\'authenticité et reconnais le poids du bien-être. Tu as inventé le dilemme et conclu que oui, nous préférons la réalité — mais tu comprends pourquoi quelqu\'un choisirait la machine.', de: 'Für dich ist die Realität wichtig, aber du bist nicht dogmatisch. Du schätzt Authentizität und erkennst das Gewicht des Wohlbefindens. Du hast das Dilemma erfunden und gefolgert, dass wir ja, die Realität bevorzugen — aber du verstehst, warum jemand die Maschine wählen würde.', it: 'Per te, la realtà conta, ma non sei dogmatico. Valorizzi l\'autenticità e riconosci il peso del benessere. Hai inventato il dilemma e concluso che sì, preferiamo la realtà — ma capisci perché qualcuno sceglierebbe la macchina.', pt: 'Para você, a realidade importa, mas você não é dogmático. Você valoriza a autenticidade e reconhece o peso do bem-estar. Você inventou o dilema e concluiu que sim, preferimos a realidade — mas entende por que alguém escolheria a máquina.' } },
  ],
};

export async function seedVirtual(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'virtual' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
      categoryId: catMap['pop-culture'], sortOrder: 1,
    },
    create: {
      slug: 'virtual',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['pop-culture'],
      sortOrder: 1,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
