import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan dramático/a eres?', en: 'How dramatic are you?', fr: 'À quel point es-tu dramatique ?', de: 'Wie dramatisch bist du?', it: 'Quanto sei drammatico/a?', pt: 'O quanto você é dramático/a?' },
  description: { es: '¿Eres el protagonista de cada historia o el testigo tranquilo? Descubre tu nivel de drama.', en: 'Are you the protagonist of every story or the calm witness? Discover your drama level.', fr: 'Es-tu le protagoniste de chaque histoire ou le témoin calme ? Découvre ton niveau de drame.', de: 'Bist du der Protagonist jeder Geschichte oder der ruhige Zeuge? Entdecke dein Dramatik-Level.', it: 'Sei il protagonista di ogni storia o il testimone tranquillo? Scopri il tuo livello di dramma.', pt: 'Você é o protagonista de cada história ou a testemunha tranquila? Descubra seu nível de drama.' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { D: 'Drama', I: 'Intensidad', C: 'Calma', R: 'Resiliencia' },
    en: { D: 'Drama', I: 'Intensity', C: 'Calm', R: 'Resilience' },
    fr: { D: 'Drame', I: 'Intensité', C: 'Calme', R: 'Résilience' },
    de: { D: 'Drama', I: 'Intensität', C: 'Ruhe', R: 'Resilienz' },
    it: { D: 'Dramma', I: 'Intensità', C: 'Calma', R: 'Resilienza' },
    pt: { D: 'Drama', I: 'Intensidade', C: 'Calma', R: 'Resiliência' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu teléfono muere al 2% en un momento inconveniente.', en: 'Your phone dies at 2% at an inconvenient moment.', fr: 'Ton téléphone meurt à 2% à un moment inconvenant.', de: 'Dein Handy stirbt bei 2% in einem ungünstigen Moment.', it: 'Il tuo telefono si scarica al 2% in un momento scomodo.', pt: 'Seu celular morre em 2% em um momento inconveniente.' }, options: [
      { text: { es: 'Es literalmente lo peor. Mi día está arruinado.', en: 'It\'s literally the worst. My day is ruined.', fr: 'C\'est littéralement le pire. Ma journée est fichue.', de: 'Es ist buchstäblich das Schlimmste. Mein Tag ist ruiniert.', it: 'È letteralmente il peggio. La mia giornata è rovinata.', pt: 'É literalmente o pior. Meu dia está arruinado.' }, dimension: 'D' },
      { text: { es: 'Me genera mucha ansiedad. El teléfono es mi conexión con el mundo.', en: 'It gives me a lot of anxiety. My phone is my connection to the world.', fr: 'Ça me génère beaucoup d\'anxiété. Le téléphone est ma connexion avec le monde.', de: 'Es erzeugt viel Angst bei mir. Das Telefon ist meine Verbindung zur Welt.', it: 'Mi genera molta ansia. Il telefono è la mia connessione con il mondo.', pt: 'Me gera muita ansiedade. O telefone é minha conexão com o mundo.' }, dimension: 'I' },
      { text: { es: 'Un inconveniente. Me las arreglaré.', en: 'An inconvenience. I\'ll manage.', fr: 'Un inconvénient. Je m\'en sortirai.', de: 'Ein Ärgernis. Ich werde damit klarkommen.', it: 'Un inconveniente. Me la caverò.', pt: 'Um inconveniente. Vou me virar.' }, dimension: 'C' },
      { text: { es: 'Bien. Un momento de desconexión forzada puede ser útil.', en: 'Fine. A forced disconnection moment can be useful.', fr: 'Bien. Un moment de déconnexion forcée peut être utile.', de: 'Gut. Ein erzwungener Moment der Abkopplung kann nützlich sein.', it: 'Bene. Un momento di disconnessione forzata può essere utile.', pt: 'Tudo bem. Um momento de desconexão forçada pode ser útil.' }, dimension: 'R' },
    ] },
    { id: 2, situation: { es: 'Un plan que esperabas con entusiasmo se cancela el día antes.', en: 'A plan you were looking forward to gets cancelled the day before.', fr: 'Un plan que tu attendais avec enthousiasme est annulé la veille.', de: 'Ein Plan, auf den du dich gefreut hast, wird am Tag davor abgesagt.', it: 'Un piano che aspettavi con entusiasmo viene cancellato il giorno prima.', pt: 'Um plano que você aguardava animado é cancelado na véspera.' }, options: [
      { text: { es: 'Es devastador. Llevaba semanas esperando esto.', en: 'It\'s devastating. I\'ve been looking forward to this for weeks.', fr: 'C\'est dévastateur. J\'attendais ça depuis des semaines.', de: 'Es ist verheerend. Ich habe mich wochenlang darauf gefreut.', it: 'È devastante. Lo aspettavo da settimane.', pt: 'É devastador. Aguardava isso há semanas.' }, dimension: 'D' },
      { text: { es: 'Me afecta bastante. Los cambios de último momento me cuestan mucho.', en: 'It affects me quite a bit. Last-minute changes cost me a lot.', fr: 'Ça m\'affecte beaucoup. Les changements de dernière minute me coûtent beaucoup.', de: 'Es betrifft mich ziemlich. Kurzfristige Änderungen kosten mich viel.', it: 'Mi colpisce abbastanza. I cambiamenti dell\'ultimo momento mi costano molto.', pt: 'Me afeta bastante. Mudanças de última hora me custam muito.' }, dimension: 'I' },
      { text: { es: 'Decepcionante, pero organizo algo diferente para mañana.', en: 'Disappointing, but I organize something different for tomorrow.', fr: 'Décevant, mais j\'organise quelque chose de différent pour demain.', de: 'Enttäuschend, aber ich organisiere für morgen etwas anderes.', it: 'Deludente, ma organizzo qualcosa di diverso per domani.', pt: 'Decepcionante, mas organizo algo diferente para amanhã.' }, dimension: 'C' },
      { text: { es: 'Una oportunidad para hacer algo que tenía pendiente.', en: 'An opportunity to do something I had pending.', fr: 'Une opportunité de faire quelque chose que j\'avais en attente.', de: 'Eine Gelegenheit, etwas zu tun, das ich noch offen hatte.', it: 'Un\'opportunità per fare qualcosa che avevo in sospeso.', pt: 'Uma oportunidade para fazer algo que estava pendente.' }, dimension: 'R' },
    ] },
    { id: 3, situation: { es: 'Alguien en una red social hace un comentario ligeramente crítico sobre algo que publicaste.', en: 'Someone on social media makes a slightly critical comment about something you posted.', fr: 'Quelqu\'un sur un réseau social fait un commentaire légèrement critique sur quelque chose que tu as publié.', de: 'Jemand in sozialen Medien macht einen leicht kritischen Kommentar über etwas, das du gepostet hast.', it: 'Qualcuno sui social fa un commento leggermente critico su qualcosa che hai pubblicato.', pt: 'Alguém nas redes sociais faz um comentário levemente crítico sobre algo que você publicou.' }, options: [
      { text: { es: 'Me afecta más de lo que debería y pienso en ello toda la tarde.', en: 'It affects me more than it should and I think about it all afternoon.', fr: 'Ça m\'affecte plus que ça ne devrait et j\'y pense tout l\'après-midi.', de: 'Es betrifft mich mehr als es sollte und ich denke den ganzen Nachmittag daran.', it: 'Mi colpisce più di quanto dovrebbe e ci penso tutto il pomeriggio.', pt: 'Me afeta mais do que deveria e penso nisso a tarde toda.' }, dimension: 'D' },
      { text: { es: 'Lo leo varias veces para asegurarme de entender bien el tono.', en: 'I read it several times to make sure I understand the tone correctly.', fr: 'Je le lis plusieurs fois pour m\'assurer de bien comprendre le ton.', de: 'Ich lese es mehrmals, um sicherzustellen, dass ich den Ton richtig verstehe.', it: 'Lo leggo più volte per assicurarmi di capire bene il tono.', pt: 'Leio várias vezes para garantir que entendi bem o tom.' }, dimension: 'I' },
      { text: { es: 'Lo considero rápido. Si tiene algo válido, lo tomo. Si no, lo ignoro.', en: 'I consider it quickly. If it has something valid, I take it. If not, I ignore it.', fr: 'Je le considère rapidement. S\'il y a quelque chose de valide, je le prends. Sinon, je l\'ignore.', de: 'Ich bedenke es schnell. Wenn es etwas Gültiges hat, nehme ich es. Wenn nicht, ignoriere ich es.', it: 'Lo considero velocemente. Se ha qualcosa di valido, lo prendo. Altrimenti, lo ignoro.', pt: 'Considero rapidamente. Se tem algo válido, levo em conta. Se não, ignoro.' }, dimension: 'C' },
      { text: { es: 'Ni lo recuerdo al día siguiente.', en: 'I don\'t even remember it the next day.', fr: 'Je ne m\'en souviens même pas le lendemain.', de: 'Ich erinnere mich am nächsten Tag nicht einmal daran.', it: 'Non me lo ricordo nemmeno il giorno dopo.', pt: 'Nem me lembro no dia seguinte.' }, dimension: 'R' },
    ] },
    { id: 4, situation: { es: 'Tienes una discusión con alguien cercano. ¿Cómo lo vives?', en: 'You have an argument with someone close. How do you experience it?', fr: 'Tu as une dispute avec quelqu\'un de proche. Comment tu le vis ?', de: 'Du hast einen Streit mit jemandem Nahestehenden. Wie erlebst du ihn?', it: 'Hai una discussione con qualcuno di vicino. Come la vivi?', pt: 'Você tem uma discussão com alguém próximo. Como você vive isso?' }, options: [
      { text: { es: 'Es un evento mayor. Lo replay mentalmente durante días.', en: 'It\'s a major event. I replay it mentally for days.', fr: 'C\'est un événement majeur. Je le rejoue mentalement pendant des jours.', de: 'Es ist ein großes Ereignis. Ich spule es tagelang in meinem Kopf ab.', it: 'È un evento maggiore. Lo replay mentalmente per giorni.', pt: 'É um evento maior. Fico repetindo mentalmente por dias.' }, dimension: 'D' },
      { text: { es: 'Me cuesta seguir con el día normal. Necesito resolver antes de continuar.', en: 'It\'s hard to carry on with the normal day. I need to resolve it before continuing.', fr: 'J\'ai du mal à continuer la journée normalement. Je dois résoudre avant de continuer.', de: 'Es fällt mir schwer, den normalen Tag fortzusetzen. Ich muss es lösen, bevor ich weitermache.', it: 'Faccio fatica a continuare con la giornata normale. Devo risolvere prima di continuare.', pt: 'É difícil seguir o dia normal. Preciso resolver antes de continuar.' }, dimension: 'I' },
      { text: { es: 'Lo vivo en el momento, lo proceso y sigo. No me quedo atascado/a.', en: 'I experience it in the moment, process it and move on. I don\'t get stuck.', fr: 'Je le vis dans le moment, je le traite et je continue. Je ne reste pas bloqué(e).', de: 'Ich erlebe es im Moment, verarbeite es und mache weiter. Ich stecke nicht fest.', it: 'Lo vivo nel momento, lo processo e vado avanti. Non rimango bloccato/a.', pt: 'Vivo no momento, processo e sigo. Não fico emperrado/a.' }, dimension: 'C' },
      { text: { es: 'Los conflictos son parte de las relaciones. Lo hablo, lo cierro, sigo.', en: 'Conflicts are part of relationships. I talk it out, close it, move on.', fr: 'Les conflits font partie des relations. Je le parle, je le ferme, je continue.', de: 'Konflikte sind Teil von Beziehungen. Ich rede darüber, schließe es ab, mache weiter.', it: 'I conflitti sono parte delle relazioni. Ne parlo, lo chiudo, vado avanti.', pt: 'Conflitos são parte dos relacionamentos. Falo, resolvo, sigo.' }, dimension: 'R' },
    ] },
    { id: 5, situation: { es: 'Llegas a una reunión importante y olvidas algo clave en casa.', en: 'You arrive at an important meeting and forgot something key at home.', fr: 'Tu arrives à une réunion importante et tu oublies quelque chose de clé à la maison.', de: 'Du kommst zu einem wichtigen Meeting und hast etwas Wichtiges zuhause vergessen.', it: 'Arrivi a una riunione importante e dimentichi qualcosa di chiave a casa.', pt: 'Você chega a uma reunião importante e esquece algo fundamental em casa.' }, options: [
      { text: { es: 'Catástrofe. ¿Cómo pude hacerme esto?', en: 'Catastrophe. How could I do this to myself?', fr: 'Catastrophe. Comment ai-je pu me faire ça ?', de: 'Katastrophe. Wie konnte ich mir das antun?', it: 'Catastrofe. Come ho potuto fare questo a me stesso/a?', pt: 'Catástrofe. Como pude fazer isso comigo?' }, dimension: 'D' },
      { text: { es: 'Me genera mucha angustia y me cuesta concentrarme el resto de la reunión.', en: 'It gives me a lot of distress and I struggle to concentrate for the rest of the meeting.', fr: 'Ça me génère beaucoup d\'angoisse et j\'ai du mal à me concentrer pour le reste de la réunion.', de: 'Es erzeugt viel Stress bei mir und ich kann mich für den Rest des Meetings kaum konzentrieren.', it: 'Mi genera molta angoscia e faccio fatica a concentrarmi per il resto della riunione.', pt: 'Me gera muita angústia e fico com dificuldade de me concentrar no resto da reunião.' }, dimension: 'I' },
      { text: { es: 'Improviso. Se puede manejar la situación de otra forma.', en: 'I improvise. The situation can be handled another way.', fr: 'J\'improvise. La situation peut être gérée d\'une autre façon.', de: 'Ich improvisiere. Die Situation kann auf andere Weise gehandhabt werden.', it: 'Improvviso. La situazione può essere gestita in un altro modo.', pt: 'Improviso. A situação pode ser gerida de outra forma.' }, dimension: 'C' },
      { text: { es: 'Evalúo si realmente es tan importante y sigo adelante.', en: 'I evaluate if it\'s really that important and move forward.', fr: 'J\'évalue si c\'est vraiment si important et je continue.', de: 'Ich bewerte, ob es wirklich so wichtig ist, und mache weiter.', it: 'Valuto se è davvero così importante e vado avanti.', pt: 'Avalio se é realmente tão importante e sigo em frente.' }, dimension: 'R' },
    ] },
    { id: 6, situation: { es: 'Una persona que te importa no te escribe en todo el día, cuando normalmente lo hace.', en: 'Someone you care about doesn\'t write to you all day, when they normally do.', fr: 'Une personne qui t\'importe ne t\'écrit pas de toute la journée, alors qu\'elle le fait normalement.', de: 'Eine Person, die dir wichtig ist, schreibt dir den ganzen Tag nicht, obwohl sie das normalerweise tut.', it: 'Una persona che ti importa non ti scrive per tutta la giornata, quando di solito lo fa.', pt: 'Uma pessoa que te importa não te escreve durante todo o dia, quando normalmente faz isso.' }, options: [
      { text: { es: 'Estoy alerta desde el mediodía. ¿Pasó algo? ¿Estará bien? ¿Hice algo mal?', en: 'I\'m alert from noon. Did something happen? Are they okay? Did I do something wrong?', fr: 'Je suis en alerte depuis midi. Il s\'est passé quelque chose ? Ça va ? J\'ai fait quelque chose de mal ?', de: 'Ich bin seit Mittag in Alarmbereitschaft. Ist etwas passiert? Geht es ihnen gut? Habe ich etwas falsch gemacht?', it: 'Sono in allerta dal mezzogiorno. È successo qualcosa? Starà bene? Ho fatto qualcosa di sbagliato?', pt: 'Fico alerta desde o meio-dia. Aconteceu algo? Estará bem? Fiz algo errado?' }, dimension: 'D' },
      { text: { es: 'Me genera algo de inquietud aunque sé que probablemente sea simple.', en: 'It gives me some unease even though I know it\'s probably nothing serious.', fr: 'Ça me génère un peu d\'inquiétude même si je sais que c\'est probablement simple.', de: 'Es macht mir etwas Unruhe, obwohl ich weiß, dass es wahrscheinlich simpel ist.', it: 'Mi genera un po\' di inquietudine anche se so che probabilmente è semplice.', pt: 'Me gera alguma inquietação mesmo sabendo que provavelmente é simples.' }, dimension: 'I' },
      { text: { es: 'Seguro está ocupado/a. Le escribo al final del día si no sé nada.', en: 'They\'re probably busy. I\'ll write at the end of the day if I don\'t hear anything.', fr: 'Il/elle est sûrement occupé(e). Je lui écris en fin de journée si je n\'ai pas de nouvelles.', de: 'Er/sie ist wahrscheinlich beschäftigt. Ich schreibe am Ende des Tages, wenn ich nichts höre.', it: 'Sarà sicuramente occupato/a. Gli scrivo alla fine della giornata se non so nulla.', pt: 'Deve estar ocupado/a. Escrevo no final do dia se não tiver notícias.' }, dimension: 'C' },
      { text: { es: 'Le mando un mensaje tranquilo y sigo con mi día.', en: 'I send them a calm message and continue with my day.', fr: 'Je lui envoie un message tranquille et continue ma journée.', de: 'Ich sende ihnen eine ruhige Nachricht und mache mit meinem Tag weiter.', it: 'Gli mando un messaggio tranquillo e continuo con la mia giornata.', pt: 'Mando uma mensagem tranquila e sigo com meu dia.' }, dimension: 'R' },
    ] },
    { id: 7, situation: { es: 'Ves una noticia terrible en el mundo que no te afecta directamente.', en: 'You see terrible news in the world that doesn\'t affect you directly.', fr: 'Tu vois une terrible nouvelle dans le monde qui ne t\'affecte pas directement.', de: 'Du siehst schreckliche Nachrichten in der Welt, die dich nicht direkt betreffen.', it: 'Vedi una notizia terribile nel mondo che non ti riguarda direttamente.', pt: 'Você vê uma notícia terrível no mundo que não te afeta diretamente.' }, options: [
      { text: { es: 'Me quedo en un loop de noticias relacionadas durante horas.', en: 'I get stuck in a loop of related news for hours.', fr: 'Je reste dans une boucle de nouvelles liées pendant des heures.', de: 'Ich bleibe stundenlang in einer Schleife verwandter Nachrichten.', it: 'Rimango in un loop di notizie correlate per ore.', pt: 'Fico em um loop de notícias relacionadas por horas.' }, dimension: 'D' },
      { text: { es: 'Me afecta emocionalmente de forma significativa ese día.', en: 'It emotionally affects me significantly that day.', fr: 'Ça m\'affecte émotionnellement de façon significative ce jour-là.', de: 'Es betrifft mich an diesem Tag emotional erheblich.', it: 'Mi colpisce emotivamente in modo significativo quel giorno.', pt: 'Me afeta emocionalmente de forma significativa naquele dia.' }, dimension: 'I' },
      { text: { es: 'Me afecta, lo proceso y trato de enfocarlo en algo constructivo.', en: 'It affects me, I process it and try to channel it into something constructive.', fr: 'Ça m\'affecte, je le traite et j\'essaie de l\'orienter vers quelque chose de constructif.', de: 'Es betrifft mich, ich verarbeite es und versuche es in etwas Konstruktives zu kanalisieren.', it: 'Mi colpisce, lo processo e cerco di convogliarlo in qualcosa di costruttivo.', pt: 'Me afeta, processo e tento canalizá-lo em algo construtivo.' }, dimension: 'C' },
      { text: { es: 'Lo registro, lo lamento y sigo funcionando con normalidad.', en: 'I register it, grieve it, and keep functioning normally.', fr: 'Je le note, je le déplore et je continue à fonctionner normalement.', de: 'Ich registriere es, beklage es und funktioniere weiterhin normal.', it: 'Lo registro, mi dispiace e continuo a funzionare normalmente.', pt: 'Registro, lamento e sigo funcionando normalmente.' }, dimension: 'R' },
    ] },
    { id: 8, situation: { es: 'Te enteras de que un grupo de personas organizó algo sin invitarte.', en: 'You find out that a group of people organized something without inviting you.', fr: 'Tu apprends qu\'un groupe de personnes a organisé quelque chose sans t\'inviter.', de: 'Du erfährst, dass eine Gruppe von Leuten etwas ohne dich organisiert hat.', it: 'Scopri che un gruppo di persone ha organizzato qualcosa senza invitarti.', pt: 'Você fica sabendo que um grupo de pessoas organizou algo sem te convidar.' }, options: [
      { text: { es: 'Es un golpe. ¿Por qué no me incluyeron? ¿Qué dice eso de mí?', en: 'It\'s a blow. Why weren\'t I included? What does that say about me?', fr: 'C\'est un coup. Pourquoi ne m\'ont-ils pas inclus(e) ? Qu\'est-ce que ça dit de moi ?', de: 'Es ist ein Schlag. Warum war ich nicht dabei? Was sagt das über mich aus?', it: 'È un colpo. Perché non mi hanno incluso/a? Cosa dice di me?', pt: 'É um golpe. Por que não me incluíram? O que isso diz de mim?' }, dimension: 'D' },
      { text: { es: 'Me genera muchas preguntas sobre qué dije o hice para merecer ser excluido/a.', en: 'It raises many questions about what I said or did to deserve being excluded.', fr: 'Ça me génère beaucoup de questions sur ce que j\'ai dit ou fait pour mériter d\'être exclu(e).', de: 'Es wirft viele Fragen auf, was ich gesagt oder getan habe, um ausgeschlossen zu werden.', it: 'Mi genera molte domande su cosa ho detto o fatto per meritare di essere escluso/a.', pt: 'Me gera muitas perguntas sobre o que disse ou fiz para merecer ser excluído/a.' }, dimension: 'I' },
      { text: { es: 'A veces los planes se hacen entre subgrupos. No es personal.', en: 'Sometimes plans are made between subgroups. It\'s not personal.', fr: 'Parfois les plans se font entre sous-groupes. Ce n\'est pas personnel.', de: 'Manchmal werden Pläne zwischen Untergruppen gemacht. Es ist nicht persönlich.', it: 'A volte i piani si fanno tra sottogruppi. Non è personale.', pt: 'Às vezes os planos são feitos entre subgrupos. Não é pessoal.' }, dimension: 'C' },
      { text: { es: 'Bien. No puedo estar en todos los planes y no tiene por qué significar algo.', en: 'Fine. I can\'t be in every plan and it doesn\'t have to mean anything.', fr: 'Bien. Je ne peux pas être dans tous les plans et ça n\'a pas forcément de signification.', de: 'Gut. Ich kann nicht bei allen Plänen dabei sein und das muss nichts bedeuten.', it: 'Bene. Non posso essere in tutti i piani e non deve significare nulla.', pt: 'Tudo bem. Não posso estar em todos os planos e não precisa significar nada.' }, dimension: 'R' },
    ] },
    { id: 9, situation: { es: 'Tus amigos te describen como alguien que...', en: 'Your friends describe you as someone who...', fr: 'Tes amis te décrivent comme quelqu\'un qui...', de: 'Deine Freunde beschreiben dich als jemanden, der...', it: 'I tuoi amici ti descrivono come qualcuno che...', pt: 'Seus amigos te descrevem como alguém que...' }, options: [
      { text: { es: '...siempre tiene algo que contar. Tu vida nunca es aburrida.', en: '...always has something to tell. Your life is never boring.', fr: '...a toujours quelque chose à raconter. Ta vie n\'est jamais ennuyeuse.', de: '...immer etwas zu erzählen hat. Dein Leben ist nie langweilig.', it: '...ha sempre qualcosa da raccontare. La tua vita non è mai noiosa.', pt: '...sempre tem algo para contar. Sua vida nunca é entediante.' }, dimension: 'D' },
      { text: { es: '...siente las cosas con mucha intensidad. Para bien y para mal.', en: '...feels things with great intensity. For better and for worse.', fr: '...ressent les choses avec beaucoup d\'intensité. Pour le meilleur et pour le pire.', de: '...die Dinge mit viel Intensität fühlt. Zum Guten wie zum Schlechten.', it: '...sente le cose con molta intensità. In bene e in male.', pt: '...sente as coisas com muita intensidade. Para o bem e para o mal.' }, dimension: 'I' },
      { text: { es: '...mantiene la cabeza fría cuando otros se alteran.', en: '...keeps a cool head when others get flustered.', fr: '...garde la tête froide quand les autres s\'agitent.', de: '...einen kühlen Kopf bewahrt, wenn andere sich aufregen.', it: '...mantiene la testa fredda quando gli altri si agitano.', pt: '...mantém a cabeça fria quando os outros se alteram.' }, dimension: 'C' },
      { text: { es: '...rebota rápido. Nunca te ven caído/a por mucho tiempo.', en: '...bounces back fast. They never see you down for long.', fr: '...rebondit vite. On ne te voit jamais à terre longtemps.', de: '...schnell zurückspringt. Man sieht dich nie lange am Boden.', it: '...rimbalza velocemente. Non ti vedono mai giù per molto tempo.', pt: '...rebote rápido. Nunca te veem caído/a por muito tempo.' }, dimension: 'R' },
    ] },
    { id: 10, situation: { es: '¿Cuál es tu relación con los contratiempos menores?', en: 'What is your relationship with minor setbacks?', fr: 'Quelle est ta relation avec les contrariétés mineures ?', de: 'Wie ist deine Beziehung zu kleinen Rückschlägen?', it: 'Qual è il tuo rapporto con i contrattempi minori?', pt: 'Qual é sua relação com os contratempos menores?' }, options: [
      { text: { es: 'No hay contratiempos menores en mi radar. Todo merece atención.', en: 'There are no minor setbacks on my radar. Everything deserves attention.', fr: 'Il n\'y a pas de contrariétés mineures dans mon radar. Tout mérite attention.', de: 'Es gibt keine kleinen Rückschläge auf meinem Radar. Alles verdient Aufmerksamkeit.', it: 'Non ci sono contrattempi minori nel mio radar. Tutto merita attenzione.', pt: 'Não há contratempos menores no meu radar. Tudo merece atenção.' }, dimension: 'D' },
      { text: { es: 'Los siento más de lo que me gustaría. Trabajo en ello.', en: 'I feel them more than I\'d like. I\'m working on it.', fr: 'Je les ressens plus que je ne le souhaiterais. J\'y travaille.', de: 'Ich fühle sie mehr als ich möchte. Ich arbeite daran.', it: 'Li sento più di quanto vorrei. Ci lavoro.', pt: 'Os sinto mais do que gostaria. Estou trabalhando nisso.' }, dimension: 'I' },
      { text: { es: 'Los proceso rápido y sigo. La energía emocional es finita y hay que usarla bien.', en: 'I process them quickly and move on. Emotional energy is finite and should be used wisely.', fr: 'Je les traite rapidement et je continue. L\'énergie émotionnelle est finie et il faut bien l\'utiliser.', de: 'Ich verarbeite sie schnell und mache weiter. Emotionale Energie ist endlich und sollte gut eingesetzt werden.', it: 'Li processo velocemente e vado avanti. L\'energia emotiva è finita e va usata bene.', pt: 'Os processo rapidamente e sigo. A energia emocional é finita e deve ser bem usada.' }, dimension: 'C' },
      { text: { es: 'Casi no los registro. Si no es importante en cinco años, no lo es ahora.', en: 'I barely register them. If it won\'t matter in five years, it doesn\'t matter now.', fr: 'Je les note à peine. Si ce n\'est pas important dans cinq ans, ça ne l\'est pas maintenant.', de: 'Ich registriere sie kaum. Wenn es in fünf Jahren nicht wichtig ist, ist es jetzt nicht wichtig.', it: 'Li registro appena. Se non è importante tra cinque anni, non lo è adesso.', pt: 'Quase não os registro. Se não vai ser importante em cinco anos, não é agora.' }, dimension: 'R' },
    ] },
  ],
  characters: [
    { name: { es: 'La Protagonista de su Propia Telenovela', en: 'The Protagonist of Their Own Soap Opera', fr: 'Le Protagoniste de sa Propre Telenovela', de: 'Der Protagonist seiner eigenen Telenovela', it: 'Il Protagonista della Propria Telenovela', pt: 'O Protagonista de sua Própria Novela' }, dimensions: ['D'], photo: '/characters/telenovela.jpg', description: { es: 'Cada día es un episodio. Cada problema, un drama de temporada.', en: 'Every day is an episode. Every problem, a season drama.', fr: 'Chaque jour est un épisode. Chaque problème, un drame de saison.', de: 'Jeder Tag ist eine Episode. Jedes Problem, ein Saisondrama.', it: 'Ogni giorno è un episodio. Ogni problema, un dramma di stagione.', pt: 'Cada dia é um episódio. Cada problema, um drama de temporada.' }, philosophy: { es: 'Tu vida interior es intensa y rica. Sientes todo con fuerza máxima y eso te hace alguien magnético/a. El drama no es un defecto — es la forma en que experimentas el mundo. Solo que a veces el volumen está demasiado alto.', en: 'Your inner life is intense and rich. You feel everything at maximum strength and that makes you magnetic. Drama is not a defect — it\'s the way you experience the world. Just sometimes the volume is too high.', fr: 'Ta vie intérieure est intense et riche. Tu ressens tout à puissance maximale et ça te rend magnétique. Le drame n\'est pas un défaut — c\'est la façon dont tu expérimentes le monde. Sauf que parfois le volume est trop fort.', de: 'Dein Innenleben ist intensiv und reich. Du fühlst alles mit maximaler Kraft und das macht dich magnetisch. Drama ist kein Defekt — es ist die Art, wie du die Welt erlebst. Nur manchmal ist die Lautstärke zu hoch.', it: 'La tua vita interiore è intensa e ricca. Senti tutto con forza massima e questo ti rende magnetico/a. Il dramma non è un difetto — è il modo in cui sperimenti il mondo. Solo che a volte il volume è troppo alto.', pt: 'Sua vida interior é intensa e rica. Você sente tudo com força máxima e isso te torna magnético/a. O drama não é um defeito — é a forma como você experimenta o mundo. Só que às vezes o volume está muito alto.' } },
    { name: { es: 'El Sensible Intenso', en: 'The Intense Sensitive', fr: 'Le Sensible Intense', de: 'Der Intensiv Sensible', it: 'Il Sensibile Intenso', pt: 'O Sensível Intenso' }, dimensions: ['I'], photo: '/characters/intense-sensitive.jpg', description: { es: 'Siente profundamente. No exagera — simplemente tiene alta definición emocional.', en: 'Feels deeply. Doesn\'t exaggerate — simply has high emotional definition.', fr: 'Ressent profondément. N\'exagère pas — a simplement une haute définition émotionnelle.', de: 'Fühlt tief. Übertreibt nicht — hat einfach eine hohe emotionale Auflösung.', it: 'Sente profondamente. Non esagera — ha semplicemente alta definizione emotiva.', pt: 'Sente profundamente. Não exagera — simplesmente tem alta definição emocional.' }, philosophy: { es: 'Tu intensidad emocional no es drama — es sensibilidad genuina. Percibes más matices, más detalles, más capas. Eso puede ser agotador, pero también significa que vives con una profundidad que otros no experimentan.', en: 'Your emotional intensity is not drama — it\'s genuine sensitivity. You perceive more nuances, more details, more layers. That can be exhausting, but it also means you live with a depth that others don\'t experience.', fr: 'Ton intensité émotionnelle n\'est pas du drame — c\'est une sensibilité authentique. Tu perçois plus de nuances, plus de détails, plus de couches. C\'est peut-être épuisant, mais ça signifie aussi que tu vis avec une profondeur que les autres n\'expérimentent pas.', de: 'Deine emotionale Intensität ist kein Drama — es ist echte Sensibilität. Du nimmst mehr Nuancen wahr, mehr Details, mehr Schichten. Das kann erschöpfend sein, bedeutet aber auch, dass du mit einer Tiefe lebst, die andere nicht erleben.', it: 'La tua intensità emotiva non è dramma — è sensibilità genuina. Percepisci più sfumature, più dettagli, più strati. Può essere esaurente, ma significa anche che vivi con una profondità che gli altri non sperimentano.', pt: 'Sua intensidade emocional não é drama — é sensibilidade genuína. Você percebe mais nuances, mais detalhes, mais camadas. Isso pode ser exaustivo, mas também significa que você vive com uma profundidade que outros não experimentam.' } },
    { name: { es: 'El Tranquilo Estable', en: 'The Calm Stable', fr: 'Le Calme Stable', de: 'Der Ruhige Stabile', it: 'Il Tranquillo Stabile', pt: 'O Tranquilo Estável' }, dimensions: ['C'], photo: '/characters/calm-stable.jpg', description: { es: 'El ancla en cualquier tormenta. Difícil de alterar.', en: 'The anchor in any storm. Hard to disturb.', fr: 'L\'ancre dans toute tempête. Difficile à altérer.', de: 'Der Anker in jedem Sturm. Schwer zu erschüttern.', it: 'L\'ancora in qualsiasi tempesta. Difficile da alterare.', pt: 'A âncora em qualquer tempestade. Difícil de alterar.' }, philosophy: { es: 'Tu ecuanimidad no es frialdad — es madurez emocional. Has aprendido (o siempre supiste) que la mayoría de los contratiempos no merecen la energía que les daría alguien más reactivo. Eso te hace confiable en situaciones difíciles.', en: 'Your equanimity is not coldness — it\'s emotional maturity. You\'ve learned (or always knew) that most setbacks don\'t deserve the energy a more reactive person would give them. That makes you reliable in difficult situations.', fr: 'Ton équanimité n\'est pas de la froideur — c\'est de la maturité émotionnelle. Tu as appris (ou toujours su) que la plupart des contrariétés ne méritent pas l\'énergie qu\'une personne plus réactive leur donnerait. Ça te rend fiable dans des situations difficiles.', de: 'Deine Gelassenheit ist keine Kälte — es ist emotionale Reife. Du hast gelernt (oder immer gewusst), dass die meisten Rückschläge nicht die Energie verdienen, die eine reaktivere Person ihnen geben würde. Das macht dich in schwierigen Situationen zuverlässig.', it: 'La tua equanimità non è freddezza — è maturità emotiva. Hai imparato (o sempre saputo) che la maggior parte dei contrattempi non merita l\'energia che darebbe loro una persona più reattiva. Questo ti rende affidabile nelle situazioni difficili.', pt: 'Sua equanimidade não é frieza — é maturidade emocional. Você aprendeu (ou sempre soube) que a maioria dos contratempos não merece a energia que uma pessoa mais reativa lhes daria. Isso te torna confiável em situações difíceis.' } },
    { name: { es: 'El Resiliente Natural', en: 'The Natural Resilient', fr: 'Le Résilient Naturel', de: 'Der Natürliche Resiliente', it: 'Il Resiliente Naturale', pt: 'O Resiliente Natural' }, dimensions: ['R'], photo: '/characters/resilient.jpg', description: { es: 'Cae, rebota. Una y otra vez. Siempre hacia adelante.', en: 'Falls, bounces back. Again and again. Always forward.', fr: 'Tombe, rebondit. Encore et encore. Toujours en avant.', de: 'Fällt, springt zurück. Immer wieder. Immer vorwärts.', it: 'Cade, rimbalza. Ancora e ancora. Sempre avanti.', pt: 'Cai, rebote. Vez após vez. Sempre para frente.' }, philosophy: { es: 'No es que no te afecte nada — es que tu capacidad de recuperación es extraordinaria. Procesas, integras y sigues. Esa resiliencia no se compró — se construyó, probablemente a través de experiencias difíciles que dejaste atrás.', en: 'It\'s not that nothing affects you — it\'s that your recovery capacity is extraordinary. You process, integrate, and move on. That resilience wasn\'t bought — it was built, probably through difficult experiences you left behind.', fr: 'Ce n\'est pas que rien ne t\'affecte — c\'est que ta capacité de récupération est extraordinaire. Tu traites, intègres et continues. Cette résilience ne s\'est pas achetée — elle s\'est construite, probablement à travers des expériences difficiles que tu as laissées derrière toi.', de: 'Es ist nicht so, dass dich nichts betrifft — es ist, dass deine Erholungsfähigkeit außergewöhnlich ist. Du verarbeitest, integrierst und machst weiter. Diese Resilienz wurde nicht gekauft — sie wurde aufgebaut, wahrscheinlich durch schwierige Erfahrungen, die du hinter dir gelassen hast.', it: 'Non è che niente ti colpisca — è che la tua capacità di recupero è straordinaria. Elabori, integri e vai avanti. Quella resilienza non si è comprata — si è costruita, probabilmente attraverso esperienze difficili che hai lasciato alle spalle.', pt: 'Não é que nada te afete — é que sua capacidade de recuperação é extraordinária. Você processa, integra e segue. Essa resiliência não foi comprada — foi construída, provavelmente através de experiências difíceis que você deixou para trás.' } },
    { name: { es: 'La Reina del Drama Intenso', en: 'The Queen of Intense Drama', fr: 'La Reine du Drame Intense', de: 'Die Königin des Intensiven Dramas', it: 'La Regina del Dramma Intenso', pt: 'A Rainha do Drama Intenso' }, dimensions: ['D', 'I'], photo: '/characters/drama-queen.jpg', description: { es: 'Drama e intensidad juntos. Una combinación de alto mantenimiento.', en: 'Drama and intensity together. A high-maintenance combination.', fr: 'Drame et intensité ensemble. Une combinaison à entretien élevé.', de: 'Drama und Intensität zusammen. Eine anspruchsvolle Kombination.', it: 'Dramma e intensità insieme. Una combinazione ad alto mantenimento.', pt: 'Drama e intensidade juntos. Uma combinação de alto manutenção.' }, philosophy: { es: 'Vives la vida al máximo volumen. Cada emoción está amplificada. Es agotador para el entorno, pero también significa que cuando amas, amas con todo. Cuando celebras, es memorable. El precio es alto, pero la experiencia también.', en: 'You live life at maximum volume. Every emotion is amplified. It\'s exhausting for those around you, but it also means when you love, you love with everything. When you celebrate, it\'s memorable. The price is high, but so is the experience.', fr: 'Tu vis la vie au volume maximum. Chaque émotion est amplifiée. C\'est épuisant pour l\'entourage, mais ça signifie aussi que quand tu aimes, tu aimes avec tout. Quand tu célèbres, c\'est mémorable. Le prix est élevé, mais l\'expérience aussi.', de: 'Du lebst das Leben mit maximaler Lautstärke. Jede Emotion ist verstärkt. Es ist erschöpfend für das Umfeld, aber es bedeutet auch, dass wenn du liebst, du mit allem liebst. Wenn du feierst, ist es unvergesslich. Der Preis ist hoch, aber die Erfahrung auch.', it: 'Vivi la vita al massimo volume. Ogni emozione è amplificata. È estenuante per l\'entourage, ma significa anche che quando ami, ami con tutto. Quando festeggi, è memorabile. Il prezzo è alto, ma anche l\'esperienza.', pt: 'Você vive a vida no volume máximo. Cada emoção está amplificada. É exaustivo para o entorno, mas também significa que quando ama, ama com tudo. Quando celebra, é memorável. O preço é alto, mas a experiência também.' } },
    { name: { es: 'El Zen con Profundidad', en: 'Zen with Depth', fr: 'Le Zen avec Profondeur', de: 'Zen mit Tiefe', it: 'Lo Zen con Profondità', pt: 'O Zen com Profundidade' }, dimensions: ['C', 'R'], photo: '/characters/zen.jpg', description: { es: 'Calmado y resiliente. El que todos quieren cerca cuando las cosas se ponen difíciles.', en: 'Calm and resilient. The one everyone wants nearby when things get tough.', fr: 'Calme et résilient. Celui/celle que tout le monde veut près de soi quand les choses deviennent difficiles.', de: 'Ruhig und resilient. Der/die, den/die alle in der Nähe haben wollen, wenn es schwierig wird.', it: 'Calmo e resiliente. Quello che tutti vogliono vicino quando le cose si fanno difficili.', pt: 'Calmo e resiliente. Aquele que todos querem por perto quando as coisas ficam difíceis.' }, philosophy: { es: 'Combinas la calma con la capacidad de recuperación. No es que no sientas — es que tienes una relación madura con tus emociones. Las procesas sin que te gobiernen. Eso es muy difícil de lograr.', en: 'You combine calm with the ability to recover. It\'s not that you don\'t feel — it\'s that you have a mature relationship with your emotions. You process them without letting them govern you. That\'s very hard to achieve.', fr: 'Tu combines le calme avec la capacité de récupération. Ce n\'est pas que tu ne ressens pas — c\'est que tu as une relation mature avec tes émotions. Tu les traites sans qu\'elles te gouvernent. C\'est très difficile à réaliser.', de: 'Du kombinierst Ruhe mit der Fähigkeit zur Erholung. Es ist nicht so, dass du nichts fühlst — es ist, dass du eine reife Beziehung zu deinen Emotionen hast. Du verarbeitest sie, ohne dass sie dich beherrschen. Das ist sehr schwer zu erreichen.', it: 'Combini la calma con la capacità di recupero. Non è che non senti — è che hai una relazione matura con le tue emozioni. Le elabori senza che ti governino. È molto difficile da ottenere.', pt: 'Você combina a calma com a capacidade de recuperação. Não é que você não sinta — é que você tem uma relação madura com suas emoções. Você as processa sem que elas te governem. Isso é muito difícil de conseguir.' } },
    { name: { es: 'El Intenso Resiliente', en: 'The Intense Resilient', fr: 'L\'Intense Résilient', de: 'Der Intensive Resiliente', it: 'L\'Intenso Resiliente', pt: 'O Intenso Resiliente' }, dimensions: ['I', 'R'], photo: '/characters/intense-resilient.jpg', description: { es: 'Siente fuerte y rebota fuerte.', en: 'Feels strong and bounces back strong.', fr: 'Ressent fort et rebondit fort.', de: 'Fühlt stark und springt stark zurück.', it: 'Sente forte e rimbalza forte.', pt: 'Sente forte e rebote forte.' }, philosophy: { es: 'Vives las cosas con intensidad real, pero tienes la capacidad de rehacerte. Tu ciclo emocional es pronunciado — muy arriba, muy abajo — pero siempre vuelves al equilibrio. Eso requiere una fortaleza que no siempre se ve desde afuera.', en: 'You experience things with real intensity, but you have the ability to rebuild. Your emotional cycle is pronounced — very high, very low — but you always return to balance. That requires a strength that\'s not always visible from the outside.', fr: 'Tu vis les choses avec une intensité réelle, mais tu as la capacité de te refaire. Ton cycle émotionnel est prononcé — très haut, très bas — mais tu reviens toujours à l\'équilibre. Ça demande une force qui n\'est pas toujours visible de l\'extérieur.', de: 'Du erlebst Dinge mit echter Intensität, aber du hast die Fähigkeit, dich neu aufzubauen. Dein emotionaler Zyklus ist ausgeprägt — sehr hoch, sehr niedrig — aber du kehrst immer zum Gleichgewicht zurück. Das erfordert eine Stärke, die von außen nicht immer sichtbar ist.', it: 'Vivi le cose con intensità reale, ma hai la capacità di ricostruirti. Il tuo ciclo emotivo è pronunciato — molto su, molto giù — ma torni sempre all\'equilibrio. Questo richiede una forza che non si vede sempre dall\'esterno.', pt: 'Você vive as coisas com intensidade real, mas tem a capacidade de se refazer. Seu ciclo emocional é pronunciado — muito alto, muito baixo — mas você sempre volta ao equilíbrio. Isso requer uma força que nem sempre se vê de fora.' } },
    { name: { es: 'El Equilibrado Moderno', en: 'The Modern Balanced', fr: 'L\'Équilibré Moderne', de: 'Der Moderne Ausgeglichene', it: 'L\'Equilibrato Moderno', pt: 'O Equilibrado Moderno' }, dimensions: ['C', 'I'], photo: '/characters/modern-balance.jpg', description: { es: 'Siente con profundidad pero mantiene el control.', en: 'Feels deeply but maintains control.', fr: 'Ressent profondément mais maintient le contrôle.', de: 'Fühlt tief, aber behält die Kontrolle.', it: 'Sente profondamente ma mantiene il controllo.', pt: 'Sente profundamente mas mantém o controle.' }, philosophy: { es: 'Eres profundo/a sin ser reactivo/a. Sientes las cosas de verdad — no las minimizas — pero tienes la madurez de no actuar desde cada emoción que te visita. Es la combinación más difícil de lograr y la más valiosa.', en: 'You\'re deep without being reactive. You genuinely feel things — you don\'t minimize them — but you have the maturity not to act from every emotion that visits you. It\'s the hardest combination to achieve and the most valuable.', fr: 'Tu es profond(e) sans être réactif/ve. Tu ressens vraiment les choses — tu ne les minimises pas — mais tu as la maturité de ne pas agir depuis chaque émotion qui te visite. C\'est la combinaison la plus difficile à réaliser et la plus précieuse.', de: 'Du bist tiefgründig ohne reaktiv zu sein. Du fühlst Dinge wirklich — du minimierst sie nicht — aber du hast die Reife, nicht aus jeder Emotion heraus zu handeln, die dich besucht. Es ist die schwierigste Kombination zu erreichen und die wertvollste.', it: 'Sei profondo/a senza essere reattivo/a. Senti le cose davvero — non le minimizzi — ma hai la maturità di non agire da ogni emozione che ti visita. È la combinazione più difficile da raggiungere e la più preziosa.', pt: 'Você é profundo/a sem ser reativo/a. Você sente as coisas de verdade — não as minimiza — mas tem a maturidade de não agir a partir de cada emoção que te visita. É a combinação mais difícil de conseguir e a mais valiosa.' } },
  ],
};

export async function seedDramatic(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'dramatic' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'dramatic',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 6,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
