import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan cobarde eres?', en: 'How cowardly are you?', fr: 'À quel point es-tu lâche ?', de: 'Wie feige bist du?', it: 'Quanto sei codardo/a?', pt: 'O quanto você é covarde?' },
  description: { es: 'El coraje no es la ausencia de miedo. Es actuar a pesar de él. ¿Tú actúas?', en: 'Courage is not the absence of fear. It\'s acting despite it. Do you act?', fr: 'Le courage n\'est pas l\'absence de peur. C\'est agir malgré elle. Est-ce que tu agis ?', de: 'Mut ist nicht die Abwesenheit von Angst. Es geht darum, trotzdem zu handeln. Handelst du?', it: 'Il coraggio non è l\'assenza di paura. È agire nonostante essa. Tu agisci?', pt: 'Coragem não é a ausência de medo. É agir apesar dele. Você age?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { C: 'Cobardía', V: 'Valentía', P: 'Prudencia', A: 'Audacia' },
    en: { C: 'Cowardice', V: 'Bravery', P: 'Prudence', A: 'Audacity' },
    fr: { C: 'Lâcheté', V: 'Bravoure', P: 'Prudence', A: 'Audace' },
    de: { C: 'Feigheit', V: 'Tapferkeit', P: 'Besonnenheit', A: 'Kühnheit' },
    it: { C: 'Vigliaccheria', V: 'Coraggio', P: 'Prudenza', A: 'Audacia' },
    pt: { C: 'Covardia', V: 'Bravura', P: 'Prudência', A: 'Audácia' },
  },
  questions: [
    { id: 1, situation: { es: 'Alguien dice algo injusto frente a un grupo. Nadie habla. ¿Qué haces?', en: 'Someone says something unfair in front of a group. Nobody speaks up. What do you do?', fr: 'Quelqu\'un dit quelque chose d\'injuste devant un groupe. Personne ne parle. Que fais-tu ?', de: 'Jemand sagt etwas Ungerechtes vor einer Gruppe. Niemand spricht. Was tust du?', it: 'Qualcuno dice qualcosa di ingiusto di fronte a un gruppo. Nessuno parla. Cosa fai?', pt: 'Alguém diz algo injusto diante de um grupo. Ninguém fala. O que você faz?' }, options: [
      { text: { es: 'Me quedo callado/a. No es mi batalla y no quiero el conflicto.', en: 'I stay silent. It\'s not my battle and I don\'t want the conflict.', fr: 'Je reste silencieux/se. Ce n\'est pas ma bataille et je ne veux pas le conflit.', de: 'Ich bleibe still. Es ist nicht mein Kampf und ich will den Konflikt nicht.', it: 'Rimango in silenzio. Non è la mia battaglia e non voglio il conflitto.', pt: 'Fico calado/a. Não é minha batalha e não quero o conflito.' }, dimension: 'C' },
      { text: { es: 'Lo digo claramente aunque me ponga en una posición incómoda.', en: 'I say it clearly even if it puts me in an uncomfortable position.', fr: 'Je le dis clairement même si ça me met dans une position inconfortable.', de: 'Ich sage es klar, auch wenn es mich in eine unangenehme Position bringt.', it: 'Lo dico chiaramente anche se mi mette in una posizione scomoda.', pt: 'Digo claramente mesmo que me coloque em uma posição desconfortável.' }, dimension: 'V' },
      { text: { es: 'Espero el momento y el contexto adecuado para decirlo de forma efectiva.', en: 'I wait for the right moment and context to say it effectively.', fr: 'J\'attends le bon moment et contexte pour le dire de façon effective.', de: 'Ich warte auf den richtigen Moment und Kontext, um es effektiv zu sagen.', it: 'Aspetto il momento e il contesto adeguato per dirlo in modo efficace.', pt: 'Espero o momento e contexto adequado para dizê-lo de forma eficaz.' }, dimension: 'P' },
      { text: { es: 'Lo digo inmediatamente con toda claridad, sin calcular consecuencias.', en: 'I say it immediately with full clarity, without calculating consequences.', fr: 'Je le dis immédiatement avec toute clarté, sans calculer les conséquences.', de: 'Ich sage es sofort mit voller Klarheit, ohne Konsequenzen zu berechnen.', it: 'Lo dico immediatamente con tutta chiarezza, senza calcolare le conseguenze.', pt: 'Digo imediatamente com toda clareza, sem calcular consequências.' }, dimension: 'A' },
    ] },
    { id: 2, situation: { es: 'Llevas años en un trabajo que odias. Tienes una idea de negocio que te emociona. ¿Qué haces?', en: 'You\'ve been at a job you hate for years. You have a business idea that excites you. What do you do?', fr: 'Tu es depuis des années dans un travail que tu détestes. Tu as une idée d\'entreprise qui t\'enthousiasme. Que fais-tu ?', de: 'Du bist seit Jahren in einem Job, den du hasst. Du hast eine Geschäftsidee, die dich begeistert. Was tust du?', it: 'Sei da anni in un lavoro che odi. Hai un\'idea di business che ti entusiasma. Cosa fai?', pt: 'Você está há anos em um emprego que odeia. Tem uma ideia de negócio que te emociona. O que você faz?' }, options: [
      { text: { es: 'Me quedo en el trabajo. La seguridad vale más que el riesgo.', en: 'I stay at the job. Security is worth more than risk.', fr: 'Je reste dans le travail. La sécurité vaut plus que le risque.', de: 'Ich bleibe im Job. Sicherheit ist mehr wert als Risiko.', it: 'Rimango nel lavoro. La sicurezza vale più del rischio.', pt: 'Fico no emprego. A segurança vale mais do que o risco.' }, dimension: 'C' },
      { text: { es: 'Renuncio en los próximos meses. He postergado demasiado.', en: 'I quit in the coming months. I\'ve postponed too much.', fr: 'Je démissionne dans les prochains mois. J\'ai trop tardé.', de: 'Ich kündige in den nächsten Monaten. Ich habe zu lange gezögert.', it: 'Mi dimetto nei prossimi mesi. Ho rimandato troppo.', pt: 'Peço demissão nos próximos meses. Já posterguei demais.' }, dimension: 'V' },
      { text: { es: 'Construyo el negocio en paralelo hasta que tenga ingresos suficientes para el salto.', en: 'I build the business in parallel until I have enough income to make the leap.', fr: 'Je construis l\'entreprise en parallèle jusqu\'à ce que j\'aie des revenus suffisants pour le saut.', de: 'Ich baue das Unternehmen parallel auf, bis ich genug Einkommen für den Sprung habe.', it: 'Costruisco il business in parallelo finché non ho abbastanza entrate per il salto.', pt: 'Construo o negócio em paralelo até ter renda suficiente para o salto.' }, dimension: 'P' },
      { text: { es: 'Renuncio y me lanzo. Si no ahora, ¿cuándo?', en: 'I quit and go for it. If not now, when?', fr: 'Je démissionne et je me lance. Si ce n\'est pas maintenant, quand ?', de: 'Ich kündige und starte durch. Wenn nicht jetzt, wann dann?', it: 'Mi dimetto e mi lancio. Se non adesso, quando?', pt: 'Peço demissão e me lanço. Se não agora, quando?' }, dimension: 'A' },
    ] },
    { id: 3, situation: { es: 'Alguien a quien respetas dice algo equivocado en público y espera que todos estén de acuerdo.', en: 'Someone you respect says something wrong in public and expects everyone to agree.', fr: 'Quelqu\'un que tu respectes dit quelque chose de faux en public et s\'attend à ce que tout le monde soit d\'accord.', de: 'Jemand, den du respektierst, sagt öffentlich etwas Falsches und erwartet, dass alle zustimmen.', it: 'Qualcuno che rispetti dice qualcosa di sbagliato in pubblico e si aspetta che tutti siano d\'accordo.', pt: 'Alguém que você respeita diz algo errado em público e espera que todos concordem.' }, options: [
      { text: { es: 'Asiento o guardo silencio. No vale la pena el enfrentamiento.', en: 'I nod or stay silent. It\'s not worth the confrontation.', fr: 'J\'acquiesce ou je garde le silence. Ça ne vaut pas la confrontation.', de: 'Ich nicke oder schweige. Es ist die Konfrontation nicht wert.', it: 'Annuisco o rimango in silenzio. Non vale la pena dell\'affronto.', pt: 'Aceno ou fico em silêncio. Não vale a confrontação.' }, dimension: 'C' },
      { text: { es: 'Expreso respetuosamente mi desacuerdo. El respeto no requiere silencio.', en: 'I respectfully express my disagreement. Respect doesn\'t require silence.', fr: 'J\'exprime respectueusement mon désaccord. Le respect ne nécessite pas le silence.', de: 'Ich äußere respektvoll meinen Dissens. Respekt erfordert kein Schweigen.', it: 'Esprimo rispettosamente il mio disaccordo. Il rispetto non richiede il silenzio.', pt: 'Expresso respeitosamente minha discordância. Respeito não exige silêncio.' }, dimension: 'V' },
      { text: { es: 'Evalúo si vale la pena decirlo en ese momento o si es mejor en privado.', en: 'I evaluate whether it\'s worth saying it now or better in private.', fr: 'J\'évalue si ça vaut la peine de le dire à ce moment ou si c\'est mieux en privé.', de: 'Ich überlege, ob es sich lohnt, es jetzt zu sagen oder besser unter vier Augen.', it: 'Valuto se vale la pena dirlo in quel momento o se è meglio in privato.', pt: 'Avaliou se vale a pena dizer agora ou se é melhor em privado.' }, dimension: 'P' },
      { text: { es: 'Lo digo directamente sin importar el respeto que le tenga. El error es el error.', en: 'I say it directly regardless of the respect I have for them. An error is an error.', fr: 'Je le dis directement sans tenir compte du respect que j\'ai pour lui/elle. L\'erreur est l\'erreur.', de: 'Ich sage es direkt, ungeachtet des Respekts, den ich habe. Ein Fehler ist ein Fehler.', it: 'Lo dico direttamente senza tener conto del rispetto che ho per lui/lei. L\'errore è l\'errore.', pt: 'Digo diretamente independentemente do respeito que tenho. O erro é o erro.' }, dimension: 'A' },
    ] },
    { id: 4, situation: { es: 'Una relación que llevas tiempo está claramente terminada. ¿Cuándo lo dices?', en: 'A relationship you\'ve been in for a while is clearly over. When do you say it?', fr: 'Une relation dans laquelle tu es depuis un moment est clairement terminée. Quand le dis-tu ?', de: 'Eine Beziehung, in der du schon eine Weile bist, ist eindeutig vorbei. Wann sagst du es?', it: 'Una relazione in cui sei da un po\' è chiaramente finita. Quando lo dici?', pt: 'Um relacionamento em que você está há um tempo está claramente acabado. Quando você diz isso?' }, options: [
      { text: { es: 'Lo sigo postergando. No soporto hacerle daño a alguien.', en: 'I keep postponing it. I can\'t stand hurting someone.', fr: 'Je continue à le reporter. Je ne supporte pas de faire du mal à quelqu\'un.', de: 'Ich schiebe es weiter hinaus. Ich kann es nicht ertragen, jemandem zu schaden.', it: 'Continuo a rimandarlo. Non sopporto fare del male a qualcuno.', pt: 'Continuo adiando. Não suporto machucar alguém.' }, dimension: 'C' },
      { text: { es: 'En el próximo momento honesto que tenga. No puedo seguir en algo que ya se terminó.', en: 'At the next honest moment I have. I can\'t stay in something that\'s already over.', fr: 'Au prochain moment honnête que j\'aurai. Je ne peux pas rester dans quelque chose qui est déjà terminé.', de: 'Im nächsten ehrlichen Moment, den ich habe. Ich kann nicht in etwas bleiben, das schon vorbei ist.', it: 'Al prossimo momento onesto che avrò. Non posso rimanere in qualcosa che è già finito.', pt: 'No próximo momento honesto que tiver. Não posso continuar em algo que já acabou.' }, dimension: 'V' },
      { text: { es: 'Espero el momento menos doloroso posible para ambos.', en: 'I wait for the least painful moment possible for both of us.', fr: 'J\'attends le moment le moins douloureux possible pour nous deux.', de: 'Ich warte auf den am wenigsten schmerzhaften Moment für uns beide.', it: 'Aspetto il momento meno doloroso possibile per entrambi.', pt: 'Espero o momento menos doloroso possível para ambos.' }, dimension: 'P' },
      { text: { es: 'Lo digo ahora. Cada día que pasa es un día más de daño para los dos.', en: 'I say it now. Every day that passes is another day of harm for both.', fr: 'Je le dis maintenant. Chaque jour qui passe est un jour de plus de mal pour nous deux.', de: 'Ich sage es jetzt. Jeder Tag, der vergeht, ist ein weiterer Tag des Schadens für uns beide.', it: 'Lo dico adesso. Ogni giorno che passa è un giorno in più di danno per entrambi.', pt: 'Digo agora. Cada dia que passa é mais um dia de dano para os dois.' }, dimension: 'A' },
    ] },
    { id: 5, situation: { es: 'Hay una conversación difícil pendiente que llevas semanas evitando. ¿Qué pasa?', en: 'There\'s a difficult conversation pending that you\'ve been avoiding for weeks. What happens?', fr: 'Il y a une conversation difficile en attente que tu évites depuis des semaines. Que se passe-t-il ?', de: 'Es gibt ein schwieriges Gespräch, das du seit Wochen vermeidest. Was passiert?', it: 'C\'è una conversazione difficile in sospeso che stai evitando da settimane. Cosa succede?', pt: 'Há uma conversa difícil pendente que você evita há semanas. O que acontece?' }, options: [
      { text: { es: 'Sigo evitándola. Quizás el tiempo la resuelva solo.', en: 'I keep avoiding it. Maybe time will resolve it on its own.', fr: 'Je continue à l\'éviter. Peut-être que le temps va la résoudre seul.', de: 'Ich vermeide sie weiterhin. Vielleicht löst die Zeit sie von selbst.', it: 'Continuo ad evitarla. Forse il tempo la risolverà da solo.', pt: 'Continuo evitando. Talvez o tempo resolva por si só.' }, dimension: 'C' },
      { text: { es: 'La tengo. Las conversaciones difíciles no mejoran con el tiempo.', en: 'I have it. Difficult conversations don\'t get better with time.', fr: 'Je l\'ai. Les conversations difficiles ne s\'améliorent pas avec le temps.', de: 'Ich führe sie. Schwierige Gespräche werden mit der Zeit nicht besser.', it: 'La ho. Le conversazioni difficili non migliorano col tempo.', pt: 'A tenho. Conversas difíceis não melhoram com o tempo.' }, dimension: 'V' },
      { text: { es: 'Espero el momento y el contexto correctos para que sea más productiva.', en: 'I wait for the right moment and context so it can be more productive.', fr: 'J\'attends le bon moment et le bon contexte pour qu\'elle soit plus productive.', de: 'Ich warte auf den richtigen Moment und Kontext, damit es produktiver wird.', it: 'Aspetto il momento e il contesto giusti per renderla più produttiva.', pt: 'Espero o momento e o contexto certos para que seja mais produtiva.' }, dimension: 'P' },
      { text: { es: 'La propongo para esta semana. No hay momento perfecto.', en: 'I schedule it for this week. There\'s no perfect moment.', fr: 'Je la propose pour cette semaine. Il n\'y a pas de moment parfait.', de: 'Ich schlage sie für diese Woche vor. Es gibt keinen perfekten Moment.', it: 'La propongo per questa settimana. Non c\'è un momento perfetto.', pt: 'Proponho para esta semana. Não há momento perfeito.' }, dimension: 'A' },
    ] },
    { id: 6, situation: { es: 'Tienes la oportunidad de hacer algo que siempre quisiste pero que te aterra.', en: 'You have the opportunity to do something you always wanted but that terrifies you.', fr: 'Tu as l\'opportunité de faire quelque chose que tu as toujours voulu mais qui te terrifie.', de: 'Du hast die Möglichkeit, etwas zu tun, das du schon immer wolltest, aber das dich erschreckt.', it: 'Hai l\'opportunità di fare qualcosa che hai sempre voluto ma che ti spaventa.', pt: 'Você tem a oportunidade de fazer algo que sempre quis mas que te aterra.' }, options: [
      { text: { es: 'Lo dejo pasar. El miedo es una señal de que no estoy listo/a.', en: 'I let it pass. Fear is a sign that I\'m not ready.', fr: 'Je le laisse passer. La peur est un signe que je ne suis pas prêt(e).', de: 'Ich lasse es vorbeiziehen. Angst ist ein Zeichen, dass ich noch nicht bereit bin.', it: 'Lo lascio passare. La paura è un segnale che non sono pronto/a.', pt: 'Deixo passar. O medo é um sinal de que não estou pronto/a.' }, dimension: 'C' },
      { text: { es: 'Lo hago aunque esté aterrado/a. El miedo es compañero, no obstáculo.', en: 'I do it even though I\'m terrified. Fear is a companion, not an obstacle.', fr: 'Je le fais même si je suis terrifié(e). La peur est un compagnon, pas un obstacle.', de: 'Ich tue es, auch wenn ich erschreckt bin. Angst ist ein Begleiter, kein Hindernis.', it: 'Lo faccio anche se sono terrorizzato/a. La paura è un compagno, non un ostacolo.', pt: 'Faço mesmo estando aterrorizado/a. O medo é companheiro, não obstáculo.' }, dimension: 'V' },
      { text: { es: 'Me preparo mejor antes de dar el paso. Quiero hacerlo con más seguridad.', en: 'I prepare better before taking the step. I want to do it with more confidence.', fr: 'Je me prépare mieux avant de passer à l\'acte. Je veux le faire avec plus de sécurité.', de: 'Ich bereite mich besser vor, bevor ich den Schritt mache. Ich will es mit mehr Sicherheit tun.', it: 'Mi preparo meglio prima di fare il passo. Voglio farlo con più sicurezza.', pt: 'Me preparo melhor antes de dar o passo. Quero fazê-lo com mais segurança.' }, dimension: 'P' },
      { text: { es: 'Lo hago ahora mismo. La preparación puede convertirse en otra forma de evasión.', en: 'I do it right now. Preparation can become another form of avoidance.', fr: 'Je le fais maintenant même. La préparation peut devenir une autre forme d\'évasion.', de: 'Ich tue es jetzt. Vorbereitung kann zu einer anderen Form der Ausweichung werden.', it: 'Lo faccio adesso stesso. La preparazione può diventare un\'altra forma di evasione.', pt: 'Faço agora mesmo. A preparação pode se tornar outra forma de evasão.' }, dimension: 'A' },
    ] },
    { id: 7, situation: { es: 'Ves algo injusto pasando frente a ti. Intervenir podría tener costos para ti.', en: 'You see something unfair happening in front of you. Intervening could have costs for you.', fr: 'Tu vois quelque chose d\'injuste se passer devant toi. Intervenir pourrait avoir des coûts pour toi.', de: 'Du siehst etwas Ungerechtes vor dir. Einzugreifen könnte Kosten für dich haben.', it: 'Vedi qualcosa di ingiusto che accade di fronte a te. Intervenire potrebbe avere costi per te.', pt: 'Você vê algo injusto acontecendo na sua frente. Intervir pode ter custos para você.' }, options: [
      { text: { es: 'No intervengo. No quiero meterme en algo que no sé cómo va a terminar.', en: 'I don\'t intervene. I don\'t want to get involved in something I don\'t know how it will end.', fr: 'Je n\'interviens pas. Je ne veux pas me mêler de quelque chose dont je ne sais pas comment ça va finir.', de: 'Ich interveniere nicht. Ich will mich nicht in etwas einmischen, das ich nicht kenne.', it: 'Non intervengo. Non voglio impicciarmi in qualcosa che non so come finirà.', pt: 'Não intervenho. Não quero me meter em algo que não sei como vai terminar.' }, dimension: 'C' },
      { text: { es: 'Intervengo de alguna forma. No puedo quedarme mirando.', en: 'I intervene in some way. I can\'t just stand there watching.', fr: 'J\'interviens d\'une façon ou d\'une autre. Je ne peux pas rester là à regarder.', de: 'Ich greife irgendwie ein. Ich kann nicht einfach zuschauen.', it: 'Intervengo in qualche modo. Non posso stare lì a guardare.', pt: 'Intervenho de alguma forma. Não posso ficar só olhando.' }, dimension: 'V' },
      { text: { es: 'Evalúo si puedo intervenir de forma segura y efectiva.', en: 'I evaluate if I can intervene safely and effectively.', fr: 'J\'évalue si je peux intervenir de façon sûre et effective.', de: 'Ich überlege, ob ich sicher und effektiv eingreifen kann.', it: 'Valuto se posso intervenire in modo sicuro ed efficace.', pt: 'Avalio se posso intervir de forma segura e eficaz.' }, dimension: 'P' },
      { text: { es: 'Intervengo inmediatamente sin calcular consecuencias.', en: 'I intervene immediately without calculating consequences.', fr: 'J\'interviens immédiatement sans calculer les conséquences.', de: 'Ich greife sofort ein, ohne Konsequenzen zu berechnen.', it: 'Intervengo immediatamente senza calcolare le conseguenze.', pt: 'Intervenho imediatamente sem calcular consequências.' }, dimension: 'A' },
    ] },
    { id: 8, situation: { es: 'Tienes una opinión impopular que sabes que es correcta. ¿La dices?', en: 'You have an unpopular opinion you know is correct. Do you say it?', fr: 'Tu as une opinion impopulaire que tu sais être correcte. La dis-tu ?', de: 'Du hast eine unpopuläre Meinung, von der du weißt, dass sie richtig ist. Sagst du sie?', it: 'Hai un\'opinione impopolare che sai essere corretta. La dici?', pt: 'Você tem uma opinião impopular que sabe que é correta. Você a diz?' }, options: [
      { text: { es: 'La guardo. El costo social no vale la pena.', en: 'I keep it to myself. The social cost isn\'t worth it.', fr: 'Je la garde. Le coût social ne vaut pas la peine.', de: 'Ich behalte sie für mich. Der soziale Preis ist es nicht wert.', it: 'La tengo per me. Il costo sociale non vale la pena.', pt: 'A guardo. O custo social não vale a pena.' }, dimension: 'C' },
      { text: { es: 'La digo cuando el contexto lo permite. La verdad vale el costo.', en: 'I say it when context allows. The truth is worth the cost.', fr: 'Je la dis quand le contexte le permet. La vérité vaut le coût.', de: 'Ich sage sie, wenn der Kontext es erlaubt. Die Wahrheit ist den Preis wert.', it: 'La dico quando il contesto lo permette. La verità vale il costo.', pt: 'Digo quando o contexto permite. A verdade vale o custo.' }, dimension: 'V' },
      { text: { es: 'Espero el momento en que sea más receptible.', en: 'I wait for the moment when it\'s more receptive.', fr: 'J\'attends le moment où elle sera plus réceptible.', de: 'Ich warte auf den Moment, in dem sie besser aufgenommen wird.', it: 'Aspetto il momento in cui sarà più ricettibile.', pt: 'Espero o momento em que será mais receptível.' }, dimension: 'P' },
      { text: { es: 'La digo cuando surge. La popularidad no determina la verdad.', en: 'I say it when it comes up. Popularity doesn\'t determine truth.', fr: 'Je la dis quand elle se présente. La popularité ne détermine pas la vérité.', de: 'Ich sage sie, wenn sie aufkommt. Popularität bestimmt nicht die Wahrheit.', it: 'La dico quando emerge. La popolarità non determina la verità.', pt: 'Digo quando surge. A popularidade não determina a verdade.' }, dimension: 'A' },
    ] },
    { id: 9, situation: { es: '¿Cuál es tu relación con el fracaso público?', en: 'What is your relationship with public failure?', fr: 'Quelle est ta relation avec l\'échec public ?', de: 'Wie ist deine Beziehung zum öffentlichen Scheitern?', it: 'Qual è il tuo rapporto con il fallimento pubblico?', pt: 'Qual é sua relação com o fracasso público?' }, options: [
      { text: { es: 'Lo evito. Prefiero no intentar algo si hay riesgo real de fallo visible.', en: 'I avoid it. I prefer not to try something if there\'s real risk of visible failure.', fr: 'Je l\'évite. Je préfère ne pas essayer quelque chose s\'il y a un risque réel d\'échec visible.', de: 'Ich vermeide es. Ich versuche lieber nichts, wenn es ein echtes Risiko sichtbaren Scheiterns gibt.', it: 'Lo evito. Preferisco non tentare qualcosa se c\'è un rischio reale di fallimento visibile.', pt: 'Evito. Prefiro não tentar algo se há risco real de falha visível.' }, dimension: 'C' },
      { text: { es: 'Lo acepto como parte inevitable de hacer cosas que valen la pena.', en: 'I accept it as an inevitable part of doing things that are worth doing.', fr: 'Je l\'accepte comme une partie inévitable de faire des choses qui valent la peine.', de: 'Ich akzeptiere es als unvermeidlichen Teil des Tuns von Dingen, die es wert sind.', it: 'Lo accetto come parte inevitabile del fare cose che valgono la pena.', pt: 'Aceito como parte inevitável de fazer coisas que valem a pena.' }, dimension: 'V' },
      { text: { es: 'Lo minimizo tomando decisiones informadas. El riesgo calculado es diferente al riesgo ciego.', en: 'I minimize it by making informed decisions. Calculated risk is different from blind risk.', fr: 'Je le minimise en prenant des décisions éclairées. Le risque calculé est différent du risque aveugle.', de: 'Ich minimiere es durch fundierte Entscheidungen. Kalkuliertes Risiko ist anders als blindes Risiko.', it: 'Lo minimizo prendendo decisioni informate. Il rischio calcolato è diverso dal rischio cieco.', pt: 'Minimizo tomando decisões informadas. O risco calculado é diferente do risco cego.' }, dimension: 'P' },
      { text: { es: 'Me importa poco. El fracaso es solo información. Nunca un final.', en: 'I don\'t care much. Failure is just information. Never a final.', fr: 'Je m\'en fiche un peu. L\'échec n\'est qu\'une information. Jamais une fin.', de: 'Es ist mir wenig wichtig. Scheitern ist nur Information. Nie ein Ende.', it: 'Mi importa poco. Il fallimento è solo informazione. Mai una fine.', pt: 'Importa-me pouco. O fracasso é apenas informação. Nunca um fim.' }, dimension: 'A' },
    ] },
    { id: 10, situation: { es: 'En cinco años, ¿qué lamentarías más: haber arriesgado y fallado, o no haber arriesgado?', en: 'In five years, what would you regret more: having risked and failed, or not having risked?', fr: 'Dans cinq ans, qu\'est-ce que tu regretterais le plus : avoir risqué et échoué, ou ne pas avoir risqué ?', de: 'In fünf Jahren, was würdest du mehr bereuen: riskiert und gescheitert zu sein, oder nicht riskiert zu haben?', it: 'Tra cinque anni, cosa rimpiangeresti di più: aver rischiato e fallito, o non aver rischiato?', pt: 'Em cinco anos, o que você lamentaria mais: ter arriscado e falhado, ou não ter arriscado?' }, options: [
      { text: { es: 'Prefiero no arriesgar. Los fracasos dejan cicatrices que duran.', en: 'I prefer not to risk. Failures leave scars that last.', fr: 'Je préfère ne pas risquer. Les échecs laissent des cicatrices qui durent.', de: 'Ich ziehe es vor, nicht zu riskieren. Misserfolge hinterlassen Narben, die andauern.', it: 'Preferisco non rischiare. I fallimenti lasciano cicatrici che durano.', pt: 'Prefiro não arriscar. Os fracassos deixam cicatrizes que duram.' }, dimension: 'C' },
      { text: { es: 'Lamentaría no haber arriesgado. El arrepentimiento de lo no vivido es peor.', en: 'I would regret not having risked. The regret of the unlived is worse.', fr: 'Je regretterais de ne pas avoir risqué. Le regret de ce qui n\'a pas été vécu est pire.', de: 'Ich würde bereuen, nicht riskiert zu haben. Die Reue des Nicht-Gelebten ist schlimmer.', it: 'Rimpiangerei di non aver rischiato. Il rimpianto del non vissuto è peggio.', pt: 'Lamentaria não ter arriscado. O arrependimento do não vivido é pior.' }, dimension: 'V' },
      { text: { es: 'Lamentaría los riesgos no calculados. Los fracasos evitables me duelen más.', en: 'I would regret uncalculated risks. Avoidable failures hurt me more.', fr: 'Je regretterais les risques non calculés. Les échecs évitables me font plus mal.', de: 'Ich würde nicht kalkulierte Risiken bereuen. Vermeidbare Misserfolge schmerzen mich mehr.', it: 'Rimpiangerei i rischi non calcolati. I fallimenti evitabili mi fanno più male.', pt: 'Lamentaria os riscos não calculados. Fracassos evitáveis me doem mais.' }, dimension: 'P' },
      { text: { es: 'Nunca lamentaría haber intentado algo. El intento es en sí mismo la victoria.', en: 'I would never regret having tried something. The attempt itself is the victory.', fr: 'Je ne regretterais jamais d\'avoir essayé quelque chose. La tentative est en elle-même la victoire.', de: 'Ich würde es nie bereuen, etwas versucht zu haben. Der Versuch selbst ist der Sieg.', it: 'Non rimpiangerei mai di aver tentato qualcosa. Il tentativo è di per sé la vittoria.', pt: 'Nunca lamentaria ter tentado algo. A tentativa em si é a vitória.' }, dimension: 'A' },
    ] },
  ],
  characters: [
    { name: { es: 'El Cobarde Estratégico', en: 'The Strategic Coward', fr: 'Le Lâche Stratégique', de: 'Der Strategische Feigling', it: 'Il Codardo Strategico', pt: 'O Covarde Estratégico' }, dimensions: ['C'], photo: '/characters/strategic-coward.jpg', description: { es: 'Tiene mil razones para no actuar. Todas suenan razonables.', en: 'Has a thousand reasons for not acting. They all sound reasonable.', fr: 'A mille raisons de ne pas agir. Elles sonnent toutes raisonnables.', de: 'Hat tausend Gründe, nicht zu handeln. Sie klingen alle vernünftig.', it: 'Ha mille ragioni per non agire. Suonano tutte ragionevoli.', pt: 'Tem mil razões para não agir. Todas soam razoáveis.' }, philosophy: { es: 'Siempre hay una razón válida para no actuar ahora. El momento no es el correcto, no estás suficientemente preparado/a, el riesgo es demasiado alto. El problema es que esas razones siempre están disponibles.', en: 'There\'s always a valid reason not to act now. The moment isn\'t right, you\'re not prepared enough, the risk is too high. The problem is those reasons are always available.', fr: 'Il y a toujours une raison valide de ne pas agir maintenant. Le moment n\'est pas le bon, tu n\'es pas suffisamment préparé(e), le risque est trop élevé. Le problème est que ces raisons sont toujours disponibles.', de: 'Es gibt immer einen triftigen Grund, jetzt nicht zu handeln. Der Moment ist nicht der richtige, du bist nicht genug vorbereitet, das Risiko ist zu hoch. Das Problem ist, dass diese Gründe immer verfügbar sind.', it: 'C\'è sempre una ragione valida per non agire ora. Il momento non è quello giusto, non sei abbastanza preparato/a, il rischio è troppo alto. Il problema è che quelle ragioni sono sempre disponibili.', pt: 'Há sempre uma razão válida para não agir agora. O momento não é o certo, você não está suficientemente preparado/a, o risco é muito alto. O problema é que essas razões estão sempre disponíveis.' } },
    { name: { es: 'El Valiente Real', en: 'The Real Brave', fr: 'Le Vrai Courageux', de: 'Der Wirklich Tapfere', it: 'Il Coraggioso Reale', pt: 'O Valente Real' }, dimensions: ['V'], photo: '/characters/real-brave.jpg', description: { es: 'Actúa a pesar del miedo. Eso es todo.', en: 'Acts despite fear. That\'s all.', fr: 'Agit malgré la peur. C\'est tout.', de: 'Handelt trotz Angst. Das ist alles.', it: 'Agisce nonostante la paura. È tutto.', pt: 'Age apesar do medo. É tudo.' }, philosophy: { es: 'No eres valiente porque no tienes miedo — eres valiente porque actúas a pesar de tenerlo. Esa diferencia importa. El coraje no es ausencia de miedo; es la decisión de que lo que importa pesa más que el miedo.', en: 'You\'re not brave because you\'re not afraid — you\'re brave because you act despite being afraid. That difference matters. Courage is not the absence of fear; it\'s the decision that what matters weighs more than fear.', fr: 'Tu n\'es pas courageux/se parce que tu n\'as pas peur — tu es courageux/se parce que tu agis malgré ça. Cette différence compte. Le courage n\'est pas l\'absence de peur; c\'est la décision que ce qui compte pèse plus que la peur.', de: 'Du bist nicht tapfer, weil du keine Angst hast — du bist tapfer, weil du trotzdem handelst. Dieser Unterschied ist wichtig. Mut ist nicht die Abwesenheit von Angst; es ist die Entscheidung, dass das, was wichtig ist, mehr wiegt als Angst.', it: 'Non sei coraggioso/a perché non hai paura — sei coraggioso/a perché agisci nonostante ce l\'hai. Quella differenza conta. Il coraggio non è assenza di paura; è la decisione che ciò che conta pesa più della paura.', pt: 'Você não é valente porque não tem medo — é valente porque age apesar de tê-lo. Essa diferença importa. Coragem não é ausência de medo; é a decisão de que o que importa pesa mais do que o medo.' } },
    { name: { es: 'El Prudente Calculador', en: 'The Calculated Prudent', fr: 'Le Prudent Calculateur', de: 'Der Berechnende Kluge', it: 'Il Prudente Calcolatore', pt: 'O Prudente Calculista' }, dimensions: ['P'], photo: '/characters/calculated-prudent.jpg', description: { es: 'Mide el riesgo antes de actuar. No es cobardía — es estrategia.', en: 'Measures risk before acting. It\'s not cowardice — it\'s strategy.', fr: 'Mesure le risque avant d\'agir. Ce n\'est pas de la lâcheté — c\'est de la stratégie.', de: 'Misst das Risiko, bevor er/sie handelt. Es ist keine Feigheit — es ist Strategie.', it: 'Misura il rischio prima di agire. Non è vigliaccheria — è strategia.', pt: 'Mede o risco antes de agir. Não é covardia — é estratégia.' }, philosophy: { es: 'Para ti, la valentía sin criterio es temeridad. Evalúas cuándo y cómo actuar para maximizar el impacto y minimizar el daño innecesario. La prudencia al servicio de la acción es una forma de coraje.', en: 'For you, bravery without criterion is recklessness. You evaluate when and how to act to maximize impact and minimize unnecessary harm. Prudence in service of action is a form of courage.', fr: 'Pour toi, la bravoure sans critère est de la témérité. Tu évalues quand et comment agir pour maximiser l\'impact et minimiser les dommages inutiles. La prudence au service de l\'action est une forme de courage.', de: 'Für dich ist Tapferkeit ohne Kriterium Leichtsinn. Du bewertest, wann und wie du handelst, um die Wirkung zu maximieren und unnötigen Schaden zu minimieren. Besonnenheit im Dienst der Handlung ist eine Form von Mut.', it: 'Per te, il coraggio senza criterio è temerarietà. Valuti quando e come agire per massimizzare l\'impatto e minimizzare il danno inutile. La prudenza al servizio dell\'azione è una forma di coraggio.', pt: 'Para você, a bravura sem critério é temeridade. Você avalia quando e como agir para maximizar o impacto e minimizar o dano desnecessário. A prudência a serviço da ação é uma forma de coragem.' } },
    { name: { es: 'El Audaz Sin Filtros', en: 'The Unfiltered Audacious', fr: 'L\'Audacieux Sans Filtres', de: 'Der Ungefilttert Kühne', it: 'L\'Audace Senza Filtri', pt: 'O Audacioso Sem Filtros' }, dimensions: ['A'], photo: '/characters/fearless-audacious.jpg', description: { es: 'Actúa primero, piensa después. A veces brillante, a veces un desastre.', en: 'Acts first, thinks later. Sometimes brilliant, sometimes a disaster.', fr: 'Agit d\'abord, pense après. Parfois brillant, parfois un désastre.', de: 'Handelt zuerst, denkt danach. Manchmal brilliant, manchmal eine Katastrophe.', it: 'Agisce prima, pensa dopo. A volte brillante, a volte un disastro.', pt: 'Age primeiro, pensa depois. Às vezes brilhante, às vezes um desastre.' }, philosophy: { es: 'El miedo no llega a convertirse en obstáculo porque tú ya actuaste. Tu audacia crea posibilidades que la precaución nunca generaría. El costo: a veces tu impulso te lleva a lugares que no terminan bien.', en: 'Fear doesn\'t get to become an obstacle because you\'ve already acted. Your audacity creates possibilities that caution would never generate. The cost: sometimes your impulse takes you to places that don\'t end well.', fr: 'La peur n\'arrive pas à devenir un obstacle parce que tu as déjà agi. Ton audace crée des possibilités que la prudence ne générerait jamais. Le coût : parfois ton impulsion te mène à des endroits qui ne finissent pas bien.', de: 'Angst kann kein Hindernis werden, weil du bereits gehandelt hast. Deine Kühnheit schafft Möglichkeiten, die Vorsicht niemals erzeugen würde. Der Preis: manchmal führt dein Impuls dich an Orte, die nicht gut enden.', it: 'La paura non riesce a diventare un ostacolo perché hai già agito. La tua audacia crea possibilità che la prudenza non genererebbe mai. Il costo: a volte il tuo impulso ti porta in luoghi che non finiscono bene.', pt: 'O medo não chega a ser obstáculo porque você já agiu. Sua audácia cria possibilidades que a prudência nunca geraria. O custo: às vezes seu impulso te leva a lugares que não terminam bem.' } },
    { name: { es: 'El Cobarde Consciente', en: 'The Aware Coward', fr: 'Le Lâche Conscient', de: 'Der Bewusste Feigling', it: 'Il Codardo Consapevole', pt: 'O Covarde Consciente' }, dimensions: ['C', 'P'], photo: '/characters/aware-coward.jpg', description: { es: 'Sabe que evita, pero lo racionaliza bien.', en: 'Knows they avoid, but rationalizes it well.', fr: 'Sait qu\'il/elle évite, mais le rationalise bien.', de: 'Weiß, dass er/sie vermeidet, rationalisiert es aber gut.', it: 'Sa che evita, ma lo razionalizza bene.', pt: 'Sabe que evita, mas racionaliza bem.' }, philosophy: { es: 'Eres lo suficientemente honesto/a para reconocer que a veces evitas. La "prudencia" que aplicas a veces es cobardía disfrazada de estrategia. La diferencia entre los dos es más difícil de ver desde adentro.', en: 'You\'re honest enough to recognize that you sometimes avoid. The "prudence" you apply is sometimes cowardice disguised as strategy. The difference between the two is harder to see from the inside.', fr: 'Tu es suffisamment honnête pour reconnaître que tu évites parfois. La "prudence" que tu appliques est parfois de la lâcheté déguisée en stratégie. La différence entre les deux est plus difficile à voir de l\'intérieur.', de: 'Du bist ehrlich genug zu erkennen, dass du manchmal ausweichst. Die "Besonnenheit", die du anwendest, ist manchmal Feigheit, die als Strategie verkleidet ist. Der Unterschied zwischen beiden ist von innen schwerer zu sehen.', it: 'Sei abbastanza onesto/a da riconoscere che a volte eviti. La "prudenza" che applichi è a volte vigliaccheria mascherata da strategia. La differenza tra i due è più difficile da vedere dall\'interno.', pt: 'Você é honesto/a o suficiente para reconhecer que às vezes evita. A "prudência" que aplica às vezes é covardia disfarçada de estratégia. A diferença entre os dois é mais difícil de ver por dentro.' } },
    { name: { es: 'El Valiente Calculado', en: 'The Calculated Brave', fr: 'Le Courageux Calculé', de: 'Der Berechnende Tapfere', it: 'Il Coraggioso Calcolato', pt: 'O Valente Calculista' }, dimensions: ['V', 'P'], photo: '/characters/calculated-brave.jpg', description: { es: 'Actúa con coraje y con criterio. La combinación más efectiva.', en: 'Acts with courage and with criterion. The most effective combination.', fr: 'Agit avec courage et avec critère. La combinaison la plus effective.', de: 'Handelt mit Mut und mit Kriterium. Die effektivste Kombination.', it: 'Agisce con coraggio e con criterio. La combinazione più efficace.', pt: 'Age com coragem e critério. A combinação mais eficaz.' }, philosophy: { es: 'No actúas por impulso ni por miedo. Evalúas y cuando llega el momento, actúas con convicción. Esa combinación de coraje y criterio es la que genera los cambios más duraderos.', en: 'You don\'t act out of impulse or fear. You evaluate and when the moment comes, you act with conviction. That combination of courage and criterion is what generates the most lasting changes.', fr: 'Tu n\'agis pas par impulsion ni par peur. Tu évalues et quand le moment vient, tu agis avec conviction. Cette combinaison de courage et de critère est ce qui génère les changements les plus durables.', de: 'Du handelst nicht aus Impuls oder Angst. Du bewertest und wenn der Moment kommt, handelst du mit Überzeugung. Diese Kombination aus Mut und Kriterium ist das, was die dauerhaftesten Veränderungen erzeugt.', it: 'Non agisci per impulso né per paura. Valuti e quando arriva il momento, agisci con convinzione. Quella combinazione di coraggio e criterio è ciò che genera i cambiamenti più duraturi.', pt: 'Você não age por impulso nem por medo. Avalia e quando chega o momento, age com convicção. Essa combinação de coragem e critério é o que gera as mudanças mais duradouras.' } },
    { name: { es: 'El Impulsivo Valiente', en: 'The Impulsive Brave', fr: 'L\'Impulsif Courageux', de: 'Der Impulsive Tapfere', it: 'L\'Impulsivo Coraggioso', pt: 'O Impulsivo Valente' }, dimensions: ['V', 'A'], photo: '/characters/impulsive-brave.jpg', description: { es: 'Actúa siempre. A veces demasiado rápido.', en: 'Always acts. Sometimes too fast.', fr: 'Agit toujours. Parfois trop vite.', de: 'Handelt immer. Manchmal zu schnell.', it: 'Agisce sempre. A volte troppo velocemente.', pt: 'Age sempre. Às vezes rápido demais.' }, philosophy: { es: 'Tu instinto es actuar, no evitar. Eso genera momentos extraordinarios y también errores costosos. Pero tu tendencia base — hacia el movimiento y no hacia la parálisis — es más valiosa de lo que a veces parece.', en: 'Your instinct is to act, not avoid. That generates extraordinary moments and also costly mistakes. But your base tendency — toward movement and not paralysis — is more valuable than it sometimes seems.', fr: 'Ton instinct est d\'agir, pas d\'éviter. Ça génère des moments extraordinaires et aussi des erreurs coûteuses. Mais ta tendance de base — vers le mouvement et non vers la paralysie — est plus précieuse qu\'il ne semble parfois.', de: 'Dein Instinkt ist zu handeln, nicht zu vermeiden. Das erzeugt außergewöhnliche Momente und auch kostspielige Fehler. Aber deine Grundtendenz — hin zur Bewegung und nicht zur Lähmung — ist wertvoller, als sie manchmal erscheint.', it: 'Il tuo istinto è agire, non evitare. Questo genera momenti straordinari e anche errori costosi. Ma la tua tendenza di base — verso il movimento e non verso la paralisi — è più preziosa di quanto a volte sembri.', pt: 'Seu instinto é agir, não evitar. Isso gera momentos extraordinários e também erros custosos. Mas sua tendência base — em direção ao movimento e não à paralisia — é mais valiosa do que às vezes parece.' } },
    { name: { es: 'El Cobarde en Recuperación', en: 'The Coward in Recovery', fr: 'Le Lâche en Récupération', de: 'Der Feigling in der Genesung', it: 'Il Codardo in Recupero', pt: 'O Covarde em Recuperação' }, dimensions: ['C', 'V'], photo: '/characters/recovering-coward.jpg', description: { es: 'Ha evitado mucho y está aprendiendo a actuar de todas formas.', en: 'Has avoided a lot and is learning to act anyway.', fr: 'A beaucoup évité et apprend à agir quand même.', de: 'Hat viel vermieden und lernt trotzdem zu handeln.', it: 'Ha evitato molto e sta imparando ad agire comunque.', pt: 'Evitou muito e está aprendendo a agir mesmo assim.' }, philosophy: { es: 'Tienes una historia de evitar y estás trabajando en cambiarla. Esa tensión entre tu patrón y tu aspiración es productiva. Cada vez que actúas a pesar del miedo, reprogramas el patrón.', en: 'You have a history of avoiding and you\'re working on changing it. That tension between your pattern and your aspiration is productive. Every time you act despite fear, you reprogram the pattern.', fr: 'Tu as une histoire d\'évitement et tu travailles à la changer. Cette tension entre ton schéma et ton aspiration est productive. Chaque fois que tu agis malgré la peur, tu reprogrammes le schéma.', de: 'Du hast eine Geschichte des Vermeidens und arbeitest daran, sie zu ändern. Diese Spannung zwischen deinem Muster und deiner Aspiration ist produktiv. Jedes Mal, wenn du trotz Angst handelst, programmierst du das Muster um.', it: 'Hai una storia di evitamento e stai lavorando per cambiarla. Quella tensione tra il tuo schema e la tua aspirazione è produttiva. Ogni volta che agisci nonostante la paura, riprogrammi lo schema.', pt: 'Você tem um histórico de evitar e está trabalhando para mudar isso. Essa tensão entre seu padrão e sua aspiração é produtiva. Cada vez que você age apesar do medo, você reprograma o padrão.' } },
  ],
};

export async function seedCoward(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'coward' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'coward',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['lifestyle'],
      sortOrder: 5,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
