import type { PrismaClient } from '../../generated/prisma/client.js';

export async function seedCorrupt(prisma: PrismaClient, catMap: Record<string, string>) {
  const data = {
    slug: 'corrupt',
    title: { es: '¿Qué tan corrupto/a serías en el poder?', en: 'How corrupt would you be in power?', fr: 'À quel point seriez-vous corrompu(e) au pouvoir ?', de: 'Wie korrupt wärst du in einer Machtposition?', it: 'Quanto saresti corrotto/a al potere?', pt: 'Quão corrupto/a você seria no poder?' },
    description: { es: 'El poder no corrompe — revela. ¿Qué revelaría de ti?', en: 'Power doesn\'t corrupt — it reveals. What would it reveal about you?', fr: 'Le pouvoir ne corrompt pas — il révèle. Que révèlerait-il de vous ?', de: 'Macht korrumpiert nicht — sie enthüllt. Was würde sie über dich enthüllen?', it: 'Il potere non corrompe — rivela. Cosa rivelarebbe di te?', pt: 'O poder não corrompe — revela. O que revelaria sobre você?' },
    scenarioLabel: { es: 'Dilema', en: 'Dilemma', fr: 'Dilemme', de: 'Dilemma', it: 'Dilemma', pt: 'Dilema' },
    categoryId: catMap['moral'],
    sortOrder: 4,
    dimensionLabels: {
      es: { C: 'Corrupción', I: 'Integridad', P: 'Pragmatismo', T: 'Transparencia' },
      en: { C: 'Corruption', I: 'Integrity', P: 'Pragmatism', T: 'Transparency' },
      fr: { C: 'Corruption', I: 'Intégrité', P: 'Pragmatisme', T: 'Transparence' },
      de: { C: 'Korruption', I: 'Integrität', P: 'Pragmatismus', T: 'Transparenz' },
      it: { C: 'Corruzione', I: 'Integrità', P: 'Pragmatismo', T: 'Trasparenza' },
      pt: { C: 'Corrupção', I: 'Integridade', P: 'Pragmatismo', T: 'Transparência' },
    },
    questions: [
      {
        id: 1,
        situation: { es: 'Eres funcionario y puedes adjudicar un contrato a una empresa de tu familia que tiene una propuesta ligeramente inferior a la del competidor.', en: 'You are a public official and can award a contract to your family\'s company, which has a slightly weaker proposal than the competitor\'s.', fr: 'Vous êtes fonctionnaire et pouvez attribuer un contrat à l\'entreprise de votre famille, dont la proposition est légèrement inférieure à celle du concurrent.', de: 'Du bist Beamter und kannst einen Auftrag an das Unternehmen deiner Familie vergeben, das ein leicht schwächeres Angebot hat als der Mitbewerber.', it: 'Sei un funzionario e puoi aggiudicare un contratto all\'azienda della tua famiglia, che ha un\'offerta leggermente inferiore a quella del concorrente.', pt: 'Você é funcionário e pode adjudicar um contrato à empresa da sua família, que tem uma proposta ligeiramente inferior à do concorrente.' },
        options: [
          { text: { es: 'Lo adjudico a la de mi familia. La diferencia es pequeña y es mi familia.', en: 'I award it to my family\'s company. The difference is small and family comes first.', fr: 'Je l\'attribue à l\'entreprise de ma famille. La différence est minime et c\'est ma famille.', de: 'Ich vergebe es an das Unternehmen meiner Familie. Der Unterschied ist gering und es ist meine Familie.', it: 'Lo aggiudico all\'azienda di famiglia. La differenza è piccola ed è la mia famiglia.', pt: 'Adjudico à empresa da minha família. A diferença é pequena e é minha família.' }, dimension: 'C' },
          { text: { es: 'No puedo. Lo recuso y dejo que otro decida para no tener conflicto de interés.', en: 'I can\'t. I recuse myself and let someone else decide to avoid a conflict of interest.', fr: 'Je ne peux pas. Je me récuse et laisse quelqu\'un d\'autre décider pour éviter tout conflit d\'intérêts.', de: 'Ich kann nicht. Ich lehne ab und überlasse die Entscheidung jemand anderem, um keinen Interessenkonflikt zu haben.', it: 'Non posso. Mi ricuso e lascio che qualcun altro decida per evitare conflitti di interesse.', pt: 'Não posso. Recuso-me e deixo que outra pessoa decida para não ter conflito de interesses.' }, dimension: 'I' },
          { text: { es: 'Adjudico al mejor candidato. Si es la empresa de mi familia, genial.', en: 'I award it to the best candidate. If that happens to be my family\'s company, great.', fr: 'J\'attribue au meilleur candidat. Si c\'est l\'entreprise de ma famille, tant mieux.', de: 'Ich vergebe es an den besten Kandidaten. Wenn das die Firma meiner Familie ist, umso besser.', it: 'Aggiudico al miglior candidato. Se è l\'azienda di famiglia, tanto meglio.', pt: 'Adjudico ao melhor candidato. Se for a empresa da minha família, ótimo.' }, dimension: 'P' },
          { text: { es: 'Lo hago público: anuncio el conflicto de interés y tomo la decisión más justificable.', en: 'I make it public: I disclose the conflict of interest and take the most defensible decision.', fr: 'Je le rends public : j\'annonce le conflit d\'intérêts et prends la décision la plus justifiable.', de: 'Ich mache es öffentlich: Ich gebe den Interessenkonflikt bekannt und treffe die am besten vertretbare Entscheidung.', it: 'Lo rendo pubblico: dichiaro il conflitto di interessi e prendo la decisione più giustificabile.', pt: 'Torno público: anuncio o conflito de interesses e tomo a decisão mais justificável.' }, dimension: 'T' },
        ],
      },
      {
        id: 2,
        situation: { es: 'Como jefe/a, puedes contratar a un amigo poco calificado o a un candidato desconocido muy superior.', en: 'As a manager, you can hire an underqualified friend or an unknown but far more capable candidate.', fr: 'En tant que responsable, vous pouvez embaucher un ami peu qualifié ou un candidat inconnu bien supérieur.', de: 'Als Vorgesetzte/r kannst du einen wenig qualifizierten Freund oder einen unbekannten, weit überlegenen Kandidaten einstellen.', it: 'Come responsabile, puoi assumere un amico poco qualificato o un candidato sconosciuto molto più capace.', pt: 'Como chefe, você pode contratar um amigo pouco qualificado ou um candidato desconhecido muito superior.' },
        options: [
          { text: { es: 'Contrato al amigo. La lealtad tiene valor y lo puedo desarrollar.', en: 'I hire my friend. Loyalty has value and I can develop them.', fr: 'J\'embauche mon ami. La loyauté a de la valeur et je peux le faire progresser.', de: 'Ich stelle meinen Freund ein. Loyalität hat ihren Wert und ich kann ihn weiterentwickeln.', it: 'Assumo l\'amico. La lealtà ha valore e posso svilupparlo.', pt: 'Contrato o amigo. A lealdade tem valor e posso desenvolvê-lo.' }, dimension: 'C' },
          { text: { es: 'Contrato al mejor candidato. La amistad no puede comprar un puesto.', en: 'I hire the best candidate. Friendship can\'t buy a position.', fr: 'J\'embauche le meilleur candidat. L\'amitié ne peut pas acheter un poste.', de: 'Ich stelle den besten Kandidaten ein. Freundschaft kann keine Stelle kaufen.', it: 'Assumo il miglior candidato. L\'amicizia non può comprare una posizione.', pt: 'Contrato o melhor candidato. A amizade não pode comprar um cargo.' }, dimension: 'I' },
          { text: { es: 'Contrato al mejor candidato. La empresa lo necesita y es lo más sostenible.', en: 'I hire the best candidate. The company needs it and it\'s the most sustainable choice.', fr: 'J\'embauche le meilleur candidat. L\'entreprise en a besoin et c\'est la décision la plus viable.', de: 'Ich stelle den besten Kandidaten ein. Das Unternehmen braucht es und es ist die nachhaltigste Entscheidung.', it: 'Assumo il miglior candidato. L\'azienda ne ha bisogno ed è la scelta più sostenibile.', pt: 'Contrato o melhor candidato. A empresa precisa disso e é a decisão mais sustentável.' }, dimension: 'P' },
          { text: { es: 'Hago el proceso transparente para que sea evidente quién es mejor.', en: 'I make the process transparent so it\'s clear who the better candidate is.', fr: 'Je rends le processus transparent pour qu\'il soit évident qui est le meilleur.', de: 'Ich mache den Prozess transparent, damit klar erkennbar ist, wer der bessere Kandidat ist.', it: 'Rendo il processo trasparente in modo che sia evidente chi è il migliore.', pt: 'Torno o processo transparente para que seja evidente quem é o melhor.' }, dimension: 'T' },
        ],
      },
      {
        id: 3,
        situation: { es: 'Tienes acceso a información privilegiada que, si la usas, te generaría una ganancia enorme sin que nadie lo sepa.', en: 'You have access to insider information that, if used, would generate a huge gain and nobody would know.', fr: 'Vous avez accès à des informations privilégiées qui, si vous les utilisez, vous rapporteraient un gain énorme sans que personne ne le sache.', de: 'Du hast Zugang zu Insider-Informationen, die dir, wenn du sie nutzt, einen enormen Gewinn einbringen würden, ohne dass es jemand erfährt.', it: 'Hai accesso a informazioni privilegiate che, se usate, ti genererebbero un enorme guadagno senza che nessuno lo sappia.', pt: 'Você tem acesso a informações privilegiadas que, se usadas, gerariam um enorme ganho sem que ninguém soubesse.' },
        options: [
          { text: { es: 'La uso. Si nadie se entera, el daño es abstracto.', en: 'I use it. If nobody finds out, the harm is abstract.', fr: 'Je l\'utilise. Si personne ne le sait, le préjudice est abstrait.', de: 'Ich nutze sie. Wenn niemand es erfährt, ist der Schaden abstrakt.', it: 'La uso. Se nessuno lo viene a sapere, il danno è astratto.', pt: 'Uso. Se ninguém ficar sabendo, o dano é abstrato.' }, dimension: 'C' },
          { text: { es: 'No la uso. Es ilegal e inmoral, independientemente de si se descubre.', en: 'I don\'t use it. It\'s illegal and immoral, regardless of whether it\'s discovered.', fr: 'Je ne l\'utilise pas. C\'est illégal et immoral, qu\'on le découvre ou non.', de: 'Ich nutze sie nicht. Es ist illegal und unmoralisch, egal ob es entdeckt wird.', it: 'Non la uso. È illegale e immorale, indipendentemente dal fatto che venga scoperto.', pt: 'Não uso. É ilegal e imoral, independentemente de ser descoberto.' }, dimension: 'I' },
          { text: { es: 'Evalúo el riesgo real. Si el riesgo es muy alto, no lo hago.', en: 'I assess the real risk. If the risk is too high, I don\'t do it.', fr: 'J\'évalue le risque réel. Si le risque est trop élevé, je ne le fais pas.', de: 'Ich bewerte das tatsächliche Risiko. Wenn das Risiko zu hoch ist, tue ich es nicht.', it: 'Valuto il rischio reale. Se il rischio è troppo alto, non lo faccio.', pt: 'Avalio o risco real. Se o risco for muito alto, não faço.' }, dimension: 'P' },
          { text: { es: 'No la uso y además alerto sobre la existencia de esa información privilegiada.', en: 'I don\'t use it and I also alert others to the existence of that insider information.', fr: 'Je ne l\'utilise pas et j\'alerte également sur l\'existence de ces informations privilégiées.', de: 'Ich nutze sie nicht und weise außerdem auf die Existenz dieser Insider-Informationen hin.', it: 'Non la uso e segnalo anche l\'esistenza di quell\'informazione privilegiata.', pt: 'Não uso e também alerto sobre a existência dessa informação privilegiada.' }, dimension: 'T' },
        ],
      },
      {
        id: 4,
        situation: { es: 'Puedes aceptar un regalo costoso de un proveedor con quien necesitas mantener buena relación.', en: 'You can accept an expensive gift from a supplier with whom you need to maintain a good relationship.', fr: 'Vous pouvez accepter un cadeau coûteux d\'un fournisseur avec lequel vous devez entretenir de bonnes relations.', de: 'Du kannst ein teures Geschenk von einem Lieferanten annehmen, mit dem du gute Beziehungen pflegen musst.', it: 'Puoi accettare un regalo costoso da un fornitore con cui devi mantenere buoni rapporti.', pt: 'Você pode aceitar um presente caro de um fornecedor com quem precisa manter um bom relacionamento.' },
        options: [
          { text: { es: 'Lo acepto. Es un gesto de buena voluntad y no cambia mis decisiones... mucho.', en: 'I accept it. It\'s a goodwill gesture and it won\'t change my decisions... much.', fr: 'Je l\'accepte. C\'est un geste de bonne volonté et ça ne changera pas mes décisions... vraiment.', de: 'Ich nehme es an. Es ist eine Geste des guten Willens und wird meine Entscheidungen nicht wirklich ändern.', it: 'Lo accetto. È un gesto di buona volontà e non cambierà le mie decisioni... molto.', pt: 'Aceito. É um gesto de boa vontade e não mudará minhas decisões... muito.' }, dimension: 'C' },
          { text: { es: 'No lo acepto. Cualquier regalo de proveedores es potencialmente una deuda implícita.', en: 'I don\'t accept it. Any gift from suppliers is potentially an implicit debt.', fr: 'Je ne l\'accepte pas. Tout cadeau d\'un fournisseur est potentiellement une dette implicite.', de: 'Ich nehme es nicht an. Jedes Geschenk von Lieferanten ist potenziell eine implizite Schuld.', it: 'Non lo accetto. Qualsiasi regalo da fornitori è potenzialmente un debito implicito.', pt: 'Não aceito. Qualquer presente de fornecedores é potencialmente uma dívida implícita.' }, dimension: 'I' },
          { text: { es: 'Lo acepto pero me aseguro de que no afecte mis decisiones futuras.', en: 'I accept it but make sure it doesn\'t influence my future decisions.', fr: 'Je l\'accepte mais je m\'assure que ça n\'influence pas mes décisions futures.', de: 'Ich nehme es an, achte aber darauf, dass es meine zukünftigen Entscheidungen nicht beeinflusst.', it: 'Lo accetto ma mi assicuro che non influenzi le mie decisioni future.', pt: 'Aceito, mas me certifico de que não influencie minhas decisões futuras.' }, dimension: 'P' },
          { text: { es: 'Lo declaro. Si hay política de empresa sobre esto, la sigo. Si no, la creo.', en: 'I declare it. If there\'s a company policy on this, I follow it. If not, I create one.', fr: 'Je le déclare. S\'il existe une politique d\'entreprise à ce sujet, je la suis. Sinon, je la crée.', de: 'Ich deklariere es. Wenn es eine Unternehmensrichtlinie dazu gibt, halte ich mich daran. Wenn nicht, erstelle ich eine.', it: 'Lo dichiaro. Se esiste una politica aziendale in merito, la seguo. In caso contrario, la creo.', pt: 'Declaro. Se houver uma política da empresa sobre isso, a sigo. Se não houver, a crio.' }, dimension: 'T' },
        ],
      },
      {
        id: 5,
        situation: { es: 'Eres auditor y encuentras una irregularidad menor en los registros de una empresa dirigida por un amigo.', en: 'You\'re an auditor and find a minor irregularity in the records of a company run by a friend.', fr: 'Vous êtes auditeur et trouvez une irrégularité mineure dans les registres d\'une entreprise dirigée par un ami.', de: 'Du bist Prüfer und findest eine geringfügige Unregelmäßigkeit in den Unterlagen eines Unternehmens, das von einem Freund geleitet wird.', it: 'Sei un revisore e trovi una piccola irregolarità nei registri di un\'azienda gestita da un amico.', pt: 'Você é auditor e encontra uma irregularidade menor nos registros de uma empresa dirigida por um amigo.' },
        options: [
          { text: { es: 'La paso por alto. No vale la pena destruir una relación por algo menor.', en: 'I overlook it. It\'s not worth ruining a relationship over something minor.', fr: 'Je passe outre. Ça ne vaut pas la peine de détruire une relation pour si peu.', de: 'Ich sehe darüber hinweg. Es ist nicht wert, eine Beziehung wegen einer Kleinigkeit zu zerstören.', it: 'La ignoro. Non vale la pena rovinare un rapporto per qualcosa di minore.', pt: 'Ignoro. Não vale a pena destruir uma relação por algo menor.' }, dimension: 'C' },
          { text: { es: 'La documento y reporto. La función de auditor exige imparcialidad total.', en: 'I document and report it. The auditor\'s role demands complete impartiality.', fr: 'Je la documente et la signale. La fonction d\'auditeur exige une totale impartialité.', de: 'Ich dokumentiere und melde es. Die Aufgabe eines Prüfers erfordert vollständige Unparteilichkeit.', it: 'La documento e la segnalo. Il ruolo di revisore richiede totale imparzialità.', pt: 'Documento e reporto. A função de auditor exige total imparcialidade.' }, dimension: 'I' },
          { text: { es: 'Hablo primero con mi amigo para que lo corrija antes de que sea un problema mayor.', en: 'I talk to my friend first so they can fix it before it becomes a bigger issue.', fr: 'Je parle d\'abord à mon ami pour qu\'il corrige cela avant que ça ne devienne un problème majeur.', de: 'Ich spreche zuerst mit meinem Freund, damit er es korrigieren kann, bevor es zu einem größeren Problem wird.', it: 'Parlo prima con il mio amico perché possa correggerlo prima che diventi un problema maggiore.', pt: 'Falo primeiro com meu amigo para que ele corrija antes que se torne um problema maior.' }, dimension: 'P' },
          { text: { es: 'La reporto y se lo comunico a mi amigo al mismo tiempo. Sin sorpresas.', en: 'I report it and tell my friend at the same time. No surprises.', fr: 'Je la signale et en informe mon ami en même temps. Sans surprises.', de: 'Ich melde es und informiere gleichzeitig meinen Freund. Keine Überraschungen.', it: 'La segnalo e lo comunico al mio amico allo stesso tempo. Nessuna sorpresa.', pt: 'Reporto e comunico ao meu amigo ao mesmo tempo. Sem surpresas.' }, dimension: 'T' },
        ],
      },
      {
        id: 6,
        situation: { es: 'Como político, puedes desviar fondos menores a un proyecto de tu comunidad que realmente necesita ayuda pero no califica oficialmente.', en: 'As a politician, you can divert minor funds to a community project that genuinely needs help but doesn\'t officially qualify.', fr: 'En tant que politique, vous pouvez détourner de petits fonds vers un projet communautaire qui en a vraiment besoin mais ne remplit pas officiellement les critères.', de: 'Als Politiker kannst du kleinere Mittel in ein Gemeinschaftsprojekt umleiten, das wirklich Hilfe braucht, aber offiziell nicht qualifiziert.', it: 'Come politico, puoi dirottare fondi minori verso un progetto della tua comunità che ha davvero bisogno di aiuto ma non rientra nei criteri ufficiali.', pt: 'Como político, você pode desviar fundos menores para um projeto da sua comunidade que realmente precisa de ajuda, mas não se qualifica oficialmente.' },
        options: [
          { text: { es: 'Lo hago. El bien que genero compensa la irregularidad formal.', en: 'I do it. The good I generate compensates for the formal irregularity.', fr: 'Je le fais. Le bien que je génère compense l\'irrégularité formelle.', de: 'Ich tue es. Das Gute, das ich bewirke, wiegt die formale Unregelmäßigkeit auf.', it: 'Lo faccio. Il bene che genero compensa l\'irregolarità formale.', pt: 'Faço. O bem que gero compensa a irregularidade formal.' }, dimension: 'C' },
          { text: { es: 'No lo hago. Si todos usan esa lógica, los sistemas de control no sirven para nada.', en: 'I don\'t do it. If everyone uses that logic, control systems become meaningless.', fr: 'Je ne le fais pas. Si tout le monde utilise cette logique, les systèmes de contrôle ne servent à rien.', de: 'Ich tue es nicht. Wenn alle diese Logik verwenden, sind Kontrollsysteme für nichts zu gebrauchen.', it: 'Non lo faccio. Se tutti usano questa logica, i sistemi di controllo non servono a nulla.', pt: 'Não faço. Se todos usam essa lógica, os sistemas de controle não servem para nada.' }, dimension: 'I' },
          { text: { es: 'Busco la forma legal de obtener esos fondos aunque tome más tiempo.', en: 'I look for the legal way to obtain those funds even if it takes more time.', fr: 'Je cherche le moyen légal d\'obtenir ces fonds, même si ça prend plus de temps.', de: 'Ich suche den legalen Weg, diese Mittel zu erhalten, auch wenn es länger dauert.', it: 'Cerco il modo legale per ottenere quei fondi anche se richiede più tempo.', pt: 'Busco a forma legal de obter esses fundos, mesmo que leve mais tempo.' }, dimension: 'P' },
          { text: { es: 'Lo planteo públicamente como un problema que necesita solución normativa.', en: 'I raise it publicly as a problem that needs a regulatory solution.', fr: 'Je le soulève publiquement comme un problème nécessitant une solution réglementaire.', de: 'Ich bringe es öffentlich als Problem zur Sprache, das einer normativen Lösung bedarf.', it: 'Lo propongo pubblicamente come un problema che necessita di una soluzione normativa.', pt: 'Levanto publicamente como um problema que precisa de solução normativa.' }, dimension: 'T' },
        ],
      },
      {
        id: 7,
        situation: { es: 'Sabes que un colega hace pequeñas irregularidades. Si lo reportas, probablemente lo despidan y tiene hijos.', en: 'You know a colleague commits minor irregularities. If you report it, they\'ll likely be fired and they have children.', fr: 'Vous savez qu\'un collègue commet de petites irrégularités. Si vous le signalez, il sera probablement licencié et il a des enfants.', de: 'Du weißt, dass ein Kollege kleinere Unregelmäßigkeiten begeht. Wenn du es meldest, wird er wahrscheinlich entlassen und er hat Kinder.', it: 'Sai che un collega commette piccole irregolarità. Se lo segnali, probabilmente verrà licenziato e ha figli.', pt: 'Você sabe que um colega comete pequenas irregularidades. Se reportar, provavelmente será demitido e tem filhos.' },
        options: [
          { text: { es: 'No lo reporto. Las consecuencias para su familia son demasiado graves.', en: 'I don\'t report it. The consequences for his family are too severe.', fr: 'Je ne le signale pas. Les conséquences pour sa famille sont trop graves.', de: 'Ich melde es nicht. Die Konsequenzen für seine Familie sind zu schwerwiegend.', it: 'Non lo segnalo. Le conseguenze per la sua famiglia sono troppo gravi.', pt: 'Não reporto. As consequências para a família dele são graves demais.' }, dimension: 'C' },
          { text: { es: 'Lo reporto. Las consecuencias son de sus propias decisiones, no mías.', en: 'I report it. The consequences follow from his own decisions, not mine.', fr: 'Je le signale. Les conséquences découlent de ses propres décisions, pas des miennes.', de: 'Ich melde es. Die Konsequenzen folgen aus seinen eigenen Entscheidungen, nicht meinen.', it: 'Lo segnalo. Le conseguenze derivano dalle sue decisioni, non dalle mie.', pt: 'Reporto. As consequências são das próprias decisões dele, não das minhas.' }, dimension: 'I' },
          { text: { es: 'Lo hablo con él primero y le doy la oportunidad de corregirlo.', en: 'I talk to him first and give him the chance to correct it.', fr: 'Je lui en parle d\'abord et lui donne l\'occasion de corriger cela.', de: 'Ich spreche zuerst mit ihm und gebe ihm die Chance, es zu korrigieren.', it: 'Gli parlo prima e gli do la possibilità di correggerlo.', pt: 'Falo com ele primeiro e dou a oportunidade de corrigir.' }, dimension: 'P' },
          { text: { es: 'Lo reporto y al mismo tiempo busco que el proceso considere las circunstancias atenuantes.', en: 'I report it and at the same time advocate for the process to consider mitigating circumstances.', fr: 'Je le signale et cherche en même temps à ce que le processus prenne en compte les circonstances atténuantes.', de: 'Ich melde es und setze mich gleichzeitig dafür ein, dass das Verfahren die mildernden Umstände berücksichtigt.', it: 'Lo segnalo e allo stesso tempo cerco che il processo consideri le circostanze attenuanti.', pt: 'Reporto e ao mesmo tempo busco que o processo considere as circunstâncias atenuantes.' }, dimension: 'T' },
        ],
      },
      {
        id: 8,
        situation: { es: 'Puedes inflar levemente tu currículum en un área difícil de verificar para conseguir un trabajo que sí podrías hacer.', en: 'You can slightly inflate your résumé in an area that\'s hard to verify to get a job you could actually do.', fr: 'Vous pouvez légèrement gonfler votre CV dans un domaine difficile à vérifier pour obtenir un emploi que vous pourriez réellement exercer.', de: 'Du kannst deinen Lebenslauf in einem schwer zu überprüfenden Bereich leicht aufbauschen, um einen Job zu bekommen, den du tatsächlich machen könntest.', it: 'Puoi gonfiare leggermente il tuo curriculum in un\'area difficile da verificare per ottenere un lavoro che potresti davvero svolgere.', pt: 'Você pode inflar levemente seu currículo em uma área difícil de verificar para conseguir um emprego que você realmente poderia fazer.' },
        options: [
          { text: { es: 'Lo hago. Me arriesgo. Ya demostraré mis capacidades dentro.', en: 'I do it. I\'ll take the risk. I\'ll prove my abilities once I\'m in.', fr: 'Je le fais. Je prends le risque. Je prouverai mes capacités une fois en poste.', de: 'Ich tue es. Ich riskiere es. Ich werde meine Fähigkeiten dann unter Beweis stellen.', it: 'Lo faccio. Mi rischio. Dimostrerò le mie capacità una volta dentro.', pt: 'Faço. Vou me arriscar. Depois demonstrarei minhas capacidades.' }, dimension: 'C' },
          { text: { es: 'No lo hago. Si me contratan bajo una falsa premisa, el inicio está viciado.', en: 'I don\'t. If I\'m hired under a false premise, the start is tainted.', fr: 'Je ne le fais pas. Si je suis embauché sous une fausse prémisse, le début est vicié.', de: 'Ich tue es nicht. Wenn ich unter einer falschen Voraussetzung eingestellt werde, ist der Beginn vergiftet.', it: 'Non lo faccio. Se vengo assunto sotto una falsa premessa, l\'inizio è viziato.', pt: 'Não faço. Se me contratarem com uma premissa falsa, o início já está comprometido.' }, dimension: 'I' },
          { text: { es: 'Evalúo si podría cumplir lo que exagero. Si sí, el riesgo es menor.', en: 'I assess whether I could deliver what I\'m exaggerating. If yes, the risk is lower.', fr: 'J\'évalue si je pourrais tenir ce que j\'exagère. Si oui, le risque est moindre.', de: 'Ich bewerte, ob ich das Übertriebene liefern könnte. Wenn ja, ist das Risiko geringer.', it: 'Valuto se riuscirei a fare ciò che sto esagerando. Se sì, il rischio è minore.', pt: 'Avalio se conseguiria cumprir o que estou exagerando. Se sim, o risco é menor.' }, dimension: 'P' },
          { text: { es: 'No lo hago. Pero soy directo sobre mis capacidades reales y mi potencial de aprendizaje.', en: 'I don\'t. But I\'m direct about my real capabilities and my learning potential.', fr: 'Je ne le fais pas. Mais je suis direct sur mes capacités réelles et mon potentiel d\'apprentissage.', de: 'Ich tue es nicht. Aber ich bin direkt über meine tatsächlichen Fähigkeiten und mein Lernpotenzial.', it: 'Non lo faccio. Ma sono diretto sulle mie capacità reali e sul mio potenziale di apprendimento.', pt: 'Não faço. Mas sou direto sobre minhas capacidades reais e meu potencial de aprendizado.' }, dimension: 'T' },
        ],
      },
      {
        id: 9,
        situation: { es: 'En un proceso de licitación, alguien te ofrece un soborno para favorecer a su empresa.', en: 'During a bidding process, someone offers you a bribe to favor their company.', fr: 'Dans le cadre d\'un appel d\'offres, quelqu\'un vous propose un pot-de-vin pour favoriser son entreprise.', de: 'In einem Ausschreibungsverfahren bietet dir jemand eine Bestechung an, um sein Unternehmen zu bevorzugen.', it: 'Nel corso di una gara d\'appalto, qualcuno ti offre una bustarella per favorire la sua azienda.', pt: 'Em um processo licitatório, alguém te oferece suborno para favorecer a empresa dele.' },
        options: [
          { text: { es: 'Depende del monto y del riesgo. Si es suficiente y seguro, lo evalúo.', en: 'It depends on the amount and risk. If it\'s enough and safe, I consider it.', fr: 'Ça dépend du montant et du risque. Si c\'est suffisant et sûr, j\'y réfléchis.', de: 'Es hängt von Betrag und Risiko ab. Wenn es genug und sicher ist, überlege ich es mir.', it: 'Dipende dall\'importo e dal rischio. Se è sufficiente e sicuro, lo valuto.', pt: 'Depende do valor e do risco. Se for suficiente e seguro, avalio.' }, dimension: 'C' },
          { text: { es: 'Lo rechazo inmediatamente y lo reporto.', en: 'I reject it immediately and report it.', fr: 'Je le refuse immédiatement et le signale.', de: 'Ich lehne es sofort ab und erstatzte Anzeige.', it: 'Lo rifiuto immediatamente e lo segnalo.', pt: 'Recuso imediatamente e reporto.' }, dimension: 'I' },
          { text: { es: 'Lo rechazo. El riesgo legal y reputacional no vale ningún beneficio.', en: 'I reject it. The legal and reputational risk isn\'t worth any benefit.', fr: 'Je le refuse. Le risque légal et de réputation ne vaut aucun avantage.', de: 'Ich lehne es ab. Das rechtliche und Reputationsrisiko ist keinen Vorteil wert.', it: 'Lo rifiuto. Il rischio legale e reputazionale non vale nessun vantaggio.', pt: 'Recuso. O risco legal e reputacional não vale nenhum benefício.' }, dimension: 'P' },
          { text: { es: 'Lo rechazo, lo reporto y hago el proceso lo más transparente posible.', en: 'I reject it, report it, and make the process as transparent as possible.', fr: 'Je le refuse, le signale et rends le processus aussi transparent que possible.', de: 'Ich lehne es ab, melde es und mache den Prozess so transparent wie möglich.', it: 'Lo rifiuto, lo segnalo e rendo il processo il più trasparente possibile.', pt: 'Recuso, reporto e torno o processo o mais transparente possível.' }, dimension: 'T' },
        ],
      },
      {
        id: 10,
        situation: { es: 'Tienes acceso a beneficios de la empresa que técnicamente no te corresponden pero nadie los usa.', en: 'You have access to company perks that technically don\'t belong to you but nobody uses them.', fr: 'Vous avez accès à des avantages d\'entreprise qui ne vous appartiennent techniquement pas, mais que personne n\'utilise.', de: 'Du hast Zugang zu Unternehmensvorteilen, die dir technisch gesehen nicht zustehen, aber niemand nutzt sie.', it: 'Hai accesso a benefit aziendali che tecnicamente non ti spettano, ma nessuno li usa.', pt: 'Você tem acesso a benefícios da empresa que tecnicamente não lhe cabem, mas ninguém os usa.' },
        options: [
          { text: { es: 'Los uso. Si nadie los usa, no hago daño a nadie.', en: 'I use them. If nobody uses them, I\'m not hurting anyone.', fr: 'Je les utilise. Si personne ne les utilise, je ne fais de mal à personne.', de: 'Ich nutze sie. Wenn niemand sie nutzt, schadet es niemandem.', it: 'Li uso. Se nessuno li usa, non faccio del male a nessuno.', pt: 'Uso. Se ninguém usa, não estou prejudicando ninguém.' }, dimension: 'C' },
          { text: { es: 'No los uso si no me corresponden. El principio vale aunque nadie lo vea.', en: 'I don\'t use them if they\'re not mine. The principle counts even if no one is watching.', fr: 'Je ne les utilise pas s\'ils ne me reviennent pas. Le principe vaut même si personne ne regarde.', de: 'Ich nutze sie nicht, wenn sie mir nicht zustehen. Das Prinzip gilt, auch wenn niemand zuschaut.', it: 'Non li uso se non mi spettano. Il principio vale anche se nessuno lo vede.', pt: 'Não uso se não me cabem. O princípio vale mesmo que ninguém veja.' }, dimension: 'I' },
          { text: { es: 'Los uso discretamente si realmente no afecta a nadie.', en: 'I use them discreetly if it really doesn\'t affect anyone.', fr: 'Je les utilise discrètement si ça n\'affecte vraiment personne.', de: 'Ich nutze sie diskret, wenn es wirklich niemandem schadet.', it: 'Li uso discretamente se davvero non influisce su nessuno.', pt: 'Uso discretamente se realmente não afeta ninguém.' }, dimension: 'P' },
          { text: { es: 'Los señalo como un problema de política interna que debería regularse.', en: 'I flag them as an internal policy issue that should be regulated.', fr: 'Je les signale comme un problème de politique interne qui devrait être réglementé.', de: 'Ich weise darauf hin als internes Richtlinienproblem, das reguliert werden sollte.', it: 'Li segnalo come un problema di politica interna che dovrebbe essere regolamentato.', pt: 'Aponto como um problema de política interna que deveria ser regulamentado.' }, dimension: 'T' },
        ],
      },
    ],
    characters: [
      { name: { es: 'El Corrupto Pragmático', en: 'The Pragmatic Corrupt', fr: 'Le Corrompu Pragmatique', de: 'Der Pragmatische Korrupte', it: 'Il Corrotto Pragmatico', pt: 'O Corrupto Pragmático' }, dimensions: ['C'], photo: '/characters/corrupt-pragmatic.jpg', description: { es: 'Justifica cada desvío con una razón que suena razonable.', en: 'Justifies every deviation with a reason that sounds reasonable.', fr: 'Justifie chaque écart par une raison qui semble raisonnable.', de: 'Rechtfertigt jede Abweichung mit einem vernünftig klingenden Grund.', it: 'Giustifica ogni deviazione con una ragione che sembra ragionevole.', pt: 'Justifica cada desvio com uma razão que parece razoável.' }, philosophy: { es: 'Para ti, las reglas son guías, no absolutos. Cuando la situación lo "justifica", te permites desviaciones. El problema es que esa puerta nunca se cierra — siempre hay una razón para la siguiente excepción.', en: 'For you, rules are guidelines, not absolutes. When the situation "justifies" it, you allow yourself deviations. The problem is that door never closes — there\'s always a reason for the next exception.', fr: 'Pour vous, les règles sont des guides, pas des absolus. Quand la situation le "justifie", vous vous permettez des écarts. Le problème, c\'est que cette porte ne se ferme jamais — il y a toujours une raison pour la prochaine exception.', de: 'Für dich sind Regeln Richtlinien, keine Absoluta. Wenn die Situation es "rechtfertigt", erlaubst du dir Abweichungen. Das Problem ist, dass diese Tür sich nie schließt — es gibt immer einen Grund für die nächste Ausnahme.', it: 'Per te le regole sono guide, non assoluti. Quando la situazione lo "giustifica", ti permetti deviazioni. Il problema è che quella porta non si chiude mai — c\'è sempre una ragione per la prossima eccezione.', pt: 'Para você, as regras são guias, não absolutos. Quando a situação "justifica", você se permite desvios. O problema é que essa porta nunca fecha — sempre há uma razão para a próxima exceção.' } },
      { name: { es: 'El Íntegro Absoluto', en: 'The Absolute Integrity', fr: 'L\'Intègre Absolu', de: 'Die Absolute Integrität', it: 'L\'Integro Assoluto', pt: 'O Íntegro Absoluto' }, dimensions: ['I'], photo: '/characters/absolute-integrity.jpg', description: { es: 'Los principios no se doblan. Nunca.', en: 'Principles don\'t bend. Ever.', fr: 'Les principes ne fléchissent pas. Jamais.', de: 'Prinzipien biegen sich nicht. Niemals.', it: 'I principi non si piegano. Mai.', pt: 'Os princípios não se dobram. Nunca.' }, philosophy: { es: 'Para ti, la integridad no es negociable. No importa el beneficio, no importa las consecuencias para otros, no importa si nadie va a enterarse. Las reglas existen por una razón y tú las respetas.', en: 'For you, integrity is non-negotiable. It doesn\'t matter the benefit, the consequences for others, or whether anyone will ever find out. Rules exist for a reason and you follow them.', fr: 'Pour vous, l\'intégrité est non négociable. Peu importe l\'avantage, les conséquences pour les autres, ou si personne ne le saura jamais. Les règles existent pour une raison et vous les respectez.', de: 'Für dich ist Integrität nicht verhandelbar. Es spielt keine Rolle, wie groß der Vorteil ist, welche Konsequenzen es für andere hat oder ob jemand es je herausfinden wird. Regeln existieren aus einem Grund und du hältst sie ein.', it: 'Per te l\'integrità non è negoziabile. Non importa il vantaggio, le conseguenze per gli altri o se qualcuno lo scoprirà mai. Le regole esistono per una ragione e tu le rispetti.', pt: 'Para você, a integridade não é negociável. Não importa o benefício, as consequências para outros ou se alguém vai descobrir. As regras existem por uma razão e você as respeita.' } },
      { name: { es: 'El Pragmático Ético', en: 'The Ethical Pragmatist', fr: 'Le Pragmatique Éthique', de: 'Der Ethische Pragmatiker', it: 'Il Pragmatico Etico', pt: 'O Pragmático Ético' }, dimensions: ['P'], photo: '/characters/ethical-pragmatist.jpg', description: { es: 'Piensa en resultados, pero dentro de límites éticos.', en: 'Thinks in outcomes, but within ethical limits.', fr: 'Pense aux résultats, mais dans les limites éthiques.', de: 'Denkt in Ergebnissen, aber innerhalb ethischer Grenzen.', it: 'Pensa ai risultati, ma entro i limiti etici.', pt: 'Pensa em resultados, mas dentro de limites éticos.' }, philosophy: { es: 'Para ti, la ética es práctica. No eres rígido/a en la forma, pero sí en el fondo. Buscas la solución más efectiva dentro de los límites correctos. A veces eso requiere más trabajo que tomar el atajo.', en: 'For you, ethics is practical. You\'re not rigid in form, but you are in substance. You seek the most effective solution within the right limits. Sometimes that takes more work than taking the shortcut.', fr: 'Pour vous, l\'éthique est pratique. Vous n\'êtes pas rigide dans la forme, mais dans le fond, oui. Vous cherchez la solution la plus efficace dans les bonnes limites. Parfois, cela demande plus de travail que de prendre un raccourci.', de: 'Für dich ist Ethik praktisch. Du bist nicht in der Form starr, aber im Kern schon. Du suchst die effektivste Lösung innerhalb der richtigen Grenzen. Manchmal erfordert das mehr Arbeit als den Abkürzung zu nehmen.', it: 'Per te l\'etica è pratica. Non sei rigido nella forma, ma lo sei nella sostanza. Cerchi la soluzione più efficace entro i limiti giusti. A volte richiede più lavoro che prendere la scorciatoia.', pt: 'Para você, a ética é prática. Você não é rígido na forma, mas sim no fundo. Você busca a solução mais eficaz dentro dos limites certos. Às vezes isso exige mais trabalho do que tomar o atalho.' } },
      { name: { es: 'El Transparente Radical', en: 'The Radical Transparent', fr: 'Le Transparent Radical', de: 'Der Radikal Transparente', it: 'Il Trasparente Radicale', pt: 'O Transparente Radical' }, dimensions: ['T'], photo: '/characters/radical-transparent.jpg', description: { es: 'Si no puedes hacerlo públicamente, no deberías hacerlo.', en: 'If you can\'t do it publicly, you shouldn\'t do it at all.', fr: 'Si vous ne pouvez pas le faire publiquement, vous ne devriez pas le faire.', de: 'Wenn du es nicht öffentlich tun kannst, solltest du es nicht tun.', it: 'Se non puoi farlo pubblicamente, non dovresti farlo.', pt: 'Se não pode fazer publicamente, não deveria fazer.' }, philosophy: { es: 'Tu prueba ácida para cualquier decisión es: ¿podría defender esto públicamente? Si no, no lo haces. La transparencia no es solo honestidad con otros — es la garantía de honestidad contigo mismo.', en: 'Your litmus test for any decision is: could I defend this publicly? If not, you don\'t do it. Transparency isn\'t just honesty with others — it\'s the guarantee of honesty with yourself.', fr: 'Votre test décisif pour toute décision est : pourrais-je défendre cela publiquement ? Si non, vous ne le faites pas. La transparence n\'est pas seulement l\'honnêteté avec les autres — c\'est la garantie d\'honnêteté avec soi-même.', de: 'Dein Lackmustest für jede Entscheidung ist: Könnte ich das öffentlich verteidigen? Wenn nicht, tust du es nicht. Transparenz ist nicht nur Ehrlichkeit gegenüber anderen — es ist die Garantie der Ehrlichkeit mit dir selbst.', it: 'Il tuo test per qualsiasi decisione è: potrei difenderlo pubblicamente? In caso negativo, non lo fai. La trasparenza non è solo onestà con gli altri — è la garanzia di onestà con se stessi.', pt: 'Seu teste decisivo para qualquer decisão é: poderia defender isso publicamente? Se não, não faz. A transparência não é apenas honestidade com os outros — é a garantia de honestidade consigo mesmo.' } },
      { name: { es: 'El Corrupto Racionalizado', en: 'The Rationalized Corrupt', fr: 'Le Corrompu Rationalisé', de: 'Der Rationalisierte Korrupte', it: 'Il Corrotto Razionalizzato', pt: 'O Corrupto Racionalizado' }, dimensions: ['C', 'P'], photo: '/characters/rationalized-corrupt.jpg', description: { es: 'Cada acto corrupto tiene una justificación elaborada.', en: 'Every corrupt act has an elaborate justification.', fr: 'Chaque acte corrompu a une justification élaborée.', de: 'Jede korrupte Handlung hat eine ausgefeilte Rechtfertigung.', it: 'Ogni atto corrotto ha una giustificazione elaborata.', pt: 'Cada ato corrupto tem uma justificativa elaborada.' }, philosophy: { es: 'Eres el tipo de persona que podría convencerse de casi cualquier desviación siempre que el marco narrativo sea suficientemente sólido. Primero decide, después racionaliza. El peligro es que el límite siempre se corre un poco más.', en: 'You\'re the kind of person who can convince themselves of almost any deviation as long as the narrative framework is solid enough. First decide, then rationalize. The danger is the line always moves a little further.', fr: 'Vous êtes le genre de personne qui peut se convaincre de presque n\'importe quel écart tant que le cadre narratif est suffisamment solide. D\'abord on décide, ensuite on rationalise. Le danger, c\'est que la limite recule toujours un peu plus.', de: 'Du bist der Typ Mensch, der sich von fast jeder Abweichung überzeugen kann, solange der Erzählrahmen fest genug ist. Erst entscheiden, dann rationalisieren. Die Gefahr ist, dass die Grenze immer etwas weiter rückt.', it: 'Sei il tipo di persona che riesce a convincersi di quasi qualsiasi deviazione purché il quadro narrativo sia abbastanza solido. Prima si decide, poi si razionalizza. Il pericolo è che il limite si sposta sempre un po\' più in là.', pt: 'Você é o tipo de pessoa que consegue se convencer de quase qualquer desvio desde que o enquadramento narrativo seja suficientemente sólido. Primeiro decide, depois racionaliza. O perigo é que o limite sempre se move um pouco mais.' } },
      { name: { es: 'El Gris Consciente', en: 'The Conscious Gray', fr: 'Le Gris Conscient', de: 'Das Bewusste Grau', it: 'Il Grigio Consapevole', pt: 'O Cinza Consciente' }, dimensions: ['C', 'I'], photo: '/characters/conscious-gray.jpg', description: { es: 'Sabe que lo que hace está mal pero lo hace de todas formas.', en: 'Knows what they\'re doing is wrong but does it anyway.', fr: 'Sait que ce qu\'il fait est mal, mais le fait quand même.', de: 'Weiß, dass das, was er tut, falsch ist, tut es aber trotzdem.', it: 'Sa che quello che fa è sbagliato ma lo fa comunque.', pt: 'Sabe que o que faz está errado, mas faz assim mesmo.' }, philosophy: { es: 'Al menos eres honesto contigo mismo/a: no te engañas. Sabes que cruzas una línea. Eso lo distingue de la corrupción racionalizada, pero no lo hace menos problemático. La conciencia sin acción es su propia forma de cobardía.', en: 'At least you\'re honest with yourself: you don\'t deceive yourself. You know you\'re crossing a line. That distinguishes it from rationalized corruption, but doesn\'t make it less problematic. Awareness without action is its own form of cowardice.', fr: 'Au moins, vous êtes honnête avec vous-même : vous ne vous trompez pas. Vous savez que vous franchissez une ligne. Cela distingue cela de la corruption rationalisée, mais ne le rend pas moins problématique. La conscience sans action est sa propre forme de lâcheté.', de: 'Zumindest bist du ehrlich mit dir selbst: Du täuschst dich nicht. Du weißt, dass du eine Linie überschreitest. Das unterscheidet es von rationalisierter Korruption, macht es aber nicht weniger problematisch. Bewusstsein ohne Handlung ist seine eigene Form von Feigheit.', it: 'Almeno sei onesto con te stesso: non ti inganni. Sai che stai attraversando una linea. Questo lo distingue dalla corruzione razionalizzata, ma non lo rende meno problematico. La consapevolezza senza azione è la sua forma di vigliaccheria.', pt: 'Pelo menos você é honesto consigo mesmo: não se engana. Você sabe que está cruzando uma linha. Isso o distingue da corrupção racionalizada, mas não o torna menos problemático. A consciência sem ação é sua própria forma de covardia.' } },
      { name: { es: 'El Prudente Honesto', en: 'The Prudent Honest', fr: 'Le Prudent Honnête', de: 'Der Kluge Ehrliche', it: 'Il Prudente Onesto', pt: 'O Prudente Honesto' }, dimensions: ['P', 'T'], photo: '/characters/prudent-honest.jpg', description: { es: 'Busca la solución más efectiva y más transparente.', en: 'Seeks the most effective and most transparent solution.', fr: 'Cherche la solution la plus efficace et la plus transparente.', de: 'Sucht nach der effektivsten und transparentesten Lösung.', it: 'Cerca la soluzione più efficace e più trasparente.', pt: 'Busca a solução mais eficaz e mais transparente.' }, philosophy: { es: 'Combinas eficiencia con honestidad. No eres ingenuo/a sobre cómo funcionan las instituciones, pero tampoco eres cínico/a. Crees que se puede actuar con integridad dentro de sistemas complejos.', en: 'You combine efficiency with honesty. You\'re not naive about how institutions work, but you\'re not cynical either. You believe you can act with integrity within complex systems.', fr: 'Vous combinez efficacité et honnêteté. Vous n\'êtes pas naïf sur le fonctionnement des institutions, mais vous n\'êtes pas non plus cynique. Vous croyez que l\'on peut agir avec intégrité au sein de systèmes complexes.', de: 'Du verbindest Effizienz mit Ehrlichkeit. Du bist nicht naiv über die Funktionsweise von Institutionen, aber auch nicht zynisch. Du glaubst, dass man innerhalb komplexer Systeme mit Integrität handeln kann.', it: 'Combini efficienza e onestà. Non sei ingenuo su come funzionano le istituzioni, ma non sei nemmeno cinico. Credi che si possa agire con integrità all\'interno di sistemi complessi.', pt: 'Você combina eficiência com honestidade. Não é ingênuo sobre como as instituições funcionam, mas também não é cínico. Acredita que é possível agir com integridade dentro de sistemas complexos.' } },
      { name: { es: 'El Transformador Institucional', en: 'The Institutional Transformer', fr: 'Le Transformateur Institutionnel', de: 'Der Institutionelle Transformator', it: 'Il Trasformatore Istituzionale', pt: 'O Transformador Institucional' }, dimensions: ['I', 'T'], photo: '/characters/institutional-transformer.jpg', description: { es: 'Usa su posición para hacer los sistemas más transparentes.', en: 'Uses their position to make systems more transparent.', fr: 'Utilise sa position pour rendre les systèmes plus transparents.', de: 'Nutzt seine Position, um Systeme transparenter zu machen.', it: 'Usa la propria posizione per rendere i sistemi più trasparenti.', pt: 'Usa sua posição para tornar os sistemas mais transparentes.' }, philosophy: { es: 'No te basta con ser íntegro/a individualmente. Usas tu posición para hacer los sistemas más transparentes, las reglas más claras, los procesos más auditables. La integridad como proyecto colectivo.', en: 'Being individually ethical isn\'t enough for you. You use your position to make systems more transparent, rules clearer, processes more auditable. Integrity as a collective project.', fr: 'Être personnellement intègre ne vous suffit pas. Vous utilisez votre position pour rendre les systèmes plus transparents, les règles plus claires, les processus plus auditables. L\'intégrité comme projet collectif.', de: 'Individuell integer zu sein reicht dir nicht. Du nutzt deine Position, um Systeme transparenter, Regeln klarer und Prozesse überprüfbarer zu machen. Integrität als kollektives Projekt.', it: 'Non ti basta essere intègro individualmente. Usi la tua posizione per rendere i sistemi più trasparenti, le regole più chiare, i processi più verificabili. L\'integrità come progetto collettivo.', pt: 'Ser íntegro individualmente não é suficiente para você. Você usa sua posição para tornar os sistemas mais transparentes, as regras mais claras, os processos mais auditáveis. A integridade como projeto coletivo.' } },
    ],
  };

  await prisma.quiz.upsert({
    where: { slug: 'corrupt' },
    update: {
      title: data.title,
      description: data.description,
      scenarioLabel: data.scenarioLabel,
      dimensionLabels: data.dimensionLabels,
      questions: data.questions,
      characters: data.characters,
    },
    create: data,
  });
}
