import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan maquiavélico/a eres?', en: 'How Machiavellian are you?', fr: 'À quel point es-tu machiavélique ?', de: 'Wie machiavellistisch bist du?', it: 'Quanto sei machiavellico/a?', pt: 'O quanto você é maquiavélico/a?' },
  description: { es: 'El fin justifica los medios — ¿o no? Descubre si piensas como un estratega político del siglo XVI.', en: 'Does the end justify the means — or not? Discover if you think like a 16th-century political strategist.', fr: 'La fin justifie-t-elle les moyens — ou pas ? Découvrez si vous pensez comme un stratège politique du XVIe siècle.', de: 'Heiligt der Zweck die Mittel — oder nicht? Entdecke, ob du wie ein politischer Stratege des 16. Jahrhunderts denkst.', it: 'Il fine giustifica i mezzi — o no? Scopri se pensi come uno stratega politico del XVI secolo.', pt: 'O fim justifica os meios — ou não? Descubra se você pensa como um estrategista político do século XVI.' },
  scenarioLabel: { es: 'Dilema', en: 'Dilemma', fr: 'Dilemme', de: 'Dilemma', it: 'Dilemma', pt: 'Dilema' },
  dimensionLabels: {
    es: { E: 'Estrategia', P: 'Principios', L: 'Lealtad', A: 'Adaptabilidad' },
    en: { E: 'Strategy', P: 'Principles', L: 'Loyalty', A: 'Adaptability' },
    fr: { E: 'Stratégie', P: 'Principes', L: 'Loyauté', A: 'Adaptabilité' },
    de: { E: 'Strategie', P: 'Prinzipien', L: 'Loyalität', A: 'Anpassungsfähigkeit' },
    it: { E: 'Strategia', P: 'Principi', L: 'Lealtà', A: 'Adattabilità' },
    pt: { E: 'Estratégia', P: 'Princípios', L: 'Lealdade', A: 'Adaptabilidade' },
  },
  questions: [
    { id: 1, situation: { es: 'Para conseguir el trabajo de tus sueños, podrías omitir un dato de tu CV que te descalificaría. Nadie lo verificará.', en: 'To get your dream job, you could omit a detail from your CV that would disqualify you. Nobody will verify it.', fr: 'Pour décrocher le travail de tes rêves, tu pourrais omettre une information de ton CV qui te disqualifierait. Personne ne le vérifiera.', de: 'Um deinen Traumjob zu bekommen, könntest du ein Detail aus deinem Lebenslauf weglassen, das dich disqualifizieren würde. Niemand wird es überprüfen.', it: 'Per ottenere il lavoro dei tuoi sogni, potresti omettere un dato dal tuo CV che ti squalificherebbe. Nessuno lo verificherà.', pt: 'Para conseguir o emprego dos seus sonhos, você poderia omitir um dado do seu currículo que te desqualificaria. Ninguém verificará.' }, options: [
      { text: { es: 'Lo omito. El trabajo importa; los detalles se arreglan después desde adentro.', en: 'I omit it. The job matters; details can be fixed from the inside afterwards.', fr: 'Je l\'omets. Le travail compte; les détails se règlent après de l\'intérieur.', de: 'Ich lasse es weg. Der Job ist wichtig; Details lassen sich danach von innen regeln.', it: 'Lo ometto. Il lavoro conta; i dettagli si sistemano dopo dall\'interno.', pt: 'Omito. O emprego importa; os detalhes se resolvem depois por dentro.' }, dimension: 'E' },
      { text: { es: 'No lo omito. Si descubren la mentira en cualquier momento, todo se derrumba.', en: 'I don\'t omit it. If they discover the lie at any point, everything collapses.', fr: 'Je ne l\'omets pas. Si on découvre le mensonge à un moment quelconque, tout s\'effondre.', de: 'Ich lasse es nicht weg. Wenn sie die Lüge irgendwann entdecken, bricht alles zusammen.', it: 'Non lo ometto. Se scoprono la bugia in qualsiasi momento, tutto crolla.', pt: 'Não omito. Se descobrirem a mentira a qualquer momento, tudo desmorona.' }, dimension: 'P' },
      { text: { es: 'Llamo a alguien que me pueda dar una referencia que tape ese vacío.', en: 'I call someone who can give me a reference that covers that gap.', fr: 'J\'appelle quelqu\'un qui peut me donner une référence qui comble ce vide.', de: 'Ich rufe jemanden an, der mir eine Referenz geben kann, die diese Lücke abdeckt.', it: 'Chiamo qualcuno che possa darmi un riferimento che copra quella lacuna.', pt: 'Ligo para alguém que possa me dar uma referência que tape esse vazio.' }, dimension: 'L' },
      { text: { es: 'Omito ese dato pero me preparo para la eventualidad de que lo descubran.', en: 'I omit that detail but prepare for the eventuality that they discover it.', fr: 'J\'omets cette information mais me prépare à l\'éventualité qu\'on la découvre.', de: 'Ich lasse dieses Detail weg, bereite mich aber auf die Möglichkeit vor, dass sie es entdecken.', it: 'Ometto quel dato ma mi preparo per l\'eventualità che lo scoprano.', pt: 'Omito esse dado mas me preparo para a eventualidade de que o descubram.' }, dimension: 'A' },
    ] },
    { id: 2, situation: { es: 'Un colega incompetente ocupa un puesto que tú mereces. Tienes información que podría perjudicarlo.', en: 'An incompetent colleague holds a position you deserve. You have information that could harm them.', fr: 'Un collègue incompétent occupe un poste que tu mérites. Tu as des informations qui pourraient lui nuire.', de: 'Ein inkompetenter Kollege besetzt eine Stelle, die du verdienst. Du hast Informationen, die ihm schaden könnten.', it: 'Un collega incompetente occupa una posizione che meriti. Hai informazioni che potrebbero danneggiarlo.', pt: 'Um colega incompetente ocupa um cargo que você merece. Você tem informações que poderiam prejudicá-lo.' }, options: [
      { text: { es: 'La uso estratégicamente cuando llegue el momento correcto.', en: 'I use it strategically when the right moment comes.', fr: 'Je l\'utilise stratégiquement quand le bon moment arrive.', de: 'Ich nutze es strategisch, wenn der richtige Moment kommt.', it: 'La uso strategicamente quando arriva il momento giusto.', pt: 'Uso estrategicamente quando chegar o momento certo.' }, dimension: 'E' },
      { text: { es: 'No la uso. Prefiero ganar por mis méritos.', en: 'I don\'t use it. I prefer to win by my merits.', fr: 'Je ne l\'utilise pas. Je préfère gagner par mes mérites.', de: 'Ich nutze sie nicht. Ich gewinne lieber durch meine Verdienste.', it: 'Non la uso. Preferisco vincere per i miei meriti.', pt: 'Não uso. Prefiro ganhar pelos meus méritos.' }, dimension: 'P' },
      { text: { es: 'Depende de qué tan cercano sea. A los aliados no los traiciono.', en: 'Depends on how close we are. I don\'t betray allies.', fr: 'Ça dépend de notre proximité. Je ne trahis pas mes alliés.', de: 'Hängt davon ab, wie nah wir uns sind. Ich verrate keine Verbündeten.', it: 'Dipende da quanto è vicino. Non tradisco gli alleati.', pt: 'Depende de quão próximo seja. Não traio aliados.' }, dimension: 'L' },
      { text: { es: 'La guardo como opción de último recurso si es que lo necesito.', en: 'I keep it as a last resort option if I need it.', fr: 'Je la garde comme option de dernier recours si j\'en ai besoin.', de: 'Ich behalte es als letzte Möglichkeit, wenn ich es brauche.', it: 'La tengo come opzione di ultimo ricorso se ne ho bisogno.', pt: 'Guardo como opção de último recurso se precisar.' }, dimension: 'A' },
    ] },
    { id: 3, situation: { es: 'Alguien de tu equipo está filtrando información confidencial. Sospechas pero no tienes prueba.', en: 'Someone on your team is leaking confidential information. You suspect but have no proof.', fr: 'Quelqu\'un dans ton équipe divulgue des informations confidentielles. Tu soupçonnes mais n\'as pas de preuve.', de: 'Jemand in deinem Team gibt vertrauliche Informationen preis. Du verdächtigst sie, hast aber keinen Beweis.', it: 'Qualcuno nel tuo team sta divulgando informazioni riservate. Sospetti ma non hai prove.', pt: 'Alguém na sua equipe está vazando informações confidenciais. Você suspeita mas não tem prova.' }, options: [
      { text: { es: 'Planto información falsa para identificar quién la filtra.', en: 'I plant false information to identify who is leaking it.', fr: 'Je plante de fausses informations pour identifier qui les divulgue.', de: 'Ich pflanze falsche Informationen, um zu identifizieren, wer sie preisgibt.', it: 'Pianto informazioni false per identificare chi le divulga.', pt: 'Planto informações falsas para identificar quem está vazando.' }, dimension: 'E' },
      { text: { es: 'Hablo directamente con los sospechosos y observo su reacción.', en: 'I speak directly with the suspects and observe their reaction.', fr: 'Je parle directement avec les suspects et observe leur réaction.', de: 'Ich spreche direkt mit den Verdächtigen und beobachte ihre Reaktion.', it: 'Parlo direttamente con i sospettati e osservo la loro reazione.', pt: 'Falo diretamente com os suspeitos e observo a reação.' }, dimension: 'P' },
      { text: { es: 'Confío en el equipo hasta que haya pruebas concretas.', en: 'I trust the team until there is concrete evidence.', fr: 'Je fais confiance à l\'équipe jusqu\'à ce qu\'il y ait des preuves concrètes.', de: 'Ich vertraue dem Team, bis es konkrete Beweise gibt.', it: 'Mi fido del team fino a quando non ci sono prove concrete.', pt: 'Confio na equipe até que haja provas concretas.' }, dimension: 'L' },
      { text: { es: 'Limito el acceso a información sensible sin hacer acusaciones.', en: 'I limit access to sensitive information without making accusations.', fr: 'Je limite l\'accès aux informations sensibles sans faire d\'accusations.', de: 'Ich beschränke den Zugang zu sensiblen Informationen ohne Anschuldigungen zu machen.', it: 'Limito l\'accesso alle informazioni sensibili senza fare accuse.', pt: 'Limito o acesso a informações sensíveis sem fazer acusações.' }, dimension: 'A' },
    ] },
    { id: 4, situation: { es: 'Para avanzar en política de empresa, ¿cómo manejas a tu jefe?', en: 'To advance in company politics, how do you handle your boss?', fr: 'Pour avancer dans la politique de l\'entreprise, comment gères-tu ton patron ?', de: 'Um in der Unternehmenspolitik voranzukommen, wie gehst du mit deinem Chef um?', it: 'Per avanzare nella politica aziendale, come gestisci il tuo capo?', pt: 'Para avançar na política da empresa, como você lida com seu chefe?' }, options: [
      { text: { es: 'Identifico qué es lo que más valora y lo proveo consistentemente. Todos tienen un precio.', en: 'I identify what they value most and consistently provide it. Everyone has a price.', fr: 'J\'identifie ce qu\'il/elle valorise le plus et le fournis constamment. Tout le monde a un prix.', de: 'Ich identifiziere, was er am meisten schätzt, und liefere es konsequent. Jeder hat einen Preis.', it: 'Identifico cosa valorizza di più e lo fornisco costantemente. Tutti hanno un prezzo.', pt: 'Identifico o que mais valoriza e forneço consistentemente. Todos têm um preço.' }, dimension: 'E' },
      { text: { es: 'Hago bien mi trabajo y confío en que eso hable por sí solo.', en: 'I do my work well and trust that it speaks for itself.', fr: 'Je fais bien mon travail et fais confiance que ça parle de lui-même.', de: 'Ich mache meine Arbeit gut und vertraue darauf, dass sie für sich selbst spricht.', it: 'Faccio bene il mio lavoro e confido che parli da solo.', pt: 'Faço bem meu trabalho e confio que isso fale por si só.' }, dimension: 'P' },
      { text: { es: 'Construyo una relación genuina con él/ella. La lealtad es más valiosa que la política.', en: 'I build a genuine relationship with them. Loyalty is more valuable than politics.', fr: 'Je construis une relation genuino avec lui/elle. La loyauté est plus précieuse que la politique.', de: 'Ich baue eine echte Beziehung zu ihm/ihr auf. Loyalität ist wertvoller als Politik.', it: 'Costruisco una relazione genuina con lui/lei. La lealtà è più preziosa della politica.', pt: 'Construo uma relação genuína com ele/ela. A lealdade é mais valiosa que a política.' }, dimension: 'L' },
      { text: { es: 'Adapto mi estilo según lo que necesite la situación en cada momento.', en: 'I adapt my style according to what the situation needs at each moment.', fr: 'J\'adapte mon style selon ce que la situation nécessite à chaque moment.', de: 'Ich passe meinen Stil an das an, was die Situation in jedem Moment erfordert.', it: 'Adatto il mio stile in base a ciò di cui la situazione ha bisogno in ogni momento.', pt: 'Adapto meu estilo de acordo com o que a situação precisa em cada momento.' }, dimension: 'A' },
    ] },
    { id: 5, situation: { es: 'Dos aliados tuyos están en conflicto. Ambos te piden apoyo. ¿Qué haces?', en: 'Two of your allies are in conflict. Both ask for your support. What do you do?', fr: 'Deux de tes alliés sont en conflit. Les deux te demandent du soutien. Que fais-tu ?', de: 'Zwei deiner Verbündeten sind im Konflikt. Beide bitten dich um Unterstützung. Was tust du?', it: 'Due tuoi alleati sono in conflitto. Entrambi ti chiedono supporto. Cosa fai?', pt: 'Dois aliados seus estão em conflito. Ambos pedem apoio. O que você faz?' }, options: [
      { text: { es: 'Apoyo al que tenga más poder o sea más útil para mis objetivos actuales.', en: 'I support whoever has more power or is more useful for my current objectives.', fr: 'Je soutiens celui qui a le plus de pouvoir ou est le plus utile à mes objectifs actuels.', de: 'Ich unterstütze denjenigen mit mehr Macht oder der für meine aktuellen Ziele nützlicher ist.', it: 'Supporto chi ha più potere o è più utile ai miei obiettivi attuali.', pt: 'Apoio quem tem mais poder ou é mais útil para meus objetivos atuais.' }, dimension: 'E' },
      { text: { es: 'Me niego a tomar partido. No es mi conflicto y no pienso destruir una relación por otra.', en: 'I refuse to take sides. It\'s not my conflict and I\'m not destroying one relationship for another.', fr: 'Je refuse de prendre parti. Ce n\'est pas mon conflit et je ne vais pas détruire une relation pour une autre.', de: 'Ich weigere mich, Partei zu ergreifen. Es ist nicht mein Konflikt und ich will keine Beziehung für eine andere zerstören.', it: 'Mi rifiuto di prendere posizione. Non è il mio conflitto e non penso di distruggere una relazione per un\'altra.', pt: 'Me recuso a tomar partido. Não é meu conflito e não pretendo destruir um relacionamento por outro.' }, dimension: 'P' },
      { text: { es: 'Apoyo al que considero tiene razón, aunque sea el más débil.', en: 'I support whoever I think is right, even if they\'re the weakest.', fr: 'Je soutiens celui que je considère avoir raison, même s\'il est le plus faible.', de: 'Ich unterstütze denjenigen, den ich für richtig halte, auch wenn er der Schwächere ist.', it: 'Supporto chi considero abbia ragione, anche se è il più debole.', pt: 'Apoio quem considero ter razão, mesmo que seja o mais fraco.' }, dimension: 'L' },
      { text: { es: 'Me presento como mediador neutral y uso esa posición para ganar capital con ambos.', en: 'I present myself as a neutral mediator and use that position to gain capital with both.', fr: 'Je me présente comme médiateur neutre et utilise cette position pour gagner du capital avec les deux.', de: 'Ich präsentiere mich als neutraler Vermittler und nutze diese Position, um bei beiden Kapital zu gewinnen.', it: 'Mi presento come mediatore neutrale e uso quella posizione per guadagnare capitale con entrambi.', pt: 'Me apresento como mediador neutro e uso essa posição para ganhar capital com ambos.' }, dimension: 'A' },
    ] },
    { id: 6, situation: { es: 'Puedes mentirle a un cliente sobre el plazo de entrega para ganar el contrato. Después podrás cumplirlo, pero será muy ajustado.', en: 'You can lie to a client about the delivery timeline to win the contract. You\'ll be able to meet it afterwards, but it will be very tight.', fr: 'Tu peux mentir à un client sur le délai de livraison pour gagner le contrat. Tu pourras le respecter ensuite, mais ce sera très serré.', de: 'Du kannst einem Kunden über die Lieferfrist lügen, um den Vertrag zu gewinnen. Du kannst sie danach einhalten, aber es wird sehr knapp.', it: 'Puoi mentire a un cliente sulla tempistica di consegna per vincere il contratto. Dopo potrai rispettarla, ma sarà molto ridotta.', pt: 'Você pode mentir a um cliente sobre o prazo de entrega para ganhar o contrato. Depois poderá cumpri-lo, mas será muito apertado.' }, options: [
      { text: { es: 'Lo hago. Primero ganar el contrato, después resolver los plazos. Los clientes se adaptan.', en: 'I do it. First win the contract, then resolve the timelines. Clients adapt.', fr: 'Je le fais. D\'abord gagner le contrat, ensuite résoudre les délais. Les clients s\'adaptent.', de: 'Ich tue es. Erst den Vertrag gewinnen, dann die Fristen regeln. Kunden passen sich an.', it: 'Lo faccio. Prima vincere il contratto, poi risolvere le tempistiche. I clienti si adattano.', pt: 'Faço. Primeiro ganhar o contrato, depois resolver os prazos. Os clientes se adaptam.' }, dimension: 'E' },
      { text: { es: 'No lo hago. Una relación construida sobre una mentira es una relación en riesgo permanente.', en: 'I don\'t do it. A relationship built on a lie is a relationship in permanent risk.', fr: 'Je ne le fais pas. Une relation construite sur un mensonge est une relation en risque permanent.', de: 'Ich tue es nicht. Eine Beziehung, die auf einer Lüge aufgebaut ist, ist eine Beziehung in dauerhafter Gefahr.', it: 'Non lo faccio. Una relazione costruita su una bugia è una relazione in rischio permanente.', pt: 'Não faço. Um relacionamento construído sobre uma mentira é um relacionamento em risco permanente.' }, dimension: 'P' },
      { text: { es: 'Depende de la relación con el cliente. Con clientes conocidos, soy más honesto.', en: 'Depends on the client relationship. With known clients, I\'m more honest.', fr: 'Ça dépend de la relation avec le client. Avec les clients connus, je suis plus honnête.', de: 'Hängt von der Kundenbeziehung ab. Mit bekannten Kunden bin ich ehrlicher.', it: 'Dipende dal rapporto con il cliente. Con clienti conosciuti, sono più onesto.', pt: 'Depende do relacionamento com o cliente. Com clientes conhecidos, sou mais honesto.' }, dimension: 'L' },
      { text: { es: 'Soy ambiguo con el plazo pero sin mentir directamente. Que interprete lo que quiera.', en: 'I\'m ambiguous about the timeline but without lying directly. Let them interpret what they want.', fr: 'Je suis ambigu sur le délai mais sans mentir directement. Qu\'il interprète ce qu\'il veut.', de: 'Ich bin mehrdeutig zur Frist, aber ohne direkt zu lügen. Möge er interpretieren, was er will.', it: 'Sono ambiguo sulla tempistica ma senza mentire direttamente. Che interpreti quello che vuole.', pt: 'Sou ambíguo com o prazo mas sem mentir diretamente. Que interprete o que quiser.' }, dimension: 'A' },
    ] },
    { id: 7, situation: { es: 'Para cerrar un acuerdo, necesitas que tu contraparte baje la guardia. ¿Qué haces?', en: 'To close a deal, you need your counterpart to let their guard down. What do you do?', fr: 'Pour conclure un accord, tu as besoin que ta contrepartie baisse la garde. Que fais-tu ?', de: 'Um einen Deal abzuschließen, musst du deine Gegenpartei dazu bringen, die Deckung zu senken. Was tust du?', it: 'Per chiudere un accordo, hai bisogno che la tua controparte abbassi la guardia. Cosa fai?', pt: 'Para fechar um acordo, você precisa que sua contraparte baixe a guarda. O que você faz?' }, options: [
      { text: { es: 'Creo deliberadamente un ambiente de confianza y cercanía que facilite el acuerdo.', en: 'I deliberately create an atmosphere of trust and closeness that facilitates the deal.', fr: 'Je crée délibérément une atmosphère de confiance et de proximité qui facilite l\'accord.', de: 'Ich schaffe bewusst eine Atmosphäre des Vertrauens und der Nähe, die den Deal erleichtert.', it: 'Creo deliberatamente un\'atmosfera di fiducia e vicinanza che facilita l\'accordo.', pt: 'Crio deliberadamente uma atmosfera de confiança e proximidade que facilita o acordo.' }, dimension: 'E' },
      { text: { es: 'Presento mi caso con claridad y dejo que los argumentos hablen.', en: 'I present my case clearly and let the arguments speak.', fr: 'Je présente mon cas avec clarté et laisse les arguments parler.', de: 'Ich präsentiere meinen Fall klar und lasse die Argumente sprechen.', it: 'Presento il mio caso con chiarezza e lascio che gli argomenti parlino.', pt: 'Apresento meu caso com clareza e deixo os argumentos falarem.' }, dimension: 'P' },
      { text: { es: 'Construyo una relación genuina antes de llegar a la negociación.', en: 'I build a genuine relationship before reaching the negotiation.', fr: 'Je construis une relation genuino avant d\'arriver à la négociation.', de: 'Ich baue eine echte Beziehung auf, bevor ich zur Verhandlung komme.', it: 'Costruisco una relazione genuina prima di arrivare alla trattativa.', pt: 'Construo uma relação genuína antes de chegar à negociação.' }, dimension: 'L' },
      { text: { es: 'Me adapto a su estilo de comunicación para que se sienta cómodo/a.', en: 'I adapt to their communication style so they feel comfortable.', fr: 'Je m\'adapte à leur style de communication pour qu\'il/elle se sente à l\'aise.', de: 'Ich passe mich an ihren Kommunikationsstil an, damit sie sich wohl fühlen.', it: 'Mi adatto al loro stile di comunicazione affinché si senta a proprio agio.', pt: 'Me adapto ao estilo de comunicação deles para que se sinta confortável.' }, dimension: 'A' },
    ] },
    { id: 8, situation: { es: 'Tu empresa está perdiendo terreno frente a un competidor. Una persona clave del competidor quiere cambiarse.', en: 'Your company is losing ground to a competitor. A key person from the competitor wants to switch.', fr: 'Ton entreprise perd du terrain face à un concurrent. Une personne clé du concurrent veut changer.', de: 'Dein Unternehmen verliert gegenüber einem Wettbewerber Boden. Eine Schlüsselperson des Wettbewerbers möchte wechseln.', it: 'La tua azienda sta perdendo terreno rispetto a un concorrente. Una persona chiave del concorrente vuole cambiare.', pt: 'Sua empresa está perdendo terreno para um concorrente. Uma pessoa-chave do concorrente quer mudar.' }, options: [
      { text: { es: 'La contrato de inmediato. Toda ventaja competitiva es válida.', en: 'I hire them immediately. Any competitive advantage is valid.', fr: 'Je l\'engage immédiatement. Tout avantage concurrentiel est valide.', de: 'Ich stelle sie sofort ein. Jeder Wettbewerbsvorteil ist gültig.', it: 'La assuno immediatamente. Qualsiasi vantaggio competitivo è valido.', pt: 'Contrato imediatamente. Qualquer vantagem competitiva é válida.' }, dimension: 'E' },
      { text: { es: 'Solo si puede traer valor genuino, no solo información del competidor.', en: 'Only if they can bring genuine value, not just competitor information.', fr: 'Seulement s\'il/elle peut apporter une valeur réelle, pas seulement des informations sur le concurrent.', de: 'Nur wenn sie echten Wert bringen können, nicht nur Informationen des Wettbewerbers.', it: 'Solo se può portare valore genuino, non solo informazioni del concorrente.', pt: 'Somente se puder trazer valor genuíno, não apenas informações do concorrente.' }, dimension: 'P' },
      { text: { es: 'La considero, pero no si implica que traiga información confidencial del otro lado.', en: 'I consider it, but not if it involves them bringing confidential information from the other side.', fr: 'Je la considère, mais pas si ça implique qu\'il/elle apporte des informations confidentielles de l\'autre côté.', de: 'Ich erwäge es, aber nicht, wenn es bedeutet, dass sie vertrauliche Informationen der anderen Seite mitbringen.', it: 'La considero, ma non se implica che porti informazioni riservate dall\'altro lato.', pt: 'Considero, mas não se implicar que traga informações confidenciais do outro lado.' }, dimension: 'L' },
      { text: { es: 'La contrato y establezco qué información puede y no puede compartir.', en: 'I hire them and establish what information they can and cannot share.', fr: 'Je l\'engage et établis quelles informations il/elle peut et ne peut pas partager.', de: 'Ich stelle sie ein und lege fest, welche Informationen sie teilen können und welche nicht.', it: 'La assumo e stabilisco quali informazioni può e non può condividere.', pt: 'Contrato e estabeleço quais informações pode e não pode compartilhar.' }, dimension: 'A' },
    ] },
    { id: 9, situation: { es: 'Alguien en una posición de poder te hace un favor. ¿Cómo lo registras?', en: 'Someone in a position of power does you a favor. How do you register it?', fr: 'Quelqu\'un en position de pouvoir te rend un service. Comment l\'enregistres-tu ?', de: 'Jemand in einer Machtposition tut dir einen Gefallen. Wie registrierst du das?', it: 'Qualcuno in una posizione di potere ti fa un favore. Come lo registri?', pt: 'Alguém em uma posição de poder te faz um favor. Como você registra?' }, options: [
      { text: { es: 'Lo anoto mentalmente como deuda a cobrar en el momento oportuno.', en: 'I mentally note it as a debt to collect at the right moment.', fr: 'Je le note mentalement comme une dette à récupérer au bon moment.', de: 'Ich notiere es gedanklich als Schuld, die zum richtigen Zeitpunkt einzufordern ist.', it: 'Lo annoto mentalmente come debito da riscuotere nel momento opportuno.', pt: 'Anoto mentalmente como dívida a cobrar no momento oportuno.' }, dimension: 'E' },
      { text: { es: 'Lo agradezco genuinamente y no pienso en cobrarlo. Los favores no son contratos.', en: 'I genuinely thank them and don\'t think about collecting. Favors are not contracts.', fr: 'Je le remercie genuinement et ne pense pas à le récupérer. Les faveurs ne sont pas des contrats.', de: 'Ich danke aufrichtig und denke nicht daran, es einzufordern. Gefälligkeiten sind keine Verträge.', it: 'Lo ringrazio genuinamente e non penso a riscuoterlo. I favori non sono contratti.', pt: 'Agradeço genuinamente e não penso em cobrar. Favores não são contratos.' }, dimension: 'P' },
      { text: { es: 'Me genera un sentido genuino de obligación de reciprocar cuando pueda.', en: 'It generates a genuine sense of obligation to reciprocate when I can.', fr: 'Ça me génère un sens genuino d\'obligation de réciprocité quand je peux.', de: 'Es erzeugt ein echtes Gefühl der Verpflichtung, zu erwidern, wenn ich kann.', it: 'Mi genera un senso genuino di obbligo di reciprocare quando posso.', pt: 'Me gera um sentido genuíno de obrigação de reciprocar quando puder.' }, dimension: 'L' },
      { text: { es: 'Depende de la persona. Con algunos es una deuda, con otros es simplemente gratitud.', en: 'Depends on the person. With some it\'s a debt, with others it\'s simply gratitude.', fr: 'Ça dépend de la personne. Avec certains c\'est une dette, avec d\'autres c\'est simplement de la gratitude.', de: 'Hängt von der Person ab. Bei einigen ist es eine Schuld, bei anderen einfach Dankbarkeit.', it: 'Dipende dalla persona. Con alcuni è un debito, con altri è semplicemente gratitudine.', pt: 'Depende da pessoa. Com alguns é uma dívida, com outros é simplesmente gratidão.' }, dimension: 'A' },
    ] },
    { id: 10, situation: { es: 'Una alianza que construiste te resulta ahora un obstáculo para tus nuevos objetivos.', en: 'An alliance you built now turns out to be an obstacle for your new objectives.', fr: 'Une alliance que tu as construite s\'avère maintenant être un obstacle pour tes nouveaux objectifs.', de: 'Ein Bündnis, das du aufgebaut hast, erweist sich nun als Hindernis für deine neuen Ziele.', it: 'Un\'alleanza che hai costruito si rivela ora un ostacolo per i tuoi nuovi obiettivi.', pt: 'Uma aliança que você construiu agora se torna um obstáculo para seus novos objetivos.' }, options: [
      { text: { es: 'La deshago estratégicamente de forma que el otro no lo sienta como traición.', en: 'I strategically dismantle it so the other doesn\'t feel it as betrayal.', fr: 'Je la défais stratégiquement de façon que l\'autre ne le ressente pas comme une trahison.', de: 'Ich löse sie strategisch auf, sodass der andere es nicht als Verrat empfindet.', it: 'La disfaccio strategicamente in modo che l\'altro non la senta come tradimento.', pt: 'Desfaço estrategicamente de forma que o outro não sinta como traição.' }, dimension: 'E' },
      { text: { es: 'Soy honesto/a: le digo que mis prioridades cambiaron y que necesito redefinir la relación.', en: 'I\'m honest: I tell them my priorities changed and I need to redefine the relationship.', fr: 'Je suis honnête: je lui dis que mes priorités ont changé et que j\'ai besoin de redéfinir la relation.', de: 'Ich bin ehrlich: Ich sage ihm, dass sich meine Prioritäten geändert haben und ich die Beziehung neu definieren muss.', it: 'Sono onesto/a: gli dico che le mie priorità sono cambiate e che ho bisogno di ridefinire la relazione.', pt: 'Sou honesto/a: digo que minhas prioridades mudaram e que preciso redefinir a relação.' }, dimension: 'P' },
      { text: { es: 'Me cuesta mucho. Las alianzas son compromisos y los compromisos se honran.', en: 'It\'s very hard for me. Alliances are commitments and commitments are honored.', fr: 'Ça me coûte beaucoup. Les alliances sont des engagements et les engagements s\'honorent.', de: 'Es fällt mir sehr schwer. Bündnisse sind Verpflichtungen und Verpflichtungen werden eingehalten.', it: 'Mi costa molto. Le alleanze sono impegni e gli impegni si onorano.', pt: 'Me custa muito. Alianças são compromissos e compromissos se honram.' }, dimension: 'L' },
      { text: { es: 'Renegocio los términos de la alianza para que funcione para mis nuevos objetivos.', en: 'I renegotiate the terms of the alliance so it works for my new objectives.', fr: 'Je renégocie les termes de l\'alliance pour qu\'elle fonctionne pour mes nouveaux objectifs.', de: 'Ich handele die Bedingungen des Bündnisses neu aus, damit es für meine neuen Ziele funktioniert.', it: 'Rinegozieo i termini dell\'alleanza affinché funzioni per i miei nuovi obiettivi.', pt: 'Renegoceio os termos da aliança para que funcione para meus novos objetivos.' }, dimension: 'A' },
    ] },
  ],
  characters: [
    { name: { es: 'Nicolás Maquiavelo', en: 'Niccolò Machiavelli', fr: 'Nicolas Machiavel', de: 'Niccolò Machiavelli', it: 'Niccolò Machiavelli', pt: 'Nicolau Maquiavel' }, dimensions: ['E'], photo: '/characters/machiavelli.jpg', description: { es: 'El estratega puro: el poder como única métrica del éxito.', en: 'The pure strategist: power as the only metric of success.', fr: 'Le stratège pur: le pouvoir comme seule mesure du succès.', de: 'Der reine Stratege: Macht als einziges Erfolgsmaß.', it: 'Lo stratega puro: il potere come unica misura del successo.', pt: 'O estrategista puro: o poder como única métrica do sucesso.' }, philosophy: { es: 'Para ti, la política y la vida son juegos de ajedrez. La moralidad es útil cuando funciona, pero nunca es la razón para actuar. El poder se obtiene, se mantiene y se usa — o alguien más lo hará.', en: 'For you, politics and life are chess games. Morality is useful when it works, but it\'s never the reason to act. Power is obtained, maintained and used — or someone else will do it.', fr: 'Pour toi, la politique et la vie sont des jeux d\'échecs. La moralité est utile quand elle fonctionne, mais elle n\'est jamais la raison d\'agir. Le pouvoir s\'obtient, se maintient et s\'utilise — ou quelqu\'un d\'autre le fera.', de: 'Für dich sind Politik und Leben Schachspiele. Moralität ist nützlich, wenn sie funktioniert, aber nie der Grund zu handeln. Macht wird erworben, erhalten und genutzt — oder jemand anderes wird es tun.', it: 'Per te, la politica e la vita sono giochi di scacchi. La moralità è utile quando funziona, ma non è mai la ragione per agire. Il potere si ottiene, si mantiene e si usa — o qualcun altro lo farà.', pt: 'Para você, política e vida são jogos de xadrez. A moralidade é útil quando funciona, mas nunca é a razão para agir. O poder se obtém, se mantém e se usa — ou outra pessoa o fará.' } },
    { name: { es: 'Immanuel Kant', en: 'Immanuel Kant', fr: 'Immanuel Kant', de: 'Immanuel Kant', it: 'Immanuel Kant', pt: 'Immanuel Kant' }, dimensions: ['P'], photo: '/characters/kant.jpg', description: { es: 'El filósofo del deber: los principios no se negocian.', en: 'The philosopher of duty: principles are not negotiable.', fr: 'Le philosophe du devoir: les principes ne se négocient pas.', de: 'Der Philosoph der Pflicht: Prinzipien sind nicht verhandelbar.', it: 'Il filosofo del dovere: i principi non si negoziano.', pt: 'O filósofo do dever: os princípios não se negociam.' }, philosophy: { es: 'Para ti, hay reglas que no se doblegan bajo ninguna circunstancia. Actúas según principios que podrías querer que todos siguieran. No porque sea conveniente, sino porque es lo correcto.', en: 'For you, there are rules that do not bend under any circumstances. You act according to principles you could want everyone to follow. Not because it\'s convenient, but because it\'s right.', fr: 'Pour toi, il y a des règles qui ne plient sous aucune circonstance. Tu agis selon des principes que tu pourrais vouloir que tout le monde suive. Non pas parce que c\'est commode, mais parce que c\'est juste.', de: 'Für dich gibt es Regeln, die sich unter keinen Umständen beugen. Du handelst nach Grundsätzen, die du dir wünschen könntest, dass alle sie befolgen. Nicht weil es bequem ist, sondern weil es richtig ist.', it: 'Per te, ci sono regole che non si piegano in nessuna circostanza. Agisci secondo principi che potresti voler far seguire a tutti. Non perché sia conveniente, ma perché è giusto.', pt: 'Para você, há regras que não se dobram sob nenhuma circunstância. Você age de acordo com princípios que gostaria que todos seguissem. Não porque seja conveniente, mas porque é correto.' } },
    { name: { es: 'Marco Aurelio', en: 'Marcus Aurelius', fr: 'Marc Aurèle', de: 'Marc Aurel', it: 'Marco Aurelio', pt: 'Marco Aurélio' }, dimensions: ['L'], photo: '/characters/marco.jpg', description: { es: 'Estratega virtuoso que nunca traicionó a quienes le eran leales.', en: 'Virtuous strategist who never betrayed those who were loyal to him.', fr: 'Stratège vertueux qui n\'a jamais trahi ceux qui lui étaient loyaux.', de: 'Tugendhafter Stratege, der diejenigen, die ihm treu waren, nie verriet.', it: 'Stratega virtuoso che non tradì mai coloro che gli erano leali.', pt: 'Estrategista virtuoso que nunca traiu aqueles que lhe eram leais.' }, philosophy: { es: 'Crees en la lealtad como fundamento de todo poder duradero. No por bondad ingenua, sino por convicción estratégica: la confianza es el activo más valioso que existe.', en: 'You believe in loyalty as the foundation of all lasting power. Not out of naive goodness, but by strategic conviction: trust is the most valuable asset there is.', fr: 'Tu crois en la loyauté comme fondement de tout pouvoir durable. Non par bonté naïve, mais par conviction stratégique: la confiance est l\'actif le plus précieux qui soit.', de: 'Du glaubst an Loyalität als Grundlage aller dauerhaften Macht. Nicht aus naiver Güte, sondern aus strategischer Überzeugung: Vertrauen ist das wertvollste Gut, das es gibt.', it: 'Credi nella lealtà come fondamento di ogni potere duraturo. Non per bontà ingenua, ma per convinzione strategica: la fiducia è il bene più prezioso che esista.', pt: 'Você acredita na lealdade como fundamento de todo poder duradouro. Não por bondade ingênua, mas por convicção estratégica: a confiança é o ativo mais valioso que existe.' } },
    { name: { es: 'Sun Tzu', en: 'Sun Tzu', fr: 'Sun Tzu', de: 'Sun Tzu', it: 'Sun Tzu', pt: 'Sun Tzu' }, dimensions: ['A'], photo: '/characters/suntzu.jpg', description: { es: 'El arte de la guerra: adaptarse al terreno es la única constante.', en: 'The art of war: adapting to the terrain is the only constant.', fr: 'L\'art de la guerre: s\'adapter au terrain est la seule constante.', de: 'Die Kunst des Krieges: sich an das Gelände anzupassen ist die einzige Konstante.', it: 'L\'arte della guerra: adattarsi al terreno è l\'unica costante.', pt: 'A arte da guerra: adaptar-se ao terreno é a única constante.' }, philosophy: { es: 'No tienes principios fijos ni estrategias predeterminadas. Tu fuerza está en leer el contexto y adaptarte. El agua no tiene forma propia — pero puede corroer la roca.', en: 'You have no fixed principles or predetermined strategies. Your strength lies in reading the context and adapting. Water has no fixed form — but it can corrode rock.', fr: 'Tu n\'as pas de principes fixes ni de stratégies prédéterminées. Ta force réside dans la lecture du contexte et l\'adaptation. L\'eau n\'a pas de forme propre — mais elle peut corroder la roche.', de: 'Du hast keine festen Prinzipien oder vorherbestimmten Strategien. Deine Stärke liegt darin, den Kontext zu lesen und dich anzupassen. Wasser hat keine eigene Form — aber es kann Fels zerfressen.', it: 'Non hai principi fissi né strategie predeterminate. La tua forza sta nel leggere il contesto e adattarti. L\'acqua non ha forma propria — ma può corrodere la roccia.', pt: 'Você não tem princípios fixos nem estratégias predeterminadas. Sua força está em ler o contexto e se adaptar. A água não tem forma própria — mas pode corroer a rocha.' } },
    { name: { es: 'Julio César', en: 'Julius Caesar', fr: 'Jules César', de: 'Julius Cäsar', it: 'Giulio Cesare', pt: 'Júlio César' }, dimensions: ['E', 'A'], photo: '/characters/caesar.jpg', description: { es: 'Estratega brillante que sabía cuándo actuar y cuándo esperar.', en: 'Brilliant strategist who knew when to act and when to wait.', fr: 'Stratège brillant qui savait quand agir et quand attendre.', de: 'Brillanter Stratege, der wusste, wann er handeln und wann er warten sollte.', it: 'Stratega brillante che sapeva quando agire e quando aspettare.', pt: 'Estrategista brilhante que sabia quando agir e quando esperar.' }, philosophy: { es: 'Combinas la visión estratégica con la flexibilidad táctica. Sabes leer el momento perfecto para actuar, y cuando llega, eres implacable. Tu peligro: la confianza excesiva en tu propio juicio.', en: 'You combine strategic vision with tactical flexibility. You know how to read the perfect moment to act, and when it arrives, you are relentless. Your danger: excessive confidence in your own judgment.', fr: 'Tu combines la vision stratégique avec la flexibilité tactique. Tu sais lire le moment parfait pour agir, et quand il arrive, tu es implacable. Ton danger: la confiance excessive dans ton propre jugement.', de: 'Du kombinierst strategische Vision mit taktischer Flexibilität. Du weißt, den perfekten Moment zum Handeln zu lesen, und wenn er kommt, bist du unerbittlich. Deine Gefahr: übermäßiges Vertrauen in dein eigenes Urteil.', it: 'Combini la visione strategica con la flessibilità tattica. Sai leggere il momento perfetto per agire, e quando arriva, sei implacabile. Il tuo pericolo: la fiducia eccessiva nel tuo giudizio.', pt: 'Você combina visão estratégica com flexibilidade tática. Você sabe ler o momento perfeito para agir, e quando chega, é implacável. Seu perigo: confiança excessiva em seu próprio julgamento.' } },
    { name: { es: 'Abraham Lincoln', en: 'Abraham Lincoln', fr: 'Abraham Lincoln', de: 'Abraham Lincoln', it: 'Abraham Lincoln', pt: 'Abraham Lincoln' }, dimensions: ['P', 'L'], photo: '/characters/lincoln.jpg', description: { es: 'Principios fuertes con lealtad genuina a quienes lo rodean.', en: 'Strong principles with genuine loyalty to those around him.', fr: 'Principes forts avec loyauté genuino envers ceux qui l\'entourent.', de: 'Starke Prinzipien mit echter Loyalität gegenüber denen um ihn herum.', it: 'Principi forti con genuina lealtà verso coloro che lo circondano.', pt: 'Princípios fortes com genuína lealdade àqueles ao seu redor.' }, philosophy: { es: 'Puedes ser firme en lo que crees sin necesitar traicionar a nadie. La lealtad y los principios se refuerzan mutuamente. No son límites — son la base de tu fuerza.', en: 'You can be firm in what you believe without needing to betray anyone. Loyalty and principles reinforce each other. They\'re not limitations — they\'re the foundation of your strength.', fr: 'Tu peux être ferme dans ce que tu crois sans avoir besoin de trahir qui que ce soit. La loyauté et les principes se renforcent mutuellement. Ce ne sont pas des limites — ce sont la base de ta force.', de: 'Du kannst in dem, was du glaubst, standhaft sein, ohne jemanden verraten zu müssen. Loyalität und Prinzipien verstärken sich gegenseitig. Das sind keine Einschränkungen — das ist die Grundlage deiner Stärke.', it: 'Puoi essere fermo in ciò che credi senza dover tradire nessuno. La lealtà e i principi si rafforzano a vicenda. Non sono limiti — sono la base della tua forza.', pt: 'Você pode ser firme no que acredita sem precisar trair ninguém. Lealdade e princípios se reforçam mutuamente. Não são limites — são a base da sua força.' } },
    { name: { es: 'Cleopatra', en: 'Cleopatra', fr: 'Cléopâtre', de: 'Kleopatra', it: 'Cleopatra', pt: 'Cleópatra' }, dimensions: ['E', 'L'], photo: '/characters/cleopatra.jpg', description: { es: 'Estratega que usó la lealtad como herramienta de poder.', en: 'Strategist who used loyalty as a tool of power.', fr: 'Stratège qui a utilisé la loyauté comme outil de pouvoir.', de: 'Strategin, die Loyalität als Machtwerkzeug einsetzte.', it: 'Stratega che usò la lealtà come strumento di potere.', pt: 'Estrategista que usou a lealdade como ferramenta de poder.' }, philosophy: { es: 'Entiendes que la lealtad es poder. Tus alianzas son genuinas en su utilidad mutua. No traicionas a los tuyos porque sabes que eso destruiría lo que construiste.', en: 'You understand that loyalty is power. Your alliances are genuine in their mutual utility. You don\'t betray yours because you know that would destroy what you built.', fr: 'Tu comprends que la loyauté est du pouvoir. Tes alliances sont genuinas dans leur utilité mutuelle. Tu ne trahis pas les tiens parce que tu sais que ça détruirait ce que tu as construit.', de: 'Du verstehst, dass Loyalität Macht ist. Deine Bündnisse sind in ihrer gegenseitigen Nützlichkeit echt. Du verrätst die Deinen nicht, weil du weißt, dass das zerstören würde, was du aufgebaut hast.', it: 'Capisci che la lealtà è potere. Le tue alleanze sono genuine nella loro utilità reciproca. Non tradisci i tuoi perché sai che ciò distruggerebbe quello che hai costruito.', pt: 'Você entende que lealdade é poder. Suas alianças são genuínas em sua utilidade mútua. Você não trai os seus porque sabe que isso destruiria o que construiu.' } },
    { name: { es: 'Angela Merkel', en: 'Angela Merkel', fr: 'Angela Merkel', de: 'Angela Merkel', it: 'Angela Merkel', pt: 'Angela Merkel' }, dimensions: ['P', 'A'], photo: '/characters/merkel.jpg', description: { es: 'Principios firmes con capacidad de adaptación pragmática.', en: 'Firm principles with capacity for pragmatic adaptation.', fr: 'Principes fermes avec capacité d\'adaptation pragmatique.', de: 'Feste Prinzipien mit Fähigkeit zur pragmatischen Anpassung.', it: 'Principi fermi con capacità di adattamento pragmatico.', pt: 'Princípios firmes com capacidade de adaptação pragmática.' }, philosophy: { es: 'Tienes valores que no se mueven, pero entiendes que el camino para honrarlos puede cambiar según las circunstancias. La firmeza en los fines, flexibilidad en los medios.', en: 'You have values that don\'t move, but you understand that the path to honoring them can change depending on circumstances. Firmness in ends, flexibility in means.', fr: 'Tu as des valeurs qui ne bougent pas, mais tu comprends que le chemin pour les honorer peut changer selon les circonstances. Fermeté dans les fins, flexibilité dans les moyens.', de: 'Du hast Werte, die sich nicht bewegen, aber du verstehst, dass der Weg, sie zu ehren, je nach Umständen variieren kann. Festigkeit in den Zielen, Flexibilität in den Mitteln.', it: 'Hai valori che non si muovono, ma capisci che il percorso per onorarli può cambiare a seconda delle circostanze. Fermezza nei fini, flessibilità nei mezzi.', pt: 'Você tem valores que não se movem, mas entende que o caminho para honrá-los pode mudar de acordo com as circunstâncias. Firmeza nos fins, flexibilidade nos meios.' } },
  ],
};

export async function seedMachiavellian(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'machiavellian' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'machiavellian',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['dark-personality'],
      sortOrder: 4,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
