import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan red flag eres?', en: 'How much of a red flag are you?', fr: 'À quel point es-tu un red flag ?', de: 'Wie sehr bist du eine rote Flagge?', it: 'Quanto sei una red flag?', pt: 'O quanto você é uma red flag?' },
  description: { es: 'Todos tenemos algo. ¿Cuál es tu red flag principal y qué tan consciente eres de ella?', en: 'We all have something. What\'s your main red flag and how aware are you of it?', fr: 'Nous avons tous quelque chose. Quelle est ta principale red flag et dans quelle mesure en es-tu conscient(e) ?', de: 'Wir alle haben etwas. Was ist deine größte rote Flagge und wie bewusst bist du dir davon?', it: 'Abbiamo tutti qualcosa. Qual è la tua principale red flag e quanto ne sei consapevole?', pt: 'Todos temos algo. Qual é sua principal red flag e o quanto você está consciente dela?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { A: 'Apego Ansioso', C: 'Control', E: 'Evasión', S: 'Seguridad' },
    en: { A: 'Anxious Attachment', C: 'Control', E: 'Avoidance', S: 'Security' },
    fr: { A: 'Attachement Anxieux', C: 'Contrôle', E: 'Évitement', S: 'Sécurité' },
    de: { A: 'Ängstliche Bindung', C: 'Kontrolle', E: 'Vermeidung', S: 'Sicherheit' },
    it: { A: 'Attaccamento Ansioso', C: 'Controllo', E: 'Evasione', S: 'Sicurezza' },
    pt: { A: 'Apego Ansioso', C: 'Controle', E: 'Evasão', S: 'Segurança' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu pareja tarda en responder un mensaje. Ya pasaron dos horas.', en: 'Your partner takes a while to respond to a message. Two hours have passed.', fr: 'Ton partenaire met du temps à répondre à un message. Il s\'est déjà écoulé deux heures.', de: 'Dein Partner braucht eine Weile, um auf eine Nachricht zu antworten. Es sind bereits zwei Stunden vergangen.', it: 'Il tuo partner tarda a rispondere a un messaggio. Sono già passate due ore.', pt: 'Seu parceiro demora a responder uma mensagem. Já se passaram duas horas.' }, options: [
      { text: { es: 'Le mando varios mensajes más. Algo debe haber pasado.', en: 'I send several more messages. Something must have happened.', fr: 'Je lui envoie plusieurs autres messages. Il a dû se passer quelque chose.', de: 'Ich schicke noch mehrere Nachrichten. Irgendetwas muss passiert sein.', it: 'Mando altri messaggi. Dev\'essere successo qualcosa.', pt: 'Mando várias mensagens a mais. Algo deve ter acontecido.' }, dimension: 'A' },
      { text: { es: 'Le pregunto con quién está y qué está haciendo.', en: 'I ask who they\'re with and what they\'re doing.', fr: 'Je lui demande avec qui il/elle est et ce qu\'il/elle fait.', de: 'Ich frage, mit wem sie sind und was sie tun.', it: 'Gli chiedo con chi è e cosa sta facendo.', pt: 'Pergunto com quem está e o que está fazendo.' }, dimension: 'C' },
      { text: { es: 'Decido no pensar en ello hasta que responda.', en: 'I decide not to think about it until they respond.', fr: 'Je décide de ne pas y penser jusqu\'à ce qu\'il/elle réponde.', de: 'Ich beschließe, nicht daran zu denken, bis sie antworten.', it: 'Decido di non pensarci finché non risponde.', pt: 'Decido não pensar nisso até que responda.' }, dimension: 'E' },
      { text: { es: 'Asumo que está ocupado/a y sigo con mi día.', en: 'I assume they\'re busy and continue with my day.', fr: 'Je suppose qu\'il/elle est occupé(e) et continue ma journée.', de: 'Ich nehme an, dass sie beschäftigt sind, und mache mit meinem Tag weiter.', it: 'Presumo che sia occupato/a e continuo con la mia giornata.', pt: 'Presumo que está ocupado/a e sigo com meu dia.' }, dimension: 'S' },
    ] },
    { id: 2, situation: { es: 'Tu pareja tiene planes con amigos sin incluirte.', en: 'Your partner has plans with friends without including you.', fr: 'Ton partenaire a des projets avec des amis sans t\'inclure.', de: 'Dein Partner hat Pläne mit Freunden, ohne dich einzuschließen.', it: 'Il tuo partner ha piani con gli amici senza includerti.', pt: 'Seu parceiro tem planos com amigos sem te incluir.' }, options: [
      { text: { es: 'Me siento ansioso/a y busco formas de confirmar que está bien.', en: 'I feel anxious and look for ways to confirm they\'re okay.', fr: 'Je me sens anxieux/se et cherche des moyens de confirmer qu\'il/elle va bien.', de: 'Ich fühle mich ängstlich und suche nach Möglichkeiten zu bestätigen, dass er/sie okay ist.', it: 'Mi sento ansioso/a e cerco modi per confermare che stia bene.', pt: 'Me sinto ansioso/a e busco formas de confirmar que está bem.' }, dimension: 'A' },
      { text: { es: 'Le pregunto exactamente a dónde va, con quién y a qué hora vuelve.', en: 'I ask exactly where they\'re going, who with, and what time they\'ll be back.', fr: 'Je lui demande exactement où il/elle va, avec qui et à quelle heure il/elle revient.', de: 'Ich frage genau, wohin sie gehen, mit wem und wann sie zurück sind.', it: 'Gli chiedo esattamente dove va, con chi e a che ora torna.', pt: 'Pergunto exatamente onde vai, com quem e que horas volta.' }, dimension: 'C' },
      { text: { es: 'Bien, tengo tiempo para mí. Prefiero no pensar en sus planes.', en: 'Fine, I have time for myself. I prefer not to think about their plans.', fr: 'Bien, j\'ai du temps pour moi. Je préfère ne pas penser à ses plans.', de: 'Gut, ich habe Zeit für mich. Ich denke lieber nicht an ihre Pläne.', it: 'Bene, ho tempo per me. Preferisco non pensare ai suoi piani.', pt: 'Bem, tenho tempo para mim. Prefiro não pensar nos planos dele/dela.' }, dimension: 'E' },
      { text: { es: 'Me alegra que tenga vida social propia. Cada quien tiene la suya.', en: 'I\'m glad they have their own social life. Everyone has their own.', fr: 'Je suis content(e) qu\'il/elle ait sa propre vie sociale. Chacun a la sienne.', de: 'Ich freue mich, dass er/sie sein/ihr eigenes soziales Leben hat. Jeder hat seins.', it: 'Sono contento/a che abbia una vita sociale propria. Ognuno ha la sua.', pt: 'Fico feliz que tenha vida social própria. Cada um tem a sua.' }, dimension: 'S' },
    ] },
    { id: 3, situation: { es: 'Discuten y tu pareja dice que necesita espacio para pensar.', en: 'You argue and your partner says they need space to think.', fr: 'Vous vous disputez et ton partenaire dit qu\'il/elle a besoin d\'espace pour réfléchir.', de: 'Ihr streitet und dein Partner sagt, er/sie braucht Raum zum Nachdenken.', it: 'Litigate e il tuo partner dice che ha bisogno di spazio per pensare.', pt: 'Vocês discutem e seu parceiro diz que precisa de espaço para pensar.' }, options: [
      { text: { es: 'Me aterra. Busco la forma de resolver todo antes de que se vaya.', en: 'It terrifies me. I look for a way to resolve everything before they leave.', fr: 'Ça me terrifie. Je cherche un moyen de tout résoudre avant qu\'il/elle parte.', de: 'Es erschreckt mich. Ich suche einen Weg, alles zu lösen, bevor er/sie geht.', it: 'Mi spaventa. Cerco di risolvere tutto prima che se ne vada.', pt: 'Me aterroriza. Busco resolver tudo antes que vá embora.' }, dimension: 'A' },
      { text: { es: 'Le digo que no puede simplemente desaparecer en medio de un conflicto.', en: 'I tell them they can\'t just disappear in the middle of a conflict.', fr: 'Je lui dis qu\'il/elle ne peut pas simplement disparaître au milieu d\'un conflit.', de: 'Ich sage ihnen, dass sie nicht einfach mitten in einem Konflikt verschwinden können.', it: 'Gli dico che non può semplicemente sparire nel mezzo di un conflitto.', pt: 'Digo que não pode simplesmente desaparecer no meio de um conflito.' }, dimension: 'C' },
      { text: { es: 'Perfecto. Yo también necesito espacio. Se acabó la conversación.', en: 'Perfect. I also need space. The conversation is over.', fr: 'Parfait. J\'ai aussi besoin d\'espace. La conversation est terminée.', de: 'Perfekt. Ich brauche auch Raum. Das Gespräch ist beendet.', it: 'Perfetto. Anche io ho bisogno di spazio. La conversazione è finita.', pt: 'Perfeito. Também preciso de espaço. A conversa acabou.' }, dimension: 'E' },
      { text: { es: 'Respeto el espacio y le digo que estoy disponible cuando quiera hablar.', en: 'I respect the space and tell them I\'m available when they want to talk.', fr: 'Je respecte l\'espace et lui dis que je suis disponible quand il/elle veut parler.', de: 'Ich respektiere den Raum und sage, dass ich verfügbar bin, wenn er/sie reden möchte.', it: 'Rispetto lo spazio e gli dico che sono disponibile quando vuole parlare.', pt: 'Respeito o espaço e digo que estou disponível quando quiser conversar.' }, dimension: 'S' },
    ] },
    { id: 4, situation: { es: 'Te entera de que tu pareja tuvo una conversación larga con un/a ex.', en: 'You find out your partner had a long conversation with an ex.', fr: 'Tu apprends que ton partenaire a eu une longue conversation avec un(e) ex.', de: 'Du erfährst, dass dein Partner ein langes Gespräch mit einem/r Ex hatte.', it: 'Vieni a sapere che il tuo partner ha avuto una lunga conversazione con un/a ex.', pt: 'Você fica sabendo que seu parceiro teve uma longa conversa com um ex.' }, options: [
      { text: { es: 'Necesito ver el contenido de esa conversación. No puedo con la incertidumbre.', en: 'I need to see the content of that conversation. I can\'t handle the uncertainty.', fr: 'J\'ai besoin de voir le contenu de cette conversation. Je ne supporte pas l\'incertitude.', de: 'Ich muss den Inhalt dieses Gesprächs sehen. Ich kann die Ungewissheit nicht ertragen.', it: 'Ho bisogno di vedere il contenuto di quella conversazione. Non reggo l\'incertezza.', pt: 'Preciso ver o conteúdo dessa conversa. Não consigo lidar com a incerteza.' }, dimension: 'A' },
      { text: { es: 'Le establezco que no quiero que mantenga ese tipo de contacto.', en: 'I establish that I don\'t want them to maintain that type of contact.', fr: 'Je lui établis que je ne veux pas qu\'il/elle maintienne ce type de contact.', de: 'Ich stelle klar, dass ich nicht will, dass sie diese Art von Kontakt aufrechterhalten.', it: 'Stabilisco che non voglio che mantenga quel tipo di contatto.', pt: 'Estabeleço que não quero que mantenha esse tipo de contato.' }, dimension: 'C' },
      { text: { es: 'No digo nada, pero lo anoto mentalmente.', en: 'I say nothing, but I note it mentally.', fr: 'Je ne dis rien, mais je le note mentalement.', de: 'Ich sage nichts, aber ich merke es mir.', it: 'Non dico niente, ma lo noto mentalmente.', pt: 'Não digo nada, mas anoto mentalmente.' }, dimension: 'E' },
      { text: { es: 'Si confío en mi pareja, no hay razón para darle más peso del que tiene.', en: 'If I trust my partner, there\'s no reason to give it more weight than it deserves.', fr: 'Si je fais confiance à mon partenaire, il n\'y a pas de raison de lui donner plus de poids qu\'il n\'en mérite.', de: 'Wenn ich meinem Partner vertraue, gibt es keinen Grund, dem mehr Gewicht zu geben, als es verdient.', it: 'Se mi fido del mio partner, non c\'è ragione di dargli più peso di quello che ha.', pt: 'Se confio no meu parceiro, não há razão para dar mais peso do que merece.' }, dimension: 'S' },
    ] },
    { id: 5, situation: { es: 'Tu pareja hace algo que te molesta. ¿Cómo lo manejas?', en: 'Your partner does something that bothers you. How do you handle it?', fr: 'Ton partenaire fait quelque chose qui t\'agace. Comment le gères-tu ?', de: 'Dein Partner tut etwas, das dich stört. Wie gehst du damit um?', it: 'Il tuo partner fa qualcosa che ti infastidisce. Come lo gestisci?', pt: 'Seu parceiro faz algo que te incomoda. Como você lida com isso?' }, options: [
      { text: { es: 'Lo traigo a colación repetidamente hasta que quede claro que lo entendió.', en: 'I bring it up repeatedly until it\'s clear they understood.', fr: 'Je le soulève répétitivement jusqu\'à ce qu\'il soit clair qu\'il/elle a compris.', de: 'Ich bringe es wiederholt zur Sprache, bis klar ist, dass sie es verstanden haben.', it: 'Lo tiro fuori ripetutamente finché non è chiaro che ha capito.', pt: 'Trago à tona repetidamente até que fique claro que entendeu.' }, dimension: 'A' },
      { text: { es: 'Le digo exactamente qué debe cambiar para que no vuelva a pasar.', en: 'I tell them exactly what needs to change so it doesn\'t happen again.', fr: 'Je lui dis exactement ce qui doit changer pour que ça ne se reproduise pas.', de: 'Ich sage genau, was sich ändern muss, damit es nicht wieder passiert.', it: 'Gli dico esattamente cosa deve cambiare affinché non si ripeta.', pt: 'Digo exatamente o que deve mudar para não acontecer de novo.' }, dimension: 'C' },
      { text: { es: 'No digo nada pero me alejo emocionalmente.', en: 'I say nothing but distance myself emotionally.', fr: 'Je ne dis rien mais m\'éloigne émotionnellement.', de: 'Ich sage nichts, entferne mich aber emotional.', it: 'Non dico niente ma mi distacco emotivamente.', pt: 'Não digo nada mas me afasto emocionalmente.' }, dimension: 'E' },
      { text: { es: 'Se lo digo con calma una vez y confío en que lo considera.', en: 'I tell them calmly once and trust they\'ll consider it.', fr: 'Je le lui dis calmement une fois et fais confiance qu\'il/elle le prend en compte.', de: 'Ich sage es ruhig einmal und vertraue darauf, dass sie es bedenken.', it: 'Glielo dico con calma una volta e mi fido che lo consideri.', pt: 'Digo com calma uma vez e confio que vai considerar.' }, dimension: 'S' },
    ] },
    { id: 6, situation: { es: 'Tu pareja se hace amigo/a de alguien nuevo que te cae mal.', en: 'Your partner makes friends with someone new who you don\'t like.', fr: 'Ton partenaire se lie d\'amitié avec quelqu\'un de nouveau que tu n\'apprécies pas.', de: 'Dein Partner befreundet sich mit jemandem Neuen, den du nicht magst.', it: 'Il tuo partner si fa amico/a di qualcuno di nuovo che non ti è simpatico.', pt: 'Seu parceiro se torna amigo/a de alguém novo que você não curte.' }, options: [
      { text: { es: 'Le expreso mi incomodidad repetidamente esperando que lo entienda.', en: 'I repeatedly express my discomfort hoping they understand.', fr: 'J\'exprime mon malaise répétitivement en espérant qu\'il/elle comprenne.', de: 'Ich drücke wiederholt mein Unbehagen aus, in der Hoffnung, dass sie es verstehen.', it: 'Esprimo il mio disagio ripetutamente sperando che capisca.', pt: 'Expresso meu desconforto repetidamente esperando que entenda.' }, dimension: 'A' },
      { text: { es: 'Le hago comentarios sobre esa persona hasta que deje de frecuentarla.', en: 'I make comments about that person until they stop seeing them.', fr: 'Je fais des commentaires sur cette personne jusqu\'à ce qu\'il/elle arrête de la fréquenter.', de: 'Ich mache Kommentare über diese Person, bis sie aufhören, sich mit ihr zu treffen.', it: 'Faccio commenti su quella persona finché non smette di frequentarla.', pt: 'Faço comentários sobre essa pessoa até que pare de frequentá-la.' }, dimension: 'C' },
      { text: { es: 'Finjo que no me importa y espero que la amistad se acabe sola.', en: 'I pretend I don\'t care and wait for the friendship to end on its own.', fr: 'Je fais semblant de ne pas m\'en soucier et attends que l\'amitié se termine d\'elle-même.', de: 'Ich tue so, als würde es mir nichts ausmachen, und warte darauf, dass die Freundschaft von selbst endet.', it: 'Fingo di non preoccuparmene e aspetto che l\'amicizia finisca da sola.', pt: 'Finjo que não me importo e espero que a amizade acabe sozinha.' }, dimension: 'E' },
      { text: { es: 'Le digo que no me cae bien y confío en su criterio para manejar sus relaciones.', en: 'I tell them I don\'t like that person and trust their judgment to manage their relationships.', fr: 'Je lui dis que cette personne ne me plaît pas et fais confiance à son jugement pour gérer ses relations.', de: 'Ich sage, dass mir diese Person nicht gefällt, und vertraue auf sein/ihr Urteil bei der Verwaltung seiner/ihrer Beziehungen.', it: 'Gli dico che non mi è simpatico/a e mi fido del suo giudizio per gestire le sue relazioni.', pt: 'Digo que não curto essa pessoa e confio no critério dele/dela para gerenciar seus relacionamentos.' }, dimension: 'S' },
    ] },
    { id: 7, situation: { es: '¿Cómo reaccionas cuando sientes que tu pareja te presta menos atención que antes?', en: 'How do you react when you feel your partner pays you less attention than before?', fr: 'Comment réagis-tu quand tu sens que ton partenaire t\'accorde moins d\'attention qu\'avant ?', de: 'Wie reagierst du, wenn du das Gefühl hast, dass dein Partner dir weniger Aufmerksamkeit schenkt als zuvor?', it: 'Come reagisci quando senti che il tuo partner ti presta meno attenzione di prima?', pt: 'Como você reage quando sente que seu parceiro presta menos atenção em você do que antes?' }, options: [
      { text: { es: 'Me vuelvo más demandante para recuperar su atención.', en: 'I become more demanding to recover their attention.', fr: 'Je deviens plus exigeant(e) pour récupérer son attention.', de: 'Ich werde anspruchsvoller, um ihre Aufmerksamkeit zurückzugewinnen.', it: 'Divento più esigente per recuperare la sua attenzione.', pt: 'Fico mais exigente para recuperar a atenção dele/dela.' }, dimension: 'A' },
      { text: { es: 'Establezco que las reglas de la relación requieren cierta dedicación mínima.', en: 'I establish that the relationship\'s rules require a certain minimum dedication.', fr: 'J\'établis que les règles de la relation exigent un certain dévouement minimum.', de: 'Ich stelle fest, dass die Regeln der Beziehung eine gewisse Mindestwidmung erfordern.', it: 'Stabilisco che le regole della relazione richiedono una certa dedizione minima.', pt: 'Estabeleço que as regras do relacionamento requerem uma dedicação mínima.' }, dimension: 'C' },
      { text: { es: 'Me distancio también. Si no me da atención, yo tampoco.', en: 'I distance myself too. If they don\'t give me attention, neither do I.', fr: 'Je m\'éloigne aussi. S\'il/elle ne m\'accorde pas d\'attention, moi non plus.', de: 'Ich distanziere mich auch. Wenn sie mir keine Aufmerksamkeit schenken, tue ich es auch nicht.', it: 'Mi distacco anch\'io. Se non mi presta attenzione, nemmeno io.', pt: 'Me distancio também. Se não me presta atenção, eu também não.' }, dimension: 'E' },
      { text: { es: 'Lo menciono con calma para entender si hay algo pasando.', en: 'I mention it calmly to understand if something is going on.', fr: 'Je le mentionne calmement pour comprendre s\'il se passe quelque chose.', de: 'Ich erwähne es ruhig, um zu verstehen, ob etwas vor sich geht.', it: 'Lo menziono con calma per capire se c\'è qualcosa che non va.', pt: 'Menciono com calma para entender se algo está acontecendo.' }, dimension: 'S' },
    ] },
    { id: 8, situation: { es: '¿Cuál es tu mayor miedo en una relación?', en: 'What is your greatest fear in a relationship?', fr: 'Quelle est ta plus grande peur dans une relation ?', de: 'Was ist deine größte Angst in einer Beziehung?', it: 'Qual è la tua paura maggiore in una relazione?', pt: 'Qual é seu maior medo em um relacionamento?' }, options: [
      { text: { es: 'Ser abandonado/a. El rechazo es lo más aterrador.', en: 'Being abandoned. Rejection is the most terrifying thing.', fr: 'Être abandonné(e). Le rejet est ce qu\'il y a de plus terrifiant.', de: 'Verlassen zu werden. Ablehnung ist das Erschreckendste.', it: 'Essere abbandonato/a. Il rifiuto è la cosa più spaventosa.', pt: 'Ser abandonado/a. A rejeição é o mais assustador.' }, dimension: 'A' },
      { text: { es: 'Perder el control de la dinámica. No saber qué está pasando.', en: 'Losing control of the dynamic. Not knowing what\'s happening.', fr: 'Perdre le contrôle de la dynamique. Ne pas savoir ce qui se passe.', de: 'Die Kontrolle über die Dynamik zu verlieren. Nicht zu wissen, was passiert.', it: 'Perdere il controllo della dinamica. Non sapere cosa sta succedendo.', pt: 'Perder o controle da dinâmica. Não saber o que está acontecendo.' }, dimension: 'C' },
      { text: { es: 'Que la relación me absorba y pierda mi independencia.', en: 'That the relationship absorbs me and I lose my independence.', fr: 'Que la relation m\'absorbe et que je perde mon indépendance.', de: 'Dass mich die Beziehung aufsaugt und ich meine Unabhängigkeit verliere.', it: 'Che la relazione mi assorba e perda la mia indipendenza.', pt: 'Que o relacionamento me absorva e perca minha independência.' }, dimension: 'E' },
      { text: { es: 'Que haya falta de honestidad y el vínculo no sea genuino.', en: 'That there\'s a lack of honesty and the bond isn\'t genuine.', fr: 'Qu\'il manque d\'honnêteté et que le lien ne soit pas genuino.', de: 'Dass es an Ehrlichkeit mangelt und die Verbindung nicht echt ist.', it: 'Che ci sia mancanza di onestà e il legame non sia genuino.', pt: 'Que haja falta de honestidade e o vínculo não seja genuíno.' }, dimension: 'S' },
    ] },
    { id: 9, situation: { es: 'Tu pareja necesita tiempo para resolver algo personal. Te pide que le des espacio.', en: 'Your partner needs time to resolve something personal. They ask you to give them space.', fr: 'Ton partenaire a besoin de temps pour résoudre quelque chose de personnel. Il/elle te demande de lui donner de l\'espace.', de: 'Dein Partner braucht Zeit, um etwas Persönliches zu lösen. Er/sie bittet dich, ihm/ihr Raum zu geben.', it: 'Il tuo partner ha bisogno di tempo per risolvere qualcosa di personale. Ti chiede di dargli spazio.', pt: 'Seu parceiro precisa de tempo para resolver algo pessoal. Pede que dê espaço.' }, options: [
      { text: { es: 'Estoy de acuerdo, pero le mando mensajes de apoyo frecuentes para que sepa que estoy.', en: 'I agree, but I send frequent support messages so they know I\'m here.', fr: 'Je suis d\'accord, mais je lui envoie des messages de soutien fréquents pour qu\'il/elle sache que je suis là.', de: 'Ich stimme zu, aber ich schicke häufig Unterstützungsnachrichten, damit er/sie weiß, dass ich da bin.', it: 'Sono d\'accordo, ma mando messaggi di supporto frequenti affinché sappia che ci sono.', pt: 'Concordo, mas mando mensagens de apoio frequentes para que saiba que estou aqui.' }, dimension: 'A' },
      { text: { es: 'Le pregunto exactamente qué está resolviendo y cuándo estará disponible.', en: 'I ask exactly what they\'re resolving and when they\'ll be available.', fr: 'Je lui demande exactement ce qu\'il/elle résout et quand il/elle sera disponible.', de: 'Ich frage genau, was er/sie löst und wann er/sie verfügbar sein wird.', it: 'Gli chiedo esattamente cosa sta risolvendo e quando sarà disponibile.', pt: 'Pergunto exatamente o que está resolvendo e quando estará disponível.' }, dimension: 'C' },
      { text: { es: 'Perfecto. Desaparezco completamente.', en: 'Perfect. I disappear completely.', fr: 'Parfait. Je disparais complètement.', de: 'Perfekt. Ich verschwinde vollständig.', it: 'Perfetto. Sparisco completamente.', pt: 'Perfeito. Desapareço completamente.' }, dimension: 'E' },
      { text: { es: 'Le doy el espacio que necesita y le digo que estoy cuando me necesite.', en: 'I give them the space they need and tell them I\'m here when they need me.', fr: 'Je lui donne l\'espace dont il/elle a besoin et lui dis que je suis là quand il/elle a besoin de moi.', de: 'Ich gebe ihnen den Raum, den sie brauchen, und sage, dass ich da bin, wenn sie mich brauchen.', it: 'Gli do lo spazio di cui ha bisogno e gli dico che ci sono quando ha bisogno di me.', pt: 'Dou o espaço que precisa e digo que estou aqui quando precisar.' }, dimension: 'S' },
    ] },
    { id: 10, situation: { es: 'Ves a tu pareja sonreír al celular. No sabes con quién habla.', en: 'You see your partner smiling at their phone. You don\'t know who they\'re talking to.', fr: 'Tu vois ton partenaire sourire à son téléphone. Tu ne sais pas avec qui il/elle parle.', de: 'Du siehst deinen Partner sein Telefon anlächeln. Du weißt nicht, mit wem er/sie spricht.', it: 'Vedi il tuo partner sorridere al telefono. Non sai con chi sta parlando.', pt: 'Você vê seu parceiro sorrindo para o celular. Você não sabe com quem está falando.' }, options: [
      { text: { es: 'Inmediatamente necesito saber qué o quién le generó esa sonrisa.', en: 'I immediately need to know what or who caused that smile.', fr: 'J\'ai immédiatement besoin de savoir ce qui ou qui lui a procuré ce sourire.', de: 'Ich muss sofort wissen, was oder wer dieses Lächeln ausgelöst hat.', it: 'Ho immediatamente bisogno di sapere cosa o chi ha generato quel sorriso.', pt: 'Imediatamente preciso saber o que ou quem gerou esse sorriso.' }, dimension: 'A' },
      { text: { es: 'Le pregunto directamente con quién habla.', en: 'I ask them directly who they\'re talking to.', fr: 'Je lui demande directement avec qui il/elle parle.', de: 'Ich frage sie direkt, mit wem sie sprechen.', it: 'Gli chiedo direttamente con chi sta parlando.', pt: 'Pergunto diretamente com quem está falando.' }, dimension: 'C' },
      { text: { es: 'No digo nada pero lo registro como dato.', en: 'I say nothing but register it as data.', fr: 'Je ne dis rien mais l\'enregistre comme donnée.', de: 'Ich sage nichts, registriere es aber als Datum.', it: 'Non dico niente ma lo registro come dato.', pt: 'Não digo nada mas registro como dado.' }, dimension: 'E' },
      { text: { es: 'Me alegra que algo le genere alegría.', en: 'I\'m glad something brings them joy.', fr: 'Je suis content(e) que quelque chose lui procure de la joie.', de: 'Ich freue mich, dass etwas ihnen Freude bereitet.', it: 'Sono contento/a che qualcosa gli generi allegria.', pt: 'Fico feliz que algo gere alegria para ele/ela.' }, dimension: 'S' },
    ] },
  ],
  characters: [
    { name: { es: 'La Red Flag del Apego', en: 'The Attachment Red Flag', fr: 'Le Red Flag de l\'Attachement', de: 'Die Bindungs-Rote-Flagge', it: 'La Red Flag dell\'Attaccamento', pt: 'A Red Flag do Apego' }, dimensions: ['A'], photo: '/characters/attachment-red-flag.jpg', description: { es: 'El miedo al abandono lo/la hace demandante e invasivo/a.', en: 'Fear of abandonment makes them demanding and invasive.', fr: 'La peur de l\'abandon le/la rend exigeant(e) et envahissant(e).', de: 'Die Angst vor dem Verlassenwerden macht sie fordernd und aufdringlich.', it: 'La paura dell\'abbandono lo/la rende esigente e invadente.', pt: 'O medo do abandono o/a torna exigente e invasivo/a.' }, philosophy: { es: 'Tu red flag más visible viene del miedo. No controlas porque eres cruel — controlas porque tienes terror de que el otro se vaya. Ese miedo tiene una historia, probablemente larga. Y tiene solución, aunque no sea fácil.', en: 'Your most visible red flag comes from fear. You don\'t control because you\'re cruel — you control because you\'re terrified the other will leave. That fear has a history, probably a long one. And it has a solution, even if it\'s not easy.', fr: 'Ta red flag la plus visible vient de la peur. Tu ne contrôles pas parce que tu es cruel(le) — tu contrôles parce que tu as terreur que l\'autre parte. Cette peur a une histoire, probablement longue. Et elle a une solution, même si ce n\'est pas facile.', de: 'Deine sichtbarste rote Flagge kommt aus der Angst. Du kontrollierst nicht, weil du grausam bist — du kontrollierst, weil du Angst hast, dass der andere geht. Diese Angst hat eine Geschichte, wahrscheinlich eine lange. Und sie hat eine Lösung, auch wenn sie nicht einfach ist.', it: 'La tua red flag più visibile viene dalla paura. Non controlli perché sei crudele — controlli perché hai terrore che l\'altro se ne vada. Quella paura ha una storia, probabilmente lunga. E ha una soluzione, anche se non è facile.', pt: 'Sua red flag mais visível vem do medo. Você não controla porque é cruel — controla porque tem terror de que o outro vá embora. Esse medo tem uma história, provavelmente longa. E tem solução, mesmo que não seja fácil.' } },
    { name: { es: 'La Red Flag del Control', en: 'The Control Red Flag', fr: 'Le Red Flag du Contrôle', de: 'Die Kontroll-Rote-Flagge', it: 'La Red Flag del Controllo', pt: 'A Red Flag do Controle' }, dimensions: ['C'], photo: '/characters/control-red-flag.jpg', description: { es: 'Necesita saber todo. Establecer límites para todo. Controlar todo.', en: 'Needs to know everything. Establish limits for everything. Control everything.', fr: 'A besoin de tout savoir. Établir des limites pour tout. Contrôler tout.', de: 'Muss alles wissen. Grenzen für alles setzen. Alles kontrollieren.', it: 'Ha bisogno di sapere tutto. Stabilire limiti per tutto. Controllare tutto.', pt: 'Precisa saber tudo. Estabelecer limites para tudo. Controlar tudo.' }, philosophy: { es: 'Tu red flag es el control. No lo llamas así — lo llamas cuidado, claridad, expectativas razonables. Pero en el fondo, la necesidad de controlar la dinámica de la relación dice algo sobre lo que no puedes controlar dentro de ti.', en: 'Your red flag is control. You don\'t call it that — you call it care, clarity, reasonable expectations. But deep down, the need to control the relationship\'s dynamic says something about what you can\'t control within yourself.', fr: 'Ta red flag est le contrôle. Tu ne l\'appelles pas ainsi — tu l\'appelles soin, clarté, attentes raisonnables. Mais au fond, le besoin de contrôler la dynamique de la relation dit quelque chose sur ce que tu ne peux pas contrôler en toi.', de: 'Deine rote Flagge ist die Kontrolle. Du nennst sie nicht so — du nennst es Fürsorge, Klarheit, vernünftige Erwartungen. Aber im Grunde sagt das Bedürfnis, die Dynamik der Beziehung zu kontrollieren, etwas über das aus, was du in dir selbst nicht kontrollieren kannst.', it: 'La tua red flag è il controllo. Non lo chiami così — lo chiami cura, chiarezza, aspettative ragionevoli. Ma in fondo, il bisogno di controllare la dinamica della relazione dice qualcosa su quello che non puoi controllare dentro di te.', pt: 'Sua red flag é o controle. Você não chama assim — chama de cuidado, clareza, expectativas razoáveis. Mas no fundo, a necessidade de controlar a dinâmica do relacionamento diz algo sobre o que você não consegue controlar dentro de si.' } },
    { name: { es: 'La Red Flag de la Evasión', en: 'The Avoidance Red Flag', fr: 'Le Red Flag de l\'Évitement', de: 'Die Vermeidungs-Rote-Flagge', it: 'La Red Flag dell\'Evasione', pt: 'A Red Flag da Evasão' }, dimensions: ['E'], photo: '/characters/evasion-red-flag.jpg', description: { es: 'Desaparece emocionalmente cuando hay conflicto o cercanía.', en: 'Disappears emotionally when there\'s conflict or closeness.', fr: 'Disparaît émotionnellement quand il y a conflit ou proximité.', de: 'Verschwindet emotional, wenn es Konflikte oder Nähe gibt.', it: 'Sparisce emotivamente quando c\'è conflitto o vicinanza.', pt: 'Desaparece emocionalmente quando há conflito ou proximidade.' }, philosophy: { es: 'Tu red flag es invisible: no atacas, simplemente no estás. Cuando las cosas se ponen difíciles o íntimas, te desconectas. No es indiferencia — es protección. Y la persona al otro lado no siempre puede ver la diferencia.', en: 'Your red flag is invisible: you don\'t attack, you simply aren\'t there. When things get difficult or intimate, you disconnect. It\'s not indifference — it\'s protection. And the person on the other side can\'t always see the difference.', fr: 'Ta red flag est invisible: tu n\'attaques pas, tu n\'es simplement pas là. Quand les choses deviennent difficiles ou intimes, tu te déconnectes. Ce n\'est pas de l\'indifférence — c\'est de la protection. Et la personne de l\'autre côté ne peut pas toujours voir la différence.', de: 'Deine rote Flagge ist unsichtbar: du greifst nicht an, du bist einfach nicht da. Wenn es schwierig oder intim wird, trennst du die Verbindung. Es ist keine Gleichgültigkeit — es ist Schutz. Und die Person auf der anderen Seite kann den Unterschied nicht immer sehen.', it: 'La tua red flag è invisibile: non attacchi, semplicemente non ci sei. Quando le cose si fanno difficili o intime, ti disconnetti. Non è indifferenza — è protezione. E la persona dall\'altro lato non sempre riesce a vedere la differenza.', pt: 'Sua red flag é invisível: você não ataca, simplesmente não está. Quando as coisas ficam difíceis ou íntimas, você se desconecta. Não é indiferença — é proteção. E a pessoa do outro lado nem sempre consegue ver a diferença.' } },
    { name: { es: 'La Base Segura', en: 'The Secure Base', fr: 'La Base Sécurisée', de: 'Die Sichere Basis', it: 'La Base Sicura', pt: 'A Base Segura' }, dimensions: ['S'], photo: '/characters/secure-base.jpg', description: { es: 'Confía, comunica, respeta. El tipo de pareja que todos dicen querer.', en: 'Trusts, communicates, respects. The type of partner everyone says they want.', fr: 'Fait confiance, communique, respecte. Le type de partenaire que tout le monde dit vouloir.', de: 'Vertraut, kommuniziert, respektiert. Der Typ Partner, den alle sagen zu wollen.', it: 'Fidato, comunicativo, rispettoso. Il tipo di partner che tutti dicono di volere.', pt: 'Confia, comunica, respeita. O tipo de parceiro que todos dizem querer.' }, philosophy: { es: 'No eres perfecta/o. Pero has trabajado en crear una base segura desde la cual relacionarte. Confías hasta que hay razón para no hacerlo. Comunicas en lugar de asumir. Respetas en lugar de controlar.', en: 'You\'re not perfect. But you\'ve worked on creating a secure base from which to relate. You trust until there\'s reason not to. You communicate instead of assuming. You respect instead of controlling.', fr: 'Tu n\'es pas parfait(e). Mais tu as travaillé à créer une base sécurisée à partir de laquelle te lier. Tu fais confiance jusqu\'à ce qu\'il y ait une raison de ne pas le faire. Tu communiques au lieu d\'assumer. Tu respectes au lieu de contrôler.', de: 'Du bist nicht perfekt. Aber du hast daran gearbeitet, eine sichere Basis zu schaffen, von der aus du dich beziehst. Du vertraust, bis es einen Grund gibt, das nicht zu tun. Du kommunizierst, anstatt zu vermuten. Du respektierst, anstatt zu kontrollieren.', it: 'Non sei perfetto/a. Ma hai lavorato per creare una base sicura da cui relazionarti. Ti fidi fino a quando c\'è una ragione per non farlo. Comunichi invece di presumere. Rispetti invece di controllare.', pt: 'Você não é perfeito/a. Mas trabalhou para criar uma base segura a partir da qual se relacionar. Você confia até que haja razão para não confiar. Você comunica em vez de presumir. Você respeita em vez de controlar.' } },
    { name: { es: 'El Ansioso-Controlador', en: 'The Anxious Controller', fr: 'L\'Anxieux Contrôleur', de: 'Der Ängstliche Kontrolleur', it: 'L\'Ansioso-Controllore', pt: 'O Ansioso-Controlador' }, dimensions: ['A', 'C'], photo: '/characters/anxious-controller.jpg', description: { es: 'Ansioso por dentro, controlador por fuera.', en: 'Anxious on the inside, controlling on the outside.', fr: 'Anxieux à l\'intérieur, contrôlant à l\'extérieur.', de: 'Innen ängstlich, außen kontrollierend.', it: 'Ansioso dentro, controllore fuori.', pt: 'Ansioso por dentro, controlador por fora.' }, philosophy: { es: 'La ansiedad por el abandono se expresa como control. Es el ciclo más difícil porque el control aumenta la ansiedad y la ansiedad aumenta el control. Salir de ese loop requiere trabajar en el miedo, no en el control.', en: 'Anxiety about abandonment expresses itself as control. It\'s the hardest cycle because control increases anxiety and anxiety increases control. Getting out of that loop requires working on the fear, not the control.', fr: 'L\'anxiété d\'abandon s\'exprime comme contrôle. C\'est le cycle le plus difficile car le contrôle augmente l\'anxiété et l\'anxiété augmente le contrôle. Sortir de cette boucle nécessite de travailler sur la peur, pas sur le contrôle.', de: 'Trennungsangst äußert sich als Kontrolle. Es ist der schwierigste Kreislauf, weil Kontrolle die Angst erhöht und Angst die Kontrolle erhöht. Aus dieser Schleife herauszukommen erfordert, an der Angst zu arbeiten, nicht an der Kontrolle.', it: 'L\'ansia per l\'abbandono si esprime come controllo. È il ciclo più difficile perché il controllo aumenta l\'ansia e l\'ansia aumenta il controllo. Uscire da quel loop richiede di lavorare sulla paura, non sul controllo.', pt: 'A ansiedade pelo abandono se expressa como controle. É o ciclo mais difícil porque o controle aumenta a ansiedade e a ansiedade aumenta o controle. Sair desse loop requer trabalhar no medo, não no controle.' } },
    { name: { es: 'El Evasivo Ansioso', en: 'The Anxious Avoider', fr: 'L\'Évitant Anxieux', de: 'Der Ängstliche Ausweicher', it: 'L\'Evasivo Ansioso', pt: 'O Evasivo Ansioso' }, dimensions: ['A', 'E'], photo: '/characters/evasive-anxious.jpg', description: { es: 'Teme el abandono pero huye cuando hay demasiada cercanía.', en: 'Fears abandonment but flees when there\'s too much closeness.', fr: 'Craint l\'abandon mais fuit quand il y a trop de proximité.', de: 'Fürchtet das Verlassenwerden, flieht aber, wenn zu viel Nähe da ist.', it: 'Teme l\'abbandono ma fugge quando c\'è troppa vicinanza.', pt: 'Teme o abandono mas foge quando há muita proximidade.' }, philosophy: { es: 'Eres la contradicción más dolorosa: necesitas al otro pero te asusta tenerlo. Te alejas para protegerte del rechazo anticipado. El resultado: a veces eres tú quien genera el abandono que más temes.', en: 'You\'re the most painful contradiction: you need the other but you\'re afraid of having them. You pull away to protect yourself from anticipated rejection. The result: sometimes you\'re the one who generates the very abandonment you fear most.', fr: 'Tu es la contradiction la plus douloureuse: tu as besoin de l\'autre mais tu as peur de l\'avoir. Tu t\'éloignes pour te protéger du rejet anticipé. Le résultat: parfois c\'est toi qui génères l\'abandon que tu crains le plus.', de: 'Du bist der schmerzhafteste Widerspruch: Du brauchst den anderen, aber du hast Angst, ihn zu haben. Du ziehst dich zurück, um dich vor dem antizipierten Ablehnen zu schützen. Das Ergebnis: Manchmal bist du derjenige, der das Verlassenwerden erzeugt, das du am meisten fürchtest.', it: 'Sei la contraddizione più dolorosa: hai bisogno dell\'altro ma ti spaventa averlo. Ti allontani per proteggerti dal rifiuto anticipato. Il risultato: a volte sei tu a generare l\'abbandono che temi di più.', pt: 'Você é a contradição mais dolorosa: precisa do outro mas tem medo de tê-lo. Você se afasta para se proteger da rejeição antecipada. O resultado: às vezes é você quem gera o abandono que mais teme.' } },
    { name: { es: 'El Controlador Evasivo', en: 'The Controlling Avoider', fr: 'Le Contrôleur Évitant', de: 'Der Kontrollierende Ausweicher', it: 'Il Controllore Evasivo', pt: 'O Controlador Evasivo' }, dimensions: ['C', 'E'], photo: '/characters/controlling-evasive.jpg', description: { es: 'Controla cuando está presente, desaparece cuando no puede.', en: 'Controls when present, disappears when they can\'t.', fr: 'Contrôle quand il/elle est présent(e), disparaît quand il/elle ne peut pas.', de: 'Kontrolliert, wenn präsent, verschwindet, wenn sie nicht können.', it: 'Controlla quando è presente, sparisce quando non può.', pt: 'Controla quando está presente, desaparece quando não consegue.' }, philosophy: { es: 'Alternas entre control total y desaparición total. Cuando estás, todo tiene que seguir tus reglas. Cuando no puedes con eso, te vas. El otro/a nunca sabe qué esperar.', en: 'You alternate between total control and total disappearance. When you\'re there, everything has to follow your rules. When you can\'t handle that, you leave. The other never knows what to expect.', fr: 'Tu alternes entre contrôle total et disparition totale. Quand tu es là, tout doit suivre tes règles. Quand tu ne peux pas avec ça, tu pars. L\'autre ne sait jamais à quoi s\'attendre.', de: 'Du wechselst zwischen totaler Kontrolle und totalem Verschwinden ab. Wenn du da bist, muss alles deinen Regeln folgen. Wenn du das nicht kannst, gehst du. Der andere weiß nie, was er erwarten soll.', it: 'Alterni tra controllo totale e sparizione totale. Quando sei presente, tutto deve seguire le tue regole. Quando non riesci a gestirlo, te ne vai. L\'altro/a non sa mai cosa aspettarsi.', pt: 'Você alterna entre controle total e desaparecimento total. Quando está, tudo tem que seguir suas regras. Quando não consegue com isso, vai embora. O outro/a nunca sabe o que esperar.' } },
    { name: { es: 'La Pareja en Proceso', en: 'The Partner in Progress', fr: 'Le Partenaire en Progrès', de: 'Der Partner in Entwicklung', it: 'Il Partner in Processo', pt: 'O Parceiro em Processo' }, dimensions: ['S', 'A'], photo: '/characters/processing-partner.jpg', description: { es: 'Tiene ansiedad pero trabaja activamente en ella.', en: 'Has anxiety but actively works on it.', fr: 'A de l\'anxiété mais y travaille activement.', de: 'Hat Angst, arbeitet aber aktiv daran.', it: 'Ha ansia ma ci lavora attivamente.', pt: 'Tem ansiedade mas trabalha ativamente nela.' }, philosophy: { es: 'Tienes el apego ansioso pero lo conoces y lo trabajas. Eso no significa que no aparezca — significa que cada vez lo gestionas mejor. La diferencia entre el ansioso que trabaja y el que no es exactamente esa conciencia.', en: 'You have anxious attachment but you know it and work on it. That doesn\'t mean it doesn\'t appear — it means you manage it better each time. The difference between the anxious person who works on it and the one who doesn\'t is exactly that awareness.', fr: 'Tu as l\'attachement anxieux mais tu le connais et tu y travailles. Ça ne veut pas dire qu\'il n\'apparaît pas — ça veut dire que tu le gères de mieux en mieux. La différence entre l\'anxieux qui y travaille et celui qui ne le fait pas, c\'est exactement cette conscience.', de: 'Du hast ängstliche Bindung, aber du kennst sie und arbeitest daran. Das bedeutet nicht, dass sie nicht erscheint — es bedeutet, dass du sie jedes Mal besser handhabst. Der Unterschied zwischen dem Ängstlichen, der daran arbeitet, und dem, der es nicht tut, ist genau dieses Bewusstsein.', it: 'Hai l\'attaccamento ansioso ma lo conosci e ci lavori. Questo non significa che non appaia — significa che ogni volta lo gestisci meglio. La differenza tra l\'ansioso che ci lavora e quello che non lo fa è esattamente quella consapevolezza.', pt: 'Você tem o apego ansioso mas o conhece e trabalha nele. Isso não significa que não aparece — significa que cada vez você o gerencia melhor. A diferença entre o ansioso que trabalha e o que não trabalha é exatamente essa consciência.' } },
  ],
};

export async function seedRedFlag(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'red-flag' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'red-flag',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['relationships'],
      sortOrder: 1,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
