import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan buen/a amigo/a eres?', en: 'How good a friend are you?', fr: 'À quel point es-tu un(e) bon(ne) ami(e) ?', de: 'Wie gut ein Freund/eine Freundin bist du?', it: 'Quanto sei un buon/a amico/a?', pt: 'O quanto você é um bom/boa amigo/a?' },
  description: { es: 'Todos creemos ser buenos amigos. Las situaciones difíciles revelan la verdad.', en: 'We all believe we\'re good friends. Difficult situations reveal the truth.', fr: 'Nous croyons tous être de bons amis. Les situations difficiles révèlent la vérité.', de: 'Wir alle glauben, gute Freunde zu sein. Schwierige Situationen offenbaren die Wahrheit.', it: 'Tutti crediamo di essere buoni amici. Le situazioni difficili rivelano la verità.', pt: 'Todos acreditamos ser bons amigos. As situações difíceis revelam a verdade.' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { P: 'Presencia', L: 'Lealtad', H: 'Honestidad', A: 'Autonomía' },
    en: { P: 'Presence', L: 'Loyalty', H: 'Honesty', A: 'Autonomy' },
    fr: { P: 'Présence', L: 'Loyauté', H: 'Honnêteté', A: 'Autonomie' },
    de: { P: 'Präsenz', L: 'Loyalität', H: 'Ehrlichkeit', A: 'Autonomie' },
    it: { P: 'Presenza', L: 'Lealtà', H: 'Onestà', A: 'Autonomia' },
    pt: { P: 'Presença', L: 'Lealdade', H: 'Honestidade', A: 'Autonomia' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu amigo/a te llama a las 2am llorando. Tienes una presentación crucial mañana.', en: 'Your friend calls you at 2am crying. You have a crucial presentation tomorrow.', fr: 'Ton/ta ami(e) t\'appelle à 2h du matin en pleurant. Tu as une présentation cruciale demain.', de: 'Dein Freund/deine Freundin ruft dich um 2 Uhr morgens weinend an. Du hast morgen eine wichtige Präsentation.', it: 'Il tuo amico/a ti chiama alle 2am piangendo. Hai una presentazione cruciale domani.', pt: 'Seu/sua amigo/a te liga às 2h da manhã chorando. Você tem uma apresentação crucial amanhã.' }, options: [
      { text: { es: 'Contesto y estoy el tiempo que necesite. La presentación puede esperar.', en: 'I answer and stay as long as they need. The presentation can wait.', fr: 'Je réponds et reste le temps qu\'il/elle a besoin. La présentation peut attendre.', de: 'Ich nehme ab und bleibe so lange wie nötig. Die Präsentation kann warten.', it: 'Rispondo e rimango il tempo necessario. La presentazione può aspettare.', pt: 'Atendo e fico o tempo que precisar. A apresentação pode esperar.' }, dimension: 'P' },
      { text: { es: 'Contesto, le dedico 30 minutos y le propongo hablar mañana más despacio.', en: 'I answer, dedicate 30 minutes, and suggest talking more slowly tomorrow.', fr: 'Je réponds, lui consacre 30 minutes et propose de parler plus calmement demain.', de: 'Ich nehme ab, widme ihm/ihr 30 Minuten und schlage vor, morgen ausführlicher zu reden.', it: 'Rispondo, gli dedico 30 minuti e propongo di parlare domani con più calma.', pt: 'Atendo, dedico 30 minutos e proponho conversar mais devagar amanhã.' }, dimension: 'L' },
      { text: { es: 'Contesto y le digo honestamente que tengo que dormir, pero que mañana hablamos.', en: 'I answer and honestly tell them I need to sleep, but we\'ll talk tomorrow.', fr: 'Je réponds et lui dis honnêtement que je dois dormir, mais que demain nous parlons.', de: 'Ich nehme ab und sage ihm/ihr ehrlich, dass ich schlafen muss, aber wir morgen reden.', it: 'Rispondo e gli dico onestamente che devo dormire, ma che domani parliamo.', pt: 'Atendo e digo honestamente que preciso dormir, mas que amanhã conversamos.' }, dimension: 'H' },
      { text: { es: 'Mando un audio de voz diciéndole que no puedo ahora pero que lo quiero.', en: 'I send a voice message saying I can\'t right now but I love them.', fr: 'J\'envoie un message vocal en disant que je ne peux pas maintenant mais que je les aime.', de: 'Ich sende eine Sprachnachricht, dass ich jetzt nicht kann, aber sie/ihn liebe.', it: 'Mando un messaggio vocale dicendogli che non posso adesso ma che gli voglio bene.', pt: 'Mando um áudio dizendo que não posso agora mas que o/a amo.' }, dimension: 'A' },
    ] },
    { id: 2, situation: { es: 'Tu mejor amigo/a va a tomar una decisión que crees que va a arruinar su vida.', en: 'Your best friend is going to make a decision you think will ruin their life.', fr: 'Ton/ta meilleur(e) ami(e) va prendre une décision que tu penses va ruiner sa vie.', de: 'Dein bester Freund/deine beste Freundin wird eine Entscheidung treffen, von der du denkst, dass sie ihr Leben ruinieren wird.', it: 'Il tuo migliore amico/a sta per prendere una decisione che pensi rovinerà la sua vita.', pt: 'Seu/sua melhor amigo/a vai tomar uma decisão que você acha que vai arruinar a vida dele/dela.' }, options: [
      { text: { es: 'Me siento con él/ella el tiempo que haga falta para entender su perspectiva primero.', en: 'I sit with them as long as needed to understand their perspective first.', fr: 'Je m\'assieds avec lui/elle le temps qu\'il faut pour comprendre sa perspective d\'abord.', de: 'Ich setze mich mit ihm/ihr so lange hin, wie nötig, um seine/ihre Perspektive zuerst zu verstehen.', it: 'Mi siedo con lui/lei il tempo necessario per capire prima la sua prospettiva.', pt: 'Sento com ele/ela o tempo que for preciso para entender a perspectiva primeiro.' }, dimension: 'P' },
      { text: { es: 'Le digo lo que pienso una vez y después lo apoyo sin condiciones.', en: 'I tell them what I think once and then support them unconditionally.', fr: 'Je lui dis ce que je pense une fois et ensuite je le/la soutiens sans conditions.', de: 'Ich sage ihm/ihr einmal, was ich denke, und unterstütze ihn/sie dann bedingungslos.', it: 'Gli dico cosa penso una volta e poi lo supporto senza condizioni.', pt: 'Digo o que penso uma vez e depois o/a apoio sem condições.' }, dimension: 'L' },
      { text: { es: 'Le digo lo que pienso con toda claridad aunque no le guste.', en: 'I tell them what I think with complete clarity even if they don\'t like it.', fr: 'Je lui dis ce que je pense avec toute clarté même si ça ne lui plaît pas.', de: 'Ich sage ihm/ihr klar meine Meinung, auch wenn es ihm/ihr nicht gefällt.', it: 'Gli dico cosa penso con tutta chiarezza anche se non gli piace.', pt: 'Digo o que penso com toda clareza mesmo que não goste.' }, dimension: 'H' },
      { text: { es: 'Lo apoyo en su decisión. No es mi vida ni mi elección.', en: 'I support them in their decision. It\'s not my life or my choice.', fr: 'Je le/la soutiens dans sa décision. Ce n\'est pas ma vie ni mon choix.', de: 'Ich unterstütze ihn/sie in seiner/ihrer Entscheidung. Es ist nicht mein Leben oder meine Wahl.', it: 'Lo supporto nella sua decisione. Non è la mia vita né la mia scelta.', pt: 'Apoio na decisão. Não é minha vida nem minha escolha.' }, dimension: 'A' },
    ] },
    { id: 3, situation: { es: 'Descubres que tu amigo/a está siendo engañado/a por su pareja. Tienes pruebas.', en: 'You discover your friend is being cheated on by their partner. You have proof.', fr: 'Tu découvres que ton/ta ami(e) est trompé(e) par son/sa partenaire. Tu as des preuves.', de: 'Du entdeckst, dass dein Freund/deine Freundin von seinem/ihrem Partner betrogen wird. Du hast Beweise.', it: 'Scopri che il tuo amico/a viene tradito/a dal suo partner. Hai prove.', pt: 'Você descobre que seu/sua amigo/a está sendo traído/a pelo parceiro. Você tem provas.' }, options: [
      { text: { es: 'Busco el momento y el lugar correctos para hablar con él/ella en persona.', en: 'I look for the right moment and place to talk with them in person.', fr: 'Je cherche le bon moment et le bon endroit pour lui parler en personne.', de: 'Ich suche den richtigen Moment und Ort, um mit ihm/ihr persönlich zu reden.', it: 'Cerco il momento e il posto giusto per parlare con lui/lei di persona.', pt: 'Busco o momento e lugar certos para falar com ele/ela pessoalmente.' }, dimension: 'P' },
      { text: { es: 'Espero a que me dé alguna señal de que quiere hablar de su relación.', en: 'I wait for them to give me some signal that they want to talk about their relationship.', fr: 'J\'attends qu\'il/elle me donne un signal qu\'il/elle veut parler de sa relation.', de: 'Ich warte darauf, dass er/sie mir ein Signal gibt, dass er/sie über seine/ihre Beziehung reden möchte.', it: 'Aspetto che mi dia qualche segnale di voler parlare della sua relazione.', pt: 'Espero que me dê algum sinal de que quer falar sobre o relacionamento.' }, dimension: 'L' },
      { text: { es: 'Le digo inmediatamente. Tiene derecho a saber.', en: 'I tell them immediately. They have the right to know.', fr: 'Je lui dis immédiatement. Il/elle a le droit de savoir.', de: 'Ich sage es ihm/ihr sofort. Er/sie hat das Recht zu wissen.', it: 'Glielo dico immediatamente. Ha il diritto di sapere.', pt: 'Digo imediatamente. Ele/ela tem o direito de saber.' }, dimension: 'H' },
      { text: { es: 'No me meto. Es su relación y quizás hay cosas que no sé.', en: 'I don\'t get involved. It\'s their relationship and maybe there are things I don\'t know.', fr: 'Je ne m\'en mêle pas. C\'est sa relation et peut-être qu\'il y a des choses que je ne sais pas.', de: 'Ich mische mich nicht ein. Es ist seine/ihre Beziehung und vielleicht gibt es Dinge, die ich nicht weiß.', it: 'Non mi intrometto. È la sua relazione e forse ci sono cose che non so.', pt: 'Não me meto. É o relacionamento dele/dela e talvez haja coisas que não sei.' }, dimension: 'A' },
    ] },
    { id: 4, situation: { es: 'Tu amigo/a cancela planes frecuentemente. Cuando lo hace, siempre es al último momento.', en: 'Your friend cancels plans frequently. When they do, it\'s always at the last minute.', fr: 'Ton/ta ami(e) annule les plans fréquemment. Quand il/elle le fait, c\'est toujours à la dernière minute.', de: 'Dein Freund/deine Freundin sagt Pläne häufig ab. Wenn er/sie es tut, ist es immer in letzter Minute.', it: 'Il tuo amico/a cancella piani frequentemente. Quando lo fa, è sempre all\'ultimo momento.', pt: 'Seu/sua amigo/a cancela planos frequentemente. Quando faz isso, é sempre em cima da hora.' }, options: [
      { text: { es: 'Hablo con él/ella de lo que está pasando. Algo debe estar pasando.', en: 'I talk to them about what\'s happening. Something must be going on.', fr: 'Je lui parle de ce qui se passe. Il doit se passer quelque chose.', de: 'Ich rede mit ihm/ihr darüber, was los ist. Irgendetwas muss los sein.', it: 'Parlo con lui/lei di quello che sta succedendo. Qualcosa deve stare succedendo.', pt: 'Falo com ele/ela sobre o que está acontecendo. Algo deve estar acontecendo.' }, dimension: 'P' },
      { text: { es: 'Espero que él/ella lo note y lo resuelva. No quiero ser la persona que lleva las cuentas.', en: 'I wait for them to notice and resolve it. I don\'t want to be the person keeping score.', fr: 'J\'attends qu\'il/elle le remarque et le résolve. Je ne veux pas être la personne qui tient les comptes.', de: 'Ich warte darauf, dass er/sie es bemerkt und löst. Ich will nicht die Person sein, die Rechenschaft führt.', it: 'Aspetto che lui/lei se ne accorga e lo risolva. Non voglio essere la persona che tiene i conti.', pt: 'Espero que ele/ela perceba e resolva. Não quero ser a pessoa que fica contando.' }, dimension: 'L' },
      { text: { es: 'Le digo directamente que ese patrón me afecta y necesita cambiar.', en: 'I tell them directly that pattern affects me and needs to change.', fr: 'Je lui dis directement que ce schéma me touche et doit changer.', de: 'Ich sage ihm/ihr direkt, dass dieses Muster mich betrifft und sich ändern muss.', it: 'Glielo dico direttamente che quel schema mi colpisce e deve cambiare.', pt: 'Digo diretamente que esse padrão me afeta e precisa mudar.' }, dimension: 'H' },
      { text: { es: 'Dejo de planear cosas con él/ella hasta que demuestre que es confiable.', en: 'I stop planning things with them until they show they\'re reliable.', fr: 'Je cesse de planifier des choses avec lui/elle jusqu\'à ce qu\'il/elle démontre qu\'il/elle est fiable.', de: 'Ich höre auf, Dinge mit ihm/ihr zu planen, bis er/sie beweist, zuverlässig zu sein.', it: 'Smetto di pianificare cose con lui/lei finché non dimostra di essere affidabile.', pt: 'Paro de planejar coisas com ele/ela até que demonstre ser confiável.' }, dimension: 'A' },
    ] },
    { id: 5, situation: { es: 'Tu amigo/a empieza a salir con alguien que claramente no es buena influencia para él/ella.', en: 'Your friend starts dating someone who clearly isn\'t a good influence on them.', fr: 'Ton/ta ami(e) commence à sortir avec quelqu\'un qui n\'est clairement pas une bonne influence pour lui/elle.', de: 'Dein Freund/deine Freundin beginnt jemanden zu daten, der offensichtlich kein guter Einfluss auf ihn/sie ist.', it: 'Il tuo amico/a inizia a frequentare qualcuno che chiaramente non è una buona influenza per lui/lei.', pt: 'Seu/sua amigo/a começa a sair com alguém que claramente não é boa influência para ele/ela.' }, options: [
      { text: { es: 'Lo observo de cerca para entender la dinámica antes de decir algo.', en: 'I observe closely to understand the dynamic before saying something.', fr: 'Je l\'observe de près pour comprendre la dynamique avant de dire quelque chose.', de: 'Ich beobachte es genau, um die Dynamik zu verstehen, bevor ich etwas sage.', it: 'Lo osservo da vicino per capire la dinamica prima di dire qualcosa.', pt: 'Observo de perto para entender a dinâmica antes de dizer algo.' }, dimension: 'P' },
      { text: { es: 'Construyo más tiempo con él/ella para que no se aísle con esa persona.', en: 'I build more time with them so they don\'t isolate with that person.', fr: 'Je construis plus de temps avec lui/elle pour qu\'il/elle ne s\'isole pas avec cette personne.', de: 'Ich baue mehr Zeit mit ihm/ihr auf, damit er/sie sich nicht mit dieser Person isoliert.', it: 'Costruisco più tempo con lui/lei affinché non si isoli con quella persona.', pt: 'Construo mais tempo com ele/ela para que não se isole com essa pessoa.' }, dimension: 'L' },
      { text: { es: 'Le digo lo que pienso una vez, con respeto, y dejo que él/ella decida.', en: 'I tell them what I think once, respectfully, and let them decide.', fr: 'Je lui dis ce que je pense une fois, avec respect, et le laisse décider.', de: 'Ich sage ihm/ihr einmal respektvoll, was ich denke, und lasse ihn/sie entscheiden.', it: 'Glielo dico cosa penso una volta, con rispetto, e lasciare che decida.', pt: 'Digo o que penso uma vez, com respeito, e deixo que ele/ela decida.' }, dimension: 'H' },
      { text: { es: 'Me mantengo presente sin opinar. No soy su padre/madre.', en: 'I stay present without commenting. I\'m not their parent.', fr: 'Je reste présent(e) sans commenter. Je ne suis pas son/sa père/mère.', de: 'Ich bleibe präsent, ohne zu kommentieren. Ich bin nicht sein/ihr Elternteil.', it: 'Rimango presente senza commentare. Non sono suo/a padre/madre.', pt: 'Me mantenho presente sem opinar. Não sou seu/sua pai/mãe.' }, dimension: 'A' },
    ] },
    { id: 6, situation: { es: 'Tu amigo/a te pide consejo sobre un dilema pero no quiere escuchar la opinión que le darías.', en: 'Your friend asks you for advice on a dilemma but doesn\'t want to hear the opinion you\'d give.', fr: 'Ton/ta ami(e) te demande conseil sur un dilemme mais ne veut pas entendre l\'opinion que tu lui donnerais.', de: 'Dein Freund/deine Freundin bittet dich um Rat bei einem Dilemma, will aber nicht die Meinung hören, die du geben würdest.', it: 'Il tuo amico/a ti chiede consiglio su un dilemma ma non vuole sentire l\'opinione che gli daresti.', pt: 'Seu/sua amigo/a pede conselho sobre um dilema mas não quer ouvir a opinião que você daria.' }, options: [
      { text: { es: 'Le hago preguntas para que llegue él/ella mismo/a a la conclusión que creo es correcta.', en: 'I ask questions to help them reach the conclusion I think is right on their own.', fr: 'Je lui pose des questions pour qu\'il/elle arrive lui/elle-même à la conclusion que je pense être correcte.', de: 'Ich stelle Fragen, damit er/sie selbst zu dem Schluss kommt, den ich für richtig halte.', it: 'Gli faccio domande affinché arrivi lui/lei stesso/a alla conclusione che penso sia corretta.', pt: 'Faço perguntas para que ele/ela mesmo/a chegue à conclusão que acredito ser certa.' }, dimension: 'P' },
      { text: { es: 'Le doy el consejo que él/ella quiere escuchar. A veces eso es lo que se necesita.', en: 'I give them the advice they want to hear. Sometimes that\'s what\'s needed.', fr: 'Je lui donne le conseil qu\'il/elle veut entendre. Parfois c\'est ce qu\'on a besoin.', de: 'Ich gebe ihm/ihr den Rat, den er/sie hören möchte. Manchmal ist das, was gebraucht wird.', it: 'Gli do il consiglio che vuole sentire. A volte è quello di cui si ha bisogno.', pt: 'Dou o conselho que ele/ela quer ouvir. Às vezes é isso que é necessário.' }, dimension: 'L' },
      { text: { es: 'Le digo lo que pienso de todas formas. Si no quería honestidad, no debió preguntar.', en: 'I tell them what I think anyway. If they didn\'t want honesty, they shouldn\'t have asked.', fr: 'Je lui dis ce que je pense de toute façon. S\'il/elle ne voulait pas d\'honnêteté, il/elle n\'aurait pas dû demander.', de: 'Ich sage ihm/ihr trotzdem, was ich denke. Wenn er/sie keine Ehrlichkeit wollte, hätte er/sie nicht fragen sollen.', it: 'Gli dico comunque cosa penso. Se non voleva onestà, non avrebbe dovuto chiedere.', pt: 'Digo o que penso de qualquer forma. Se não queria honestidade, não deveria ter perguntado.' }, dimension: 'H' },
      { text: { es: 'Le digo que no soy la persona indicada para ese consejo en particular.', en: 'I tell them I\'m not the right person for that particular advice.', fr: 'Je lui dis que je ne suis pas la personne indiquée pour ce conseil en particulier.', de: 'Ich sage ihm/ihr, dass ich nicht die richtige Person für diesen speziellen Rat bin.', it: 'Gli dico che non sono la persona indicata per quel consiglio in particolare.', pt: 'Digo que não sou a pessoa indicada para aquele conselho em particular.' }, dimension: 'A' },
    ] },
    { id: 7, situation: { es: 'Tu grupo de amigos habla mal de uno de ellos que está ausente. ¿Qué haces?', en: 'Your group of friends speaks badly about one of them who is absent. What do you do?', fr: 'Ton groupe d\'amis parle mal de l\'un d\'eux qui est absent. Que fais-tu ?', de: 'Deine Freundesgruppe spricht schlecht über einen von ihnen, der abwesend ist. Was tust du?', it: 'Il tuo gruppo di amici parla male di uno di loro che è assente. Cosa fai?', pt: 'Seu grupo de amigos fala mal de um deles que está ausente. O que você faz?' }, options: [
      { text: { es: 'Escucho para entender si hay algo legítimo detrás de la queja.', en: 'I listen to understand if there\'s something legitimate behind the complaint.', fr: 'J\'écoute pour comprendre s\'il y a quelque chose de légitime derrière la plainte.', de: 'Ich höre zu, um zu verstehen, ob es etwas Legitimes hinter der Beschwerde gibt.', it: 'Ascolto per capire se c\'è qualcosa di legittimo dietro il lamento.', pt: 'Ouço para entender se há algo legítimo por trás da queixa.' }, dimension: 'P' },
      { text: { es: 'Lo defiendo o cambio el tema. No voy a ser parte de esto.', en: 'I defend them or change the topic. I\'m not going to be part of this.', fr: 'Je le/la défends ou change de sujet. Je ne vais pas être partie prenante.', de: 'Ich verteidige ihn/sie oder wechsle das Thema. Ich werde kein Teil davon sein.', it: 'Lo difendo o cambio argomento. Non voglio essere parte di questo.', pt: 'Defendo ou mudo o assunto. Não vou fazer parte disso.' }, dimension: 'L' },
      { text: { es: 'Digo que si hay algo que decirle, hay que decírselo directamente.', en: 'I say that if there\'s something to tell them, it should be said directly.', fr: 'Je dis que s\'il y a quelque chose à lui dire, il faut le lui dire directement.', de: 'Ich sage, wenn es etwas gibt, das ihm/ihr gesagt werden muss, sollte es direkt gesagt werden.', it: 'Dico che se c\'è qualcosa da dirgli, bisogna dirglielo direttamente.', pt: 'Digo que se há algo a dizer, deve-se dizer diretamente.' }, dimension: 'H' },
      { text: { es: 'No participo activamente pero tampoco hago escándalo. Esas dinámicas existen.', en: 'I don\'t participate actively but I don\'t make a scene either. These dynamics exist.', fr: 'Je ne participe pas activement mais je ne fais pas non plus de scandale. Ces dynamiques existent.', de: 'Ich nehme nicht aktiv teil, mache aber auch kein Theater. Diese Dynamiken existieren.', it: 'Non partecipo attivamente ma nemmeno faccio scandalo. Quelle dinamiche esistono.', pt: 'Não participo ativamente mas também não faço escândalo. Essas dinâmicas existem.' }, dimension: 'A' },
    ] },
    { id: 8, situation: { es: 'Tu amigo/a está en un mal momento emocional pero dice que está bien.', en: 'Your friend is in a bad emotional moment but says they\'re fine.', fr: 'Ton/ta ami(e) est dans un mauvais moment émotionnel mais dit que ça va.', de: 'Dein Freund/deine Freundin steckt in einem schlechten emotionalen Moment, sagt aber, dass es gut geht.', it: 'Il tuo amico/a sta attraversando un brutto momento emotivo ma dice di stare bene.', pt: 'Seu/sua amigo/a está em um mal momento emocional mas diz que está bem.' }, options: [
      { text: { es: 'Estoy presente, creo un espacio seguro y espero a que me diga cuando esté listo/a.', en: 'I\'m present, create a safe space, and wait for them to tell me when they\'re ready.', fr: 'Je suis présent(e), crée un espace sûr et attends qu\'il/elle me dise quand il/elle est prêt(e).', de: 'Ich bin präsent, schaffe einen sicheren Raum und warte darauf, dass er/sie mir sagt, wann er/sie bereit ist.', it: 'Sono presente, creo uno spazio sicuro e aspetto che mi dica quando è pronto/a.', pt: 'Estou presente, crio um espaço seguro e espero que me diga quando estiver pronto/a.' }, dimension: 'P' },
      { text: { es: 'Le propongo hacer algo juntos. A veces lo que se necesita no es hablar sino compañía.', en: 'I suggest doing something together. Sometimes what\'s needed isn\'t talking but company.', fr: 'Je propose de faire quelque chose ensemble. Parfois ce qu\'il faut n\'est pas de parler mais de la compagnie.', de: 'Ich schlage vor, etwas zusammen zu machen. Manchmal braucht man keine Gespräche, sondern Gesellschaft.', it: 'Propongo di fare qualcosa insieme. A volte quello di cui si ha bisogno non è parlare ma compagnia.', pt: 'Proponho fazer algo juntos. Às vezes o que se precisa não é falar mas companhia.' }, dimension: 'L' },
      { text: { es: 'Le digo que sé que algo pasa y que estoy ahí cuando quiera hablar.', en: 'I tell them I know something is going on and I\'m there when they want to talk.', fr: 'Je lui dis que je sais que quelque chose se passe et que je suis là quand il/elle veut parler.', de: 'Ich sage ihm/ihr, dass ich weiß, dass etwas los ist, und ich da bin, wenn er/sie reden möchte.', it: 'Gli dico che so che qualcosa sta succedendo e che sono lì quando vuole parlare.', pt: 'Digo que sei que algo está acontecendo e que estou aqui quando quiser falar.' }, dimension: 'H' },
      { text: { es: 'Si dice que está bien, lo respeto. No es mi lugar insistir.', en: 'If they say they\'re fine, I respect it. It\'s not my place to insist.', fr: 'S\'il/elle dit que ça va, je respecte ça. Ce n\'est pas mon rôle d\'insister.', de: 'Wenn er/sie sagt, dass es gut geht, respektiere ich das. Es ist nicht mein Platz zu insistieren.', it: 'Se dice che sta bene, lo rispetto. Non è il mio posto insistere.', pt: 'Se diz que está bem, respeito. Não é meu lugar insistir.' }, dimension: 'A' },
    ] },
    { id: 9, situation: { es: 'Tu amigo/a toma una decisión importante sin consultarte. Antes siempre lo hacía.', en: 'Your friend makes an important decision without consulting you. They used to always do so.', fr: 'Ton/ta ami(e) prend une décision importante sans te consulter. Avant, il/elle le faisait toujours.', de: 'Dein Freund/deine Freundin trifft eine wichtige Entscheidung, ohne dich zu konsultieren. Früher tat er/sie das immer.', it: 'Il tuo amico/a prende una decisione importante senza consultarti. Prima lo faceva sempre.', pt: 'Seu/sua amigo/a toma uma decisão importante sem te consultar. Antes sempre fazia isso.' }, options: [
      { text: { es: 'Le pregunto cómo está la relación. Algo cambió y quiero entender qué.', en: 'I ask how the relationship is. Something changed and I want to understand what.', fr: 'Je lui demande comment va la relation. Quelque chose a changé et je veux comprendre quoi.', de: 'Ich frage, wie die Beziehung ist. Irgendetwas hat sich geändert und ich möchte verstehen, was.', it: 'Gli chiedo come va la relazione. Qualcosa è cambiato e voglio capire cosa.', pt: 'Pergunto como está o relacionamento. Algo mudou e quero entender o quê.' }, dimension: 'P' },
      { text: { es: 'No me afecta. Las personas evolucionan y las amistades también.', en: 'It doesn\'t affect me. People evolve and friendships do too.', fr: 'Ça ne m\'affecte pas. Les gens évoluent et les amitiés aussi.', de: 'Es betrifft mich nicht. Menschen entwickeln sich und Freundschaften auch.', it: 'Non mi colpisce. Le persone si evolvono e le amicizie anche.', pt: 'Não me afeta. As pessoas evoluem e as amizades também.' }, dimension: 'L' },
      { text: { es: 'Se lo digo: me sorprendió que no me lo contara antes. ¿Estamos bien?', en: 'I tell them: I was surprised they didn\'t tell me beforehand. Are we okay?', fr: 'Je lui dis : ça m\'a surpris qu\'il/elle ne me l\'ait pas dit avant. Est-ce qu\'on est bien ?', de: 'Ich sage ihm/ihr: Ich war überrascht, dass er/sie es mir vorher nicht erzählt hat. Sind wir okay?', it: 'Glielo dico: mi ha sorpreso che non me lo avesse detto prima. Stiamo bene?', pt: 'Digo: fiquei surpreso/a que não me contou antes. Estamos bem?' }, dimension: 'H' },
      { text: { es: 'Lo noto pero no lo menciono. Quizás está en un proceso de ganar más independencia.', en: 'I notice it but don\'t mention it. Maybe they\'re in a process of gaining more independence.', fr: 'Je le remarque mais ne le mentionne pas. Peut-être qu\'il/elle est en processus de gagner plus d\'indépendance.', de: 'Ich bemerke es, erwähne es aber nicht. Vielleicht ist er/sie dabei, mehr Unabhängigkeit zu gewinnen.', it: 'Lo noto ma non lo menziono. Forse sta in un processo di guadagnare più indipendenza.', pt: 'Noto mas não menciono. Talvez esteja em um processo de ganhar mais independência.' }, dimension: 'A' },
    ] },
    { id: 10, situation: { es: 'Tu amigo/a te pide que seas el padrino/madrina de su boda. No te llevas bien con su pareja.', en: 'Your friend asks you to be the best man/maid of honor at their wedding. You don\'t get along with their partner.', fr: 'Ton/ta ami(e) te demande d\'être le parrain/la marraine de son mariage. Tu ne t\'entends pas bien avec son/sa partenaire.', de: 'Dein Freund/deine Freundin bittet dich, sein/ihr Trauzeuge/ihre Trauzeugin zu sein. Du verstehst dich nicht gut mit seinem/ihrem Partner/seiner/ihrer Partnerin.', it: 'Il tuo amico/a ti chiede di essere il testimone/a del suo matrimonio. Non ti vai d\'accordo con il suo partner.', pt: 'Seu/sua amigo/a te pede para ser o padrinho/madrinha do casamento. Você não se dá bem com o parceiro dele/dela.' }, options: [
      { text: { es: 'Acepto de inmediato. Si me lo pidió, es que confía en mí y eso es lo que importa.', en: 'I accept immediately. If they asked, it\'s because they trust me and that\'s what matters.', fr: 'J\'accepte immédiatement. S\'il/elle me l\'a demandé, c\'est qu\'il/elle me fait confiance et c\'est ce qui compte.', de: 'Ich stimme sofort zu. Wenn er/sie gefragt hat, vertraut er/sie mir und das ist, was zählt.', it: 'Accetto subito. Se me lo ha chiesto, è perché si fida di me e questo è ciò che conta.', pt: 'Aceito imediatamente. Se pediu, é porque confia em mim e isso é o que importa.' }, dimension: 'L' },
      { text: { es: 'Antes de aceptar, hablo honestamente sobre mis reservas con él/ella.', en: 'Before accepting, I honestly discuss my reservations with them.', fr: 'Avant d\'accepter, je parle honnêtement de mes réserves avec lui/elle.', de: 'Bevor ich zustimme, spreche ich ehrlich über meine Vorbehalte mit ihm/ihr.', it: 'Prima di accettare, parlo onestamente delle mie riserve con lui/lei.', pt: 'Antes de aceitar, falo honestamente sobre minhas reservas com ele/ela.' }, dimension: 'H' },
      { text: { es: 'Acepto y uso ese rol para ser el mejor apoyo posible ese día.', en: 'I accept and use that role to be the best possible support that day.', fr: 'J\'accepte et utilise ce rôle pour être le meilleur soutien possible ce jour-là.', de: 'Ich stimme zu und nutze diese Rolle, um an diesem Tag die bestmögliche Unterstützung zu sein.', it: 'Accetto e uso quel ruolo per essere il miglior supporto possibile quel giorno.', pt: 'Aceito e uso esse papel para ser o melhor suporte possível naquele dia.' }, dimension: 'P' },
      { text: { es: 'Le digo que me lo tiene que pensar. No quiero hacer algo que no pueda sostener.', en: 'I tell them I need to think about it. I don\'t want to do something I can\'t sustain.', fr: 'Je lui dis qu\'il/elle doit y réfléchir. Je ne veux pas faire quelque chose que je ne peux pas soutenir.', de: 'Ich sage ihm/ihr, dass er/sie darüber nachdenken muss. Ich möchte nichts tun, was ich nicht aufrechterhalten kann.', it: 'Gli dico che deve pensarci. Non voglio fare qualcosa che non riesca a sostenere.', pt: 'Digo que ele/ela tem que pensar. Não quero fazer algo que não possa sustentar.' }, dimension: 'A' },
    ] },
  ],
  characters: [
    { name: { es: 'El Presente Total', en: 'The Fully Present', fr: 'Le Totalement Présent', de: 'Der Vollständig Anwesende', it: 'Il Totalmente Presente', pt: 'O Totalmente Presente' }, dimensions: ['P'], photo: '/characters/full-presence.jpg', description: { es: 'Cuando estás con un amigo, estás completamente ahí.', en: 'When you\'re with a friend, you\'re completely there.', fr: 'Quand tu es avec un ami, tu y es complètement.', de: 'Wenn du mit einem Freund bist, bist du völlig da.', it: 'Quando sei con un amico, sei completamente lì.', pt: 'Quando você está com um amigo, está completamente lá.' }, philosophy: { es: 'Tu mayor regalo es tu presencia. Cuando alguien está contigo, siente que es la única persona que existe en ese momento. No miras el teléfono, no piensas en lo siguiente. Eso es extraordinariamente raro.', en: 'Your greatest gift is your presence. When someone is with you, they feel they\'re the only person in the world in that moment. You don\'t check your phone, don\'t think of what\'s next. That is extraordinarily rare.', fr: 'Ton plus grand don est ta présence. Quand quelqu\'un est avec toi, il/elle sent qu\'il/elle est la seule personne qui existe en ce moment. Tu ne regardes pas ton téléphone, tu ne penses pas à ce qui suit.', de: 'Dein größtes Geschenk ist deine Präsenz. Wenn jemand bei dir ist, fühlt er/sie, dass er/sie die einzige Person ist, die in diesem Moment existiert. Du schaust nicht auf dein Telefon, denkst nicht an das Nächste.', it: 'Il tuo più grande dono è la tua presenza. Quando qualcuno è con te, sente di essere l\'unica persona che esiste in quel momento. Non guardi il telefono, non pensi a cosa viene dopo.', pt: 'Seu maior presente é sua presença. Quando alguém está com você, sente que é a única pessoa que existe naquele momento. Você não olha para o telefone, não pensa no próximo.' } },
    { name: { es: 'El Leal Incondicional', en: 'The Unconditionally Loyal', fr: 'Le Loyal Inconditionnel', de: 'Der Bedingungslos Loyale', it: 'Il Leale Incondizionale', pt: 'O Leal Incondicional' }, dimensions: ['L'], photo: '/characters/loyal.jpg', description: { es: 'Está ahí en las malas, sin importar el costo personal.', en: 'There in the bad times, regardless of personal cost.', fr: 'Là dans les mauvais moments, peu importe le coût personnel.', de: 'Da in den schlechten Zeiten, ungeachtet der persönlichen Kosten.', it: 'Là nei momenti brutti, indipendentemente dal costo personale.', pt: 'Lá nos momentos difíceis, independentemente do custo pessoal.' }, philosophy: { es: 'Tu lealtad no tiene cláusulas ni condiciones. Estás ahí en las malas incluso cuando cuesta algo. Tus amigos saben que si el mundo se cae, tú vas a estar parado/a al lado de ellos.', en: 'Your loyalty has no clauses or conditions. You\'re there in the bad times even when it costs something. Your friends know that if the world falls apart, you\'ll be standing beside them.', fr: 'Ta loyauté n\'a pas de clauses ni de conditions. Tu es là dans les mauvais moments même quand ça coûte quelque chose. Tes amis savent que si le monde s\'effondre, tu seras debout à leurs côtés.', de: 'Deine Loyalität hat keine Klauseln oder Bedingungen. Du bist in den schlechten Zeiten da, auch wenn es etwas kostet. Deine Freunde wissen, dass du neben ihnen stehst, wenn die Welt einstürzt.', it: 'La tua lealtà non ha clausole né condizioni. Sei lì nei momenti brutti anche quando costa qualcosa. I tuoi amici sanno che se il mondo cade, tu sarai in piedi accanto a loro.', pt: 'Sua lealdade não tem cláusulas nem condições. Você está lá nos momentos difíceis mesmo quando custa algo. Seus amigos sabem que se o mundo cair, você estará ao lado deles.' } },
    { name: { es: 'El Espejo Honesto', en: 'The Honest Mirror', fr: 'Le Miroir Honnête', de: 'Der Ehrliche Spiegel', it: 'Lo Specchio Onesto', pt: 'O Espelho Honesto' }, dimensions: ['H'], photo: '/characters/honest-mirror.jpg', description: { es: 'Dice la verdad aunque duela. El amigo que más se necesita y menos se busca.', en: 'Tells the truth even when it hurts. The friend most needed and least sought.', fr: 'Dit la vérité même si ça fait mal. L\'ami dont on a le plus besoin et qu\'on cherche le moins.', de: 'Sagt die Wahrheit, auch wenn es wehtut. Der Freund, der am meisten gebraucht wird und am wenigsten gesucht.', it: 'Dice la verità anche quando fa male. L\'amico di cui si ha più bisogno e che si cerca meno.', pt: 'Diz a verdade mesmo quando dói. O amigo mais necessário e menos buscado.' }, philosophy: { es: 'Eres el amigo/a que todo el mundo dice querer pero no siempre está listo para tener. Dices lo que ves aunque incomode, porque crees que la verdad dicha con cariño siempre supera a la mentira cómoda.', en: 'You\'re the friend everyone says they want but isn\'t always ready to have. You say what you see even when it\'s uncomfortable, because you believe truth said with care always surpasses a comfortable lie.', fr: 'Tu es l\'ami(e) que tout le monde dit vouloir mais n\'est pas toujours prêt à avoir. Tu dis ce que tu vois même si ça dérange, parce que tu crois que la vérité dite avec affection surpasse toujours le mensonge confortable.', de: 'Du bist der Freund/die Freundin, den/die alle haben wollen, aber nicht immer bereit sind zu haben. Du sagst, was du siehst, auch wenn es unbequem ist, weil du glaubst, dass Wahrheit mit Fürsorge gesagt immer die bequeme Lüge übertrifft.', it: 'Sei l\'amico/a che tutti dicono di volere ma non sempre è pronto ad avere. Dici quello che vedi anche se disturba, perché credi che la verità detta con cura superi sempre la menzogna comoda.', pt: 'Você é o/a amigo/a que todos dizem querer mas nem sempre estão prontos para ter. Você diz o que vê mesmo que incomode, porque acredita que a verdade dita com carinho sempre supera a mentira confortável.' } },
    { name: { es: 'El Que Respeta los Límites', en: 'The One Who Respects Limits', fr: 'Celui/Celle qui Respecte les Limites', de: 'Derjenige, der Grenzen Respektiert', it: 'Quello che Rispetta i Limiti', pt: 'O Que Respeita os Limites' }, dimensions: ['A'], photo: '/characters/boundaries.jpg', description: { es: 'Amigo/a sin asfixia. Te quiere pero no te necesita.', en: 'Friend without suffocation. Loves you but doesn\'t need you.', fr: 'Ami(e) sans étouffement. T\'aime mais n\'a pas besoin de toi.', de: 'Freund/Freundin ohne Erstickung. Liebt dich, braucht dich aber nicht.', it: 'Amico/a senza soffocamento. Ti vuole bene ma non ha bisogno di te.', pt: 'Amigo/a sem sufocamento. Te ama mas não precisa de você.' }, philosophy: { es: 'Entiendes que las personas necesitan espacio para ser ellas mismas, incluso dentro de las amistades. Tu amor no controla. Dejas que tus amigos tomen sus decisiones y confías en que saben lo que hacen.', en: 'You understand that people need space to be themselves, even within friendships. Your love doesn\'t control. You let your friends make their decisions and trust that they know what they\'re doing.', fr: 'Tu comprends que les gens ont besoin d\'espace pour être eux-mêmes, même dans les amitiés. Ton amour ne contrôle pas. Tu laisses tes amis prendre leurs décisions et tu fais confiance qu\'ils savent ce qu\'ils font.', de: 'Du verstehst, dass Menschen Raum brauchen, um sie selbst zu sein, auch innerhalb von Freundschaften. Deine Liebe kontrolliert nicht. Du lässt deine Freunde ihre Entscheidungen treffen und vertraust darauf, dass sie wissen, was sie tun.', it: 'Capisci che le persone hanno bisogno di spazio per essere se stesse, anche all\'interno delle amicizie. Il tuo amore non controlla. Lasci che i tuoi amici prendano le loro decisioni e ti fidi che sanno cosa stanno facendo.', pt: 'Você entende que as pessoas precisam de espaço para ser elas mesmas, mesmo dentro das amizades. Seu amor não controla. Você deixa seus amigos tomarem suas decisões e confia que eles sabem o que fazem.' } },
    { name: { es: 'El Confidente Leal', en: 'The Loyal Confidant', fr: 'Le Confident Loyal', de: 'Der Loyale Vertraute', it: 'Il Confidente Leale', pt: 'O Confidente Leal' }, dimensions: ['P', 'L'], photo: '/characters/confident.jpg', description: { es: 'Presente y leal. El amigo con quien te quedas a hablar hasta las 4am.', en: 'Present and loyal. The friend you stay up talking with until 4am.', fr: 'Présent et loyal. L\'ami avec qui tu restes à parler jusqu\'à 4h du matin.', de: 'Präsent und loyal. Der Freund, mit dem du bis 4 Uhr morgens redest.', it: 'Presente e leale. L\'amico con cui rimani a parlare fino alle 4 del mattino.', pt: 'Presente e leal. O amigo com quem você fica conversando até as 4h da manhã.' }, philosophy: { es: 'Estás ahí y no te vas. Esa combinación de presencia y lealtad genera el tipo de amistad que dura décadas. La gente construye su vida sabiendo que cuenta contigo.', en: 'You\'re there and you don\'t leave. That combination of presence and loyalty generates the kind of friendship that lasts decades. People build their lives knowing they can count on you.', fr: 'Tu es là et tu ne pars pas. Cette combinaison de présence et de loyauté génère le type d\'amitié qui dure des décennies. Les gens construisent leur vie en sachant qu\'ils peuvent compter sur toi.', de: 'Du bist da und gehst nicht weg. Diese Kombination aus Präsenz und Loyalität erzeugt die Art von Freundschaft, die Jahrzehnte dauert. Menschen bauen ihr Leben auf, in dem Wissen, dass sie auf dich zählen können.', it: 'Sei lì e non te ne vai. Quella combinazione di presenza e lealtà genera il tipo di amicizia che dura decenni. Le persone costruiscono la loro vita sapendo di poter contare su di te.', pt: 'Você está lá e não vai embora. Essa combinação de presença e lealdade gera o tipo de amizade que dura décadas. As pessoas constroem suas vidas sabendo que podem contar com você.' } },
    { name: { es: 'El Asesor Honesto', en: 'The Honest Advisor', fr: 'Le Conseiller Honnête', de: 'Der Ehrliche Berater', it: 'Il Consigliere Onesto', pt: 'O Conselheiro Honesto' }, dimensions: ['H', 'A'], photo: '/characters/honest-advisor.jpg', description: { es: 'Dice la verdad pero respeta tu derecho a decidir.', en: 'Tells the truth but respects your right to decide.', fr: 'Dit la vérité mais respecte ton droit de décider.', de: 'Sagt die Wahrheit, respektiert aber dein Recht zu entscheiden.', it: 'Dice la verità ma rispetta il tuo diritto di decidere.', pt: 'Diz a verdade mas respeita seu direito de decidir.' }, philosophy: { es: 'Das tu perspectiva honesta, claramente, y después te haces a un lado. No insistes, no te pones en medio de las decisiones de otros. Tu honestidad viene sin condiciones ni control.', en: 'You give your honest perspective, clearly, and then step aside. You don\'t insist, don\'t put yourself in the middle of others\' decisions. Your honesty comes without conditions or control.', fr: 'Tu donnes ta perspective honnête, clairement, et ensuite tu t\'effaces. Tu n\'insistes pas, tu ne te mets pas au milieu des décisions des autres. Ton honnêteté vient sans conditions ni contrôle.', de: 'Du gibst deine ehrliche Perspektive klar und trittst dann zurück. Du bestehst nicht, stellst dich nicht in die Mitte der Entscheidungen anderer. Deine Ehrlichkeit kommt ohne Bedingungen oder Kontrolle.', it: 'Dai la tua prospettiva onesta, chiaramente, e poi ti fai da parte. Non insisti, non ti metti in mezzo alle decisioni degli altri. La tua onestà viene senza condizioni né controllo.', pt: 'Você dá sua perspectiva honesta, claramente, e depois se afasta. Não insiste, não se coloca no meio das decisões dos outros. Sua honestidade vem sem condições nem controle.' } },
    { name: { es: 'El Guardián Presente', en: 'The Present Guardian', fr: 'Le Gardien Présent', de: 'Der Anwesende Hüter', it: 'Il Guardiano Presente', pt: 'O Guardião Presente' }, dimensions: ['P', 'H'], photo: '/characters/guardian.jpg', description: { es: 'Está ahí y dice las cosas como son. Rara combinación.', en: 'There and tells it like it is. A rare combination.', fr: 'Là et dit les choses comme elles sont. Une combinaison rare.', de: 'Da und sagt die Dinge, wie sie sind. Eine seltene Kombination.', it: 'Lì e dice le cose come stanno. Rara combinazione.', pt: 'Lá e diz as coisas como são. Rara combinação.' }, philosophy: { es: 'Combinas lo más difícil: la presencia total y la honestidad valiente. No te quedas callado/a cuando algo está mal, pero tampoco te vas cuando las cosas se complican. Eso hace que tus amigos te busquen en los momentos más difíciles.', en: 'You combine the hardest things: total presence and brave honesty. You don\'t stay silent when something is wrong, but you also don\'t leave when things get complicated. That makes your friends seek you in the most difficult moments.', fr: 'Tu combines ce qui est le plus difficile : la présence totale et l\'honnêteté courageuse. Tu ne te tais pas quand quelque chose ne va pas, mais tu ne pars pas non plus quand les choses se compliquent.', de: 'Du kombinierst das Schwierigste: totale Präsenz und mutige Ehrlichkeit. Du schweigst nicht, wenn etwas nicht stimmt, aber du gehst auch nicht, wenn die Dinge kompliziert werden.', it: 'Combini le cose più difficili: la presenza totale e l\'onestà coraggiosa. Non taci quando qualcosa va male, ma non te ne vai nemmeno quando le cose si complicano.', pt: 'Você combina o mais difícil: a presença total e a honestidade corajosa. Não fica calado/a quando algo está errado, mas também não vai embora quando as coisas ficam complicadas.' } },
    { name: { es: 'El Mejor Amigo', en: 'The Best Friend', fr: 'Le Meilleur Ami', de: 'Der Beste Freund', it: 'Il Migliore Amico', pt: 'O Melhor Amigo' }, dimensions: ['L', 'H'], photo: '/characters/best-friend.jpg', description: { es: 'Leal como pocos, honesto como nadie.', en: 'Loyal like few, honest like none.', fr: 'Loyal comme peu, honnête comme personne.', de: 'Loyal wie wenige, ehrlich wie keiner.', it: 'Leale come pochi, onesto come nessuno.', pt: 'Leal como poucos, honesto como ninguém.' }, philosophy: { es: 'Eres la persona que todos quisieran tener en su círculo: incondicional en la lealtad, impecable en la honestidad. No te quedas con lo que no se debe decir, pero tampoco te olvidas de para qué está el otro.', en: 'You\'re the person everyone would want in their circle: unconditional in loyalty, impeccable in honesty. You don\'t keep back what should be said, but you don\'t forget what the other person is there for either.', fr: 'Tu es la personne que tout le monde voudrait dans son cercle : inconditionnel(le) dans la loyauté, impeccable dans l\'honnêteté. Tu ne gardes pas ce qui ne doit pas être dit, mais tu n\'oublies pas non plus à quoi l\'autre sert.', de: 'Du bist die Person, die alle in ihrem Kreis hätten wollen: bedingungslos in der Loyalität, tadellos in der Ehrlichkeit. Du behältst das nicht zurück, was gesagt werden sollte, vergisst aber auch nicht, wofür der andere da ist.', it: 'Sei la persona che tutti vorrebbero nel loro cerchio: incondizionale nella lealtà, impeccabile nell\'onestà. Non tieni quello che non si deve dire, ma non dimentichi nemmeno a cosa serve l\'altro.', pt: 'Você é a pessoa que todos gostariam de ter em seu círculo: incondicional na lealdade, impecável na honestidade. Não retém o que não se deve dizer, mas também não esquece para que está o outro.' } },
  ],
};

export async function seedGoodFriend(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'good-friend' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'good-friend',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 1,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
