import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan celoso/a eres?', en: 'How jealous are you?', fr: 'À quel point es-tu jaloux/se ?', de: 'Wie eifersüchtig bist du?', it: 'Quanto sei geloso/a?', pt: 'O quanto você é ciumento/a?' },
  description: { es: 'Los celos revelan nuestros miedos más profundos. ¿Cuáles son los tuyos?', en: 'Jealousy reveals our deepest fears. What are yours?', fr: 'La jalousie révèle nos peurs les plus profondes. Quelles sont les tiennes ?', de: 'Eifersucht offenbart unsere tiefsten Ängste. Was sind deine?', it: 'La gelosia rivela le nostre paure più profonde. Quali sono le tue?', pt: 'O ciúme revela nossos medos mais profundos. Quais são os seus?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { R: 'Reactividad', C: 'Control', S: 'Seguridad', T: 'Confianza' },
    en: { R: 'Reactivity', C: 'Control', S: 'Security', T: 'Trust' },
    fr: { R: 'Réactivité', C: 'Contrôle', S: 'Sécurité', T: 'Confiance' },
    de: { R: 'Reaktivität', C: 'Kontrolle', S: 'Sicherheit', T: 'Vertrauen' },
    it: { R: 'Reattività', C: 'Controllo', S: 'Sicurezza', T: 'Fiducia' },
    pt: { R: 'Reatividade', C: 'Controle', S: 'Segurança', T: 'Confiança' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu pareja menciona que su ex le mandó un mensaje de cumpleaños.', en: 'Your partner mentions their ex sent them a birthday message.', fr: 'Ton/ta partenaire mentionne que son/sa ex lui a envoyé un message d\'anniversaire.', de: 'Dein Partner/deine Partnerin erwähnt, dass sein/ihr Ex eine Geburtstagsnaricht geschickt hat.', it: 'Il tuo partner menziona che il suo ex gli ha mandato un messaggio di compleanno.', pt: 'Seu parceiro menciona que o ex mandou uma mensagem de aniversário.' }, options: [
      { text: { es: 'Quiero ver el mensaje. ¿Solo fue "feliz cumple" o había más?', en: 'I want to see the message. Was it just "happy birthday" or was there more?', fr: 'Je veux voir le message. C\'était juste "joyeux anniversaire" ou y avait-il plus ?', de: 'Ich möchte die Nachricht sehen. War es nur "Happy Birthday" oder gab es mehr?', it: 'Voglio vedere il messaggio. Era solo "buon compleanno" o c\'era di più?', pt: 'Quero ver a mensagem. Foi só "parabéns" ou havia mais?' }, dimension: 'R' },
      { text: { es: 'Le pregunto si planean verse o si van a seguir hablando regularmente.', en: 'I ask if they plan to meet or if they\'re going to keep talking regularly.', fr: 'Je lui demande s\'ils prévoient de se voir ou s\'ils vont continuer à se parler régulièrement.', de: 'Ich frage, ob sie planen, sich zu treffen oder ob sie weiterhin regelmäßig reden werden.', it: 'Chiedo se hanno in programma di vedersi o se continueranno a parlare regolarmente.', pt: 'Pergunto se planejam se ver ou se vão continuar falando regularmente.' }, dimension: 'C' },
      { text: { es: 'Me genera algo pero lo proceso internamente. No hago nada al respecto.', en: 'It generates something in me but I process it internally. I don\'t do anything about it.', fr: 'Ça me génère quelque chose mais je le traite intérieurement. Je ne fais rien à ce sujet.', de: 'Es erzeugt etwas in mir, aber ich verarbeite es innerlich. Ich unternehme nichts dagegen.', it: 'Mi genera qualcosa ma lo processo internamente. Non faccio nulla al riguardo.', pt: 'Me gera algo mas processo internamente. Não faço nada a respeito.' }, dimension: 'S' },
      { text: { es: 'Me parece normal. El pasado es el pasado y eso no es una amenaza.', en: 'I find it normal. The past is the past and that\'s not a threat.', fr: 'Je trouve ça normal. Le passé est le passé et ce n\'est pas une menace.', de: 'Ich finde es normal. Die Vergangenheit ist die Vergangenheit und das ist keine Bedrohung.', it: 'Mi sembra normale. Il passato è il passato e non è una minaccia.', pt: 'Me parece normal. O passado é o passado e isso não é uma ameaça.' }, dimension: 'T' },
    ] },
    { id: 2, situation: { es: 'Tu pareja tiene un colega que claramente le tiene interés romántico.', en: 'Your partner has a colleague who clearly has romantic interest in them.', fr: 'Ton/ta partenaire a un(e) collègue qui lui porte clairement un intérêt romantique.', de: 'Dein Partner/deine Partnerin hat einen Kollegen/eine Kollegin, der/die offensichtlich romantisches Interesse hat.', it: 'Il tuo partner ha un collega che chiaramente ha interesse romantico per lui/lei.', pt: 'Seu parceiro tem um colega que claramente tem interesse romântico por ele/ela.' }, options: [
      { text: { es: 'Estoy pendiente de cada interacción entre ellos dos. No puedo evitarlo.', en: 'I\'m watching every interaction between the two of them. I can\'t help it.', fr: 'Je suis attentif/ve à chaque interaction entre eux deux. Je ne peux pas m\'en empêcher.', de: 'Ich beobachte jede Interaktion zwischen den beiden. Ich kann nicht anders.', it: 'Sono attento/a ad ogni interazione tra loro due. Non posso evitarlo.', pt: 'Fico de olho em cada interação entre os dois. Não consigo evitar.' }, dimension: 'R' },
      { text: { es: 'Establezco conversación sobre límites claros con esa persona en el trabajo.', en: 'I establish a conversation about clear boundaries with that person at work.', fr: 'J\'établis une conversation sur des limites claires avec cette personne au travail.', de: 'Ich führe ein Gespräch über klare Grenzen mit dieser Person bei der Arbeit.', it: 'Stabilisco una conversazione sui limiti chiari con quella persona al lavoro.', pt: 'Estabeleço uma conversa sobre limites claros com essa pessoa no trabalho.' }, dimension: 'C' },
      { text: { es: 'Lo observo sin hacer nada precipitado. Si hay algo concreto que me preocupe, hablo.', en: 'I observe it without doing anything hasty. If there\'s something concrete that worries me, I talk.', fr: 'Je l\'observe sans faire quoi que ce soit de précipité. S\'il y a quelque chose de concret qui m\'inquiète, j\'en parle.', de: 'Ich beobachte es, ohne etwas Übereiltes zu tun. Wenn es etwas Konkretes gibt, das mich besorgt, rede ich.', it: 'Lo osservo senza fare nulla di precipitoso. Se c\'è qualcosa di concreto che mi preoccupa, ne parlo.', pt: 'Observo sem fazer nada precipitado. Se há algo concreto que me preocupa, falo.' }, dimension: 'S' },
      { text: { es: 'Confío en mi pareja. Si hay algo que deba saber, me lo dirá.', en: 'I trust my partner. If there\'s something I should know, they\'ll tell me.', fr: 'Je fais confiance à mon/ma partenaire. S\'il y a quelque chose que je dois savoir, il/elle me le dira.', de: 'Ich vertraue meinem Partner/meiner Partnerin. Wenn es etwas gibt, das ich wissen sollte, werden sie es mir sagen.', it: 'Mi fido del mio partner. Se c\'è qualcosa che dovrei sapere, me lo dirà.', pt: 'Confio no meu parceiro. Se há algo que devo saber, me dirá.' }, dimension: 'T' },
    ] },
    { id: 3, situation: { es: 'En una fiesta, tu pareja pasa mucho tiempo conversando con alguien muy atractivo/a.', en: 'At a party, your partner spends a lot of time talking to someone very attractive.', fr: 'À une fête, ton/ta partenaire passe beaucoup de temps à converser avec quelqu\'un de très attrayant(e).', de: 'Auf einer Party verbringt dein Partner/deine Partnerin viel Zeit damit, mit jemandem sehr Attraktiven zu sprechen.', it: 'A una festa, il tuo partner passa molto tempo a conversare con qualcuno molto attraente.', pt: 'Em uma festa, seu parceiro passa muito tempo conversando com alguém muito atraente.' }, options: [
      { text: { es: 'Me acerco con excusas frecuentes para estar presente en la conversación.', en: 'I approach with frequent excuses to be present in the conversation.', fr: 'Je m\'approche avec des excuses fréquentes pour être présent(e) dans la conversation.', de: 'Ich nähere mich mit häufigen Ausreden, um in der Konversation präsent zu sein.', it: 'Mi avvicino con scuse frequenti per essere presente nella conversazione.', pt: 'Me aproximo com desculpas frequentes para estar presente na conversa.' }, dimension: 'R' },
      { text: { es: 'Lo hablo esa noche en casa. ¿Quién era esa persona? ¿Se conocían?', en: 'I talk about it that night at home. Who was that person? Did they know each other?', fr: 'J\'en parle ce soir-là à la maison. Qui était cette personne ? Ils/elles se connaissaient ?', de: 'Ich rede darüber abends zuhause. Wer war diese Person? Kannten sie sich?', it: 'Ne parlo quella sera a casa. Chi era quella persona? Si conoscevano?', pt: 'Falo sobre isso naquela noite em casa. Quem era essa pessoa? Se conheciam?' }, dimension: 'C' },
      { text: { es: 'Siento incomodidad pero termino la fiesta bien. Lo proceso después.', en: 'I feel discomfort but finish the party fine. I process it afterward.', fr: 'Je ressens un malaise mais je finis bien la fête. Je le traite après.', de: 'Ich fühle Unbehagen, beende die Party aber gut. Ich verarbeite es danach.', it: 'Sento disagio ma finisco la festa bene. Lo processo dopo.', pt: 'Sinto desconforto mas termino a festa bem. Processo depois.' }, dimension: 'S' },
      { text: { es: 'Me alegra que mi pareja tenga conversaciones interesantes. Me cuenta después.', en: 'I\'m glad my partner has interesting conversations. They tell me about it afterward.', fr: 'Je suis content(e) que mon/ma partenaire ait des conversations intéressantes. Il/elle me raconte après.', de: 'Ich freue mich, dass mein Partner/meine Partnerin interessante Gespräche führt. Er/sie erzählt es mir danach.', it: 'Sono contento/a che il mio partner abbia conversazioni interessanti. Me ne parla dopo.', pt: 'Fico feliz que meu parceiro tenha conversas interessantes. Me conta depois.' }, dimension: 'T' },
    ] },
    { id: 4, situation: { es: 'Tu pareja tiene una amistad muy cercana con alguien del sexo opuesto que conoces poco.', en: 'Your partner has a very close friendship with someone of the opposite sex you barely know.', fr: 'Ton/ta partenaire a une amitié très proche avec quelqu\'un du sexe opposé que tu connais peu.', de: 'Dein Partner/deine Partnerin hat eine sehr enge Freundschaft mit jemandem des anderen Geschlechts, den/die du kaum kennst.', it: 'Il tuo partner ha un\'amicizia molto stretta con qualcuno del sesso opposto che conosci poco.', pt: 'Seu parceiro tem uma amizade muito próxima com alguém do sexo oposto que você mal conhece.' }, options: [
      { text: { es: 'Busco formas de conocer más sobre esa persona: redes sociales, preguntarle a amigos comunes.', en: 'I look for ways to know more about that person: social media, asking mutual friends.', fr: 'Je cherche des façons d\'en savoir plus sur cette personne : réseaux sociaux, demander à des amis communs.', de: 'Ich suche nach Möglichkeiten, mehr über diese Person zu erfahren: soziale Medien, gemeinsame Freunde fragen.', it: 'Cerco modi per sapere di più su quella persona: social media, chiedere ad amici comuni.', pt: 'Busco formas de saber mais sobre essa pessoa: redes sociais, perguntar a amigos em comum.' }, dimension: 'R' },
      { text: { es: 'Le pido a mi pareja que me incluya más en esos planes para conocerla/lo mejor.', en: 'I ask my partner to include me more in those plans to get to know them better.', fr: 'Je demande à mon/ma partenaire de m\'inclure davantage dans ces plans pour mieux connaître cette personne.', de: 'Ich bitte meinen Partner/meine Partnerin, mich mehr in diese Pläne einzubeziehen, um ihn/sie besser kennenzulernen.', it: 'Chiedo al mio partner di includermi di più in quei piani per conoscere meglio questa persona.', pt: 'Peço ao meu parceiro que me inclua mais nesses planos para conhecer melhor essa pessoa.' }, dimension: 'C' },
      { text: { es: 'Me genera algunas preguntas pero confío en mi pareja y espero verlo en el tiempo.', en: 'It generates some questions for me but I trust my partner and wait to see it over time.', fr: 'Ça me génère quelques questions mais je fais confiance à mon/ma partenaire et j\'attends de le voir avec le temps.', de: 'Es wirft einige Fragen bei mir auf, aber ich vertraue meinem Partner/meiner Partnerin und warte ab.', it: 'Mi genera alcune domande ma mi fido del mio partner e aspetto di vederlo nel tempo.', pt: 'Me gera algumas perguntas mas confio no meu parceiro e espero ver com o tempo.' }, dimension: 'S' },
      { text: { es: 'Me parece bien. Tener amigos cercanos del sexo opuesto es normal y sano.', en: 'I think it\'s fine. Having close friends of the opposite sex is normal and healthy.', fr: 'Je pense que c\'est bien. Avoir des amis proches du sexe opposé est normal et sain.', de: 'Ich finde es gut. Enge Freunde des anderen Geschlechts zu haben ist normal und gesund.', it: 'Mi sembra giusto. Avere amici stretti del sesso opposto è normale e sano.', pt: 'Me parece bem. Ter amigos próximos do sexo oposto é normal e saudável.' }, dimension: 'T' },
    ] },
    { id: 5, situation: { es: 'Tu pareja no responde los mensajes por varias horas. No sabes dónde está.', en: 'Your partner doesn\'t respond to messages for several hours. You don\'t know where they are.', fr: 'Ton/ta partenaire ne répond pas aux messages pendant plusieurs heures. Tu ne sais pas où il/elle est.', de: 'Dein Partner/deine Partnerin antwortet stundenlang nicht auf Nachrichten. Du weißt nicht, wo er/sie ist.', it: 'Il tuo partner non risponde ai messaggi per diverse ore. Non sai dove si trova.', pt: 'Seu parceiro não responde às mensagens por várias horas. Você não sabe onde está.' }, options: [
      { text: { es: 'Mando varios mensajes y llamo un par de veces. La ansiedad me sube.', en: 'I send several messages and call a couple of times. My anxiety rises.', fr: 'J\'envoie plusieurs messages et appelle deux fois. Mon anxiété monte.', de: 'Ich sende mehrere Nachrichten und rufe ein paar Mal an. Meine Angst steigt.', it: 'Mando vari messaggi e chiamo un paio di volte. L\'ansia mi sale.', pt: 'Mando várias mensagens e ligo algumas vezes. A ansiedade sobe.' }, dimension: 'R' },
      { text: { es: 'Cuando aparece, le digo que no me parece bien desaparecer sin avisar.', en: 'When they appear, I tell them I don\'t think it\'s okay to disappear without letting me know.', fr: 'Quand il/elle apparaît, je lui dis que je ne trouve pas bien de disparaître sans prévenir.', de: 'Als er/sie erscheint, sage ich ihm/ihr, dass ich es nicht gut finde, zu verschwinden ohne Bescheid zu geben.', it: 'Quando appare, gli dico che non mi sembra giusto sparire senza avvisare.', pt: 'Quando aparece, digo que não me parece bem desaparecer sem avisar.' }, dimension: 'C' },
      { text: { es: 'Me genera algo de ansiedad pero espero. Seguro está ocupado/a.', en: 'It gives me some anxiety but I wait. They\'re probably busy.', fr: 'Ça me génère un peu d\'anxiété mais j\'attends. Il/elle est sûrement occupé(e).', de: 'Es erzeugt etwas Angst, aber ich warte. Er/sie ist wahrscheinlich beschäftigt.', it: 'Mi genera un po\' di ansia ma aspetto. Sarà sicuramente occupato/a.', pt: 'Me gera alguma ansiedade mas espero. Deve estar ocupado/a.' }, dimension: 'S' },
      { text: { es: 'Confío en que tendrá su razón. Me cuenta cuando puede.', en: 'I trust they have their reasons. They\'ll tell me when they can.', fr: 'Je fais confiance qu\'il/elle a ses raisons. Il/elle me raconte quand il/elle peut.', de: 'Ich vertraue darauf, dass er/sie seinen/ihren Grund hat. Er/sie erzählt es mir, wenn er/sie kann.', it: 'Mi fido che avrà le sue ragioni. Me lo racconterà quando può.', pt: 'Confio que terá seus motivos. Me conta quando puder.' }, dimension: 'T' },
    ] },
    { id: 6, situation: { es: 'Tu pareja tiene una noche de trabajo con colegas y no te invita.', en: 'Your partner has a work night with colleagues and doesn\'t invite you.', fr: 'Ton/ta partenaire a une soirée de travail avec des collègues et ne t\'invite pas.', de: 'Dein Partner/deine Partnerin hat einen Arbeitsabend mit Kollegen und lädt dich nicht ein.', it: 'Il tuo partner ha una serata di lavoro con colleghi e non ti invita.', pt: 'Seu parceiro tem uma noite de trabalho com colegas e não te convida.' }, options: [
      { text: { es: 'Le pregunto específicamente con quién va y dónde.', en: 'I ask specifically who they\'re going with and where.', fr: 'Je lui demande spécifiquement avec qui il/elle va et où.', de: 'Ich frage spezifisch, mit wem er/sie geht und wohin.', it: 'Gli chiedo specificatamente con chi va e dove.', pt: 'Pergunto especificamente com quem vai e onde.' }, dimension: 'R' },
      { text: { es: 'Le pido que me mande un mensaje cuando llegue a casa.', en: 'I ask them to send me a message when they get home.', fr: 'Je lui demande de m\'envoyer un message quand il/elle arrive à la maison.', de: 'Ich bitte ihn/sie, mir eine Nachricht zu schicken, wenn er/sie nach Hause kommt.', it: 'Gli chiedo di mandarmi un messaggio quando arriva a casa.', pt: 'Peço que me mande uma mensagem quando chegar em casa.' }, dimension: 'C' },
      { text: { es: 'Está bien, pero noto que preferiría que me lo hubiera contado antes y no último momento.', en: 'It\'s fine, but I notice I would have preferred they told me earlier and not at the last minute.', fr: 'D\'accord, mais je remarque que j\'aurais préféré qu\'il/elle me le dise avant et pas à la dernière minute.', de: 'Gut, aber ich bemerke, dass ich es vorgezogen hätte, wenn er/sie es mir früher gesagt hätte.', it: 'Va bene, ma noto che avrei preferito che me lo avesse detto prima e non all\'ultimo momento.', pt: 'Tudo bem, mas noto que preferiria que tivesse me contado antes e não em cima da hora.' }, dimension: 'S' },
      { text: { es: 'Sin problema. Tiene su vida profesional y es sano que la viva.', en: 'No problem. They have their professional life and it\'s healthy that they live it.', fr: 'Pas de problème. Il/elle a sa vie professionnelle et c\'est sain qu\'il/elle la vive.', de: 'Kein Problem. Er/sie hat sein/ihr Berufsleben und es ist gesund, dass er/sie es lebt.', it: 'Nessun problema. Ha la sua vita professionale ed è sano che la viva.', pt: 'Sem problema. Tem sua vida profissional e é saudável que a viva.' }, dimension: 'T' },
    ] },
    { id: 7, situation: { es: 'Descubres que tu pareja omitió contarte sobre un plan que hizo con alguien.', en: 'You discover your partner omitted telling you about a plan they made with someone.', fr: 'Tu découvres que ton/ta partenaire a omis de te parler d\'un plan qu\'il/elle a fait avec quelqu\'un.', de: 'Du entdeckst, dass dein Partner/deine Partnerin dir von einem Plan mit jemandem nicht erzählt hat.', it: 'Scopri che il tuo partner ha omesso di parlarti di un piano che ha fatto con qualcuno.', pt: 'Você descobre que seu parceiro omitiu te contar sobre um plano que fez com alguém.' }, options: [
      { text: { es: 'Me pongo inmediatamente en modo interrogatorio. ¿Por qué no me lo dijo?', en: 'I immediately go into interrogation mode. Why didn\'t they tell me?', fr: 'Je passe immédiatement en mode interrogatoire. Pourquoi ne me l\'a-t-il/elle pas dit ?', de: 'Ich schalte sofort in den Verhörmodus. Warum hat er/sie es mir nicht gesagt?', it: 'Mi metto immediatamente in modalità interrogatorio. Perché non me l\'ha detto?', pt: 'Entro imediatamente em modo interrogatório. Por que não me disse?' }, dimension: 'R' },
      { text: { es: 'Le digo que no me gusta enterarme de las cosas por terceros y que espero más comunicación.', en: 'I tell them I don\'t like finding out things through third parties and that I expect more communication.', fr: 'Je lui dis que je n\'aime pas apprendre les choses par des tiers et que j\'attends plus de communication.', de: 'Ich sage ihm/ihr, dass ich es nicht mag, Dinge durch Dritte zu erfahren, und dass ich mehr Kommunikation erwarte.', it: 'Gli dico che non mi piace venire a sapere le cose da terzi e che mi aspetto più comunicazione.', pt: 'Digo que não gosto de saber das coisas por terceiros e que espero mais comunicação.' }, dimension: 'C' },
      { text: { es: 'Lo menciono con calma. Quiero entender si fue intencional o simplemente se olvidó.', en: 'I mention it calmly. I want to understand if it was intentional or they simply forgot.', fr: 'Je le mentionne calmement. Je veux comprendre si c\'était intentionnel ou s\'il/elle a simplement oublié.', de: 'Ich erwähne es ruhig. Ich möchte verstehen, ob es absichtlich war oder er/sie es einfach vergessen hat.', it: 'Lo menziono con calma. Voglio capire se è stato intenzionale o semplicemente lo ha dimenticato.', pt: 'Menciono com calma. Quero entender se foi intencional ou simplesmente esqueceu.' }, dimension: 'S' },
      { text: { es: 'No me parece grave. No tiene que contarme cada plan que hace.', en: 'I don\'t think it\'s serious. They don\'t have to tell me every plan they make.', fr: 'Je ne pense pas que c\'est grave. Il/elle n\'a pas à me dire chaque plan qu\'il/elle fait.', de: 'Ich finde es nicht ernst. Er/sie muss mir nicht jeden Plan, den er/sie macht, mitteilen.', it: 'Non mi sembra grave. Non deve raccontarmi ogni piano che fa.', pt: 'Não me parece grave. Não precisa me contar cada plano que faz.' }, dimension: 'T' },
    ] },
    { id: 8, situation: { es: 'Tu pareja sigue en contacto con alguien con quien tuvo algo antes de conocerte.', en: 'Your partner keeps in contact with someone they had something with before meeting you.', fr: 'Ton/ta partenaire reste en contact avec quelqu\'un avec qui il/elle avait quelque chose avant de te connaître.', de: 'Dein Partner/deine Partnerin bleibt in Kontakt mit jemandem, mit dem/der er/sie etwas hatte, bevor er/sie dich kennenlernte.', it: 'Il tuo partner rimane in contatto con qualcuno con cui aveva avuto qualcosa prima di conoscerti.', pt: 'Seu parceiro continua em contato com alguém com quem teve algo antes de te conhecer.' }, options: [
      { text: { es: 'Reviso discretamente (o no tan discretamente) esas conversaciones cuando puedo.', en: 'I check those conversations discreetly (or not so discreetly) when I can.', fr: 'Je vérifie discrètement (ou pas si discrètement) ces conversations quand je peux.', de: 'Ich überprüfe diese Gespräche diskret (oder nicht so diskret), wenn ich kann.', it: 'Controllo discretamente (o non così discretamente) quelle conversazioni quando posso.', pt: 'Verifico discretamente (ou não tão discretamente) essas conversas quando posso.' }, dimension: 'R' },
      { text: { es: 'Establezco que esa relación tiene que tener límites claros para mí.', en: 'I establish that that relationship needs to have clear limits for me.', fr: 'J\'établis que cette relation doit avoir des limites claires pour moi.', de: 'Ich lege fest, dass diese Beziehung für mich klare Grenzen haben muss.', it: 'Stabilisco che quella relazione deve avere limiti chiari per me.', pt: 'Estabeleço que aquela relação precisa ter limites claros para mim.' }, dimension: 'C' },
      { text: { es: 'Me genera incomodidad pero confío hasta que haya una razón concreta para no hacerlo.', en: 'It makes me uncomfortable but I trust until there\'s a concrete reason not to.', fr: 'Ça me met mal à l\'aise mais je fais confiance jusqu\'à ce qu\'il y ait une raison concrète de ne pas le faire.', de: 'Es macht mich unwohl, aber ich vertraue, bis es einen konkreten Grund gibt, es nicht zu tun.', it: 'Mi crea disagio ma mi fido fino a quando non ci sia una ragione concreta per non farlo.', pt: 'Me gera desconforto mas confio até que haja razão concreta para não fazer isso.' }, dimension: 'S' },
      { text: { es: 'El pasado de mi pareja es suyo. No tengo derecho a controlar esas relaciones.', en: 'My partner\'s past is theirs. I have no right to control those relationships.', fr: 'Le passé de mon/ma partenaire lui appartient. Je n\'ai pas le droit de contrôler ces relations.', de: 'Die Vergangenheit meines Partners/meiner Partnerin gehört ihr/ihm. Ich habe kein Recht, diese Beziehungen zu kontrollieren.', it: 'Il passato del mio partner è suo. Non ho il diritto di controllare quelle relazioni.', pt: 'O passado do meu parceiro é dele/dela. Não tenho o direito de controlar essas relações.' }, dimension: 'T' },
    ] },
    { id: 9, situation: { es: 'En redes sociales, tu pareja da muchos likes a fotos de una persona específica.', en: 'On social media, your partner likes many photos of a specific person.', fr: 'Sur les réseaux sociaux, ton/ta partenaire donne beaucoup de likes aux photos d\'une personne spécifique.', de: 'In sozialen Medien gibt dein Partner/deine Partnerin vielen Fotos einer bestimmten Person Likes.', it: 'Sui social media, il tuo partner mette tanti like alle foto di una persona specifica.', pt: 'Nas redes sociais, seu parceiro curte muitas fotos de uma pessoa específica.' }, options: [
      { text: { es: 'Veo el perfil de esa persona para entender qué hay ahí.', en: 'I look at that person\'s profile to understand what\'s there.', fr: 'Je regarde le profil de cette personne pour comprendre ce qu\'il y a là.', de: 'Ich schaue mir das Profil dieser Person an, um zu verstehen, was dort ist.', it: 'Guardo il profilo di quella persona per capire cosa c\'è là.', pt: 'Vejo o perfil dessa pessoa para entender o que há lá.' }, dimension: 'R' },
      { text: { es: 'Lo menciono. No es una acusación, pero quiero que sepa que lo noté.', en: 'I mention it. It\'s not an accusation, but I want them to know I noticed.', fr: 'Je le mentionne. Ce n\'est pas une accusation, mais je veux qu\'il/elle sache que j\'ai remarqué.', de: 'Ich erwähne es. Es ist keine Anklage, aber ich möchte, dass er/sie weiß, dass ich es bemerkt habe.', it: 'Lo menziono. Non è un\'accusa, ma voglio che sappia che l\'ho notato.', pt: 'Menciono. Não é uma acusação, mas quero que saiba que notei.' }, dimension: 'C' },
      { text: { es: 'Lo noto pero no le doy demasiada importancia. Es solo redes.', en: 'I notice it but don\'t give it too much importance. It\'s just social media.', fr: 'Je le remarque mais je ne lui donne pas trop d\'importance. Ce ne sont que des réseaux.', de: 'Ich bemerke es, aber ich gebe ihm nicht zu viel Bedeutung. Es ist nur soziale Medien.', it: 'Lo noto ma non gli do troppa importanza. Sono solo social.', pt: 'Noto mas não dou importância demais. São apenas redes.' }, dimension: 'S' },
      { text: { es: 'No me genera nada. Las redes no son un indicador de nada.', en: 'It doesn\'t generate anything in me. Social media is not an indicator of anything.', fr: 'Ça ne me génère rien. Les réseaux ne sont pas un indicateur de quoi que ce soit.', de: 'Es erzeugt nichts in mir. Soziale Medien sind kein Indikator für irgendetwas.', it: 'Non mi genera nulla. I social non sono un indicatore di nulla.', pt: 'Não me gera nada. As redes não são um indicador de nada.' }, dimension: 'T' },
    ] },
    { id: 10, situation: { es: 'Tu pareja y tú están en momentos de vida muy diferentes. Él/ella tiene mucho más éxito ahora.', en: 'You and your partner are at very different life moments. They\'re much more successful now.', fr: 'Toi et ton/ta partenaire êtes à des moments de vie très différents. Il/elle a beaucoup plus de succès maintenant.', de: 'Du und dein Partner/deine Partnerin befinden sich in sehr unterschiedlichen Lebensmomenten. Er/sie ist jetzt viel erfolgreicher.', it: 'Tu e il tuo partner siete in momenti di vita molto diversi. Ha molto più successo ora.', pt: 'Você e seu parceiro estão em momentos de vida muito diferentes. Ele/ela tem muito mais sucesso agora.' }, options: [
      { text: { es: 'Me pregunto si seguirá necesitando lo mismo que yo le puedo dar.', en: 'I wonder if they\'ll still need what I can give them.', fr: 'Je me demande s\'il/elle aura encore besoin de ce que je peux lui donner.', de: 'Ich frage mich, ob er/sie noch das brauchen wird, was ich ihm/ihr geben kann.', it: 'Mi chiedo se continuerà ad aver bisogno di quello che posso dargli.', pt: 'Me pergunto se continuará precisando do que posso dar.' }, dimension: 'R' },
      { text: { es: 'Busco formas de estar a su nivel o de agregar valor a su vida de formas nuevas.', en: 'I look for ways to be at their level or add value to their life in new ways.', fr: 'Je cherche des façons d\'être à son niveau ou d\'apporter de la valeur à sa vie de nouvelles façons.', de: 'Ich suche nach Wegen, auf sein/ihr Niveau zu kommen oder seinem/ihrem Leben auf neue Weise Mehrwert zu bieten.', it: 'Cerco modi per essere al suo livello o aggiungere valore alla sua vita in modi nuovi.', pt: 'Busco formas de estar no nível dele/dela ou acrescentar valor à vida dele/dela de novas formas.' }, dimension: 'C' },
      { text: { es: 'Lo proceso con algo de inseguridad, pero confío en que nuestra relación tiene bases propias.', en: 'I process it with some insecurity, but I trust that our relationship has its own foundations.', fr: 'Je le traite avec un peu d\'insécurité, mais je fais confiance que notre relation a ses propres bases.', de: 'Ich verarbeite es mit etwas Unsicherheit, aber ich vertraue darauf, dass unsere Beziehung eigene Grundlagen hat.', it: 'Lo processo con un po\' di insicurezza, ma mi fido che la nostra relazione abbia basi proprie.', pt: 'Processo com alguma insegurança, mas confio que nosso relacionamento tem bases próprias.' }, dimension: 'S' },
      { text: { es: 'Me alegra su éxito. Las relaciones sanas soportan las diferencias de ritmo.', en: 'I\'m glad for their success. Healthy relationships withstand differences in pace.', fr: 'Je suis content(e) de son succès. Les relations saines supportent les différences de rythme.', de: 'Ich freue mich über seinen/ihren Erfolg. Gesunde Beziehungen tragen Unterschiede im Tempo.', it: 'Sono contento/a del suo successo. Le relazioni sane sopportano le differenze di ritmo.', pt: 'Fico feliz pelo sucesso dele/dela. Relacionamentos saudáveis suportam diferenças de ritmo.' }, dimension: 'T' },
    ] },
  ],
  characters: [
    { name: { es: 'El Celoso Reactivo', en: 'The Reactive Jealous', fr: 'Le Jaloux Réactif', de: 'Der Reaktive Eifersüchtige', it: 'Il Geloso Reattivo', pt: 'O Ciumento Reativo' }, dimensions: ['R'], photo: '/characters/reactive-jealous.jpg', description: { es: 'Sus celos explotan antes de que pueda procesarlos.', en: 'Their jealousy explodes before they can process it.', fr: 'Sa jalousie explose avant qu\'il/elle puisse la traiter.', de: 'Seine/ihre Eifersucht explodiert, bevor er/sie sie verarbeiten kann.', it: 'La sua gelosia esplode prima che possa elaborarla.', pt: 'Seu ciúme explode antes que possa processá-lo.' }, philosophy: { es: 'Tu sistema de alarma interna es muy sensible. Reaccionas antes de pensar porque el miedo actúa más rápido que la razón. No es que no confíes — es que el miedo a perder al otro es demasiado intenso para manejarlo en calma.', en: 'Your internal alarm system is very sensitive. You react before thinking because fear acts faster than reason. It\'s not that you don\'t trust — it\'s that the fear of losing the other is too intense to handle calmly.', fr: 'Ton système d\'alarme interne est très sensible. Tu réagis avant de penser parce que la peur agit plus vite que la raison. Ce n\'est pas que tu ne fais pas confiance — c\'est que la peur de perdre l\'autre est trop intense pour la gérer calmement.', de: 'Dein internes Alarmsystem ist sehr sensibel. Du reagierst, bevor du denkst, weil Angst schneller handelt als Vernunft. Es ist nicht so, dass du nicht vertraust — die Angst, den anderen zu verlieren, ist zu intensiv, um sie ruhig zu handhaben.', it: 'Il tuo sistema di allarme interno è molto sensibile. Reagisci prima di pensare perché la paura agisce più velocemente della ragione. Non è che non ti fidi — è che la paura di perdere l\'altro è troppo intensa per gestirla con calma.', pt: 'Seu sistema de alarme interno é muito sensível. Você reage antes de pensar porque o medo age mais rápido que a razão. Não é que você não confie — é que o medo de perder o outro é intenso demais para lidar com calma.' } },
    { name: { es: 'El Celoso Controlador', en: 'The Controlling Jealous', fr: 'Le Jaloux Contrôleur', de: 'Der Kontrollierende Eifersüchtige', it: 'Il Geloso Controllore', pt: 'O Ciumento Controlador' }, dimensions: ['C'], photo: '/characters/controlling-jealous.jpg', description: { es: 'Intenta gestionar su inseguridad controlando al otro.', en: 'Tries to manage their insecurity by controlling the other.', fr: 'Essaie de gérer son insécurité en contrôlant l\'autre.', de: 'Versucht, seine/ihre Unsicherheit zu verwalten, indem er/sie den anderen kontrolliert.', it: 'Cerca di gestire la propria insicurezza controllando l\'altro.', pt: 'Tenta gerenciar sua insegurança controlando o outro.' }, philosophy: { es: 'Crees que si controlas el entorno, controlas el miedo. Pero los límites que impones no calman tu ansiedad — la alimentan. Cada control exitoso solo confirma que sin él, el miedo volvería.', en: 'You believe that if you control the environment, you control fear. But the limits you impose don\'t calm your anxiety — they feed it. Each successful control only confirms that without it, fear would return.', fr: 'Tu crois que si tu contrôles l\'environnement, tu contrôles la peur. Mais les limites que tu imposes ne calment pas ton anxiété — elles l\'alimentent. Chaque contrôle réussi confirme seulement que sans lui, la peur reviendrait.', de: 'Du glaubst, wenn du die Umgebung kontrollierst, kontrollierst du die Angst. Aber die Grenzen, die du auferlegst, beruhigen deine Angst nicht — sie nähren sie. Jede erfolgreiche Kontrolle bestätigt nur, dass ohne sie die Angst zurückkehren würde.', it: 'Credi che se controlli l\'ambiente, controlli la paura. Ma i limiti che imponi non calmano la tua ansia — la alimentano. Ogni controllo riuscito conferma solo che senza di esso, la paura tornerebbe.', pt: 'Você acredita que se controlar o ambiente, controla o medo. Mas os limites que impõe não acalmam sua ansiedade — a alimentam. Cada controle bem-sucedido apenas confirma que sem ele, o medo voltaria.' } },
    { name: { es: 'El Celoso Silencioso', en: 'The Silent Jealous', fr: 'Le Jaloux Silencieux', de: 'Der Stille Eifersüchtige', it: 'Il Geloso Silenzioso', pt: 'O Ciumento Silencioso' }, dimensions: ['S'], photo: '/characters/silent-jealous.jpg', description: { es: 'Siente pero no actúa. Procesa internamente y decide cuándo hablar.', en: 'Feels but doesn\'t act. Processes internally and decides when to speak.', fr: 'Ressent mais n\'agit pas. Traite intérieurement et décide quand parler.', de: 'Fühlt, handelt aber nicht. Verarbeitet innerlich und entscheidet, wann zu sprechen.', it: 'Sente ma non agisce. Elabora internamente e decide quando parlare.', pt: 'Sente mas não age. Processa internamente e decide quando falar.' }, philosophy: { es: 'Tienes celos como todo el mundo, pero tu madurez emocional te permite procesarlos antes de actuar. No siempre es perfecto — a veces lo que callas se acumula — pero en general navegas esos momentos con mucha más inteligencia que la mayoría.', en: 'You have jealousy like everyone, but your emotional maturity allows you to process it before acting. It\'s not always perfect — sometimes what you keep silent accumulates — but in general you navigate those moments with much more intelligence than most.', fr: 'Tu as de la jalousie comme tout le monde, mais ta maturité émotionnelle te permet de la traiter avant d\'agir. Ce n\'est pas toujours parfait — parfois ce que tu tais s\'accumule — mais en général tu navigues ces moments avec beaucoup plus d\'intelligence que la plupart.', de: 'Du hast Eifersucht wie jeder, aber deine emotionale Reife erlaubt es dir, sie zu verarbeiten, bevor du handelst. Es ist nicht immer perfekt — manchmal häuft sich an, was du schweigst — aber im Allgemeinen navigierst du diese Momente mit viel mehr Intelligenz als die meisten.', it: 'Hai gelosia come tutti, ma la tua maturità emotiva ti permette di elaborarla prima di agire. Non è sempre perfetto — a volte quello che taci si accumula — ma in generale navighi quei momenti con molta più intelligenza della maggior parte.', pt: 'Você tem ciúme como todo mundo, mas sua maturidade emocional permite processar antes de agir. Nem sempre é perfeito — às vezes o que você cala se acumula — mas em geral navega esses momentos com muito mais inteligência que a maioria.' } },
    { name: { es: 'El Confiante Seguro', en: 'The Trusting Secure', fr: 'Le Confiant Sûr', de: 'Der Vertrauende Sichere', it: 'Il Fidante Sicuro', pt: 'O Confiante Seguro' }, dimensions: ['T'], photo: '/characters/trusting.jpg', description: { es: 'La confianza no es ingenuidad — es su base de operaciones.', en: 'Trust is not naivety — it\'s their base of operations.', fr: 'La confiance n\'est pas de la naïveté — c\'est sa base d\'opérations.', de: 'Vertrauen ist keine Naivität — es ist seine Operationsbasis.', it: 'La fiducia non è ingenuità — è la sua base operativa.', pt: 'A confiança não é ingenuidade — é sua base de operações.' }, philosophy: { es: 'Tu confianza no viene de no ver las señales — viene de elegir conscientemente confiar hasta que haya razones concretas para no hacerlo. Esa seguridad no es debilidad. Es la única base posible para una relación sana.', en: 'Your trust doesn\'t come from not seeing the signs — it comes from consciously choosing to trust until there are concrete reasons not to. That security is not weakness. It\'s the only possible foundation for a healthy relationship.', fr: 'Ta confiance ne vient pas du fait de ne pas voir les signes — elle vient du choix conscient de faire confiance jusqu\'à ce qu\'il y ait des raisons concrètes de ne pas le faire. Cette sécurité n\'est pas une faiblesse. C\'est la seule base possible pour une relation saine.', de: 'Dein Vertrauen kommt nicht davon, keine Zeichen zu sehen — es kommt von der bewussten Entscheidung zu vertrauen, bis es konkrete Gründe gibt, es nicht zu tun. Diese Sicherheit ist keine Schwäche. Es ist die einzig mögliche Grundlage für eine gesunde Beziehung.', it: 'La tua fiducia non deriva dal non vedere i segnali — viene dalla scelta consapevole di fidarsi finché non ci sono ragioni concrete per non farlo. Quella sicurezza non è debolezza. È l\'unica base possibile per una relazione sana.', pt: 'Sua confiança não vem de não ver os sinais — vem de escolher conscientemente confiar até que haja razões concretas para não fazê-lo. Essa segurança não é fraqueza. É a única base possível para um relacionamento saudável.' } },
    { name: { es: 'El Ansioso-Controlador', en: 'The Anxious Controller', fr: 'L\'Anxieux Contrôleur', de: 'Der Ängstliche Kontrolleur', it: 'L\'Ansioso-Controllore', pt: 'O Ansioso-Controlador' }, dimensions: ['R', 'C'], photo: '/characters/anxious-controller.jpg', description: { es: 'Reacciona con ansiedad y luego intenta controlar para calmarla.', en: 'Reacts with anxiety and then tries to control to calm it.', fr: 'Réagit avec anxiété et essaie ensuite de contrôler pour la calmer.', de: 'Reagiert mit Angst und versucht dann zu kontrollieren, um sie zu beruhigen.', it: 'Reagisce con ansia e poi cerca di controllare per calmarla.', pt: 'Reage com ansiedade e depois tenta controlar para acalmá-la.' }, philosophy: { es: 'Tu ciclo es: sientes, reaccionas, controlas, te tranquilizas, sientes de nuevo. Es agotador para ti y para quien está al lado. La raíz no es el otro — es un miedo interno que no se puede controlar desde afuera.', en: 'Your cycle is: feel, react, control, calm down, feel again. It\'s exhausting for you and for whoever is beside you. The root isn\'t the other — it\'s an internal fear that can\'t be controlled from the outside.', fr: 'Ton cycle est : ressentir, réagir, contrôler, se calmer, ressentir à nouveau. C\'est épuisant pour toi et pour celui/celle qui est à côté. La racine n\'est pas l\'autre — c\'est une peur interne qui ne peut pas être contrôlée de l\'extérieur.', de: 'Dein Zyklus ist: fühlen, reagieren, kontrollieren, beruhigen, wieder fühlen. Es ist erschöpfend für dich und für denjenigen, der daneben ist. Die Wurzel ist nicht der andere — es ist eine innere Angst, die von außen nicht kontrolliert werden kann.', it: 'Il tuo ciclo è: senti, reagisci, controlli, ti calmi, senti di nuovo. È estenuante per te e per chi è accanto. La radice non è l\'altro — è una paura interna che non può essere controllata dall\'esterno.', pt: 'Seu ciclo é: sente, reage, controla, se acalma, sente de novo. É exaustivo para você e para quem está ao lado. A raiz não é o outro — é um medo interno que não pode ser controlado de fora.' } },
    { name: { es: 'El Inseguro Silencioso', en: 'The Silent Insecure', fr: 'L\'Insécure Silencieux', de: 'Der Stille Unsichere', it: 'L\'Insicuro Silenzioso', pt: 'O Inseguro Silencioso' }, dimensions: ['R', 'S'], photo: '/characters/insecure-silent.jpg', description: { es: 'Tiene celos fuertes pero los reprime. Volcán en espera.', en: 'Has strong jealousy but suppresses it. Volcano waiting.', fr: 'A une jalousie forte mais la refoule. Volcan en attente.', de: 'Hat starke Eifersucht, unterdrückt sie aber. Wartender Vulkan.', it: 'Ha una gelosia forte ma la reprime. Vulcano in attesa.', pt: 'Tem ciúme forte mas o reprime. Vulcão em espera.' }, philosophy: { es: 'Eres una combinación de gran reactividad interna y gran control externo. Por fuera pareces bien. Por dentro, llevas las cuentas. En algún punto, lo que acumulas sale — y sale con fuerza.', en: 'You\'re a combination of great internal reactivity and great external control. On the outside you seem fine. Inside, you\'re keeping score. At some point, what you accumulate comes out — and comes out with force.', fr: 'Tu es une combinaison de grande réactivité interne et de grand contrôle externe. Vu de l\'extérieur, tu sembles bien. À l\'intérieur, tu gardes les comptes. À un moment, ce que tu accumules sort — et sort avec force.', de: 'Du bist eine Kombination aus großer innerer Reaktivität und großer äußerer Kontrolle. Von außen siehst du gut aus. Innen führst du Buch. Irgendwann kommt raus, was du ansammelst — und kommt mit Kraft raus.', it: 'Sei una combinazione di grande reattività interna e grande controllo esterno. Dall\'esterno sembri bene. Dentro, tieni i conti. A un certo punto, quello che accumuli esce — ed esce con forza.', pt: 'Você é uma combinação de grande reatividade interna e grande controle externo. Por fora parece bem. Por dentro, guarda as contas. Em algum momento, o que você acumula sai — e sai com força.' } },
    { name: { es: 'El Celoso en Proceso', en: 'The Jealous in Progress', fr: 'Le Jaloux en Progrès', de: 'Der Eifersüchtige in Entwicklung', it: 'Il Geloso in Progresso', pt: 'O Ciumento em Processo' }, dimensions: ['C', 'S'], photo: '/characters/jealous-in-progress.jpg', description: { es: 'Trabaja activamente sus celos. Tiene límites pero los negocia.', en: 'Actively works on their jealousy. Has limits but negotiates them.', fr: 'Travaille activement sa jalousie. A des limites mais les négocie.', de: 'Arbeitet aktiv an seiner/ihrer Eifersucht. Hat Grenzen, verhandelt sie aber.', it: 'Lavora attivamente sulla propria gelosia. Ha limiti ma li negozia.', pt: 'Trabalha ativamente seu ciúme. Tem limites mas os negocia.' }, philosophy: { es: 'Reconoces que tus celos existen, que a veces te llevan a querer controlar, y estás trabajando en ello. Eso ya te pone en una categoría diferente. La conciencia de sí mismo es el primer paso.', en: 'You recognize that your jealousy exists, that it sometimes leads you to want to control, and you\'re working on it. That already puts you in a different category. Self-awareness is the first step.', fr: 'Tu reconnais que ta jalousie existe, qu\'elle te pousse parfois à vouloir contrôler, et tu travailles dessus. Ça te met déjà dans une catégorie différente. La conscience de soi est le premier pas.', de: 'Du erkennst, dass deine Eifersucht existiert, dass sie dich manchmal dazu bringt, kontrollieren zu wollen, und du arbeitest daran. Das setzt dich bereits in eine andere Kategorie. Selbstbewusstsein ist der erste Schritt.', it: 'Riconosci che la tua gelosia esiste, che a volte ti porta a voler controllare, e stai lavorandoci. Questo ti mette già in una categoria diversa. La consapevolezza di sé è il primo passo.', pt: 'Você reconhece que seu ciúme existe, que às vezes te leva a querer controlar, e está trabalhando nisso. Isso já te coloca em uma categoria diferente. A consciência de si mesmo é o primeiro passo.' } },
    { name: { es: 'La Seguridad Real', en: 'Real Security', fr: 'La Sécurité Réelle', de: 'Echte Sicherheit', it: 'La Sicurezza Reale', pt: 'A Segurança Real' }, dimensions: ['S', 'T'], photo: '/characters/real-security.jpg', description: { es: 'Siente pero no se deja llevar. Confía sin ser ingenuo/a.', en: 'Feels but doesn\'t get carried away. Trusts without being naive.', fr: 'Ressent mais ne se laisse pas emporter. Fait confiance sans être naïf/ve.', de: 'Fühlt, lässt sich aber nicht mitreißen. Vertraut ohne naiv zu sein.', it: 'Sente ma non si fa trascinare. Si fida senza essere ingenuo/a.', pt: 'Sente mas não se deixa levar. Confia sem ser ingênuo/a.' }, philosophy: { es: 'Tu seguridad es producto de trabajo, no de ausencia de celos. Los sientes, los procesas, y después eliges confiar. Esa elección consciente es lo que hace que tus relaciones puedan ser duraderas.', en: 'Your security is the product of work, not the absence of jealousy. You feel it, process it, and then choose to trust. That conscious choice is what makes your relationships able to be lasting.', fr: 'Ta sécurité est le produit du travail, pas de l\'absence de jalousie. Tu la ressens, tu la traites, et ensuite tu choisis de faire confiance. Ce choix conscient est ce qui fait que tes relations peuvent être durables.', de: 'Deine Sicherheit ist das Produkt von Arbeit, nicht die Abwesenheit von Eifersucht. Du fühlst sie, verarbeitest sie und entscheidest dich dann zu vertrauen. Diese bewusste Entscheidung ist das, was deine Beziehungen dauerhaft machen kann.', it: 'La tua sicurezza è il prodotto del lavoro, non dell\'assenza di gelosia. La senti, la elabori, e poi scegli di fidarti. Quella scelta consapevole è ciò che fa sì che le tue relazioni possano essere durature.', pt: 'Sua segurança é produto de trabalho, não de ausência de ciúme. Você o sente, processa, e depois escolhe confiar. Essa escolha consciente é o que faz seus relacionamentos poderem ser duradouros.' } },
  ],
};

export async function seedJealous(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'jealous' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'jealous',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
