import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan adicto/a al trabajo eres?', en: 'How addicted to work are you?', fr: 'À quel point es-tu accro au travail ?', de: 'Wie arbeitsbesessen bist du?', it: 'Quanto sei dipendente dal lavoro?', pt: 'O quanto você é viciado/a em trabalho?' },
  description: { es: 'Trabajar mucho no es el problema. El problema es cuando el trabajo se convierte en escape.', en: 'Working a lot is not the problem. The problem is when work becomes an escape.', fr: 'Travailler beaucoup n\'est pas le problème. Le problème, c\'est quand le travail devient une échappatoire.', de: 'Viel zu arbeiten ist nicht das Problem. Das Problem ist, wenn die Arbeit zu einer Flucht wird.', it: 'Lavorare tanto non è il problema. Il problema è quando il lavoro diventa una fuga.', pt: 'Trabalhar muito não é o problema. O problema é quando o trabalho se torna uma fuga.' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { W: 'Adicción', D: 'Dedicación', E: 'Equilibrio', R: 'Recuperación' },
    en: { W: 'Addiction', D: 'Dedication', E: 'Balance', R: 'Recovery' },
    fr: { W: 'Addiction', D: 'Dédication', E: 'Équilibre', R: 'Récupération' },
    de: { W: 'Sucht', D: 'Hingabe', E: 'Balance', R: 'Erholung' },
    it: { W: 'Dipendenza', D: 'Dedizione', E: 'Equilibrio', R: 'Recupero' },
    pt: { W: 'Dependência', D: 'Dedicação', E: 'Equilíbrio', R: 'Recuperação' },
  },
  questions: [
    { id: 1, situation: { es: 'Es sábado a las 10am. No tienes compromisos. ¿Qué estás haciendo?', en: 'It\'s Saturday at 10am. You have no commitments. What are you doing?', fr: 'C\'est samedi à 10h du matin. Tu n\'as aucun engagement. Qu\'est-ce que tu fais ?', de: 'Es ist Samstag um 10 Uhr morgens. Du hast keine Verpflichtungen. Was machst du?', it: 'È sabato alle 10 del mattino. Non hai impegni. Cosa stai facendo?', pt: 'É sábado às 10h. Você não tem compromissos. O que você está fazendo?' }, options: [
      { text: { es: 'Revisando el correo o adelantando trabajo. Me siento productivo/a.', en: 'Checking email or getting ahead on work. I feel productive.', fr: 'Je révise mes emails ou j\'avance dans le travail. Je me sens productif(ve).', de: 'E-Mails prüfen oder Arbeit voraus erledigen. Ich fühle mich produktiv.', it: 'Controllo le email o anticipo il lavoro. Mi sento produttivo/a.', pt: 'Verificando e-mail ou adiantando trabalho. Me sinto produtivo/a.' }, dimension: 'W' },
      { text: { es: 'Probablemente trabajando en algo que me importa. Porque quiero, no porque deba.', en: 'Probably working on something that matters to me. Because I want to, not because I should.', fr: 'Probablement en train de travailler sur quelque chose qui me tient à cœur. Parce que je veux, pas parce que je dois.', de: 'Wahrscheinlich an etwas arbeiten, das mir wichtig ist. Weil ich will, nicht weil ich muss.', it: 'Probabilmente lavorando su qualcosa che mi importa. Perché voglio, non perché devo.', pt: 'Provavelmente trabalhando em algo que me importa. Porque quero, não porque devo.' }, dimension: 'D' },
      { text: { es: 'Desconectado/a completamente. El fin de semana es sagrado.', en: 'Completely disconnected. The weekend is sacred.', fr: 'Complètement déconnecté(e). Le week-end est sacré.', de: 'Vollständig abgeschaltet. Das Wochenende ist heilig.', it: 'Completamente scollegato/a. Il fine settimana è sacro.', pt: 'Completamente desconectado/a. O fim de semana é sagrado.' }, dimension: 'E' },
      { text: { es: 'Haciendo algo que me recargue: ejercicio, naturaleza, personas que quiero.', en: 'Doing something that recharges me: exercise, nature, people I love.', fr: 'En train de faire quelque chose qui me recharge : exercice, nature, personnes que j\'aime.', de: 'Etwas tun, das mich auflädt: Sport, Natur, Menschen, die ich liebe.', it: 'Facendo qualcosa che mi ricarica: esercizio, natura, persone che voglio bene.', pt: 'Fazendo algo que me recarregue: exercício, natureza, pessoas que amo.' }, dimension: 'R' },
    ] },
    { id: 2, situation: { es: 'Estás de vacaciones y tu teléfono tiene una notificación de trabajo. ¿Qué haces?', en: 'You\'re on vacation and your phone has a work notification. What do you do?', fr: 'Tu es en vacances et ton téléphone a une notification de travail. Que fais-tu ?', de: 'Du bist im Urlaub und dein Telefon hat eine Arbeitsbenachrichtigung. Was tust du?', it: 'Sei in vacanza e il tuo telefono ha una notifica di lavoro. Cosa fai?', pt: 'Você está de férias e seu telefone tem uma notificação de trabalho. O que você faz?' }, options: [
      { text: { es: 'La reviso inmediatamente. No puedo ignorarla.', en: 'I check it immediately. I can\'t ignore it.', fr: 'Je la vérifie immédiatement. Je ne peux pas l\'ignorer.', de: 'Ich überprüfe sie sofort. Ich kann sie nicht ignorieren.', it: 'La controllo immediatamente. Non riesco a ignorarla.', pt: 'Verifico imediatamente. Não consigo ignorar.' }, dimension: 'W' },
      { text: { es: 'La reviso si parece urgente. Si no, espera.', en: 'I check it if it seems urgent. If not, it waits.', fr: 'Je la vérifie si ça semble urgent. Sinon, ça attend.', de: 'Ich überprüfe es, wenn es dringend erscheint. Wenn nicht, wartet es.', it: 'La controllo se sembra urgente. Se no, aspetta.', pt: 'Verifico se parece urgente. Se não, espera.' }, dimension: 'D' },
      { text: { es: 'No la reviso. Si era urgente, alguien me llamará.', en: 'I don\'t check it. If it was urgent, someone will call.', fr: 'Je ne la vérifie pas. Si c\'était urgent, quelqu\'un m\'appellera.', de: 'Ich überprüfe es nicht. Wenn es dringend war, wird mich jemand anrufen.', it: 'Non la controllo. Se era urgente, qualcuno mi chiamerà.', pt: 'Não verifico. Se era urgente, alguém vai ligar.' }, dimension: 'E' },
      { text: { es: 'Reviso al final del día solo para asegurarme de que no hay emergencias.', en: 'I check at the end of the day just to make sure there are no emergencies.', fr: 'Je vérifie en fin de journée juste pour m\'assurer qu\'il n\'y a pas d\'urgences.', de: 'Ich überprüfe am Ende des Tages, um sicherzustellen, dass es keine Notfälle gibt.', it: 'Controllo a fine giornata solo per assicurarmi che non ci siano emergenze.', pt: 'Verifico ao final do dia apenas para garantir que não há emergências.' }, dimension: 'R' },
    ] },
    { id: 3, situation: { es: '¿Cuándo fue la última vez que pasaste un día completo sin pensar en el trabajo?', en: 'When was the last time you spent a full day without thinking about work?', fr: 'Quand était la dernière fois que tu as passé une journée entière sans penser au travail ?', de: 'Wann war das letzte Mal, dass du einen ganzen Tag verbracht hast, ohne an die Arbeit zu denken?', it: 'Quando è stata l\'ultima volta che hai trascorso una giornata intera senza pensare al lavoro?', pt: 'Quando foi a última vez que você passou um dia inteiro sem pensar no trabalho?' }, options: [
      { text: { es: 'No recuerdo. Siempre hay algo dando vueltas.', en: 'I don\'t remember. There\'s always something going around.', fr: 'Je ne me souviens pas. Il y a toujours quelque chose qui tourne.', de: 'Ich erinnere mich nicht. Es gibt immer etwas, das sich dreht.', it: 'Non ricordo. C\'è sempre qualcosa che gira.', pt: 'Não me lembro. Sempre há algo girando na cabeça.' }, dimension: 'W' },
      { text: { es: 'Cuando estoy completamente absorbido/a en algo que no tiene nada que ver.', en: 'When I\'m completely absorbed in something that has nothing to do with it.', fr: 'Quand je suis complètement absorbé(e) dans quelque chose qui n\'a rien à voir.', de: 'Wenn ich völlig in etwas versunken bin, das nichts damit zu tun hat.', it: 'Quando sono completamente assorbito/a in qualcosa che non c\'entra niente.', pt: 'Quando estou completamente absorto/a em algo que não tem nada a ver.' }, dimension: 'D' },
      { text: { es: 'Regularmente. Me cuido de proteger tiempo libre real.', en: 'Regularly. I take care to protect real free time.', fr: 'Régulièrement. Je fais attention à protéger du temps libre réel.', de: 'Regelmäßig. Ich passe darauf auf, echte Freizeit zu schützen.', it: 'Regolarmente. Mi curo di proteggere il tempo libero reale.', pt: 'Regularmente. Me cuido para proteger tempo livre real.' }, dimension: 'E' },
      { text: { es: 'En vacaciones largas o en momentos muy específicos de descanso planeado.', en: 'On long vacations or in very specific moments of planned rest.', fr: 'En longues vacances ou dans des moments très spécifiques de repos planifié.', de: 'Im langen Urlaub oder in sehr spezifischen Momenten geplanter Ruhe.', it: 'In vacanze lunghe o in momenti molto specifici di riposo pianificato.', pt: 'Em férias longas ou em momentos muito específicos de descanso planejado.' }, dimension: 'R' },
    ] },
    { id: 4, situation: { es: 'Tu pareja dice que siente que el trabajo siempre está presente. ¿Cómo reaccionas?', en: 'Your partner says they feel like work is always present. How do you react?', fr: 'Ton/ta partenaire dit qu\'il/elle sent que le travail est toujours présent. Comment réagis-tu ?', de: 'Dein Partner/deine Partnerin sagt, er/sie fühlt, dass die Arbeit immer präsent ist. Wie reagierst du?', it: 'Il tuo partner dice che sente che il lavoro è sempre presente. Come reagisci?', pt: 'Seu parceiro/a diz que sente que o trabalho está sempre presente. Como você reage?' }, options: [
      { text: { es: 'Me molesta un poco. No entiende que esto es por nosotros.', en: 'It bothers me a bit. They don\'t understand that this is for us.', fr: 'Ça me dérange un peu. Il/elle ne comprend pas que c\'est pour nous.', de: 'Es stört mich ein wenig. Er/sie versteht nicht, dass es für uns ist.', it: 'Mi dà un po\' fastidio. Non capisce che questo è per noi.', pt: 'Me incomoda um pouco. Não entende que isso é por nós.' }, dimension: 'W' },
      { text: { es: 'Lo escucho y me comprometo a mejorar los límites.', en: 'I listen and commit to improving boundaries.', fr: 'Je l\'écoute et m\'engage à améliorer les limites.', de: 'Ich höre zu und verpflichte mich, die Grenzen zu verbessern.', it: 'Lo ascolto e mi impegno a migliorare i confini.', pt: 'Ouço e me comprometo a melhorar os limites.' }, dimension: 'D' },
      { text: { es: 'Es una señal de alerta importante que tomo muy en serio.', en: 'It\'s an important warning sign that I take very seriously.', fr: 'C\'est un signal d\'alarme important que je prends très au sérieux.', de: 'Es ist ein wichtiges Warnsignal, das ich sehr ernst nehme.', it: 'È un segnale d\'allarme importante che prendo molto sul serio.', pt: 'É um sinal de alerta importante que levo muito a sério.' }, dimension: 'E' },
      { text: { es: 'Ya lo sabía. Estoy trabajando en crear más rituales de desconexión.', en: 'I already knew it. I\'m working on creating more disconnection rituals.', fr: 'Je le savais déjà. Je travaille à créer plus de rituels de déconnexion.', de: 'Ich wusste es bereits. Ich arbeite daran, mehr Trennungsrituale zu schaffen.', it: 'Lo sapevo già. Sto lavorando per creare più rituali di disconnessione.', pt: 'Já sabia. Estou trabalhando em criar mais rituais de desconexão.' }, dimension: 'R' },
    ] },
    { id: 5, situation: { es: 'Terminas una semana agotadora. Tu plan ideal para el fin de semana es...', en: 'You finish an exhausting week. Your ideal plan for the weekend is...', fr: 'Tu termines une semaine épuisante. Ton plan idéal pour le week-end est...', de: 'Du beendest eine erschöpfende Woche. Dein idealer Plan für das Wochenende ist...', it: 'Finisci una settimana estenuante. Il tuo piano ideale per il fine settimana è...', pt: 'Você termina uma semana exaustiva. Seu plano ideal para o fim de semana é...' }, options: [
      { text: { es: 'Adelantar lo de la semana siguiente para empezar más tranquilo/a.', en: 'Getting ahead on next week\'s work to start more calmly.', fr: 'Avancer sur la semaine suivante pour commencer plus calmement.', de: 'Die Arbeit der nächsten Woche voraus erledigen, um ruhiger anzufangen.', it: 'Anticipare il lavoro della settimana seguente per iniziare più tranquillo/a.', pt: 'Adiantar o da semana seguinte para começar mais tranquilo/a.' }, dimension: 'W' },
      { text: { es: 'Hacer algo que realmente disfruto, aunque sea relacionado con mi campo.', en: 'Do something I really enjoy, even if related to my field.', fr: 'Faire quelque chose que j\'apprécie vraiment, même si c\'est lié à mon domaine.', de: 'Etwas tun, das ich wirklich genieße, auch wenn es mit meinem Bereich zusammenhängt.', it: 'Fare qualcosa che apprezzo davvero, anche se correlato al mio campo.', pt: 'Fazer algo que realmente curto, mesmo que relacionado à minha área.' }, dimension: 'D' },
      { text: { es: 'Nada de trabajo. Tiempo con personas que quiero.', en: 'No work at all. Time with people I love.', fr: 'Pas de travail. Du temps avec des personnes que j\'aime.', de: 'Überhaupt keine Arbeit. Zeit mit Menschen, die ich liebe.', it: 'Niente lavoro. Tempo con le persone che amo.', pt: 'Nada de trabalho. Tempo com pessoas que amo.' }, dimension: 'E' },
      { text: { es: 'Primero recargo con descanso real. Después evaluaré si hay algo urgente.', en: 'First recharge with real rest. Then I\'ll evaluate if there\'s anything urgent.', fr: 'D\'abord je me recharge avec du vrai repos. Ensuite j\'évaluerai s\'il y a quelque chose d\'urgent.', de: 'Zuerst mit echter Ruhe aufladen. Dann werde ich bewerten, ob es etwas Dringendes gibt.', it: 'Prima ricarico con vero riposo. Dopo valuterò se c\'è qualcosa di urgente.', pt: 'Primeiro recarrego com descanso real. Depois avaliarei se há algo urgente.' }, dimension: 'R' },
    ] },
    { id: 6, situation: { es: '¿Cómo describirías tu relación con la productividad?', en: 'How would you describe your relationship with productivity?', fr: 'Comment décrirais-tu ta relation avec la productivité ?', de: 'Wie würdest du deine Beziehung zur Produktivität beschreiben?', it: 'Come descriveresti la tua relazione con la produttività?', pt: 'Como você descreveria sua relação com a produtividade?' }, options: [
      { text: { es: 'Es mi métrica principal de un día bien vivido.', en: 'It\'s my main metric for a day well lived.', fr: 'C\'est ma principale métrique d\'une journée bien vécue.', de: 'Es ist mein wichtigster Maßstab für einen gut gelebten Tag.', it: 'È la mia metrica principale di una giornata ben vissuta.', pt: 'É minha métrica principal de um dia bem vivido.' }, dimension: 'W' },
      { text: { es: 'La productividad me importa cuando está al servicio de algo que me apasiona.', en: 'Productivity matters to me when it\'s in service of something I\'m passionate about.', fr: 'La productivité m\'importe quand elle est au service de quelque chose qui me passionne.', de: 'Produktivität ist mir wichtig, wenn sie im Dienst von etwas steht, das mich begeistert.', it: 'La produttività mi importa quando è al servizio di qualcosa che mi appassiona.', pt: 'A produtividade me importa quando está a serviço de algo que me apaixona.' }, dimension: 'D' },
      { text: { es: 'Importante, pero no la única métrica. El bienestar también cuenta.', en: 'Important, but not the only metric. Wellbeing counts too.', fr: 'Important, mais pas la seule métrique. Le bien-être compte aussi.', de: 'Wichtig, aber nicht die einzige Metrik. Auch das Wohlbefinden zählt.', it: 'Importante, ma non l\'unica metrica. Anche il benessere conta.', pt: 'Importante, mas não a única métrica. O bem-estar também conta.' }, dimension: 'E' },
      { text: { es: 'Trato de que la productividad sirva a mi energía, no al revés.', en: 'I try to make productivity serve my energy, not the other way around.', fr: 'J\'essaie que la productivité serve mon énergie, pas l\'inverse.', de: 'Ich versuche, dass Produktivität meiner Energie dient, nicht umgekehrt.', it: 'Cerco che la produttività serva alla mia energia, non il contrario.', pt: 'Tento que a produtividade sirva à minha energia, não ao contrário.' }, dimension: 'R' },
    ] },
    { id: 7, situation: { es: 'Si te dijeran que tienes que tomar un mes de descanso obligatorio, ¿cómo te sentirías?', en: 'If you were told you have to take a mandatory month of rest, how would you feel?', fr: 'Si on te disait que tu dois prendre un mois de repos obligatoire, comment te sentirais-tu ?', de: 'Wenn man dir sagen würde, dass du einen obligatorischen Monat Ruhe nehmen musst, wie würdest du dich fühlen?', it: 'Se ti dicessero che devi prendere un mese di riposo obbligatorio, come ti sentiresti?', pt: 'Se te dissessem que você tem que tirar um mês de descanso obrigatório, como você se sentiria?' }, options: [
      { text: { es: 'Muy ansioso/a. Un mes sin trabajar me parece una eternidad amenazante.', en: 'Very anxious. A month without working seems like a threatening eternity to me.', fr: 'Très anxieux/se. Un mois sans travailler me semble une éternité menaçante.', de: 'Sehr ängstlich. Ein Monat ohne Arbeit erscheint mir wie eine bedrohliche Ewigkeit.', it: 'Molto ansioso/a. Un mese senza lavorare mi sembra un\'eternità minacciosa.', pt: 'Muito ansioso/a. Um mês sem trabalhar me parece uma eternidade ameaçadora.' }, dimension: 'W' },
      { text: { es: 'Depende del momento. A veces lo necesito; a veces lo odiaría.', en: 'Depends on the moment. Sometimes I need it; sometimes I\'d hate it.', fr: 'Ça dépend du moment. Parfois j\'en ai besoin ; parfois je le détesterais.', de: 'Hängt vom Moment ab. Manchmal brauche ich es; manchmal würde ich es hassen.', it: 'Dipende dal momento. A volte ne ho bisogno; a volte lo odierei.', pt: 'Depende do momento. Às vezes preciso; às vezes odiaria.' }, dimension: 'D' },
      { text: { es: 'Bien. Lo aprovecharía para hacer las cosas que pospongo por el trabajo.', en: 'Fine. I\'d use it to do the things I postpone because of work.', fr: 'Bien. J\'en profiterais pour faire les choses que je reporte à cause du travail.', de: 'Gut. Ich würde es nutzen, um die Dinge zu tun, die ich wegen der Arbeit aufschiebe.', it: 'Bene. Lo userei per fare le cose che rimando a causa del lavoro.', pt: 'Bem. Aproveitaria para fazer as coisas que adio por causa do trabalho.' }, dimension: 'E' },
      { text: { es: 'Bien, si me lo propongo con intención. El descanso activo es recuperación.', en: 'Fine, if I approach it with intention. Active rest is recovery.', fr: 'Bien, si je me le propose avec intention. Le repos actif est de la récupération.', de: 'Gut, wenn ich es mit Absicht angehe. Aktive Ruhe ist Erholung.', it: 'Bene, se me lo propongo con intenzione. Il riposo attivo è recupero.', pt: 'Bem, se me proponho com intenção. O descanso ativo é recuperação.' }, dimension: 'R' },
    ] },
    { id: 8, situation: { es: '¿Tu identidad está fuertemente ligada a tu trabajo?', en: 'Is your identity strongly tied to your work?', fr: 'Ton identité est-elle fortement liée à ton travail ?', de: 'Ist deine Identität stark mit deiner Arbeit verbunden?', it: 'La tua identità è fortemente legata al tuo lavoro?', pt: 'Sua identidade está fortemente ligada ao seu trabalho?' }, options: [
      { text: { es: 'Sí. Lo que hago es central a quien soy.', en: 'Yes. What I do is central to who I am.', fr: 'Oui. Ce que je fais est central à qui je suis.', de: 'Ja. Was ich tue, ist zentral für das, wer ich bin.', it: 'Sì. Quello che faccio è centrale per chi sono.', pt: 'Sim. O que faço é central para quem sou.' }, dimension: 'W' },
      { text: { es: 'Es parte importante de quien soy, pero no todo.', en: 'It\'s an important part of who I am, but not everything.', fr: 'C\'est une partie importante de qui je suis, mais pas tout.', de: 'Es ist ein wichtiger Teil davon, wer ich bin, aber nicht alles.', it: 'È parte importante di chi sono, ma non tutto.', pt: 'É parte importante de quem sou, mas não tudo.' }, dimension: 'D' },
      { text: { es: 'Intento que no. Soy más que mi trabajo.', en: 'I try not to let it be. I\'m more than my work.', fr: 'J\'essaie que non. Je suis plus que mon travail.', de: 'Ich versuche es nicht zu sein. Ich bin mehr als meine Arbeit.', it: 'Cerco che no. Sono più del mio lavoro.', pt: 'Tento que não. Sou mais do que meu trabalho.' }, dimension: 'E' },
      { text: { es: 'No debería serlo. Trabajo para vivir, no al revés.', en: 'It shouldn\'t be. I work to live, not the other way around.', fr: 'Ça ne devrait pas l\'être. Je travaille pour vivre, pas l\'inverse.', de: 'Es sollte es nicht sein. Ich arbeite, um zu leben, nicht umgekehrt.', it: 'Non dovrebbe esserlo. Lavoro per vivere, non al contrario.', pt: 'Não deveria ser. Trabalho para viver, não ao contrário.' }, dimension: 'R' },
    ] },
    { id: 9, situation: { es: '¿Cuánto del trabajo que haces está impulsado por miedo (a fallar, quedarte atrás, no ser suficiente)?', en: 'How much of the work you do is driven by fear (of failing, falling behind, not being enough)?', fr: 'Quelle part du travail que tu fais est motivée par la peur (d\'échouer, de prendre du retard, de ne pas être suffisant) ?', de: 'Wie viel von der Arbeit, die du tust, wird von Angst angetrieben (zu scheitern, zurückzubleiben, nicht genug zu sein)?', it: 'Quanta parte del lavoro che fai è spinta dalla paura (di fallire, restare indietro, non essere abbastanza)?', pt: 'Quanto do trabalho que você faz é impulsionado pelo medo (de falhar, ficar para trás, não ser suficiente)?' }, options: [
      { text: { es: 'Más de lo que me gustaría admitir.', en: 'More than I\'d like to admit.', fr: 'Plus que je ne voudrais l\'admettre.', de: 'Mehr, als ich zugeben möchte.', it: 'Più di quanto mi piacerebbe ammettere.', pt: 'Mais do que gostaria de admitir.' }, dimension: 'W' },
      { text: { es: 'Algo, pero la mayor parte es genuino interés o propósito.', en: 'Some, but most of it is genuine interest or purpose.', fr: 'Un peu, mais la plupart est un intérêt genuins ou un but.', de: 'Etwas, aber das meiste ist echtes Interesse oder Zweck.', it: 'Qualcosa, ma la maggior parte è genuino interesse o scopo.', pt: 'Algo, mas a maior parte é genuíno interesse ou propósito.' }, dimension: 'D' },
      { text: { es: 'Poco. Trabajo desde la motivación más que desde el miedo.', en: 'Little. I work from motivation rather than fear.', fr: 'Peu. Je travaille à partir de la motivation plutôt que de la peur.', de: 'Wenig. Ich arbeite aus Motivation heraus, nicht aus Angst.', it: 'Poco. Lavoro dalla motivazione più che dalla paura.', pt: 'Pouco. Trabalho mais pela motivação do que pelo medo.' }, dimension: 'E' },
      { text: { es: 'Lo he trabajado activamente. Antes era más miedo; ahora más elección.', en: 'I\'ve actively worked on it. Before it was more fear; now more choice.', fr: 'Je l\'ai activement travaillé. Avant c\'était plus de la peur ; maintenant c\'est plus un choix.', de: 'Ich habe aktiv daran gearbeitet. Früher war es mehr Angst; jetzt mehr Wahl.', it: 'L\'ho lavorato attivamente. Prima era più paura; ora più scelta.', pt: 'Trabalhei ativamente nisso. Antes era mais medo; agora mais escolha.' }, dimension: 'R' },
    ] },
    { id: 10, situation: { es: 'Si el trabajo no existiera (o si el dinero no fuera necesario), ¿qué harías?', en: 'If work didn\'t exist (or if money wasn\'t necessary), what would you do?', fr: 'Si le travail n\'existait pas (ou si l\'argent n\'était pas nécessaire), que ferais-tu ?', de: 'Wenn Arbeit nicht existieren würde (oder wenn Geld nicht notwendig wäre), was würdest du tun?', it: 'Se il lavoro non esistesse (o se il denaro non fosse necessario), cosa faresti?', pt: 'Se o trabalho não existisse (ou se o dinheiro não fosse necessário), o que você faria?' }, options: [
      { text: { es: 'Probablemente algo muy parecido. No sabría qué hacer sin proyectos.', en: 'Probably something very similar. I wouldn\'t know what to do without projects.', fr: 'Probablement quelque chose de très similaire. Je ne saurais pas quoi faire sans projets.', de: 'Wahrscheinlich etwas sehr Ähnliches. Ich würde nicht wissen, was ich ohne Projekte tun soll.', it: 'Probabilmente qualcosa di molto simile. Non saprei cosa fare senza progetti.', pt: 'Provavelmente algo muito parecido. Não saberia o que fazer sem projetos.' }, dimension: 'W' },
      { text: { es: 'Lo mismo, pero con más libertad para elegir exactamente qué y cómo.', en: 'The same, but with more freedom to choose exactly what and how.', fr: 'La même chose, mais avec plus de liberté pour choisir exactement quoi et comment.', de: 'Dasselbe, aber mit mehr Freiheit, genau zu wählen, was und wie.', it: 'La stessa cosa, ma con più libertà di scegliere esattamente cosa e come.', pt: 'O mesmo, mas com mais liberdade para escolher exatamente o quê e como.' }, dimension: 'D' },
      { text: { es: 'Muchas cosas que el trabajo me quita tiempo de hacer.', en: 'Many things that work takes time away from doing.', fr: 'Beaucoup de choses que le travail m\'empêche de faire.', de: 'Viele Dinge, für die die Arbeit Zeit wegnimmt.', it: 'Molte cose che il lavoro mi toglie il tempo di fare.', pt: 'Muitas coisas que o trabalho me tira tempo de fazer.' }, dimension: 'E' },
      { text: { es: 'Combinación de descanso, exploración y proyectos que me apasionen sin presión.', en: 'A combination of rest, exploration, and projects I\'m passionate about without pressure.', fr: 'Une combinaison de repos, d\'exploration et de projets qui me passionnent sans pression.', de: 'Eine Kombination aus Ruhe, Erkundung und Projekten, die mich ohne Druck begeistern.', it: 'Combinazione di riposo, esplorazione e progetti che mi appassionano senza pressione.', pt: 'Combinação de descanso, exploração e projetos que me apaixonam sem pressão.' }, dimension: 'R' },
    ] },
  ],
  characters: [
    { name: { es: 'El Workaholic Puro', en: 'The Pure Workaholic', fr: 'Le Workaholic Pur', de: 'Der Reine Workaholic', it: 'Il Workaholic Puro', pt: 'O Workaholic Puro' }, dimensions: ['W'], photo: '/characters/workaholic.jpg', description: { es: 'El trabajo es identidad, refugio y propósito. Todo a la vez.', en: 'Work is identity, refuge, and purpose. All at once.', fr: 'Le travail est identité, refuge et but. Tout à la fois.', de: 'Arbeit ist Identität, Zuflucht und Zweck. Alles auf einmal.', it: 'Il lavoro è identità, rifugio e scopo. Tutto allo stesso tempo.', pt: 'O trabalho é identidade, refúgio e propósito. Tudo ao mesmo tempo.' }, philosophy: { es: 'El trabajo no es lo que haces — es lo que eres. No es ambición ni dedicación — es que el trabajo se convirtió en el lugar más seguro del mundo. Más cómodo que las relaciones, más manejable que el descanso.', en: 'Work isn\'t what you do — it\'s what you are. It\'s not ambition or dedication — it\'s that work became the safest place in the world. More comfortable than relationships, more manageable than rest.', fr: 'Le travail n\'est pas ce que tu fais — c\'est ce que tu es. Ce n\'est pas de l\'ambition ni de la dédicace — c\'est que le travail est devenu le lieu le plus sûr du monde. Plus confortable que les relations, plus gérable que le repos.', de: 'Arbeit ist nicht das, was du tust — es ist das, was du bist. Es ist keine Ambition oder Hingabe — es ist, dass die Arbeit zum sichersten Ort der Welt geworden ist. Bequemer als Beziehungen, handhabbarer als Ruhe.', it: 'Il lavoro non è quello che fai — è quello che sei. Non è ambizione né dedizione — è che il lavoro è diventato il posto più sicuro del mondo. Più comodo delle relazioni, più gestibile del riposo.', pt: 'O trabalho não é o que você faz — é o que você é. Não é ambição nem dedicação — é que o trabalho se tornou o lugar mais seguro do mundo. Mais confortável do que os relacionamentos, mais gerenciável do que o descanso.' } },
    { name: { es: 'El Apasionado Dedicado', en: 'The Dedicated Passionate', fr: 'Le Passionné Dédicacé', de: 'Der Leidenschaftliche Engagierte', it: 'Il Passionato Dedicato', pt: 'O Apaixonado Dedicado' }, dimensions: ['D'], photo: '/characters/dedicated-passionate.jpg', description: { es: 'Trabaja mucho porque lo que hace le importa, no por ansiedad.', en: 'Works a lot because what they do matters, not out of anxiety.', fr: 'Travaille beaucoup parce que ce qu\'il/elle fait lui importe, pas par anxiété.', de: 'Arbeitet viel, weil das, was er/sie tut, wichtig ist, nicht aus Angst.', it: 'Lavora tanto perché quello che fa gli importa, non per ansia.', pt: 'Trabalha muito porque o que faz importa, não por ansiedade.' }, philosophy: { es: 'Trabajas intensamente porque lo que haces te mueve genuinamente. Eso no es adicción — es compromiso. La diferencia: podrías parar si quisieras. No quieres porque te importa.', en: 'You work intensely because what you do genuinely moves you. That\'s not addiction — it\'s commitment. The difference: you could stop if you wanted. You don\'t want to because it matters.', fr: 'Tu travailles intensément parce que ce que tu fais te touche genuinement. Ce n\'est pas de l\'addiction — c\'est de l\'engagement. La différence : tu pourrais t\'arrêter si tu le voulais. Tu ne veux pas parce que ça t\'importe.', de: 'Du arbeitest intensiv, weil das, was du tust, dich wirklich bewegt. Das ist keine Sucht — es ist Engagement. Der Unterschied: Du könntest aufhören, wenn du wolltest. Du willst es nicht, weil es dir wichtig ist.', it: 'Lavori intensamente perché quello che fai ti muove genuinamente. Non è dipendenza — è impegno. La differenza: potresti smettere se volessi. Non vuoi perché ti importa.', pt: 'Você trabalha intensamente porque o que faz genuinamente te move. Isso não é dependência — é comprometimento. A diferença: você poderia parar se quisesse. Não quer porque importa.' } },
    { name: { es: 'El Equilibrado Consciente', en: 'The Conscious Balanced', fr: 'L\'Équilibré Conscient', de: 'Der Bewusste Ausgeglichene', it: 'L\'Equilibrato Consapevole', pt: 'O Equilibrado Consciente' }, dimensions: ['E'], photo: '/characters/balanced-worker.jpg', description: { es: 'Sabe separar. El trabajo tiene sus horas; el resto de la vida también.', en: 'Knows how to separate. Work has its hours; the rest of life does too.', fr: 'Sait séparer. Le travail a ses heures ; le reste de la vie aussi.', de: 'Weiß, wie man trennt. Arbeit hat ihre Stunden; der Rest des Lebens auch.', it: 'Sa separare. Il lavoro ha le sue ore; il resto della vita anche.', pt: 'Sabe separar. O trabalho tem suas horas; o resto da vida também.' }, philosophy: { es: 'Has construido límites reales entre el trabajo y el resto de tu vida. No siempre fue fácil, pero es una de las decisiones más importantes que has tomado. Tu presencia fuera del trabajo es completa.', en: 'You\'ve built real boundaries between work and the rest of your life. It wasn\'t always easy, but it\'s one of the most important decisions you\'ve made. Your presence outside of work is complete.', fr: 'Tu as construit de vraies limites entre le travail et le reste de ta vie. Ce n\'était pas toujours facile, mais c\'est l\'une des décisions les plus importantes que tu aies prises. Ta présence en dehors du travail est complète.', de: 'Du hast echte Grenzen zwischen der Arbeit und dem Rest deines Lebens aufgebaut. Es war nicht immer einfach, aber es ist eine der wichtigsten Entscheidungen, die du getroffen hast. Deine Präsenz außerhalb der Arbeit ist vollständig.', it: 'Hai costruito veri confini tra il lavoro e il resto della tua vita. Non è sempre stato facile, ma è una delle decisioni più importanti che tu abbia preso. La tua presenza fuori dal lavoro è completa.', pt: 'Você construiu limites reais entre o trabalho e o resto da sua vida. Nem sempre foi fácil, mas é uma das decisões mais importantes que você tomou. Sua presença fora do trabalho é completa.' } },
    { name: { es: 'El Recuperador Activo', en: 'The Active Recoverer', fr: 'Le Récupérateur Actif', de: 'Der Aktive Erhol', it: 'Il Recuperatore Attivo', pt: 'O Recuperador Ativo' }, dimensions: ['R'], photo: '/characters/active-recoverer.jpg', description: { es: 'Trabaja intensamente pero sabe recuperarse igual de intensamente.', en: 'Works intensely but knows how to recover just as intensely.', fr: 'Travaille intensément mais sait se récupérer tout aussi intensément.', de: 'Arbeitet intensiv, weiß aber, wie er/sie sich genauso intensiv erholt.', it: 'Lavora intensamente ma sa recuperare altrettanto intensamente.', pt: 'Trabalha intensamente mas sabe se recuperar igualmente intensamente.' }, philosophy: { es: 'Para ti, el descanso no es la ausencia de trabajo — es parte del sistema. Sabes que tu mejor rendimiento laboral depende de una recuperación real. No descansas por guilt — descansas por estrategia.', en: 'For you, rest is not the absence of work — it\'s part of the system. You know your best work performance depends on real recovery. You don\'t rest out of guilt — you rest by strategy.', fr: 'Pour toi, le repos n\'est pas l\'absence de travail — c\'est une partie du système. Tu sais que ta meilleure performance au travail dépend d\'une récupération réelle. Tu ne te reposes pas par culpabilité — tu te reposes par stratégie.', de: 'Für dich ist Ruhe nicht die Abwesenheit von Arbeit — es ist Teil des Systems. Du weißt, dass deine beste Arbeitsleistung von echter Erholung abhängt. Du ruhst dich nicht aus Schuldgefühlen aus — du ruhst dich strategisch aus.', it: 'Per te, il riposo non è l\'assenza di lavoro — è parte del sistema. Sai che il tuo miglior rendimento lavorativo dipende da un recupero reale. Non ti riposi per colpa — ti riposi per strategia.', pt: 'Para você, o descanso não é a ausência de trabalho — é parte do sistema. Você sabe que seu melhor desempenho laboral depende de uma recuperação real. Você não descansa por culpa — descansa por estratégia.' } },
    { name: { es: 'El Ansioso Productivo', en: 'The Anxious Productive', fr: 'L\'Anxieux Productif', de: 'Der Ängstliche Produktive', it: 'L\'Ansioso Produttivo', pt: 'O Ansioso Produtivo' }, dimensions: ['W', 'D'], photo: '/characters/anxious-productive.jpg', description: { es: 'Apasionado pero también ansioso. La línea entre los dos es borrosa.', en: 'Passionate but also anxious. The line between the two is blurry.', fr: 'Passionné mais aussi anxieux. La ligne entre les deux est floue.', de: 'Leidenschaftlich, aber auch ängstlich. Die Grenze zwischen beiden ist verschwommen.', it: 'Appassionato ma anche ansioso. La linea tra i due è sfumata.', pt: 'Apaixonado mas também ansioso. A linha entre os dois é turva.' }, philosophy: { es: 'Genuinamente amas lo que haces, pero el trabajo también llena un hueco que no es solo pasión. La mezcla es potente y confusa. ¿Cuándo trabajas porque quieres y cuándo porque no puedes parar?', en: 'You genuinely love what you do, but work also fills a gap that isn\'t just passion. The mix is powerful and confusing. When do you work because you want to and when because you can\'t stop?', fr: 'Tu aimes genuinement ce que tu fais, mais le travail remplit aussi un vide qui n\'est pas seulement de la passion. Le mélange est puissant et confus. Quand travailles-tu parce que tu le veux et quand parce que tu ne peux pas t\'arrêter ?', de: 'Du liebst wirklich, was du tust, aber Arbeit füllt auch eine Lücke, die nicht nur Leidenschaft ist. Die Mischung ist mächtig und verwirrend. Wann arbeitest du, weil du es willst, und wann, weil du nicht aufhören kannst?', it: 'Ami genuinamente quello che fai, ma il lavoro riempie anche un vuoto che non è solo passione. La miscela è potente e confusa. Quando lavori perché vuoi e quando perché non riesci a fermarti?', pt: 'Você genuinamente ama o que faz, mas o trabalho também preenche um vazio que não é só paixão. A mistura é potente e confusa. Quando você trabalha porque quer e quando porque não consegue parar?' } },
    { name: { es: 'El Burnout Potencial', en: 'The Potential Burnout', fr: 'Le Burnout Potentiel', de: 'Der Potenzielle Burnout', it: 'Il Burnout Potenziale', pt: 'O Burnout Potencial' }, dimensions: ['W', 'E'], photo: '/characters/burnout-risk.jpg', description: { es: 'Sabe que debería equilibrar pero no puede parar.', en: 'Knows they should balance but can\'t stop.', fr: 'Sait qu\'il/elle devrait équilibrer mais ne peut pas s\'arrêter.', de: 'Weiß, dass er/sie ausgleichen sollte, kann aber nicht aufhören.', it: 'Sa che dovrebbe equilibrare ma non riesce a fermarsi.', pt: 'Sabe que deveria equilibrar mas não consegue parar.' }, philosophy: { es: 'Sabes en teoría que necesitas más equilibrio. En práctica, el trabajo siempre encuentra la forma de entrar en los espacios que deberían ser de otra cosa. Esa brecha entre lo que sabes y lo que haces tiene un costo real.', en: 'You know in theory you need more balance. In practice, work always finds a way to enter the spaces that should be for something else. That gap between what you know and what you do has a real cost.', fr: 'Tu sais en théorie que tu as besoin de plus d\'équilibre. En pratique, le travail trouve toujours un moyen d\'entrer dans les espaces qui devraient être pour autre chose. Cet écart entre ce que tu sais et ce que tu fais a un coût réel.', de: 'Du weißt in der Theorie, dass du mehr Balance brauchst. In der Praxis findet die Arbeit immer einen Weg, in die Räume einzudringen, die für etwas anderes sein sollten. Diese Lücke zwischen dem, was du weißt, und dem, was du tust, hat einen echten Preis.', it: 'Sai in teoria che hai bisogno di più equilibrio. In pratica, il lavoro trova sempre il modo di entrare negli spazi che dovrebbero essere di altro. Quel divario tra quello che sai e quello che fai ha un costo reale.', pt: 'Você sabe em teoria que precisa de mais equilíbrio. Na prática, o trabalho sempre encontra a forma de entrar nos espaços que deveriam ser de outra coisa. Essa lacuna entre o que você sabe e o que faz tem um custo real.' } },
    { name: { es: 'El Profesional Sostenible', en: 'The Sustainable Professional', fr: 'Le Professionnel Durable', de: 'Der Nachhaltige Profi', it: 'Il Professionista Sostenibile', pt: 'O Profissional Sustentável' }, dimensions: ['D', 'R'], photo: '/characters/sustainable-professional.jpg', description: { es: 'Comprometido y con ciclos de recuperación reales.', en: 'Committed and with real recovery cycles.', fr: 'Engagé et avec de vrais cycles de récupération.', de: 'Engagiert und mit echten Erholungszyklen.', it: 'Impegnato e con cicli di recupero reali.', pt: 'Comprometido e com ciclos de recuperação reais.' }, philosophy: { es: 'Has encontrado el ritmo que te permite ser intensamente dedicado/a y también recuperarte de verdad. No es fácil — requiere disciplina en ambas direcciones. Pero es el único modelo que dura a largo plazo.', en: 'You\'ve found the rhythm that allows you to be intensely dedicated and also truly recover. It\'s not easy — it requires discipline in both directions. But it\'s the only model that lasts in the long run.', fr: 'Tu as trouvé le rythme qui te permet d\'être intensément dédicacé(e) et aussi de vraiment récupérer. Ce n\'est pas facile — ça requiert de la discipline dans les deux directions. Mais c\'est le seul modèle qui dure à long terme.', de: 'Du hast den Rhythmus gefunden, der es dir ermöglicht, intensiv engagiert zu sein und dich auch wirklich zu erholen. Es ist nicht einfach — es erfordert Disziplin in beide Richtungen. Aber es ist das einzige Modell, das langfristig anhält.', it: 'Hai trovato il ritmo che ti permette di essere intensamente dedicato/a e anche recuperare davvero. Non è facile — richiede disciplina in entrambe le direzioni. Ma è l\'unico modello che dura a lungo termine.', pt: 'Você encontrou o ritmo que permite ser intensamente dedicado/a e também se recuperar de verdade. Não é fácil — requer disciplina em ambas as direções. Mas é o único modelo que dura a longo prazo.' } },
    { name: { es: 'El Integrado Pleno', en: 'The Fully Integrated', fr: 'L\'Intégré Complet', de: 'Der Vollständig Integrierte', it: 'L\'Integrato Pieno', pt: 'O Integrado Pleno' }, dimensions: ['E', 'R'], photo: '/characters/integrated-full.jpg', description: { es: 'Trabaja para vivir y vive bien fuera del trabajo.', en: 'Works to live and lives well outside of work.', fr: 'Travaille pour vivre et vit bien en dehors du travail.', de: 'Arbeitet, um zu leben und lebt gut außerhalb der Arbeit.', it: 'Lavora per vivere e vive bene fuori dal lavoro.', pt: 'Trabalha para viver e vive bem fora do trabalho.' }, philosophy: { es: 'El trabajo tiene su lugar en tu vida, no toda tu vida. Recuperarte no es un lujo — es una práctica activa. Esa decisión te permite estar completamente presente en cada contexto, incluyendo el profesional.', en: 'Work has its place in your life, not all your life. Recovering isn\'t a luxury — it\'s an active practice. That decision allows you to be completely present in every context, including the professional one.', fr: 'Le travail a sa place dans ta vie, pas toute ta vie. Se récupérer n\'est pas un luxe — c\'est une pratique active. Cette décision te permet d\'être complètement présent(e) dans chaque contexte, y compris le professionnel.', de: 'Arbeit hat ihren Platz in deinem Leben, nicht dein ganzes Leben. Sich zu erholen ist kein Luxus — es ist eine aktive Praxis. Diese Entscheidung ermöglicht es dir, in jedem Kontext vollständig präsent zu sein, einschließlich des professionellen.', it: 'Il lavoro ha il suo posto nella tua vita, non tutta la tua vita. Recuperarti non è un lusso — è una pratica attiva. Quella decisione ti permette di essere completamente presente in ogni contesto, incluso quello professionale.', pt: 'O trabalho tem seu lugar na sua vida, não toda a sua vida. Recuperar-se não é um luxo — é uma prática ativa. Essa decisão permite que você esteja completamente presente em cada contexto, incluindo o profissional.' } },
  ],
};

export async function seedWorkaholic(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'workaholic' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'workaholic',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['lifestyle'],
      sortOrder: 2,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
