import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan envidioso/a eres?', en: 'How envious are you?', fr: 'À quel point es-tu envieux/se ?', de: 'Wie neidisch bist du?', it: 'Quanto sei invidioso/a?', pt: 'O quanto você é invejoso/a?' },
  description: { es: 'La envidia es el reconocimiento de que alguien tiene algo que tú quieres. ¿La tuya te destruye o te motiva?', en: 'Envy is the recognition that someone has something you want. Does yours destroy you or motivate you?', fr: 'L\'envie est la reconnaissance que quelqu\'un a quelque chose que tu veux. La tienne te détruit-elle ou te motive-t-elle ?', de: 'Neid ist die Erkenntnis, dass jemand etwas hat, das du willst. Zerstört deiner dich oder motiviert er dich?', it: 'L\'invidia è il riconoscimento che qualcuno ha qualcosa che vuoi. La tua ti distrugge o ti motiva?', pt: 'A inveja é o reconhecimento de que alguém tem algo que você quer. A sua te destrói ou te motiva?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { E: 'Envidia Activa', P: 'Proyección', A: 'Admiración', M: 'Motivación' },
    en: { E: 'Active Envy', P: 'Projection', A: 'Admiration', M: 'Motivation' },
    fr: { E: 'Envie Active', P: 'Projection', A: 'Admiration', M: 'Motivation' },
    de: { E: 'Aktiver Neid', P: 'Projektion', A: 'Bewunderung', M: 'Motivation' },
    it: { E: 'Invidia Attiva', P: 'Proiezione', A: 'Ammirazione', M: 'Motivazione' },
    pt: { E: 'Inveja Ativa', P: 'Projeção', A: 'Admiração', M: 'Motivação' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu amigo/a del alma consigue el trabajo de sus sueños. Tú llevas meses buscando empleo.', en: 'Your best friend gets their dream job. You\'ve been job hunting for months.', fr: 'Ton/ta meilleur(e) ami(e) décroche le travail de ses rêves. Tu cherches un emploi depuis des mois.', de: 'Dein bester Freund/deine beste Freundin bekommt seinen/ihren Traumjob. Du suchst seit Monaten Arbeit.', it: 'Il tuo migliore amico/a ottiene il lavoro dei sogni. Tu stai cercando lavoro da mesi.', pt: 'Seu melhor amigo/a consegue o emprego dos sonhos. Você procura emprego há meses.' }, options: [
      { text: { es: 'Me alegro por fuera pero por dentro quisiera que no lo hubiera conseguido tan fácil.', en: 'I\'m happy outwardly but inside I wish they hadn\'t gotten it so easily.', fr: 'Je me réjouis en apparence mais intérieurement je voudrais qu\'il/elle ne l\'ait pas obtenu si facilement.', de: 'Äußerlich freue ich mich, aber innerlich wünschte ich, sie hätten es nicht so leicht bekommen.', it: 'Sono felice all\'esterno ma dentro vorrei che non l\'avesse ottenuto così facilmente.', pt: 'Fico feliz por fora mas por dentro queria que não tivesse conseguido tão facilmente.' }, dimension: 'E' },
      { text: { es: 'Empiezo a notar defectos en ese trabajo que antes no veía. ¿Realmente es tan bueno?', en: 'I start noticing flaws in that job I didn\'t see before. Is it really that good?', fr: 'Je commence à remarquer des défauts dans ce travail que je ne voyais pas avant. Est-il vraiment si bien ?', de: 'Ich fange an, Fehler in diesem Job zu bemerken, die ich vorher nicht gesehen habe. Ist es wirklich so gut?', it: 'Comincio a notare difetti in quel lavoro che prima non vedevo. È davvero così buono?', pt: 'Começo a notar defeitos naquele emprego que antes não via. Será que é tão bom assim?' }, dimension: 'P' },
      { text: { es: 'Me alegro genuinamente. Su éxito me demuestra que es posible.', en: 'I\'m genuinely happy for them. Their success shows me it\'s possible.', fr: 'Je suis genuinement content(e). Leur succès me montre que c\'est possible.', de: 'Ich freue mich aufrichtig. Ihr Erfolg zeigt mir, dass es möglich ist.', it: 'Sono genuinamente felice. Il loro successo mi dimostra che è possibile.', pt: 'Fico genuinamente feliz. O sucesso dele/dela me prova que é possível.' }, dimension: 'A' },
      { text: { es: 'Me usa como combustible. Si él/ella pudo, yo también. Me pongo en modo intenso.', en: 'I use it as fuel. If they could do it, so can I. I go into intense mode.', fr: 'Je l\'utilise comme carburant. S\'il/elle a pu, moi aussi. Je passe en mode intensif.', de: 'Ich nutze es als Treibstoff. Wenn er/sie es konnte, kann ich es auch. Ich gehe in den intensiven Modus.', it: 'Lo uso come carburante. Se lui/lei ce l\'ha fatta, posso farcela anch\'io. Vado in modalità intensa.', pt: 'Uso como combustível. Se ele/ela conseguiu, eu também consigo. Entro no modo intenso.' }, dimension: 'M' },
    ] },
    { id: 2, situation: { es: 'Un compañero de trabajo que no considerabas muy capaz asciende antes que tú.', en: 'A coworker you didn\'t consider very capable gets promoted before you.', fr: 'Un collègue que tu ne considérais pas très compétent est promu avant toi.', de: 'Ein Kollege, den du nicht für sehr fähig hieltest, wird vor dir befördert.', it: 'Un collega che non consideravi molto capace viene promosso prima di te.', pt: 'Um colega de trabalho que você não considerava muito capaz é promovido antes de você.' }, options: [
      { text: { es: 'Me consume el pensamiento de que fue injusto. Lo replayo en mi cabeza por días.', en: 'The thought that it was unfair consumes me. I replay it in my head for days.', fr: 'La pensée que c\'était injuste me consume. Je le rejoue dans ma tête pendant des jours.', de: 'Der Gedanke, dass es ungerecht war, verzehrt mich. Ich spule es tagelang in meinem Kopf ab.', it: 'Il pensiero che fosse ingiusto mi consuma. Lo riprendo in testa per giorni.', pt: 'O pensamento de que foi injusto me consome. Fico repetindo na cabeça por dias.' }, dimension: 'E' },
      { text: { es: 'Concluyo que fue por políticas de oficina, no por mérito real.', en: 'I conclude it was office politics, not real merit.', fr: 'Je conclus que c\'était de la politique de bureau, pas du mérite réel.', de: 'Ich komme zu dem Schluss, dass es Büropolitik war, kein echter Verdienst.', it: 'Concludo che è stata politica d\'ufficio, non merito reale.', pt: 'Concluo que foi política de escritório, não mérito real.' }, dimension: 'P' },
      { text: { es: 'Lo felicito y le pregunto qué hizo diferente.', en: 'I congratulate them and ask what they did differently.', fr: 'Je le/la félicite et lui demande ce qu\'il/elle a fait différemment.', de: 'Ich gratuliere ihm/ihr und frage, was er/sie anders gemacht hat.', it: 'Lo congratulo e gli chiedo cosa ha fatto di diverso.', pt: 'Parabenizo e pergunto o que fez diferente.' }, dimension: 'A' },
      { text: { es: 'Lo tomo como señal de que necesito ser más visible. Me activo.', en: 'I take it as a sign I need to be more visible. I get activated.', fr: 'Je le prends comme un signe que je dois être plus visible. Je m\'active.', de: 'Ich nehme es als Zeichen, dass ich sichtbarer sein muss. Ich werde aktiv.', it: 'Lo prendo come segnale che devo essere più visibile. Mi attivo.', pt: 'Tomo como sinal de que preciso ser mais visível. Me ativo.' }, dimension: 'M' },
    ] },
    { id: 3, situation: { es: 'Un amigo publica fotos de sus vacaciones espectaculares. Tú no puedes permitirte ese tipo de viajes.', en: 'A friend posts photos of their spectacular vacation. You can\'t afford that kind of travel.', fr: 'Un ami publie des photos de ses vacances spectaculaires. Tu ne peux pas te permettre ce type de voyage.', de: 'Ein Freund postet Fotos von seinem spektakulären Urlaub. Du kannst dir solche Reisen nicht leisten.', it: 'Un amico pubblica foto delle sue vacanze spettacolari. Non puoi permetterti quel tipo di viaggi.', pt: 'Um amigo publica fotos das suas férias espetaculares. Você não pode se dar ao luxo desse tipo de viagem.' }, options: [
      { text: { es: 'Las miro todas con una mezcla de admiración y algo que se siente muy feo por dentro.', en: 'I look at all of them with a mix of admiration and something that feels very ugly inside.', fr: 'Je les regarde toutes avec un mélange d\'admiration et quelque chose qui se sent très laid à l\'intérieur.', de: 'Ich schaue sie alle an mit einer Mischung aus Bewunderung und etwas, das sich sehr hässlich anfühlt.', it: 'Le guardo tutte con un mix di ammirazione e qualcosa che si sente molto brutto dentro.', pt: 'Vejo todas com uma mistura de admiração e algo que parece muito feio por dentro.' }, dimension: 'E' },
      { text: { es: 'Empiezo a pensar que "seguro tiene deudas" o que "no es tan divertido como parece".', en: 'I start thinking "they probably have debt" or "it\'s not as fun as it looks".', fr: 'Je commence à penser "il/elle a sûrement des dettes" ou "ce n\'est pas aussi amusant que ça paraît".', de: 'Ich fange an zu denken "sie haben wahrscheinlich Schulden" oder "es ist nicht so spaßig, wie es aussieht".', it: 'Comincio a pensare "di sicuro ha debiti" o "non è così divertente come sembra".', pt: 'Começo a pensar que "certamente tem dívidas" ou "não é tão divertido quanto parece".' }, dimension: 'P' },
      { text: { es: 'Me alegra que esté disfrutando. Cada quien con su timing.', en: 'I\'m glad they\'re enjoying it. Everyone has their timing.', fr: 'Je suis content(e) qu\'il/elle profite. Chacun a son timing.', de: 'Ich freue mich, dass er/sie es genießt. Jeder hat seinen Zeitpunkt.', it: 'Sono contento/a che stia godendo. Ognuno ha il suo timing.', pt: 'Fico feliz que esteja aproveitando. Cada um tem seu timing.' }, dimension: 'A' },
      { text: { es: 'Lo uso para crear un plan de ahorro. Si quiero eso, necesito hacer algo diferente.', en: 'I use it to create a savings plan. If I want that, I need to do something different.', fr: 'Je l\'utilise pour créer un plan d\'épargne. Si je veux ça, je dois faire quelque chose de différent.', de: 'Ich nutze es, um einen Sparplan zu erstellen. Wenn ich das will, muss ich etwas anders machen.', it: 'Lo uso per creare un piano di risparmio. Se voglio quello, devo fare qualcosa di diverso.', pt: 'Uso para criar um plano de poupança. Se quero isso, preciso fazer algo diferente.' }, dimension: 'M' },
    ] },
    { id: 4, situation: { es: 'Alguien de tu círculo recibe un elogio público que sientes que tú mereces igual o más.', en: 'Someone in your circle receives public praise you feel you deserve equally or more.', fr: 'Quelqu\'un de ton entourage reçoit des éloges publics que tu penses mériter autant ou davantage.', de: 'Jemand in deinem Umfeld bekommt öffentliches Lob, das du glaubst gleichwertig oder mehr zu verdienen.', it: 'Qualcuno del tuo cerchio riceve elogi pubblici che senti di meritare altrettanto o di più.', pt: 'Alguém do seu círculo recebe um elogio público que você sente merecer igualmente ou mais.' }, options: [
      { text: { es: 'Me incomoda más de lo que debería. No puedo evitar pensar que debería ser para mí también.', en: 'It bothers me more than it should. I can\'t help thinking it should be for me too.', fr: 'Ça me dérange plus que ça ne devrait. Je ne peux m\'empêcher de penser que ça devrait être pour moi aussi.', de: 'Es stört mich mehr als es sollte. Ich kann nicht umhin zu denken, dass es auch für mich sein sollte.', it: 'Mi disturba più di quanto dovrebbe. Non posso fare a meno di pensare che dovrebbe essere anche per me.', pt: 'Me incomoda mais do que deveria. Não consigo evitar pensar que deveria ser para mim também.' }, dimension: 'E' },
      { text: { es: 'Pienso que elogiaron a esa persona porque conocen al jurado o tienen más contactos.', en: 'I think they praised that person because they know the jury or have more connections.', fr: 'Je pense qu\'ils ont loué cette personne parce qu\'elle connaît le jury ou a plus de contacts.', de: 'Ich denke, sie lobten diese Person, weil sie die Jury kennt oder mehr Kontakte hat.', it: 'Penso che abbiano elogiato quella persona perché conosce la giuria o ha più contatti.', pt: 'Acho que elogiaram essa pessoa porque conhece o júri ou tem mais contatos.' }, dimension: 'P' },
      { text: { es: 'Me alegro. El reconocimiento no es un pastel del que si le dan a otro, me queda menos.', en: 'I\'m glad. Recognition is not a pie: giving it to others doesn\'t leave me with less.', fr: 'Je me réjouis. La reconnaissance n\'est pas un gâteau dont si on en donne à l\'autre, il m\'en reste moins.', de: 'Ich freue mich. Anerkennung ist kein Kuchen: wenn man ihn anderen gibt, bleibt mir nicht weniger.', it: 'Mi rallegro. Il riconoscimento non è una torta da cui se ne danno a un altro, me ne rimane meno.', pt: 'Fico feliz. O reconhecimento não é um bolo: dar a outros não deixa menos para mim.' }, dimension: 'A' },
      { text: { es: 'Lo proceso rápido y me pregunto qué necesito hacer para merecer ese mismo reconocimiento.', en: 'I process it quickly and ask myself what I need to do to deserve that same recognition.', fr: 'Je le traite rapidement et me demande ce que je dois faire pour mériter cette même reconnaissance.', de: 'Ich verarbeite es schnell und frage mich, was ich tun muss, um die gleiche Anerkennung zu verdienen.', it: 'Lo processo velocemente e mi chiedo cosa devo fare per meritare lo stesso riconoscimento.', pt: 'Processo rápido e me pergunto o que preciso fazer para merecer esse mesmo reconhecimento.' }, dimension: 'M' },
    ] },
    { id: 5, situation: { es: 'Tu ex pareja rehízo su vida rápidamente y parece muy feliz. Mucho más que contigo.', en: 'Your ex quickly rebuilt their life and seems very happy. Much happier than with you.', fr: 'Ton/ta ex a refait sa vie rapidement et semble très heureux/se. Beaucoup plus qu\'avec toi.', de: 'Dein Ex hat sein/ihr Leben schnell neu aufgebaut und scheint sehr glücklich. Viel glücklicher als mit dir.', it: 'Il tuo ex ha ricostruito la sua vita rapidamente e sembra molto felice. Molto più che con te.', pt: 'Seu ex refez a vida rapidamente e parece muito feliz. Muito mais do que com você.' }, options: [
      { text: { es: 'Me duele y me irrita al mismo tiempo. No debería importarme, pero me importa demasiado.', en: 'It hurts and irritates me at the same time. I shouldn\'t care, but I care too much.', fr: 'Ça me fait mal et m\'irrite en même temps. Ça ne devrait pas m\'importer, mais ça m\'importe trop.', de: 'Es tut weh und ärgert mich gleichzeitig. Es sollte mir egal sein, aber es ist mir zu wichtig.', it: 'Mi fa male e mi irrita allo stesso tempo. Non dovrebbe importarmi, ma mi importa troppo.', pt: 'Me dói e irrita ao mesmo tempo. Não deveria me importar, mas me importa demais.' }, dimension: 'E' },
      { text: { es: 'Esa felicidad tiene que ser forzada o superficial. Nadie supera algo serio tan rápido.', en: 'That happiness must be forced or superficial. Nobody gets over something serious that fast.', fr: 'Ce bonheur doit être forcé ou superficiel. Personne ne surmonte quelque chose de sérieux si vite.', de: 'Dieses Glück muss erzwungen oder oberflächlich sein. Niemand überwindet etwas Ernstes so schnell.', it: 'Quella felicità deve essere forzata o superficiale. Nessuno supera qualcosa di serio così in fretta.', pt: 'Essa felicidade deve ser forçada ou superficial. Ninguém supera algo sério tão rápido.' }, dimension: 'P' },
      { text: { es: 'Me alegra que esté bien. Fue importante para mí y quiero que sea feliz.', en: 'I\'m glad they\'re well. They were important to me and I want them to be happy.', fr: 'Je suis content(e) qu\'il/elle aille bien. Il/elle était important(e) pour moi et je veux qu\'il/elle soit heureux/se.', de: 'Ich bin froh, dass es ihm/ihr gut geht. Er/sie war mir wichtig und ich wünsche mir, dass er/sie glücklich ist.', it: 'Sono contento/a che stia bene. Era importante per me e voglio che sia felice.', pt: 'Fico feliz que esteja bem. Foi importante para mim e quero que seja feliz.' }, dimension: 'A' },
      { text: { es: 'Me recuerda que yo también tengo que priorizar mi propia felicidad. A construir la mía.', en: 'It reminds me that I also need to prioritize my own happiness. Time to build mine.', fr: 'Ça me rappelle que je dois aussi prioriser mon propre bonheur. À construire le mien.', de: 'Es erinnert mich daran, dass ich auch mein eigenes Glück priorisieren muss. Zeit, meins aufzubauen.', it: 'Mi ricorda che anch\'io devo dare priorità alla mia felicità. A costruire la mia.', pt: 'Me lembra que também preciso priorizar minha própria felicidade. A construir a minha.' }, dimension: 'M' },
    ] },
    { id: 6, situation: { es: 'Un amigo de la infancia se volvió famoso/rico. Antes eran del mismo nivel.', en: 'A childhood friend became famous/rich. You were at the same level before.', fr: 'Un ami d\'enfance est devenu célèbre/riche. Vous étiez au même niveau avant.', de: 'Ein Kindheitsfreund wurde berühmt/reich. Früher wart ihr auf dem gleichen Niveau.', it: 'Un amico d\'infanzia è diventato famoso/ricco. Prima eravate allo stesso livello.', pt: 'Um amigo de infância se tornou famoso/rico. Antes eram do mesmo nível.' }, options: [
      { text: { es: 'Siento que la vida me debe algo. Éramos iguales y ahora hay una brecha enorme.', en: 'I feel life owes me something. We were equal and now there\'s a huge gap.', fr: 'Je sens que la vie me doit quelque chose. Nous étions égaux et maintenant il y a un écart énorme.', de: 'Ich habe das Gefühl, das Leben schuldet mir etwas. Wir waren gleich und jetzt gibt es eine riesige Lücke.', it: 'Sento che la vita mi deve qualcosa. Eravamo uguali e ora c\'è un enorme divario.', pt: 'Sinto que a vida me deve algo. Éramos iguais e agora há uma lacuna enorme.' }, dimension: 'E' },
      { text: { es: 'Algo tuvo que pasar para ese salto tan rápido. Nadie sube tan alto limpiamente.', en: 'Something must have happened for that jump. Nobody rises that high cleanly.', fr: 'Quelque chose a dû se passer pour ce saut si rapide. Personne ne monte si haut proprement.', de: 'Irgendetwas muss für diesen schnellen Sprung passiert sein. Niemand steigt so hoch ohne Tricks auf.', it: 'Qualcosa deve essere successo per quel salto così rapido. Nessuno sale così in alto pulitamente.', pt: 'Algo teve que acontecer para esse salto tão rápido. Ninguém sobe tão alto de forma limpa.' }, dimension: 'P' },
      { text: { es: 'Me llena de orgullo conocer a alguien que logró tanto. Es inspirador.', en: 'It fills me with pride to know someone who achieved so much. It\'s inspiring.', fr: 'Je suis fier/fière de connaître quelqu\'un qui a accompli autant. C\'est inspirant.', de: 'Es erfüllt mich mit Stolz, jemanden zu kennen, der so viel erreicht hat. Es ist inspirierend.', it: 'Sono pieno/a di orgoglio di conoscere qualcuno che ha ottenuto così tanto. È ispirante.', pt: 'Fico orgulhoso/a de conhecer alguém que conquistou tanto. É inspirador.' }, dimension: 'A' },
      { text: { es: 'Me activa. Si alguien de donde vengo llegó ahí, el camino existe.', en: 'It activates me. If someone from where I come from got there, the path exists.', fr: 'Ça m\'active. Si quelqu\'un d\'où je viens est arrivé là, le chemin existe.', de: 'Es aktiviert mich. Wenn jemand von wo ich komme dort angekommen ist, gibt es den Weg.', it: 'Mi attiva. Se qualcuno da dove vengo è arrivato lì, il percorso esiste.', pt: 'Me ativa. Se alguém de onde venho chegou lá, o caminho existe.' }, dimension: 'M' },
    ] },
    { id: 7, situation: { es: 'Alguien que no conoces mucho tiene mucho más talento natural para algo que tú practicas hace años.', en: 'Someone you barely know has much more natural talent for something you\'ve practiced for years.', fr: 'Quelqu\'un que tu ne connais pas beaucoup a beaucoup plus de talent naturel pour quelque chose que tu pratiques depuis des années.', de: 'Jemand, den du kaum kennst, hat viel mehr natürliches Talent für etwas, das du seit Jahren übst.', it: 'Qualcuno che non conosci molto ha molto più talento naturale per qualcosa che pratichi da anni.', pt: 'Alguém que mal conhece tem muito mais talento natural para algo que você pratica há anos.' }, options: [
      { text: { es: 'Me frustra profundamente. ¿Para qué me esfuerzo si otros nacen con eso?', en: 'It deeply frustrates me. Why do I bother if others are born with it?', fr: 'Ça me frustre profondément. Pourquoi je m\'efforce si d\'autres naissent avec ça ?', de: 'Es frustriert mich tief. Wozu strenge ich mich an, wenn andere damit geboren werden?', it: 'Mi frustra profondamente. A cosa serve sforzarmi se altri nascono con quello?', pt: 'Me frustra profundamente. Para que me esforço se outros nascem com isso?' }, dimension: 'E' },
      { text: { es: 'Probablemente tuvo ventajas que yo no tuve. No es un campo nivelado.', en: 'They probably had advantages I didn\'t. It\'s not a level field.', fr: 'Il/elle a probablement eu des avantages que je n\'ai pas eus. Ce n\'est pas un terrain nivelé.', de: 'Er/sie hatte wahrscheinlich Vorteile, die ich nicht hatte. Es ist kein ebenes Spielfeld.', it: 'Probabilmente ha avuto vantaggi che io non ho avuto. Non è un campo livellato.', pt: 'Provavelmente teve vantagens que eu não tive. Não é um campo nivelado.' }, dimension: 'P' },
      { text: { es: 'Me parece increíble. El talento natural es un regalo y me gusta verlo.', en: 'I find it incredible. Natural talent is a gift and I like watching it.', fr: 'Je trouve ça incroyable. Le talent naturel est un don et j\'aime le voir.', de: 'Ich finde es unglaublich. Natürliches Talent ist ein Geschenk und ich mag es zu sehen.', it: 'Mi sembra incredibile. Il talento naturale è un dono e mi piace vederlo.', pt: 'Acho incrível. O talento natural é um dom e gosto de ver.' }, dimension: 'A' },
      { text: { es: 'Me recuerda que el talento sin esfuerzo no llega lejos. Mi disciplina es mi ventaja.', en: 'It reminds me that talent without effort doesn\'t go far. My discipline is my advantage.', fr: 'Ça me rappelle que le talent sans effort ne va pas loin. Ma discipline est mon avantage.', de: 'Es erinnert mich daran, dass Talent ohne Einsatz nicht weit kommt. Meine Disziplin ist mein Vorteil.', it: 'Mi ricorda che il talento senza sforzo non arriva lontano. La mia disciplina è il mio vantaggio.', pt: 'Me lembra que o talento sem esforço não vai longe. Minha disciplina é minha vantagem.' }, dimension: 'M' },
    ] },
    { id: 8, situation: { es: 'Tu mejor amigo/a tiene una relación de pareja que parece perfecta. La tuya es complicada.', en: 'Your best friend has a relationship that seems perfect. Yours is complicated.', fr: 'Ton/ta meilleur(e) ami(e) a une relation amoureuse qui semble parfaite. La tienne est compliquée.', de: 'Dein bester Freund/deine beste Freundin hat eine Beziehung, die perfekt erscheint. Deine ist kompliziert.', it: 'Il tuo migliore amico/a ha una relazione che sembra perfetta. La tua è complicata.', pt: 'Seu melhor amigo/a tem um relacionamento que parece perfeito. O seu é complicado.' }, options: [
      { text: { es: 'A veces me pregunto por qué a ellos les resulta tan fácil y a mí tan difícil.', en: 'Sometimes I wonder why it\'s so easy for them and so hard for me.', fr: 'Parfois je me demande pourquoi c\'est si facile pour eux et si difficile pour moi.', de: 'Manchmal frage ich mich, warum es für sie so einfach und für mich so schwer ist.', it: 'A volte mi chiedo perché a loro venga così facile e a me così difficile.', pt: 'Às vezes me pergunto por que para eles é tão fácil e para mim tão difícil.' }, dimension: 'E' },
      { text: { es: 'Nadie muestra la realidad en redes. Seguro no es tan idílico como parece.', en: 'Nobody shows reality on social media. It\'s probably not as idyllic as it seems.', fr: 'Personne ne montre la réalité sur les réseaux. Ce n\'est sûrement pas aussi idyllique que ça semble.', de: 'Niemand zeigt die Realität in sozialen Medien. Es ist wahrscheinlich nicht so idyllisch, wie es scheint.', it: 'Nessuno mostra la realtà sui social. Di sicuro non è così idilliaco come sembra.', pt: 'Ninguém mostra a realidade nas redes. Certamente não é tão idílico quanto parece.' }, dimension: 'P' },
      { text: { es: 'Me alegra que tengan algo tan bueno. Me da esperanza de que es posible.', en: 'I\'m glad they have something so good. It gives me hope that it\'s possible.', fr: 'Je suis content(e) qu\'ils aient quelque chose d\'aussi bon. Ça me donne l\'espoir que c\'est possible.', de: 'Ich bin froh, dass sie etwas so Gutes haben. Es gibt mir Hoffnung, dass es möglich ist.', it: 'Sono contento/a che abbiano qualcosa di così buono. Mi dà speranza che sia possibile.', pt: 'Fico feliz que tenham algo tão bom. Me dá esperança de que é possível.' }, dimension: 'A' },
      { text: { es: 'Me hace reflexionar sobre qué necesito cambiar en mi propia relación.', en: 'It makes me reflect on what I need to change in my own relationship.', fr: 'Ça me fait réfléchir à ce que je dois changer dans ma propre relation.', de: 'Es lässt mich darüber nachdenken, was ich in meiner eigenen Beziehung ändern muss.', it: 'Mi fa riflettere su cosa devo cambiare nella mia relazione.', pt: 'Me faz refletir sobre o que preciso mudar no meu próprio relacionamento.' }, dimension: 'M' },
    ] },
    { id: 9, situation: { es: 'Un libro que escribiste recibió críticas moderadas. Uno de un colega fue un éxito total.', en: 'A book you wrote received moderate reviews. One by a colleague was a total success.', fr: 'Un livre que tu as écrit a reçu des critiques modérées. Celui d\'un collègue a été un succès total.', de: 'Ein Buch, das du geschrieben hast, erhielt moderate Kritiken. Das eines Kollegen war ein totaler Erfolg.', it: 'Un libro che hai scritto ha ricevuto recensioni moderate. Quello di un collega è stato un successo totale.', pt: 'Um livro que você escreveu recebeu críticas moderadas. O de um colega foi um sucesso total.' }, options: [
      { text: { es: 'No puedo leer su libro sin pensar que el mío merecía más.', en: 'I can\'t read their book without thinking mine deserved more.', fr: 'Je ne peux pas lire son livre sans penser que le mien méritait plus.', de: 'Ich kann sein/ihr Buch nicht lesen, ohne zu denken, dass meins mehr verdient hätte.', it: 'Non riesco a leggere il suo libro senza pensare che il mio meritasse di più.', pt: 'Não consigo ler o livro dele/dela sem pensar que o meu merecia mais.' }, dimension: 'E' },
      { text: { es: 'El mercado editorial es caprichoso. No hay una correlación real entre calidad y éxito.', en: 'The publishing market is capricious. There\'s no real correlation between quality and success.', fr: 'Le marché éditorial est capricieux. Il n\'y a pas de corrélation réelle entre qualité et succès.', de: 'Der Verlagsmarkt ist launisch. Es gibt keine echte Korrelation zwischen Qualität und Erfolg.', it: 'Il mercato editoriale è capriccioso. Non c\'è una correlazione reale tra qualità e successo.', pt: 'O mercado editorial é caprichoso. Não há correlação real entre qualidade e sucesso.' }, dimension: 'P' },
      { text: { es: 'Me alegra que un buen libro tenga éxito. Empuja el mercado hacia arriba para todos.', en: 'I\'m glad a good book is successful. It pushes the market up for everyone.', fr: 'Je suis content(e) qu\'un bon livre ait du succès. Ça pousse le marché vers le haut pour tout le monde.', de: 'Ich freue mich, dass ein gutes Buch Erfolg hat. Es treibt den Markt für alle nach oben.', it: 'Sono contento/a che un buon libro abbia successo. Spinge il mercato verso l\'alto per tutti.', pt: 'Fico feliz que um bom livro tenha sucesso. Empurra o mercado para cima para todos.' }, dimension: 'A' },
      { text: { es: 'Analizo qué hizo diferente y lo incorporo a mi próximo proyecto.', en: 'I analyze what they did differently and incorporate it into my next project.', fr: 'J\'analyse ce qu\'il/elle a fait différemment et l\'incorpore à mon prochain projet.', de: 'Ich analysiere, was er/sie anders gemacht hat, und integriere es in mein nächstes Projekt.', it: 'Analizzo cosa ha fatto di diverso e lo incorporo nel mio prossimo progetto.', pt: 'Analiso o que fez diferente e incorporo ao meu próximo projeto.' }, dimension: 'M' },
    ] },
    { id: 10, situation: { es: 'Alguien que te cae mal logra algo extraordinario.', en: 'Someone you dislike achieves something extraordinary.', fr: 'Quelqu\'un que tu n\'apprécies pas réalise quelque chose d\'extraordinaire.', de: 'Jemand, den du nicht magst, erreicht etwas Außergewöhnliches.', it: 'Qualcuno che non ti sta simpatico ottiene qualcosa di straordinario.', pt: 'Alguém que você não curte conquista algo extraordinário.' }, options: [
      { text: { es: 'No puedo evitar que me moleste más que si lo hubiera logrado alguien que aprecio.', en: 'I can\'t help it bothering me more than if someone I like had achieved it.', fr: 'Je ne peux pas m\'empêcher que ça me dérange plus que si quelqu\'un que j\'apprécie l\'avait réalisé.', de: 'Ich kann nicht umhin, dass es mich mehr stört, als wenn jemand, den ich mag, es erreicht hätte.', it: 'Non riesco a evitare che mi disturbi di più che se lo avesse ottenuto qualcuno che apprezzo.', pt: 'Não consigo evitar que me incomode mais do que se fosse alguém que aprecio.' }, dimension: 'E' },
      { text: { es: 'Algo oscuro tuvo que haber detrás. La gente así no llega tan lejos de forma limpia.', en: 'Something dark must be behind it. People like that don\'t get that far cleanly.', fr: 'Il doit y avoir quelque chose de sombre derrière. Les gens comme ça n\'arrivent pas si loin proprement.', de: 'Etwas Dunkles muss dahinterstecken. Solche Menschen kommen nicht so weit ohne Tricks.', it: 'Qualcosa di oscuro deve esserci dietro. La gente così non arriva così in alto pulitamente.', pt: 'Algo obscuro deve estar por trás. Pessoas assim não chegam tão longe de forma limpa.' }, dimension: 'P' },
      { text: { es: 'El mérito es el mérito. No cambia por quién lo tenga.', en: 'Merit is merit. It doesn\'t change based on who has it.', fr: 'Le mérite est le mérite. Ça ne change pas selon qui l\'a.', de: 'Verdienst ist Verdienst. Er ändert sich nicht danach, wer ihn hat.', it: 'Il merito è il merito. Non cambia in base a chi ce l\'ha.', pt: 'Mérito é mérito. Não muda dependendo de quem tem.' }, dimension: 'A' },
      { text: { es: 'Si alguien que me cae mal puede lograrlo, yo definitivamente también puedo.', en: 'If someone I dislike can achieve it, I definitely can too.', fr: 'Si quelqu\'un que je n\'apprécie pas peut y arriver, moi définitivement aussi.', de: 'Wenn jemand, den ich nicht mag, es schaffen kann, kann ich es definitiv auch.', it: 'Se qualcuno che non mi sta simpatico può farcela, posso farcela anch\'io.', pt: 'Se alguém que não curto pode conseguir, eu definitivamente também posso.' }, dimension: 'M' },
    ] },
  ],
  characters: [
    { name: { es: 'La Envidia Activa', en: 'Active Envy', fr: 'L\'Envie Active', de: 'Aktiver Neid', it: 'L\'Invidia Attiva', pt: 'A Inveja Ativa' }, dimensions: ['E'], photo: '/characters/active-envy.jpg', description: { es: 'La envidia que corroe por dentro y contamina las relaciones.', en: 'The envy that corrodes from within and contaminates relationships.', fr: 'L\'envie qui ronge de l\'intérieur et contamine les relations.', de: 'Der Neid, der von innen zerfrisst und Beziehungen vergiftet.', it: 'L\'invidia che corrode dall\'interno e contamina le relazioni.', pt: 'A inveja que corrói por dentro e contamina os relacionamentos.' }, philosophy: { es: 'Tu envidia no es motivación — es veneno. Sientes el éxito ajeno como una derrota personal. Hasta que reconozcas que el pastel del éxito no es de un tamaño fijo, seguirás sintiendo que te roban lo tuyo.', en: 'Your envy is not motivation — it\'s poison. You feel others\' success as a personal defeat. Until you recognize that the pie of success is not a fixed size, you\'ll keep feeling that yours is being stolen.', fr: 'Ton envie n\'est pas de la motivation — c\'est du poison. Tu ressens le succès des autres comme une défaite personnelle. Jusqu\'à ce que tu reconnaisse que le gâteau du succès n\'est pas de taille fixe, tu continueras à sentir qu\'on te vole le tien.', de: 'Dein Neid ist keine Motivation — er ist Gift. Du erlebst den Erfolg anderer als persönliche Niederlage. Bis du erkennst, dass der Kuchen des Erfolgs keine feste Größe hat, wirst du weiterhin das Gefühl haben, dass dir deins gestohlen wird.', it: 'La tua invidia non è motivazione — è veleno. Senti il successo altrui come una sconfitta personale. Finché non riconosci che la torta del successo non è di dimensioni fisse, continuerai a sentire che ti rubano il tuo.', pt: 'Sua inveja não é motivação — é veneno. Você sente o sucesso alheio como uma derrota pessoal. Até reconhecer que o bolo do sucesso não é de tamanho fixo, você continuará sentindo que o seu está sendo roubado.' } },
    { name: { es: 'El Racionalizador', en: 'The Rationalizer', fr: 'Le Rationaliseur', de: 'Der Rationalisierer', it: 'Il Razionalizzatore', pt: 'O Racionalizador' }, dimensions: ['P'], photo: '/characters/rationalizer.jpg', description: { es: 'Desacredita el éxito ajeno para no tener que sentir la envidia directamente.', en: 'Discredits others\' success to avoid feeling envy directly.', fr: 'Discrédite le succès des autres pour ne pas avoir à ressentir l\'envie directement.', de: 'Diskreditiert den Erfolg anderer, um Neid nicht direkt fühlen zu müssen.', it: 'Scredita il successo altrui per non dover sentire l\'invidia direttamente.', pt: 'Desacredita o sucesso alheio para não ter que sentir a inveja diretamente.' }, philosophy: { es: 'No te permites sentir envidia — eso sería admitir que el otro tiene algo valioso. Así que construyes narrativas alternativas. El éxito de otros siempre tiene una explicación que no sea el mérito.', en: 'You don\'t allow yourself to feel envy — that would mean admitting the other has something valuable. So you build alternative narratives. Others\' success always has an explanation that isn\'t merit.', fr: 'Tu ne te permets pas de ressentir de l\'envie — ce serait admettre que l\'autre a quelque chose de précieux. Alors tu construis des récits alternatifs. Le succès des autres a toujours une explication autre que le mérite.', de: 'Du erlaubst dir nicht, Neid zu fühlen — das würde bedeuten zuzugeben, dass der andere etwas Wertvolles hat. Also baust du alternative Narrative. Der Erfolg anderer hat immer eine Erklärung, die kein Verdienst ist.', it: 'Non ti permetti di sentire invidia — significherebbe ammettere che l\'altro ha qualcosa di prezioso. Quindi costruisci narrazioni alternative. Il successo degli altri ha sempre una spiegazione che non è il merito.', pt: 'Você não se permite sentir inveja — isso seria admitir que o outro tem algo valioso. Então você constrói narrativas alternativas. O sucesso dos outros sempre tem uma explicação que não é mérito.' } },
    { name: { es: 'El Admirador Genuino', en: 'The Genuine Admirer', fr: 'L\'Admirateur Génuino', de: 'Der Echte Bewunderer', it: 'L\'Ammiratore Genuino', pt: 'O Admirador Genuíno' }, dimensions: ['A'], photo: '/characters/admirer.jpg', description: { es: 'Siente admiración donde otros sienten envidia.', en: 'Feels admiration where others feel envy.', fr: 'Ressent de l\'admiration là où les autres ressentent de l\'envie.', de: 'Fühlt Bewunderung, wo andere Neid fühlen.', it: 'Sente ammirazione dove gli altri sentono invidia.', pt: 'Sente admiração onde os outros sentem inveja.' }, philosophy: { es: 'Has aprendido — o tal vez siempre supiste — que el éxito ajeno no te quita nada. Puedes admirar sin resentir. Es una de las formas más sanas de relacionarte con el mundo, y también una de las más raras.', en: 'You\'ve learned — or maybe always knew — that others\' success takes nothing from you. You can admire without resentment. It\'s one of the healthiest ways to relate to the world, and also one of the rarest.', fr: 'Tu as appris — ou peut-être toujours su — que le succès des autres ne te prend rien. Tu peux admirer sans ressentir. C\'est l\'une des façons les plus saines de se lier au monde, et aussi l\'une des plus rares.', de: 'Du hast gelernt — oder vielleicht immer gewusst — dass der Erfolg anderer dir nichts wegnimmt. Du kannst bewundern ohne Groll. Es ist eine der gesündesten Arten, sich zur Welt zu verhalten, und auch eine der seltensten.', it: 'Hai imparato — o forse hai sempre saputo — che il successo altrui non ti toglie nulla. Puoi ammirare senza risentirsi. È uno dei modi più sani di relazionarsi col mondo, e anche uno dei più rari.', pt: 'Você aprendeu — ou talvez sempre soube — que o sucesso alheio não tira nada de você. Você pode admirar sem ressentir. É uma das formas mais saudáveis de se relacionar com o mundo, e também uma das mais raras.' } },
    { name: { es: 'El Motivado por el Contraste', en: 'The Contrast-Motivated', fr: 'Le Motivé par le Contraste', de: 'Der Kontrastmotivierte', it: 'Il Motivato dal Contrasto', pt: 'O Motivado pelo Contraste' }, dimensions: ['M'], photo: '/characters/motivated.jpg', description: { es: 'Convierte la envidia en combustible de acción.', en: 'Converts envy into fuel for action.', fr: 'Convertit l\'envie en carburant d\'action.', de: 'Verwandelt Neid in Treibstoff für Handlung.', it: 'Converte l\'invidia in carburante d\'azione.', pt: 'Converte a inveja em combustível para ação.' }, philosophy: { es: 'Cuando ves a alguien lograr algo que quieres, no sientes resentimiento — sientes activación. El éxito ajeno es evidencia de que el camino existe. Tu motor arranca cuando ves que es posible.', en: 'When you see someone achieve something you want, you don\'t feel resentment — you feel activation. Others\' success is evidence that the path exists. Your engine starts when you see it\'s possible.', fr: 'Quand tu vois quelqu\'un réaliser quelque chose que tu veux, tu ne ressens pas de ressentiment — tu te sens activé(e). Le succès des autres est la preuve que le chemin existe. Ton moteur démarre quand tu vois que c\'est possible.', de: 'Wenn du jemanden siehst, der etwas erreicht, das du willst, fühlst du keinen Groll — du fühlst Aktivierung. Der Erfolg anderer ist der Beweis, dass der Weg existiert. Dein Motor startet, wenn du siehst, dass es möglich ist.', it: 'Quando vedi qualcuno raggiungere qualcosa che vuoi, non senti risentimento — senti attivazione. Il successo altrui è la prova che il percorso esiste. Il tuo motore parte quando vedi che è possibile.', pt: 'Quando você vê alguém conquista algo que quer, não sente ressentimento — sente ativação. O sucesso alheio é evidência de que o caminho existe. Seu motor liga quando você vê que é possível.' } },
    { name: { es: 'El Envidioso Consciente', en: 'The Conscious Envious', fr: 'L\'Envieux Conscient', de: 'Der Bewusste Neidische', it: 'L\'Invidioso Consapevole', pt: 'O Invejoso Consciente' }, dimensions: ['E', 'M'], photo: '/characters/conscious-envy.jpg', description: { es: 'Siente envidia pero la convierte en energía productiva.', en: 'Feels envy but converts it into productive energy.', fr: 'Ressent de l\'envie mais la convertit en énergie productive.', de: 'Fühlt Neid, aber verwandelt ihn in produktive Energie.', it: 'Sente invidia ma la converte in energia produttiva.', pt: 'Sente inveja mas a converte em energia produtiva.' }, philosophy: { es: 'Sientes la punzada, no te la negas. Pero después de sentirla, la canalizas. Eres honesto/a contigo mismo/a sobre lo que sientes y lo suficientemente inteligente para no quedarte ahí.', en: 'You feel the sting, you don\'t deny it. But after feeling it, you channel it. You\'re honest with yourself about what you feel and smart enough not to stay there.', fr: 'Tu ressens la piqûre, tu ne la nies pas. Mais après l\'avoir ressentie, tu la canalises. Tu es honnête avec toi-même sur ce que tu ressens et assez intelligent(e) pour ne pas y rester.', de: 'Du fühlst den Stich, du leugnest ihn nicht. Aber nachdem du ihn gefühlt hast, kanalisierst du ihn. Du bist ehrlich zu dir selbst über das, was du fühlst, und klug genug, um nicht dabei zu bleiben.', it: 'Senti la puntura, non te la nega. Ma dopo averla sentita, la canalizza. Sei onesto/a con te stesso/a su quello che senti e abbastanza intelligente da non restarci.', pt: 'Você sente a picada, não a nega. Mas depois de sentir, canaliza. Você é honesto/a consigo mesmo/a sobre o que sente e inteligente o suficiente para não ficar nisso.' } },
    { name: { es: 'El Crítico Protector', en: 'The Protective Critic', fr: 'Le Critique Protecteur', de: 'Der Schützende Kritiker', it: 'Il Critico Protettore', pt: 'O Crítico Protetor' }, dimensions: ['P', 'E'], photo: '/characters/critical-protector.jpg', description: { es: 'Racionaliza y resiente al mismo tiempo.', en: 'Rationalizes and resents at the same time.', fr: 'Rationalise et ressent du ressentiment en même temps.', de: 'Rationalisiert und empfindet gleichzeitig Groll.', it: 'Razionalizza e risente allo stesso tempo.', pt: 'Racionaliza e ressente ao mesmo tempo.' }, philosophy: { es: 'Primero desacreditas el logro ajeno para no tener que sentirlo. Cuando eso no funciona, lo sientes igual. Vives en un ciclo de defensa y resentimiento que gasta muchísima energía sin producir nada.', en: 'First you discredit others\' achievement so you don\'t have to feel it. When that doesn\'t work, you feel it anyway. You live in a cycle of defense and resentment that spends enormous energy without producing anything.', fr: 'D\'abord tu discrédites la réussite des autres pour ne pas avoir à la ressentir. Quand ça ne marche pas, tu la ressens quand même. Tu vis dans un cycle de défense et de ressentiment qui dépense énormément d\'énergie sans rien produire.', de: 'Zuerst diskreditierst du die Leistung anderer, damit du sie nicht fühlen musst. Wenn das nicht funktioniert, fühlst du es trotzdem. Du lebst in einem Kreislauf aus Verteidigung und Groll, der enorm viel Energie verbraucht ohne etwas zu produzieren.', it: 'Prima discrediti il successo altrui per non doverlo sentire. Quando quello non funziona, lo senti comunque. Vivi in un ciclo di difesa e risentimento che spende moltissima energia senza produrre nulla.', pt: 'Primeiro você desacredita a conquista alheia para não ter que senti-la. Quando isso não funciona, você sente de qualquer jeito. Você vive em um ciclo de defesa e ressentimento que gasta uma enorme energia sem produzir nada.' } },
    { name: { es: 'El Sabio Observador', en: 'The Wise Observer', fr: 'Le Sage Observateur', de: 'Der Weise Beobachter', it: 'Il Saggio Osservatore', pt: 'O Sábio Observador' }, dimensions: ['A', 'M'], photo: '/characters/wise-observer.jpg', description: { es: 'Aprende del éxito ajeno para construir el suyo.', en: 'Learns from others\' success to build their own.', fr: 'Apprend du succès des autres pour construire le sien.', de: 'Lernt aus dem Erfolg anderer, um den eigenen aufzubauen.', it: 'Impara dal successo altrui per costruire il suo.', pt: 'Aprende com o sucesso alheio para construir o seu.' }, philosophy: { es: 'Para ti, las personas exitosas son un recurso, no una amenaza. Las observas, admiras lo que hacen bien y absorbes lo que puede ser útil. Tu envidia, si existe, dura cinco minutos antes de convertirse en un plan.', en: 'For you, successful people are a resource, not a threat. You observe them, admire what they do well, and absorb what can be useful. Your envy, if it exists, lasts five minutes before becoming a plan.', fr: 'Pour toi, les personnes qui réussissent sont une ressource, pas une menace. Tu les observes, admires ce qu\'elles font bien et absorbes ce qui peut être utile. Ton envie, si elle existe, dure cinq minutes avant de se transformer en plan.', de: 'Für dich sind erfolgreiche Menschen eine Ressource, keine Bedrohung. Du beobachtest sie, bewunderst was sie gut machen und absorbierst was nützlich sein kann. Dein Neid, wenn er existiert, dauert fünf Minuten, bevor er zu einem Plan wird.', it: 'Per te, le persone di successo sono una risorsa, non una minaccia. Le osservi, ammiri quello che fanno bene e assorbi quello che può essere utile. La tua invidia, se esiste, dura cinque minuti prima di diventare un piano.', pt: 'Para você, pessoas bem-sucedidas são um recurso, não uma ameaça. Você as observa, admira o que fazem bem e absorve o que pode ser útil. Sua inveja, se existe, dura cinco minutos antes de se tornar um plano.' } },
    { name: { es: 'El Equilibrado Emocional', en: 'The Emotionally Balanced', fr: 'L\'Équilibré Émotionnel', de: 'Der Emotional Ausgeglichene', it: 'L\'Equilibrato Emotivo', pt: 'O Equilibrado Emocional' }, dimensions: ['A', 'E'], photo: '/characters/emotional-balance.jpg', description: { es: 'Puede sentir y admitir la envidia sin que lo controle.', en: 'Can feel and admit envy without being controlled by it.', fr: 'Peut ressentir et admettre l\'envie sans qu\'elle le/la contrôle.', de: 'Kann Neid fühlen und zugeben, ohne davon kontrolliert zu werden.', it: 'Può sentire e ammettere l\'invidia senza che lo controlli.', pt: 'Pode sentir e admitir a inveja sem ser controlado por ela.' }, philosophy: { es: 'Eres humano/a: la envidia te visita. Pero tienes la honestidad de reconocerla y la madurez de no dejar que te dirija. La sientes, la nombras y la dejas ir.', en: 'You\'re human: envy visits you. But you have the honesty to acknowledge it and the maturity not to let it direct you. You feel it, name it, and let it go.', fr: 'Tu es humain(e): l\'envie te visite. Mais tu as l\'honnêteté de la reconnaître et la maturité de ne pas la laisser te diriger. Tu la ressens, tu la nommes et tu la laisses partir.', de: 'Du bist menschlich: der Neid besucht dich. Aber du hast die Ehrlichkeit, ihn anzuerkennen, und die Reife, ihn nicht leiten zu lassen. Du fühlst ihn, benennst ihn und lässt ihn los.', it: 'Sei umano/a: l\'invidia ti visita. Ma hai l\'onestà di riconoscerla e la maturità di non lasciarle dirtere. La senti, la nomini e la lasci andare.', pt: 'Você é humano/a: a inveja te visita. Mas você tem a honestidade de reconhecê-la e a maturidade de não deixar que te dirija. Você a sente, a nomeia e a deixa ir.' } },
  ],
};

export async function seedEnvious(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'envious' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'envious',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['dark-personality'],
      sortOrder: 6,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
