import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan maduro/a eres emocionalmente?', en: 'How emotionally mature are you?', fr: 'À quel point es-tu mature émotionnellement ?', de: 'Wie emotional reif bist du?', it: 'Quanto sei emotivamente maturo/a?', pt: 'O quanto você é emocionalmente maduro/a?' },
  description: { es: 'La madurez emocional no tiene que ver con la edad. Tiene que ver con cómo gestionas lo que sientes.', en: 'Emotional maturity has nothing to do with age. It\'s about how you manage what you feel.', fr: 'La maturité émotionnelle n\'a rien à voir avec l\'âge. Il s\'agit de la façon dont tu gères ce que tu ressens.', de: 'Emotionale Reife hat nichts mit dem Alter zu tun. Es geht darum, wie du mit dem umgehst, was du fühlst.', it: 'La maturità emotiva non ha nulla a che fare con l\'età. Riguarda come gestisci ciò che senti.', pt: 'A maturidade emocional não tem a ver com a idade. Tem a ver com como você gerencia o que sente.' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { R: 'Regulación', E: 'Empatía', A: 'Autoconocimiento', C: 'Comunicación' },
    en: { R: 'Regulation', E: 'Empathy', A: 'Self-Knowledge', C: 'Communication' },
    fr: { R: 'Régulation', E: 'Empathie', A: 'Connaissance de Soi', C: 'Communication' },
    de: { R: 'Regulation', E: 'Empathie', A: 'Selbsterkenntnis', C: 'Kommunikation' },
    it: { R: 'Regolazione', E: 'Empatia', A: 'Autoconoscenza', C: 'Comunicazione' },
    pt: { R: 'Regulação', E: 'Empatia', A: 'Autoconhecimento', C: 'Comunicação' },
  },
  questions: [
    { id: 1, situation: { es: 'Alguien que quieres dice algo que te duele sin darse cuenta. ¿Cómo reaccionas?', en: 'Someone you care about says something hurtful without realizing it. How do you react?', fr: 'Quelqu\'un que tu aimes dit quelque chose qui te fait mal sans s\'en rendre compte. Comment réagis-tu ?', de: 'Jemand, den du liebst, sagt etwas Verletzendes, ohne es zu merken. Wie reagierst du?', it: 'Qualcuno che ami dice qualcosa che ti fa male senza rendersene conto. Come reagisci?', pt: 'Alguém que você ama diz algo que te machuca sem perceber. Como você reage?' }, options: [
      { text: { es: 'Dejo pasar. No vale la pena mencionarlo.', en: 'I let it go. It\'s not worth mentioning.', fr: 'Je laisse passer. Ça ne vaut pas la peine d\'en parler.', de: 'Ich lasse es passieren. Es ist nicht der Mühe wert, es zu erwähnen.', it: 'Lascio perdere. Non vale la pena menzionarlo.', pt: 'Deixo passar. Não vale a pena mencionar.' }, dimension: 'R' },
      { text: { es: 'Pienso en por qué lo dijo antes de reaccionar.', en: 'I think about why they said it before reacting.', fr: 'Je pense à pourquoi il/elle l\'a dit avant de réagir.', de: 'Ich denke darüber nach, warum er/sie es gesagt hat, bevor ich reagiere.', it: 'Penso al perché lo ha detto prima di reagire.', pt: 'Penso no por que disse antes de reagir.' }, dimension: 'E' },
      { text: { es: 'Lo noto y me pregunto si hay algo mío que me hace especialmente sensible a eso.', en: 'I notice it and wonder if there\'s something in me that makes me especially sensitive to it.', fr: 'Je le remarque et me demande si quelque chose en moi me rend particulièrement sensible à ça.', de: 'Ich bemerke es und frage mich, ob es etwas in mir gibt, das mich dafür besonders sensibel macht.', it: 'Lo noto e mi chiedo se c\'è qualcosa in me che mi rende particolarmente sensibile a questo.', pt: 'Noto e me pergunto se há algo em mim que me torna especialmente sensível a isso.' }, dimension: 'A' },
      { text: { es: 'En el momento oportuno, le digo que eso me afectó y cómo.', en: 'At the right moment, I tell them it affected me and how.', fr: 'Au bon moment, je lui dis que ça m\'a affecté et comment.', de: 'Zum richtigen Zeitpunkt sage ich ihm/ihr, dass es mich betroffen hat und wie.', it: 'Al momento opportuno, gli dico che questo mi ha colpito e come.', pt: 'No momento oportuno, digo que isso me afetou e como.' }, dimension: 'C' },
    ] },
    { id: 2, situation: { es: 'Estás muy enojado/a. Alguien te provoca más. ¿Qué haces?', en: 'You\'re very angry. Someone provokes you further. What do you do?', fr: 'Tu es très en colère. Quelqu\'un te provoque davantage. Que fais-tu ?', de: 'Du bist sehr wütend. Jemand provoziert dich weiter. Was tust du?', it: 'Sei molto arrabbiato/a. Qualcuno ti provoca ancora. Cosa fai?', pt: 'Você está muito com raiva. Alguém te provoca mais. O que você faz?' }, options: [
      { text: { es: 'Me salgo de la situación o pido tiempo antes de responder.', en: 'I leave the situation or ask for time before responding.', fr: 'Je sors de la situation ou demande du temps avant de répondre.', de: 'Ich verlasse die Situation oder bitte um Zeit, bevor ich antworte.', it: 'Mi allontano dalla situazione o chiedo tempo prima di rispondere.', pt: 'Saio da situação ou peço tempo antes de responder.' }, dimension: 'R' },
      { text: { es: 'Intento entender su perspectiva antes de reaccionar.', en: 'I try to understand their perspective before reacting.', fr: 'J\'essaie de comprendre leur perspective avant de réagir.', de: 'Ich versuche, ihre Perspektive zu verstehen, bevor ich reagiere.', it: 'Cerco di capire la loro prospettiva prima di reagire.', pt: 'Tento entender a perspectiva deles antes de reagir.' }, dimension: 'E' },
      { text: { es: 'Reconozco que estoy al límite y que no puedo responder bien ahora.', en: 'I recognize I\'m at my limit and can\'t respond well right now.', fr: 'Je reconnais que je suis à ma limite et que je ne peux pas bien répondre maintenant.', de: 'Ich erkenne, dass ich an meiner Grenze bin und jetzt nicht gut antworten kann.', it: 'Riconosco che sono al limite e che non posso rispondere bene ora.', pt: 'Reconheço que estou no limite e que não posso responder bem agora.' }, dimension: 'A' },
      { text: { es: 'Le digo que necesito tiempo y que hablamos después.', en: 'I tell them I need time and we\'ll talk later.', fr: 'Je lui dis que j\'ai besoin de temps et que nous parlerons après.', de: 'Ich sage ihm/ihr, dass ich Zeit brauche und wir später reden werden.', it: 'Gli dico che ho bisogno di tempo e che parleremo dopo.', pt: 'Digo que preciso de tempo e que falamos depois.' }, dimension: 'C' },
    ] },
    { id: 3, situation: { es: 'Una persona cercana está pasando por algo difícil y no pide consejo. ¿Qué haces?', en: 'A close person is going through something difficult and doesn\'t ask for advice. What do you do?', fr: 'Une personne proche traverse quelque chose de difficile et ne demande pas de conseil. Que fais-tu ?', de: 'Eine nahestehende Person geht durch etwas Schwieriges und bittet nicht um Rat. Was tust du?', it: 'Una persona vicina sta attraversando qualcosa di difficile e non chiede consigli. Cosa fai?', pt: 'Uma pessoa próxima está passando por algo difícil e não pede conselho. O que você faz?' }, options: [
      { text: { es: 'Estoy presente pero no intervengo más de lo necesario.', en: 'I\'m present but don\'t intervene more than necessary.', fr: 'Je suis présent(e) mais n\'interviens pas plus que nécessaire.', de: 'Ich bin präsent, aber greife nicht mehr als nötig ein.', it: 'Sono presente ma non intervengo più del necessario.', pt: 'Estou presente mas não intervenho mais do que necessário.' }, dimension: 'R' },
      { text: { es: 'Escucho sin interrumpir. Lo que necesita es ser escuchado/a.', en: 'I listen without interrupting. What they need is to be heard.', fr: 'J\'écoute sans interrompre. Ce dont il/elle a besoin c\'est d\'être écouté(e).', de: 'Ich höre ohne Unterbrechung zu. Was sie brauchen, ist gehört zu werden.', it: 'Ascolto senza interrompere. Ciò di cui ha bisogno è essere ascoltato/a.', pt: 'Escuto sem interromper. O que precisa é ser ouvido/a.' }, dimension: 'E' },
      { text: { es: 'Evalúo si mis ganas de dar consejos son por ayudar o por resolver mi incomodidad.', en: 'I evaluate whether my desire to give advice is to help or to resolve my own discomfort.', fr: 'J\'évalue si mes envies de donner des conseils sont pour aider ou pour résoudre mon malaise.', de: 'Ich bewerte, ob mein Wunsch, Ratschläge zu geben, um zu helfen ist oder um mein eigenes Unbehagen zu lösen.', it: 'Valuto se il mio desiderio di dare consigli è per aiutare o per risolvere il mio disagio.', pt: 'Avalio se meu desejo de dar conselhos é para ajudar ou para resolver meu próprio desconforto.' }, dimension: 'A' },
      { text: { es: 'Le pregunto qué tipo de apoyo necesita antes de asumir qué darle.', en: 'I ask what kind of support they need before assuming what to give them.', fr: 'Je lui demande quel type de soutien il/elle a besoin avant d\'assumer ce que lui donner.', de: 'Ich frage, welche Art von Unterstützung sie brauchen, bevor ich annehme, was ihnen zu geben.', it: 'Gli chiedo che tipo di supporto ha bisogno prima di assumere cosa dargli.', pt: 'Pergunto que tipo de apoio precisa antes de presumir o que dar.' }, dimension: 'C' },
    ] },
    { id: 4, situation: { es: 'Cometes un error grande que afecta a otros. ¿Cómo lo manejas?', en: 'You make a big mistake that affects others. How do you handle it?', fr: 'Tu commets une grande erreur qui affecte les autres. Comment tu la gères ?', de: 'Du machst einen großen Fehler, der andere beeinflusst. Wie gehst du damit um?', it: 'Commetti un errore grande che influenza gli altri. Come lo gestisci?', pt: 'Você comete um erro grande que afeta outros. Como você lida?' }, options: [
      { text: { es: 'Lo proceso internamente antes de hablar para no reaccionar desde la culpa.', en: 'I process it internally before speaking so I don\'t react from guilt.', fr: 'Je le traite intérieurement avant de parler pour ne pas réagir depuis la culpabilité.', de: 'Ich verarbeite es innerlich, bevor ich spreche, um nicht aus Schuld zu reagieren.', it: 'Lo processo internamente prima di parlare per non reagire dalla colpa.', pt: 'Processo internamente antes de falar para não reagir a partir da culpa.' }, dimension: 'R' },
      { text: { es: 'Pienso primero en el impacto que tuvo en los demás.', en: 'I think first about the impact it had on others.', fr: 'Je pense d\'abord à l\'impact que ça a eu sur les autres.', de: 'Ich denke zuerst an die Auswirkungen, die es auf andere hatte.', it: 'Penso prima all\'impatto che ha avuto sugli altri.', pt: 'Penso primeiro no impacto que teve nos outros.' }, dimension: 'E' },
      { text: { es: 'Lo reconozco sin dramatismo. Los errores son parte del proceso.', en: 'I acknowledge it without drama. Errors are part of the process.', fr: 'Je le reconnais sans dramatisme. Les erreurs font partie du processus.', de: 'Ich erkenne es ohne Drama an. Fehler sind Teil des Prozesses.', it: 'Lo riconosco senza drammatismi. Gli errori sono parte del processo.', pt: 'Reconheço sem dramatismo. Os erros fazem parte do processo.' }, dimension: 'A' },
      { text: { es: 'Lo reconozco claramente ante quien corresponda y hablo sobre cómo evitarlo.', en: 'I clearly acknowledge it to whoever is appropriate and discuss how to avoid it.', fr: 'Je le reconnais clairement devant qui il convient et je parle de comment l\'éviter.', de: 'Ich erkenne es klar vor der richtigen Person an und spreche darüber, wie man es vermeidet.', it: 'Lo riconosco chiaramente davanti a chi compete e parlo di come evitarlo.', pt: 'Reconheço claramente diante de quem corresponde e falo sobre como evitá-lo.' }, dimension: 'C' },
    ] },
    { id: 5, situation: { es: 'Alguien está emocionalmente angustiado frente a ti. ¿Cómo te afecta?', en: 'Someone is emotionally distressed in front of you. How does it affect you?', fr: 'Quelqu\'un est émotionnellement angoissé devant toi. Comment ça t\'affecte ?', de: 'Jemand ist emotional aufgewühlt vor dir. Wie beeinflusst dich das?', it: 'Qualcuno è emotivamente angosciato di fronte a te. Come ti influenza?', pt: 'Alguém está emocionalmente angustiado na sua frente. Como isso te afeta?' }, options: [
      { text: { es: 'Lo proceso sin que me arrastre su estado emocional.', en: 'I process it without being swept away by their emotional state.', fr: 'Je le traite sans être emporté(e) par son état émotionnel.', de: 'Ich verarbeite es, ohne von seinem/ihrem emotionalen Zustand mitgerissen zu werden.', it: 'Lo processo senza essere travolto/a dal suo stato emotivo.', pt: 'Processo sem ser arrastado/a pelo estado emocional deles.' }, dimension: 'R' },
      { text: { es: 'Siento profundamente lo que siente. A veces demasiado.', en: 'I feel deeply what they feel. Sometimes too deeply.', fr: 'Je ressens profondément ce qu\'il/elle ressent. Parfois trop.', de: 'Ich fühle tief, was er/sie fühlt. Manchmal zu tief.', it: 'Sento profondamente quello che sente. A volte troppo.', pt: 'Sinto profundamente o que ele/ela sente. Às vezes demais.' }, dimension: 'E' },
      { text: { es: 'Noto mis propias reacciones ante el dolor ajeno y las gestiono.', en: 'I notice my own reactions to others\' pain and manage them.', fr: 'Je remarque mes propres réactions face à la douleur des autres et je les gère.', de: 'Ich bemerke meine eigenen Reaktionen auf den Schmerz anderer und verwalte sie.', it: 'Noto le mie proprie reazioni al dolore altrui e le gestisco.', pt: 'Noto minhas próprias reações diante da dor alheia e as gerencio.' }, dimension: 'A' },
      { text: { es: 'Creo un espacio de seguridad y le hago saber que estoy presente.', en: 'I create a safe space and let them know I\'m present.', fr: 'Je crée un espace de sécurité et lui fais savoir que je suis présent(e).', de: 'Ich schaffe einen sicheren Raum und lasse ihn/sie wissen, dass ich präsent bin.', it: 'Creo uno spazio di sicurezza e gli faccio sapere che sono presente.', pt: 'Crio um espaço seguro e faço com que saiba que estou presente.' }, dimension: 'C' },
    ] },
    { id: 6, situation: { es: '¿Cuál es tu relación con la crítica a tu trabajo o a ti mismo/a?', en: 'What is your relationship with criticism of your work or yourself?', fr: 'Quelle est ta relation avec la critique de ton travail ou de toi-même ?', de: 'Wie ist deine Beziehung zur Kritik an deiner Arbeit oder dir selbst?', it: 'Qual è il tuo rapporto con la critica al tuo lavoro o a te stesso/a?', pt: 'Qual é sua relação com a crítica ao seu trabalho ou a você mesmo/a?' }, options: [
      { text: { es: 'Me genera algo pero lo proceso sin que me desestabilice por mucho tiempo.', en: 'It generates something in me but I process it without being destabilized for long.', fr: 'Ça me génère quelque chose mais je le traite sans être déstabilisé(e) trop longtemps.', de: 'Es erzeugt etwas in mir, aber ich verarbeite es, ohne lange destabilisiert zu werden.', it: 'Mi genera qualcosa ma lo processo senza essere destabilizzato/a a lungo.', pt: 'Me gera algo mas processo sem ser desestabilizado/a por muito tempo.' }, dimension: 'R' },
      { text: { es: 'La recibo mejor cuando entiendo desde dónde viene quien la da.', en: 'I receive it better when I understand where it comes from.', fr: 'Je la reçois mieux quand je comprends d\'où vient celui/celle qui la donne.', de: 'Ich nehme sie besser an, wenn ich verstehe, woher derjenige kommt, der sie gibt.', it: 'La ricevo meglio quando capisco da dove viene chi la dà.', pt: 'A recebo melhor quando entendo de onde vem quem a dá.' }, dimension: 'E' },
      { text: { es: 'La evalúo para ver qué es válido y qué es proyección del otro.', en: 'I evaluate it to see what\'s valid and what\'s the other\'s projection.', fr: 'Je l\'évalue pour voir ce qui est valide et ce qui est une projection de l\'autre.', de: 'Ich bewerte sie, um zu sehen, was gültig ist und was die Projektion des anderen ist.', it: 'La valuto per vedere cosa è valido e cosa è proiezione dell\'altro.', pt: 'Avalio para ver o que é válido e o que é projeção do outro.' }, dimension: 'A' },
      { text: { es: 'Pido aclaraciones para entender exactamente qué mejorar.', en: 'I ask for clarifications to understand exactly what to improve.', fr: 'Je demande des clarifications pour comprendre exactement quoi améliorer.', de: 'Ich bitte um Klarstellungen, um genau zu verstehen, was ich verbessern soll.', it: 'Chiedo chiarimenti per capire esattamente cosa migliorare.', pt: 'Peço esclarecimentos para entender exatamente o que melhorar.' }, dimension: 'C' },
    ] },
    { id: 7, situation: { es: 'Una relación importante está en conflicto. ¿Cuál es tu primer impulso?', en: 'An important relationship is in conflict. What\'s your first impulse?', fr: 'Une relation importante est en conflit. Quel est ton premier impulse ?', de: 'Eine wichtige Beziehung ist im Konflikt. Was ist dein erster Impuls?', it: 'Una relazione importante è in conflitto. Qual è il tuo primo impulso?', pt: 'Um relacionamento importante está em conflito. Qual é seu primeiro impulso?' }, options: [
      { text: { es: 'Darme (y darle al otro) tiempo para que las emociones bajen antes de hablar.', en: 'Give myself (and the other) time for emotions to settle before talking.', fr: 'Me donner (et donner à l\'autre) du temps pour que les émotions se calment avant de parler.', de: 'Mir (und dem anderen) Zeit geben, damit sich die Emotionen beruhigen, bevor ich spreche.', it: 'Darmi (e dare all\'altro) tempo perché le emozioni si calmino prima di parlare.', pt: 'Me dar (e dar ao outro) tempo para as emoções baixarem antes de falar.' }, dimension: 'R' },
      { text: { es: 'Intentar entender cómo se siente el otro antes de defender mi posición.', en: 'Try to understand how the other feels before defending my position.', fr: 'Essayer de comprendre comment l\'autre se sent avant de défendre ma position.', de: 'Versuchen zu verstehen, wie sich der andere fühlt, bevor ich meine Position verteidige.', it: 'Cercare di capire come si sente l\'altro prima di difendere la mia posizione.', pt: 'Tentar entender como o outro se sente antes de defender minha posição.' }, dimension: 'E' },
      { text: { es: 'Examinar honestamente mi rol en el conflicto.', en: 'Honestly examine my role in the conflict.', fr: 'Examiner honnêtement mon rôle dans le conflit.', de: 'Meine Rolle im Konflikt ehrlich prüfen.', it: 'Esaminare onestamente il mio ruolo nel conflitto.', pt: 'Examinar honestamente meu papel no conflito.' }, dimension: 'A' },
      { text: { es: 'Proponer un momento y un espacio para hablarlo con calma.', en: 'Propose a moment and space to discuss it calmly.', fr: 'Proposer un moment et un espace pour en parler calmement.', de: 'Einen Moment und Raum vorschlagen, um es ruhig zu besprechen.', it: 'Proporre un momento e uno spazio per parlarne con calma.', pt: 'Propor um momento e espaço para conversar com calma.' }, dimension: 'C' },
    ] },
    { id: 8, situation: { es: '¿Cómo describes tu conciencia emocional interna?', en: 'How do you describe your internal emotional awareness?', fr: 'Comment décris-tu ta conscience émotionnelle interne ?', de: 'Wie beschreibst du dein inneres emotionales Bewusstsein?', it: 'Come descrivi la tua consapevolezza emotiva interna?', pt: 'Como você descreve sua consciência emocional interna?' }, options: [
      { text: { es: 'Puedo sentir las emociones sin que tomen el control de mis acciones.', en: 'I can feel emotions without them taking control of my actions.', fr: 'Je peux ressentir les émotions sans qu\'elles prennent le contrôle de mes actions.', de: 'Ich kann Emotionen fühlen, ohne dass sie die Kontrolle über meine Handlungen übernehmen.', it: 'Posso sentire le emozioni senza che prendano il controllo delle mie azioni.', pt: 'Posso sentir as emoções sem que tomem o controle das minhas ações.' }, dimension: 'R' },
      { text: { es: 'Sintonizo muy fácilmente con las emociones de quienes me rodean.', en: 'I tune in very easily to the emotions of those around me.', fr: 'Je me synchronise très facilement avec les émotions de ceux qui m\'entourent.', de: 'Ich stimme sehr leicht auf die Emotionen der Menschen um mich herum ein.', it: 'Mi sintonizzio molto facilmente con le emozioni di chi mi circonda.', pt: 'Sintonizo muito facilmente com as emoções de quem me rodeia.' }, dimension: 'E' },
      { text: { es: 'Tengo bastante claridad sobre qué siento y por qué.', en: 'I have quite a bit of clarity about what I feel and why.', fr: 'J\'ai beaucoup de clarté sur ce que je ressens et pourquoi.', de: 'Ich habe ziemlich viel Klarheit darüber, was ich fühle und warum.', it: 'Ho abbastanza chiarezza su cosa sento e perché.', pt: 'Tenho bastante clareza sobre o que sinto e por quê.' }, dimension: 'A' },
      { text: { es: 'Soy bueno/a expresando lo que siento de forma que los demás puedan entender.', en: 'I\'m good at expressing what I feel in a way others can understand.', fr: 'Je suis bon(ne) pour exprimer ce que je ressens d\'une façon que les autres peuvent comprendre.', de: 'Ich bin gut darin, das, was ich fühle, auf eine Weise auszudrücken, die andere verstehen können.', it: 'Sono bravo/a a esprimere ciò che sento in un modo che gli altri possono capire.', pt: 'Sou bom/boa em expressar o que sinto de forma que os outros possam entender.' }, dimension: 'C' },
    ] },
    { id: 9, situation: { es: 'Alguien te dice algo que interpretas como agresivo. Después te das cuenta de que no fue intencional.', en: 'Someone says something you interpret as aggressive. Later you realize it wasn\'t intentional.', fr: 'Quelqu\'un te dit quelque chose que tu interprètes comme agressif. Ensuite tu réalises que ce n\'était pas intentionnel.', de: 'Jemand sagt dir etwas, das du als aggressiv interpretierst. Dann merkst du, dass es nicht absichtlich war.', it: 'Qualcuno ti dice qualcosa che interpreti come aggressivo. Poi ti rendi conto che non era intenzionale.', pt: 'Alguém diz algo que você interpreta como agressivo. Depois percebe que não foi intencional.' }, options: [
      { text: { es: 'Bien. No reaccioné en caliente y ahora puedo responder desde el lugar correcto.', en: 'Good. I didn\'t react in the heat of the moment and now I can respond from the right place.', fr: 'Bien. Je n\'ai pas réagi à chaud et maintenant je peux répondre depuis le bon endroit.', de: 'Gut. Ich habe nicht im Eifer reagiert und kann jetzt vom richtigen Ort aus antworten.', it: 'Bene. Non ho reagito a caldo e ora posso rispondere dal posto giusto.', pt: 'Bem. Não reagi no calor do momento e agora posso responder do lugar certo.' }, dimension: 'R' },
      { text: { es: 'Me pongo en su lugar. Seguro tenía su razón para decirlo así.', en: 'I put myself in their place. They surely had their reason for saying it that way.', fr: 'Je me mets à sa place. Il/elle avait sûrement sa raison de le dire ainsi.', de: 'Ich versetze mich in seine/ihre Lage. Er/sie hatte sicher seinen/ihren Grund, es so zu sagen.', it: 'Mi metto nei suoi panni. Di sicuro aveva la sua ragione per dirlo così.', pt: 'Me coloco no lugar deles. Com certeza tinha sua razão para dizer assim.' }, dimension: 'E' },
      { text: { es: 'Me pregunto si mi reacción inicial dice algo sobre algo mío.', en: 'I wonder if my initial reaction says something about something in me.', fr: 'Je me demande si ma réaction initiale dit quelque chose sur quelque chose en moi.', de: 'Ich frage mich, ob meine anfängliche Reaktion etwas über mich selbst aussagt.', it: 'Mi chiedo se la mia reazione iniziale dica qualcosa di mio.', pt: 'Me pergunto se minha reação inicial diz algo sobre mim.' }, dimension: 'A' },
      { text: { es: 'Se lo digo: "Cuando dijiste X, lo escuché de esta manera. Quiero entender qué quisiste decir."', en: 'I tell them: "When you said X, I heard it this way. I want to understand what you meant."', fr: 'Je lui dis : "Quand tu as dit X, je l\'ai entendu de cette façon. Je veux comprendre ce que tu voulais dire."', de: 'Ich sage ihm/ihr: "Als du X sagtest, hörte ich es so. Ich möchte verstehen, was du meintest."', it: 'Glielo dico: "Quando hai detto X, l\'ho sentito in questo modo. Voglio capire cosa intendevi."', pt: 'Digo: "Quando você disse X, ouvi desta forma. Quero entender o que você quis dizer."' }, dimension: 'C' },
    ] },
    { id: 10, situation: { es: '¿Cuál es tu forma favorita de regular emociones difíciles?', en: 'What is your favorite way to regulate difficult emotions?', fr: 'Quelle est ta façon préférée de réguler les émotions difficiles ?', de: 'Wie regulierst du am liebsten schwierige Emotionen?', it: 'Qual è il tuo modo preferito di regolare le emozioni difficili?', pt: 'Qual é sua forma favorita de regular emoções difíceis?' }, options: [
      { text: { es: 'Pausa, movimiento físico, respiración. Herramientas concretas.', en: 'Pause, physical movement, breathing. Concrete tools.', fr: 'Pause, mouvement physique, respiration. Des outils concrets.', de: 'Pause, körperliche Bewegung, Atmung. Konkrete Werkzeuge.', it: 'Pausa, movimento fisico, respirazione. Strumenti concreti.', pt: 'Pausa, movimento físico, respiração. Ferramentas concretas.' }, dimension: 'R' },
      { text: { es: 'Hablar con alguien que me entienda. La conexión me regula.', en: 'Talking with someone who understands me. Connection regulates me.', fr: 'Parler avec quelqu\'un qui me comprend. La connexion me régule.', de: 'Mit jemandem sprechen, der mich versteht. Die Verbindung reguliert mich.', it: 'Parlare con qualcuno che mi capisce. La connessione mi regola.', pt: 'Falar com alguém que me entende. A conexão me regula.' }, dimension: 'E' },
      { text: { es: 'Escribir o reflexionar para entender qué está pasando dentro.', en: 'Writing or reflecting to understand what\'s going on inside.', fr: 'Écrire ou réfléchir pour comprendre ce qui se passe à l\'intérieur.', de: 'Schreiben oder Nachdenken, um zu verstehen, was innen passiert.', it: 'Scrivere o riflettere per capire cosa sta succedendo dentro.', pt: 'Escrever ou refletir para entender o que está acontecendo por dentro.' }, dimension: 'A' },
      { text: { es: 'Expresarlo de alguna forma: escribir, hablar, crear.', en: 'Expressing it somehow: writing, talking, creating.', fr: 'L\'exprimer d\'une façon ou d\'une autre : écrire, parler, créer.', de: 'Es irgendwie ausdrücken: schreiben, reden, schaffen.', it: 'Esprimerlo in qualche modo: scrivere, parlare, creare.', pt: 'Expressá-lo de alguma forma: escrever, falar, criar.' }, dimension: 'C' },
    ] },
  ],
  characters: [
    { name: { es: 'El Regulador Maestro', en: 'The Master Regulator', fr: 'Le Régulateur Maître', de: 'Der Meister-Regulator', it: 'Il Regolatore Maestro', pt: 'O Regulador Mestre' }, dimensions: ['R'], photo: '/characters/emotional-regulator.jpg', description: { es: 'Sus emociones son información, no comandos.', en: 'Their emotions are information, not commands.', fr: 'Ses émotions sont de l\'information, pas des commandes.', de: 'Seine/ihre Emotionen sind Informationen, keine Befehle.', it: 'Le sue emozioni sono informazioni, non comandi.', pt: 'Suas emoções são informações, não comandos.' }, philosophy: { es: 'Has desarrollado la capacidad de sentir sin ser gobernado/a por lo que sientes. Las emociones difíciles te visitan pero no te secuestran. Eso no se aprende de un día para otro — es trabajo real.', en: 'You\'ve developed the ability to feel without being governed by what you feel. Difficult emotions visit you but don\'t kidnap you. That\'s not learned overnight — it\'s real work.', fr: 'Tu as développé la capacité de ressentir sans être gouverné(e) par ce que tu ressens. Les émotions difficiles te rendent visite mais ne te séquestrent pas. Ça ne s\'apprend pas du jour au lendemain — c\'est un vrai travail.', de: 'Du hast die Fähigkeit entwickelt zu fühlen, ohne von dem, was du fühlst, regiert zu werden. Schwierige Emotionen besuchen dich, entführen dich aber nicht. Das lernt man nicht über Nacht — es ist echte Arbeit.', it: 'Hai sviluppato la capacità di sentire senza essere governato/a da ciò che senti. Le emozioni difficili ti visitano ma non ti sequestrano. Non si impara dall\'oggi al domani — è un vero lavoro.', pt: 'Você desenvolveu a capacidade de sentir sem ser governado/a pelo que sente. As emoções difíceis te visitam mas não te sequestram. Isso não se aprende da noite para o dia — é trabalho real.' } },
    { name: { es: 'El Empático Profundo', en: 'The Deep Empath', fr: 'L\'Empathique Profond', de: 'Der Tiefe Empath', it: 'L\'Empatico Profondo', pt: 'O Empático Profundo' }, dimensions: ['E'], photo: '/characters/deep-empath.jpg', description: { es: 'Siente lo que sienten los demás con precisión extraordinaria.', en: 'Feels what others feel with extraordinary precision.', fr: 'Ressent ce que les autres ressentent avec une précision extraordinaire.', de: 'Fühlt, was andere fühlen, mit außerordentlicher Präzision.', it: 'Sente quello che sentono gli altri con precisione straordinaria.', pt: 'Sente o que os outros sentem com precisão extraordinária.' }, philosophy: { es: 'Tu capacidad de sintonizar emocionalmente con los demás es tu mayor regalo en las relaciones. Puedes estar con alguien en su dolor sin necesitar que pare o cambie. Eso es raro y valioso.', en: 'Your ability to emotionally tune in to others is your greatest gift in relationships. You can be with someone in their pain without needing it to stop or change. That is rare and valuable.', fr: 'Ta capacité à te synchroniser émotionnellement avec les autres est ton plus grand don dans les relations. Tu peux être avec quelqu\'un dans sa douleur sans avoir besoin qu\'elle s\'arrête ou change. C\'est rare et précieux.', de: 'Deine Fähigkeit, dich emotional auf andere einzustimmen, ist dein größtes Geschenk in Beziehungen. Du kannst mit jemandem in seinem Schmerz sein, ohne dass er aufhören oder sich ändern muss. Das ist selten und wertvoll.', it: 'La tua capacità di sintonizzarti emotivamente con gli altri è il tuo più grande dono nelle relazioni. Puoi stare con qualcuno nel suo dolore senza aver bisogno che si fermi o cambi. È raro e prezioso.', pt: 'Sua capacidade de se sintonizar emocionalmente com os outros é seu maior presente nas relações. Você pode estar com alguém na dor sem precisar que pare ou mude. Isso é raro e valioso.' } },
    { name: { es: 'El Autoconocido', en: 'The Self-Knowing', fr: 'Le Connaissance de Soi', de: 'Der Sich-Selbst-Kennende', it: 'Il Autoconoscitore', pt: 'O Autoconhecido' }, dimensions: ['A'], photo: '/characters/self-knowing.jpg', description: { es: 'Se conoce bien. Sabe de dónde vienen sus reacciones.', en: 'Knows themselves well. Knows where their reactions come from.', fr: 'Se connaît bien. Sait d\'où viennent ses réactions.', de: 'Kennt sich gut. Weiß, woher seine/ihre Reaktionen kommen.', it: 'Si conosce bene. Sa da dove vengono le sue reazioni.', pt: 'Se conhece bem. Sabe de onde vêm suas reações.' }, philosophy: { es: 'Tienes un mapa bastante claro de tu mundo emocional interno. Sabes qué te activa, por qué, de dónde viene. Ese conocimiento no elimina las reacciones, pero te da un segundo más de espacio para elegir.', en: 'You have a fairly clear map of your internal emotional world. You know what activates you, why, where it comes from. That knowledge doesn\'t eliminate reactions, but it gives you one more second of space to choose.', fr: 'Tu as une carte assez claire de ton monde émotionnel interne. Tu sais ce qui t\'active, pourquoi, d\'où ça vient. Cette connaissance n\'élimine pas les réactions, mais te donne une seconde de plus pour choisir.', de: 'Du hast eine ziemlich klare Karte deiner inneren emotionalen Welt. Du weißt, was dich aktiviert, warum, woher es kommt. Dieses Wissen beseitigt keine Reaktionen, gibt dir aber eine weitere Sekunde Raum zum Wählen.', it: 'Hai una mappa abbastanza chiara del tuo mondo emotivo interno. Sai cosa ti attiva, perché, da dove viene. Quella conoscenza non elimina le reazioni, ma ti dà un secondo in più di spazio per scegliere.', pt: 'Você tem um mapa bastante claro do seu mundo emocional interno. Sabe o que te ativa, por quê, de onde vem. Esse conhecimento não elimina as reações, mas te dá um segundo a mais de espaço para escolher.' } },
    { name: { es: 'El Comunicador Emocional', en: 'The Emotional Communicator', fr: 'Le Communicateur Émotionnel', de: 'Der Emotionale Kommunikator', it: 'Il Comunicatore Emotivo', pt: 'O Comunicador Emocional' }, dimensions: ['C'], photo: '/characters/emotional-communicator.jpg', description: { es: 'Expresa lo que siente de forma que los demás pueden recibir.', en: 'Expresses what they feel in a way others can receive.', fr: 'Exprime ce qu\'il/elle ressent d\'une façon que les autres peuvent recevoir.', de: 'Drückt das, was er/sie fühlt, auf eine Weise aus, die andere empfangen können.', it: 'Esprime ciò che sente in un modo che gli altri possono ricevere.', pt: 'Expressa o que sente de forma que os outros podem receber.' }, philosophy: { es: 'Has aprendido uno de los idiomas más difíciles: cómo decir lo que sientes de forma que el otro pueda escucharlo. Eso requiere claridad interior y cuidado exterior al mismo tiempo.', en: 'You\'ve learned one of the hardest languages: how to say what you feel in a way the other can hear. That requires inner clarity and outer care at the same time.', fr: 'Tu as appris l\'un des langages les plus difficiles : comment dire ce que tu ressens d\'une façon que l\'autre peut entendre. Ça nécessite de la clarté intérieure et du soin extérieur en même temps.', de: 'Du hast eine der schwierigsten Sprachen gelernt: wie man sagt, was man fühlt, auf eine Weise, die der andere hören kann. Das erfordert gleichzeitig innere Klarheit und äußere Fürsorge.', it: 'Hai imparato uno dei linguaggi più difficili: come dire ciò che senti in un modo che l\'altro possa ascoltarlo. Questo richiede chiarezza interiore e cura esteriore allo stesso tempo.', pt: 'Você aprendeu um dos idiomas mais difíceis: como dizer o que sente de forma que o outro possa ouvir. Isso requer clareza interior e cuidado exterior ao mesmo tempo.' } },
    { name: { es: 'El Maduro Equilibrado', en: 'The Mature Balanced', fr: 'Le Mûr Équilibré', de: 'Der Reife Ausgeglichene', it: 'Il Maturo Equilibrato', pt: 'O Maduro Equilibrado' }, dimensions: ['R', 'A'], photo: '/characters/mature-balanced.jpg', description: { es: 'Se conoce y se regula. Una combinación poderosa.', en: 'Knows themselves and regulates. A powerful combination.', fr: 'Se connaît et se régule. Une combinaison puissante.', de: 'Kennt sich und reguliert sich. Eine kraftvolle Kombination.', it: 'Si conosce e si regola. Una combinazione potente.', pt: 'Se conhece e se regula. Uma combinação poderosa.' }, philosophy: { es: 'Sabes de dónde vienen tus emociones y tienes herramientas para gestionarlas. No siempre perfectamente, pero consistentemente. Eso es lo que distingue a las personas emocionalmente maduras.', en: 'You know where your emotions come from and have tools to manage them. Not always perfectly, but consistently. That\'s what distinguishes emotionally mature people.', fr: 'Tu sais d\'où viennent tes émotions et tu as des outils pour les gérer. Pas toujours parfaitement, mais régulièrement. C\'est ce qui distingue les personnes émotionnellement matures.', de: 'Du weißt, woher deine Emotionen kommen, und hast Werkzeuge, um sie zu managen. Nicht immer perfekt, aber konsequent. Das unterscheidet emotional reife Menschen.', it: 'Sai da dove vengono le tue emozioni e hai strumenti per gestirle. Non sempre perfettamente, ma costantemente. Questo è ciò che distingue le persone emotivamente mature.', pt: 'Você sabe de onde vêm suas emoções e tem ferramentas para gerenciá-las. Nem sempre perfeitamente, mas consistentemente. É isso que distingue as pessoas emocionalmente maduras.' } },
    { name: { es: 'La Presencia Empática', en: 'The Empathic Presence', fr: 'La Présence Empathique', de: 'Die Empathische Präsenz', it: 'La Presenza Empatica', pt: 'A Presença Empática' }, dimensions: ['E', 'C'], photo: '/characters/empathic-presence.jpg', description: { es: 'Siente lo del otro y sabe cómo acompañar.', en: 'Feels what the other feels and knows how to accompany them.', fr: 'Ressent ce que l\'autre ressent et sait comment accompagner.', de: 'Fühlt, was der andere fühlt, und weiß, wie man begleitet.', it: 'Sente quello dell\'altro e sa come accompagnare.', pt: 'Sente o que o outro sente e sabe como acompanhar.' }, philosophy: { es: 'Tienes el don de la empatía y la habilidad de expresar esa presencia de forma que el otro la recibe. Eso crea relaciones de una profundidad que pocas personas experimentan.', en: 'You have the gift of empathy and the ability to express that presence in a way the other receives it. That creates relationships of a depth few people experience.', fr: 'Tu as le don de l\'empathie et la capacité d\'exprimer cette présence d\'une façon que l\'autre reçoit. Ça crée des relations d\'une profondeur que peu de gens expérimentent.', de: 'Du hast das Geschenk der Empathie und die Fähigkeit, diese Präsenz auf eine Weise auszudrücken, die der andere empfängt. Das schafft Beziehungen von einer Tiefe, die nur wenige Menschen erleben.', it: 'Hai il dono dell\'empatia e la capacità di esprimere quella presenza in un modo che l\'altro riceve. Questo crea relazioni di una profondità che poche persone sperimentano.', pt: 'Você tem o dom da empatia e a habilidade de expressar essa presença de forma que o outro recebe. Isso cria relacionamentos de uma profundidade que poucas pessoas experimentam.' } },
    { name: { es: 'El Inteligente Emocional', en: 'The Emotionally Intelligent', fr: 'L\'Intelligent Émotionnel', de: 'Der Emotional Intelligente', it: 'L\'Intelligente Emotivo', pt: 'O Inteligente Emocional' }, dimensions: ['A', 'C'], photo: '/characters/emotional-intelligence.jpg', description: { es: 'Se conoce y lo comunica. Lo que la mayoría llama IE.', en: 'Knows themselves and communicates it. What most call EI.', fr: 'Se connaît et le communique. Ce que la plupart appelle IE.', de: 'Kennt sich und kommuniziert es. Was die meisten EI nennen.', it: 'Si conosce e lo comunica. Quello che la maggior parte chiama IE.', pt: 'Se conhece e comunica. O que a maioria chama de IE.' }, philosophy: { es: 'Tienes claridad interior y puedes traducirla al exterior. Sabes qué sientes, por qué lo sientes y cómo expresarlo de forma que genera conexión en lugar de distancia.', en: 'You have inner clarity and can translate it to the outside. You know what you feel, why you feel it, and how to express it in a way that generates connection rather than distance.', fr: 'Tu as de la clarté intérieure et tu peux la traduire à l\'extérieur. Tu sais ce que tu ressens, pourquoi tu le ressens et comment l\'exprimer d\'une façon qui génère de la connexion plutôt que de la distance.', de: 'Du hast innere Klarheit und kannst sie nach außen übersetzen. Du weißt, was du fühlst, warum du es fühlst und wie du es auf eine Weise ausdrückst, die Verbindung statt Distanz erzeugt.', it: 'Hai chiarezza interiore e puoi tradurla all\'esterno. Sai cosa senti, perché lo senti e come esprimerlo in un modo che genera connessione invece che distanza.', pt: 'Você tem clareza interior e pode traduzi-la para o exterior. Sabe o que sente, por que sente e como expressar de forma que gera conexão em vez de distância.' } },
    { name: { es: 'El Adulto Emocional', en: 'The Emotional Adult', fr: 'L\'Adulte Émotionnel', de: 'Der Emotionale Erwachsene', it: 'L\'Adulto Emotivo', pt: 'O Adulto Emocional' }, dimensions: ['R', 'E', 'C'], photo: '/characters/emotional-adult.jpg', description: { es: 'Todo lo anterior junto. El adulto emocional pleno.', en: 'All of the above together. The fully emotional adult.', fr: 'Tout ce qui précède ensemble. L\'adulte émotionnel complet.', de: 'Alles oben zusammen. Der vollständige emotionale Erwachsene.', it: 'Tutto quanto precedente insieme. L\'adulto emotivo pieno.', pt: 'Tudo o anterior junto. O adulto emocional pleno.' }, philosophy: { es: 'Regulación, empatía y comunicación integradas. No eres perfecto/a — pero tienes la capacidad de volver al equilibrio rápidamente, de entender a los demás y de expresarte de forma que conecta. Eso es madurez emocional real.', en: 'Regulation, empathy, and communication integrated. You\'re not perfect — but you have the ability to return to balance quickly, to understand others, and to express yourself in a way that connects. That is real emotional maturity.', fr: 'Régulation, empathie et communication intégrées. Tu n\'es pas parfait(e) — mais tu as la capacité de revenir à l\'équilibre rapidement, de comprendre les autres et de t\'exprimer d\'une façon qui connecte. C\'est la vraie maturité émotionnelle.', de: 'Regulation, Empathie und Kommunikation integriert. Du bist nicht perfekt — aber du hast die Fähigkeit, schnell zum Gleichgewicht zurückzukehren, andere zu verstehen und dich auf eine Weise auszudrücken, die verbindet. Das ist echte emotionale Reife.', it: 'Regolazione, empatia e comunicazione integrate. Non sei perfetto/a — ma hai la capacità di tornare all\'equilibrio rapidamente, di capire gli altri e di esprimerti in un modo che connette. Questa è la vera maturità emotiva.', pt: 'Regulação, empatia e comunicação integradas. Você não é perfeito/a — mas tem a capacidade de voltar ao equilíbrio rapidamente, de entender os outros e de se expressar de forma que conecta. Isso é maturidade emocional real.' } },
  ],
};

export async function seedEmotionallyMature(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'emotionally-mature' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'emotionally-mature',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['life'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
