import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Guardas secretos o los cuentas?', en: 'Do you keep secrets or tell them?', fr: 'Gardes-tu les secrets ou les racontes-tu ?', de: 'Bewahrst du Geheimnisse oder verrätst du sie?', it: 'Tieni i segreti o li racconti?', pt: 'Você guarda segredos ou os conta?' },
  description: { es: 'Un secreto compartido es un secreto a medias. ¿Cuál es tu verdad?', en: 'A shared secret is half a secret. What\'s your truth?', fr: 'Un secret partagé est un secret à moitié. Quelle est ta vérité ?', de: 'Ein geteiltes Geheimnis ist ein halbes Geheimnis. Was ist deine Wahrheit?', it: 'Un segreto condiviso è un segreto a metà. Qual è la tua verità?', pt: 'Um segredo compartilhado é um segredo pela metade. Qual é a sua verdade?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { G: 'Guardián', C: 'Contador', S: 'Selectivo', T: 'Transparente' },
    en: { G: 'Guardian', C: 'Teller', S: 'Selective', T: 'Transparent' },
    fr: { G: 'Gardien', C: 'Narrateur', S: 'Sélectif', T: 'Transparent' },
    de: { G: 'Hüter', C: 'Erzähler', S: 'Selektiv', T: 'Transparent' },
    it: { G: 'Guardiano', C: 'Narratore', S: 'Selettivo', T: 'Trasparente' },
    pt: { G: 'Guardião', C: 'Contador', S: 'Seletivo', T: 'Transparente' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu mejor amigo/a te cuenta algo muy privado y te pide que no se lo digas a nadie. ¿Qué pasa a los tres días?', en: 'Your best friend tells you something very private and asks you not to tell anyone. What happens after three days?', fr: 'Ton/ta meilleur(e) ami(e) te raconte quelque chose de très privé et te demande de ne le dire à personne. Que se passe-t-il après trois jours ?', de: 'Dein bester Freund/deine beste Freundin erzählt dir etwas sehr Privates und bittet dich, es niemandem zu sagen. Was passiert nach drei Tagen?', it: 'Il tuo migliore amico/a ti racconta qualcosa di molto privato e ti chiede di non dirlo a nessuno. Cosa succede dopo tre giorni?', pt: 'Seu/sua melhor amigo/a te conta algo muito privado e pede que não diga a ninguém. O que acontece depois de três dias?' }, options: [
      { text: { es: 'El secreto sigue completamente guardado. No lo menciono ni en forma de insinuación.', en: 'The secret is still completely kept. I don\'t mention it even as a hint.', fr: 'Le secret est toujours complètement gardé. Je ne le mentionne même pas sous forme d\'allusion.', de: 'Das Geheimnis ist noch vollständig bewahrt. Ich erwähne es noch nicht einmal als Andeutung.', it: 'Il segreto è ancora completamente custodito. Non lo menziono nemmeno sotto forma di allusione.', pt: 'O segredo continua completamente guardado. Não o menciono nem na forma de insinuação.' }, dimension: 'G' },
      { text: { es: 'Se lo conté a mi pareja. Ella/él no cuenta, así que es casi lo mismo que guardarlo.', en: 'I told my partner. They don\'t tell, so it\'s almost the same as keeping it.', fr: 'Je l\'ai dit à mon/ma partenaire. Il/elle ne le raconte pas, donc c\'est presque la même chose que le garder.', de: 'Ich habe es meinem Partner/meiner Partnerin erzählt. Er/sie erzählt es nicht weiter, also ist es fast dasselbe wie es zu bewahren.', it: 'L\'ho detto al mio partner. Lui/lei non lo racconta, quindi è quasi come custodirlo.', pt: 'Contei ao meu parceiro/a. Ele/ela não conta, então é quase a mesma coisa que guardar.' }, dimension: 'C' },
      { text: { es: 'Se lo conté a una sola persona de absoluta confianza que no tiene relación con mi amigo.', en: 'I told one absolutely trusted person who has no connection to my friend.', fr: 'Je l\'ai dit à une seule personne de confiance absolue qui n\'a aucun rapport avec mon ami.', de: 'Ich habe es einer einzigen absolut vertrauenswürdigen Person erzählt, die keine Verbindung zu meinem Freund hat.', it: 'L\'ho detto a una sola persona di assoluta fiducia che non ha relazione con il mio amico.', pt: 'Contei a uma única pessoa de absoluta confiança que não tem relação com meu amigo.' }, dimension: 'S' },
      { text: { es: 'No lo conté, pero cambié mi comportamiento de formas que quizás generan preguntas.', en: 'I didn\'t tell it, but I changed my behavior in ways that might generate questions.', fr: 'Je ne l\'ai pas dit, mais j\'ai changé mon comportement de façons qui génèrent peut-être des questions.', de: 'Ich habe es nicht erzählt, aber ich habe mein Verhalten auf eine Weise geändert, die vielleicht Fragen aufwirft.', it: 'Non l\'ho detto, ma ho cambiato il mio comportamento in modi che forse generano domande.', pt: 'Não contei, mas mudei meu comportamento de formas que talvez gerem perguntas.' }, dimension: 'T' },
    ] },
    { id: 2, situation: { es: 'Alguien te pide un secreto en confianza que claramente te genera presión social mantenerlo.', en: 'Someone entrusts you with a secret that clearly creates social pressure to keep it.', fr: 'Quelqu\'un te confie un secret qui te génère clairement de la pression sociale à le garder.', de: 'Jemand vertraut dir ein Geheimnis an, das offensichtlich sozialen Druck erzeugt, es zu bewahren.', it: 'Qualcuno ti affida un segreto in confidenza che chiaramente ti genera pressione sociale a mantenerlo.', pt: 'Alguém te confia um segredo que claramente te gera pressão social para mantê-lo.' }, options: [
      { text: { es: 'Lo guardo de todas formas. Me comprometí.', en: 'I keep it anyway. I committed.', fr: 'Je le garde quand même. Je me suis engagé(e).', de: 'Ich bewahre es trotzdem. Ich habe mich verpflichtet.', it: 'Lo custodisco comunque. Mi sono impegnato/a.', pt: 'Guardo de qualquer forma. Me comprometi.' }, dimension: 'G' },
      { text: { es: 'En algún momento necesito procesarlo con alguien. No puedo con todo solo/a.', en: 'At some point I need to process it with someone. I can\'t handle everything alone.', fr: 'À un moment donné, j\'ai besoin de le traiter avec quelqu\'un. Je ne peux pas tout gérer seul(e).', de: 'Irgendwann muss ich es mit jemandem verarbeiten. Ich kann nicht alles alleine bewältigen.', it: 'Ad un certo punto ho bisogno di elaborarlo con qualcuno. Non posso farcela da solo/a con tutto.', pt: 'Em algum momento preciso processá-lo com alguém. Não consigo com tudo sozinho/a.' }, dimension: 'C' },
      { text: { es: 'Antes de comprometerme, le digo que no siempre puedo garantizar guardar todo.', en: 'Before committing, I tell them I can\'t always guarantee keeping everything.', fr: 'Avant de m\'engager, je lui dis que je ne peux pas toujours garantir de tout garder.', de: 'Bevor ich mich verpflichte, sage ich ihm/ihr, dass ich nicht immer garantieren kann, alles zu bewahren.', it: 'Prima di impegnarmi, dico che non posso sempre garantire di mantenere tutto.', pt: 'Antes de me comprometer, digo que nem sempre posso garantir guardar tudo.' }, dimension: 'T' },
      { text: { es: 'Lo guardo en general, pero me reservo el derecho de contarlo si cambian las circunstancias.', en: 'I keep it in general, but reserve the right to tell it if circumstances change.', fr: 'Je le garde en général, mais je me réserve le droit de le dire si les circonstances changent.', de: 'Ich bewahre es im Allgemeinen, behalte mir aber das Recht vor, es zu erzählen, wenn sich die Umstände ändern.', it: 'Lo custodisco in generale, ma mi riservo il diritto di raccontarlo se cambiano le circostanze.', pt: 'Guardo em geral, mas me reservo o direito de contá-lo se as circunstâncias mudarem.' }, dimension: 'S' },
    ] },
    { id: 3, situation: { es: 'Sabes algo de alguien famoso (o influyente en tu círculo) que cambiaría la percepción que todos tienen de esa persona.', en: 'You know something about someone famous (or influential in your circle) that would change everyone\'s perception of that person.', fr: 'Tu sais quelque chose sur quelqu\'un de célèbre (ou influent dans ton cercle) qui changerait la perception que tout le monde a de cette personne.', de: 'Du weißt etwas über jemanden Berühmten (oder Einflussreichen in deinem Kreis), das die Wahrnehmung aller über diese Person verändern würde.', it: 'Sai qualcosa di qualcuno famoso (o influente nel tuo cerchio) che cambierebbe la percezione che tutti hanno di quella persona.', pt: 'Você sabe algo de alguém famoso (ou influente em seu círculo) que mudaria a percepção que todos têm dessa pessoa.' }, options: [
      { text: { es: 'No lo digo. No es mío para contar.', en: 'I don\'t say it. It\'s not mine to tell.', fr: 'Je ne le dis pas. Ce n\'est pas le mien à raconter.', de: 'Ich sage es nicht. Es ist nicht meine Geschichte, sie zu erzählen.', it: 'Non lo dico. Non è mio da raccontare.', pt: 'Não digo. Não é meu para contar.' }, dimension: 'G' },
      { text: { es: 'Se lo insinúo a las personas más cercanas. Solo para que tengan el contexto.', en: 'I hint at it to the closest people. Just so they have the context.', fr: 'Je le suggère aux personnes les plus proches. Juste pour qu\'elles aient le contexte.', de: 'Ich deute es den nächsten Personen an. Nur damit sie den Kontext haben.', it: 'Lo accenno alle persone più vicine. Solo per dargli il contesto.', pt: 'Insinuo às pessoas mais próximas. Apenas para que tenham o contexto.' }, dimension: 'C' },
      { text: { es: 'Lo evalúo: ¿cambiaría algo importante que afecte a otras personas? Si no, me callo.', en: 'I evaluate it: would it change something important that affects other people? If not, I stay quiet.', fr: 'Je l\'évalue : est-ce que ça changerait quelque chose d\'important qui affecte d\'autres personnes ? Si non, je me tais.', de: 'Ich bewerte es: Würde es etwas Wichtiges ändern, das andere Menschen betrifft? Wenn nicht, schweige ich.', it: 'Lo valuto: cambierebbe qualcosa di importante che riguarda altre persone? Se no, taccio.', pt: 'Avalio: mudaria algo importante que afeta outras pessoas? Se não, me calo.' }, dimension: 'S' },
      { text: { es: 'Si me preguntan directamente, no voy a mentir.', en: 'If asked directly, I won\'t lie.', fr: 'Si on me le demande directement, je ne vais pas mentir.', de: 'Wenn ich direkt gefragt werde, werde ich nicht lügen.', it: 'Se mi chiedono direttamente, non mentirò.', pt: 'Se me perguntarem diretamente, não vou mentir.' }, dimension: 'T' },
    ] },
    { id: 4, situation: { es: 'Estás en una conversación grupal y alguien menciona un tema relacionado con un secreto que guardas. ¿Cómo reaccionas?', en: 'You\'re in a group conversation and someone mentions a topic related to a secret you keep. How do you react?', fr: 'Tu es dans une conversation de groupe et quelqu\'un mentionne un sujet lié à un secret que tu gardes. Comment réagis-tu ?', de: 'Du bist in einem Gruppengespräch und jemand erwähnt ein Thema, das mit einem Geheimnis zusammenhängt, das du bewahrst. Wie reagierst du?', it: 'Sei in una conversazione di gruppo e qualcuno menziona un argomento legato a un segreto che custodisci. Come reagisci?', pt: 'Você está em uma conversa em grupo e alguém menciona um assunto relacionado a um segredo que guarda. Como você reage?' }, options: [
      { text: { es: 'Cambio el tema sutilmente. No doy ni la mínima señal.', en: 'I subtly change the topic. I don\'t give even the slightest signal.', fr: 'Je change subtilement de sujet. Je ne donne pas le moindre signal.', de: 'Ich wechsle subtil das Thema. Ich gebe nicht einmal das kleinste Signal.', it: 'Cambio subito argomento. Non do nemmeno il minimo segnale.', pt: 'Mudo sutilmente o assunto. Não dou nem o mínimo sinal.' }, dimension: 'G' },
      { text: { es: 'Hago una referencia vaga que solo los iniciados entenderían.', en: 'I make a vague reference that only the initiated would understand.', fr: 'Je fais une référence vague que seuls les initiés comprendraient.', de: 'Ich mache eine vage Anspielung, die nur Eingeweihte verstehen würden.', it: 'Faccio un riferimento vago che solo gli iniziati capirebbero.', pt: 'Faço uma referência vaga que só os iniciados entenderiam.' }, dimension: 'C' },
      { text: { es: 'Me mantengo neutral. No confirmo ni niego.', en: 'I stay neutral. I neither confirm nor deny.', fr: 'Je reste neutre. Je ne confirme ni ne nie.', de: 'Ich bleibe neutral. Ich bestätige weder noch verneine ich.', it: 'Rimango neutrale. Non confermo né nego.', pt: 'Me mantenho neutro/a. Não confirmo nem nego.' }, dimension: 'S' },
      { text: { es: 'Me cuesta mucho no dar información adicional cuando el tema es relevante.', en: 'It\'s very hard for me not to give additional information when the topic is relevant.', fr: 'Il m\'est très difficile de ne pas donner d\'informations supplémentaires quand le sujet est pertinent.', de: 'Es fällt mir sehr schwer, keine zusätzlichen Informationen zu geben, wenn das Thema relevant ist.', it: 'Mi costa molto non dare informazioni aggiuntive quando il tema è rilevante.', pt: 'Me custa muito não dar informações adicionais quando o assunto é relevante.' }, dimension: 'T' },
    ] },
    { id: 5, situation: { es: 'Tu pareja te pregunta directamente sobre algo de lo que sabes un secreto relevante.', en: 'Your partner asks you directly about something you know a relevant secret about.', fr: 'Ton/ta partenaire te demande directement quelque chose dont tu connais un secret pertinent.', de: 'Dein Partner/deine Partnerin fragt dich direkt nach etwas, über das du ein relevantes Geheimnis kennst.', it: 'Il tuo partner ti chiede direttamente di qualcosa di cui conosci un segreto rilevante.', pt: 'Seu parceiro/a te pergunta diretamente sobre algo do qual você conhece um segredo relevante.' }, options: [
      { text: { es: 'Le digo que hay cosas que no me corresponde contar y que confíe en mí.', en: 'I tell them there are things that aren\'t mine to tell and to trust me.', fr: 'Je lui dis qu\'il y a des choses qui ne me reviennent pas à raconter et de me faire confiance.', de: 'Ich sage ihm/ihr, dass es Dinge gibt, die ich nicht zu erzählen habe, und dass er/sie mir vertrauen soll.', it: 'Dico che ci sono cose che non mi spetta raccontare e che si fidi di me.', pt: 'Digo que há coisas que não me cabe contar e que confie em mim.' }, dimension: 'G' },
      { text: { es: 'Termino contándole. No puedo ocultarle cosas a mi pareja.', en: 'I end up telling them. I can\'t hide things from my partner.', fr: 'Je finis par le/la lui dire. Je ne peux pas lui cacher des choses.', de: 'Ich erzähle es ihm/ihr am Ende. Ich kann meinem Partner/meiner Partnerin nichts verbergen.', it: 'Finisco per dirglielo. Non posso nascondere cose al mio partner.', pt: 'Acabo contando. Não consigo esconder coisas do meu parceiro/a.' }, dimension: 'C' },
      { text: { es: 'Evalúo si el secreto afecta directamente a nuestra relación. Si no, no lo cuento.', en: 'I evaluate if the secret directly affects our relationship. If not, I don\'t tell.', fr: 'J\'évalue si le secret affecte directement notre relation. Si non, je ne le dis pas.', de: 'Ich bewerte, ob das Geheimnis unsere Beziehung direkt betrifft. Wenn nicht, erzähle ich es nicht.', it: 'Valuto se il segreto riguarda direttamente la nostra relazione. Se no, non lo racconto.', pt: 'Avalio se o segredo afeta diretamente nosso relacionamento. Se não, não conto.' }, dimension: 'S' },
      { text: { es: 'Le digo que hay algo pero que no puedo contarlo. Al menos así soy honesto/a.', en: 'I tell them there\'s something but I can\'t tell it. At least I\'m honest that way.', fr: 'Je lui dis qu\'il y a quelque chose mais que je ne peux pas le dire. Au moins ainsi je suis honnête.', de: 'Ich sage ihm/ihr, dass es etwas gibt, aber dass ich es nicht erzählen kann. Zumindest bin ich so ehrlich.', it: 'Dico che c\'è qualcosa ma che non posso raccontarlo. Almeno così sono onesto/a.', pt: 'Digo que há algo mas que não posso contar. Pelo menos assim sou honesto/a.' }, dimension: 'T' },
    ] },
    { id: 6, situation: { es: 'Años después, el secreto que guardas ya no tiene consecuencias si se revela. ¿Qué haces?', en: 'Years later, the secret you keep no longer has consequences if revealed. What do you do?', fr: 'Des années plus tard, le secret que tu gardes n\'a plus de conséquences s\'il est révélé. Que fais-tu ?', de: 'Jahre später hat das Geheimnis, das du bewahrst, keine Konsequenzen mehr, wenn es enthüllt wird. Was tust du?', it: 'Anni dopo, il segreto che custodisci non ha più conseguenze se rivelato. Cosa fai?', pt: 'Anos depois, o segredo que guarda não tem mais consequências se revelado. O que você faz?' }, options: [
      { text: { es: 'Sigue guardado. Un secreto confiado no tiene fecha de vencimiento.', en: 'It stays kept. An entrusted secret has no expiration date.', fr: 'Il reste gardé. Un secret confié n\'a pas de date d\'expiration.', de: 'Es bleibt bewahrt. Ein anvertrautes Geheimnis hat kein Verfallsdatum.', it: 'Rimane custodito. Un segreto affidato non ha data di scadenza.', pt: 'Continua guardado. Um segredo confiado não tem data de validade.' }, dimension: 'G' },
      { text: { es: 'En alguna conversación o contexto apropiado podría salir. Ya no importa tanto.', en: 'In some conversation or appropriate context it might come out. It doesn\'t matter as much anymore.', fr: 'Dans une conversation ou un contexte approprié, ça pourrait sortir. Ça n\'a plus autant d\'importance.', de: 'In einem Gespräch oder einem geeigneten Kontext könnte es herauskommen. Es spielt nicht mehr so viel Rolle.', it: 'In qualche conversazione o contesto appropriato potrebbe venire fuori. Non importa più tanto.', pt: 'Em alguma conversa ou contexto apropriado poderia sair. Não importa mais tanto.' }, dimension: 'C' },
      { text: { es: 'Solo si la persona que me lo confió me da permiso implícito o explícito.', en: 'Only if the person who entrusted it to me gives implicit or explicit permission.', fr: 'Seulement si la personne qui me l\'a confié me donne une permission implicite ou explicite.', de: 'Nur wenn die Person, die es mir anvertraut hat, mir implizit oder explizit die Erlaubnis gibt.', it: 'Solo se la persona che me l\'ha affidato mi dà il permesso implicito o esplicito.', pt: 'Somente se a pessoa que me confiou der permissão implícita ou explícita.' }, dimension: 'S' },
      { text: { es: 'Si alguien me pregunta y ya no hay daño posible, lo cuento. No veo razón para seguir ocultándolo.', en: 'If someone asks and there\'s no longer possible harm, I tell it. I don\'t see a reason to keep hiding it.', fr: 'Si quelqu\'un me demande et qu\'il n\'y a plus de dommage possible, je le dis. Je ne vois pas de raison de continuer à le cacher.', de: 'Wenn jemand fragt und es keinen möglichen Schaden mehr gibt, erzähle ich es. Ich sehe keinen Grund, es weiter zu verbergen.', it: 'Se qualcuno me lo chiede e non c\'è più possibile danno, lo racconto. Non vedo ragione per continuare a nasconderlo.', pt: 'Se alguém me perguntar e não há mais dano possível, conto. Não vejo razão para continuar escondendo.' }, dimension: 'T' },
    ] },
    { id: 7, situation: { es: '¿Cuándo crees que está justificado romper la confidencialidad de un secreto?', en: 'When do you think it\'s justified to break the confidentiality of a secret?', fr: 'Quand penses-tu qu\'il est justifié de briser la confidentialité d\'un secret ?', de: 'Wann glaubst du, ist es gerechtfertigt, die Vertraulichkeit eines Geheimnisses zu brechen?', it: 'Quando pensi sia giustificato rompere la confidenzialità di un segreto?', pt: 'Quando você acha que é justificado quebrar a confidencialidade de um segredo?' }, options: [
      { text: { es: 'Casi nunca. Si alguien confió en mí, eso es sagrado salvo riesgo físico evidente.', en: 'Almost never. If someone trusted me, that\'s sacred except in obvious physical risk.', fr: 'Presque jamais. Si quelqu\'un m\'a fait confiance, c\'est sacré sauf en cas de risque physique évident.', de: 'Fast nie. Wenn jemand mir vertraut hat, ist das heilig, außer bei offensichtlichem physischem Risiko.', it: 'Quasi mai. Se qualcuno si è fidato di me, è sacro tranne in caso di evidente rischio fisico.', pt: 'Quase nunca. Se alguém confiou em mim, isso é sagrado exceto por risco físico evidente.' }, dimension: 'G' },
      { text: { es: 'Cuando el peso de cargarlo solo es demasiado grande.', en: 'When the weight of carrying it alone is too great.', fr: 'Quand le poids de le porter seul(e) est trop grand.', de: 'Wenn die Last, es allein zu tragen, zu groß wird.', it: 'Quando il peso di portarlo da solo è troppo grande.', pt: 'Quando o peso de carregá-lo sozinho/a é grande demais.' }, dimension: 'C' },
      { text: { es: 'Cuando el secreto podría estar perjudicando a terceros que no saben que están afectados.', en: 'When the secret could be harming third parties who don\'t know they\'re affected.', fr: 'Quand le secret pourrait nuire à des tiers qui ne savent pas qu\'ils sont affectés.', de: 'Wenn das Geheimnis Dritte schädigen könnte, die nicht wissen, dass sie betroffen sind.', it: 'Quando il segreto potrebbe danneggiare terze parti che non sanno di essere colpite.', pt: 'Quando o segredo poderia estar prejudicando terceiros que não sabem que são afetados.' }, dimension: 'S' },
      { text: { es: 'Cuando guardar el secreto requiere mentir activamente a alguien.', en: 'When keeping the secret requires actively lying to someone.', fr: 'Quand garder le secret nécessite de mentir activement à quelqu\'un.', de: 'Wenn das Bewahren des Geheimnisses erfordert, jemanden aktiv zu belügen.', it: 'Quando custodire il segreto richiede di mentire attivamente a qualcuno.', pt: 'Quando guardar o segredo requer mentir ativamente para alguém.' }, dimension: 'T' },
    ] },
    { id: 8, situation: { es: 'Alguien te cuenta un secreto de otro sin el permiso del primero. ¿Qué haces con esa información?', en: 'Someone tells you a secret about another person without the first person\'s permission. What do you do with that information?', fr: 'Quelqu\'un te raconte un secret d\'une autre personne sans la permission de la première. Que fais-tu avec cette information ?', de: 'Jemand erzählt dir ein Geheimnis über eine andere Person ohne die Erlaubnis der ersten. Was machst du mit dieser Information?', it: 'Qualcuno ti racconta un segreto di un\'altra persona senza il permesso della prima. Cosa fai con quella informazione?', pt: 'Alguém te conta um segredo de outro sem a permissão do primeiro. O que você faz com essa informação?' }, options: [
      { text: { es: 'La guardo igual que si me lo hubieran contado directamente.', en: 'I keep it just as if they had told me directly.', fr: 'Je la garde comme si on me l\'avait dit directement.', de: 'Ich bewahre es genauso, als ob es mir direkt erzählt worden wäre.', it: 'La custodisco come se me lo avessero detto direttamente.', pt: 'Guardo como se tivessem me contado diretamente.' }, dimension: 'G' },
      { text: { es: 'Termina siendo parte de mi "base de conocimiento" sobre ese círculo.', en: 'It ends up being part of my "knowledge base" about that circle.', fr: 'Ça finit par faire partie de ma "base de connaissances" sur ce cercle.', de: 'Es wird Teil meiner "Wissensbasis" über diesen Kreis.', it: 'Finisce per far parte della mia "base di conoscenza" su quel cerchio.', pt: 'Acaba sendo parte da minha "base de conhecimento" sobre esse círculo.' }, dimension: 'C' },
      { text: { es: 'Puede que le pregunte a la persona original si es algo que puedo comentar.', en: 'I might ask the original person if it\'s something I can comment on.', fr: 'Je pourrais demander à la personne d\'origine si c\'est quelque chose que je peux commenter.', de: 'Ich frage vielleicht die ursprüngliche Person, ob es etwas ist, worüber ich sprechen kann.', it: 'Potrei chiedere alla persona originale se è qualcosa che posso commentare.', pt: 'Posso perguntar à pessoa original se é algo que posso comentar.' }, dimension: 'S' },
      { text: { es: 'La uso para entender mejor a las personas involucradas pero no la cuento.', en: 'I use it to better understand the people involved but don\'t tell it.', fr: 'Je l\'utilise pour mieux comprendre les personnes impliquées mais je ne la raconte pas.', de: 'Ich nutze es, um die beteiligten Personen besser zu verstehen, erzähle es aber nicht weiter.', it: 'La uso per capire meglio le persone coinvolte ma non la racconto.', pt: 'Uso para entender melhor as pessoas envolvidas mas não a conto.' }, dimension: 'T' },
    ] },
    { id: 9, situation: { es: 'Tienes un secreto tuyo propio. Tu mejor amigo/a te pregunta directamente sobre ello.', en: 'You have a secret of your own. Your best friend asks you directly about it.', fr: 'Tu as un secret qui t\'appartient. Ton/ta meilleur(e) ami(e) te pose directement la question à ce sujet.', de: 'Du hast ein eigenes Geheimnis. Dein bester Freund/deine beste Freundin fragt dich direkt danach.', it: 'Hai un tuo segreto. Il tuo migliore amico/a ti chiede direttamente di esso.', pt: 'Você tem um segredo seu. Seu/sua melhor amigo/a te pergunta diretamente sobre isso.' }, options: [
      { text: { es: 'Lo guardo. Mis secretos personales son los más sagrados.', en: 'I keep it. My personal secrets are the most sacred.', fr: 'Je le garde. Mes secrets personnels sont les plus sacrés.', de: 'Ich bewahre es. Meine persönlichen Geheimnisse sind die heiligsten.', it: 'Lo custodisco. I miei segreti personali sono i più sacri.', pt: 'Guardo. Meus segredos pessoais são os mais sagrados.' }, dimension: 'G' },
      { text: { es: 'Se lo cuento. Si no puedo ser vulnerable con mi mejor amigo/a, ¿con quién?', en: 'I tell them. If I can\'t be vulnerable with my best friend, who with?', fr: 'Je le lui raconte. Si je ne peux pas être vulnérable avec mon/ma meilleur(e) ami(e), avec qui ?', de: 'Ich erzähle es ihm/ihr. Wenn ich nicht verletzlich mit meinem besten Freund/meiner besten Freundin sein kann, mit wem dann?', it: 'Glielo racconto. Se non posso essere vulnerabile con il mio migliore amico/a, con chi?', pt: 'Conto. Se não posso ser vulnerável com meu/minha melhor amigo/a, com quem?' }, dimension: 'C' },
      { text: { es: 'Depende de qué tan listo/a me siento para compartirlo en ese momento.', en: 'Depends on how ready I feel to share it at that moment.', fr: 'Ça dépend de combien je me sens prêt(e) à le partager en ce moment.', de: 'Hängt davon ab, wie bereit ich mich fühle, es in diesem Moment zu teilen.', it: 'Dipende da quanto mi sento pronto/a a condividerlo in quel momento.', pt: 'Depende de quanto me sinto pronto/a para compartilhá-lo naquele momento.' }, dimension: 'S' },
      { text: { es: 'Le digo que hay algo pero que no estoy listo/a para hablarlo. Al menos es honesto.', en: 'I tell them there\'s something but I\'m not ready to talk about it. At least it\'s honest.', fr: 'Je lui dis qu\'il y a quelque chose mais que je ne suis pas prêt(e) à en parler. Au moins c\'est honnête.', de: 'Ich sage ihm/ihr, dass es etwas gibt, aber dass ich nicht bereit bin, darüber zu reden. Zumindest ist es ehrlich.', it: 'Dico che c\'è qualcosa ma che non sono pronto/a a parlarne. Almeno è onesto.', pt: 'Digo que há algo mas que não estou pronto/a para falar. Pelo menos é honesto.' }, dimension: 'T' },
    ] },
    { id: 10, situation: { es: '¿Cómo describirías tu reputación en tu círculo respecto a los secretos?', en: 'How would you describe your reputation in your circle regarding secrets?', fr: 'Comment décrirais-tu ta réputation dans ton cercle en ce qui concerne les secrets ?', de: 'Wie würdest du deinen Ruf in deinem Kreis bezüglich Geheimnissen beschreiben?', it: 'Come descriveresti la tua reputazione nel tuo cerchio riguardo ai segreti?', pt: 'Como você descreveria sua reputação em seu círculo em relação aos segredos?' }, options: [
      { text: { es: '"Puedo contarle cualquier cosa. Jamás lo ha filtrado."', en: '"I can tell them anything. They\'ve never leaked it."', fr: '"Je peux lui dire n\'importe quoi. Il/elle ne l\'a jamais divulgué."', de: '"Ich kann ihm/ihr alles erzählen. Er/sie hat es nie weitergegeben."', it: '"Gli/Le posso raccontare qualsiasi cosa. Non l\'ha mai filtrata."', pt: '"Posso contar qualquer coisa. Nunca vazou."' }, dimension: 'G' },
      { text: { es: '"Es buena gente pero mejor no contarle cosas muy privadas."', en: '"Good person but better not to tell them very private things."', fr: '"C\'est une bonne personne mais mieux vaut ne pas lui confier des choses très privées."', de: '"Gute Person, aber besser nicht sehr private Dinge erzählen."', it: '"È buona persona ma meglio non raccontargli cose molto private."', pt: '"É boa gente mas melhor não contar coisas muito privadas."' }, dimension: 'C' },
      { text: { es: '"Lo cuento con cuidado. Sé que lo evaluará antes de compartirlo con alguien."', en: '"Shares carefully. I know they\'ll evaluate it before sharing with someone."', fr: '"Il/elle partage avec soin. Je sais qu\'il/elle l\'évaluera avant de le partager avec quelqu\'un."', de: '"Teilt sorgfältig. Ich weiß, dass er/sie es bewerten wird, bevor er/sie es mit jemandem teilt."', it: '"Lo racconta con cura. So che lo valuterà prima di condividerlo con qualcuno."', pt: '"Conta com cuidado. Sei que vai avaliar antes de compartilhar com alguém."' }, dimension: 'S' },
      { text: { es: '"No guarda secretos activamente, pero tampoco miente. Honesto/a hasta el final."', en: '"Doesn\'t actively keep secrets, but doesn\'t lie either. Honest to the end."', fr: '"Ne garde pas activement les secrets, mais ne ment pas non plus. Honnête jusqu\'au bout."', de: '"Bewahrt Geheimnisse nicht aktiv, lügt aber auch nicht. Ehrlich bis zum Ende."', it: '"Non custodisce attivamente i segreti, ma non mente nemmeno. Onesto/a fino alla fine."', pt: '"Não guarda segredos ativamente, mas também não mente. Honesto/a até o final."' }, dimension: 'T' },
    ] },
  ],
  characters: [
    { name: { es: 'La Bóveda', en: 'The Vault', fr: 'Le Coffre-Fort', de: 'Der Tresor', it: 'La Cassaforte', pt: 'O Cofre' }, dimensions: ['G'], photo: '/characters/vault.jpg', description: { es: 'Los secretos entran y no salen. Punto.', en: 'Secrets go in and don\'t come out. Period.', fr: 'Les secrets entrent et ne sortent pas. Point.', de: 'Geheimnisse gehen rein und kommen nicht raus. Punkt.', it: 'I segreti entrano e non escono. Punto.', pt: 'Os segredos entram e não saem. Ponto.' }, philosophy: { es: 'Cuando alguien confía en ti, ese acto de confianza es más importante que cualquier beneficio que obtendrías al hablar. Eres el tipo de persona que la gente busca en los momentos más vulnerables de su vida.', en: 'When someone trusts you, that act of trust is more important than any benefit you\'d get from talking. You\'re the type of person people seek in the most vulnerable moments of their lives.', fr: 'Quand quelqu\'un te fait confiance, cet acte de confiance est plus important que tout bénéfice que tu obtiendrais en parlant. Tu es le type de personne que les gens cherchent dans les moments les plus vulnérables de leur vie.', de: 'Wenn jemand dir vertraut, ist dieser Vertrauensakt wichtiger als jeder Vorteil, den du durch Reden erzielen würdest. Du bist die Art von Person, die Menschen in den verletzlichsten Momenten ihres Lebens suchen.', it: 'Quando qualcuno si fida di te, quell\'atto di fiducia è più importante di qualsiasi beneficio che otterresti parlando. Sei il tipo di persona che le persone cercano nei momenti più vulnerabili della loro vita.', pt: 'Quando alguém confia em você, esse ato de confiança é mais importante do que qualquer benefício que obteria falando. Você é o tipo de pessoa que as pessoas buscam nos momentos mais vulneráveis de suas vidas.' } },
    { name: { es: 'El Filtrador Involuntario', en: 'The Involuntary Leaker', fr: 'Le Filtreur Involontaire', de: 'Der Unfreiwillige Durchsickerer', it: 'Il Filtratore Involontario', pt: 'O Vazador Involuntário' }, dimensions: ['C'], photo: '/characters/leaker.jpg', description: { es: 'No lo hace con maldad, pero los secretos no duran mucho con él/ella.', en: 'Doesn\'t do it with malice, but secrets don\'t last long with them.', fr: 'Ne le fait pas avec méchanceté, mais les secrets ne durent pas longtemps avec lui/elle.', de: 'Tut es nicht mit Bosheit, aber Geheimnisse dauern nicht lange bei ihm/ihr.', it: 'Non lo fa con malizia, ma i segreti non durano molto con lui/lei.', pt: 'Não faz isso com maldade, mas os segredos não duram muito com ele/ela.' }, philosophy: { es: 'Cargás los secretos de otros como un peso que tu mente y tu boca eventualmente necesitan liberar. No es malicia — es que la información quiere fluir y a ti te cuesta ser el dique.', en: 'You carry others\' secrets like a weight your mind and mouth eventually need to release. It\'s not malice — it\'s that information wants to flow and it\'s hard for you to be the dam.', fr: 'Tu portes les secrets des autres comme un poids que ton esprit et ta bouche ont éventuellement besoin de libérer. Ce n\'est pas de la malice — c\'est que l\'information veut circuler et qu\'il t\'est difficile d\'être la digue.', de: 'Du trägst die Geheimnisse anderer wie ein Gewicht, das dein Geist und dein Mund schließlich loslassen müssen. Es ist keine Bosheit — es ist, dass Informationen fließen wollen und es dir schwerfällt, der Damm zu sein.', it: 'Porti i segreti degli altri come un peso che la tua mente e la tua bocca devono eventualmente liberare. Non è malizia — è che l\'informazione vuole fluire e ti costa essere la diga.', pt: 'Você carrega os segredos dos outros como um peso que sua mente e boca eventualmente precisam liberar. Não é maldade — é que a informação quer fluir e é difícil para você ser a represa.' } },
    { name: { es: 'El Guardián Selectivo', en: 'The Selective Guardian', fr: 'Le Gardien Sélectif', de: 'Der Selektive Hüter', it: 'Il Guardiano Selettivo', pt: 'O Guardião Seletivo' }, dimensions: ['S'], photo: '/characters/selective-guardian.jpg', description: { es: 'Evalúa caso por caso antes de guardar o compartir.', en: 'Evaluates case by case before keeping or sharing.', fr: 'Évalue cas par cas avant de garder ou partager.', de: 'Bewertet Fall für Fall, bevor er/sie bewahrt oder teilt.', it: 'Valuta caso per caso prima di custodire o condividere.', pt: 'Avalia caso por caso antes de guardar ou compartilhar.' }, philosophy: { es: 'Tu ética sobre los secretos no es absoluta — es contextual. Evalúas quién confió, por qué, qué consecuencias tiene, quién podría verse afectado. Es más trabajo, pero también más sabio.', en: 'Your ethics about secrets isn\'t absolute — it\'s contextual. You evaluate who trusted, why, what consequences it has, who might be affected. It\'s more work, but also wiser.', fr: 'Ton éthique sur les secrets n\'est pas absolue — elle est contextuelle. Tu évalues qui a confié, pourquoi, quelles sont les conséquences, qui pourrait être affecté. C\'est plus de travail, mais aussi plus sage.', de: 'Deine Ethik bezüglich Geheimnissen ist nicht absolut — sie ist kontextbezogen. Du bewertest, wer vertraut hat, warum, welche Konsequenzen es hat, wer betroffen sein könnte. Es ist mehr Arbeit, aber auch weiser.', it: 'La tua etica sui segreti non è assoluta — è contestuale. Valuti chi si è fidato, perché, quali conseguenze ha, chi potrebbe essere colpito. È più lavoro, ma anche più saggio.', pt: 'Sua ética sobre os segredos não é absoluta — é contextual. Você avalia quem confiou, por quê, que consequências tem, quem poderia ser afetado. É mais trabalho, mas também mais sábio.' } },
    { name: { es: 'El Transparente Honesto', en: 'The Honest Transparent', fr: 'L\'Honnête Transparent', de: 'Der Ehrliche Transparente', it: 'Il Trasparente Onesto', pt: 'O Transparente Honesto' }, dimensions: ['T'], photo: '/characters/transparent-honest.jpg', description: { es: 'No miente, pero tampoco guarda todo. Honestidad radical.', en: 'Doesn\'t lie, but doesn\'t keep everything either. Radical honesty.', fr: 'Ne ment pas, mais ne garde pas non plus tout. Honnêteté radicale.', de: 'Lügt nicht, bewahrt aber auch nicht alles. Radikale Ehrlichkeit.', it: 'Non mente, ma non custodisce nemmeno tutto. Onestà radicale.', pt: 'Não mente, mas também não guarda tudo. Honestidade radical.' }, philosophy: { es: 'Tu principio fundamental es no mentir. Eso a veces crea tensiones con la confidencialidad. Prefieres decir "no puedo contarlo" que fingir que no sabes. Para ti, la honestidad tiene prioridad sobre la discreción.', en: 'Your fundamental principle is not lying. That sometimes creates tensions with confidentiality. You prefer to say "I can\'t tell it" rather than pretend you don\'t know. For you, honesty takes priority over discretion.', fr: 'Ton principe fondamental est de ne pas mentir. Ça crée parfois des tensions avec la confidentialité. Tu préfères dire "je ne peux pas le dire" plutôt que de prétendre ne pas savoir. Pour toi, l\'honnêteté a la priorité sur la discrétion.', de: 'Dein grundlegendes Prinzip ist, nicht zu lügen. Das schafft manchmal Spannungen mit der Vertraulichkeit. Du sagst lieber "Ich kann es nicht erzählen", als so zu tun, als ob du es nicht wüsstest. Für dich hat Ehrlichkeit Vorrang vor Diskretion.', it: 'Il tuo principio fondamentale è non mentire. Questo a volte crea tensioni con la riservatezza. Preferisci dire "non posso raccontarlo" piuttosto che fingere di non sapere. Per te, l\'onestà ha la priorità sulla discrezione.', pt: 'Seu princípio fundamental é não mentir. Isso às vezes cria tensões com a confidencialidade. Você prefere dizer "não posso contar" a fingir que não sabe. Para você, a honestidade tem prioridade sobre a discrição.' } },
    { name: { es: 'El Confidente Real', en: 'The Real Confidant', fr: 'Le Vrai Confident', de: 'Der Echte Vertraute', it: 'Il Confidente Reale', pt: 'O Confidente Real' }, dimensions: ['G', 'S'], photo: '/characters/real-confident.jpg', description: { es: 'Guardián con criterio. Sabe cuándo el secreto debe mantenerse y cuándo no.', en: 'Guardian with criteria. Knows when the secret should be kept and when not.', fr: 'Gardien avec des critères. Sait quand le secret doit être gardé et quand non.', de: 'Hüter mit Kriterien. Weiß, wann das Geheimnis bewahrt werden sollte und wann nicht.', it: 'Guardiano con criterio. Sa quando il segreto deve essere mantenuto e quando no.', pt: 'Guardião com critério. Sabe quando o segredo deve ser mantido e quando não.' }, philosophy: { es: 'Eres el guardian más valioso: silencioso por defecto, pero capaz de evaluar cuándo el secreto mismo se vuelve un daño. La mayoría de las veces, te callas. Pero no serías cómplice de algo que hace daño.', en: 'You\'re the most valuable guardian: silent by default, but capable of evaluating when the secret itself becomes harmful. Most of the time, you stay quiet. But you wouldn\'t be an accomplice to something that causes harm.', fr: 'Tu es le gardien le plus précieux : silencieux par défaut, mais capable d\'évaluer quand le secret lui-même devient un préjudice. La plupart du temps, tu te tais. Mais tu ne serais pas complice de quelque chose qui fait du mal.', de: 'Du bist der wertvollste Hüter: standardmäßig schweigend, aber in der Lage zu bewerten, wann das Geheimnis selbst zu einem Schaden wird. Meistens schweigst du. Aber du wärst kein Komplize von etwas, das Schaden anrichtet.', it: 'Sei il guardiano più prezioso: silenzioso per impostazione predefinita, ma capace di valutare quando il segreto stesso diventa un danno. La maggior parte delle volte, taci. Ma non saresti complice di qualcosa che fa del male.', pt: 'Você é o guardião mais valioso: silencioso por padrão, mas capaz de avaliar quando o próprio segredo se torna um dano. Na maioria das vezes, você se cala. Mas não seria cúmplice de algo que causa dano.' } },
    { name: { es: 'El Discreto Transparente', en: 'The Discreet Transparent', fr: 'Le Discret Transparent', de: 'Der Diskrete Transparente', it: 'Il Discreto Trasparente', pt: 'O Discreto Transparente' }, dimensions: ['G', 'T'], photo: '/characters/discrete-transparent.jpg', description: { es: 'Guarda los secretos, pero nunca finge no saber.', en: 'Keeps secrets, but never pretends not to know.', fr: 'Garde les secrets, mais ne fait jamais semblant de ne pas savoir.', de: 'Bewahrt Geheimnisse, tut aber nie so, als ob er/sie es nicht wüsste.', it: 'Custodisce i segreti, ma non finge mai di non sapere.', pt: 'Guarda os segredos, mas nunca finge não saber.' }, philosophy: { es: 'Mantienes los compromisos de confidencialidad, pero no mientes activamente. Hay una diferencia entre no decir algo y decir que no sabes nada. Esa diferencia importa mucho para ti.', en: 'You maintain confidentiality commitments, but don\'t actively lie. There\'s a difference between not saying something and saying you don\'t know anything. That difference matters a lot to you.', fr: 'Tu maintiens les engagements de confidentialité, mais tu ne mens pas activement. Il y a une différence entre ne pas dire quelque chose et dire que tu ne sais rien. Cette différence compte beaucoup pour toi.', de: 'Du hältst Vertraulichkeitsverpflichtungen ein, lügst aber nicht aktiv. Es gibt einen Unterschied zwischen nichts zu sagen und zu sagen, dass du nichts weißt. Dieser Unterschied ist für dich sehr wichtig.', it: 'Mantieni gli impegni di riservatezza, ma non menti attivamente. C\'è una differenza tra non dire qualcosa e dire che non sai niente. Quella differenza conta molto per te.', pt: 'Você mantém os compromissos de confidencialidade, mas não mente ativamente. Há uma diferença entre não dizer algo e dizer que não sabe nada. Essa diferença importa muito para você.' } },
    { name: { es: 'El Social Selectivo', en: 'The Social Selective', fr: 'Le Social Sélectif', de: 'Der Soziale Selektive', it: 'Il Sociale Selettivo', pt: 'O Social Seletivo' }, dimensions: ['C', 'S'], photo: '/characters/social-selective.jpg', description: { es: 'Comparte con criterio dentro de un círculo de confianza.', en: 'Shares with criteria within a circle of trust.', fr: 'Partage avec des critères dans un cercle de confiance.', de: 'Teilt mit Kriterien innerhalb eines Vertrauenskreises.', it: 'Condivide con criterio all\'interno di un cerchio di fiducia.', pt: 'Compartilha com critério dentro de um círculo de confiança.' }, philosophy: { es: 'Para ti, los secretos son compartibles dentro de ciertos límites. No los filtras al mundo, pero tampoco los guardas en soledad absoluta. El círculo de confianza existe por algo.', en: 'For you, secrets are shareable within certain limits. You don\'t leak them to the world, but you don\'t keep them in absolute solitude either. The circle of trust exists for a reason.', fr: 'Pour toi, les secrets sont partageables dans certaines limites. Tu ne les filtres pas au monde, mais tu ne les gardes pas non plus dans une solitude absolue. Le cercle de confiance existe pour quelque chose.', de: 'Für dich sind Geheimnisse innerhalb bestimmter Grenzen teilbar. Du gibst sie nicht an die Welt weiter, bewahrst sie aber auch nicht in absoluter Einsamkeit. Der Vertrauenskreis existiert aus einem Grund.', it: 'Per te, i segreti sono condivisibili entro certi limiti. Non li filtri al mondo, ma non li custodisci nemmeno in solitudine assoluta. Il cerchio di fiducia esiste per qualcosa.', pt: 'Para você, os segredos são compartilháveis dentro de certos limites. Você não os vaza para o mundo, mas também não os guarda em solidão absoluta. O círculo de confiança existe por algo.' } },
    { name: { es: 'El Pragmático Honesto', en: 'The Honest Pragmatist', fr: 'Le Pragmatique Honnête', de: 'Der Ehrliche Pragmatiker', it: 'Il Pragmatico Onesto', pt: 'O Pragmático Honesto' }, dimensions: ['S', 'T'], photo: '/characters/pragmatic-honest.jpg', description: { es: 'Evalúa, comunica sus límites y actúa con coherencia.', en: 'Evaluates, communicates their limits, and acts consistently.', fr: 'Évalue, communique ses limites et agit avec cohérence.', de: 'Bewertet, kommuniziert seine Grenzen und handelt kohärent.', it: 'Valuta, comunica i suoi limiti e agisce con coerenza.', pt: 'Avalia, comunica seus limites e age com coerência.' }, philosophy: { es: 'Antes de aceptar un secreto, dices lo que puedes y no puedes garantizar. Eso genera confianza real: la persona sabe exactamente qué hace al contártelo. Honestidad sobre la confidencialidad misma.', en: 'Before accepting a secret, you say what you can and can\'t guarantee. That generates real trust: the person knows exactly what they\'re doing by telling you. Honesty about confidentiality itself.', fr: 'Avant d\'accepter un secret, tu dis ce que tu peux et ne peux pas garantir. Ça génère une vraie confiance : la personne sait exactement ce qu\'elle fait en te le disant. Honnêteté sur la confidentialité elle-même.', de: 'Bevor du ein Geheimnis akzeptierst, sagst du, was du garantieren kannst und nicht kannst. Das erzeugt echtes Vertrauen: Die Person weiß genau, was sie tut, indem sie es dir erzählt. Ehrlichkeit über die Vertraulichkeit selbst.', it: 'Prima di accettare un segreto, dici cosa puoi e non puoi garantire. Questo genera vera fiducia: la persona sa esattamente cosa fa raccontandotelo. Onestà sulla riservatezza stessa.', pt: 'Antes de aceitar um segredo, você diz o que pode e não pode garantir. Isso gera confiança real: a pessoa sabe exatamente o que faz ao contá-lo. Honestidade sobre a própria confidencialidade.' } },
  ],
};

export async function seedSecretKeeper(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'secret-keeper' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'secret-keeper',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 5,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
