import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan tóxico/a eres en una relación?', en: 'How toxic are you in a relationship?', fr: 'À quel point es-tu toxique en relation ?', de: 'Wie toxisch bist du in einer Beziehung?', it: 'Quanto sei tossico/a in una relazione?', pt: 'O quanto você é tóxico/a em um relacionamento?' },
  description: { es: 'Todos tenemos conductas que dañan nuestras relaciones. ¿Las tuyas son red flags encubiertas o claramente visibles?', en: 'We all have behaviors that damage our relationships. Are yours hidden red flags or clearly visible ones?', fr: 'Nous avons tous des comportements qui nuisent à nos relations. Les tiens sont-ils des signaux d\'alarme cachés ou clairement visibles ?', de: 'Wir alle haben Verhaltensweisen, die unsere Beziehungen schädigen. Sind deine versteckte oder offensichtliche rote Flaggen?', it: 'Tutti abbiamo comportamenti che danneggiano le nostre relazioni. I tuoi sono segnali d\'allarme nascosti o chiaramente visibili?', pt: 'Todos temos comportamentos que prejudicam nossos relacionamentos. Os seus são red flags escondidas ou claramente visíveis?' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { D: 'Dependencia', C: 'Control', V: 'Evasión', T: 'Transparencia' },
    en: { D: 'Dependency', C: 'Control', V: 'Avoidance', T: 'Transparency' },
    fr: { D: 'Dépendance', C: 'Contrôle', V: 'Évitement', T: 'Transparence' },
    de: { D: 'Abhängigkeit', C: 'Kontrolle', V: 'Vermeidung', T: 'Transparenz' },
    it: { D: 'Dipendenza', C: 'Controllo', V: 'Evasione', T: 'Trasparenza' },
    pt: { D: 'Dependência', C: 'Controle', V: 'Evasão', T: 'Transparência' },
  },
  questions: [
    { id: 1, situation: { es: 'Tu pareja cancela planes contigo por última hora para salir con amigos. ¿Cómo reaccionas?', en: 'Your partner cancels plans with you at the last minute to go out with friends. How do you react?', fr: 'Ton partenaire annule des plans avec toi à la dernière minute pour sortir avec des amis. Comment réagis-tu ?', de: 'Dein Partner sagt in letzter Minute Pläne mit dir ab, um mit Freunden auszugehen. Wie reagierst du?', it: 'Il tuo partner cancella i piani con te all\'ultimo minuto per uscire con gli amici. Come reagisci?', pt: 'Seu parceiro cancela planos com você em cima da hora para sair com amigos. Como você reage?' }, options: [
      { text: { es: 'Me siento devastado/a. Paso el resto de la noche viendo su historia de Instagram.', en: 'I feel devastated. I spend the rest of the night watching their Instagram story.', fr: 'Je me sens dévasté(e). Je passe le reste de la nuit à regarder leur story Instagram.', de: 'Ich fühle mich am Boden. Ich verbringe den Rest der Nacht damit, ihre Instagram-Story anzuschauen.', it: 'Mi sento devastato/a. Passo il resto della notte a guardare la sua storia di Instagram.', pt: 'Me sinto devastado/a. Passo o resto da noite vendo a story do Instagram dele/dela.' }, dimension: 'D' },
      { text: { es: 'Le pregunto exactamente con quién va y le pido que me mande fotos durante la noche.', en: 'I ask exactly who they\'re going with and ask them to send me photos during the night.', fr: 'Je lui demande exactement avec qui il/elle y va et lui demande de m\'envoyer des photos pendant la nuit.', de: 'Ich frage genau, mit wem sie gehen, und bitte sie, mir während der Nacht Fotos zu schicken.', it: 'Chiedo esattamente con chi va e gli chiedo di mandarmi foto durante la serata.', pt: 'Pergunto exatamente com quem vai e peço que me mande fotos durante a noite.' }, dimension: 'C' },
      { text: { es: 'Digo "no pasa nada" y me desconecto emocionalmente. No hablo del tema por días.', en: 'I say "it\'s fine" and disconnect emotionally. I don\'t talk about it for days.', fr: 'Je dis "pas de problème" et me déconnecte émotionnellement. Je n\'en parle pas pendant des jours.', de: 'Ich sage "kein Problem" und trenne mich emotional. Ich spreche tagelang nicht darüber.', it: 'Dico "non importa" e mi disconnetto emotivamente. Non ne parlo per giorni.', pt: 'Digo "não tem problema" e me desconecto emocionalmente. Não falo sobre o assunto por dias.' }, dimension: 'V' },
      { text: { es: 'Le digo que me molestó y hablamos sobre cómo manejarlo mejor la próxima vez.', en: 'I tell them it bothered me and we talk about how to handle it better next time.', fr: 'Je lui dis que ça m\'a dérangé(e) et nous discutons de comment mieux gérer ça la prochaine fois.', de: 'Ich sage ihm, dass mich das gestört hat, und wir sprechen darüber, wie wir es beim nächsten Mal besser handhaben können.', it: 'Gli dico che mi ha infastidito e parliamo di come gestirlo meglio la prossima volta.', pt: 'Digo que me incomodou e conversamos sobre como lidar melhor com isso da próxima vez.' }, dimension: 'T' },
    ] },
    { id: 2, situation: { es: 'Tu pareja tiene un amigo/a del sexo opuesto con quien sale ocasionalmente. ¿Cómo lo manejas?', en: 'Your partner has a friend of the opposite sex they occasionally go out with. How do you handle it?', fr: 'Ton partenaire a un(e) ami(e) du sexe opposé avec qui il/elle sort occasionnellement. Comment le gères-tu ?', de: 'Dein Partner hat einen Freund/eine Freundin des anderen Geschlechts, mit dem/der er/sie gelegentlich ausgeht. Wie gehst du damit um?', it: 'Il tuo partner ha un amico/a del sesso opposto con cui esce occasionalmente. Come lo gestisci?', pt: 'Seu parceiro tem um amigo/a do sexo oposto com quem sai ocasionalmente. Como você lida com isso?' }, options: [
      { text: { es: 'No puedo dormir cuando salen juntos. Chequeo su ubicación constantemente.', en: 'I can\'t sleep when they go out together. I constantly check their location.', fr: 'Je ne peux pas dormir quand ils sortent ensemble. Je vérifie constamment leur localisation.', de: 'Ich kann nicht schlafen, wenn sie zusammen ausgehen. Ich überprüfe ständig ihren Standort.', it: 'Non riesco a dormire quando escono insieme. Controllo costantemente la loro posizione.', pt: 'Não consigo dormir quando saem juntos. Fico verificando a localização constantemente.' }, dimension: 'D' },
      { text: { es: 'Le hago sutiles comentarios negativos sobre esa persona hasta que deja de salir con ella.', en: 'I make subtle negative comments about that person until they stop seeing them.', fr: 'Je fais des commentaires négatifs subtils sur cette personne jusqu\'à ce qu\'il/elle arrête de la voir.', de: 'Ich mache subtile negative Kommentare über diese Person, bis mein Partner aufhört, sie zu treffen.', it: 'Faccio commenti negativi sottili su quella persona finché non smette di vederla.', pt: 'Faço comentários negativos sutis sobre essa pessoa até que ele/ela pare de sair com ela.' }, dimension: 'C' },
      { text: { es: 'Finjo que no me importa pero llevo una lista mental de cada vez que se ven.', en: 'I pretend I don\'t care but I keep a mental list of every time they meet.', fr: 'Je fais semblant de ne pas m\'en soucier mais je garde une liste mentale de chaque fois qu\'ils se voient.', de: 'Ich tue so, als würde es mich nicht kümmern, aber ich führe eine mentale Liste, wie oft sie sich treffen.', it: 'Fingo di non preoccuparmene ma tengo un elenco mentale di ogni volta che si vedono.', pt: 'Finjo que não me importo, mas guardo uma lista mental de cada vez que eles se veem.' }, dimension: 'V' },
      { text: { es: 'Conozco a esa persona y confío en mi pareja. Si algo me incomoda, lo digo directamente.', en: 'I know that person and trust my partner. If something bothers me, I say it directly.', fr: 'Je connais cette personne et je fais confiance à mon partenaire. Si quelque chose me dérange, je le dis directement.', de: 'Ich kenne diese Person und vertraue meinem Partner. Wenn mich etwas stört, sage ich es direkt.', it: 'Conosco quella persona e mi fido del mio partner. Se qualcosa mi disturba, lo dico direttamente.', pt: 'Conheço essa pessoa e confio no meu parceiro. Se algo me incomoda, digo diretamente.' }, dimension: 'T' },
    ] },
    { id: 3, situation: { es: 'Están en una discusión intensa. Tu pareja dice algo hiriente. ¿Cómo respondes?', en: 'You\'re in an intense argument. Your partner says something hurtful. How do you respond?', fr: 'Vous êtes dans une discussion intense. Ton partenaire dit quelque chose de blessant. Comment réagis-tu ?', de: 'Ihr seid in einem intensiven Streit. Dein Partner sagt etwas Verletzendes. Wie reagierst du?', it: 'Siete in una discussione intensa. Il tuo partner dice qualcosa di ferito. Come rispondi?', pt: 'Vocês estão em uma discussão intensa. Seu parceiro diz algo que machuca. Como você responde?' }, options: [
      { text: { es: 'Lloro y le pregunto si me sigue queriendo. Necesito que me lo confirme ahora.', en: 'I cry and ask if they still love me. I need them to confirm it right now.', fr: 'Je pleure et lui demande s\'il/elle m\'aime encore. J\'ai besoin qu\'il/elle me le confirme maintenant.', de: 'Ich weine und frage, ob sie mich noch lieben. Ich brauche jetzt eine Bestätigung.', it: 'Piango e chiedo se mi vuole ancora bene. Ho bisogno che me lo confermi adesso.', pt: 'Choro e pergunto se ainda me ama. Preciso que confirme agora.' }, dimension: 'D' },
      { text: { es: 'Traigo a colación algo de hace dos años que sé que le duele. Si va a atacar, yo también.', en: 'I bring up something from two years ago that I know hurts them. If they\'re going to attack, so will I.', fr: 'Je soulève quelque chose de deux ans plus tôt que je sais qui lui fait mal. S\'il/elle attaque, moi aussi.', de: 'Ich bringe etwas von vor zwei Jahren auf, das ich weiß, dass es wehtut. Wenn sie angreifen, tue ich es auch.', it: 'Tiro fuori qualcosa di due anni fa che so che gli fa male. Se attacca, lo faccio anch\'io.', pt: 'Trago à tona algo de dois anos atrás que sei que machuca. Se vai atacar, eu também ataco.' }, dimension: 'C' },
      { text: { es: 'Me callo, digo que estoy bien y salgo de la habitación. No lo mencionaré nunca más.', en: 'I go silent, say I\'m fine, and leave the room. I\'ll never mention it again.', fr: 'Je me tais, dis que ça va et quitte la pièce. Je n\'en parlerai plus jamais.', de: 'Ich schweige, sage, dass alles gut ist, und verlasse den Raum. Ich werde das nie wieder erwähnen.', it: 'Mi taccio, dico che sto bene e esco dalla stanza. Non ne parlerò mai più.', pt: 'Fico calado/a, digo que estou bem e saio da sala. Nunca mais mencionarei isso.' }, dimension: 'V' },
      { text: { es: 'Le digo que eso me dolió y pedimos una pausa para calmarnos antes de continuar.', en: 'I tell them that hurt me and we ask for a break to calm down before continuing.', fr: 'Je lui dis que ça m\'a fait mal et nous prenons une pause pour nous calmer avant de continuer.', de: 'Ich sage ihm, dass mich das verletzt hat, und wir bitten um eine Pause zum Beruhigen.', it: 'Gli dico che questo mi ha fatto male e chiediamo una pausa per calmarci prima di continuare.', pt: 'Digo que isso me machucou e pedimos uma pausa para nos acalmar antes de continuar.' }, dimension: 'T' },
    ] },
    { id: 4, situation: { es: 'Tu pareja consigue un trabajo increíble que requiere viajes frecuentes. ¿Cómo lo manejas?', en: 'Your partner gets an amazing job that requires frequent travel. How do you handle it?', fr: 'Ton partenaire décroche un travail incroyable qui nécessite des voyages fréquents. Comment le gères-tu ?', de: 'Dein Partner bekommt einen tollen Job, der häufiges Reisen erfordert. Wie gehst du damit um?', it: 'Il tuo partner ottiene un lavoro incredibile che richiede frequenti viaggi. Come lo gestisci?', pt: 'Seu parceiro consegue um trabalho incrível que exige viagens frequentes. Como você lida com isso?' }, options: [
      { text: { es: 'Internamente siento pánico. Busco razones para que no acepte, aunque no las digo abiertamente.', en: 'Internally I panic. I look for reasons for them not to accept, even if I don\'t say them openly.', fr: 'Intérieurement, je panique. Je cherche des raisons pour qu\'il/elle n\'accepte pas, même si je ne les dis pas ouvertement.', de: 'Innerlich geriere ich in Panik. Ich suche Gründe, warum sie nicht annehmen sollen, auch wenn ich sie nicht offen sage.', it: 'Internamente mi spavento. Cerco ragioni per cui non accetti, anche se non le dico apertamente.', pt: 'Internamente fico em pânico. Busco razões para que não aceite, mesmo não dizendo abertamente.' }, dimension: 'D' },
      { text: { es: 'Le digo que acepte solo si promete llamarme cada noche y compartir su ubicación cuando viaje.', en: 'I tell them to accept only if they promise to call me every night and share their location when traveling.', fr: 'Je lui dis d\'accepter seulement s\'il/elle promet de m\'appeler chaque soir et de partager sa localisation en voyage.', de: 'Ich sage, sie sollen nur annehmen, wenn sie versprechen, mich jeden Abend anzurufen und beim Reisen ihren Standort zu teilen.', it: 'Gli dico di accettare solo se promette di chiamarmi ogni sera e condividere la sua posizione quando viaggia.', pt: 'Digo que aceite somente se prometer me ligar toda noite e compartilhar a localização quando viajar.' }, dimension: 'C' },
      { text: { es: 'Digo que es genial, pero empiezo a ser distante emocionalmente sin explicar por qué.', en: 'I say it\'s great but start becoming emotionally distant without explaining why.', fr: 'Je dis que c\'est super mais commence à devenir émotionnellement distant(e) sans expliquer pourquoi.', de: 'Ich sage, es ist toll, aber beginne emotional distanziert zu werden, ohne zu erklären warum.', it: 'Dico che è fantastico, ma comincio a essere emotivamente distante senza spiegare perché.', pt: 'Digo que é ótimo, mas começo a me distanciar emocionalmente sem explicar por quê.' }, dimension: 'V' },
      { text: { es: 'Me alegro genuinamente y hablamos sobre cómo mantener la conexión durante los viajes.', en: 'I genuinely rejoice and we talk about how to maintain our connection during the trips.', fr: 'Je me réjouis sincèrement et nous parlons de comment maintenir notre connexion pendant les voyages.', de: 'Ich freue mich aufrichtig und wir sprechen darüber, wie wir unsere Verbindung während der Reisen aufrechterhalten.', it: 'Mi rallegro genuinamente e parliamo di come mantenere la connessione durante i viaggi.', pt: 'Fico genuinamente feliz e conversamos sobre como manter a conexão durante as viagens.' }, dimension: 'T' },
    ] },
    { id: 5, situation: { es: 'Tu pareja necesita tiempo a solas. Dice que simplemente quiere un fin de semana con sus amigos sin ti.', en: 'Your partner needs alone time. They say they simply want a weekend with their friends without you.', fr: 'Ton partenaire a besoin de temps seul(e). Il/elle dit qu\'il/elle veut simplement un week-end avec ses amis sans toi.', de: 'Dein Partner braucht Zeit für sich. Er/sie sagt, er/sie möchte einfach ein Wochenende mit Freunden ohne dich.', it: 'Il tuo partner ha bisogno di tempo da solo. Dice che vuole semplicemente un weekend con i suoi amici senza di te.', pt: 'Seu parceiro precisa de tempo sozinho. Diz que simplesmente quer um fim de semana com os amigos sem você.' }, options: [
      { text: { es: 'Que algo está mal. Las personas que se quieren no necesitan tiempo separadas.', en: 'Something is wrong. People who love each other don\'t need time apart.', fr: 'Quelque chose ne va pas. Les gens qui s\'aiment n\'ont pas besoin de temps séparé.', de: 'Irgendetwas stimmt nicht. Menschen, die sich lieben, brauchen keine Zeit getrennt.', it: 'Qualcosa non va. Le persone che si amano non hanno bisogno di tempo separato.', pt: 'Algo está errado. Pessoas que se amam não precisam de tempo separadas.' }, dimension: 'D' },
      { text: { es: 'Está bien, pero voy a asegurarme de estar muy ocupado/a para que note que yo también tengo vida.', en: 'Fine, but I\'ll make sure I\'m very busy so they notice I have a life too.', fr: 'D\'accord, mais je vais m\'assurer d\'être très occupé(e) pour qu\'il/elle remarque que j\'ai aussi une vie.', de: 'Gut, aber ich werde sicherstellen, dass ich sehr beschäftigt bin, damit sie merken, dass ich auch ein Leben habe.', it: 'Va bene, ma mi assicurerò di essere molto occupato/a affinché noti che anch\'io ho una vita.', pt: 'Tudo bem, mas vou me certificar de estar muito ocupado/a para que perceba que eu também tenho vida.' }, dimension: 'C' },
      { text: { es: 'Perfecto, digo. Y después me encierro a ver Netflix fingiendo que todo está bien.', en: 'Perfect, I say. And then I lock myself up watching Netflix pretending everything\'s fine.', fr: 'Parfait, je dis. Et puis je m\'enferme à regarder Netflix en prétendant que tout va bien.', de: 'Perfekt, sage ich. Und dann schließe ich mich ein und schaue Netflix, während ich tue, als sei alles gut.', it: 'Perfetto, dico. E poi mi rinchiudo a guardare Netflix fingendo che vada tutto bene.', pt: 'Perfeito, digo. E depois me enfio assistindo Netflix fingindo que está tudo bem.' }, dimension: 'V' },
      { text: { es: 'Perfecto. El espacio individual es sano en una relación. Aprovecho para hacer mis propias cosas.', en: 'Perfect. Individual space is healthy in a relationship. I use the time to do my own things.', fr: 'Parfait. L\'espace individuel est sain dans une relation. J\'en profite pour faire mes propres choses.', de: 'Perfekt. Individueller Raum ist gesund in einer Beziehung. Ich nutze die Zeit für meine eigenen Dinge.', it: 'Perfetto. Lo spazio individuale è sano in una relazione. Ne approfitto per fare le mie cose.', pt: 'Perfeito. O espaço individual é saudável em um relacionamento. Aproveito para fazer minhas próprias coisas.' }, dimension: 'T' },
    ] },
    { id: 6, situation: { es: 'Llevan un mes mal. Tu pareja propone terapia de pareja. ¿Qué piensas?', en: 'You\'ve been struggling for a month. Your partner suggests couples therapy. What do you think?', fr: 'Vous avez eu un mois difficile. Ton partenaire propose une thérapie de couple. Qu\'en penses-tu ?', de: 'Ihr hattet einen schwierigen Monat. Dein Partner schlägt Paartherapie vor. Was denkst du?', it: 'Avete avuto un mese difficile. Il tuo partner propone una terapia di coppia. Cosa pensi?', pt: 'Vocês têm um mês difícil. Seu parceiro propõe terapia de casal. O que você acha?' }, options: [
      { text: { es: 'Me aterra. ¿Y si el terapeuta dice que la relación no tiene futuro?', en: 'I\'m terrified. What if the therapist says the relationship has no future?', fr: 'Ça me terrifie. Et si le thérapeute dit que la relation n\'a pas d\'avenir ?', de: 'Ich bin verängstigt. Was, wenn der Therapeut sagt, die Beziehung hat keine Zukunft?', it: 'Mi spaventa. E se il terapeuta dice che la relazione non ha futuro?', pt: 'Fico aterrorizado/a. E se o terapeuta disser que o relacionamento não tem futuro?' }, dimension: 'D' },
      { text: { es: 'Solo si el terapeuta es alguien que yo elija. No quiero que un desconocido tome partido.', en: 'Only if the therapist is someone I choose. I don\'t want a stranger taking sides.', fr: 'Seulement si le thérapeute est quelqu\'un que je choisis. Je ne veux pas qu\'un inconnu prenne parti.', de: 'Nur wenn der Therapeut jemand ist, den ich auswähle. Ich möchte nicht, dass ein Fremder Partei ergreift.', it: 'Solo se il terapeuta è qualcuno che scelgo io. Non voglio che uno sconosciuto prenda le parti.', pt: 'Somente se o terapeuta for alguém que eu escolha. Não quero que um desconhecido tome partido.' }, dimension: 'C' },
      { text: { es: 'Acepto externamente pero boicoteo las sesiones respondiendo con monosílabos.', en: 'I accept outwardly but sabotage the sessions by answering in monosyllables.', fr: 'J\'accepte extérieurement mais je sabote les séances en répondant par monosyllabes.', de: 'Ich stimme äußerlich zu, sabotiere aber die Sitzungen, indem ich mit Einsilbern antworte.', it: 'Accetto esternamente ma saboto le sessioni rispondendo a monosillabi.', pt: 'Aceito externamente mas boicoto as sessões respondendo com monossílabos.' }, dimension: 'V' },
      { text: { es: 'Excelente idea. Un espacio externo puede ayudarnos a ver puntos ciegos.', en: 'Excellent idea. An external space can help us see blind spots.', fr: 'Excellente idée. Un espace externe peut nous aider à voir nos angles morts.', de: 'Ausgezeichnete Idee. Ein externer Raum kann uns helfen, blinde Flecken zu sehen.', it: 'Ottima idea. Uno spazio esterno può aiutarci a vedere i punti ciechi.', pt: 'Excelente ideia. Um espaço externo pode nos ajudar a ver pontos cegos.' }, dimension: 'T' },
    ] },
    { id: 7, situation: { es: 'Tu pareja hace algo que no te gusta pero que no es incorrecto, es solo diferente a como lo harías tú.', en: 'Your partner does something you don\'t like, but it\'s not wrong — it\'s just different from how you\'d do it.', fr: 'Ton partenaire fait quelque chose que tu n\'aimes pas mais qui n\'est pas incorrect, c\'est juste différent de comment tu le ferais.', de: 'Dein Partner macht etwas, das dir nicht gefällt, aber nicht falsch ist — es ist nur anders, als du es tun würdest.', it: 'Il tuo partner fa qualcosa che non ti piace ma che non è sbagliato, è solo diverso da come lo faresti tu.', pt: 'Seu parceiro faz algo que você não gosta mas que não está errado, é apenas diferente de como você faria.' }, options: [
      { text: { es: 'Me pregunto si me conoce realmente si hace las cosas tan diferente a como me gustan.', en: 'I wonder if they really know me if they do things so differently from what I like.', fr: 'Je me demande s\'il/elle me connaît vraiment si il/elle fait les choses si différemment de ce que j\'aime.', de: 'Ich frage mich, ob sie mich wirklich kennen, wenn sie Dinge so anders machen, als ich es mag.', it: 'Mi chiedo se mi conosce davvero se fa le cose così diversamente da come mi piacciono.', pt: 'Fico me perguntando se realmente me conhece se faz as coisas tão diferente do que gosto.' }, dimension: 'D' },
      { text: { es: 'Le explico repetidamente por qué mi forma es mejor hasta que cambia.', en: 'I repeatedly explain why my way is better until they change.', fr: 'Je lui explique répétitivement pourquoi ma façon est meilleure jusqu\'à ce qu\'il/elle change.', de: 'Ich erkläre wiederholt, warum meine Art besser ist, bis sie sich ändern.', it: 'Gli spiego ripetutamente perché il mio modo è migliore finché non cambia.', pt: 'Explico repetidamente por que o meu jeito é melhor até que mude.' }, dimension: 'C' },
      { text: { es: 'No digo nada, pero acumulo el incidente en una lista mental de decepciones.', en: 'I say nothing, but I add the incident to a mental list of disappointments.', fr: 'Je ne dis rien, mais j\'ajoute l\'incident à une liste mentale de déceptions.', de: 'Ich sage nichts, aber ich füge den Vorfall einer mentalen Liste von Enttäuschungen hinzu.', it: 'Non dico niente, ma accumulo l\'incidente in un elenco mentale di delusioni.', pt: 'Não digo nada, mas acumulo o incidente em uma lista mental de decepções.' }, dimension: 'V' },
      { text: { es: 'Acepto que somos diferentes y solo lo menciono si realmente afecta nuestra dinámica.', en: 'I accept we are different and only mention it if it really affects our dynamic.', fr: 'J\'accepte que nous soyons différents et je le mentionne seulement si ça affecte vraiment notre dynamique.', de: 'Ich akzeptiere, dass wir verschieden sind, und erwähne es nur, wenn es wirklich unsere Dynamik betrifft.', it: 'Accetto che siamo diversi e lo menziono solo se influisce davvero sulla nostra dinamica.', pt: 'Aceito que somos diferentes e só menciono se realmente afetar nossa dinâmica.' }, dimension: 'T' },
    ] },
    { id: 8, situation: { es: 'Tu pareja habla con entusiasmo de su ex por algo positivo que hicieron juntos. ¿Cómo te sientes?', en: 'Your partner talks enthusiastically about their ex regarding something positive they did together. How do you feel?', fr: 'Ton partenaire parle avec enthousiasme de son ex pour quelque chose de positif qu\'ils ont fait ensemble. Comment te sens-tu ?', de: 'Dein Partner spricht begeistert über seinen Ex wegen etwas Positivem, das sie zusammen gemacht haben. Wie fühlst du dich?', it: 'Il tuo partner parla con entusiasmo del suo ex per qualcosa di positivo che hanno fatto insieme. Come ti senti?', pt: 'Seu parceiro fala com entusiasmo do ex sobre algo positivo que fizeram juntos. Como você se sente?' }, options: [
      { text: { es: 'Me siento amenazado/a inmediatamente. Empiezo a preguntar sobre esa relación.', en: 'I immediately feel threatened. I start asking questions about that relationship.', fr: 'Je me sens immédiatement menacé(e). Je commence à poser des questions sur cette relation.', de: 'Ich fühle mich sofort bedroht. Ich fange an, Fragen zu dieser Beziehung zu stellen.', it: 'Mi sento immediatamente minacciato/a. Comincio a fare domande su quella relazione.', pt: 'Me sinto ameaçado/a imediatamente. Começo a perguntar sobre aquele relacionamento.' }, dimension: 'D' },
      { text: { es: 'Inmediatamente traigo a colación algo que yo hice mejor que ese ex.', en: 'I immediately bring up something I did better than that ex.', fr: 'J\'amène immédiatement quelque chose que j\'ai fait mieux que cet ex.', de: 'Ich bringe sofort etwas zur Sprache, das ich besser gemacht habe als dieser Ex.', it: 'Porto immediatamente alla luce qualcosa che ho fatto meglio di quell\'ex.', pt: 'Imediatamente trago à tona algo que fiz melhor que esse ex.' }, dimension: 'C' },
      { text: { es: 'Finjo que no me importa y después tengo sueños raros con ese ex durante una semana.', en: 'I pretend I don\'t care and then have weird dreams about that ex for a week.', fr: 'Je fais semblant de ne pas m\'en soucier et puis j\'ai des rêves bizarres avec cet ex pendant une semaine.', de: 'Ich tue so, als würde es mir nichts ausmachen, und habe dann eine Woche lang merkwürdige Träume über diesen Ex.', it: 'Fingo di non preoccuparmi e poi ho sogni strani con quell\'ex per una settimana.', pt: 'Finjo que não me importo e depois tenho sonhos estranhos com esse ex por uma semana.' }, dimension: 'V' },
      { text: { es: 'Me alegra que tenga buenos recuerdos. El pasado es parte de quien es hoy.', en: 'I\'m glad they have good memories. The past is part of who they are today.', fr: 'Je suis content(e) qu\'il/elle ait de bons souvenirs. Le passé fait partie de qui il/elle est aujourd\'hui.', de: 'Es freut mich, dass sie gute Erinnerungen haben. Die Vergangenheit ist Teil davon, wer sie heute sind.', it: 'Sono contento/a che abbia bei ricordi. Il passato è parte di chi è oggi.', pt: 'Fico feliz que tenha boas memórias. O passado é parte de quem é hoje.' }, dimension: 'T' },
    ] },
    { id: 9, situation: { es: 'Están en una fiesta y tu pareja pasa mucho tiempo hablando con alguien que acabas de conocer.', en: 'You\'re at a party and your partner spends a lot of time talking to someone you just met.', fr: 'Vous êtes à une fête et ton partenaire passe beaucoup de temps à parler avec quelqu\'un que vous venez de rencontrer.', de: 'Ihr seid auf einer Party und dein Partner verbringt viel Zeit damit, mit jemandem zu sprechen, den ihr gerade kennengelernt habt.', it: 'Siete a una festa e il tuo partner passa molto tempo a parlare con qualcuno che hai appena conosciuto.', pt: 'Vocês estão em uma festa e seu parceiro passa muito tempo conversando com alguém que acabou de conhecer.' }, options: [
      { text: { es: 'Me acerco frecuentemente a la conversación con excusas para recordarle que estoy ahí.', en: 'I frequently approach the conversation with excuses to remind them I\'m there.', fr: 'Je m\'approche fréquemment de la conversation avec des excuses pour lui rappeler que je suis là.', de: 'Ich nähere mich häufig dem Gespräch mit Ausreden, um daran zu erinnern, dass ich da bin.', it: 'Mi avvicino frequentemente alla conversazione con scuse per ricordargli che sono lì.', pt: 'Me aproximo frequentemente da conversa com desculpas para lembrá-lo que estou lá.' }, dimension: 'D' },
      { text: { es: 'Me acerco y hago comentarios que naturalmente desvían la conversación hacia mí.', en: 'I approach and make comments that naturally steer the conversation toward me.', fr: 'Je m\'approche et fais des commentaires qui orientent naturellement la conversation vers moi.', de: 'Ich nähere mich und mache Kommentare, die das Gespräch auf natürliche Weise auf mich lenken.', it: 'Mi avvicino e faccio commenti che naturalmente deviano la conversazione verso di me.', pt: 'Me aproximo e faço comentários que naturalmente desviam a conversa para mim.' }, dimension: 'C' },
      { text: { es: 'Me alejo y paso el resto de la fiesta ligeramente distante para que note algo.', en: 'I walk away and spend the rest of the party slightly distant so they notice something.', fr: 'Je m\'éloigne et passe le reste de la fête légèrement distant(e) pour qu\'il/elle remarque quelque chose.', de: 'Ich entferne mich und verbringe den Rest der Party leicht distanziert, damit sie etwas bemerken.', it: 'Mi allontano e passo il resto della festa leggermente distante affinché noti qualcosa.', pt: 'Me afasto e passo o resto da festa levemente distante para que perceba algo.' }, dimension: 'V' },
      { text: { es: 'Disfruto la fiesta por mi cuenta y después le pregunto si conoció gente interesante.', en: 'I enjoy the party on my own and later ask if they met interesting people.', fr: 'Je profite de la fête pour moi-même et lui demande ensuite s\'il/elle a rencontré des gens intéressants.', de: 'Ich genieße die Party für mich und frage ihn später, ob er interessante Leute kennengelernt hat.', it: 'Godo della festa per conto mio e poi gli chiedo se ha conosciuto persone interessanti.', pt: 'Aproveito a festa por conta própria e depois pergunto se conheceu pessoas interessantes.' }, dimension: 'T' },
    ] },
    { id: 10, situation: { es: 'Tu pareja decide tomarse un tiempo para pensar sobre la relación. ¿Cómo manejas esa semana?', en: 'Your partner decides to take some time to think about the relationship. How do you handle that week?', fr: 'Ton partenaire décide de prendre du temps pour réfléchir à la relation. Comment gères-tu cette semaine ?', de: 'Dein Partner beschließt, sich Zeit zum Nachdenken über die Beziehung zu nehmen. Wie gehst du mit dieser Woche um?', it: 'Il tuo partner decide di prendersi del tempo per riflettere sulla relazione. Come gestisci quella settimana?', pt: 'Seu parceiro decide se afastar para pensar sobre o relacionamento. Como você lida com essa semana?' }, options: [
      { text: { es: 'La paso en modo crisis: mensajes, llamadas, pedir a amigos comunes que hablen con ella/él.', en: 'I spend it in crisis mode: messages, calls, asking mutual friends to talk to them.', fr: 'Je la passe en mode crise: messages, appels, demander à des amis communs de lui parler.', de: 'Ich verbringe sie im Krisenmodus: Nachrichten, Anrufe, gemeinsame Freunde bitten, mit ihm zu reden.', it: 'La trascorro in modalità crisi: messaggi, chiamate, chiedere ad amici comuni di parlargli.', pt: 'Passo em modo crise: mensagens, ligações, pedir a amigos em comum que falem com ele/ela.' }, dimension: 'D' },
      { text: { es: 'Diseño una estrategia para que vea lo increíble que soy en esa semana. Recordatorios sutiles de lo que perdería.', en: 'I design a strategy for them to see how amazing I am that week. Subtle reminders of what they\'d lose.', fr: 'Je conçois une stratégie pour qu\'il/elle voie à quel point je suis incroyable cette semaine. Des rappels subtils de ce qu\'il/elle perdrait.', de: 'Ich entwerfe eine Strategie, damit sie in dieser Woche sehen, wie toll ich bin. Subtile Erinnerungen daran, was sie verlieren würden.', it: 'Progetto una strategia affinché veda quanto sono incredibile quella settimana. Promemoria sottili di ciò che perderebbe.', pt: 'Projeto uma estratégia para que veja o quanto sou incrível nessa semana. Lembretes sutis do que perderia.' }, dimension: 'C' },
      { text: { es: 'Desaparezco completamente. Si me piden espacio, les doy todo el espacio del universo.', en: 'I disappear completely. If they ask for space, I give them all the space in the universe.', fr: 'Je disparais complètement. S\'ils demandent de l\'espace, je leur donne tout l\'espace de l\'univers.', de: 'Ich verschwinde vollständig. Wenn sie Raum verlangen, gebe ich ihnen den gesamten Raum des Universums.', it: 'Sparisco completamente. Se chiedono spazio, do loro tutto lo spazio dell\'universo.', pt: 'Desapareço completamente. Se pedirem espaço, dou todo o espaço do universo.' }, dimension: 'V' },
      { text: { es: 'Respeto el espacio, pero le escribo una vez para decir que estoy disponible cuando quiera hablar.', en: 'I respect the space but write once to say I\'m available when they want to talk.', fr: 'Je respecte l\'espace mais lui écris une fois pour dire que je suis disponible quand il/elle veut parler.', de: 'Ich respektiere den Raum, schreibe aber einmal, um zu sagen, dass ich verfügbar bin, wenn er/sie reden möchte.', it: 'Rispetto lo spazio, ma scrivo una volta per dire che sono disponibile quando vuole parlare.', pt: 'Respeito o espaço, mas escrevo uma vez para dizer que estou disponível quando quiser conversar.' }, dimension: 'T' },
    ] },
  ],
  characters: [
    { name: { es: 'El Apegado Ansioso', en: 'The Anxious Attacher', fr: 'L\'Attaché Anxieux', de: 'Der Ängstliche Anhänger', it: 'L\'Attaccato Ansioso', pt: 'O Apegado Ansioso' }, dimensions: ['D'], photo: '/characters/dependent.jpg', description: { es: 'La persona que no puede existir sin la validación constante de su pareja.', en: 'The person who cannot exist without constant validation from their partner.', fr: 'La personne qui ne peut pas exister sans la validation constante de son partenaire.', de: 'Die Person, die ohne ständige Bestätigung ihres Partners nicht existieren kann.', it: 'La persona che non può esistere senza la costante validazione del partner.', pt: 'A pessoa que não consegue existir sem a validação constante do parceiro.' }, philosophy: { es: 'Tu amor es real, pero tiene un costo: necesitar estar seguro/a constantemente. No es manipulación — es miedo. El miedo a ser suficientemente bueno/a, a que te abandonen, a que lo que sientes no sea correspondido.', en: 'Your love is real, but it comes with a cost: needing constant reassurance. It\'s not manipulation — it\'s fear. Fear of not being good enough, of being abandoned, of what you feel not being reciprocated.', fr: 'Ton amour est réel, mais il a un coût: avoir besoin d\'être rassuré(e) en permanence. Ce n\'est pas de la manipulation — c\'est de la peur. La peur de ne pas être assez bien, d\'être abandonné(e).', de: 'Deine Liebe ist real, aber sie hat einen Preis: ständige Bestätigung zu brauchen. Es ist keine Manipulation — es ist Angst. Angst, nicht gut genug zu sein, verlassen zu werden.', it: 'Il tuo amore è reale, ma ha un costo: aver bisogno di rassicurazioni costanti. Non è manipolazione — è paura. Paura di non essere abbastanza bravo/a, di essere abbandonato/a.', pt: 'Seu amor é real, mas tem um custo: precisar de reasseguramento constante. Não é manipulação — é medo. Medo de não ser suficientemente bom/boa, de ser abandonado/a.' } },
    { name: { es: 'El Controlador Invisible', en: 'The Invisible Controller', fr: 'Le Contrôleur Invisible', de: 'Der Unsichtbare Kontrolleur', it: 'Il Controllore Invisibile', pt: 'O Controlador Invisível' }, dimensions: ['C'], photo: '/characters/controller.jpg', description: { es: 'Controla sin parecer que controla. Cada decisión de su pareja pasa por su filtro.', en: 'Controls without seeming to control. Every decision their partner makes passes through their filter.', fr: 'Contrôle sans avoir l\'air de contrôler. Chaque décision de son partenaire passe par son filtre.', de: 'Kontrolliert, ohne zu kontrollieren. Jede Entscheidung des Partners geht durch sein Filter.', it: 'Controlla senza sembrare che controlli. Ogni decisione del partner passa attraverso il suo filtro.', pt: 'Controla sem parecer que controla. Cada decisão do parceiro passa pelo seu filtro.' }, philosophy: { es: 'Tu amor viene disfrazado de preocupación. No crees controlar — crees proteger. Pero hay una línea muy fina entre cuidar y poseer, y a veces la cruzas sin darte cuenta.', en: 'Your love comes disguised as concern. You don\'t think you\'re controlling — you think you\'re protecting. But there\'s a very thin line between caring and possessing, and sometimes you cross it without realizing.', fr: 'Ton amour vient déguisé en préoccupation. Tu ne penses pas contrôler — tu penses protéger. Mais il y a une ligne très fine entre prendre soin et posséder.', de: 'Deine Liebe kommt verkleidet als Sorge. Du denkst nicht, dass du kontrollierst — du denkst, du schützt. Aber es gibt eine sehr dünne Linie zwischen Fürsorge und Besitz.', it: 'Il tuo amore viene mascherato da preoccupazione. Non pensi di controllare — pensi di proteggere. Ma c\'è una linea molto sottile tra prendersi cura e possedere.', pt: 'Seu amor vem disfarçado de preocupação. Você não acha que está controlando — acha que está protegendo. Mas há uma linha muito tênue entre cuidar e possuir.' } },
    { name: { es: 'El Evasor Maestro', en: 'The Master Avoider', fr: 'Le Maître Évitant', de: 'Der Meisterausweicher', it: 'Il Maestro Evasore', pt: 'O Mestre Evasor' }, dimensions: ['V'], photo: '/characters/avoider.jpg', description: { es: 'Dice que todo está bien cuando todo está mal. Sus emociones son un misterio incluso para él/ella.', en: 'Says everything is fine when everything is wrong. Their emotions are a mystery even to themselves.', fr: 'Dit que tout va bien quand tout va mal. Ses émotions sont un mystère même pour lui/elle.', de: 'Sagt, alles ist gut, wenn alles schlecht ist. Seine Gefühle sind sogar für ihn ein Rätsel.', it: 'Dice che va tutto bene quando va tutto male. Le sue emozioni sono un mistero anche per lui/lei.', pt: 'Diz que está tudo bem quando está tudo errado. Suas emoções são um mistério até para si mesmo/a.' }, philosophy: { es: 'Aprendiste que mostrar lo que sientes es peligroso. Así que construiste un muro perfecto: siempre tranquilo/a, siempre "bien". El problema es que quienes te aman no saben cómo llegar a ti.', en: 'You learned that showing what you feel is dangerous. So you built a perfect wall: always calm, always "fine". The problem is that those who love you don\'t know how to reach you.', fr: 'Tu as appris que montrer ce que tu ressens est dangereux. Alors tu as construit un mur parfait: toujours calme, toujours "bien". Le problème c\'est que ceux qui t\'aiment ne savent pas comment t\'atteindre.', de: 'Du hast gelernt, dass es gefährlich ist, zu zeigen, was du fühlst. Also hast du eine perfekte Mauer gebaut: immer ruhig, immer "gut". Das Problem ist, dass diejenigen, die dich lieben, nicht wissen, wie sie dich erreichen können.', it: 'Hai imparato che mostrare quello che senti è pericoloso. Così hai costruito un muro perfetto: sempre tranquillo/a, sempre "bene". Il problema è che chi ti ama non sa come raggiungerti.', pt: 'Você aprendeu que mostrar o que sente é perigoso. Então construiu uma parede perfeita: sempre tranquilo/a, sempre "bem". O problema é que quem te ama não sabe como chegar até você.' } },
    { name: { es: 'La Pareja Sana', en: 'The Healthy Partner', fr: 'Le Partenaire Sain', de: 'Der Gesunde Partner', it: 'Il Partner Sano', pt: 'O Parceiro Saudável' }, dimensions: ['T'], photo: '/characters/healthy.jpg', description: { es: 'Comunicación directa, límites claros, seguridad en la relación.', en: 'Direct communication, clear boundaries, security in the relationship.', fr: 'Communication directe, limites claires, sécurité dans la relation.', de: 'Direkte Kommunikation, klare Grenzen, Sicherheit in der Beziehung.', it: 'Comunicazione diretta, limiti chiari, sicurezza nella relazione.', pt: 'Comunicação direta, limites claros, segurança no relacionamento.' }, philosophy: { es: 'Sabes que el amor no requiere control ni fusión. Confías en ti mismo/a, confías en tu pareja y cuando algo no funciona, lo dices. Eso suena simple pero es lo más difícil de lograr.', en: 'You know that love doesn\'t require control or fusion. You trust yourself, trust your partner, and when something doesn\'t work, you say it. That sounds simple but it\'s the hardest thing to achieve.', fr: 'Tu sais que l\'amour ne nécessite pas de contrôle ni de fusion. Tu te fais confiance, tu fais confiance à ton partenaire et quand quelque chose ne fonctionne pas, tu le dis.', de: 'Du weißt, dass Liebe keine Kontrolle oder Fusion erfordert. Du vertraust dir selbst, vertraust deinem Partner, und wenn etwas nicht funktioniert, sagst du es.', it: 'Sai che l\'amore non richiede controllo né fusione. Ti fidi di te stesso/a, ti fidi del tuo partner e quando qualcosa non funziona, lo dici.', pt: 'Você sabe que o amor não requer controle nem fusão. Confia em si mesmo/a, confia no parceiro e quando algo não funciona, diz. Isso parece simples mas é o mais difícil de alcançar.' } },
    { name: { es: 'El Ansioso-Controlador', en: 'The Anxious Controller', fr: 'L\'Anxieux Contrôleur', de: 'Der Ängstliche Kontrolleur', it: 'L\'Ansioso-Controllore', pt: 'O Ansioso-Controlador' }, dimensions: ['D', 'C'], photo: '/characters/anxious-control.jpg', description: { es: 'La combinación más explosiva: necesita validación constante y controla para obtenerla.', en: 'The most explosive combination: needs constant validation and controls to obtain it.', fr: 'La combinaison la plus explosive: a besoin d\'une validation constante et contrôle pour l\'obtenir.', de: 'Die explosivste Kombination: braucht ständige Bestätigung und kontrolliert, um sie zu bekommen.', it: 'La combinazione più esplosiva: ha bisogno di validazione costante e controlla per ottenerla.', pt: 'A combinação mais explosiva: precisa de validação constante e controla para obtê-la.' }, philosophy: { es: 'Tienes tanto miedo de perder al otro que lo vigilas de cerca. Tu control no es crueldad — es terror. Pero el resultado es el mismo: la persona que amas eventualmente necesita escapar.', en: 'You\'re so afraid of losing the other that you watch them closely. Your control is not cruelty — it\'s terror. But the result is the same: the person you love eventually needs to escape.', fr: 'Tu as tellement peur de perdre l\'autre que tu le surveilles de près. Ton contrôle n\'est pas de la cruauté — c\'est de la terreur. Mais le résultat est le même.', de: 'Du hast solche Angst, den anderen zu verlieren, dass du ihn genau beobachtest. Deine Kontrolle ist keine Grausamkeit — es ist Terror. Aber das Ergebnis ist dasselbe.', it: 'Hai tanta paura di perdere l\'altro che lo tieni sotto controllo. Il tuo controllo non è crudeltà — è terrore. Ma il risultato è lo stesso.', pt: 'Você tem tanto medo de perder o outro que o vigia de perto. Seu controle não é crueldade — é terror. Mas o resultado é o mesmo.' } },
    { name: { es: 'El Silencioso Calculador', en: 'The Silent Calculator', fr: 'Le Calculateur Silencieux', de: 'Der Stille Kalkulator', it: 'Il Calcolatore Silenzioso', pt: 'O Calculador Silencioso' }, dimensions: ['C', 'V'], photo: '/characters/silent-controller.jpg', description: { es: 'Controla sin hablar. La frialdad es su herramienta.', en: 'Controls without speaking. Coldness is their tool.', fr: 'Contrôle sans parler. La froideur est son outil.', de: 'Kontrolliert ohne zu sprechen. Kälte ist sein Werkzeug.', it: 'Controlla senza parlare. La freddezza è il suo strumento.', pt: 'Controla sem falar. A frieza é sua ferramenta.' }, philosophy: { es: 'Tu silencio es tu arma favorita. No pelea, simplemente desaparece emocionalmente hasta que el otro cede. Pareces desapegado/a, pero detrás de ese silencio hay una estrategia perfectamente diseñada.', en: 'Your silence is your favorite weapon. You don\'t fight — you simply disappear emotionally until the other gives in. You seem detached, but behind that silence is a perfectly designed strategy.', fr: 'Ton silence est ton arme préférée. Tu ne te bats pas, tu disparais simplement émotionnellement jusqu\'à ce que l\'autre cède. Tu sembles détaché(e), mais derrière ce silence il y a une stratégie parfaitement conçue.', de: 'Dein Schweigen ist deine Lieblingswaffe. Du kämpfst nicht — du verschwindest einfach emotional, bis der andere nachgibt. Du scheinst losgelöst, aber hinter diesem Schweigen steckt eine perfekt durchdachte Strategie.', it: 'Il tuo silenzio è la tua arma preferita. Non combatte, scompare semplicemente emotivamente finché l\'altro non cede. Sembri distaccato/a, ma dietro quel silenzio c\'è una strategia perfettamente progettata.', pt: 'Seu silêncio é sua arma favorita. Não briga, simplesmente desaparece emocionalmente até que o outro ceda. Parece desapegado/a, mas por trás desse silêncio há uma estratégia perfeitamente planejada.' } },
    { name: { es: 'El Fantasma con Apego', en: 'The Ghost with Attachment', fr: 'Le Fantôme avec Attachement', de: 'Das Gespenst mit Bindung', it: 'Il Fantasma con Attaccamento', pt: 'O Fantasma com Apego' }, dimensions: ['D', 'V'], photo: '/characters/ghost-attached.jpg', description: { es: 'Desaparece cuando le duele, pero no puede vivir sin la persona.', en: 'Disappears when hurt, but cannot live without the person.', fr: 'Disparaît quand il/elle souffre, mais ne peut pas vivre sans la personne.', de: 'Verschwindet, wenn es wehtut, kann aber ohne die Person nicht leben.', it: 'Sparisce quando soffre, ma non può vivere senza la persona.', pt: 'Desaparece quando está magoado/a, mas não consegue viver sem a pessoa.' }, philosophy: { es: 'Cuando te lastiman, huyes. Pero tampoco puedes irse de verdad. Tu danza favorita es alejarte y esperar que el otro te persiga — prueba de que le importas. Es un juego que nadie gana.', en: 'When you\'re hurt, you run. But you can\'t really leave either. Your favorite dance is to pull away and wait for the other to chase you — proof that they care. It\'s a game nobody wins.', fr: 'Quand tu souffres, tu fuis. Mais tu ne peux pas vraiment partir non plus. Ta danse favorite est de t\'éloigner et d\'attendre que l\'autre te poursuive — preuve qu\'il/elle tient à toi. C\'est un jeu que personne ne gagne.', de: 'Wenn du verletzt wirst, läufst du weg. Aber du kannst auch nicht wirklich gehen. Dein Lieblingstanz ist es, dich zu entfernen und darauf zu warten, dass der andere dich verfolgt — Beweis, dass es ihm wichtig ist. Es ist ein Spiel, das niemand gewinnt.', it: 'Quando vieni ferito/a, scappi. Ma non puoi nemmeno andartene davvero. Il tuo ballo preferito è allontanarti e aspettare che l\'altro ti insegua — prova che gli importi. È un gioco che nessuno vince.', pt: 'Quando é machucado/a, foge. Mas também não consegue ir embora de verdade. Sua dança favorita é se afastar e esperar que o outro te persiga — prova de que importa. É um jogo que ninguém ganha.' } },
    { name: { es: 'La Pareja Consciente', en: 'The Conscious Partner', fr: 'Le Partenaire Conscient', de: 'Der Bewusste Partner', it: 'Il Partner Consapevole', pt: 'O Parceiro Consciente' }, dimensions: ['T', 'V'], photo: '/characters/ideal-partner.jpg', description: { es: 'Necesita espacio pero lo comunica. Independiente pero presente.', en: 'Needs space but communicates it. Independent but present.', fr: 'A besoin d\'espace mais le communique. Indépendant(e) mais présent(e).', de: 'Braucht Raum, kommuniziert das aber. Unabhängig, aber präsent.', it: 'Ha bisogno di spazio ma lo comunica. Indipendente ma presente.', pt: 'Precisa de espaço mas comunica isso. Independente mas presente.' }, philosophy: { es: 'Valoras tu independencia y la independencia de tu pareja. A veces te cuesta pedir lo que necesitas, pero cuando lo haces, lo dices claramente. Eres el tipo de persona con quien construir algo real.', en: 'You value your independence and your partner\'s. Sometimes it\'s hard to ask for what you need, but when you do, you say it clearly. You\'re the type of person to build something real with.', fr: 'Tu valorises ton indépendance et celle de ton partenaire. Parfois il t\'est difficile de demander ce dont tu as besoin, mais quand tu le fais, tu le dis clairement.', de: 'Du schätzt deine Unabhängigkeit und die deines Partners. Manchmal fällt es dir schwer, um das zu bitten, was du brauchst, aber wenn du es tust, sagst du es klar.', it: 'Valorizzi la tua indipendenza e quella del tuo partner. A volte è difficile chiedere quello di cui hai bisogno, ma quando lo fai, lo dici chiaramente.', pt: 'Você valoriza sua independência e a do seu parceiro. Às vezes é difícil pedir o que precisa, mas quando o faz, diz claramente. Você é o tipo de pessoa com quem construir algo real.' } },
  ],
};

export async function seedToxic(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'toxic' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'toxic',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['dark-personality'],
      sortOrder: 2,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
