import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tan fiel eres?', en: 'How faithful are you?', fr: 'À quel point es-tu fidèle ?', de: 'Wie treu bist du?', it: 'Quanto sei fedele?', pt: 'O quanto você é fiel?' },
  description: { es: 'La fidelidad no es solo no engañar. Es lo que piensas, haces y eliges cuando nadie mira.', en: 'Faithfulness is not just about not cheating. It\'s what you think, do, and choose when nobody is watching.', fr: 'La fidélité ne consiste pas seulement à ne pas tromper. C\'est ce que tu penses, fais et choisis quand personne ne regarde.', de: 'Treue bedeutet nicht nur nicht zu betrügen. Es geht darum, was du denkst, tust und wählst, wenn niemand zuschaut.', it: 'La fedeltà non consiste solo nel non tradire. È ciò che pensi, fai e scegli quando nessuno guarda.', pt: 'A fidelidade não é apenas não trair. É o que você pensa, faz e escolhe quando ninguém está olhando.' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { F: 'Fidelidad', T: 'Tentación', A: 'Ambigüedad', C: 'Compromiso' },
    en: { F: 'Fidelity', T: 'Temptation', A: 'Ambiguity', C: 'Commitment' },
    fr: { F: 'Fidélité', T: 'Tentation', A: 'Ambiguïté', C: 'Engagement' },
    de: { F: 'Treue', T: 'Versuchung', A: 'Ambiguität', C: 'Engagement' },
    it: { F: 'Fedeltà', T: 'Tentazione', A: 'Ambiguità', C: 'Impegno' },
    pt: { F: 'Fidelidade', T: 'Tentação', A: 'Ambiguidade', C: 'Compromisso' },
  },
  questions: [
    { id: 1, situation: { es: 'Alguien muy atractivo flirtea contigo. Tu pareja no está y no lo sabrá nunca.', en: 'Someone very attractive flirts with you. Your partner isn\'t there and will never know.', fr: 'Quelqu\'un de très attrayant flirte avec toi. Ton/ta partenaire n\'est pas là et ne le saura jamais.', de: 'Jemand sehr Attraktives flirtet mit dir. Dein Partner/deine Partnerin ist nicht da und wird es nie erfahren.', it: 'Qualcuno di molto attraente flirta con te. Il tuo partner non c\'è e non lo saprà mai.', pt: 'Alguém muito atraente flerta com você. Seu parceiro não está e nunca saberá.' }, options: [
      { text: { es: 'Lo disfruto, flirteo de vuelta. ¿Qué hay de malo en eso?', en: 'I enjoy it, flirt back. What\'s wrong with that?', fr: 'J\'en profite, je flirte en retour. Quel mal y a-t-il à ça ?', de: 'Ich genieße es, flirte zurück. Was ist daran falsch?', it: 'Mi diverte, flirto di ritorno. Cos\'ha di sbagliato?', pt: 'Aproveito, flerto de volta. O que há de errado nisso?' }, dimension: 'T' },
      { text: { es: 'Flirteo levemente pero sin cruzar líneas. Inocente, me digo.', en: 'I flirt lightly but without crossing lines. Innocent, I tell myself.', fr: 'Je flirte légèrement mais sans franchir de lignes. Innocent, je me dis.', de: 'Ich flirte leicht, aber ohne Grenzen zu überschreiten. Harmlos, sage ich mir.', it: 'Flirto leggermente ma senza attraversare linee. Innocente, mi dico.', pt: 'Flerto levemente mas sem cruzar limites. Inocente, me digo.' }, dimension: 'A' },
      { text: { es: 'Lo corto rápido. No me interesa ese tipo de interacciones.', en: 'I cut it short. I\'m not interested in that kind of interaction.', fr: 'Je coupe court. Ce type d\'interactions ne m\'intéresse pas.', de: 'Ich beende es schnell. Ich bin nicht an dieser Art von Interaktionen interessiert.', it: 'Lo taglio corto. Non mi interessano quel tipo di interazioni.', pt: 'Corto rápido. Não me interessam esse tipo de interações.' }, dimension: 'F' },
      { text: { es: 'Se lo cuento a mi pareja después. Prefiero ser transparente.', en: 'I tell my partner afterward. I prefer to be transparent.', fr: 'Je le dis à mon/ma partenaire après. Je préfère être transparent(e).', de: 'Ich erzähle es meinem Partner/meiner Partnerin danach. Ich bevorzuge Transparenz.', it: 'Lo dico al mio partner dopo. Preferisco essere trasparente.', pt: 'Conto ao meu parceiro depois. Prefiro ser transparente.' }, dimension: 'C' },
    ] },
    { id: 2, situation: { es: 'Tu relación pasa por un momento difícil. Alguien más te hace sentir exactamente lo que te falta.', en: 'Your relationship is going through a difficult time. Someone else makes you feel exactly what you\'re missing.', fr: 'Ta relation traverse un moment difficile. Quelqu\'un d\'autre te fait ressentir exactement ce qui te manque.', de: 'Deine Beziehung geht durch eine schwierige Phase. Jemand anderes lässt dich genau das fühlen, was dir fehlt.', it: 'La tua relazione attraversa un momento difficile. Qualcun altro ti fa sentire esattamente quello che ti manca.', pt: 'Seu relacionamento passa por um momento difícil. Outra pessoa te faz sentir exatamente o que está faltando.' }, options: [
      { text: { es: 'Me dejo llevar. Los momentos difíciles crean vulnerabilidades reales.', en: 'I let myself be carried away. Difficult moments create real vulnerabilities.', fr: 'Je me laisse emporter. Les moments difficiles créent de vraies vulnérabilités.', de: 'Ich lasse mich mitreißen. Schwierige Momente schaffen echte Verletzlichkeiten.', it: 'Mi lascio trasportare. I momenti difficili creano vulnerabilità reali.', pt: 'Me deixo levar. Momentos difíceis criam vulnerabilidades reais.' }, dimension: 'T' },
      { text: { es: 'Me permito la conexión emocional aunque me digo que no es infidelidad.', en: 'I allow the emotional connection even though I tell myself it\'s not infidelity.', fr: 'Je me permets la connexion émotionnelle même si je me dis que ce n\'est pas de l\'infidélité.', de: 'Ich erlaube mir die emotionale Verbindung, obwohl ich mir sage, dass es keine Untreue ist.', it: 'Mi permetto la connessione emotiva anche se mi dico che non è infedeltà.', pt: 'Me permito a conexão emocional embora me diga que não é infidelidade.' }, dimension: 'A' },
      { text: { es: 'Reconozco lo que falta en mi relación y lo trabajo desde adentro.', en: 'I recognize what\'s missing in my relationship and work on it from within.', fr: 'Je reconnais ce qui manque dans ma relation et je travaille dessus de l\'intérieur.', de: 'Ich erkenne, was in meiner Beziehung fehlt, und arbeite von innen daran.', it: 'Riconosco cosa manca nella mia relazione e ci lavoro dall\'interno.', pt: 'Reconheço o que falta no meu relacionamento e trabalho nisso por dentro.' }, dimension: 'F' },
      { text: { es: 'Hablo con mi pareja sobre lo que me falta. Si no se puede resolver, hablo de eso también.', en: 'I talk to my partner about what I\'m missing. If it can\'t be resolved, I talk about that too.', fr: 'Je parle à mon/ma partenaire de ce qui me manque. Si ça ne peut pas être résolu, j\'en parle aussi.', de: 'Ich spreche mit meinem Partner/meiner Partnerin darüber, was mir fehlt. Wenn es nicht gelöst werden kann, spreche ich auch darüber.', it: 'Parlo con il mio partner di ciò che mi manca. Se non si può risolvere, ne parlo anche di questo.', pt: 'Falo com meu parceiro sobre o que está faltando. Se não puder ser resolvido, falo sobre isso também.' }, dimension: 'C' },
    ] },
    { id: 3, situation: { es: '¿Cómo defines infidelidad en una relación?', en: 'How do you define infidelity in a relationship?', fr: 'Comment définis-tu l\'infidélité dans une relation ?', de: 'Wie definierst du Untreue in einer Beziehung?', it: 'Come definisci l\'infedeltà in una relazione?', pt: 'Como você define infidelidade em um relacionamento?' }, options: [
      { text: { es: 'Solo el acto físico. Lo emocional es complicado de delimitar.', en: 'Only the physical act. The emotional is complicated to define.', fr: 'Seulement l\'acte physique. L\'émotionnel est compliqué à délimiter.', de: 'Nur der körperliche Akt. Das Emotionale ist schwer zu begrenzen.', it: 'Solo l\'atto fisico. L\'emotivo è complicato da delimitare.', pt: 'Apenas o ato físico. O emocional é complicado de delimitar.' }, dimension: 'T' },
      { text: { es: 'Depende de lo que cada pareja acuerda. No hay una definición universal.', en: 'Depends on what each couple agrees on. There\'s no universal definition.', fr: 'Ça dépend de ce que chaque couple s\'accorde. Il n\'y a pas de définition universelle.', de: 'Hängt davon ab, was jedes Paar vereinbart. Es gibt keine universelle Definition.', it: 'Dipende da ciò che ogni coppia si accorda. Non c\'è una definizione universale.', pt: 'Depende do que cada casal acorda. Não há definição universal.' }, dimension: 'A' },
      { text: { es: 'Cualquier cosa que haría de forma diferente si mi pareja estuviera presente.', en: 'Anything I would do differently if my partner were present.', fr: 'Tout ce que je ferais différemment si mon/ma partenaire était présent(e).', de: 'Alles, was ich anders tun würde, wenn mein Partner/meine Partnerin anwesend wäre.', it: 'Qualsiasi cosa che farei diversamente se il mio partner fosse presente.', pt: 'Qualquer coisa que eu faria de forma diferente se meu parceiro estivesse presente.' }, dimension: 'F' },
      { text: { es: 'Romper el acuerdo explícito o implícito de exclusividad que construimos juntos.', en: 'Breaking the explicit or implicit exclusivity agreement we built together.', fr: 'Rompre l\'accord explicite ou implicite d\'exclusivité que nous avons construit ensemble.', de: 'Den expliziten oder impliziten Exklusivitätsvertrag zu brechen, den wir gemeinsam aufgebaut haben.', it: 'Rompere l\'accordo esplicito o implicito di esclusività che abbiamo costruito insieme.', pt: 'Romper o acordo explícito ou implícito de exclusividade que construímos juntos.' }, dimension: 'C' },
    ] },
    { id: 4, situation: { es: 'Tienes una amistad cercana con alguien que claramente tiene interés romántico en ti.', en: 'You have a close friendship with someone who clearly has romantic interest in you.', fr: 'Tu as une amitié proche avec quelqu\'un qui a clairement un intérêt romantique pour toi.', de: 'Du hast eine enge Freundschaft mit jemandem, der offensichtlich romantisches Interesse an dir hat.', it: 'Hai un\'amicizia stretta con qualcuno che chiaramente ha un interesse romantico per te.', pt: 'Você tem uma amizade próxima com alguém que claramente tem interesse romântico em você.' }, options: [
      { text: { es: 'Lo disfruto. La atención se siente bien aunque no actúe sobre ello.', en: 'I enjoy it. The attention feels good even if I don\'t act on it.', fr: 'J\'en profite. L\'attention se sent bien même si je n\'agis pas dessus.', de: 'Ich genieße es. Die Aufmerksamkeit fühlt sich gut an, auch wenn ich nicht darauf eingehe.', it: 'Mi diverte. L\'attenzione si sente bene anche se non agisco su di essa.', pt: 'Aproveito. A atenção se sente bem mesmo não agindo sobre isso.' }, dimension: 'T' },
      { text: { es: 'Mantengo la amistad pero no hago nada para que baje de intensidad.', en: 'I maintain the friendship but don\'t do anything to lower the intensity.', fr: 'Je maintiens l\'amitié mais ne fais rien pour en diminuer l\'intensité.', de: 'Ich halte die Freundschaft aufrecht, tue aber nichts, um die Intensität zu verringern.', it: 'Mantengo l\'amicizia ma non faccio nulla perché diminuisca di intensità.', pt: 'Mantenho a amizade mas não faço nada para que baixe de intensidade.' }, dimension: 'A' },
      { text: { es: 'Pongo límites claros a esa persona aunque incomode la dinámica.', en: 'I set clear limits with that person even if it makes the dynamic uncomfortable.', fr: 'Je pose des limites claires à cette personne même si ça met la dynamique mal à l\'aise.', de: 'Ich setze dieser Person klare Grenzen, auch wenn es die Dynamik unbequem macht.', it: 'Pongo limiti chiari a quella persona anche se rende la dinamica scomoda.', pt: 'Coloco limites claros com essa pessoa mesmo que incomode a dinâmica.' }, dimension: 'F' },
      { text: { es: 'Se lo cuento a mi pareja y hablamos sobre cómo manejarlo.', en: 'I tell my partner and we talk about how to handle it.', fr: 'Je le dis à mon/ma partenaire et nous parlons de comment le gérer.', de: 'Ich erzähle es meinem Partner/meiner Partnerin und wir reden darüber, wie man damit umgeht.', it: 'Lo dico al mio partner e parliamo di come gestirlo.', pt: 'Conto ao meu parceiro e conversamos sobre como lidar.' }, dimension: 'C' },
    ] },
    { id: 5, situation: { es: 'Estás de viaje solo/a. Alguien te propone algo explícito. ¿Cuál es tu respuesta interior?', en: 'You\'re traveling alone. Someone proposes something explicit. What is your inner response?', fr: 'Tu es en voyage seul(e). Quelqu\'un te propose quelque chose d\'explicite. Quelle est ta réponse intérieure ?', de: 'Du reist allein. Jemand schlägt etwas Explizites vor. Was ist deine innere Reaktion?', it: 'Sei in viaggio da solo/a. Qualcuno ti propone qualcosa di esplicito. Qual è la tua risposta interiore?', pt: 'Você está viajando sozinho/a. Alguém propõe algo explícito. Qual é sua resposta interior?' }, options: [
      { text: { es: 'Hay una parte de mí que evalúa seriamente si hacerlo.', en: 'There\'s a part of me that seriously evaluates doing it.', fr: 'Il y a une partie de moi qui évalue sérieusement de le faire.', de: 'Es gibt einen Teil von mir, der ernsthaft abwägt, es zu tun.', it: 'C\'è una parte di me che valuta seriamente se farlo.', pt: 'Há uma parte de mim que avalia seriamente se fazer isso.' }, dimension: 'T' },
      { text: { es: 'No lo haría, pero reconozco que la tentación existe.', en: 'I wouldn\'t do it, but I acknowledge the temptation exists.', fr: 'Je ne le ferais pas, mais je reconnais que la tentation existe.', de: 'Ich würde es nicht tun, aber ich erkenne, dass die Versuchung existiert.', it: 'Non lo farei, ma riconosco che la tentazione esiste.', pt: 'Não faria, mas reconheço que a tentação existe.' }, dimension: 'A' },
      { text: { es: 'No. No lo necesito y no quiero cargar con eso.', en: 'No. I don\'t need it and I don\'t want to carry that.', fr: 'Non. Je n\'en ai pas besoin et je ne veux pas porter ça.', de: 'Nein. Ich brauche es nicht und will das nicht tragen.', it: 'No. Non ne ho bisogno e non voglio portarmi questo.', pt: 'Não. Não preciso disso e não quero carregar isso.' }, dimension: 'F' },
      { text: { es: 'No. Y me pregunto si debo contarle a mi pareja que pasó aunque no haya hecho nada.', en: 'No. And I wonder if I should tell my partner it happened even though I didn\'t do anything.', fr: 'Non. Et je me demande si je dois dire à mon/ma partenaire que ça s\'est passé même si je n\'ai rien fait.', de: 'Nein. Und ich frage mich, ob ich meinem Partner/meiner Partnerin sagen soll, dass es passiert ist, auch wenn ich nichts getan habe.', it: 'No. E mi chiedo se devo dire al mio partner che è successo anche se non ho fatto nulla.', pt: 'Não. E me pergunto se devo contar ao meu parceiro que aconteceu mesmo não tendo feito nada.' }, dimension: 'C' },
    ] },
    { id: 6, situation: { es: 'Un ex significativo vuelve a tu vida buscando reconectar.', en: 'A significant ex comes back into your life looking to reconnect.', fr: 'Un(e) ex significatif/ve revient dans ta vie pour reconnecter.', de: 'Ein bedeutender Ex kommt wieder in dein Leben, um eine Verbindung herzustellen.', it: 'Un ex significativo torna nella tua vita cercando di riconnettersi.', pt: 'Um ex significativo volta à sua vida buscando reconectar.' }, options: [
      { text: { es: 'Hay algo que sigue ahí. Lo exploraría discretamente.', en: 'There\'s something still there. I\'d explore it discreetly.', fr: 'Il y a quelque chose qui est toujours là. Je l\'explorerais discrètement.', de: 'Da ist noch etwas. Ich würde es diskret erkunden.', it: 'C\'è qualcosa che è ancora lì. Lo esplorerei discretamente.', pt: 'Há algo que ainda existe. Exploraria discretamente.' }, dimension: 'T' },
      { text: { es: 'Reconecto a nivel amistoso aunque sé que hay algo más en el aire.', en: 'I reconnect on a friendly level even though I know there\'s something more in the air.', fr: 'Je reconnecte à un niveau amical même si je sais qu\'il y a quelque chose de plus dans l\'air.', de: 'Ich verbinde mich auf freundschaftlicher Ebene, obwohl ich weiß, dass etwas mehr in der Luft liegt.', it: 'Mi riconnetto a livello amichevole anche se so che c\'è qualcosa di più nell\'aria.', pt: 'Reconecto em nível amistoso embora saiba que há algo mais no ar.' }, dimension: 'A' },
      { text: { es: 'Establezco límites claros desde el principio.', en: 'I establish clear boundaries from the start.', fr: 'J\'établis des limites claires depuis le début.', de: 'Ich setze von Anfang an klare Grenzen.', it: 'Stabilisco limiti chiari fin dall\'inizio.', pt: 'Estabeleço limites claros desde o princípio.' }, dimension: 'F' },
      { text: { es: 'Se lo comento a mi pareja antes de tener cualquier tipo de contacto.', en: 'I mention it to my partner before having any type of contact.', fr: 'Je le mentionne à mon/ma partenaire avant d\'avoir tout type de contact.', de: 'Ich erwähne es meinem Partner/meiner Partnerin, bevor ich irgendeinen Kontakt aufnehme.', it: 'Lo menziono al mio partner prima di avere qualsiasi tipo di contatto.', pt: 'Comento ao meu parceiro antes de ter qualquer tipo de contato.' }, dimension: 'C' },
    ] },
    { id: 7, situation: { es: 'Guardas un secreto emocional de tu pareja. ¿Qué es eso para ti?', en: 'You keep an emotional secret from your partner. What is that to you?', fr: 'Tu gardes un secret émotionnel de ton/ta partenaire. Qu\'est-ce que c\'est pour toi ?', de: 'Du bewahrst ein emotionales Geheimnis vor deinem Partner/deiner Partnerin. Was ist das für dich?', it: 'Tieni un segreto emotivo dal tuo partner. Cos\'è per te?', pt: 'Você guarda um segredo emocional do seu parceiro. O que isso é para você?' }, options: [
      { text: { es: 'Hay cosas que es mejor no contar. La privacidad no es infidelidad.', en: 'There are things better left unsaid. Privacy is not infidelity.', fr: 'Il y a des choses qu\'il vaut mieux ne pas raconter. La vie privée n\'est pas de l\'infidélité.', de: 'Es gibt Dinge, die besser ungesagt bleiben. Privatsphäre ist keine Untreue.', it: 'Ci sono cose che è meglio non raccontare. La privacy non è infedeltà.', pt: 'Há coisas que é melhor não contar. Privacidade não é infidelidade.' }, dimension: 'T' },
      { text: { es: 'No es infidelidad en sí, pero reconozco que genera una distancia real.', en: 'It\'s not infidelity in itself, but I recognize it creates real distance.', fr: 'Ce n\'est pas de l\'infidélité en soi, mais je reconnais que ça génère une vraie distance.', de: 'Es ist keine Untreue an sich, aber ich erkenne, dass es eine echte Distanz schafft.', it: 'Non è infedeltà di per sé, ma riconosco che genera una distanza reale.', pt: 'Não é infidelidade em si, mas reconheço que gera uma distância real.' }, dimension: 'A' },
      { text: { es: 'No los guardo. La transparencia emocional es parte de la fidelidad para mí.', en: 'I don\'t keep them. Emotional transparency is part of faithfulness for me.', fr: 'Je ne les garde pas. La transparence émotionnelle fait partie de la fidélité pour moi.', de: 'Ich bewahre sie nicht auf. Emotionale Transparenz ist für mich Teil der Treue.', it: 'Non li tengo. La trasparenza emotiva è parte della fedeltà per me.', pt: 'Não os guardo. A transparência emocional é parte da fidelidade para mim.' }, dimension: 'F' },
      { text: { es: 'Depende del secreto. Pero en general, prefiero la apertura.', en: 'Depends on the secret. But in general, I prefer openness.', fr: 'Ça dépend du secret. Mais en général, je préfère l\'ouverture.', de: 'Kommt auf das Geheimnis an. Aber im Allgemeinen bevorzuge ich Offenheit.', it: 'Dipende dal segreto. Ma in generale, preferisco l\'apertura.', pt: 'Depende do segredo. Mas em geral, prefiro a abertura.' }, dimension: 'C' },
    ] },
    { id: 8, situation: { es: '¿Cuánto pesas las consecuencias de una infidelidad antes de actuar?', en: 'How much do you weigh the consequences of infidelity before acting?', fr: 'Dans quelle mesure peuses-tu les conséquences d\'une infidélité avant d\'agir ?', de: 'Wie viel wägst du die Konsequenzen einer Untreue ab, bevor du handelst?', it: 'Quanto pesi le conseguenze di un\'infedeltà prima di agire?', pt: 'Quanto você pondera as consequências de uma infidelidade antes de agir?' }, options: [
      { text: { es: 'Si soy honesto/a, en el momento las consecuencias se vuelven abstractas.', en: 'If I\'m honest, in the moment consequences become abstract.', fr: 'Si je suis honnête(e), dans le moment les conséquences deviennent abstraites.', de: 'Wenn ich ehrlich bin, werden in dem Moment die Konsequenzen abstrakt.', it: 'Se sono onesto/a, nel momento le conseguenze diventano astratte.', pt: 'Se sou honesto/a, no momento as consequências se tornam abstratas.' }, dimension: 'T' },
      { text: { es: 'Las pienso, pero a veces la racionalización gana.', en: 'I think about them, but sometimes rationalization wins.', fr: 'Je les pense, mais parfois la rationalisation gagne.', de: 'Ich denke darüber nach, aber manchmal gewinnt die Rationalisierung.', it: 'Le penso, ma a volte la razionalizzazione vince.', pt: 'As penso, mas às vezes a racionalização vence.' }, dimension: 'A' },
      { text: { es: 'Mucho. Y eso suele ser suficiente para no actuar.', en: 'A lot. And that is usually enough not to act.', fr: 'Beaucoup. Et c\'est généralement suffisant pour ne pas agir.', de: 'Viel. Und das reicht normalerweise, um nicht zu handeln.', it: 'Molto. E di solito è sufficiente per non agire.', pt: 'Muito. E isso geralmente é suficiente para não agir.' }, dimension: 'F' },
      { text: { es: 'Las consecuencias son relevantes, pero no son la principal razón para ser fiel.', en: 'Consequences are relevant, but they\'re not the main reason to be faithful.', fr: 'Les conséquences sont pertinentes, mais ce n\'est pas la principale raison d\'être fidèle.', de: 'Die Konsequenzen sind relevant, aber sie sind nicht der Hauptgrund für Treue.', it: 'Le conseguenze sono rilevanti, ma non sono la ragione principale per essere fedele.', pt: 'As consequências são relevantes, mas não são a principal razão para ser fiel.' }, dimension: 'C' },
    ] },
    { id: 9, situation: { es: 'Sabes que tu pareja tuvo una microinfidelidad pero no sabe que la viste.', en: 'You know your partner had a micro-infidelity but they don\'t know you saw it.', fr: 'Tu sais que ton/ta partenaire a eu une micro-infidélité mais il/elle ne sait pas que tu l\'as vue.', de: 'Du weißt, dass dein Partner/deine Partnerin eine Mikro-Untreue hatte, aber er/sie weiß nicht, dass du es gesehen hast.', it: 'Sai che il tuo partner ha avuto una micro-infedeltà ma non sa che l\'hai vista.', pt: 'Você sabe que seu parceiro teve uma micro-infidelidade mas não sabe que você viu.' }, options: [
      { text: { es: 'No digo nada. Si no fue tan grave, ¿para qué generar conflicto?', en: 'I say nothing. If it wasn\'t that serious, why generate conflict?', fr: 'Je ne dis rien. Si ce n\'était pas si grave, pourquoi générer un conflit ?', de: 'Ich sage nichts. Wenn es nicht so ernst war, warum einen Konflikt erzeugen?', it: 'Non dico nulla. Se non era così grave, perché generare conflitto?', pt: 'Não digo nada. Se não foi tão grave, por que gerar conflito?' }, dimension: 'T' },
      { text: { es: 'La proceso internamente antes de decidir si lo digo.', en: 'I process it internally before deciding whether to say it.', fr: 'Je la traite intérieurement avant de décider si je le dis.', de: 'Ich verarbeite es innerlich, bevor ich entscheide, ob ich es sage.', it: 'La processo internamente prima di decidere se dirlo.', pt: 'Processo internamente antes de decidir se digo.' }, dimension: 'A' },
      { text: { es: 'Se lo digo. Las cosas pequeñas que se acumulan se convierten en grandes.', en: 'I tell them. Small things that accumulate become big ones.', fr: 'Je le lui dis. Les petites choses qui s\'accumulent deviennent grandes.', de: 'Ich sage es ihm/ihr. Kleine Dinge, die sich anhäufen, werden zu großen.', it: 'Glielo dico. Le cose piccole che si accumulano diventano grandi.', pt: 'Digo. As coisas pequenas que se acumulam se tornam grandes.' }, dimension: 'F' },
      { text: { es: 'Se lo digo porque necesito que hablemos sobre qué significa para nosotros.', en: 'I tell them because I need us to talk about what it means for us.', fr: 'Je le lui dis parce que j\'ai besoin que nous parlions de ce que ça signifie pour nous.', de: 'Ich sage es, weil ich brauche, dass wir darüber sprechen, was es für uns bedeutet.', it: 'Glielo dico perché ho bisogno che parli con me di cosa significa per noi.', pt: 'Digo porque preciso que conversemos sobre o que isso significa para nós.' }, dimension: 'C' },
    ] },
    { id: 10, situation: { es: 'Si descubrieras que nunca te atraparían, ¿cambiaría tu comportamiento en una relación?', en: 'If you discovered you\'d never be caught, would your behavior in a relationship change?', fr: 'Si tu découvrais qu\'on ne t\'attraperait jamais, ton comportement dans une relation changerait-il ?', de: 'Wenn du herausfinden würdest, dass du nie erwischt werden würdest, würde sich dein Verhalten in einer Beziehung ändern?', it: 'Se scoprissi che non ti scoprirebbero mai, cambierebbe il tuo comportamento in una relazione?', pt: 'Se descobrisse que nunca seria pego/a, seu comportamento em um relacionamento mudaria?' }, options: [
      { text: { es: 'Sería ingenuo negar que cambia algo. La posibilidad de ser descubierto disuade.', en: 'It would be naive to deny something changes. The possibility of being caught deters.', fr: 'Ce serait naïf de nier que quelque chose change. La possibilité d\'être découvert(e) dissuade.', de: 'Es wäre naiv zu leugnen, dass sich etwas ändert. Die Möglichkeit, entdeckt zu werden, schreckt ab.', it: 'Sarebbe ingenuo negare che qualcosa cambia. La possibilità di essere scoperto dissuade.', pt: 'Seria ingênuo negar que algo muda. A possibilidade de ser descoberto/a dissuade.' }, dimension: 'T' },
      { text: { es: 'No mucho, pero quizás tomaría riesgos emocionales que ahora no tomo.', en: 'Not much, but perhaps I\'d take emotional risks I currently don\'t take.', fr: 'Pas beaucoup, mais peut-être que je prendrais des risques émotionnels que je ne prends pas maintenant.', de: 'Nicht viel, aber vielleicht würde ich emotionale Risiken eingehen, die ich jetzt nicht eingehe.', it: 'Non molto, ma forse prenderei rischi emotivi che ora non prendo.', pt: 'Não muito, mas talvez tomaria riscos emocionais que agora não tomo.' }, dimension: 'A' },
      { text: { es: 'No. No soy fiel por miedo a que me atrapen.', en: 'No. I\'m not faithful because I\'m afraid of being caught.', fr: 'Non. Je ne suis pas fidèle par peur d\'être attrapé(e).', de: 'Nein. Ich bin nicht treu aus Angst vor Entdeckung.', it: 'No. Non sono fedele per paura di essere scoperto/a.', pt: 'Não. Não sou fiel por medo de ser pego/a.' }, dimension: 'F' },
      { text: { es: 'No. El compromiso no es una jaula — es una elección que haría igual.', en: 'No. Commitment is not a cage — it\'s a choice I\'d make regardless.', fr: 'Non. L\'engagement n\'est pas une cage — c\'est un choix que je ferais quand même.', de: 'Nein. Engagement ist kein Käfig — es ist eine Wahl, die ich trotzdem treffen würde.', it: 'No. L\'impegno non è una gabbia — è una scelta che farei comunque.', pt: 'Não. O compromisso não é uma gaiola — é uma escolha que faria da mesma forma.' }, dimension: 'C' },
    ] },
  ],
  characters: [
    { name: { es: 'El Tentado Frecuente', en: 'The Frequently Tempted', fr: 'Le Tenté Fréquent', de: 'Der Häufig Versuchte', it: 'Il Tentato Frequente', pt: 'O Tentado Frequente' }, dimensions: ['T'], photo: '/characters/frequently-tempted.jpg', description: { es: 'La tentación lo visita mucho y a veces la invita.', en: 'Temptation visits them often and sometimes they invite it in.', fr: 'La tentation lui rend souvent visite et parfois il/elle l\'invite.', de: 'Die Versuchung besucht ihn/sie oft und manchmal lädt er/sie sie ein.', it: 'La tentazione lo visita spesso e a volte la invita.', pt: 'A tentação o visita muito e às vezes a convida.' }, philosophy: { es: 'No eres infiel por maldad — eres alguien para quien la fidelidad requiere un esfuerzo consciente real. Eso no es una excusa, pero sí es una información útil sobre qué necesitas trabajar para que tu relación sea sostenible.', en: 'You\'re not unfaithful out of malice — you\'re someone for whom faithfulness requires real conscious effort. That\'s not an excuse, but it is useful information about what you need to work on for your relationship to be sustainable.', fr: 'Tu n\'es pas infidèle par méchanceté — tu es quelqu\'un pour qui la fidélité nécessite un vrai effort conscient. Ce n\'est pas une excuse, mais c\'est une information utile sur ce que tu dois travailler pour que ta relation soit durable.', de: 'Du bist nicht untreu aus Bosheit — du bist jemand, für den Treue echte bewusste Anstrengung erfordert. Das ist keine Entschuldigung, aber es ist nützliche Information darüber, woran du arbeiten musst, damit deine Beziehung nachhaltig ist.', it: 'Non sei infedele per cattiveria — sei qualcuno per cui la fedeltà richiede un vero sforzo conscio. Non è una scusa, ma è un\'informazione utile su cosa devi lavorare perché la tua relazione sia sostenibile.', pt: 'Você não é infiel por maldade — é alguém para quem a fidelidade requer um esforço consciente real. Isso não é uma desculpa, mas é uma informação útil sobre o que você precisa trabalhar para que seu relacionamento seja sustentável.' } },
    { name: { es: 'El Navegante Ambiguo', en: 'The Ambiguous Navigator', fr: 'Le Navigateur Ambigu', de: 'Der Ambige Navigator', it: 'Il Navigatore Ambiguo', pt: 'O Navegante Ambíguo' }, dimensions: ['A'], photo: '/characters/ambiguous-navigator.jpg', description: { es: 'Vive en la zona gris. Dice que no cruza líneas pero dibuja las líneas muy lejos.', en: 'Lives in the gray zone. Says they don\'t cross lines but draws the lines very far.', fr: 'Vit dans la zone grise. Dit qu\'il/elle ne franchit pas de lignes mais dessine les lignes très loin.', de: 'Lebt in der Grauzone. Sagt, er/sie überschreitet keine Grenzen, zieht die Grenzen aber sehr weit.', it: 'Vive nella zona grigia. Dice di non attraversare linee ma disegna le linee molto lontano.', pt: 'Vive na zona cinzenta. Diz que não cruza limites mas desenha os limites muito longe.' }, philosophy: { es: 'Eres especialista en la zona gris. No engañas exactamente — pero construyes situaciones que se parecen mucho a ello. "No pasó nada" es técnicamente verdad pero funciona como escudo para cosas que sí tienen nombre.', en: 'You\'re a specialist in the gray zone. You don\'t exactly cheat — but you build situations that look a lot like it. "Nothing happened" is technically true but works as a shield for things that do have a name.', fr: 'Tu es spécialiste de la zone grise. Tu ne trompes pas exactement — mais tu construis des situations qui y ressemblent beaucoup. "Il ne s\'est rien passé" est techniquement vrai mais fonctionne comme un bouclier pour des choses qui ont bien un nom.', de: 'Du bist Spezialist in der Grauzone. Du betrügst nicht genau — aber du baust Situationen auf, die ihm sehr ähnlich sehen. "Es ist nichts passiert" ist technisch wahr, funktioniert aber als Schild für Dinge, die durchaus einen Namen haben.', it: 'Sei uno specialista della zona grigia. Non tradisci esattamente — ma costruisci situazioni che ci somigliano molto. "Non è successo nulla" è tecnicamente vero ma funziona come scudo per cose che hanno un nome.', pt: 'Você é especialista na zona cinzenta. Não trai exatamente — mas constrói situações que se parecem muito com isso. "Não aconteceu nada" é tecnicamente verdade mas funciona como escudo para coisas que têm nome.' } },
    { name: { es: 'El Fiel por Convicción', en: 'The Faithful by Conviction', fr: 'Le Fidèle par Conviction', de: 'Der Treue aus Überzeugung', it: 'Il Fedele per Convinzione', pt: 'O Fiel por Convicção' }, dimensions: ['F'], photo: '/characters/conviction-faithful.jpg', description: { es: 'No es fiel por miedo — es fiel porque eso es quien es.', en: 'Not faithful out of fear — faithful because that\'s who they are.', fr: 'Pas fidèle par peur — fidèle parce que c\'est qui il/elle est.', de: 'Nicht treu aus Angst — treu, weil das ist, wer er/sie ist.', it: 'Non fedele per paura — fedele perché è chi è.', pt: 'Não é fiel por medo — é fiel porque é quem é.' }, philosophy: { es: 'Tu fidelidad no depende de si te van a atrapar o no. Viene de un lugar más profundo: un sentido de quién eres y cómo quieres relacionarte. Eso es más difícil de mantener pero también más sólido.', en: 'Your faithfulness doesn\'t depend on whether you\'ll be caught or not. It comes from a deeper place: a sense of who you are and how you want to relate. That\'s harder to maintain but also more solid.', fr: 'Ta fidélité ne dépend pas de si tu vas être attrapé(e) ou non. Elle vient d\'un endroit plus profond : un sens de qui tu es et comment tu veux te lier. C\'est plus difficile à maintenir mais aussi plus solide.', de: 'Deine Treue hängt nicht davon ab, ob du erwischt wirst oder nicht. Sie kommt von einem tieferen Ort: einem Sinn für wer du bist und wie du dich verhalten willst. Das ist schwerer aufrechtzuerhalten, aber auch solider.', it: 'La tua fedeltà non dipende dal fatto che ti scopriranno o meno. Viene da un posto più profondo: un senso di chi sei e come vuoi relazionarti. È più difficile da mantenere ma anche più solido.', pt: 'Sua fidelidade não depende de ser pego/a ou não. Vem de um lugar mais profundo: um senso de quem você é e como quer se relacionar. Isso é mais difícil de manter mas também mais sólido.' } },
    { name: { es: 'El Comprometido Real', en: 'The Really Committed', fr: 'Le Vraiment Engagé', de: 'Der Wirklich Engagierte', it: 'Il Davvero Impegnato', pt: 'O Comprometido Real' }, dimensions: ['C'], photo: '/characters/real-committed.jpg', description: { es: 'El compromiso no es una carga — es una elección que renueva constantemente.', en: 'Commitment is not a burden — it\'s a choice they constantly renew.', fr: 'L\'engagement n\'est pas un fardeau — c\'est un choix qu\'il/elle renouvelle constamment.', de: 'Engagement ist keine Last — es ist eine Wahl, die er/sie ständig erneuert.', it: 'L\'impegno non è un peso — è una scelta che rinnova costantemente.', pt: 'O compromisso não é um fardo — é uma escolha que renova constantemente.' }, philosophy: { es: 'Para ti, la fidelidad es activa, no pasiva. No es solo "no hacer cosas" — es elegir activamente la relación todos los días. El compromiso que renuevas conscientemente es el único tipo que dura.', en: 'For you, faithfulness is active, not passive. It\'s not just "not doing things" — it\'s actively choosing the relationship every day. The commitment you consciously renew is the only kind that lasts.', fr: 'Pour toi, la fidélité est active, pas passive. Ce n\'est pas seulement "ne pas faire des choses" — c\'est choisir activement la relation tous les jours. L\'engagement que tu renouvelles consciemment est le seul type qui dure.', de: 'Für dich ist Treue aktiv, nicht passiv. Es geht nicht nur darum, "Dinge nicht zu tun" — es geht darum, die Beziehung jeden Tag aktiv zu wählen. Das Engagement, das du bewusst erneuerst, ist das einzige, das dauert.', it: 'Per te, la fedeltà è attiva, non passiva. Non è solo "non fare cose" — è scegliere attivamente la relazione ogni giorno. L\'impegno che rinnovi consciamente è l\'unico tipo che dura.', pt: 'Para você, a fidelidade é ativa, não passiva. Não é apenas "não fazer coisas" — é escolher ativamente o relacionamento todos os dias. O compromisso que você renova conscientemente é o único tipo que dura.' } },
    { name: { es: 'El Tentado Consciente', en: 'The Consciously Tempted', fr: 'Le Tenté Conscient', de: 'Der Bewusst Versuchte', it: 'Il Tentato Conscio', pt: 'O Tentado Consciente' }, dimensions: ['T', 'F'], photo: '/characters/consciously-tempted.jpg', description: { es: 'Siente tentación pero elige conscientemente no actuar.', en: 'Feels temptation but consciously chooses not to act.', fr: 'Ressent la tentation mais choisit consciemment de ne pas agir.', de: 'Fühlt Versuchung, wählt aber bewusst, nicht zu handeln.', it: 'Sente tentazione ma sceglie consapevolmente di non agire.', pt: 'Sente tentação mas escolhe conscientemente não agir.' }, philosophy: { es: 'Eres honesto/a: la tentación existe. Y también eres claro/a: elegir la fidelidad es exactamente eso, una elección. Esa combinación de honestidad sobre los impulsos y agencia sobre las acciones es madura y realista.', en: 'You\'re honest: temptation exists. And you\'re also clear: choosing faithfulness is exactly that, a choice. That combination of honesty about impulses and agency about actions is mature and realistic.', fr: 'Tu es honnête(e) : la tentation existe. Et tu es aussi clair(e) : choisir la fidélité est exactement ça, un choix. Cette combinaison d\'honnêteté sur les impulsions et d\'agentivité sur les actions est mature et réaliste.', de: 'Du bist ehrlich: die Versuchung existiert. Und du bist auch klar: Treue zu wählen ist genau das, eine Wahl. Diese Kombination aus Ehrlichkeit über Impulse und Handlungsfähigkeit über Handlungen ist reif und realistisch.', it: 'Sei onesto/a: la tentazione esiste. E sei anche chiaro/a: scegliere la fedeltà è esattamente questo, una scelta. Quella combinazione di onestà sugli impulsi e agentività sulle azioni è matura e realistica.', pt: 'Você é honesto/a: a tentação existe. E você também é claro/a: escolher a fidelidade é exatamente isso, uma escolha. Essa combinação de honestidade sobre os impulsos e agência sobre as ações é madura e realista.' } },
    { name: { es: 'El Ambiguo que Trabaja en Ello', en: 'The Ambiguous Working on It', fr: 'L\'Ambigu qui y Travaille', de: 'Der Ambige, der Daran Arbeitet', it: 'L\'Ambiguo che ci Lavora', pt: 'O Ambíguo que Trabalha Nisso' }, dimensions: ['A', 'C'], photo: '/characters/working-ambiguous.jpg', description: { es: 'Sabe que vive en la zona gris y está tratando de salir.', en: 'Knows they live in the gray zone and is trying to get out.', fr: 'Sait qu\'il/elle vit dans la zone grise et essaie d\'en sortir.', de: 'Weiß, dass er/sie in der Grauzone lebt und versucht herauszukommen.', it: 'Sa che vive nella zona grigia e sta cercando di uscirne.', pt: 'Sabe que vive na zona cinzenta e está tentando sair.' }, philosophy: { es: 'Reconoces que la zona gris no es una zona segura — es un territorio peligroso disfrazado de inocencia. Y estás trabajando en ser más claro/a contigo mismo/a y con tu pareja sobre dónde están los límites.', en: 'You recognize that the gray zone is not a safe zone — it\'s dangerous territory disguised as innocence. And you\'re working on being clearer with yourself and your partner about where the limits are.', fr: 'Tu reconnais que la zone grise n\'est pas une zone sûre — c\'est un territoire dangereux déguisé en innocence. Et tu travailles à être plus clair(e) avec toi-même et avec ton/ta partenaire sur où sont les limites.', de: 'Du erkennst, dass die Grauzone keine sichere Zone ist — es ist gefährliches Terrain, das als Unschuld getarnt ist. Und du arbeitest daran, klarer mit dir selbst und deinem Partner/deiner Partnerin zu sein, wo die Grenzen liegen.', it: 'Riconosci che la zona grigia non è una zona sicura — è un territorio pericoloso travestito da innocenza. E stai lavorando per essere più chiaro/a con te stesso/a e con il tuo partner su dove sono i limiti.', pt: 'Você reconhece que a zona cinzenta não é uma zona segura — é um território perigoso disfarçado de inocência. E você está trabalhando em ser mais claro/a consigo mesmo/a e com seu parceiro sobre onde estão os limites.' } },
    { name: { es: 'El Fiel Comprometido', en: 'The Faithful Committed', fr: 'Le Fidèle Engagé', de: 'Der Treue Engagierte', it: 'Il Fedele Impegnato', pt: 'O Fiel Comprometido' }, dimensions: ['F', 'C'], photo: '/characters/committed-faithful.jpg', description: { es: 'Fiel por convicción y activo en su compromiso.', en: 'Faithful by conviction and active in their commitment.', fr: 'Fidèle par conviction et actif/ve dans son engagement.', de: 'Treu aus Überzeugung und aktiv in seinem/ihrem Engagement.', it: 'Fedele per convinzione e attivo nel suo impegno.', pt: 'Fiel por convicção e ativo/a em seu compromisso.' }, philosophy: { es: 'Combinas los dos elementos más poderosos: la fidelidad como identidad y el compromiso como práctica activa. No solo no engañas — construyes activamente la relación que hace que no quieras hacerlo.', en: 'You combine the two most powerful elements: faithfulness as identity and commitment as active practice. You don\'t just not cheat — you actively build the relationship that makes you not want to.', fr: 'Tu combines les deux éléments les plus puissants : la fidélité comme identité et l\'engagement comme pratique active. Tu ne te contentes pas de ne pas tromper — tu construis activement la relation qui fait que tu ne veux pas le faire.', de: 'Du kombinierst die zwei mächtigsten Elemente: Treue als Identität und Engagement als aktive Praxis. Du betrügst nicht nur nicht — du baust aktiv die Beziehung auf, die dich nicht betrügen lassen will.', it: 'Combini i due elementi più potenti: la fedeltà come identità e l\'impegno come pratica attiva. Non solo non tradisci — costruisci attivamente la relazione che fa sì che tu non voglia farlo.', pt: 'Você combina os dois elementos mais poderosos: a fidelidade como identidade e o compromisso como prática ativa. Você não apenas não trai — constrói ativamente o relacionamento que faz você não querer fazer isso.' } },
    { name: { es: 'El Tentado en Proceso', en: 'The Tempted in Process', fr: 'Le Tenté en Processus', de: 'Der Versuchte im Prozess', it: 'Il Tentato in Processo', pt: 'O Tentado em Processo' }, dimensions: ['T', 'A'], photo: '/characters/tempted-in-process.jpg', description: { es: 'Lucha con la tentación y con la ambigüedad. Todavía en construcción.', en: 'Struggles with temptation and ambiguity. Still under construction.', fr: 'Lutte avec la tentation et l\'ambiguïté. Encore en construction.', de: 'Kämpft mit Versuchung und Ambiguität. Noch im Aufbau.', it: 'Lotta con la tentazione e con l\'ambiguità. Ancora in costruzione.', pt: 'Luta com a tentação e a ambiguidade. Ainda em construção.' }, philosophy: { es: 'Estás en un momento de definición. La tentación y la zona gris son donde vives ahora. La pregunta es: ¿qué quieres construir desde aquí? La respuesta a eso definirá el tipo de persona que serás en una relación.', en: 'You\'re at a moment of definition. Temptation and the gray zone are where you live now. The question is: what do you want to build from here? The answer to that will define the kind of person you\'ll be in a relationship.', fr: 'Tu es à un moment de définition. La tentation et la zone grise sont là où tu vis maintenant. La question est : qu\'est-ce que tu veux construire à partir d\'ici ? La réponse à ça définira le type de personne que tu seras dans une relation.', de: 'Du bist in einem Moment der Definition. Versuchung und Grauzone sind, wo du jetzt lebst. Die Frage ist: Was willst du von hier aus aufbauen? Die Antwort darauf wird die Art von Person definieren, die du in einer Beziehung sein wirst.', it: 'Sei in un momento di definizione. La tentazione e la zona grigia sono dove vivi ora. La domanda è: cosa vuoi costruire da qui? La risposta a questo definirà il tipo di persona che sarai in una relazione.', pt: 'Você está em um momento de definição. A tentação e a zona cinzenta são onde você vive agora. A pergunta é: o que você quer construir a partir daqui? A resposta a isso definirá o tipo de pessoa que você será em um relacionamento.' } },
  ],
};

export async function seedFaithful(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'faithful' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'faithful',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['relationships'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
