import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Eres un NPC o el personaje principal?', en: 'Are you an NPC or the main character?', fr: 'Es-tu un PNJ ou le personnage principal ?', de: 'Bist du ein NPC oder die Hauptfigur?', it: 'Sei un NPC o il personaggio principale?', pt: 'Você é um NPC ou o personagem principal?' },
  description: { es: '¿Tu vida tiene historia propia o eres un personaje de fondo en la vida de los demás?', en: 'Does your life have its own story or are you a background character in others\' lives?', fr: 'Ta vie a-t-elle sa propre histoire ou es-tu un personnage de fond dans la vie des autres ?', de: 'Hat dein Leben eine eigene Geschichte oder bist du eine Hintergrundfigur im Leben anderer?', it: 'La tua vita ha una storia propria o sei un personaggio di sfondo nella vita degli altri?', pt: 'Sua vida tem história própria ou você é um personagem de fundo na vida dos outros?' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { N: 'NPC', P: 'Personaje Principal', S: 'Secundario', H: 'Héroe' },
    en: { N: 'NPC', P: 'Main Character', S: 'Supporting Character', H: 'Hero' },
    fr: { N: 'PNJ', P: 'Personnage Principal', S: 'Personnage Secondaire', H: 'Héros' },
    de: { N: 'NPC', P: 'Hauptfigur', S: 'Nebenfigur', H: 'Held' },
    it: { N: 'NPC', P: 'Personaggio Principale', S: 'Personaggio Secondario', H: 'Eroe' },
    pt: { N: 'NPC', P: 'Personagem Principal', S: 'Personagem Secundário', H: 'Herói' },
  },
  questions: [
    { id: 1, situation: { es: 'En una reunión de trabajo, la conversación toma un giro que nadie esperaba. ¿Qué haces tú?', en: 'In a work meeting, the conversation takes a turn nobody expected. What do you do?', fr: 'Dans une réunion de travail, la conversation prend une tournure que personne n\'attendait. Qu\'est-ce que tu fais ?', de: 'In einem Arbeitsmeeting nimmt das Gespräch eine Wendung, die niemand erwartet hatte. Was tust du?', it: 'In una riunione di lavoro, la conversazione prende una piega che nessuno si aspettava. Cosa fai?', pt: 'Em uma reunião de trabalho, a conversa toma um rumo que ninguém esperava. O que você faz?' }, options: [
      { text: { es: 'Escucho, asiento cuando otros asienten, hablo cuando me preguntan directamente.', en: 'I listen, nod when others nod, speak when directly asked.', fr: 'J\'écoute, j\'acquiesce quand les autres acquiescent, je parle quand on me demande directement.', de: 'Ich höre zu, nicke wenn andere nicken, spreche wenn ich direkt gefragt werde.', it: 'Ascolto, annuisco quando gli altri annuiscono, parlo quando mi viene chiesto direttamente.', pt: 'Ouço, aceno quando outros acenaram, falo quando me perguntam diretamente.' }, dimension: 'N' },
      { text: { es: 'Tomo el hilo de la conversación y la llevo hacia donde creo que es útil.', en: 'I take the thread of the conversation and lead it where I think it\'s useful.', fr: 'Je prends le fil de la conversation et je la mène là où je pense qu\'elle est utile.', de: 'Ich nehme den Faden des Gesprächs und führe es dorthin, wo ich es für nützlich halte.', it: 'Prendo il filo della conversazione e la porto dove penso sia utile.', pt: 'Pego o fio da conversa e a levo para onde acho que é útil.' }, dimension: 'P' },
      { text: { es: 'Hago preguntas que enriquecen la conversación sin necesitar protagonizarla.', en: 'I ask questions that enrich the conversation without needing to star in it.', fr: 'Je pose des questions qui enrichissent la conversation sans avoir besoin d\'en être la vedette.', de: 'Ich stelle Fragen, die das Gespräch bereichern, ohne es anführen zu müssen.', it: 'Faccio domande che arricchiscono la conversazione senza dover essere protagonista.', pt: 'Faço perguntas que enriquecem a conversa sem precisar protagonizá-la.' }, dimension: 'S' },
      { text: { es: 'Propongo algo completamente nuevo que cambia la dirección de la reunión.', en: 'I propose something completely new that changes the direction of the meeting.', fr: 'Je propose quelque chose de complètement nouveau qui change la direction de la réunion.', de: 'Ich schlage etwas völlig Neues vor, das die Richtung des Meetings ändert.', it: 'Propongo qualcosa di completamente nuovo che cambia la direzione della riunione.', pt: 'Proponho algo completamente novo que muda a direção da reunião.' }, dimension: 'H' },
    ] },
    { id: 2, situation: { es: '¿Cómo describirías el arco narrativo de tu vida hasta ahora?', en: 'How would you describe the narrative arc of your life so far?', fr: 'Comment décrirais-tu l\'arc narratif de ta vie jusqu\'à présent ?', de: 'Wie würdest du den narrativen Bogen deines Lebens bis jetzt beschreiben?', it: 'Come descriveresti l\'arco narrativo della tua vita fino ad ora?', pt: 'Como você descreveria o arco narrativo da sua vida até agora?' }, options: [
      { text: { es: 'No lo había pensado. La vida pasa y yo voy con ella.', en: 'I hadn\'t thought about it. Life happens and I go with it.', fr: 'Je n\'y avais pas pensé. La vie se passe et j\'y vais avec elle.', de: 'Ich hatte nicht daran gedacht. Das Leben passiert und ich gehe mit.', it: 'Non ci avevo pensato. La vita accade e io ci vado con essa.', pt: 'Não havia pensado nisso. A vida acontece e eu vou com ela.' }, dimension: 'N' },
      { text: { es: 'Tiene una dirección clara que yo he elegido y construido.', en: 'It has a clear direction I\'ve chosen and built.', fr: 'Il a une direction claire que j\'ai choisie et construite.', de: 'Es hat eine klare Richtung, die ich gewählt und aufgebaut habe.', it: 'Ha una direzione chiara che ho scelto e costruito.', pt: 'Tem uma direção clara que eu escolhi e construí.' }, dimension: 'P' },
      { text: { es: 'Tiene momentos clave que me definieron aunque no todos los elegí.', en: 'It has key moments that defined me even though I didn\'t choose all of them.', fr: 'Il a des moments clés qui m\'ont défini(e) même si je ne les ai pas tous choisis.', de: 'Es hat Schlüsselmomente, die mich definierten, auch wenn ich nicht alle gewählt habe.', it: 'Ha momenti chiave che mi hanno definito anche se non li ho tutti scelti.', pt: 'Tem momentos-chave que me definiram mesmo que não os tenha escolhido todos.' }, dimension: 'S' },
      { text: { es: 'Es una historia de superación con un propósito que todavía estoy construyendo.', en: 'It\'s a story of overcoming with a purpose I\'m still building.', fr: 'C\'est une histoire de dépassement avec un but que je construis encore.', de: 'Es ist eine Geschichte der Überwindung mit einem Zweck, den ich noch aufbaue.', it: 'È una storia di superamento con uno scopo che sto ancora costruendo.', pt: 'É uma história de superação com um propósito que ainda estou construindo.' }, dimension: 'H' },
    ] },
    { id: 3, situation: { es: 'Un amigo propone un plan para el fin de semana. Tú no tenías ninguno.', en: 'A friend proposes a plan for the weekend. You had none.', fr: 'Un ami propose un plan pour le week-end. Tu n\'en avais aucun.', de: 'Ein Freund schlägt einen Plan fürs Wochenende vor. Du hattest keinen.', it: 'Un amico propone un piano per il fine settimana. Tu non ne avevi nessuno.', pt: 'Um amigo propõe um plano para o fim de semana. Você não tinha nenhum.' }, options: [
      { text: { es: 'Bien, ¿qué hacemos? Me adapto al plan de otros.', en: 'Great, what are we doing? I adapt to others\' plans.', fr: 'Bien, qu\'est-ce qu\'on fait ? Je m\'adapte au plan des autres.', de: 'Gut, was machen wir? Ich passe mich dem Plan anderer an.', it: 'Bene, cosa facciamo? Mi adatto al piano degli altri.', pt: 'Ótimo, o que fazemos? Me adapto ao plano dos outros.' }, dimension: 'N' },
      { text: { es: 'Evalúo si se alinea con lo que yo quería hacer y propongo adaptaciones.', en: 'I evaluate if it aligns with what I wanted to do and propose adaptations.', fr: 'J\'évalue si ça s\'aligne avec ce que je voulais faire et je propose des adaptations.', de: 'Ich bewerte, ob es dem entspricht, was ich tun wollte, und schlage Anpassungen vor.', it: 'Valuto se si allinea con quello che volevo fare e propongo adattamenti.', pt: 'Avalio se se alinha com o que eu queria fazer e proponho adaptações.' }, dimension: 'P' },
      { text: { es: 'Lo apoyo activamente y ayudo a que salga bien.', en: 'I actively support it and help make it go well.', fr: 'Je le soutiens activement et j\'aide à ce que ça se passe bien.', de: 'Ich unterstütze es aktiv und helfe dabei, dass es gut läuft.', it: 'Lo supporto attivamente e aiuto a farlo andare bene.', pt: 'Apoio ativamente e ajudo a fazer dar certo.' }, dimension: 'S' },
      { text: { es: 'Propongo una alternativa diferente o un giro al plan que lo hace mejor.', en: 'I propose a different alternative or a twist to the plan that makes it better.', fr: 'Je propose une alternative différente ou un rebondissement au plan qui le rend meilleur.', de: 'Ich schlage eine andere Alternative oder eine Wendung des Plans vor, die ihn besser macht.', it: 'Propongo un\'alternativa diversa o una svolta al piano che lo rende migliore.', pt: 'Proponho uma alternativa diferente ou uma reviravolta no plano que o melhora.' }, dimension: 'H' },
    ] },
    { id: 4, situation: { es: '¿Tienes opiniones propias y originales sobre cosas que importan?', en: 'Do you have your own original opinions about things that matter?', fr: 'As-tu des opinions propres et originales sur les choses qui comptent ?', de: 'Hast du eigene und originelle Meinungen zu Dingen, die wichtig sind?', it: 'Hai opinioni proprie e originali su cose che contano?', pt: 'Você tem opiniões próprias e originais sobre coisas que importam?' }, options: [
      { text: { es: 'Tengo las opiniones del grupo con el que más paso tiempo.', en: 'I have the opinions of the group I spend most time with.', fr: 'J\'ai les opinions du groupe avec lequel je passe le plus de temps.', de: 'Ich habe die Meinungen der Gruppe, mit der ich die meiste Zeit verbringe.', it: 'Ho le opinioni del gruppo con cui passo più tempo.', pt: 'Tenho as opiniões do grupo com que passo mais tempo.' }, dimension: 'N' },
      { text: { es: 'Sí, y las defiendo aunque sean minoritarias.', en: 'Yes, and I defend them even when they\'re minority views.', fr: 'Oui, et je les défends même si elles sont minoritaires.', de: 'Ja, und ich verteidige sie, auch wenn sie Minderheitsmeinungen sind.', it: 'Sì, e le difendo anche se sono minoritarie.', pt: 'Sim, e as defendo mesmo que sejam minoritárias.' }, dimension: 'P' },
      { text: { es: 'Tengo perspectivas propias pero no siempre las expreso.', en: 'I have my own perspectives but don\'t always express them.', fr: 'J\'ai mes propres perspectives mais je ne les exprime pas toujours.', de: 'Ich habe meine eigenen Perspektiven, aber ich drücke sie nicht immer aus.', it: 'Ho prospettive proprie ma non sempre le esprimo.', pt: 'Tenho perspectivas próprias mas nem sempre as expresso.' }, dimension: 'S' },
      { text: { es: 'Sí, y a veces van en contra de lo que se espera de mí.', en: 'Yes, and sometimes they go against what\'s expected of me.', fr: 'Oui, et parfois elles vont à l\'encontre de ce qu\'on attend de moi.', de: 'Ja, und manchmal laufen sie gegen das, was von mir erwartet wird.', it: 'Sì, e a volte vanno contro quello che ci si aspetta da me.', pt: 'Sim, e às vezes vão contra o que se espera de mim.' }, dimension: 'H' },
    ] },
    { id: 5, situation: { es: 'Si alguien escribe una historia basada en las personas de tu círculo, ¿qué rol tendrías?', en: 'If someone writes a story based on people in your circle, what role would you have?', fr: 'Si quelqu\'un écrit une histoire basée sur les personnes de ton cercle, quel rôle aurais-tu ?', de: 'Wenn jemand eine Geschichte basierend auf Personen in deinem Umfeld schreibt, welche Rolle hättest du?', it: 'Se qualcuno scrive una storia basata sulle persone del tuo cerchio, che ruolo avresti?', pt: 'Se alguém escreve uma história baseada nas pessoas do seu círculo, que papel você teria?' }, options: [
      { text: { es: 'El amigo que siempre está pero no tiene escenas propias.', en: 'The friend who\'s always there but has no scenes of their own.', fr: 'L\'ami qui est toujours là mais n\'a pas de scènes propres.', de: 'Der Freund, der immer da ist, aber keine eigenen Szenen hat.', it: 'L\'amico che è sempre lì ma non ha scene proprie.', pt: 'O amigo que está sempre lá mas não tem cenas próprias.' }, dimension: 'N' },
      { text: { es: 'Uno de los personajes principales con su propia historia.', en: 'One of the main characters with their own story.', fr: 'L\'un des personnages principaux avec sa propre histoire.', de: 'Eine der Hauptfiguren mit ihrer eigenen Geschichte.', it: 'Uno dei personaggi principali con la sua storia.', pt: 'Um dos personagens principais com sua própria história.' }, dimension: 'P' },
      { text: { es: 'El personaje de apoyo que hace posibles los momentos de los protagonistas.', en: 'The supporting character who makes the protagonists\' moments possible.', fr: 'Le personnage de soutien qui rend possibles les moments des protagonistes.', de: 'Die unterstützende Figur, die die Momente der Protagonisten ermöglicht.', it: 'Il personaggio di supporto che rende possibili i momenti dei protagonisti.', pt: 'O personagem de apoio que torna possíveis os momentos dos protagonistas.' }, dimension: 'S' },
      { text: { es: 'El que tiene el arco más interesante, aunque no siempre el más visible.', en: 'The one with the most interesting arc, even if not always the most visible.', fr: 'Celui qui a l\'arc le plus intéressant, même si pas toujours le plus visible.', de: 'Der/Die mit dem interessantesten Bogen, auch wenn nicht immer der sichtbarste.', it: 'Quello con l\'arco più interessante, anche se non sempre il più visibile.', pt: 'O que tem o arco mais interessante, mesmo que nem sempre o mais visível.' }, dimension: 'H' },
    ] },
    { id: 6, situation: { es: '¿Cuántas veces en el último año tomaste una decisión que cambiara la dirección de tu vida?', en: 'How many times in the last year did you make a decision that changed the direction of your life?', fr: 'Combien de fois au cours de la dernière année as-tu pris une décision qui a changé la direction de ta vie ?', de: 'Wie viele Male im letzten Jahr hast du eine Entscheidung getroffen, die die Richtung deines Lebens geändert hat?', it: 'Quante volte nell\'ultimo anno hai preso una decisione che cambiasse la direzione della tua vita?', pt: 'Quantas vezes no último ano você tomou uma decisão que mudasse a direção da sua vida?' }, options: [
      { text: { es: 'Ninguna. La vida siguió su curso natural.', en: 'None. Life followed its natural course.', fr: 'Aucune. La vie a suivi son cours naturel.', de: 'Keine. Das Leben folgte seinem natürlichen Lauf.', it: 'Nessuna. La vita ha seguito il suo corso naturale.', pt: 'Nenhuma. A vida seguiu seu curso natural.' }, dimension: 'N' },
      { text: { es: 'Varias. Las decisiones son la herramienta con que construyo mi historia.', en: 'Several. Decisions are the tool I use to build my story.', fr: 'Plusieurs. Les décisions sont l\'outil avec lequel je construis mon histoire.', de: 'Mehrere. Entscheidungen sind das Werkzeug, mit dem ich meine Geschichte aufbaue.', it: 'Diverse. Le decisioni sono lo strumento con cui costruisco la mia storia.', pt: 'Várias. As decisões são a ferramenta com que construo minha história.' }, dimension: 'P' },
      { text: { es: 'Una o dos importantes que me costaron algo real.', en: 'One or two important ones that cost me something real.', fr: 'Une ou deux importantes qui m\'ont coûté quelque chose de réel.', de: 'Eine oder zwei wichtige, die mich etwas Reales gekostet haben.', it: 'Una o due importanti che mi sono costate qualcosa di reale.', pt: 'Uma ou duas importantes que me custaram algo real.' }, dimension: 'S' },
      { text: { es: 'Una grande que cambió todo. O estoy a punto de tomarla.', en: 'One big one that changed everything. Or I\'m about to take it.', fr: 'Une grande qui a tout changé. Ou je suis sur le point de la prendre.', de: 'Eine große, die alles verändert hat. Oder ich stehe kurz davor, sie zu treffen.', it: 'Una grande che ha cambiato tutto. O sto per prenderla.', pt: 'Uma grande que mudou tudo. Ou estou prestes a tomá-la.' }, dimension: 'H' },
    ] },
    { id: 7, situation: { es: 'Cuando mueras, ¿qué quieres que recuerden de ti?', en: 'When you die, what do you want people to remember about you?', fr: 'Quand tu mourras, que veux-tu qu\'on se souvienne de toi ?', de: 'Wenn du stirbst, was möchtest du, dass man sich an dich erinnert?', it: 'Quando morirai, cosa vuoi che ricordino di te?', pt: 'Quando você morrer, o que quer que lembrem de você?' }, options: [
      { text: { es: 'Que era buena persona, no causé problemas, traté bien a los que me rodearon.', en: 'That I was a good person, didn\'t cause problems, treated those around me well.', fr: 'Que j\'étais une bonne personne, que je n\'ai pas causé de problèmes, que j\'ai bien traité ceux qui m\'entouraient.', de: 'Dass ich ein guter Mensch war, keine Probleme verursacht habe, die Menschen um mich herum gut behandelt habe.', it: 'Che ero una buona persona, non ho causato problemi, ho trattato bene quelli che mi circondavano.', pt: 'Que era boa pessoa, não causei problemas, tratei bem quem estava ao meu redor.' }, dimension: 'N' },
      { text: { es: 'Que viví según mis propios términos y lo que construí tiene valor propio.', en: 'That I lived on my own terms and what I built has its own value.', fr: 'Que j\'ai vécu selon mes propres termes et ce que j\'ai construit a sa propre valeur.', de: 'Dass ich nach meinen eigenen Bedingungen lebte und was ich aufgebaut habe, einen eigenen Wert hat.', it: 'Che ho vissuto secondo i miei termini e quello che ho costruito ha un valore proprio.', pt: 'Que vivi segundo meus próprios termos e o que construí tem valor próprio.' }, dimension: 'P' },
      { text: { es: 'Que ayudé a las personas importantes en mi vida a ser mejores.', en: 'That I helped the important people in my life become better.', fr: 'Que j\'ai aidé les personnes importantes dans ma vie à être meilleures.', de: 'Dass ich den wichtigen Menschen in meinem Leben geholfen habe, besser zu werden.', it: 'Che ho aiutato le persone importanti nella mia vita a essere migliori.', pt: 'Que ajudei as pessoas importantes na minha vida a serem melhores.' }, dimension: 'S' },
      { text: { es: 'Que cambié algo. Que antes de mí, algo era diferente.', en: 'That I changed something. That before me, something was different.', fr: 'Que j\'ai changé quelque chose. Qu\'avant moi, quelque chose était différent.', de: 'Dass ich etwas verändert habe. Dass vor mir etwas anders war.', it: 'Che ho cambiato qualcosa. Che prima di me, qualcosa era diverso.', pt: 'Que mudei algo. Que antes de mim, algo era diferente.' }, dimension: 'H' },
    ] },
    { id: 8, situation: { es: 'Alguien te describe como "siempre está ahí pero nunca es el protagonista". ¿Cómo te cae?', en: 'Someone describes you as "always there but never the protagonist." How does that land?', fr: 'Quelqu\'un te décrit comme "toujours là mais jamais le protagoniste". Comment ça te touche ?', de: 'Jemand beschreibt dich als "immer da, aber nie der Protagonist". Wie kommt das bei dir an?', it: 'Qualcuno ti descrive come "sempre lì ma mai il protagonista". Come ti suona?', pt: 'Alguém te descreve como "sempre lá mas nunca o protagonista". Como isso cai?' }, options: [
      { text: { es: 'No me molesta. No busco protagonismo.', en: 'It doesn\'t bother me. I don\'t seek the spotlight.', fr: 'Ça ne me dérange pas. Je ne cherche pas à être la vedette.', de: 'Es stört mich nicht. Ich suche keine Hauptrolle.', it: 'Non mi dà fastidio. Non cerco il protagonismo.', pt: 'Não me incomoda. Não busco protagonismo.' }, dimension: 'N' },
      { text: { es: 'Me genera reflexión. ¿Estoy construyendo mi propia historia o viviendo la de otros?', en: 'It makes me reflect. Am I building my own story or living someone else\'s?', fr: 'Ça me génère de la réflexion. Est-ce que je construis ma propre histoire ou est-ce que je vis celle des autres ?', de: 'Es bringt mich zum Nachdenken. Baue ich meine eigene Geschichte auf oder lebe ich die Geschichte anderer?', it: 'Mi genera riflessione. Sto costruendo la mia storia o vivendo quella degli altri?', pt: 'Me gera reflexão. Estou construindo minha própria história ou vivendo a dos outros?' }, dimension: 'P' },
      { text: { es: 'Hay algo de cierto, pero el rol de apoyo tiene valor propio.', en: 'There\'s something true in that, but the supporting role has its own value.', fr: 'Il y a quelque chose de vrai là-dedans, mais le rôle de soutien a sa propre valeur.', de: 'Da ist etwas Wahres dran, aber die Nebenrolle hat ihren eigenen Wert.', it: 'C\'è qualcosa di vero, ma il ruolo di supporto ha un valore proprio.', pt: 'Há algo de verdade nisso, mas o papel de apoio tem valor próprio.' }, dimension: 'S' },
      { text: { es: 'Me activa. Quiero que esa descripción cambie.', en: 'It activates me. I want that description to change.', fr: 'Ça m\'active. Je veux que cette description change.', de: 'Es aktiviert mich. Ich möchte, dass sich diese Beschreibung ändert.', it: 'Mi attiva. Voglio che quella descrizione cambi.', pt: 'Me ativa. Quero que essa descrição mude.' }, dimension: 'H' },
    ] },
    { id: 9, situation: { es: '¿Tienes metas de largo plazo que te exigen algo de ti?', en: 'Do you have long-term goals that demand something of you?', fr: 'As-tu des objectifs à long terme qui t\'exigent quelque chose ?', de: 'Hast du langfristige Ziele, die etwas von dir fordern?', it: 'Hai obiettivi a lungo termine che ti esigono qualcosa?', pt: 'Você tem metas de longo prazo que exigem algo de você?' }, options: [
      { text: { es: 'No especialmente. Voy resolviendo lo que se presenta.', en: 'Not especially. I solve what presents itself.', fr: 'Pas particulièrement. Je résous ce qui se présente.', de: 'Nicht besonders. Ich löse, was sich ergibt.', it: 'Non particolarmente. Risolvo quello che si presenta.', pt: 'Não especialmente. Vou resolvendo o que aparece.' }, dimension: 'N' },
      { text: { es: 'Sí, y organizo mi vida en función de ellas.', en: 'Yes, and I organize my life around them.', fr: 'Oui, et j\'organise ma vie en fonction d\'elles.', de: 'Ja, und ich organisiere mein Leben nach ihnen.', it: 'Sì, e organizzo la mia vita in funzione di loro.', pt: 'Sim, e organizo minha vida em função delas.' }, dimension: 'P' },
      { text: { es: 'Tengo aspiraciones pero me cuesta priorizar sobre lo urgente cotidiano.', en: 'I have aspirations but struggle to prioritize over daily urgencies.', fr: 'J\'ai des aspirations mais j\'ai du mal à prioriser sur les urgences quotidiennes.', de: 'Ich habe Ambitionen, aber es fällt mir schwer, gegenüber den täglichen Dringlichkeiten zu priorisieren.', it: 'Ho aspirazioni ma faccio fatica a dare priorità rispetto alle urgenze quotidiane.', pt: 'Tenho aspirações mas me custa priorizar sobre as urgências cotidianas.' }, dimension: 'S' },
      { text: { es: 'Sí, y son lo suficientemente grandes para asustarme un poco.', en: 'Yes, and they\'re big enough to scare me a little.', fr: 'Oui, et ils sont assez grands pour me faire un peu peur.', de: 'Ja, und sie sind groß genug, um mich ein wenig zu erschrecken.', it: 'Sì, e sono abbastanza grandi da spaventarmi un po\'.', pt: 'Sim, e são grandes o suficiente para me assustar um pouco.' }, dimension: 'H' },
    ] },
    { id: 10, situation: { es: '¿Qué tipo de historia estás escribiendo con tu vida?', en: 'What kind of story are you writing with your life?', fr: 'Quel type d\'histoire écris-tu avec ta vie ?', de: 'Welche Art von Geschichte schreibst du mit deinem Leben?', it: 'Che tipo di storia stai scrivendo con la tua vita?', pt: 'Que tipo de história você está escrevendo com sua vida?' }, options: [
      { text: { es: 'Honestamente, no lo pienso mucho.', en: 'Honestly, I don\'t think about it much.', fr: 'Honnêtement, je n\'y pense pas beaucoup.', de: 'Ehrlich gesagt denke ich nicht viel darüber nach.', it: 'Onestamente, non ci penso molto.', pt: 'Honestamente, não penso muito nisso.' }, dimension: 'N' },
      { text: { es: 'Una deliberada y elegida. Soy el autor/a.', en: 'A deliberate and chosen one. I\'m the author.', fr: 'Une délibérée et choisie. Je suis l\'auteur/l\'autrice.', de: 'Eine bewusste und gewählte. Ich bin der/die Autor/in.', it: 'Una deliberata e scelta. Sono l\'autore/autrice.', pt: 'Uma deliberada e escolhida. Sou o/a autor/a.' }, dimension: 'P' },
      { text: { es: 'Una de contribución. Mi historia tiene sentido porque aporta a las de otros.', en: 'One of contribution. My story makes sense because it contributes to others\'.', fr: 'Une de contribution. Mon histoire a du sens parce qu\'elle contribue à celles des autres.', de: 'Eine des Beitrags. Meine Geschichte macht Sinn, weil sie zu denen anderer beiträgt.', it: 'Una di contribuzione. La mia storia ha senso perché contribuisce a quelle degli altri.', pt: 'Uma de contribuição. Minha história faz sentido porque contribui com as dos outros.' }, dimension: 'S' },
      { text: { es: 'Una épica todavía en proceso. El mejor capítulo no ha llegado.', en: 'An epic still in progress. The best chapter hasn\'t arrived yet.', fr: 'Une épopée encore en cours. Le meilleur chapitre n\'est pas encore arrivé.', de: 'Eine Epik, die noch im Gange ist. Das beste Kapitel ist noch nicht angekommen.', it: 'Un\'epica ancora in corso. Il capitolo migliore non è ancora arrivato.', pt: 'Uma épica ainda em progresso. O melhor capítulo ainda não chegou.' }, dimension: 'H' },
    ] },
  ],
  characters: [
    { name: { es: 'El NPC Clásico', en: 'The Classic NPC', fr: 'Le PNJ Classique', de: 'Der Klassische NPC', it: 'Il NPC Classico', pt: 'O NPC Clássico' }, dimensions: ['N'], photo: '/characters/npc.jpg', description: { es: 'Aparece en todas las escenas pero no tiene historia propia.', en: 'Appears in all scenes but has no story of their own.', fr: 'Apparaît dans toutes les scènes mais n\'a pas d\'histoire propre.', de: 'Erscheint in allen Szenen, hat aber keine eigene Geschichte.', it: 'Appare in tutte le scene ma non ha una storia propria.', pt: 'Aparece em todas as cenas mas não tem história própria.' }, philosophy: { es: 'No hay nada malo en ser un NPC — pero hay algo triste en no elegirlo. Tu vida fluye sin fricción porque nunca has chocado con nada suficientemente grande para obligarte a definirte.', en: 'There\'s nothing wrong with being an NPC — but there\'s something sad about not choosing it. Your life flows without friction because you\'ve never collided with anything big enough to force you to define yourself.', fr: 'Il n\'y a rien de mal à être un PNJ — mais il y a quelque chose de triste à ne pas le choisir. Ta vie coule sans friction parce que tu n\'as jamais heurté quelque chose d\'assez grand pour t\'obliger à te définir.', de: 'Es ist nichts falsch daran, ein NPC zu sein — aber es ist traurig, es nicht zu wählen. Dein Leben fließt ohne Reibung, weil du nie auf etwas gestoßen bist, das groß genug war, dich zu zwingen, dich zu definieren.', it: 'Non c\'è niente di sbagliato nell\'essere un NPC — ma c\'è qualcosa di triste nel non sceglierlo. La tua vita scorre senza attrito perché non hai mai scontrato qualcosa di abbastanza grande da costringerti a definirti.', pt: 'Não há nada de errado em ser um NPC — mas há algo triste em não escolher isso. Sua vida flui sem atrito porque nunca colidiu com algo grande o suficiente para obrigá-lo/a a definir-se.' } },
    { name: { es: 'El Personaje Principal', en: 'The Main Character', fr: 'Le Personnage Principal', de: 'Die Hauptfigur', it: 'Il Personaggio Principale', pt: 'O Personagem Principal' }, dimensions: ['P'], photo: '/characters/main-character.jpg', description: { es: 'La historia es suya. Actúa, elige, enfrenta consecuencias.', en: 'The story is theirs. They act, choose, face consequences.', fr: 'L\'histoire est la sienne. Il/elle agit, choisit, fait face aux conséquences.', de: 'Die Geschichte gehört ihm/ihr. Er/sie handelt, wählt, steht den Konsequenzen gegenüber.', it: 'La storia è sua. Agisce, sceglie, affronta le conseguenze.', pt: 'A história é dele/dela. Age, escolhe, enfrenta consequências.' }, philosophy: { es: 'Vives como el autor de tu propia historia. Eso no significa que todo salga bien — significa que cada decisión es tuya y cada consecuencia también. Esa autoría tiene un costo y también una libertad que pocos experimentan.', en: 'You live as the author of your own story. That doesn\'t mean everything goes well — it means every decision is yours and every consequence too. That authorship has a cost and also a freedom few experience.', fr: 'Tu vis comme l\'auteur de ta propre histoire. Ça ne veut pas dire que tout va bien — ça veut dire que chaque décision est la tienne et chaque conséquence aussi. Cette paternité a un coût et aussi une liberté que peu expérimentent.', de: 'Du lebst als Autor deiner eigenen Geschichte. Das bedeutet nicht, dass alles gut geht — es bedeutet, dass jede Entscheidung deine ist und jede Konsequenz auch. Diese Urheberschaft hat einen Preis und auch eine Freiheit, die wenige erleben.', it: 'Vivi come l\'autore della tua storia. Questo non significa che tutto vada bene — significa che ogni decisione è tua e ogni conseguenza anche. Quella paternità ha un costo e anche una libertà che pochi sperimentano.', pt: 'Você vive como o autor da sua própria história. Isso não significa que tudo sai bem — significa que cada decisão é sua e cada consequência também. Essa autoria tem um custo e também uma liberdade que poucos experimentam.' } },
    { name: { es: 'El Personaje Secundario Poderoso', en: 'The Powerful Supporting Character', fr: 'Le Personnage Secondaire Puissant', de: 'Die Mächtige Nebenfigur', it: 'Il Personaggio Secondario Potente', pt: 'O Personagem Secundário Poderoso' }, dimensions: ['S'], photo: '/characters/powerful-secondary.jpg', description: { es: 'No busca el protagonismo pero su impacto es real.', en: 'Doesn\'t seek the spotlight but their impact is real.', fr: 'Ne cherche pas le protagonisme mais son impact est réel.', de: 'Sucht nicht die Hauptrolle, aber ihr Einfluss ist real.', it: 'Non cerca il protagonismo ma il suo impatto è reale.', pt: 'Não busca o protagonismo mas seu impacto é real.' }, philosophy: { es: 'Has encontrado una forma de existir que no requiere ser el centro. Tu contribución a la historia de otros no es menor que la de los protagonistas — a veces es lo que hace posible que todo lo demás funcione.', en: 'You\'ve found a way of existing that doesn\'t require being the center. Your contribution to others\' stories is no lesser than that of protagonists — sometimes it\'s what makes everything else work.', fr: 'Tu as trouvé une façon d\'exister qui ne nécessite pas d\'être le centre. Ta contribution à l\'histoire des autres n\'est pas moins importante que celle des protagonistes — parfois c\'est ce qui permet à tout le reste de fonctionner.', de: 'Du hast eine Existenzweise gefunden, die nicht erfordert, im Mittelpunkt zu stehen. Dein Beitrag zur Geschichte anderer ist nicht geringer als der der Protagonisten — manchmal ist es das, was alles andere zum Funktionieren bringt.', it: 'Hai trovato un modo di esistere che non richiede essere al centro. Il tuo contributo alla storia degli altri non è minore di quello dei protagonisti — a volte è quello che fa funzionare tutto il resto.', pt: 'Você encontrou uma forma de existir que não requer estar no centro. Sua contribuição para a história dos outros não é menor que a dos protagonistas — às vezes é o que faz tudo o mais funcionar.' } },
    { name: { es: 'El Héroe en Proceso', en: 'The Hero in Progress', fr: 'Le Héros en Processus', de: 'Der Held im Prozess', it: 'L\'Eroe in Progressione', pt: 'O Herói em Processo' }, dimensions: ['H'], photo: '/characters/hero-in-progress.jpg', description: { es: 'Tiene el arco del héroe pero todavía está en el camino.', en: 'Has the hero\'s arc but is still on the journey.', fr: 'A l\'arc du héros mais est encore en chemin.', de: 'Hat den Heldenbogen, ist aber noch unterwegs.', it: 'Ha l\'arco dell\'eroe ma è ancora in cammino.', pt: 'Tem o arco do herói mas ainda está no caminho.' }, philosophy: { es: 'Tienes lo que se necesita para un arco interesante: voluntad de cambiar, disposición al riesgo, una historia que todavía no está escrita. El héroe no es el que llegó — es el que decidió ir.', en: 'You have what\'s needed for an interesting arc: willingness to change, openness to risk, a story that isn\'t written yet. The hero isn\'t the one who arrived — it\'s the one who decided to go.', fr: 'Tu as ce qu\'il faut pour un arc intéressant : volonté de changer, disposition au risque, une histoire qui n\'est pas encore écrite. Le héros n\'est pas celui qui est arrivé — c\'est celui qui a décidé d\'y aller.', de: 'Du hast, was für einen interessanten Bogen nötig ist: Bereitschaft zur Veränderung, Risikobereitschaft, eine Geschichte, die noch nicht geschrieben ist. Der Held ist nicht derjenige, der angekommen ist — es ist derjenige, der sich entschieden hat zu gehen.', it: 'Hai quello che serve per un arco interessante: volontà di cambiare, disposizione al rischio, una storia che non è ancora scritta. L\'eroe non è quello che è arrivato — è quello che ha deciso di andare.', pt: 'Você tem o que é necessário para um arco interessante: vontade de mudar, disposição para o risco, uma história que ainda não está escrita. O herói não é o que chegou — é o que decidiu ir.' } },
    { name: { es: 'El NPC Despertando', en: 'The Awakening NPC', fr: 'Le PNJ qui s\'Éveille', de: 'Der Erwachende NPC', it: 'Il NPC che si Sveglia', pt: 'O NPC Despertando' }, dimensions: ['N', 'P'], photo: '/characters/npc-awakening.jpg', description: { es: 'Empezando a preguntarse si quiere seguir siendo fondo.', en: 'Starting to wonder if they want to keep being background.', fr: 'Commençant à se demander s\'il/elle veut continuer à être en arrière-plan.', de: 'Fängt an sich zu fragen, ob er/sie weiterhin Hintergrund sein will.', it: 'Iniziando a chiedersi se vuole continuare a essere sfondo.', pt: 'Começando a se perguntar se quer continuar sendo fundo.' }, philosophy: { es: 'Algo está cambiando. La pregunta de si tu vida tiene dirección propia empezó a incomodarte. Eso ya es el inicio del arco. El NPC que empieza a cuestionarse su rol es el inicio de otro tipo de personaje.', en: 'Something is changing. The question of whether your life has its own direction started to make you uncomfortable. That\'s already the start of the arc. The NPC who starts questioning their role is the beginning of another type of character.', fr: 'Quelque chose change. La question de si ta vie a sa propre direction a commencé à te déranger. C\'est déjà le début de l\'arc. Le PNJ qui commence à remettre en question son rôle est le début d\'un autre type de personnage.', de: 'Etwas ändert sich. Die Frage, ob dein Leben eine eigene Richtung hat, begann dich zu stören. Das ist bereits der Beginn des Bogens. Der NPC, der anfängt, seine Rolle zu hinterfragen, ist der Anfang einer anderen Art von Figur.', it: 'Qualcosa sta cambiando. La domanda se la tua vita abbia una direzione propria ha iniziato a disturbarti. Questo è già l\'inizio dell\'arco. Il NPC che inizia a mettere in discussione il suo ruolo è l\'inizio di un altro tipo di personaggio.', pt: 'Algo está mudando. A pergunta se sua vida tem direção própria começou a te incomodar. Isso já é o início do arco. O NPC que começa a questionar seu papel é o início de outro tipo de personagem.' } },
    { name: { es: 'El Secundario con Propósito', en: 'The Supporting Character with Purpose', fr: 'Le Personnage Secondaire avec un But', de: 'Die Nebenfigur mit Zweck', it: 'Il Personaggio Secondario con Scopo', pt: 'O Personagem Secundário com Propósito' }, dimensions: ['S', 'H'], photo: '/characters/secondary-purpose.jpg', description: { es: 'Apoya a otros y también tiene su propia misión.', en: 'Supports others and also has their own mission.', fr: 'Soutient les autres et a aussi sa propre mission.', de: 'Unterstützt andere und hat auch seine eigene Mission.', it: 'Supporta gli altri e ha anche la propria missione.', pt: 'Apoia outros e também tem sua própria missão.' }, philosophy: { es: 'Sabes que tu historia tiene valor aunque no necesites ser el protagonista de todas las escenas. Pero también tienes algo propio que defender. Es la combinación más madura: presencia sin dependencia del reconocimiento.', en: 'You know your story has value even without needing to be the protagonist of every scene. But you also have something of your own to defend. It\'s the most mature combination: presence without dependence on recognition.', fr: 'Tu sais que ton histoire a de la valeur même sans avoir besoin d\'être le protagoniste de toutes les scènes. Mais tu as aussi quelque chose de propre à défendre. C\'est la combinaison la plus mature : présence sans dépendance à la reconnaissance.', de: 'Du weißt, dass deine Geschichte Wert hat, auch ohne der Protagonist aller Szenen sein zu müssen. Aber du hast auch etwas Eigenes zu verteidigen. Es ist die ausgereifteste Kombination: Präsenz ohne Abhängigkeit von Anerkennung.', it: 'Sai che la tua storia ha valore anche senza dover essere il protagonista di tutte le scene. Ma hai anche qualcosa di tuo da difendere. È la combinazione più matura: presenza senza dipendenza dal riconoscimento.', pt: 'Você sabe que sua história tem valor mesmo sem precisar ser o protagonista de todas as cenas. Mas você também tem algo próprio para defender. É a combinação mais madura: presença sem dependência do reconhecimento.' } },
    { name: { es: 'El Protagonista en Construcción', en: 'The Protagonist Under Construction', fr: 'Le Protagoniste en Construction', de: 'Der Protagonist im Aufbau', it: 'Il Protagonista in Costruzione', pt: 'O Protagonista em Construção' }, dimensions: ['P', 'H'], photo: '/characters/protagonist-builder.jpg', description: { es: 'Construye su historia activamente con visión de largo plazo.', en: 'Actively builds their story with long-term vision.', fr: 'Construit activement son histoire avec une vision à long terme.', de: 'Baut aktiv seine Geschichte mit langfristiger Vision auf.', it: 'Costruisce attivamente la sua storia con visione a lungo termine.', pt: 'Constrói sua história ativamente com visão de longo prazo.' }, philosophy: { es: 'No esperas que la historia te pase — la construyes. Tienes la disposición al riesgo del héroe y la agencia del personaje principal. Tu historia no será un accidente.', en: 'You don\'t wait for the story to happen to you — you build it. You have the hero\'s openness to risk and the main character\'s agency. Your story will not be an accident.', fr: 'Tu n\'attends pas que l\'histoire t\'arrive — tu la construis. Tu as la disposition au risque du héros et l\'agency du personnage principal. Ton histoire ne sera pas un accident.', de: 'Du wartest nicht darauf, dass die Geschichte dir passiert — du baust sie. Du hast die Risikobereitschaft des Helden und die Handlungsmacht der Hauptfigur. Deine Geschichte wird kein Zufall sein.', it: 'Non aspetti che la storia ti accada — la costruisci. Hai la disposizione al rischio dell\'eroe e l\'agency del personaggio principale. La tua storia non sarà un caso.', pt: 'Você não espera que a história aconteça com você — a constrói. Você tem a disposição para o risco do herói e a agência do personagem principal. Sua história não será um acidente.' } },
    { name: { es: 'El Necesario', en: 'The Necessary One', fr: 'Le Nécessaire', de: 'Der Notwendige', it: 'Il Necessario', pt: 'O Necessário' }, dimensions: ['N', 'S'], photo: '/characters/necessary-one.jpg', description: { es: 'Imprescindible en la historia de otros aunque no tenga la suya.', en: 'Indispensable in others\' stories even without their own.', fr: 'Indispensable dans l\'histoire des autres même sans avoir la sienne.', de: 'Unverzichtbar in der Geschichte anderer, auch ohne die eigene.', it: 'Indispensabile nella storia degli altri anche senza avere la propria.', pt: 'Indispensável na história dos outros mesmo sem ter a sua.' }, philosophy: { es: 'Tu presencia constante y confiable hace posible que los demás construyan sus historias. No siempre buscas tu propio arco, pero el tejido social depende de personas como tú. Eso tiene un valor que no siempre se celebra suficientemente.', en: 'Your constant and reliable presence makes it possible for others to build their stories. You don\'t always seek your own arc, but the social fabric depends on people like you. That has value that isn\'t always celebrated enough.', fr: 'Ta présence constante et fiable permet aux autres de construire leurs histoires. Tu ne cherches pas toujours ton propre arc, mais le tissu social dépend de personnes comme toi. Cela a une valeur qui n\'est pas toujours assez célébrée.', de: 'Deine beständige und zuverlässige Präsenz ermöglicht es anderen, ihre Geschichten aufzubauen. Du suchst nicht immer deinen eigenen Bogen, aber das soziale Gefüge hängt von Menschen wie dir ab. Das hat einen Wert, der nicht immer ausreichend gefeiert wird.', it: 'La tua presenza costante e affidabile permette agli altri di costruire le loro storie. Non cerchi sempre il tuo arco, ma il tessuto sociale dipende da persone come te. Questo ha un valore che non sempre viene celebrato abbastanza.', pt: 'Sua presença constante e confiável torna possível que os outros construam suas histórias. Você nem sempre busca seu próprio arco, mas o tecido social depende de pessoas como você. Isso tem um valor que nem sempre é celebrado o suficiente.' } },
  ],
};

export async function seedNpc(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'npc' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'npc',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['pop-culture'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
