import type { PrismaClient } from '../../generated/prisma/client.js';

export async function seedMaterialist(prisma: PrismaClient, catMap: Record<string, string>) {
  const data = {
    slug: 'materialist',
    title: { es: '¿Qué tan materialista eres?', en: 'How materialistic are you?', fr: 'À quel point êtes-vous matérialiste ?', de: 'Wie materialistisch bist du?', it: 'Quanto sei materialista?', pt: 'Quão materialista você é?' },
    description: { es: 'El dinero no da la felicidad — pero la falta de él tampoco. ¿Dónde está tu equilibrio real?', en: 'Money doesn\'t buy happiness — but neither does the lack of it. Where is your real balance?', fr: 'L\'argent ne donne pas le bonheur — mais son absence non plus. Où est votre vrai équilibre ?', de: 'Geld gibt kein Glück — aber sein Fehlen auch nicht. Wo liegt dein echtes Gleichgewicht?', it: 'Il denaro non dà la felicità — ma nemmeno la sua mancanza. Dove sta il tuo vero equilibrio?', pt: 'O dinheiro não traz felicidade — mas a falta dele também não. Onde está seu equilíbrio real?' },
    scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
    categoryId: catMap['life'],
    sortOrder: 4,
    dimensionLabels: {
      es: { M: 'Materialismo', E: 'Experiencial', A: 'Altruismo', S: 'Suficiencia' },
      en: { M: 'Materialism', E: 'Experiential', A: 'Altruism', S: 'Sufficiency' },
      fr: { M: 'Matérialisme', E: 'Expérientiel', A: 'Altruisme', S: 'Suffisance' },
      de: { M: 'Materialismus', E: 'Erlebnisorientiert', A: 'Altruismus', S: 'Genügsamkeit' },
      it: { M: 'Materialismo', E: 'Esperienziale', A: 'Altruismo', S: 'Sufficienza' },
      pt: { M: 'Materialismo', E: 'Experiencial', A: 'Altruísmo', S: 'Suficiência' },
    },
    questions: [
      {
        id: 1,
        situation: { es: 'Recibes un bono inesperado. ¿En qué lo gastas primero?', en: 'You receive an unexpected bonus. What do you spend it on first?', fr: 'Vous recevez une prime inattendue. En quoi l\'investissez-vous en premier ?', de: 'Du erhältst einen unerwarteten Bonus. Wofür gibst du ihn zuerst aus?', it: 'Ricevi un bonus inaspettato. In cosa lo spendi per primo?', pt: 'Você recebe um bônus inesperado. Em que o gasta primeiro?' },
        options: [
          { text: { es: 'En algo que quería comprar hace tiempo: un objeto, ropa, tecnología.', en: 'On something I\'ve wanted to buy for a while: an item, clothes, technology.', fr: 'Sur quelque chose que je voulais acheter depuis un moment : un objet, des vêtements, de la technologie.', de: 'Auf etwas, das ich schon lange kaufen wollte: einen Gegenstand, Kleidung, Technologie.', it: 'In qualcosa che volevo comprare da tempo: un oggetto, vestiti, tecnologia.', pt: 'Em algo que queria comprar há tempo: um objeto, roupa, tecnologia.' }, dimension: 'M' },
          { text: { es: 'En una experiencia: viaje, cena especial, concierto.', en: 'On an experience: a trip, special dinner, concert.', fr: 'Sur une expérience : voyage, dîner spécial, concert.', de: 'Auf ein Erlebnis: Reise, besonderes Dinner, Konzert.', it: 'In un\'esperienza: viaggio, cena speciale, concerto.', pt: 'Em uma experiência: viagem, jantar especial, show.' }, dimension: 'E' },
          { text: { es: 'En parte lo ahorro y en parte ayudo a alguien que lo necesita.', en: 'Partly I save it and partly I help someone who needs it.', fr: 'Je l\'épargne en partie et aide en partie quelqu\'un qui en a besoin.', de: 'Zum Teil spare ich es und zum Teil helfe ich jemandem, der es braucht.', it: 'In parte lo risparmio e in parte aiuto qualcuno che ne ha bisogno.', pt: 'Em parte economizo e em parte ajudo alguém que precisa.' }, dimension: 'A' },
          { text: { es: 'Lo ahorro. No necesito nada urgente y la seguridad financiera vale más.', en: 'I save it. I don\'t need anything urgent and financial security is worth more.', fr: 'Je l\'épargne. Je n\'ai besoin de rien d\'urgent et la sécurité financière vaut plus.', de: 'Ich spare es. Ich brauche nichts Dringendes und finanzielle Sicherheit ist wertvoller.', it: 'Lo risparmio. Non ho bisogno di niente di urgente e la sicurezza finanziaria vale di più.', pt: 'Economizo. Não preciso de nada urgente e a segurança financeira vale mais.' }, dimension: 'S' },
        ],
      },
      {
        id: 2,
        situation: { es: 'Tienes que elegir entre un trabajo con salario alto pero horrible, o uno que te apasiona con salario modesto.', en: 'You have to choose between a high-paying but terrible job, or one you\'re passionate about with a modest salary.', fr: 'Vous devez choisir entre un emploi bien payé mais horrible, ou un emploi qui vous passionne avec un salaire modeste.', de: 'Du musst zwischen einem hochbezahlten, aber schrecklichen Job oder einem, der dich begeistert, mit einem bescheidenen Gehalt wählen.', it: 'Devi scegliere tra un lavoro con alto salario ma orribile, o uno che ti appassiona con salario modesto.', pt: 'Você tem que escolher entre um trabalho com salário alto mas horrível, ou um que te apaixona com salário modesto.' },
        options: [
          { text: { es: 'El salario alto. Con ese dinero puedo construir la vida que quiero fuera del trabajo.', en: 'The high salary. With that money I can build the life I want outside of work.', fr: 'Le salaire élevé. Avec cet argent, je peux construire la vie que je veux en dehors du travail.', de: 'Das hohe Gehalt. Mit diesem Geld kann ich das Leben aufbauen, das ich außerhalb der Arbeit will.', it: 'Il salario alto. Con quei soldi posso costruire la vita che voglio fuori dal lavoro.', pt: 'O salário alto. Com esse dinheiro posso construir a vida que quero fora do trabalho.' }, dimension: 'M' },
          { text: { es: 'El que me apasiona. El dinero importa, pero el bienestar diario más.', en: 'The one I\'m passionate about. Money matters, but daily well-being matters more.', fr: 'Celui qui me passionne. L\'argent compte, mais le bien-être quotidien encore plus.', de: 'Den, der mich begeistert. Geld ist wichtig, aber das tägliche Wohlbefinden ist wichtiger.', it: 'Quello che mi appassiona. Il denaro conta, ma il benessere quotidiano di più.', pt: 'O que me apaixona. O dinheiro importa, mas o bem-estar diário importa mais.' }, dimension: 'E' },
          { text: { es: 'El que me permita aportar más a causas que me importan.', en: 'The one that lets me contribute more to causes that matter to me.', fr: 'Celui qui me permettra de contribuer davantage à des causes qui me tiennent à cœur.', de: 'Den, der es mir erlaubt, mehr zu Zwecken beizutragen, die mir wichtig sind.', it: 'Quello che mi permette di contribuire di più a cause che mi stanno a cuore.', pt: 'O que me permite contribuir mais para causas que me importam.' }, dimension: 'A' },
          { text: { es: 'El modesto. Si cubro mis necesidades básicas, no necesito más.', en: 'The modest one. If I cover my basic needs, I don\'t need more.', fr: 'Le modeste. Si je couvre mes besoins de base, je n\'en ai pas besoin de plus.', de: 'Den bescheidenen. Wenn ich meine Grundbedürfnisse decke, brauche ich nicht mehr.', it: 'Quello modesto. Se copro i miei bisogni di base, non ho bisogno di altro.', pt: 'O modesto. Se cobrir minhas necessidades básicas, não preciso de mais.' }, dimension: 'S' },
        ],
      },
      {
        id: 3,
        situation: { es: '¿Cómo describes tu relación con las marcas y los objetos de lujo?', en: 'How would you describe your relationship with brands and luxury items?', fr: 'Comment décrivez-vous votre relation avec les marques et les objets de luxe ?', de: 'Wie beschreibst du deine Beziehung zu Marken und Luxusgütern?', it: 'Come descrivi il tuo rapporto con i marchi e gli oggetti di lusso?', pt: 'Como você descreve sua relação com marcas e objetos de luxo?' },
        options: [
          { text: { es: 'Me importan. La calidad y el estatus que proyectan tienen valor real para mí.', en: 'They matter to me. The quality and status they project have real value for me.', fr: 'Ils comptent pour moi. La qualité et le statut qu\'ils projettent ont une valeur réelle pour moi.', de: 'Sie sind mir wichtig. Die Qualität und der Status, den sie projizieren, haben für mich echten Wert.', it: 'Mi importano. La qualità e lo status che proiettano hanno valore reale per me.', pt: 'Me importam. A qualidade e o status que projetam têm valor real para mim.' }, dimension: 'M' },
          { text: { es: 'Solo si mejoran genuinamente una experiencia. No pago por la etiqueta.', en: 'Only if they genuinely improve an experience. I don\'t pay for the label.', fr: 'Seulement s\'ils améliorent genuinement une expérience. Je ne paie pas pour l\'étiquette.', de: 'Nur wenn sie eine Erfahrung wirklich verbessern. Ich zahle nicht für das Etikett.', it: 'Solo se migliorano genuinamente un\'esperienza. Non pago per l\'etichetta.', pt: 'Somente se melhorarem genuinamente uma experiência. Não pago pela etiqueta.' }, dimension: 'E' },
          { text: { es: 'Me generan incomodidad. Prefiero gastar ese dinero en algo con más impacto.', en: 'They make me uncomfortable. I prefer to spend that money on something with more impact.', fr: 'Ils me mettent mal à l\'aise. Je préfère dépenser cet argent pour quelque chose ayant plus d\'impact.', de: 'Sie bereiten mir Unbehagen. Ich gebe dieses Geld lieber für etwas mit mehr Wirkung aus.', it: 'Mi generano disagio. Preferisco spendere quei soldi in qualcosa con più impatto.', pt: 'Me geram desconforto. Prefiro gastar esse dinheiro em algo com mais impacto.' }, dimension: 'A' },
          { text: { es: 'No me interesan. Lo básico de buena calidad es suficiente.', en: 'They don\'t interest me. Quality basics are enough.', fr: 'Ils ne m\'intéressent pas. Les produits de base de bonne qualité suffisent.', de: 'Sie interessieren mich nicht. Qualitativ hochwertige Grundausstattung reicht.', it: 'Non mi interessano. Le cose di base di buona qualità sono sufficienti.', pt: 'Não me interessam. O básico de boa qualidade é suficiente.' }, dimension: 'S' },
        ],
      },
      {
        id: 4,
        situation: { es: 'Tu vecino/a compra un auto nuevo y llamativo. ¿Qué sientes?', en: 'Your neighbor buys a flashy new car. What do you feel?', fr: 'Votre voisin(e) achète une voiture neuve et tape-à-l\'œil. Que ressentez-vous ?', de: 'Dein Nachbar kauft ein auffälliges neues Auto. Was fühlst du?', it: 'Il tuo vicino compra una macchina nuova e appariscente. Cosa provi?', pt: 'Seu vizinho compra um carro novo e chamativo. O que você sente?' },
        options: [
          { text: { es: 'Envidia un poco. Me recuerda que yo también quiero ese tipo de cosas.', en: 'A little envy. It reminds me that I want those kinds of things too.', fr: 'Un peu d\'envie. Ça me rappelle que je veux aussi ce genre de choses.', de: 'Ein bisschen Neid. Es erinnert mich daran, dass auch ich solche Dinge will.', it: 'Un po\' d\'invidia. Mi ricorda che voglio anche io quel tipo di cose.', pt: 'Um pouco de inveja. Me lembra que eu também quero esse tipo de coisa.' }, dimension: 'M' },
          { text: { es: 'Nada en particular. No valoro los autos como símbolo de nada.', en: 'Nothing in particular. I don\'t value cars as a symbol of anything.', fr: 'Rien de particulier. Je ne valorise pas les voitures comme symbole de quoi que ce soit.', de: 'Nichts Besonderes. Ich bewerte Autos nicht als Symbol für irgendwas.', it: 'Niente in particolare. Non valuto le auto come simbolo di niente.', pt: 'Nada em particular. Não valorizo carros como símbolo de nada.' }, dimension: 'E' },
          { text: { es: 'Me parece un gasto innecesario cuando hay necesidades urgentes en el mundo.', en: 'I think it\'s an unnecessary expense when there are urgent needs in the world.', fr: 'Je pense que c\'est une dépense inutile alors qu\'il y a des besoins urgents dans le monde.', de: 'Mir erscheint es als unnötige Ausgabe, wenn es dringende Bedürfnisse in der Welt gibt.', it: 'Mi sembra una spesa inutile quando ci sono bisogni urgenti nel mondo.', pt: 'Parece-me um gasto desnecessário quando há necessidades urgentes no mundo.' }, dimension: 'A' },
          { text: { es: 'Que cada quien gasta su dinero como quiere. Yo prefiero no necesitar tanto.', en: 'Everyone spends their money how they want. I prefer not to need so much.', fr: 'Chacun dépense son argent comme il le souhaite. Moi, je préfère ne pas avoir autant besoin.', de: 'Jeder gibt sein Geld so aus, wie er will. Ich bevorzuge es, nicht so viel zu brauchen.', it: 'Ognuno spende i propri soldi come vuole. Io preferisco non averne così tanto bisogno.', pt: 'Cada um gasta seu dinheiro como quer. Eu prefiro não precisar tanto.' }, dimension: 'S' },
        ],
      },
      {
        id: 5,
        situation: { es: 'Si tuvieras mucho más dinero del que necesitas, ¿qué harías con el resto?', en: 'If you had much more money than you need, what would you do with the rest?', fr: 'Si vous aviez beaucoup plus d\'argent que nécessaire, que feriez-vous avec le reste ?', de: 'Wenn du viel mehr Geld hättest, als du brauchst, was würdest du mit dem Rest machen?', it: 'Se avessi molti più soldi di quanti ne hai bisogno, cosa faresti con il resto?', pt: 'Se você tivesse muito mais dinheiro do que precisa, o que faria com o restante?' },
        options: [
          { text: { es: 'Actualizar mi estilo de vida: casa más grande, viajes de lujo, mejores cosas.', en: 'Upgrade my lifestyle: bigger house, luxury travel, better things.', fr: 'Améliorer mon style de vie : maison plus grande, voyages de luxe, meilleures choses.', de: 'Meinen Lebensstil verbessern: größeres Haus, Luxusreisen, bessere Dinge.', it: 'Aggiornare il mio stile di vita: casa più grande, viaggi di lusso, cose migliori.', pt: 'Atualizar meu estilo de vida: casa maior, viagens de luxo, coisas melhores.' }, dimension: 'M' },
          { text: { es: 'Más experiencias: explorar el mundo, aprender cosas, vivir más plenamente.', en: 'More experiences: explore the world, learn things, live more fully.', fr: 'Plus d\'expériences : explorer le monde, apprendre des choses, vivre plus pleinement.', de: 'Mehr Erlebnisse: die Welt erkunden, Dinge lernen, vollständiger leben.', it: 'Più esperienze: esplorare il mondo, imparare cose, vivere più pienamente.', pt: 'Mais experiências: explorar o mundo, aprender coisas, viver mais plenamente.' }, dimension: 'E' },
          { text: { es: 'Donarlo o invertirlo en proyectos que generen impacto.', en: 'Donate it or invest it in projects that generate impact.', fr: 'Le donner ou l\'investir dans des projets qui génèrent un impact.', de: 'Es spenden oder in Projekte investieren, die eine Wirkung erzeugen.', it: 'Donarlo o investirlo in progetti che generano impatto.', pt: 'Doá-lo ou investir em projetos que gerem impacto.' }, dimension: 'A' },
          { text: { es: 'Guardarlo. La seguridad de saber que tengo más de lo necesario es el regalo.', en: 'Save it. The security of knowing I have more than enough is the gift.', fr: 'Le garder. La sécurité de savoir que j\'en ai plus que nécessaire est le cadeau.', de: 'Es sparen. Die Sicherheit zu wissen, dass ich mehr als genug habe, ist das Geschenk.', it: 'Tenerlo. La sicurezza di sapere che ho più del necessario è il regalo.', pt: 'Guardar. A segurança de saber que tenho mais do que preciso é o presente.' }, dimension: 'S' },
        ],
      },
      {
        id: 6,
        situation: { es: 'Tus amigos se van de vacaciones de lujo y no puedes pagar. ¿Qué haces?', en: 'Your friends go on a luxury vacation and you can\'t afford it. What do you do?', fr: 'Vos amis partent en vacances de luxe et vous ne pouvez pas vous le permettre. Que faites-vous ?', de: 'Deine Freunde machen Luxusurlaub und du kannst es dir nicht leisten. Was machst du?', it: 'I tuoi amici vanno in vacanza di lusso e non puoi permettertelo. Cosa fai?', pt: 'Seus amigos vão de férias de luxo e você não pode pagar. O que você faz?' },
        options: [
          { text: { es: 'Busco la forma de ir aunque tenga que ajustar gastos en otras áreas. No me quiero quedar afuera.', en: 'I find a way to go even if I have to cut spending in other areas. I don\'t want to be left out.', fr: 'Je trouve un moyen d\'y aller même si je dois réduire les dépenses dans d\'autres domaines. Je ne veux pas être laissé(e) de côté.', de: 'Ich finde einen Weg zu gehen, auch wenn ich in anderen Bereichen sparen muss. Ich will nicht ausgeschlossen werden.', it: 'Trovo il modo di andare anche se devo tagliare le spese in altre aree. Non voglio restare fuori.', pt: 'Busco uma forma de ir mesmo que tenha que ajustar gastos em outras áreas. Não quero ficar de fora.' }, dimension: 'M' },
          { text: { es: 'Organizo mi propio viaje a un lugar diferente que sí puedo pagar y disfruto igual.', en: 'I organize my own trip to a different place I can afford and enjoy it just as much.', fr: 'J\'organise mon propre voyage dans un endroit différent que je peux me permettre et j\'en profite autant.', de: 'Ich organisiere meine eigene Reise an einen anderen Ort, den ich mir leisten kann, und genieße sie genauso.', it: 'Organizzo il mio viaggio in un posto diverso che posso permettermi e mi diverto ugualmente.', pt: 'Organizo minha própria viagem para um lugar diferente que posso pagar e aproveito igualmente.' }, dimension: 'E' },
          { text: { es: 'Me parece bien. El dinero que no gasto ahí puede ser útil en otras cosas.', en: 'That\'s fine by me. The money I don\'t spend there can be useful elsewhere.', fr: 'Ça me convient. L\'argent que je ne dépense pas là peut être utile ailleurs.', de: 'Das ist mir recht. Das Geld, das ich dort nicht ausgebe, kann anderswo nützlich sein.', it: 'Va bene per me. I soldi che non spendo lì possono essere utili altrove.', pt: 'Acho ótimo. O dinheiro que não gasto ali pode ser útil em outras coisas.' }, dimension: 'A' },
          { text: { es: 'Me quedo. No me afecta no ir. Hay cosas que disfruto sin gastar.', en: 'I stay home. Not going doesn\'t bother me. There are things I enjoy without spending.', fr: 'Je reste. Ne pas y aller ne m\'affecte pas. Il y a des choses dont je profite sans dépenser.', de: 'Ich bleibe. Nicht zu gehen beeinträchtigt mich nicht. Es gibt Dinge, die ich genieße, ohne Geld auszugeben.', it: 'Resto. Non mi influisce non andare. Ci sono cose che apprezzo senza spendere.', pt: 'Fico. Não me afeta não ir. Há coisas que aproveito sem gastar.' }, dimension: 'S' },
        ],
      },
      {
        id: 7,
        situation: { es: '¿Qué tan frecuentemente piensas en dinero o posesiones?', en: 'How frequently do you think about money or possessions?', fr: 'À quelle fréquence pensez-vous à l\'argent ou aux possessions ?', de: 'Wie häufig denkst du an Geld oder Besitz?', it: 'Con quanta frequenza pensi al denaro o alle posizioni?', pt: 'Com que frequência você pensa em dinheiro ou posses?' },
        options: [
          { text: { es: 'Bastante. El dinero y lo que permite obtener está muy presente en mi mente.', en: 'Quite a lot. Money and what it allows to obtain is very present in my mind.', fr: 'Beaucoup. L\'argent et ce qu\'il permet d\'obtenir est très présent dans mon esprit.', de: 'Ziemlich oft. Geld und was es ermöglicht zu bekommen, ist sehr präsent in meinem Kopf.', it: 'Abbastanza. Il denaro e ciò che permette di ottenere è molto presente nella mia mente.', pt: 'Bastante. O dinheiro e o que permite obter está muito presente na minha mente.' }, dimension: 'M' },
          { text: { es: 'Cuando planifico experiencias o cuando algo me parece que vale la pena.', en: 'When I plan experiences or when something seems worth it to me.', fr: 'Quand je planifie des expériences ou quand quelque chose me semble en valoir la peine.', de: 'Wenn ich Erlebnisse plane oder wenn mir etwas es wert zu sein scheint.', it: 'Quando planifico esperienze o quando qualcosa mi sembra che valga la pena.', pt: 'Quando planejo experiências ou quando algo parece que vale a pena.' }, dimension: 'E' },
          { text: { es: 'Cuando pienso en cómo distribuirlo de forma más justa o útil.', en: 'When I think about how to distribute it in a more fair or useful way.', fr: 'Quand je pense à la façon de le distribuer de manière plus juste ou utile.', de: 'Wenn ich darüber nachdenke, wie ich es fairer oder nützlicher verteilen kann.', it: 'Quando penso a come distribuirlo in modo più equo o utile.', pt: 'Quando penso em como distribuí-lo de forma mais justa ou útil.' }, dimension: 'A' },
          { text: { es: 'Lo justo. Solo cuando hay algo concreto que resolver.', en: 'Just enough. Only when there\'s something concrete to resolve.', fr: 'Juste ce qu\'il faut. Seulement quand il y a quelque chose de concret à résoudre.', de: 'Gerade genug. Nur wenn es etwas Konkretes zu lösen gibt.', it: 'Il giusto. Solo quando c\'è qualcosa di concreto da risolvere.', pt: 'O suficiente. Só quando há algo concreto para resolver.' }, dimension: 'S' },
        ],
      },
      {
        id: 8,
        situation: { es: 'Una persona rica que hace poco bien con su riqueza. ¿Qué piensas?', en: 'A wealthy person who does little good with their wealth. What do you think?', fr: 'Une personne riche qui fait peu de bien avec sa richesse. Qu\'en pensez-vous ?', de: 'Eine reiche Person, die wenig Gutes mit ihrem Reichtum tut. Was denkst du?', it: 'Una persona ricca che fa poco bene con la sua ricchezza. Cosa pensi?', pt: 'Uma pessoa rica que faz pouco bem com sua riqueza. O que você pensa?' },
        options: [
          { text: { es: 'Es su dinero, que haga lo que quiera. Yo también usaría el dinero para vivir bien.', en: 'It\'s their money, let them do what they want. I\'d also use the money to live well.', fr: 'C\'est son argent, qu\'il fasse ce qu\'il veut. J\'utiliserais aussi cet argent pour bien vivre.', de: 'Es ist sein Geld, lass ihn machen, was er will. Ich würde das Geld auch benutzen, um gut zu leben.', it: 'È il suo denaro, lascia che faccia quello che vuole. Anch\'io userei il denaro per vivere bene.', pt: 'É o dinheiro dele, que faça o que quiser. Eu também usaria o dinheiro para viver bem.' }, dimension: 'M' },
          { text: { es: 'Me parece una oportunidad desperdiciada de vivir más plenamente.', en: 'I think it\'s a wasted opportunity to live more fully.', fr: 'Je pense que c\'est une occasion gâchée de vivre plus pleinement.', de: 'Mir erscheint es als verschwendete Gelegenheit, vollständiger zu leben.', it: 'Mi sembra un\'opportunità sprecata di vivere più pienamente.', pt: 'Me parece uma oportunidade desperdiçada de viver mais plenamente.' }, dimension: 'E' },
          { text: { es: 'Me parece irresponsable. Con esa riqueza podría cambiar vidas.', en: 'I think it\'s irresponsible. With that wealth they could change lives.', fr: 'Je pense que c\'est irresponsable. Avec cette richesse, il pourrait changer des vies.', de: 'Mir erscheint es unverantwortlich. Mit diesem Reichtum könnten sie Leben verändern.', it: 'Mi sembra irresponsabile. Con quella ricchezza potrebbe cambiare delle vite.', pt: 'Me parece irresponsável. Com essa riqueza poderia mudar vidas.' }, dimension: 'A' },
          { text: { es: 'Tener tanto y no necesitarlo me parece una forma de esclavitud voluntaria.', en: 'Having so much and not needing it seems to me a form of voluntary slavery.', fr: 'Avoir autant et ne pas en avoir besoin me semble une forme d\'esclavage volontaire.', de: 'So viel zu haben und es nicht zu brauchen erscheint mir eine Form freiwilliger Knechtschaft.', it: 'Avere così tanto e non averne bisogno mi sembra una forma di schiavitù volontaria.', pt: 'Ter tanto e não precisar parece-me uma forma de escravidão voluntária.' }, dimension: 'S' },
        ],
      },
      {
        id: 9,
        situation: { es: 'Ves una notificación de "oferta de tiempo limitado" en algo que no necesitas pero que está muy rebajado.', en: 'You see a "limited time offer" notification on something you don\'t need but is heavily discounted.', fr: 'Vous voyez une notification d\'offre à durée limitée pour quelque chose dont vous n\'avez pas besoin mais qui est très réduit.', de: 'Du siehst eine Benachrichtigung über ein "zeitlich begrenztes Angebot" für etwas, das du nicht brauchst, aber stark reduziert ist.', it: 'Vedi una notifica di "offerta a tempo limitato" su qualcosa che non hai bisogno ma che è molto scontato.', pt: 'Você vê uma notificação de "oferta por tempo limitado" em algo que não precisa, mas que está muito em promoção.' },
        options: [
          { text: { es: 'Hay grandes posibilidades de que lo compre. Si está barato, es una oportunidad.', en: 'There\'s a good chance I\'ll buy it. If it\'s cheap, it\'s an opportunity.', fr: 'Il y a de fortes chances que je l\'achète. Si c\'est bon marché, c\'est une opportunité.', de: 'Es gibt eine gute Chance, dass ich es kaufe. Wenn es billig ist, ist es eine Gelegenheit.', it: 'Ci sono grandi possibilità che lo compri. Se è a buon prezzo, è un\'opportunità.', pt: 'Há grandes chances de que eu compre. Se está barato, é uma oportunidade.' }, dimension: 'M' },
          { text: { es: 'Solo si me permitiría una experiencia que de otra forma no tendría.', en: 'Only if it would allow me an experience I otherwise wouldn\'t have.', fr: 'Seulement si cela me permettrait une expérience que je n\'aurais pas autrement.', de: 'Nur wenn es mir ein Erlebnis ermöglichen würde, das ich sonst nicht hätte.', it: 'Solo se mi permettesse un\'esperienza che altrimenti non avrei.', pt: 'Somente se me permitir uma experiência que de outra forma não teria.' }, dimension: 'E' },
          { text: { es: 'Lo ignoro. Si no lo necesito, no lo compro sin importar el precio.', en: 'I ignore it. If I don\'t need it, I don\'t buy it regardless of the price.', fr: 'Je l\'ignore. Si je n\'en ai pas besoin, je ne l\'achète pas, peu importe le prix.', de: 'Ich ignoriere es. Wenn ich es nicht brauche, kaufe ich es nicht, egal wie günstig.', it: 'Lo ignoro. Se non ne ho bisogno, non lo compro indipendentemente dal prezzo.', pt: 'Ignoro. Se não preciso, não compro independentemente do preço.' }, dimension: 'S' },
          { text: { es: 'Lo ignoro. Ese dinero puede ser más útil en otra parte.', en: 'I ignore it. That money can be more useful elsewhere.', fr: 'Je l\'ignore. Cet argent peut être plus utile ailleurs.', de: 'Ich ignoriere es. Dieses Geld kann anderswo nützlicher sein.', it: 'Lo ignoro. Quel denaro può essere più utile altrove.', pt: 'Ignoro. Esse dinheiro pode ser mais útil em outro lugar.' }, dimension: 'A' },
        ],
      },
      {
        id: 10,
        situation: { es: '¿Qué crees que el dinero puede y no puede comprar?', en: 'What do you think money can and cannot buy?', fr: 'Que pensez-vous que l\'argent peut et ne peut pas acheter ?', de: 'Was glaubst du, kann Geld kaufen und nicht kaufen?', it: 'Cosa pensi che il denaro possa e non possa comprare?', pt: 'O que você acha que o dinheiro pode e não pode comprar?' },
        options: [
          { text: { es: 'Puede comprar casi todo lo que importa: seguridad, acceso, opciones. Negar eso es ingenuo.', en: 'It can buy almost everything that matters: security, access, options. Denying that is naive.', fr: 'Il peut acheter presque tout ce qui compte : sécurité, accès, options. Nier cela est naïf.', de: 'Es kann fast alles kaufen, was wichtig ist: Sicherheit, Zugang, Optionen. Das zu leugnen ist naiv.', it: 'Può comprare quasi tutto ciò che conta: sicurezza, accesso, opzioni. Negarlo è ingenuo.', pt: 'Pode comprar quase tudo que importa: segurança, acesso, opções. Negar isso é ingênuo.' }, dimension: 'M' },
          { text: { es: 'Puede comprar las condiciones para vivir bien, pero no la vida misma.', en: 'It can buy the conditions for living well, but not life itself.', fr: 'Il peut acheter les conditions pour bien vivre, mais pas la vie elle-même.', de: 'Es kann die Bedingungen für ein gutes Leben kaufen, aber nicht das Leben selbst.', it: 'Può comprare le condizioni per vivere bene, ma non la vita stessa.', pt: 'Pode comprar as condições para viver bem, mas não a própria vida.' }, dimension: 'E' },
          { text: { es: 'Puede comprar cambios reales si se usa bien. El problema es que rara vez se usa bien.', en: 'It can buy real change if used well. The problem is it\'s rarely used well.', fr: 'Il peut acheter de vrais changements s\'il est bien utilisé. Le problème, c\'est qu\'il est rarement bien utilisé.', de: 'Es kann echte Veränderungen kaufen, wenn es gut eingesetzt wird. Das Problem ist, dass es selten gut eingesetzt wird.', it: 'Può comprare cambiamenti reali se usato bene. Il problema è che raramente viene usato bene.', pt: 'Pode comprar mudanças reais se usado bem. O problema é que raramente é usado bem.' }, dimension: 'A' },
          { text: { es: 'Compra tranquilidad y nada más. El resto de lo que importa no se vende.', en: 'It buys peace of mind and nothing more. The rest of what matters can\'t be bought.', fr: 'Il achète la tranquillité d\'esprit et rien de plus. Le reste de ce qui compte ne se vend pas.', de: 'Es kauft Seelenfrieden und nichts mehr. Der Rest von dem, was wichtig ist, kann nicht gekauft werden.', it: 'Compra tranquillità e nient\'altro. Il resto di ciò che conta non si vende.', pt: 'Compra tranquilidade e nada mais. O resto do que importa não tem preço.' }, dimension: 'S' },
        ],
      },
    ],
    characters: [
      { name: { es: 'El Materialista Honesto', en: 'The Honest Materialist', fr: 'Le Matérialiste Honnête', de: 'Der Ehrliche Materialist', it: 'Il Materialista Onesto', pt: 'O Materialista Honesto' }, dimensions: ['M'], photo: '/characters/materialist.jpg', description: { es: 'Los objetos y el dinero le generan bienestar real. No lo niega.', en: 'Objects and money generate real well-being for them. They don\'t deny it.', fr: 'Les objets et l\'argent lui procurent un vrai bien-être. Il ne le nie pas.', de: 'Objekte und Geld erzeugen echtes Wohlbefinden für sie. Sie leugnen es nicht.', it: 'Gli oggetti e il denaro gli generano vero benessere. Non lo nega.', pt: 'Objetos e dinheiro geram bem-estar real. Não nega isso.' }, philosophy: { es: 'Para ti, las posesiones y el dinero son genuinas fuentes de satisfacción y seguridad. No te disculpas por ello. El problema solo aparece cuando el materialismo se convierte en identidad en lugar de herramienta.', en: 'For you, possessions and money are genuine sources of satisfaction and security. You don\'t apologize for it. The problem only appears when materialism becomes identity instead of tool.', fr: 'Pour vous, les possessions et l\'argent sont de véritables sources de satisfaction et de sécurité. Vous ne vous en excusez pas. Le problème n\'apparaît que lorsque le matérialisme devient une identité plutôt qu\'un outil.', de: 'Für dich sind Besitz und Geld echte Quellen der Zufriedenheit und Sicherheit. Du entschuldigst dich nicht dafür. Das Problem erscheint nur, wenn Materialismus zur Identität statt zum Werkzeug wird.', it: 'Per te, le proprietà e il denaro sono genuine fonti di soddisfazione e sicurezza. Non ti scusi per questo. Il problema appare solo quando il materialismo diventa identità invece che strumento.', pt: 'Para você, as posses e o dinheiro são genuínas fontes de satisfação e segurança. Não se desculpa por isso. O problema só aparece quando o materialismo se torna identidade em vez de ferramenta.' } },
      { name: { es: 'El Experiencial', en: 'The Experiential', fr: 'L\'Expérientiel', de: 'Der Erlebnisorientierte', it: 'L\'Esperienziale', pt: 'O Experiencial' }, dimensions: ['E'], photo: '/characters/experiential.jpg', description: { es: 'El dinero sirve para vivir, no para acumular.', en: 'Money is for living, not for accumulating.', fr: 'L\'argent sert à vivre, pas à accumuler.', de: 'Geld dient zum Leben, nicht zum Anhäufen.', it: 'Il denaro serve per vivere, non per accumulare.', pt: 'O dinheiro serve para viver, não para acumular.' }, philosophy: { es: 'Para ti, el valor del dinero está en lo que permite vivir, no en lo que permite tener. Prefiere gastar en momentos que en objetos, en recuerdos que en cosas.', en: 'For you, the value of money lies in what it allows you to live, not in what it allows you to have. You prefer spending on moments rather than objects, on memories rather than things.', fr: 'Pour vous, la valeur de l\'argent réside dans ce qu\'il permet de vivre, pas dans ce qu\'il permet d\'avoir. Vous préférez dépenser pour des moments plutôt que pour des objets, pour des souvenirs plutôt que pour des choses.', de: 'Für dich liegt der Wert des Geldes darin, was es erlaubt zu leben, nicht in dem, was es erlaubt zu besitzen. Du gibst lieber für Momente als für Objekte aus, für Erinnerungen als für Dinge.', it: 'Per te, il valore del denaro è in ciò che permette di vivere, non in ciò che permette di avere. Preferisce spendere in momenti piuttosto che in oggetti, in ricordi piuttosto che in cose.', pt: 'Para você, o valor do dinheiro está no que permite viver, não no que permite ter. Prefere gastar em momentos do que em objetos, em memórias do que em coisas.' } },
      { name: { es: 'El Altruista Activo', en: 'The Active Altruist', fr: 'L\'Altruiste Actif', de: 'Der Aktive Altruist', it: 'L\'Altruista Attivo', pt: 'O Altruísta Ativo' }, dimensions: ['A'], photo: '/characters/active-altruist.jpg', description: { es: 'El dinero tiene más valor cuando cambia vidas que cuando llena armarios.', en: 'Money has more value when it changes lives than when it fills closets.', fr: 'L\'argent a plus de valeur quand il change des vies que quand il remplit des armoires.', de: 'Geld hat mehr Wert, wenn es Leben verändert, als wenn es Schränke füllt.', it: 'Il denaro ha più valore quando cambia vite che quando riempie armadi.', pt: 'O dinheiro tem mais valor quando muda vidas do que quando enche armários.' }, philosophy: { es: 'Para ti, la riqueza que no circula es riqueza desperdiciada. No porque sea una obligación moral — sino porque ves con claridad que el impacto que genera es mayor que el placer personal que podrías obtener.', en: 'For you, wealth that doesn\'t circulate is wasted wealth. Not because it\'s a moral obligation — but because you see clearly that the impact it generates is greater than the personal pleasure you could obtain.', fr: 'Pour vous, la richesse qui ne circule pas est une richesse gâchée. Non pas parce que c\'est une obligation morale — mais parce que vous voyez clairement que l\'impact qu\'elle génère est supérieur au plaisir personnel que vous pourriez en obtenir.', de: 'Für dich ist Reichtum, der nicht zirkuliert, verschwendeter Reichtum. Nicht weil es eine moralische Verpflichtung ist — sondern weil du klar siehst, dass der Einfluss, den er erzeugt, größer ist als das persönliche Vergnügen, das du daraus erhalten könntest.', it: 'Per te, la ricchezza che non circola è ricchezza sprecata. Non perché sia un obbligo morale — ma perché vedi chiaramente che l\'impatto che genera è maggiore del piacere personale che potresti ottenere.', pt: 'Para você, a riqueza que não circula é riqueza desperdiçada. Não porque seja uma obrigação moral — mas porque você vê claramente que o impacto que gera é maior do que o prazer pessoal que poderia obter.' } },
      { name: { es: 'El Suficiente', en: 'The Sufficient', fr: 'Le Suffisant', de: 'Der Genügsame', it: 'Il Sufficiente', pt: 'O Suficiente' }, dimensions: ['S'], photo: '/characters/sufficient.jpg', description: { es: 'Tiene lo que necesita y no necesita más. Eso es libertad.', en: 'Has what they need and doesn\'t need more. That\'s freedom.', fr: 'Il a ce dont il a besoin et n\'en a pas besoin de plus. C\'est la liberté.', de: 'Hat, was er braucht, und braucht nicht mehr. Das ist Freiheit.', it: 'Ha ciò di cui ha bisogno e non ha bisogno di altro. Questa è libertà.', pt: 'Tem o que precisa e não precisa de mais. Isso é liberdade.' }, philosophy: { es: 'Has descubierto algo que pocos logran: cuánto es suficiente para ti. Esa claridad te libera de la carrera interminable de acumular. El verdadero lujo es no necesitar lujos.', en: 'You\'ve discovered something few achieve: how much is enough for you. That clarity frees you from the endless race to accumulate. The real luxury is not needing luxuries.', fr: 'Vous avez découvert quelque chose que peu de gens atteignent : combien est suffisant pour vous. Cette clarté vous libère de la course sans fin à l\'accumulation. Le vrai luxe, c\'est de ne pas avoir besoin de luxes.', de: 'Du hast etwas entdeckt, das nur wenige erreichen: wie viel genug für dich ist. Diese Klarheit befreit dich von dem endlosen Rennen des Anhäufens. Der wahre Luxus ist es, keine Luxusgüter zu brauchen.', it: 'Hai scoperto qualcosa che pochi raggiungono: quanto è sufficiente per te. Quella chiarezza ti libera dalla corsa senza fine all\'accumulazione. Il vero lusso è non aver bisogno di lussi.', pt: 'Você descobriu algo que poucos alcançam: quanto é suficiente para você. Essa clareza te liberta da corrida interminável de acumular. O verdadeiro luxo é não precisar de luxos.' } },
      { name: { es: 'El Consumidor Consciente', en: 'The Conscious Consumer', fr: 'Le Consommateur Conscient', de: 'Der Bewusste Konsument', it: 'Il Consumatore Consapevole', pt: 'O Consumidor Consciente' }, dimensions: ['M', 'E'], photo: '/characters/conscious-consumer.jpg', description: { es: 'Le importan las cosas y las experiencias, pero con criterio.', en: 'Cares about things and experiences, but with discernment.', fr: 'Les choses et les expériences lui importent, mais avec discernement.', de: 'Dinge und Erlebnisse sind ihm wichtig, aber mit Bedacht.', it: 'Gli importano le cose e le esperienze, ma con criterio.', pt: 'Se importa com coisas e experiências, mas com critério.' }, philosophy: { es: 'No renuncias al placer de las cosas buenas ni al de las experiencias. Pero eres selectivo/a. No compras por impulso ni por estatus — compras lo que genuinamente agrega valor a tu vida.', en: 'You don\'t give up the pleasure of good things or experiences. But you\'re selective. You don\'t buy on impulse or for status — you buy what genuinely adds value to your life.', fr: 'Vous ne renoncez pas au plaisir des bonnes choses ni à celui des expériences. Mais vous êtes sélectif(ve). Vous n\'achetez pas par impulsion ni pour le statut — vous achetez ce qui ajoute genuinement de la valeur à votre vie.', de: 'Du verzichtest nicht auf das Vergnügen der guten Dinge noch auf das der Erlebnisse. Aber du bist wählerisch. Du kaufst nicht impulsiv oder aus Statusgründen — du kaufst, was deinem Leben wirklich Wert hinzufügt.', it: 'Non rinunci al piacere delle cose buone né a quello delle esperienze. Ma sei selettivo/a. Non compri per impulso né per status — compri ciò che aggiunge genuinamente valore alla tua vita.', pt: 'Você não renuncia ao prazer das boas coisas nem ao das experiências. Mas é seletivo/a. Não compra por impulso nem por status — compra o que genuinamente agrega valor à sua vida.' } },
      { name: { es: 'El Generoso Moderado', en: 'The Moderate Generous', fr: 'Le Généreux Modéré', de: 'Der Mäßig Großzügige', it: 'Il Generoso Moderato', pt: 'O Generoso Moderado' }, dimensions: ['A', 'S'], photo: '/characters/generous-moderate.jpg', description: { es: 'Suficiente para él/ella, generoso/a con el resto.', en: 'Enough for themselves, generous with the rest.', fr: 'Suffisant pour lui/elle, généreux(se) avec le reste.', de: 'Genug für sich selbst, großzügig mit dem Rest.', it: 'Sufficiente per sé, generoso/a con il resto.', pt: 'Suficiente para si, generoso/a com o resto.' }, philosophy: { es: 'Tienes claro cuánto necesitas y lo que sobra va a donde puede hacer más. No es sacrificio — es una forma de maximizar el impacto de lo que tienes. Vivir con suficiencia y dar con abundancia.', en: 'You\'re clear on how much you need and what\'s left goes where it can do more. It\'s not sacrifice — it\'s a way to maximize the impact of what you have. Living with sufficiency and giving with abundance.', fr: 'Vous savez clairement de combien vous avez besoin et ce qui reste va là où il peut faire plus. Ce n\'est pas un sacrifice — c\'est une façon de maximiser l\'impact de ce que vous avez. Vivre avec suffisance et donner avec abondance.', de: 'Du weißt klar, wie viel du brauchst, und das Übrige geht dorthin, wo es mehr bewirken kann. Es ist kein Opfer — es ist eine Möglichkeit, die Wirkung dessen zu maximieren, was du hast. Mit Genügsamkeit leben und mit Überfluss geben.', it: 'Hai chiaro di quanto hai bisogno e ciò che avanza va dove può fare di più. Non è sacrificio — è un modo per massimizzare l\'impatto di ciò che hai. Vivere con sufficienza e dare con abbondanza.', pt: 'Você tem claro quanto precisa e o que sobra vai onde pode fazer mais. Não é sacrifício — é uma forma de maximizar o impacto do que você tem. Viver com suficiência e dar com abundância.' } },
      { name: { es: 'El Libre de las Cosas', en: 'The Free from Things', fr: 'Le Libre des Choses', de: 'Der Freie von den Dingen', it: 'Il Libero dalle Cose', pt: 'O Livre das Coisas' }, dimensions: ['E', 'S'], photo: '/characters/free-from-things.jpg', description: { es: 'Las experiencias le dan más que las posesiones. Las posesiones le pesan.', en: 'Experiences give them more than possessions. Possessions weigh them down.', fr: 'Les expériences lui apportent plus que les possessions. Les possessions lui pèsent.', de: 'Erlebnisse geben ihm mehr als Besitz. Besitz belastet ihn.', it: 'Le esperienze gli danno di più che le posizioni. Le posizioni gli pesano.', pt: 'As experiências lhe dão mais do que as posses. As posses pesam.' }, philosophy: { es: 'Para ti, poseer cosas es un costo más que un beneficio. Las experiencias no acumulan polvo ni requieren seguro. Tu riqueza se mide en historias, no en cajones.', en: 'For you, owning things is a cost more than a benefit. Experiences don\'t gather dust or require insurance. Your wealth is measured in stories, not in drawers.', fr: 'Pour vous, posséder des choses est un coût plus qu\'un bénéfice. Les expériences n\'accumulent pas la poussière et ne nécessitent pas d\'assurance. Votre richesse se mesure en histoires, pas en tiroirs.', de: 'Für dich ist Besitzen von Dingen eher ein Kosten als ein Nutzen. Erlebnisse sammeln keinen Staub an und brauchen keine Versicherung. Dein Reichtum wird in Geschichten gemessen, nicht in Schubladen.', it: 'Per te, possedere cose è un costo più che un beneficio. Le esperienze non accumulano polvere né richiedono assicurazione. La tua ricchezza si misura in storie, non in cassetti.', pt: 'Para você, possuir coisas é um custo mais do que um benefício. As experiências não acumulam poeira nem requerem seguro. Sua riqueza se mede em histórias, não em gavetas.' } },
      { name: { es: 'El Filantrópico Experiencial', en: 'The Philanthropic Experiential', fr: 'Le Philanthrope Expérientiel', de: 'Der Philanthropische Erlebnisorientierte', it: 'Il Filantropo Esperienziale', pt: 'O Filantrópico Experiencial' }, dimensions: ['E', 'A'], photo: '/characters/philanthropic-experiential.jpg', description: { es: 'Vive bien y ayuda a que otros vivan bien también.', en: 'Lives well and helps others live well too.', fr: 'Vit bien et aide les autres à bien vivre aussi.', de: 'Lebt gut und hilft anderen, auch gut zu leben.', it: 'Vive bene e aiuta gli altri a vivere bene anche.', pt: 'Vive bem e ajuda os outros a viverem bem também.' }, philosophy: { es: 'Para ti, la riqueza ideal se distribuye de dos formas: en experiencias propias ricas y en hacer posible que otros tengan las suyas. No es altruismo de sacrificio — es generosidad desde la abundancia.', en: 'For you, ideal wealth is distributed in two ways: in rich personal experiences and in making it possible for others to have theirs. It\'s not sacrifice-based altruism — it\'s generosity from abundance.', fr: 'Pour vous, la richesse idéale se distribue de deux façons : en expériences personnelles riches et en rendant possible que d\'autres aient les leurs. Ce n\'est pas un altruisme de sacrifice — c\'est de la générosité depuis l\'abondance.', de: 'Für dich wird idealer Reichtum auf zwei Arten verteilt: in reichen persönlichen Erlebnissen und darin, anderen zu ermöglichen, ihre eigenen zu haben. Es ist kein opferbasierter Altruismus — es ist Großzügigkeit aus der Fülle.', it: 'Per te, la ricchezza ideale si distribuisce in due modi: in esperienze personali ricche e nel rendere possibile che gli altri abbiano le proprie. Non è altruismo di sacrificio — è generosità dall\'abbondanza.', pt: 'Para você, a riqueza ideal se distribui de duas formas: em experiências próprias ricas e em tornar possível que os outros tenham as suas. Não é altruísmo de sacrifício — é generosidade desde a abundância.' } },
    ],
  };

  await prisma.quiz.upsert({
    where: { slug: 'materialist' },
    update: {
      title: data.title,
      description: data.description,
      scenarioLabel: data.scenarioLabel,
      dimensionLabels: data.dimensionLabels,
      questions: data.questions,
      characters: data.characters,
    },
    create: data,
  });
}
