import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tipo de ex eres?', en: 'What kind of ex are you?', fr: 'Quel type d\'ex es-tu ?', de: 'Was für ein Ex bist du?', it: 'Che tipo di ex sei?', pt: 'Que tipo de ex você é?' },
  description: { es: 'La forma en que terminas una relación dice mucho de quién eres. ¿Cuál es tu tipo?', en: 'The way you end a relationship says a lot about who you are. What\'s your type?', fr: 'La façon dont tu termines une relation dit beaucoup sur qui tu es. Quel est ton type ?', de: 'Die Art, wie du eine Beziehung beendest, sagt viel darüber aus, wer du bist. Welcher Typ bist du?', it: 'Il modo in cui finisci una relazione dice molto su chi sei. Qual è il tuo tipo?', pt: 'A forma como você termina um relacionamento diz muito sobre quem você é. Qual é o seu tipo?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { F: 'Fantasma', R: 'Rencoroso', A: 'Amigable', N: 'Neutral' },
    en: { F: 'Ghost', R: 'Resentful', A: 'Friendly', N: 'Neutral' },
    fr: { F: 'Fantôme', R: 'Rancunier', A: 'Amical', N: 'Neutre' },
    de: { F: 'Geist', R: 'Verbittert', A: 'Freundlich', N: 'Neutral' },
    it: { F: 'Fantasma', R: 'Rancoroso', A: 'Amichevole', N: 'Neutrale' },
    pt: { F: 'Fantasma', R: 'Rancoroso', A: 'Amigável', N: 'Neutro' },
  },
  questions: [
    { id: 1, situation: { es: 'La relación terminó hace tres semanas. ¿Qué has hecho con sus pertenencias que quedaron en tu casa?', en: 'The relationship ended three weeks ago. What have you done with their belongings left at your place?', fr: 'La relation s\'est terminée il y a trois semaines. Qu\'as-tu fait avec leurs affaires restées chez toi ?', de: 'Die Beziehung endete vor drei Wochen. Was hast du mit ihren Sachen gemacht, die bei dir blieben?', it: 'La relazione è finita tre settimane fa. Cosa hai fatto con le sue cose rimaste a casa tua?', pt: 'O relacionamento terminou há três semanas. O que você fez com as pertences dele/dela que ficaram na sua casa?' }, options: [
      { text: { es: 'Todavía están ahí. No he podido decidir qué hacer con ellas.', en: 'They\'re still there. I haven\'t been able to decide what to do with them.', fr: 'Elles sont encore là. Je n\'ai pas pu décider quoi faire avec elles.', de: 'Sie sind noch da. Ich konnte nicht entscheiden, was ich damit machen soll.', it: 'Sono ancora lì. Non ho saputo decidere cosa fare con loro.', pt: 'Ainda estão lá. Não consegui decidir o que fazer com elas.' }, dimension: 'F' },
      { text: { es: 'Las empaqué y las tengo listas para devolver... cuando tenga ganas.', en: 'I packed them and have them ready to return... when I feel like it.', fr: 'Je les ai emballées et les ai prêtes à rendre... quand j\'en aurai envie.', de: 'Ich habe sie gepackt und bin bereit zurückzugeben... wenn ich Lust habe.', it: 'Le ho imballate e le ho pronte per restituire... quando ne avrò voglia.', pt: 'Embalei e estou pronto/a para devolver... quando tiver vontade.' }, dimension: 'R' },
      { text: { es: 'Le coordiné para devolverlas de forma organizada.', en: 'I coordinated with them to return everything in an organized way.', fr: 'J\'ai coordonné avec lui/elle pour les rendre de façon organisée.', de: 'Ich habe mit ihm/ihr koordiniert, um alles organisiert zurückzugeben.', it: 'Ho coordinato con lui/lei per restituirle in modo organizzato.', pt: 'Coordenei com ele/ela para devolver de forma organizada.' }, dimension: 'A' },
      { text: { es: 'Las guardé en una caja. Las devolveré cuando lo acordemos.', en: 'I stored them in a box. I\'ll return them when we agree.', fr: 'Je les ai rangées dans une boîte. Je les rendrai quand nous l\'aurons convenu.', de: 'Ich habe sie in einer Kiste verstaut. Ich werde sie zurückgeben, wenn wir es vereinbaren.', it: 'Le ho messe in una scatola. Le restituirò quando lo accordiamo.', pt: 'Guardei em uma caixa. Devolverei quando acordarmos.' }, dimension: 'N' },
    ] },
    { id: 2, situation: { es: '¿Cómo manejas el contacto post-ruptura?', en: 'How do you handle post-breakup contact?', fr: 'Comment gères-tu le contact après la rupture ?', de: 'Wie gehst du mit dem Kontakt nach dem Beziehungsende um?', it: 'Come gestisci il contatto post-rottura?', pt: 'Como você lida com o contato pós-término?' }, options: [
      { text: { es: 'Bloqueé todas sus redes pero no puedo evitar buscarle desde otra cuenta a veces.', en: 'I blocked all their socials but can\'t help checking from another account sometimes.', fr: 'J\'ai bloqué tous ses réseaux mais je ne peux pas m\'empêcher de chercher depuis un autre compte parfois.', de: 'Ich habe alle seine/ihre Netzwerke blockiert, kann aber manchmal nicht anders, als von einem anderen Konto zu suchen.', it: 'Ho bloccato tutti i suoi social ma non riesco a evitare di cercarlo da un altro account a volte.', pt: 'Bloqueei todas as redes dele/dela mas não consigo evitar de buscar por outra conta às vezes.' }, dimension: 'F' },
      { text: { es: 'Si me escribe le respondo pero yo no inicio conversación. Y mis respuestas son frías.', en: 'If they write I respond but I don\'t initiate. And my responses are cold.', fr: 'Si il/elle m\'écrit je réponds mais je n\'initie pas. Et mes réponses sont froides.', de: 'Wenn er/sie schreibt, antworte ich, aber ich initiiere nicht. Und meine Antworten sind kalt.', it: 'Se mi scrive rispondo ma non inizio io. E le mie risposte sono fredde.', pt: 'Se escrever respondo mas não inicio. E minhas respostas são frias.' }, dimension: 'R' },
      { text: { es: 'Tenemos un contacto sano y eventual. Sin dramas.', en: 'We have healthy, occasional contact. No drama.', fr: 'Nous avons un contact sain et ponctuel. Sans drames.', de: 'Wir haben gesunden, gelegentlichen Kontakt. Kein Drama.', it: 'Abbiamo un contatto sano e occasionale. Senza drammi.', pt: 'Temos um contato sano e eventual. Sem dramas.' }, dimension: 'A' },
      { text: { es: 'No hablo de esto, pero si hay algo necesario lo hago sin drama.', en: 'I don\'t talk about it, but if there\'s something needed I do it without drama.', fr: 'Je n\'en parle pas, mais si quelque chose est nécessaire je le fais sans drame.', de: 'Ich rede nicht darüber, aber wenn etwas nötig ist, tue ich es ohne Drama.', it: 'Non ne parlo, ma se c\'è qualcosa di necessario lo faccio senza drama.', pt: 'Não falo sobre isso, mas se há algo necessário faço sem drama.' }, dimension: 'N' },
    ] },
    { id: 3, situation: { es: 'Un amigo común menciona que tu ex está bien y avanzando. ¿Cómo reaccionas?', en: 'A mutual friend mentions your ex is doing well and moving on. How do you react?', fr: 'Un ami commun mentionne que ton/ta ex va bien et avance. Comment réagis-tu ?', de: 'Ein gemeinsamer Freund erwähnt, dass dein Ex gut drauf ist und vorankommt. Wie reagierst du?', it: 'Un amico comune menziona che il tuo ex sta bene e va avanti. Come reagisci?', pt: 'Um amigo em comum menciona que seu ex está bem e avançando. Como você reage?' }, options: [
      { text: { es: 'Me duele más de lo que quisiera admitir. Quería ser yo el/la primero/a en avanzar.', en: 'It hurts more than I\'d like to admit. I wanted to be the first to move on.', fr: 'Ça me fait plus mal que je ne voudrai l\'admettre. Je voulais être le/la premier(ère) à avancer.', de: 'Es schmerzt mehr als ich zugeben möchte. Ich wollte der/die Erste sein, der/die vorankommt.', it: 'Mi fa più male di quanto vorrei ammettere. Volevo essere io il/la primo/a ad andare avanti.', pt: 'Me dói mais do que gostaria de admitir. Queria ser o/a primeiro/a a avançar.' }, dimension: 'F' },
      { text: { es: 'Me cuesta que le vaya bien tan rápido. ¿Ya no sufre?', en: 'It bothers me that they\'re doing so well so fast. Aren\'t they suffering anymore?', fr: 'Ça me coûte qu\'il/elle aille si bien si vite. Il/elle ne souffre plus ?', de: 'Es fällt mir schwer, dass es ihm/ihr so schnell gut geht. Leidet er/sie nicht mehr?', it: 'Mi costa che gli vada bene così in fretta. Non soffre più?', pt: 'Me custa que esteja tão bem tão rápido. Já não sofre?' }, dimension: 'R' },
      { text: { es: 'Me alegra escucharlo. Terminar bien incluye querer que el otro esté bien.', en: 'I\'m glad to hear it. Ending well includes wanting the other to be well.', fr: 'Ça me fait plaisir d\'entendre ça. Bien terminer inclut vouloir que l\'autre aille bien.', de: 'Ich höre es gerne. Gut zu enden beinhaltet, dass man dem anderen Gutes wünscht.', it: 'Sono felice di sentirlo. Finire bene include voler che l\'altro stia bene.', pt: 'Fico feliz em ouvir. Terminar bem inclui querer que o outro esteja bem.' }, dimension: 'A' },
      { text: { es: 'Bien. Cada quien con su proceso.', en: 'Good. Everyone with their own process.', fr: 'Bien. Chacun avec son processus.', de: 'Gut. Jeder mit seinem eigenen Prozess.', it: 'Bene. Ognuno con il suo processo.', pt: 'Bem. Cada um com seu processo.' }, dimension: 'N' },
    ] },
    { id: 4, situation: { es: 'Tu ex te escribe para pedirte algo práctico (un dato, un documento).', en: 'Your ex writes asking for something practical (a piece of info, a document).', fr: 'Ton/ta ex t\'écrit pour te demander quelque chose de pratique (une info, un document).', de: 'Dein Ex schreibt, um etwas Praktisches zu fragen (eine Info, ein Dokument).', it: 'Il tuo ex ti scrive per chiederti qualcosa di pratico (un\'informazione, un documento).', pt: 'Seu ex escreve pedindo algo prático (uma informação, um documento).' }, options: [
      { text: { es: 'Me congela. No sé cómo responder ni qué tono usar.', en: 'I freeze. I don\'t know how to respond or what tone to use.', fr: 'Ça me fige. Je ne sais pas comment répondre ni quel ton utiliser.', de: 'Ich erfriere. Ich weiß nicht, wie ich antworten oder welchen Ton ich verwenden soll.', it: 'Mi congela. Non so come rispondere né che tono usare.', pt: 'Fico congelado/a. Não sei como responder nem que tom usar.' }, dimension: 'F' },
      { text: { es: 'Respondo lo mínimo y tardo más de lo necesario.', en: 'I respond minimally and take longer than necessary.', fr: 'Je réponds le minimum et prends plus de temps que nécessaire.', de: 'Ich antworte minimal und brauche länger als nötig.', it: 'Rispondo il minimo e ci metto più del necessario.', pt: 'Respondo o mínimo e demoro mais do que necessário.' }, dimension: 'R' },
      { text: { es: 'Respondo con normalidad. No tengo por qué complicar algo simple.', en: 'I respond normally. No reason to complicate something simple.', fr: 'Je réponds normalement. Pas de raison de compliquer quelque chose de simple.', de: 'Ich antworte normal. Es gibt keinen Grund, etwas Einfaches zu verkomplizieren.', it: 'Rispondo normalmente. Non ho motivo di complicare qualcosa di semplice.', pt: 'Respondo normalmente. Não há por que complicar algo simples.' }, dimension: 'A' },
      { text: { es: 'Respondo de forma clara y eficiente. Sin drama.', en: 'I respond clearly and efficiently. No drama.', fr: 'Je réponds de façon claire et efficace. Sans drame.', de: 'Ich antworte klar und effizient. Kein Drama.', it: 'Rispondo in modo chiaro ed efficiente. Senza drama.', pt: 'Respondo de forma clara e eficiente. Sem drama.' }, dimension: 'N' },
    ] },
    { id: 5, situation: { es: '¿Cómo hablas de tu ex con amigos?', en: 'How do you talk about your ex with friends?', fr: 'Comment parles-tu de ton/ta ex avec tes amis ?', de: 'Wie redest du mit Freunden über deinen Ex?', it: 'Come parli del tuo ex con gli amici?', pt: 'Como você fala do seu ex com amigos?' }, options: [
      { text: { es: 'A veces lo idealizo, a veces hablo mal. Depende del día y del estado de ánimo.', en: 'Sometimes I idealize them, sometimes I speak badly. Depends on the day and mood.', fr: 'Parfois je l\'idéalise, parfois je parle mal. Ça dépend du jour et de l\'humeur.', de: 'Manchmal idealisiere ich ihn/sie, manchmal spreche ich schlecht. Kommt auf den Tag und die Stimmung an.', it: 'A volte lo idealizzo, a volte parlo male. Dipende dal giorno e dall\'umore.', pt: 'Às vezes o idealizo, às vezes falo mal. Depende do dia e do humor.' }, dimension: 'F' },
      { text: { es: 'Con bastante rencor. Me costó y no lo voy a ocultar.', en: 'With quite a bit of resentment. It cost me and I\'m not going to hide it.', fr: 'Avec beaucoup de rancœur. Ça m\'a coûté et je ne vais pas le cacher.', de: 'Mit ziemlichem Groll. Es hat mich was gekostet und ich werde es nicht verbergen.', it: 'Con abbastanza rancore. Mi è costato e non lo nasconderò.', pt: 'Com bastante rancor. Me custou e não vou ocultar.' }, dimension: 'R' },
      { text: { es: 'Con respeto. Lo que vivimos fue real y no necesito destruir su imagen.', en: 'With respect. What we lived was real and I don\'t need to destroy their image.', fr: 'Avec respect. Ce que nous avons vécu était réel et je n\'ai pas besoin de détruire son image.', de: 'Mit Respekt. Was wir erlebt haben, war real und ich muss sein/ihr Image nicht zerstören.', it: 'Con rispetto. Quello che abbiamo vissuto era reale e non ho bisogno di distruggere la sua immagine.', pt: 'Com respeito. O que vivemos foi real e não preciso destruir a imagem dele/dela.' }, dimension: 'A' },
      { text: { es: 'Poco. No siento necesidad de hablar de ello.', en: 'Little. I don\'t feel the need to talk about it.', fr: 'Peu. Je ne ressens pas le besoin d\'en parler.', de: 'Wenig. Ich fühle kein Bedürfnis, darüber zu reden.', it: 'Poco. Non sento la necessità di parlarne.', pt: 'Pouco. Não sinto necessidade de falar sobre isso.' }, dimension: 'N' },
    ] },
    { id: 6, situation: { es: 'Tu ex empieza una nueva relación. ¿Cómo te llega la noticia?', en: 'Your ex starts a new relationship. How does the news reach you?', fr: 'Ton/ta ex commence une nouvelle relation. Comment la nouvelle t\'arrive-t-elle ?', de: 'Dein Ex beginnt eine neue Beziehung. Wie erreicht dich die Neuigkeit?', it: 'Il tuo ex inizia una nuova relazione. Come ti arriva la notizia?', pt: 'Seu ex começa um novo relacionamento. Como a notícia chega até você?' }, options: [
      { text: { es: 'La busqué antes de que llegara sola. Ya sabía que pasaría y no podía evitar estar atento/a.', en: 'I looked for it before it came alone. I knew it would happen and couldn\'t help being watchful.', fr: 'Je l\'ai cherchée avant qu\'elle arrive seule. Je savais que ça arriverait et je ne pouvais pas m\'empêcher d\'être attentif/ve.', de: 'Ich habe sie gesucht, bevor sie von alleine kam. Ich wusste, dass es passieren würde und konnte nicht anders, als aufmerksam zu sein.', it: 'L\'ho cercata prima che arrivasse da sola. Sapevo che sarebbe successo e non riuscivo a non stare attento/a.', pt: 'Busquei antes de chegar sozinha. Já sabia que aconteceria e não conseguia evitar estar atento/a.' }, dimension: 'F' },
      { text: { es: 'Me afecta más de lo que quiero. Busco defectos de la nueva persona.', en: 'It affects me more than I want. I look for flaws in the new person.', fr: 'Ça m\'affecte plus que je ne veux. Je cherche des défauts de la nouvelle personne.', de: 'Es betrifft mich mehr als ich will. Ich suche nach Mängeln der neuen Person.', it: 'Mi colpisce più di quanto voglia. Cerco difetti della nuova persona.', pt: 'Me afeta mais do que quero. Busco defeitos da nova pessoa.' }, dimension: 'R' },
      { text: { es: 'Me alegra si parece feliz. Las relaciones terminan pero la vida continúa.', en: 'I\'m glad if they seem happy. Relationships end but life continues.', fr: 'Ça me fait plaisir s\'il/elle semble heureux/se. Les relations se terminent mais la vie continue.', de: 'Ich freue mich, wenn er/sie glücklich erscheint. Beziehungen enden, aber das Leben geht weiter.', it: 'Mi fa piacere se sembra felice. Le relazioni finiscono ma la vita continua.', pt: 'Fico feliz se parece feliz. Relacionamentos terminam mas a vida continua.' }, dimension: 'A' },
      { text: { es: 'Bien. Es su vida y no me corresponde opinar.', en: 'Good. It\'s their life and it\'s not my place to comment.', fr: 'Bien. C\'est sa vie et ce n\'est pas mon rôle d\'opiner.', de: 'Gut. Es ist sein/ihr Leben und es liegt mir nicht, darüber zu kommentieren.', it: 'Bene. È la sua vita e non mi compete commentare.', pt: 'Bem. É a vida dele/dela e não me cabe opinar.' }, dimension: 'N' },
    ] },
    { id: 7, situation: { es: 'Si tienes que coincidir con tu ex en un evento social, ¿cómo lo preparas?', en: 'If you have to cross paths with your ex at a social event, how do you prepare?', fr: 'Si tu dois croiser ton/ta ex à un événement social, comment tu te prépares ?', de: 'Wenn du deinen Ex bei einer sozialen Veranstaltung treffen musst, wie bereitest du dich vor?', it: 'Se devi incontrare il tuo ex a un evento sociale, come ti prepari?', pt: 'Se você tem que encontrar seu ex em um evento social, como se prepara?' }, options: [
      { text: { es: 'Me preparo físicamente (ropa, aspecto) para que me vea bien. Quiero causar impacto.', en: 'I prepare physically (outfit, looks) so they see me looking good. I want to make an impact.', fr: 'Je me prépare physiquement (tenue, apparence) pour qu\'il/elle me voit bien. Je veux faire de l\'effet.', de: 'Ich bereite mich physisch vor (Kleidung, Aussehen), damit er/sie mich gut sieht. Ich will Eindruck machen.', it: 'Mi preparo fisicamente (vestiti, aspetto) per farmi vedere bene. Voglio fare colpo.', pt: 'Me preparo fisicamente (roupa, aparência) para que me veja bem. Quero causar impacto.' }, dimension: 'F' },
      { text: { es: 'Evalúo si vale la pena ir o si puedo evitar el encuentro.', en: 'I evaluate if it\'s worth going or if I can avoid the encounter.', fr: 'J\'évalue si ça vaut la peine d\'y aller ou si je peux éviter la rencontre.', de: 'Ich überlege, ob es sich lohnt zu gehen oder ob ich dem Treffen aus dem Weg gehen kann.', it: 'Valuto se vale la pena andare o se posso evitare l\'incontro.', pt: 'Avalio se vale a pena ir ou se posso evitar o encontro.' }, dimension: 'R' },
      { text: { es: 'Sin preparación especial. Lo saludo como saludaría a cualquier persona.', en: 'No special preparation. I greet them like I\'d greet anyone.', fr: 'Sans préparation spéciale. Je le/la salue comme je saluerais n\'importe quelle personne.', de: 'Keine besondere Vorbereitung. Ich begrüße ihn/sie, wie ich jeden begrüßen würde.', it: 'Senza preparazione speciale. Lo saluto come saluterei qualsiasi persona.', pt: 'Sem preparação especial. Cumprimento como cumprimentaria qualquer pessoa.' }, dimension: 'A' },
      { text: { es: 'Voy sin drama. Coincidiremos, saludaremos y cada uno seguirá con su noche.', en: 'I go without drama. We\'ll coincide, greet each other, and each will continue with their night.', fr: 'J\'y vais sans drame. Nous coïnciderons, nous saluerons et chacun continuera avec sa nuit.', de: 'Ich gehe ohne Drama. Wir werden aufeinandertreffen, uns begrüßen und jeder macht mit seiner Nacht weiter.', it: 'Vado senza drama. Coincideremo, ci saluteremo e ognuno continuerà con la sua serata.', pt: 'Vou sem drama. Vamos coincidir, cumprimentar e cada um seguirá com sua noite.' }, dimension: 'N' },
    ] },
    { id: 8, situation: { es: '¿Guardas sus fotos o mensajes?', en: 'Do you keep their photos or messages?', fr: 'Gardes-tu ses photos ou messages ?', de: 'Bewahrst du seine/ihre Fotos oder Nachrichten auf?', it: 'Tieni le sue foto o messaggi?', pt: 'Você guarda as fotos ou mensagens dele/dela?' }, options: [
      { text: { es: 'Sí, aunque sé que no es buena idea revisarlos.', en: 'Yes, even though I know it\'s not a good idea to look at them.', fr: 'Oui, même si je sais que ce n\'est pas une bonne idée de les regarder.', de: 'Ja, obwohl ich weiß, dass es keine gute Idee ist, sie anzuschauen.', it: 'Sì, anche se so che non è una buona idea rivederli.', pt: 'Sim, embora saiba que não é boa ideia revisá-los.' }, dimension: 'F' },
      { text: { es: 'Los borré con rabia. No quiero ningún rastro.', en: 'I deleted them in anger. I don\'t want any trace.', fr: 'Je les ai effacés avec rage. Je ne veux aucune trace.', de: 'Ich habe sie wütend gelöscht. Ich will keine Spur.', it: 'Li ho cancellati con rabbia. Non voglio alcuna traccia.', pt: 'Os deletei com raiva. Não quero nenhum rastro.' }, dimension: 'R' },
      { text: { es: 'Los guardo como recuerdos de una etapa de mi vida. Sin drama.', en: 'I keep them as memories of a stage of my life. No drama.', fr: 'Je les garde comme souvenirs d\'une étape de ma vie. Sans drame.', de: 'Ich bewahre sie als Erinnerungen an eine Phase meines Lebens. Kein Drama.', it: 'Li conservo come ricordi di una fase della mia vita. Senza drama.', pt: 'Guardo como recordações de uma fase da minha vida. Sem drama.' }, dimension: 'A' },
      { text: { es: 'Están en algún lugar pero no los busco ni los borro activamente.', en: 'They\'re somewhere but I don\'t actively look for or delete them.', fr: 'Ils sont quelque part mais je ne les cherche pas ni les efface activement.', de: 'Sie sind irgendwo, aber ich suche sie nicht aktiv und lösche sie auch nicht.', it: 'Sono da qualche parte ma non le cerco né le cancello attivamente.', pt: 'Estão em algum lugar mas não as busco nem as apago ativamente.' }, dimension: 'N' },
    ] },
    { id: 9, situation: { es: 'Tu ex te pide que hablemos de la ruptura para tener cierre.', en: 'Your ex asks you to talk about the breakup to get closure.', fr: 'Ton/ta ex te demande de parler de la rupture pour avoir une clôture.', de: 'Dein Ex bittet dich, über die Trennung zu reden, um Abschluss zu bekommen.', it: 'Il tuo ex ti chiede di parlare della rottura per avere un chiarimento.', pt: 'Seu ex pede para conversar sobre o término para ter fechamento.' }, options: [
      { text: { es: 'Acepto inmediatamente. Lo necesitaba también aunque no lo había pedido.', en: 'I accept immediately. I needed it too even though I hadn\'t asked.', fr: 'J\'accepte immédiatement. J\'en avais besoin aussi même si je ne l\'avais pas demandé.', de: 'Ich stimme sofort zu. Ich brauchte es auch, obwohl ich nicht darum gebeten hatte.', it: 'Accetto immediatamente. Ne avevo bisogno anch\'io anche se non lo avevo chiesto.', pt: 'Aceito imediatamente. Também precisava embora não tivesse pedido.' }, dimension: 'F' },
      { text: { es: 'Dependiendo de mi estado, podría acabar peor que antes.', en: 'Depending on my state, it could end up worse than before.', fr: 'Selon mon état, ça pourrait finir pire qu\'avant.', de: 'Je nach meinem Zustand könnte es schlimmer enden als zuvor.', it: 'A seconda del mio stato, potrebbe finire peggio di prima.', pt: 'Dependendo do meu estado, pode acabar pior do que antes.' }, dimension: 'R' },
      { text: { es: 'Acepto si creo que puede ser útil para los dos.', en: 'I accept if I think it can be useful for both of us.', fr: 'J\'accepte si je pense que ça peut être utile pour nous deux.', de: 'Ich stimme zu, wenn ich denke, dass es für uns beide nützlich sein kann.', it: 'Accetto se penso che possa essere utile per entrambi.', pt: 'Aceito se acho que pode ser útil para os dois.' }, dimension: 'A' },
      { text: { es: 'Lo evalúo. Si ya tengo cierre, quizás no tiene mucho sentido.', en: 'I evaluate it. If I already have closure, it might not make much sense.', fr: 'Je l\'évalue. Si j\'ai déjà une clôture, peut-être que ça n\'a pas beaucoup de sens.', de: 'Ich bewerte es. Wenn ich bereits Abschluss habe, ergibt es vielleicht nicht viel Sinn.', it: 'Lo valuto. Se ho già un chiarimento, forse non ha molto senso.', pt: 'Avalio. Se já tenho fechamento, talvez não faça muito sentido.' }, dimension: 'N' },
    ] },
    { id: 10, situation: { es: 'Años después, ¿cómo describes esa relación?', en: 'Years later, how do you describe that relationship?', fr: 'Des années après, comment décris-tu cette relation ?', de: 'Jahre später, wie beschreibst du diese Beziehung?', it: 'Anni dopo, come descrivi quella relazione?', pt: 'Anos depois, como você descreve aquele relacionamento?' }, options: [
      { text: { es: 'Con una mezcla de nostalgia y confusión. No he terminado de procesarla del todo.', en: 'With a mix of nostalgia and confusion. I haven\'t fully processed it yet.', fr: 'Avec un mélange de nostalgie et de confusion. Je ne l\'ai pas entièrement traitée.', de: 'Mit einer Mischung aus Nostalgie und Verwirrung. Ich habe es noch nicht vollständig verarbeitet.', it: 'Con un mix di nostalgia e confusione. Non l\'ho ancora elaborata del tutto.', pt: 'Com uma mistura de nostalgia e confusão. Não terminei de processá-la completamente.' }, dimension: 'F' },
      { text: { es: 'Con distancia pero todavía algo de amargura en ciertos temas.', en: 'With distance but still some bitterness on certain topics.', fr: 'Avec distance mais encore un peu d\'amertume sur certains sujets.', de: 'Mit Distanz aber noch etwas Bitterkeit bei bestimmten Themen.', it: 'Con distanza ma ancora un po\' di amarezza su certi argomenti.', pt: 'Com distância mas ainda alguma amargura em certos temas.' }, dimension: 'R' },
      { text: { es: 'Como una etapa que fue real, tuvo valor, y terminó cuando tenía que terminar.', en: 'As a stage that was real, had value, and ended when it needed to end.', fr: 'Comme une étape qui était réelle, avait de la valeur, et s\'est terminée quand elle devait se terminer.', de: 'Als eine Phase, die real war, Wert hatte und endete, als sie enden musste.', it: 'Come una fase che era reale, aveva valore, ed è finita quando doveva finire.', pt: 'Como uma fase que foi real, teve valor, e terminou quando tinha que terminar.' }, dimension: 'A' },
      { text: { es: 'Como algo que fue y ya no es. Sin más color que eso.', en: 'As something that was and no longer is. Nothing more than that.', fr: 'Comme quelque chose qui était et n\'est plus. Rien de plus que ça.', de: 'Als etwas, das war und nicht mehr ist. Nicht mehr als das.', it: 'Come qualcosa che era e non è più. Niente di più di questo.', pt: 'Como algo que foi e não é mais. Sem mais cor que isso.' }, dimension: 'N' },
    ] },
  ],
  characters: [
    { name: { es: 'El Ex Fantasma', en: 'The Ghost Ex', fr: 'L\'Ex Fantôme', de: 'Der Geist-Ex', it: 'L\'Ex Fantasma', pt: 'O Ex Fantasma' }, dimensions: ['F'], photo: '/characters/ghost-ex.jpg', description: { es: 'Desapareció pero sigue mirando historias y no terminó de soltar.', en: 'Disappeared but still watching stories and hasn\'t fully let go.', fr: 'A disparu mais regarde toujours les histoires et n\'a pas tout à fait lâché.', de: 'Verschwunden, aber immer noch Storys schauend und noch nicht ganz losgelassen.', it: 'È sparito ma guarda ancora le storie e non ha ancora lasciato andare.', pt: 'Desapareceu mas ainda vê stories e não terminou de soltar.' }, philosophy: { es: 'No es que no hayas avanzado — es que el duelo tiene sus propios tiempos. El fantasmeo post-ruptura es una forma de procesar que puede durar más de lo que te gustaría. Mientras tanto, te quedas en una tierra de nadie.', en: 'It\'s not that you haven\'t moved on — it\'s that grief has its own timing. Post-breakup ghosting is a way of processing that can last longer than you\'d like. In the meantime, you stay in no man\'s land.', fr: 'Ce n\'est pas que tu n\'as pas avancé — c\'est que le deuil a ses propres délais. Le "ghostage" post-rupture est une façon de traiter qui peut durer plus longtemps que tu ne le souhaiterais.', de: 'Es ist nicht so, dass du nicht vorangekommen bist — es ist, dass die Trauer ihre eigenen Zeiten hat. Das Post-Breakup-Ghosting ist eine Verarbeitungsweise, die länger dauern kann als gewünscht.', it: 'Non è che non sei andato/a avanti — è che il lutto ha i suoi tempi. Il ghosting post-rottura è un modo di elaborare che può durare più di quanto vorresti.', pt: 'Não é que você não avançou — é que o luto tem seus próprios tempos. O fantasmear pós-término é uma forma de processar que pode durar mais do que você gostaria.' } },
    { name: { es: 'El Ex Rencoroso', en: 'The Resentful Ex', fr: 'L\'Ex Rancunier', de: 'Der Verbitterte Ex', it: 'L\'Ex Rancoroso', pt: 'O Ex Rancoroso' }, dimensions: ['R'], photo: '/characters/rancorous-ex.jpg', description: { es: 'No perdona. Cada decisión post-ruptura tiene una dosis de venganza.', en: 'Doesn\'t forgive. Every post-breakup decision has a dose of revenge.', fr: 'Ne pardonne pas. Chaque décision post-rupture a une dose de vengeance.', de: 'Verzeiht nicht. Jede Entscheidung nach der Trennung hat eine Dosis Rache.', it: 'Non perdona. Ogni decisione post-rottura ha una dose di vendetta.', pt: 'Não perdoa. Cada decisão pós-término tem uma dose de vingança.' }, philosophy: { es: 'El rencor que sientes no es irrazonable si te lastimaron. Pero el rencor que se sostiene demasiado tiempo termina castigando más al que lo carga que al que lo recibe. Eventualmente, soltar es por ti, no por ellos.', en: 'The resentment you feel is not unreasonable if you were hurt. But resentment held too long ends up punishing the one who carries it more than the one who receives it. Eventually, letting go is for you, not them.', fr: 'La rancœur que tu ressens n\'est pas déraisonnable si tu as été blessé(e). Mais la rancœur soutenue trop longtemps finit par punir plus celui qui la porte que celui qui la reçoit.', de: 'Der Groll, den du fühlst, ist nicht unvernünftig, wenn du verletzt wurdest. Aber der Groll, der zu lange aufrechterhalten wird, bestraft denjenigen mehr, der ihn trägt, als denjenigen, der ihn empfängt.', it: 'Il rancore che senti non è irragionevole se sei stato/a ferito/a. Ma il rancore sostenuto troppo a lungo finisce per punire di più chi lo porta che chi lo riceve.', pt: 'O rancor que você sente não é irracional se foi machucado/a. Mas o rancor sustentado por muito tempo acaba punindo mais quem o carrega do que quem o recebe.' } },
    { name: { es: 'El Ex Amigable', en: 'The Friendly Ex', fr: 'L\'Ex Amical', de: 'Der Freundliche Ex', it: 'L\'Ex Amichevole', pt: 'O Ex Amigável' }, dimensions: ['A'], photo: '/characters/friendly-ex.jpg', description: { es: 'Terminó bien. Sin drama, sin rencor. Sí, existe.', en: 'Ended well. No drama, no resentment. Yes, it exists.', fr: 'A bien fini. Sans drame, sans rancœur. Oui, ça existe.', de: 'Hat gut geendet. Kein Drama, kein Groll. Ja, es gibt das.', it: 'È finita bene. Senza dramma, senza rancore. Sì, esiste.', pt: 'Terminou bem. Sem drama, sem rancor. Sim, existe.' }, philosophy: { es: 'Has logrado algo difícil: terminar una relación sin destruirla. Eso no significa que no te dolió — significa que procesaste el dolor de forma que no necesitaste convertir al otro en enemigo. Eso tiene un valor real.', en: 'You\'ve achieved something difficult: ending a relationship without destroying it. It doesn\'t mean it didn\'t hurt — it means you processed the pain in a way that didn\'t require turning the other into an enemy. That has real value.', fr: 'Tu as réussi quelque chose de difficile : terminer une relation sans la détruire. Ça ne signifie pas que ça n\'a pas fait mal — ça signifie que tu as traité la douleur d\'une façon qui n\'a pas nécessité de transformer l\'autre en ennemi.', de: 'Du hast etwas Schwieriges geschafft: eine Beziehung zu beenden, ohne sie zu zerstören. Das bedeutet nicht, dass es nicht wehtat — es bedeutet, dass du den Schmerz so verarbeitet hast, dass du den anderen nicht zum Feind machen musstest.', it: 'Hai raggiunto qualcosa di difficile: terminare una relazione senza distruggerla. Non significa che non ti ha fatto male — significa che hai elaborato il dolore in un modo che non richiedeva di trasformare l\'altro in un nemico.', pt: 'Você conseguiu algo difícil: terminar um relacionamento sem destruí-lo. Não significa que não doeu — significa que você processou a dor de forma que não precisou transformar o outro em inimigo.' } },
    { name: { es: 'El Ex Neutral', en: 'The Neutral Ex', fr: 'L\'Ex Neutre', de: 'Der Neutrale Ex', it: 'L\'Ex Neutrale', pt: 'O Ex Neutro' }, dimensions: ['N'], photo: '/characters/neutral-ex.jpg', description: { es: 'No hay rencor ni contacto. Simplemente ya no.', en: 'No resentment, no contact. Simply no longer.', fr: 'Pas de rancœur ni de contact. Simplement plus.', de: 'Kein Groll, kein Kontakt. Einfach nicht mehr.', it: 'Non c\'è rancore né contatto. Semplicemente non più.', pt: 'Não há rancor nem contato. Simplesmente não mais.' }, philosophy: { es: 'Para ti, las relaciones que terminan simplemente terminan. No hay drama ni nostalgia excesiva. Puede parecer frío desde afuera, pero es una forma sana de cierre: lo que fue, fue. Lo que no es, no es.', en: 'For you, relationships that end simply end. No drama or excessive nostalgia. It can seem cold from the outside, but it\'s a healthy form of closure: what was, was. What isn\'t, isn\'t.', fr: 'Pour toi, les relations qui se terminent se terminent simplement. Pas de drame ni de nostalgie excessive. Ça peut sembler froid vu de l\'extérieur, mais c\'est une forme saine de clôture : ce qui était, était. Ce qui n\'est pas, n\'est pas.', de: 'Für dich enden Beziehungen, die enden, einfach. Kein Drama oder übermäßige Nostalgie. Es kann von außen kalt erscheinen, aber es ist eine gesunde Form des Abschlusses: Was war, war. Was nicht ist, ist nicht.', it: 'Per te, le relazioni che finiscono semplicemente finiscono. Niente dramma né nostalgia eccessiva. Può sembrare freddo dall\'esterno, ma è una forma sana di chiusura: quello che era, era. Quello che non è, non è.', pt: 'Para você, os relacionamentos que terminam simplesmente terminam. Sem drama nem nostalgia excessiva. Pode parecer frio de fora, mas é uma forma saudável de fechamento: o que foi, foi. O que não é, não é.' } },
    { name: { es: 'El Ex en Proceso', en: 'The Ex in Process', fr: 'L\'Ex en Processus', de: 'Der Ex im Prozess', it: 'L\'Ex in Processo', pt: 'O Ex em Processo' }, dimensions: ['F', 'N'], photo: '/characters/processing-ex.jpg', description: { es: 'Quiere ser neutral pero todavía está procesando.', en: 'Wants to be neutral but is still processing.', fr: 'Veut être neutre mais traite encore.', de: 'Möchte neutral sein, verarbeitet aber noch.', it: 'Vuole essere neutrale ma sta ancora elaborando.', pt: 'Quer ser neutro mas ainda está processando.' }, philosophy: { es: 'Aspiras a la neutralidad pero todavía estás en el proceso. Eso es honesto. El duelo no sigue tus planes de tiempo. Serás más neutral cuando hayas terminado de procesar, no antes.', en: 'You aspire to neutrality but you\'re still in process. That\'s honest. Grief doesn\'t follow your time plans. You\'ll be more neutral when you\'ve finished processing, not before.', fr: 'Tu aspires à la neutralité mais tu es encore en processus. C\'est honnête. Le deuil ne suit pas tes plans de temps. Tu seras plus neutre quand tu auras fini de traiter, pas avant.', de: 'Du strebst nach Neutralität, bist aber noch im Prozess. Das ist ehrlich. Die Trauer folgt deinen Zeitplänen nicht. Du wirst neutraler sein, wenn du fertig bist zu verarbeiten, nicht vorher.', it: 'Aspiri alla neutralità ma sei ancora in processo. Questo è onesto. Il lutto non segue i tuoi piani di tempo. Sarai più neutrale quando avrai finito di elaborare, non prima.', pt: 'Você aspira à neutralidade mas ainda está no processo. Isso é honesto. O luto não segue seus planos de tempo. Você será mais neutro quando terminar de processar, não antes.' } },
    { name: { es: 'El Amigable con Límites', en: 'The Friendly with Limits', fr: 'L\'Amical avec Limites', de: 'Der Freundliche mit Grenzen', it: 'L\'Amichevole con Limiti', pt: 'O Amigável com Limites' }, dimensions: ['A', 'N'], photo: '/characters/friendly-with-limits.jpg', description: { es: 'Amigable pero con distancia sana.', en: 'Friendly but with healthy distance.', fr: 'Amical mais avec une distance saine.', de: 'Freundlich aber mit gesunder Distanz.', it: 'Amichevole ma con distanza sana.', pt: 'Amigável mas com distância saudável.' }, philosophy: { es: 'Puedes ser amable sin necesitar mantener una relación cercana. La amabilidad post-ruptura no tiene que significar continuidad de la intimidad. Puedes querer bien a alguien y al mismo tiempo dejarlo ir.', en: 'You can be kind without needing to maintain a close relationship. Post-breakup kindness doesn\'t have to mean continuity of intimacy. You can care for someone and at the same time let them go.', fr: 'Tu peux être gentil(le) sans avoir besoin de maintenir une relation proche. La gentillesse post-rupture ne doit pas signifier la continuité de l\'intimité. Tu peux bien vouloir quelqu\'un et en même temps le laisser partir.', de: 'Du kannst freundlich sein, ohne eine enge Beziehung aufrechterhalten zu müssen. Post-Breakup-Freundlichkeit muss keine Kontinuität der Intimität bedeuten. Du kannst jemanden lieben und ihn gleichzeitig loslassen.', it: 'Puoi essere gentile senza dover mantenere una relazione stretta. La gentilezza post-rottura non deve significare continuità dell\'intimità. Puoi voler bene a qualcuno e allo stesso tempo lasciarlo andare.', pt: 'Você pode ser amável sem precisar manter uma relação próxima. A amabilidade pós-término não precisa significar continuidade da intimidade. Você pode querer bem alguém e ao mesmo tempo deixá-lo ir.' } },
    { name: { es: 'El Rencoroso en Recuperación', en: 'The Resentful in Recovery', fr: 'Le Rancunier en Récupération', de: 'Der Verbitterte in der Genesung', it: 'Il Rancoroso in Recupero', pt: 'O Rancoroso em Recuperação' }, dimensions: ['R', 'N'], photo: '/characters/recovering-rancorous.jpg', description: { es: 'Tuvo rencor y está trabajando en dejarlo ir.', en: 'Had resentment and is working on letting it go.', fr: 'A eu de la rancœur et travaille à la laisser aller.', de: 'Hatte Groll und arbeitet daran, ihn loszulassen.', it: 'Ha avuto rancore e sta lavorando per lasciarlo andare.', pt: 'Teve rancor e está trabalhando em deixá-lo ir.' }, philosophy: { es: 'El rencor fue tu respuesta inicial y estás trabajando en que no sea la permanente. Ese movimiento desde el rencor hacia la neutralidad es crecimiento emocional real, aunque nadie lo celebre.', en: 'Resentment was your initial response and you\'re working on it not being permanent. That movement from resentment toward neutrality is real emotional growth, even if nobody celebrates it.', fr: 'La rancœur était ta réponse initiale et tu travailles pour qu\'elle ne soit pas permanente. Ce mouvement de la rancœur vers la neutralité est une vraie croissance émotionnelle, même si personne ne le célèbre.', de: 'Groll war deine anfängliche Reaktion und du arbeitest daran, dass er nicht dauerhaft ist. Diese Bewegung vom Groll zur Neutralität ist echtes emotionales Wachstum, auch wenn niemand es feiert.', it: 'Il rancore era la tua risposta iniziale e stai lavorando perché non sia quella permanente. Quel movimento dal rancore alla neutralità è vera crescita emotiva, anche se nessuno lo celebra.', pt: 'O rancor foi sua resposta inicial e você está trabalhando para que não seja a permanente. Esse movimento do rancor para a neutralidade é crescimento emocional real, mesmo que ninguém celebre.' } },
    { name: { es: 'El Fantasma Amigable', en: 'The Friendly Ghost', fr: 'Le Fantôme Amical', de: 'Der Freundliche Geist', it: 'Il Fantasma Amichevole', pt: 'O Fantasma Amigável' }, dimensions: ['F', 'A'], photo: '/characters/friendly-ghost.jpg', description: { es: 'No soltó del todo pero no hay drama.', en: 'Hasn\'t fully let go but there\'s no drama.', fr: 'N\'a pas tout à fait lâché mais pas de drame.', de: 'Hat nicht ganz losgelassen, aber kein Drama.', it: 'Non ha lasciato del tutto ma non c\'è drama.', pt: 'Não soltou de todo mas não há drama.' }, philosophy: { es: 'Todavía piensas en esa persona más de lo que muestras, pero externamente mantienes la compostura. Es una combinación interesante: el duelo interno coexiste con el trato externo sano.', en: 'You still think about that person more than you show, but externally you maintain composure. It\'s an interesting combination: internal grief coexists with external healthy treatment.', fr: 'Tu penses encore à cette personne plus que tu ne le montres, mais extérieurement tu gardes ta composure. C\'est une combinaison intéressante : le deuil interne coexiste avec le traitement externe sain.', de: 'Du denkst noch mehr an diese Person als du zeigst, aber äußerlich behältst du die Fassung. Es ist eine interessante Kombination: innere Trauer koexistiert mit äußerlich gesundem Umgang.', it: 'Pensi ancora a quella persona più di quanto mostri, ma esternamente mantieni la compostezza. È una combinazione interessante: il lutto interno coesiste con il trattamento esterno sano.', pt: 'Você ainda pensa nessa pessoa mais do que mostra, mas externamente mantém a compostura. É uma combinação interessante: o luto interno coexiste com o trato externo sano.' } },
  ],
};

export async function seedExType(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'ex-type' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'ex-type',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['relationships'],
      sortOrder: 2,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
