import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tipo de borracho/a eres?', en: 'What kind of drunk are you?', fr: 'Quel type d\'ivre es-tu ?', de: 'Was für ein Betrunkener/eine Betrunkene bist du?', it: 'Che tipo di ubriaco/a sei?', pt: 'Que tipo de bêbado/a você é?' },
  description: { es: 'El alcohol revela el personaje que vive dentro de ti. ¿Cuál es el tuyo?', en: 'Alcohol reveals the character that lives inside you. Which one is yours?', fr: 'L\'alcool révèle le personnage qui vit en toi. Lequel est le tien ?', de: 'Alkohol enthüllt den Charakter, der in dir lebt. Welcher ist deiner?', it: 'L\'alcol rivela il personaggio che vive dentro di te. Qual è il tuo?', pt: 'O álcool revela o personagem que vive dentro de você. Qual é o seu?' },
  scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
  dimensionLabels: {
    es: { E: 'Eufórico', F: 'Filosófico', C: 'Caótico', A: 'Afectuoso' },
    en: { E: 'Euphoric', F: 'Philosophical', C: 'Chaotic', A: 'Affectionate' },
    fr: { E: 'Euphorique', F: 'Philosophique', C: 'Chaotique', A: 'Affectueux' },
    de: { E: 'Euphorisch', F: 'Philosophisch', C: 'Chaotisch', A: 'Liebevoll' },
    it: { E: 'Euforico', F: 'Filosofico', C: 'Caotico', A: 'Affettuoso' },
    pt: { E: 'Eufórico', F: 'Filosófico', C: 'Caótico', A: 'Afetuoso' },
  },
  questions: [
    { id: 1, situation: { es: 'Llevas tres tragos en una fiesta. ¿Cómo está tu energía?', en: 'You\'ve had three drinks at a party. How is your energy?', fr: 'Tu as pris trois verres à une fête. Comment est ton énergie ?', de: 'Du hast drei Getränke auf einer Party. Wie ist deine Energie?', it: 'Hai bevuto tre bicchieri a una festa. Com\'è la tua energia?', pt: 'Você tomou três drinques em uma festa. Como está sua energia?' }, options: [
      { text: { es: 'Disparada. Estoy bailando, hablando con todos, siendo el alma de la fiesta.', en: 'Through the roof. I\'m dancing, talking to everyone, being the life of the party.', fr: 'À fond. Je danse, je parle à tout le monde, je suis l\'âme de la fête.', de: 'Durch die Decke. Ich tanze, rede mit allen, bin die Seele der Party.', it: 'Alle stelle. Sto ballando, parlando con tutti, sono l\'anima della festa.', pt: 'Disparada. Estou dançando, conversando com todos, sendo a alma da festa.' }, dimension: 'E' },
      { text: { es: 'Me volví profundo/a. Quiero hablar de la vida, del universo, de todo.', en: 'I\'ve gone deep. I want to talk about life, the universe, everything.', fr: 'Je suis devenu(e) profond(e). Je veux parler de la vie, de l\'univers, de tout.', de: 'Ich bin tief geworden. Ich will über das Leben, das Universum, alles reden.', it: 'Sono diventato/a profondo/a. Voglio parlare della vita, dell\'universo, di tutto.', pt: 'Me tornei profundo/a. Quero falar sobre a vida, o universo, tudo.' }, dimension: 'F' },
      { text: { es: 'Impredecible. A veces muy bien, a veces hago cosas que mañana no recordaré.', en: 'Unpredictable. Sometimes great, sometimes I do things I won\'t remember tomorrow.', fr: 'Imprévisible. Parfois très bien, parfois je fais des choses que je ne me rappellerai pas demain.', de: 'Unberechenbar. Manchmal sehr gut, manchmal tue ich Dinge, die ich morgen nicht erinnern werde.', it: 'Imprevedibile. A volte molto bene, a volte faccio cose che domani non ricorderò.', pt: 'Imprevisível. Às vezes muito bem, às vezes faço coisas que amanhã não vou lembrar.' }, dimension: 'C' },
      { text: { es: 'Me llenó de amor. Quiero abrazar a todos y decirles cuánto los quiero.', en: 'I\'m full of love. I want to hug everyone and tell them how much I love them.', fr: 'Je suis rempli(e) d\'amour. Je veux embrasser tout le monde et leur dire combien je les aime.', de: 'Ich bin voller Liebe. Ich möchte alle umarmen und ihnen sagen, wie sehr ich sie mag.', it: 'Sono pieno/a d\'amore. Voglio abbracciare tutti e dire loro quanto li voglio bene.', pt: 'Estou cheio/a de amor. Quero abraçar todos e dizer o quanto os amo.' }, dimension: 'A' },
    ] },
    { id: 2, situation: { es: 'Estás muy borracho/a y alguien que no conoces te dice algo que suena interesante. ¿Qué pasa?', en: 'You\'re very drunk and someone you don\'t know says something interesting. What happens?', fr: 'Tu es très ivre et quelqu\'un que tu ne connais pas te dit quelque chose d\'intéressant. Que se passe-t-il ?', de: 'Du bist sehr betrunken und jemand Unbekanntes sagt dir etwas Interessantes. Was passiert?', it: 'Sei molto ubriaco/a e qualcuno che non conosci ti dice qualcosa di interessante. Cosa succede?', pt: 'Você está muito bêbado/a e alguém que você não conhece diz algo interessante. O que acontece?' }, options: [
      { text: { es: 'Me emociono y propongo hacer algo juntos ahora mismo.', en: 'I get excited and propose doing something together right now.', fr: 'Je m\'enthousiasme et propose de faire quelque chose ensemble maintenant même.', de: 'Ich begeistere mich und schlage vor, jetzt gleich etwas zusammen zu machen.', it: 'Mi entusiasmo e propongo di fare qualcosa insieme adesso.', pt: 'Me animo e proponho fazer algo juntos agora mesmo.' }, dimension: 'E' },
      { text: { es: 'Me quedo hablando con esa persona durante horas explorando la idea.', en: 'I stay talking with that person for hours exploring the idea.', fr: 'Je reste à parler avec cette personne pendant des heures à explorer l\'idée.', de: 'Ich bleibe stundenlang mit dieser Person reden und erkunde die Idee.', it: 'Rimango a parlare con quella persona per ore esplorando l\'idea.', pt: 'Fico conversando com essa pessoa por horas explorando a ideia.' }, dimension: 'F' },
      { text: { es: 'Hago algo completamente inesperado relacionado con esa idea.', en: 'I do something completely unexpected related to that idea.', fr: 'Je fais quelque chose de complètement inattendu lié à cette idée.', de: 'Ich tue etwas völlig Unerwartetes, das mit dieser Idee zusammenhängt.', it: 'Faccio qualcosa di completamente inaspettato legato a quell\'idea.', pt: 'Faço algo completamente inesperado relacionado a essa ideia.' }, dimension: 'C' },
      { text: { es: 'Me parece el mejor ser humano del planeta y se lo digo.', en: 'I think they\'re the best human on the planet and I tell them.', fr: 'Je pense que c\'est le meilleur être humain de la planète et je le lui dis.', de: 'Ich denke, es ist der beste Mensch auf dem Planeten und sage es ihm/ihr.', it: 'Mi sembra il migliore essere umano del pianeta e glielo dico.', pt: 'Me parece o melhor ser humano do planeta e digo isso.' }, dimension: 'A' },
    ] },
    { id: 3, situation: { es: 'La fiesta está bajando de energía. ¿Qué haces?', en: 'The party is losing energy. What do you do?', fr: 'La fête perd de l\'énergie. Que fais-tu ?', de: 'Die Party verliert Energie. Was tust du?', it: 'La festa sta perdendo energia. Cosa fai?', pt: 'A festa está perdendo energia. O que você faz?' }, options: [
      { text: { es: 'Propongo cambiar de lugar o pongo música que suba el ambiente.', en: 'I propose changing venue or put on music to lift the vibe.', fr: 'Je propose de changer d\'endroit ou mets de la musique pour remonter l\'ambiance.', de: 'Ich schlage einen Ortswechsel vor oder lege Musik auf, um die Stimmung zu heben.', it: 'Propongo di cambiare posto o metto musica che alzi l\'atmosfera.', pt: 'Proponho mudar de lugar ou coloco música para animar o ambiente.' }, dimension: 'E' },
      { text: { es: 'Me quedo en el rincón teniendo la conversación más profunda de la noche.', en: 'I stay in the corner having the deepest conversation of the night.', fr: 'Je reste dans le coin ayant la conversation la plus profonde de la nuit.', de: 'Ich bleibe in der Ecke und führe das tiefste Gespräch der Nacht.', it: 'Rimango nell\'angolo avendo la conversazione più profonda della notte.', pt: 'Fico no canto tendo a conversa mais profunda da noite.' }, dimension: 'F' },
      { text: { es: 'Hago algo completamente inesperado para que la gente se reactive.', en: 'I do something completely unexpected to get people going again.', fr: 'Je fais quelque chose de complètement inattendu pour que les gens se réactivent.', de: 'Ich tue etwas völlig Unerwartetes, um die Leute wieder zu aktivieren.', it: 'Faccio qualcosa di completamente inaspettato per far riattivare le persone.', pt: 'Faço algo completamente inesperado para animar as pessoas.' }, dimension: 'C' },
      { text: { es: 'Me dedico a las personas que parecen más desganadas para que la pasen mejor.', en: 'I focus on the people who seem most unenthusiastic so they have a better time.', fr: 'Je me consacre aux personnes qui semblent les moins enthousiasmes pour qu\'elles passent un meilleur moment.', de: 'Ich kümmere mich um die Leute, die am unmotiviertesten aussehen, damit sie eine bessere Zeit haben.', it: 'Mi dedico alle persone che sembrano più svogliate perché se la passino meglio.', pt: 'Me dedico às pessoas que parecem mais desanimadas para que se divirtam melhor.' }, dimension: 'A' },
    ] },
    { id: 4, situation: { es: 'Alguien que te cae mal está en la misma fiesta. Has tomado bastante.', en: 'Someone you dislike is at the same party. You\'ve had quite a bit to drink.', fr: 'Quelqu\'un que tu n\'aimes pas est à la même fête. Tu as bu pas mal.', de: 'Jemand, den du nicht magst, ist auf der gleichen Party. Du hast ziemlich viel getrunken.', it: 'Qualcuno che non ti va a genio è alla stessa festa. Hai bevuto abbastanza.', pt: 'Alguém que você não curte está na mesma festa. Você tomou bastante.' }, options: [
      { text: { es: 'Me energizo extra y brillo más para demostrar algo.', en: 'I get extra energized and shine more to prove something.', fr: 'Je me dynamisie encore plus et brille davantage pour prouver quelque chose.', de: 'Ich werde extra energetisiert und glänze mehr, um etwas zu beweisen.', it: 'Mi energizzo extra e brillo di più per dimostrare qualcosa.', pt: 'Me animo extra e brilho mais para provar algo.' }, dimension: 'E' },
      { text: { es: 'Termino teniendo una conversación filosófica con él/ella sobre por qué no nos llevamos bien.', en: 'I end up having a philosophical conversation with them about why we don\'t get along.', fr: 'Je finis par avoir une conversation philosophique avec lui/elle sur pourquoi nous ne nous entendons pas.', de: 'Ich ende damit, ein philosophisches Gespräch mit ihm/ihr über den Grund unserer Unstimmigkeiten zu führen.', it: 'Finisco per avere una conversazione filosofica con lui/lei sul perché non andiamo d\'accordo.', pt: 'Acabo tendo uma conversa filosófica com ele/ela sobre por que não nos entendemos.' }, dimension: 'F' },
      { text: { es: 'Podría hacer o decir algo que después preferiría no haber hecho.', en: 'I might do or say something I\'d later prefer I hadn\'t.', fr: 'Je pourrais faire ou dire quelque chose que je préférerais ensuite ne pas avoir fait.', de: 'Ich könnte etwas tun oder sagen, was ich später lieber nicht getan hätte.', it: 'Potrei fare o dire qualcosa che dopo preferirei non aver fatto.', pt: 'Posso fazer ou dizer algo que depois preferiria não ter feito.' }, dimension: 'C' },
      { text: { es: 'Le digo que los conflictos entre personas son tontos y propongo hacer las paces.', en: 'I tell them that conflicts between people are silly and propose making peace.', fr: 'Je lui dis que les conflits entre personnes sont stupides et propose de faire la paix.', de: 'Ich sage ihm/ihr, dass Konflikte zwischen Menschen dumm sind und schlage vor, Frieden zu schließen.', it: 'Gli dico che i conflitti tra persone sono stupidi e propongo di fare la pace.', pt: 'Digo que os conflitos entre pessoas são bobos e proponho fazer as pazes.' }, dimension: 'A' },
    ] },
    { id: 5, situation: { es: 'Tu canción favorita suena en la fiesta.', en: 'Your favorite song plays at the party.', fr: 'Ta chanson préférée joue à la fête.', de: 'Dein Lieblingslied läuft auf der Party.', it: 'La tua canzone preferita suona alla festa.', pt: 'Sua música favorita toca na festa.' }, options: [
      { text: { es: 'Al centro de la pista, inmediatamente.', en: 'To the center of the dance floor, immediately.', fr: 'Au centre de la piste, immédiatement.', de: 'Sofort in die Mitte der Tanzfläche.', it: 'Al centro della pista, immediatamente.', pt: 'Ao centro da pista, imediatamente.' }, dimension: 'E' },
      { text: { es: 'Me genera nostalgia y me quedo pensando en por qué esa canción significa tanto.', en: 'It makes me nostalgic and I stay thinking about why that song means so much.', fr: 'Ça me rend nostalgique et je reste à penser pourquoi cette chanson signifie autant.', de: 'Es macht mich nostalgisch und ich denke nach, warum dieses Lied so viel bedeutet.', it: 'Mi genera nostalgia e rimango a pensare perché quella canzone significhi così tanto.', pt: 'Me gera nostalgia e fico pensando por que essa música significa tanto.' }, dimension: 'F' },
      { text: { es: 'Hago algo completamente ridículo que me parece brillante en ese momento.', en: 'I do something completely ridiculous that seems brilliant to me in the moment.', fr: 'Je fais quelque chose de complètement ridicule qui me semble brillant dans ce moment.', de: 'Ich tue etwas völlig Lächerliches, das mir in diesem Moment brillant erscheint.', it: 'Faccio qualcosa di completamente ridicolo che mi sembra brillante in quel momento.', pt: 'Faço algo completamente ridículo que me parece brilhante naquele momento.' }, dimension: 'C' },
      { text: { es: 'Busco a mis amigos más cercanos para bailar juntos. Quiero compartirlo.', en: 'I look for my closest friends to dance together. I want to share it.', fr: 'Je cherche mes amis les plus proches pour danser ensemble. Je veux le partager.', de: 'Ich suche meine engsten Freunde, um zusammen zu tanzen. Ich möchte es teilen.', it: 'Cerco i miei amici più vicini per ballare insieme. Voglio condividerlo.', pt: 'Busco meus amigos mais próximos para dançar juntos. Quero compartilhar.' }, dimension: 'A' },
    ] },
    { id: 6, situation: { es: 'Hay una persona que te gusta en la fiesta. Estás bastante borracho/a.', en: 'There\'s someone you like at the party. You\'re quite drunk.', fr: 'Il y a quelqu\'un qui te plaît à la fête. Tu es assez ivre.', de: 'Es gibt jemanden, der dir auf der Party gefällt. Du bist ziemlich betrunken.', it: 'C\'è una persona che ti piace alla festa. Sei abbastanza ubriaco/a.', pt: 'Há uma pessoa que você gosta na festa. Você está bastante bêbado/a.' }, options: [
      { text: { es: 'Me acerco con toda la energía del mundo. El alcohol me quitó la timidez.', en: 'I approach with all the energy in the world. Alcohol removed my shyness.', fr: 'Je m\'approche avec toute l\'énergie du monde. L\'alcool m\'a enlevé la timidité.', de: 'Ich nähere mich mit aller Energie der Welt. Alkohol hat meine Schüchternheit genommen.', it: 'Mi avvicino con tutta l\'energia del mondo. L\'alcol mi ha tolto la timidezza.', pt: 'Me aproximo com toda a energia do mundo. O álcool me tirou a timidez.' }, dimension: 'E' },
      { text: { es: 'Me acerco y terminamos en una conversación profunda sobre la vida.', en: 'I approach and we end up in a deep conversation about life.', fr: 'Je m\'approche et nous finissons dans une conversation profonde sur la vie.', de: 'Ich nähere mich und wir enden in einem tiefen Gespräch über das Leben.', it: 'Mi avvicino e finiamo in una conversazione profonda sulla vita.', pt: 'Me aproximo e acabamos em uma conversa profunda sobre a vida.' }, dimension: 'F' },
      { text: { es: 'Hago algo completamente impulsivo que podría resultar muy bien o muy mal.', en: 'I do something completely impulsive that could go very well or very badly.', fr: 'Je fais quelque chose de complètement impulsif qui pourrait très bien ou très mal se passer.', de: 'Ich tue etwas völlig Impulsives, das sehr gut oder sehr schlecht ausgehen könnte.', it: 'Faccio qualcosa di completamente impulsivo che potrebbe andare molto bene o molto male.', pt: 'Faço algo completamente impulsivo que pode resultar muito bem ou muito mal.' }, dimension: 'C' },
      { text: { es: 'Le digo que me parece increíble. Con mucho cariño y mucha sinceridad.', en: 'I tell them they seem incredible to me. With lots of affection and sincerity.', fr: 'Je lui dis qu\'il/elle me semble incroyable. Avec beaucoup d\'affection et de sincérité.', de: 'Ich sage ihnen, dass sie mir unglaublich erscheinen. Mit viel Zuneigung und Aufrichtigkeit.', it: 'Gli dico che mi sembra incredibile. Con molto affetto e molta sincerità.', pt: 'Digo que me parece incrível. Com muito carinho e muita sinceridade.' }, dimension: 'A' },
    ] },
    { id: 7, situation: { es: 'Alguien empieza a contar un problema personal en la fiesta. Llevas varios tragos.', en: 'Someone starts sharing a personal problem at the party. You\'ve had several drinks.', fr: 'Quelqu\'un commence à raconter un problème personnel à la fête. Tu as bu plusieurs verres.', de: 'Jemand beginnt, auf der Party ein persönliches Problem zu erzählen. Du hast mehrere Getränke genommen.', it: 'Qualcuno inizia a raccontare un problema personale alla festa. Hai bevuto vari bicchieri.', pt: 'Alguém começa a contar um problema pessoal na festa. Você tomou vários drinques.' }, options: [
      { text: { es: 'Escucho un momento y propongo distraerse con algo divertido. Los problemas son para mañana.', en: 'I listen for a moment and propose distracting ourselves with something fun. Problems are for tomorrow.', fr: 'J\'écoute un moment et propose de se distraire avec quelque chose d\'amusant. Les problèmes c\'est pour demain.', de: 'Ich höre einen Moment zu und schlage vor, uns mit etwas Lustigem abzulenken. Probleme sind für morgen.', it: 'Ascolto un momento e propongo di distrarsi con qualcosa di divertente. I problemi sono per domani.', pt: 'Ouço um momento e proponho nos distrair com algo divertido. Os problemas são para amanhã.' }, dimension: 'E' },
      { text: { es: 'Me engancho totalmente y terminamos en la conversación más profunda de la noche.', en: 'I get totally hooked and we end up in the deepest conversation of the night.', fr: 'Je suis totalement accroché(e) et nous finissons dans la conversation la plus profonde de la nuit.', de: 'Ich bin total gefesselt und wir enden im tiefsten Gespräch der Nacht.', it: 'Mi aggancio totalmente e finiamo nella conversazione più profonda della notte.', pt: 'Me envolvo totalmente e acabamos na conversa mais profunda da noite.' }, dimension: 'F' },
      { text: { es: 'Propongo una solución completamente fuera de lo común. Probablemente descabellada.', en: 'I propose a completely unconventional solution. Probably far-fetched.', fr: 'Je propose une solution complètement hors du commun. Probablement farfelue.', de: 'Ich schlage eine völlig ungewöhnliche Lösung vor. Wahrscheinlich abwegig.', it: 'Propongo una soluzione completamente fuori dal comune. Probabilmente strampalata.', pt: 'Proponho uma solução completamente fora do comum. Provavelmente descabida.' }, dimension: 'C' },
      { text: { es: 'Me convierto en el apoyo emocional de esa persona por el resto de la noche.', en: 'I become that person\'s emotional support for the rest of the night.', fr: 'Je deviens le soutien émotionnel de cette personne pour le reste de la nuit.', de: 'Ich werde für den Rest der Nacht die emotionale Unterstützung dieser Person.', it: 'Divento il supporto emotivo di quella persona per il resto della notte.', pt: 'Me torno o suporte emocional dessa pessoa pelo resto da noite.' }, dimension: 'A' },
    ] },
    { id: 8, situation: { es: '¿Qué tipo de mensajes mandas cuando estás muy borracho/a?', en: 'What kind of messages do you send when you\'re very drunk?', fr: 'Quel type de messages envoies-tu quand tu es très ivre ?', de: 'Welche Art von Nachrichten sendest du, wenn du sehr betrunken bist?', it: 'Che tipo di messaggi mandi quando sei molto ubriaco/a?', pt: 'Que tipo de mensagens você manda quando está muito bêbado/a?' }, options: [
      { text: { es: 'Mensajes de planes: "¿Dónde estás? Ven acá. Vamos a tal lugar."', en: 'Plans messages: "Where are you? Come here. Let\'s go to this place."', fr: 'Messages de plans: "Où es-tu? Viens ici. Allons à tel endroit."', de: 'Planungsnachrichten: "Wo bist du? Komm her. Lass uns dahin gehen."', it: 'Messaggi di piani: "Dove sei? Vieni qui. Andiamo in quel posto."', pt: 'Mensagens de planos: "Onde você está? Vem aqui. Vamos para aquele lugar."' }, dimension: 'E' },
      { text: { es: 'Reflexiones largas sobre la vida, el tiempo, el sentido de las cosas.', en: 'Long reflections about life, time, the meaning of things.', fr: 'De longues réflexions sur la vie, le temps, le sens des choses.', de: 'Lange Reflexionen über das Leben, die Zeit, den Sinn der Dinge.', it: 'Lunghe riflessioni sulla vita, il tempo, il senso delle cose.', pt: 'Reflexões longas sobre a vida, o tempo, o significado das coisas.' }, dimension: 'F' },
      { text: { es: 'Mensajes completamente impredecibles que mañana preferiría no haber mandado.', en: 'Completely unpredictable messages I\'d prefer tomorrow not to have sent.', fr: 'Des messages complètement imprévisibles que je préférerais demain ne pas avoir envoyés.', de: 'Völlig unberechenbare Nachrichten, die ich morgen lieber nicht gesendet hätte.', it: 'Messaggi completamente imprevedibili che domani preferirei non aver mandato.', pt: 'Mensagens completamente imprevisíveis que amanhã preferiria não ter mandado.' }, dimension: 'C' },
      { text: { es: '"Te quiero mucho", "eres increíble", "me alegra que existas en mi vida."', en: '"I love you so much", "you\'re incredible", "I\'m glad you exist in my life."', fr: '"Je t\'aime beaucoup", "tu es incroyable", "je suis content(e) que tu existes dans ma vie."', de: '"Ich liebe dich sehr", "du bist unglaublich", "ich bin froh, dass du in meinem Leben existierst."', it: '"Ti voglio tanto bene", "sei incredibile", "sono felice che esisti nella mia vita."', pt: '"Te amo muito", "você é incrível", "fico feliz que exista na minha vida."' }, dimension: 'A' },
    ] },
    { id: 9, situation: { es: 'Al día siguiente, ¿cuál es tu mayor preocupación?', en: 'The next day, what is your biggest concern?', fr: 'Le lendemain, quelle est ta plus grande préoccupation ?', de: 'Am nächsten Tag, was ist deine größte Sorge?', it: 'Il giorno dopo, qual è la tua maggiore preoccupazione?', pt: 'No dia seguinte, qual é sua maior preocupação?' }, options: [
      { text: { es: '¿Hice lo suficientemente épico? Espero que haya valido la pena.', en: 'Did I do something epic enough? I hope it was worth it.', fr: 'Ai-je fait quelque chose d\'assez épique ? J\'espère que ça en valait la peine.', de: 'Habe ich etwas Episches genug gemacht? Ich hoffe, es war es wert.', it: 'Ho fatto qualcosa di abbastanza epico? Spero che ne sia valsa la pena.', pt: 'Fiz algo épico o suficiente? Espero que tenha valido a pena.' }, dimension: 'E' },
      { text: { es: '¿Diré algo profundo que no recuerdo? Ojalá alguien lo grabó.', en: 'Did I say something profound I don\'t remember? I hope someone recorded it.', fr: 'Ai-je dit quelque chose de profond que je ne me rappelle pas ? J\'espère que quelqu\'un l\'a enregistré.', de: 'Habe ich etwas Tiefgründiges gesagt, das ich nicht erinnere? Ich hoffe, jemand hat es aufgezeichnet.', it: 'Ho detto qualcosa di profondo che non ricordo? Speriamo che qualcuno l\'abbia registrato.', pt: 'Terei dito algo profundo que não me lembro? Tomara que alguém tenha gravado.' }, dimension: 'F' },
      { text: { es: '¿Qué hice exactamente? Tengo fragmentos pero no el cuadro completo.', en: 'What exactly did I do? I have fragments but not the full picture.', fr: 'Qu\'ai-je fait exactement ? J\'ai des fragments mais pas le tableau complet.', de: 'Was genau habe ich gemacht? Ich habe Fragmente, aber nicht das vollständige Bild.', it: 'Cosa ho fatto esattamente? Ho dei frammenti ma non il quadro completo.', pt: 'O que exatamente eu fiz? Tenho fragmentos mas não o quadro completo.' }, dimension: 'C' },
      { text: { es: '¿Fui demasiado intenso/a con los mensajes de amor? Espero no haber incomodado.', en: 'Was I too intense with the love messages? I hope I didn\'t make anyone uncomfortable.', fr: 'Ai-je été trop intense avec les messages d\'amour ? J\'espère ne pas avoir mis mal à l\'aise.', de: 'War ich zu intensiv mit den Liebesbotschaften? Ich hoffe, ich habe niemanden unwohl gemacht.', it: 'Sono stato/a troppo intenso/a con i messaggi d\'amore? Spero di non aver messo a disagio nessuno.', pt: 'Fui muito intenso/a com as mensagens de amor? Espero não ter incomodado ninguém.' }, dimension: 'A' },
    ] },
    { id: 10, situation: { es: 'Tus amigos te describen después de una noche de tragos. ¿Qué dicen?', en: 'Your friends describe you after a night of drinks. What do they say?', fr: 'Tes amis te décrivent après une nuit de verres. Que disent-ils ?', de: 'Deine Freunde beschreiben dich nach einer Nacht mit Getränken. Was sagen sie?', it: 'I tuoi amici ti descrivono dopo una notte di bicchieri. Cosa dicono?', pt: 'Seus amigos te descrevem depois de uma noite de drinques. O que dizem?' }, options: [
      { text: { es: '"Es la persona más divertida de la fiesta. Siempre en movimiento."', en: '"They\'re the most fun person at the party. Always moving."', fr: '"C\'est la personne la plus amusante de la fête. Toujours en mouvement."', de: '"Er/sie ist die lustigste Person auf der Party. Immer in Bewegung."', it: '"È la persona più divertente della festa. Sempre in movimento."', pt: '"É a pessoa mais divertida da festa. Sempre em movimento."' }, dimension: 'E' },
      { text: { es: '"Terminamos hablando de cosas muy serias. Siempre pasa."', en: '"We ended up talking about very serious things. It always happens."', fr: '"Nous avons fini par parler de choses très sérieuses. Ça arrive toujours."', de: '"Wir haben am Ende über sehr ernste Dinge geredet. Es passiert immer."', it: '"Abbiamo finito a parlare di cose molto serie. Succede sempre."', pt: '"Acabamos falando de coisas muito sérias. Sempre acontece."' }, dimension: 'F' },
      { text: { es: '"Nunca sabes qué va a hacer. Impredecible total."', en: '"You never know what they\'re going to do. Totally unpredictable."', fr: '"On ne sait jamais ce qu\'il/elle va faire. Totalement imprévisible."', de: '"Man weiß nie, was er/sie tun wird. Völlig unberechenbar."', it: '"Non si sa mai cosa farà. Totalmente imprevedibile."', pt: '"Nunca se sabe o que vai fazer. Totalmente imprevisível."' }, dimension: 'C' },
      { text: { es: '"Me dijo que me quería tres veces. Es lo mejor del mundo cuando está borracho/a."', en: '"They told me they loved me three times. They\'re the best when drunk."', fr: '"Il/elle m\'a dit qu\'il/elle m\'aimait trois fois. C\'est le meilleur du monde quand il/elle est ivre."', de: '"Er/sie sagte mir dreimal, dass er/sie mich liebt. Er/sie ist der/die Beste der Welt, wenn betrunken."', it: '"Mi ha detto che mi voleva bene tre volte. È il migliore del mondo quando è ubriaco/a."', pt: '"Me disse que me amava três vezes. É o melhor do mundo quando está bêbado/a."' }, dimension: 'A' },
    ] },
  ],
  characters: [
    { name: { es: 'El Alma de la Fiesta', en: 'The Life of the Party', fr: 'L\'Âme de la Fête', de: 'Die Seele der Party', it: 'L\'Anima della Festa', pt: 'A Alma da Festa' }, dimensions: ['E'], photo: '/characters/party-soul.jpg', description: { es: 'Su energía contagia a toda la sala.', en: 'Their energy is contagious throughout the whole room.', fr: 'Son énergie est contagieuse dans toute la salle.', de: 'Seine/ihre Energie steckt den ganzen Raum an.', it: 'La sua energia contagia tutta la sala.', pt: 'Sua energia contagia toda a sala.' }, philosophy: { es: 'Cuando bebes, tu mejor versión social emerge amplificada. Eres la persona que hace que la fiesta sea la fiesta. Todo el mundo quiere estar donde tú estás. El alcohol simplemente elimina los filtros de lo que ya eras.', en: 'When you drink, your best social version emerges amplified. You\'re the person who makes the party the party. Everyone wants to be where you are. Alcohol simply removes the filters of who you already were.', fr: 'Quand tu bois, ta meilleure version sociale émerge amplifiée. Tu es la personne qui fait de la fête, la fête. Tout le monde veut être là où tu es. L\'alcool supprime simplement les filtres de ce que tu étais déjà.', de: 'Wenn du trinkst, kommt deine beste soziale Version verstärkt heraus. Du bist die Person, die aus der Party die Party macht. Alle wollen dort sein, wo du bist. Alkohol entfernt einfach die Filter dessen, was du bereits warst.', it: 'Quando bevi, la tua migliore versione sociale emerge amplificata. Sei la persona che fa diventare la festa, la festa. Tutti vogliono essere dove sei tu. L\'alcol semplicemente rimuove i filtri di ciò che eri già.', pt: 'Quando você bebe, sua melhor versão social emerge amplificada. Você é a pessoa que faz a festa ser a festa. Todos querem estar onde você está. O álcool simplesmente elimina os filtros do que você já era.' } },
    { name: { es: 'El Filósofo Ebrio', en: 'The Drunk Philosopher', fr: 'Le Philosophe Ivre', de: 'Der Betrunkene Philosoph', it: 'Il Filosofo Ubriaco', pt: 'O Filósofo Bêbado' }, dimensions: ['F'], photo: '/characters/drunk-philosopher.jpg', description: { es: 'Convierte cada copa en una conversación profunda.', en: 'Turns every drink into a deep conversation.', fr: 'Transforme chaque verre en une conversation profonde.', de: 'Verwandelt jedes Getränk in ein tiefes Gespräch.', it: 'Trasforma ogni bicchiere in una conversazione profonda.', pt: 'Transforma cada taça em uma conversa profunda.' }, philosophy: { es: 'Cuando el mundo desacelera un poco, tus pensamientos profundos finalmente tienen espacio para salir. No buscas ruido — buscas verdad. Y a veces la encuentras en el rincón más inesperado de una fiesta.', en: 'When the world slows down a little, your deep thoughts finally have space to come out. You\'re not looking for noise — you\'re looking for truth. And sometimes you find it in the most unexpected corner of a party.', fr: 'Quand le monde ralentit un peu, tes pensées profondes ont enfin l\'espace pour sortir. Tu ne cherches pas le bruit — tu cherches la vérité. Et parfois tu la trouves dans le coin le plus inattendu d\'une fête.', de: 'Wenn die Welt ein wenig langsamer wird, haben deine tiefen Gedanken endlich Raum herauszukommen. Du suchst nicht Lärm — du suchst Wahrheit. Und manchmal findest du sie in der unerwartetsten Ecke einer Party.', it: 'Quando il mondo rallenta un po\', i tuoi pensieri profondi hanno finalmente spazio per uscire. Non cerchi rumore — cerchi verità. E a volte la trovi nell\'angolo più inaspettato di una festa.', pt: 'Quando o mundo desacelera um pouco, seus pensamentos profundos finalmente têm espaço para sair. Você não busca barulho — busca verdade. E às vezes a encontra no canto mais inesperado de uma festa.' } },
    { name: { es: 'El Agente del Caos', en: 'The Chaos Agent', fr: 'L\'Agent du Chaos', de: 'Der Chaos-Agent', it: 'L\'Agente del Caos', pt: 'O Agente do Caos' }, dimensions: ['C'], photo: '/characters/chaos-agent.jpg', description: { es: 'Sus noches son leyendas. Nadie sabe qué va a pasar.', en: 'Their nights are legends. Nobody knows what\'s going to happen.', fr: 'Ses nuits sont des légendes. Personne ne sait ce qui va se passer.', de: 'Seine/ihre Nächte sind Legenden. Niemand weiß, was passieren wird.', it: 'Le sue notti sono leggende. Nessuno sa cosa succederà.', pt: 'Suas noites são lendas. Ninguém sabe o que vai acontecer.' }, philosophy: { es: 'El alcohol libera algo que en la sobriedad está muy bien guardado: el impulso. No calculas, no filtras, simplemente actúas. A veces es brillante. A veces es un desastre. Siempre es una historia.', en: 'Alcohol releases something that in sobriety is very well kept: the impulse. You don\'t calculate, don\'t filter, you simply act. Sometimes it\'s brilliant. Sometimes it\'s a disaster. It\'s always a story.', fr: 'L\'alcool libère quelque chose qui dans la sobriété est très bien gardé : l\'impulsion. Tu ne calcules pas, tu ne filtres pas, tu agis simplement. Parfois c\'est brillant. Parfois c\'est un désastre. C\'est toujours une histoire.', de: 'Alkohol setzt etwas frei, das in der Nüchternheit sehr gut bewacht ist: den Impuls. Du berechnest nicht, filterst nicht, du handelst einfach. Manchmal ist es brilliant. Manchmal ist es eine Katastrophe. Es ist immer eine Geschichte.', it: 'L\'alcol libera qualcosa che nella sobrietà è molto ben custodito: l\'impulso. Non calcoli, non filtri, semplicemente agisci. A volte è brillante. A volte è un disastro. È sempre una storia.', pt: 'O álcool libera algo que na sobriedade está muito bem guardado: o impulso. Você não calcula, não filtra, simplesmente age. Às vezes é brilhante. Às vezes é um desastre. É sempre uma história.' } },
    { name: { es: 'El Amante Universal', en: 'The Universal Lover', fr: 'L\'Amant Universel', de: 'Der Universelle Liebende', it: 'L\'Amante Universale', pt: 'O Amante Universal' }, dimensions: ['A'], photo: '/characters/universal-lover.jpg', description: { es: 'Quiere a todos. Sin reservas ni filtros.', en: 'Loves everyone. Without reservations or filters.', fr: 'Aime tout le monde. Sans réserves ni filtres.', de: 'Liebt alle. Ohne Vorbehalte oder Filter.', it: 'Vuole bene a tutti. Senza riserve né filtri.', pt: 'Ama todos. Sem reservas nem filtros.' }, philosophy: { es: 'El alcohol te quita las capas de protección que usas cotidianamente y sale lo que hay debajo: amor genuino por las personas. Eres el abrazo que todos necesitan, el "te quiero" que nadie esperaba recibir.', en: 'Alcohol removes the layers of protection you use daily and what comes out is what\'s underneath: genuine love for people. You\'re the hug everyone needs, the "I love you" nobody expected to receive.', fr: 'L\'alcool te retire les couches de protection que tu utilises quotidiennement et ce qui sort c\'est ce qu\'il y a en dessous : un amour authentique pour les gens. Tu es l\'étreinte dont tout le monde a besoin, le "je t\'aime" que personne n\'attendait recevoir.', de: 'Alkohol entfernt die Schutzschichten, die du täglich verwendest, und was herauskommt ist, was darunter ist: echte Liebe für Menschen. Du bist die Umarmung, die alle brauchen, das "Ich liebe dich", das niemand erwartet zu empfangen.', it: 'L\'alcol ti toglie gli strati di protezione che usi quotidianamente e viene fuori quello che c\'è sotto: amore genuino per le persone. Sei l\'abbraccio di cui tutti hanno bisogno, il "ti voglio bene" che nessuno si aspettava di ricevere.', pt: 'O álcool tira as camadas de proteção que você usa cotidianamente e sai o que há por baixo: amor genuíno pelas pessoas. Você é o abraço que todos precisam, o "te amo" que ninguém esperava receber.' } },
    { name: { es: 'El Eufórico Afectuoso', en: 'The Euphoric Affectionate', fr: 'L\'Euphorique Affectueux', de: 'Der Euphorisch Liebevolle', it: 'L\'Euforico Affettuoso', pt: 'O Eufórico Afetuoso' }, dimensions: ['E', 'A'], photo: '/characters/euphoric-affectionate.jpg', description: { es: 'Energía desbordante + amor sin filtros. Una combinación explosiva.', en: 'Overflowing energy + love without filters. An explosive combination.', fr: 'Énergie débordante + amour sans filtres. Une combinaison explosive.', de: 'Überwältigende Energie + Liebe ohne Filter. Eine explosive Kombination.', it: 'Energia traboccante + amore senza filtri. Una combinazione esplosiva.', pt: 'Energia transbordante + amor sem filtros. Uma combinação explosiva.' }, philosophy: { es: 'Eres la tormenta perfecta de energía y amor. Haces que la fiesta sea épica y al mismo tiempo haces que todos se sientan especiales. Es agotador para los demás pero nadie se queja.', en: 'You\'re the perfect storm of energy and love. You make the party epic and at the same time make everyone feel special. It\'s exhausting for others but nobody complains.', fr: 'Tu es la tempête parfaite d\'énergie et d\'amour. Tu rends la fête épique et en même temps tu fais que tout le monde se sente spécial. C\'est épuisant pour les autres mais personne ne se plaint.', de: 'Du bist der perfekte Sturm aus Energie und Liebe. Du machst die Party episch und gleichzeitig machst du, dass sich alle besonders fühlen. Es ist erschöpfend für andere, aber niemand beschwert sich.', it: 'Sei la tempesta perfetta di energia e amore. Fai la festa epica e allo stesso tempo fai sentire tutti speciali. È estenuante per gli altri ma nessuno si lamenta.', pt: 'Você é a tempestade perfeita de energia e amor. Você faz a festa épica e ao mesmo tempo faz todos se sentirem especiais. É exaustivo para os outros, mas ninguém reclama.' } },
    { name: { es: 'El Caótico Profundo', en: 'The Deep Chaotic', fr: 'Le Chaotique Profond', de: 'Der Tiefe Chaotische', it: 'Il Caotico Profondo', pt: 'O Caótico Profundo' }, dimensions: ['C', 'F'], photo: '/characters/chaotic-deep.jpg', description: { es: 'Impredecible y profundo. Una noche con él/ella es siempre una aventura intelectual.', en: 'Unpredictable and deep. A night with them is always an intellectual adventure.', fr: 'Imprévisible et profond. Une nuit avec lui/elle est toujours une aventure intellectuelle.', de: 'Unberechenbar und tiefgründig. Eine Nacht mit ihm/ihr ist immer ein intellektuelles Abenteuer.', it: 'Imprevedibile e profondo. Una notte con lui/lei è sempre un\'avventura intellettuale.', pt: 'Imprevisível e profundo. Uma noite com ele/ela é sempre uma aventura intelectual.' }, philosophy: { es: 'Mezclas el caos con la profundidad de formas que desconciertan a todos. Puedes estar en el centro del desorden y a la vez tener la conversación más interesante de la noche. Nadie sabe cómo funciona, pero funciona.', en: 'You mix chaos with depth in ways that baffle everyone. You can be at the center of disorder and at the same time have the most interesting conversation of the night. Nobody knows how it works, but it does.', fr: 'Tu mixes le chaos avec la profondeur de façons qui désorientent tout le monde. Tu peux être au centre du désordre et en même temps avoir la conversation la plus intéressante de la nuit. Personne ne sait comment ça fonctionne, mais ça fonctionne.', de: 'Du mischt Chaos mit Tiefe auf Weisen, die alle verblüffen. Du kannst im Zentrum des Chaos sein und gleichzeitig das interessanteste Gespräch der Nacht führen. Niemand weiß, wie es funktioniert, aber es tut es.', it: 'Mescoli il caos con la profondità in modi che sconcertano tutti. Puoi essere al centro del disordine e allo stesso tempo avere la conversazione più interessante della notte. Nessuno sa come funziona, ma funziona.', pt: 'Você mistura o caos com a profundidade de formas que desconcertam todos. Você pode estar no centro da desordem e ao mesmo tempo ter a conversa mais interessante da noite. Ninguém sabe como funciona, mas funciona.' } },
    { name: { es: 'El Filósofo Amoroso', en: 'The Loving Philosopher', fr: 'Le Philosophe Amoureux', de: 'Der Liebende Philosoph', it: 'Il Filosofo Amoroso', pt: 'O Filósofo Amoroso' }, dimensions: ['F', 'A'], photo: '/characters/philosophical-loving.jpg', description: { es: 'Quiere entender a todos y quererlos al mismo tiempo.', en: 'Wants to understand everyone and love them at the same time.', fr: 'Veut comprendre tout le monde et les aimer en même temps.', de: 'Möchte alle verstehen und sie gleichzeitig lieben.', it: 'Vuole capire tutti e volergli bene allo stesso tempo.', pt: 'Quer entender todos e amá-los ao mesmo tempo.' }, philosophy: { es: 'Cuando bebes, te vuelves una combinación perfecta de curiosidad y afecto. Quieres entender a las personas profundamente y amarlas exactamente como son. Es una forma muy hermosa de estar borracho/a.', en: 'When you drink, you become a perfect combination of curiosity and affection. You want to understand people deeply and love them exactly as they are. It\'s a very beautiful way to be drunk.', fr: 'Quand tu bois, tu deviens une combinaison parfaite de curiosité et d\'affection. Tu veux comprendre les gens profondément et les aimer exactement tels qu\'ils sont. C\'est une très belle façon d\'être ivre.', de: 'Wenn du trinkst, wirst du eine perfekte Kombination aus Neugier und Zuneigung. Du willst Menschen tief verstehen und sie genau so lieben, wie sie sind. Es ist eine sehr schöne Art, betrunken zu sein.', it: 'Quando bevi, diventi una combinazione perfetta di curiosità e affetto. Vuoi capire le persone profondamente e amarle esattamente come sono. È un modo molto bello di essere ubriaco/a.', pt: 'Quando você bebe, você se torna uma combinação perfeita de curiosidade e afeto. Você quer entender as pessoas profundamente e amá-las exatamente como são. É uma forma muito bonita de estar bêbado/a.' } },
    { name: { es: 'El Epicentro', en: 'The Epicenter', fr: 'L\'Épicentre', de: 'Das Epizentrum', it: 'L\'Epicentro', pt: 'O Epicentro' }, dimensions: ['E', 'C'], photo: '/characters/epicenter.jpg', description: { es: 'Energía caótica. El ojo del huracán.', en: 'Chaotic energy. The eye of the hurricane.', fr: 'Énergie chaotique. L\'œil du cyclone.', de: 'Chaotische Energie. Das Auge des Hurrikans.', it: 'Energia caotica. L\'occhio dell\'uragano.', pt: 'Energia caótica. O olho do furacão.' }, philosophy: { es: 'Cuando bebes, no solo hay fiesta — hay evento. Tu energía y tu imprevisibilidad crean noches que quedan en la memoria colectiva. No siempre de la forma que esperarías, pero siempre.', en: 'When you drink, it\'s not just a party — it\'s an event. Your energy and unpredictability create nights that remain in collective memory. Not always in the way you\'d expect, but always.', fr: 'Quand tu bois, ce n\'est pas juste une fête — c\'est un événement. Ton énergie et ton imprévisibilité créent des nuits qui restent dans la mémoire collective. Pas toujours de la façon à laquelle tu t\'attendrais, mais toujours.', de: 'Wenn du trinkst, gibt es nicht nur eine Party — es gibt ein Ereignis. Deine Energie und Unberechenbarkeit schaffen Nächte, die im kollektiven Gedächtnis bleiben. Nicht immer so, wie du es erwartest, aber immer.', it: 'Quando bevi, non c\'è solo una festa — c\'è un evento. La tua energia e la tua imprevedibilità creano notti che rimangono nella memoria collettiva. Non sempre nel modo in cui ti aspetteresti, ma sempre.', pt: 'Quando você bebe, não é só uma festa — é um evento. Sua energia e imprevisibilidade criam noites que ficam na memória coletiva. Nem sempre da forma que esperaria, mas sempre.' } },
  ],
};

export async function seedDrunk(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'drunk' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'drunk',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 4,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
