import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Eres el personaje principal de tu vida?', en: 'Are you the main character of your life?', fr: 'Es-tu le personnage principal de ta vie ?', de: 'Bist du die Hauptfigur deines Lebens?', it: 'Sei il personaggio principale della tua vita?', pt: 'Você é o personagem principal da sua vida?' },
  description: { es: 'Hay quien protagoniza su vida y hay quien la vive de fondo. ¿Cuál es tu papel?', en: 'Some people star in their own lives and others live in the background. What\'s your role?', fr: 'Certains sont protagonistes de leur vie et d\'autres y vivent en arrière-plan. Quel est ton rôle ?', de: 'Manche Menschen sind die Hauptdarsteller ihres eigenen Lebens und andere leben im Hintergrund. Welche Rolle spielst du?', it: 'C\'è chi è protagonista della propria vita e chi la vive sullo sfondo. Qual è il tuo ruolo?', pt: 'Há quem protagonize sua própria vida e há quem a viva em segundo plano. Qual é o seu papel?' },
  scenarioLabel: { es: 'Escenario', en: 'Scene', fr: 'Scène', de: 'Szene', it: 'Scena', pt: 'Cena' },
  dimensionLabels: {
    es: { P: 'Protagonismo', A: 'Autoconciencia', N: 'Narrativa', I: 'Intención' },
    en: { P: 'Protagonism', A: 'Self-Awareness', N: 'Narrative', I: 'Intention' },
    fr: { P: 'Protagonisme', A: 'Conscience de Soi', N: 'Narration', I: 'Intention' },
    de: { P: 'Protagonismus', A: 'Selbstbewusstsein', N: 'Narrativ', I: 'Absicht' },
    it: { P: 'Protagonismo', A: 'Autoconsapevolezza', N: 'Narrativa', I: 'Intenzione' },
    pt: { P: 'Protagonismo', A: 'Autoconsciência', N: 'Narrativa', I: 'Intenção' },
  },
  questions: [
    { id: 1, situation: { es: 'Caminas por la calle con música en los oídos. ¿Qué pasa internamente?', en: 'You walk down the street with music in your ears. What happens internally?', fr: 'Tu marches dans la rue avec de la musique dans les oreilles. Que se passe-t-il intérieurement ?', de: 'Du gehst mit Musik in den Ohren die Straße entlang. Was passiert innerlich?', it: 'Cammini per strada con la musica nelle orecchie. Cosa succede internamente?', pt: 'Você caminha pela rua com música nos ouvidos. O que acontece internamente?' }, options: [
      { text: { es: 'Soy el protagonista de un videoclip. La cámara me sigue.', en: 'I\'m the star of a music video. The camera follows me.', fr: 'Je suis la vedette d\'un clip vidéo. La caméra me suit.', de: 'Ich bin der Star eines Musikvideos. Die Kamera folgt mir.', it: 'Sono il protagonista di un videoclip. La telecamera mi segue.', pt: 'Sou o protagonista de um videoclipe. A câmera me segue.' }, dimension: 'P' },
      { text: { es: 'Pienso en cómo me veo. Reviso mi postura, mi ropa, mi presencia.', en: 'I think about how I look. I check my posture, clothes, presence.', fr: 'Je pense à comment j\'ai l\'air. Je vérifie ma posture, mes vêtements, ma présence.', de: 'Ich denke daran, wie ich aussehe. Ich überprüfe meine Haltung, meine Kleidung, meine Präsenz.', it: 'Penso a come appaio. Controllo la mia postura, i vestiti, la presenza.', pt: 'Penso em como pareço. Verifico minha postura, roupas, presença.' }, dimension: 'A' },
      { text: { es: 'La escena tiene una estética concreta. El clima, la luz, la música crean un momento.', en: 'The scene has a specific aesthetic. Weather, light, music create a moment.', fr: 'La scène a une esthétique concrète. Le temps, la lumière, la musique créent un moment.', de: 'Die Szene hat eine konkrete Ästhetik. Wetter, Licht, Musik schaffen einen Moment.', it: 'La scena ha un\'estetica concreta. Il clima, la luce, la musica creano un momento.', pt: 'A cena tem uma estética concreta. O clima, a luz, a música criam um momento.' }, dimension: 'N' },
      { text: { es: 'Nada en particular. Escucho música y camino. Es lo que es.', en: 'Nothing in particular. I listen to music and walk. It is what it is.', fr: 'Rien de particulier. J\'écoute de la musique et je marche. C\'est ce que c\'est.', de: 'Nichts Besonderes. Ich höre Musik und gehe. Es ist wie es ist.', it: 'Niente di particolare. Ascolto musica e cammino. È quello che è.', pt: 'Nada em particular. Ouço música e caminho. É o que é.' }, dimension: 'I' },
    ] },
    { id: 2, situation: { es: 'Algo sale mal en un día normal. ¿Cómo lo internalizas?', en: 'Something goes wrong on a normal day. How do you internalize it?', fr: 'Quelque chose se passe mal un jour normal. Comment l\'intériorises-tu ?', de: 'An einem normalen Tag geht etwas schief. Wie verinnerlichst du das?', it: 'Qualcosa va storto in un giorno normale. Come lo interiorializzi?', pt: 'Algo dá errado em um dia normal. Como você internaliza isso?' }, options: [
      { text: { es: 'Es un giro argumental. Todo lo que pasa forma parte de mi historia.', en: 'It\'s a plot twist. Everything that happens is part of my story.', fr: 'C\'est un rebondissement. Tout ce qui se passe fait partie de mon histoire.', de: 'Es ist eine Wendung. Alles, was passiert, ist Teil meiner Geschichte.', it: 'È un colpo di scena. Tutto quello che succede fa parte della mia storia.', pt: 'É uma reviravolta. Tudo que acontece faz parte da minha história.' }, dimension: 'N' },
      { text: { es: 'Lo noto y lo proceso. ¿Qué dice esto sobre mí y cómo quiero responder?', en: 'I notice and process it. What does this say about me and how do I want to respond?', fr: 'Je le remarque et le traite. Qu\'est-ce que ça dit de moi et comment est-ce que je veux y répondre ?', de: 'Ich bemerke es und verarbeite es. Was sagt das über mich und wie möchte ich reagieren?', it: 'Lo noto e lo elaboro. Cosa dice di me e come voglio rispondere?', pt: 'Noto e processo. O que isso diz sobre mim e como quero responder?' }, dimension: 'A' },
      { text: { es: 'Decido conscientemente que no va a arruinar mi día. Es una elección.', en: 'I consciously decide it won\'t ruin my day. It\'s a choice.', fr: 'Je décide consciemment que ça ne gâchera pas ma journée. C\'est un choix.', de: 'Ich entscheide bewusst, dass es meinen Tag nicht ruinieren wird. Es ist eine Entscheidung.', it: 'Decido consapevolmente che non rovinerà la mia giornata. È una scelta.', pt: 'Decido conscientemente que não vai arruinar meu dia. É uma escolha.' }, dimension: 'I' },
      { text: { es: 'Me afecta. Le cuento a alguien lo que pasó para ver cómo reacciona.', en: 'It affects me. I tell someone what happened to see how they react.', fr: 'Ça m\'affecte. Je raconte à quelqu\'un ce qui s\'est passé pour voir comment il/elle réagit.', de: 'Es betrifft mich. Ich erzähle jemandem, was passiert ist, um zu sehen, wie er/sie reagiert.', it: 'Mi colpisce. Racconto a qualcuno quello che è successo per vedere come reagisce.', pt: 'Me afeta. Conto para alguém o que aconteceu para ver como reage.' }, dimension: 'P' },
    ] },
    { id: 3, situation: { es: '¿Cómo describes tu vida cuando alguien te pregunta cómo estás?', en: 'How do you describe your life when someone asks how you are?', fr: 'Comment décris-tu ta vie quand quelqu\'un te demande comment tu vas ?', de: 'Wie beschreibst du dein Leben, wenn jemand fragt, wie es dir geht?', it: 'Come descrivi la tua vita quando qualcuno ti chiede come stai?', pt: 'Como você descreve sua vida quando alguém pergunta como você está?' }, options: [
      { text: { es: 'Con narrativa y arco. Hay un antes, un ahora y hacia dónde voy.', en: 'With narrative and arc. There\'s a before, a now, and where I\'m going.', fr: 'Avec une narration et un arc. Il y a un avant, un maintenant et vers où je vais.', de: 'Mit Narrativ und Bogen. Es gibt ein Davor, ein Jetzt und wohin ich gehe.', it: 'Con narrativa e arco. C\'è un prima, un adesso e dove sto andando.', pt: 'Com narrativa e arco. Há um antes, um agora e para onde estou indo.' }, dimension: 'N' },
      { text: { es: 'Con conciencia de lo que estoy viviendo y por qué.', en: 'With awareness of what I\'m experiencing and why.', fr: 'Avec conscience de ce que je vis et pourquoi.', de: 'Mit Bewusstsein dafür, was ich erlebe und warum.', it: 'Con consapevolezza di quello che sto vivendo e perché.', pt: 'Com consciência do que estou vivendo e por quê.' }, dimension: 'A' },
      { text: { es: 'Con intención. Sé lo que estoy construyendo y por qué lo estoy haciendo.', en: 'With intention. I know what I\'m building and why I\'m doing it.', fr: 'Avec intention. Je sais ce que je construis et pourquoi je le fais.', de: 'Mit Absicht. Ich weiß, was ich aufbaue und warum ich es tue.', it: 'Con intenzione. So cosa sto costruendo e perché lo sto facendo.', pt: 'Com intenção. Sei o que estou construindo e por que estou fazendo isso.' }, dimension: 'I' },
      { text: { es: '"Bien", "bien", "todo bien". No tengo muchas ganas de hablar de eso.', en: '"Good", "good", "all good". I don\'t really feel like talking about it.', fr: '"Bien", "bien", "tout va bien". Je n\'ai pas vraiment envie d\'en parler.', de: '"Gut", "gut", "alles gut". Ich habe keine große Lust, darüber zu reden.', it: '"Bene", "bene", "tutto bene". Non ho molta voglia di parlarne.', pt: '"Bem", "bem", "tudo bem". Não tenho muito vontade de falar sobre isso.' }, dimension: 'P' },
    ] },
    { id: 4, situation: { es: 'Estás en una situación social incómoda. ¿Cómo la navegas?', en: 'You\'re in an uncomfortable social situation. How do you navigate it?', fr: 'Tu es dans une situation sociale inconfortable. Comment la navigues-tu ?', de: 'Du befindest dich in einer unangenehmen sozialen Situation. Wie navigierst du sie?', it: 'Sei in una situazione sociale scomoda. Come la navighi?', pt: 'Você está em uma situação social desconfortável. Como você a navega?' }, options: [
      { text: { es: 'Asumo el rol de protagonista. Convierto la incomodidad en algo memorable.', en: 'I take the protagonist role. I turn the discomfort into something memorable.', fr: 'Je prends le rôle de protagoniste. Je transforme l\'inconfort en quelque chose de mémorable.', de: 'Ich übernehme die Protagonistenrolle. Ich verwandle das Unbehagen in etwas Unvergessliches.', it: 'Assumo il ruolo del protagonista. Trasformo il disagio in qualcosa di memorabile.', pt: 'Assumo o papel de protagonista. Transformo o desconforto em algo memorável.' }, dimension: 'P' },
      { text: { es: 'La observo. ¿Por qué me incomoda? ¿Qué dice eso de mí?', en: 'I observe it. Why does it make me uncomfortable? What does that say about me?', fr: 'Je l\'observe. Pourquoi est-ce que ça m\'incommode ? Qu\'est-ce que ça dit de moi ?', de: 'Ich beobachte sie. Warum macht sie mich unwohl? Was sagt das über mich aus?', it: 'La osservo. Perché mi mette a disagio? Cosa dice di me?', pt: 'Observo. Por que me incomoda? O que isso diz sobre mim?' }, dimension: 'A' },
      { text: { es: 'La reformulo como parte de la historia que me estoy contando sobre este período.', en: 'I reframe it as part of the story I\'m telling myself about this period.', fr: 'Je la recadre comme une partie de l\'histoire que je me raconte sur cette période.', de: 'Ich rahme sie um als Teil der Geschichte, die ich mir über diese Zeit erzähle.', it: 'La reframo come parte della storia che mi racconto su questo periodo.', pt: 'Reformulo como parte da história que me conto sobre este período.' }, dimension: 'N' },
      { text: { es: 'La aguanto. No hay mucho más que hacer en esos momentos.', en: 'I endure it. There\'s not much else to do in those moments.', fr: 'Je l\'endure. Il n\'y a pas grand-chose d\'autre à faire dans ces moments-là.', de: 'Ich ertrage sie. Es gibt in diesen Momenten nicht viel anderes zu tun.', it: 'La sopporto. Non c\'è molto altro da fare in quei momenti.', pt: 'Aguento. Não há muito mais a fazer nesses momentos.' }, dimension: 'I' },
    ] },
    { id: 5, situation: { es: '¿Cómo vives los cambios grandes en tu vida?', en: 'How do you experience major changes in your life?', fr: 'Comment vis-tu les grands changements dans ta vie ?', de: 'Wie erlebst du große Veränderungen in deinem Leben?', it: 'Come vivi i grandi cambiamenti nella tua vita?', pt: 'Como você vive as grandes mudanças na sua vida?' }, options: [
      { text: { es: 'Como capítulos. Cada etapa tiene su propio tono y personaje.', en: 'As chapters. Each phase has its own tone and character.', fr: 'Comme des chapitres. Chaque étape a son propre ton et personnage.', de: 'Als Kapitel. Jede Phase hat ihren eigenen Ton und Charakter.', it: 'Come capitoli. Ogni fase ha il suo tono e personaggio.', pt: 'Como capítulos. Cada fase tem seu próprio tom e personagem.' }, dimension: 'N' },
      { text: { es: 'Con mucha conciencia de lo que estoy perdiendo y ganando.', en: 'With much awareness of what I\'m losing and gaining.', fr: 'Avec beaucoup de conscience de ce que je perds et gagne.', de: 'Mit viel Bewusstsein dafür, was ich verliere und gewinne.', it: 'Con molta consapevolezza di quello che sto perdendo e guadagnando.', pt: 'Com muita consciência do que estou perdendo e ganhando.' }, dimension: 'A' },
      { text: { es: 'Como oportunidades de rediseño. Puedo elegir quién quiero ser en esta etapa.', en: 'As redesign opportunities. I can choose who I want to be in this phase.', fr: 'Comme des opportunités de redéfinition. Je peux choisir qui je veux être dans cette étape.', de: 'Als Neugestaltungsmöglichkeiten. Ich kann wählen, wer ich in dieser Phase sein möchte.', it: 'Come opportunità di ridisegno. Posso scegliere chi voglio essere in questa fase.', pt: 'Como oportunidades de redesenho. Posso escolher quem quero ser nesta fase.' }, dimension: 'I' },
      { text: { es: 'Con resistencia primero. Me cuesta adaptarme a los cambios que no elegí.', en: 'With resistance first. I struggle to adapt to changes I didn\'t choose.', fr: 'Avec résistance d\'abord. J\'ai du mal à m\'adapter aux changements que je n\'ai pas choisis.', de: 'Zuerst mit Widerstand. Ich finde es schwer, mich an Veränderungen anzupassen, die ich nicht gewählt habe.', it: 'Prima con resistenza. Faccio fatica ad adattarmi ai cambiamenti che non ho scelto.', pt: 'Com resistência primeiro. Me custa adaptar-me a mudanças que não escolhi.' }, dimension: 'P' },
    ] },
    { id: 6, situation: { es: 'Alguien que conoces logra algo que tú también quieres. ¿Cómo lo procesas?', en: 'Someone you know achieves something you also want. How do you process it?', fr: 'Quelqu\'un que tu connais réalise quelque chose que toi aussi tu veux. Comment le traites-tu ?', de: 'Jemand, den du kennst, erreicht etwas, das du auch willst. Wie verarbeitest du das?', it: 'Qualcuno che conosci realizza qualcosa che vuoi anche tu. Come lo elabori?', pt: 'Alguém que você conhece consegue algo que você também quer. Como você processa isso?' }, options: [
      { text: { es: 'Es inspiración. Si él/ella puede, yo también puedo. Forma parte de mi historia.', en: 'It\'s inspiration. If they can, I can too. It\'s part of my story.', fr: 'C\'est de l\'inspiration. Si il/elle peut, je peux aussi. Ça fait partie de mon histoire.', de: 'Es ist Inspiration. Wenn er/sie kann, kann ich auch. Es ist Teil meiner Geschichte.', it: 'È ispirazione. Se lui/lei può, posso anch\'io. Fa parte della mia storia.', pt: 'É inspiração. Se ele/ela pode, eu também posso. Faz parte da minha história.' }, dimension: 'N' },
      { text: { es: 'Lo proceso con honestidad. Hay algo de envidia y algo de motivación. Ambos son válidos.', en: 'I process it honestly. There\'s some envy and some motivation. Both are valid.', fr: 'Je le traite honnêtement. Il y a de l\'envie et de la motivation. Les deux sont valides.', de: 'Ich verarbeite es ehrlich. Es gibt etwas Neid und etwas Motivation. Beides ist gültig.', it: 'Lo elaboro onestamente. C\'è un po\' d\'invidia e un po\' di motivazione. Entrambi sono validi.', pt: 'Processo com honestidade. Há algo de inveja e algo de motivação. Ambos são válidos.' }, dimension: 'A' },
      { text: { es: 'Uso esa información para recalibrar si estoy yendo hacia donde realmente quiero ir.', en: 'I use that information to recalibrate whether I\'m going where I really want to go.', fr: 'J\'utilise cette information pour recalibrer si je vais là où je veux vraiment aller.', de: 'Ich nutze diese Information, um neu zu kalibrieren, ob ich dahin gehe, wo ich wirklich hin will.', it: 'Uso quella informazione per ricalibrarmi se sto andando dove voglio davvero andare.', pt: 'Uso essa informação para recalibrar se estou indo para onde realmente quero ir.' }, dimension: 'I' },
      { text: { es: 'Me genera un poco de ruido. Luego sigo con lo mío.', en: 'It creates some noise for me. Then I continue with my own things.', fr: 'Ça me crée un peu de bruit. Ensuite, je continue avec mes propres choses.', de: 'Es erzeugt etwas Lärm für mich. Dann mache ich mit meinen eigenen Dingen weiter.', it: 'Mi crea un po\' di rumore. Poi continuo con le mie cose.', pt: 'Me gera um pouco de ruído. Depois sigo com o que é meu.' }, dimension: 'P' },
    ] },
    { id: 7, situation: { es: '¿Cómo describes tu relación con el futuro?', en: 'How do you describe your relationship with the future?', fr: 'Comment décris-tu ta relation avec l\'avenir ?', de: 'Wie beschreibst du deine Beziehung zur Zukunft?', it: 'Come descrivi la tua relazione con il futuro?', pt: 'Como você descreve sua relação com o futuro?' }, options: [
      { text: { es: 'Es el siguiente capítulo que todavía no sé cómo va a terminar. Lo espero con expectativa.', en: 'It\'s the next chapter I don\'t yet know how it\'ll end. I await it with anticipation.', fr: 'C\'est le prochain chapitre dont je ne sais pas encore comment il va se terminer. Je l\'attends avec impatience.', de: 'Es ist das nächste Kapitel, von dem ich noch nicht weiß, wie es enden wird. Ich erwarte es mit Vorfreude.', it: 'È il prossimo capitolo che non so ancora come finirà. Lo aspetto con aspettativa.', pt: 'É o próximo capítulo que ainda não sei como vai terminar. O espero com expectativa.' }, dimension: 'N' },
      { text: { es: 'Una dirección más que un destino. Sé hacia dónde voy aunque no sé exactamente dónde llegaré.', en: 'A direction more than a destination. I know where I\'m headed though I don\'t know exactly where I\'ll arrive.', fr: 'Une direction plutôt qu\'une destination. Je sais vers où je vais même si je ne sais pas exactement où j\'arriverai.', de: 'Eine Richtung mehr als ein Ziel. Ich weiß, wohin ich gehe, auch wenn ich nicht genau weiß, wo ich ankommen werde.', it: 'Una direzione più che una destinazione. So dove sto andando anche se non so esattamente dove arriverò.', pt: 'Uma direção mais que um destino. Sei para onde estou indo embora não saiba exatamente onde chegarei.' }, dimension: 'I' },
      { text: { es: 'Algo que construyo con conciencia. Entiendo mis patrones y elijo cuáles quiero repetir.', en: 'Something I build consciously. I understand my patterns and choose which I want to repeat.', fr: 'Quelque chose que je construis avec conscience. Je comprends mes schémas et choisis lesquels je veux répéter.', de: 'Etwas, das ich bewusst aufbaue. Ich verstehe meine Muster und wähle, welche ich wiederholen möchte.', it: 'Qualcosa che costruisco con consapevolezza. Capisco i miei schemi e scelgo quali voglio ripetere.', pt: 'Algo que construo com consciência. Entendo meus padrões e escolho quais quero repetir.' }, dimension: 'A' },
      { text: { es: 'Una incógnita. Vivo más en el presente que pensando en lo que viene.', en: 'An unknown. I live more in the present than thinking about what\'s coming.', fr: 'Une inconnue. Je vis plus dans le présent qu\'en pensant à ce qui vient.', de: 'Eine Unbekannte. Ich lebe mehr in der Gegenwart als an die Zukunft zu denken.', it: 'Un\'incognita. Vivo più nel presente che pensando a quello che verrà.', pt: 'Uma incógnita. Vivo mais no presente do que pensando no que vem.' }, dimension: 'P' },
    ] },
    { id: 8, situation: { es: '¿Cómo te relacionas con las cosas que no salieron como esperabas?', en: 'How do you relate to things that didn\'t go as expected?', fr: 'Comment te relates-tu aux choses qui ne se sont pas passées comme prévu ?', de: 'Wie gehst du mit Dingen um, die nicht so gelaufen sind, wie du es erwartet hattest?', it: 'Come ti relaziona con le cose che non sono andate come ti aspettavi?', pt: 'Como você se relaciona com as coisas que não saíram como esperava?' }, options: [
      { text: { es: 'Los "fracasos" son los capítulos más importantes de cualquier historia buena.', en: 'Failures are the most important chapters of any good story.', fr: 'Les "échecs" sont les chapitres les plus importants de toute bonne histoire.', de: '"Misserfolge" sind die wichtigsten Kapitel jeder guten Geschichte.', it: 'I "fallimenti" sono i capitoli più importanti di qualsiasi buona storia.', pt: 'Os "fracassos" são os capítulos mais importantes de qualquer boa história.' }, dimension: 'N' },
      { text: { es: 'Los analizo. ¿Qué hice mal? ¿Qué hice bien? ¿Qué haría diferente?', en: 'I analyze them. What did I do wrong? What did I do right? What would I do differently?', fr: 'Je les analyse. Qu\'est-ce que j\'ai mal fait ? Qu\'est-ce que j\'ai bien fait ? Qu\'est-ce que je ferais différemment ?', de: 'Ich analysiere sie. Was habe ich falsch gemacht? Was habe ich richtig gemacht? Was würde ich anders machen?', it: 'Li analizzo. Cosa ho fatto di sbagliato? Cosa ho fatto bene? Cosa farei di diverso?', pt: 'Analiso. O que fiz errado? O que fiz certo? O que faria diferente?' }, dimension: 'A' },
      { text: { es: 'Los uso para recalibrar. La dirección importa más que los resultados individuales.', en: 'I use them to recalibrate. Direction matters more than individual results.', fr: 'Je les utilise pour recalibrer. La direction importe plus que les résultats individuels.', de: 'Ich nutze sie zum Rekalibrieren. Die Richtung ist wichtiger als einzelne Ergebnisse.', it: 'Li uso per ricalibrarmi. La direzione conta più dei risultati individuali.', pt: 'Uso para recalibrar. A direção importa mais que os resultados individuais.' }, dimension: 'I' },
      { text: { es: 'Me cuesta soltar lo que no salió. Pienso en ello más de lo que quisiera.', en: 'I struggle to let go of what didn\'t work. I think about it more than I\'d like.', fr: 'J\'ai du mal à lâcher ce qui n\'a pas marché. J\'y pense plus que je ne le voudrais.', de: 'Ich finde es schwer, das loszulassen, was nicht funktioniert hat. Ich denke mehr darüber nach, als ich möchte.', it: 'Faccio fatica a lasciar andare quello che non è andato. Ci penso più di quanto vorrei.', pt: 'Me custa soltar o que não saiu. Penso nisso mais do que gostaria.' }, dimension: 'P' },
    ] },
    { id: 9, situation: { es: 'Un día perfecto para ti luce así:', en: 'A perfect day for you looks like this:', fr: 'Une journée parfaite pour toi ressemble à ceci :', de: 'Ein perfekter Tag für dich sieht so aus:', it: 'Una giornata perfetta per te assomiglia a questa:', pt: 'Um dia perfeito para você é assim:' }, options: [
      { text: { es: 'Algo que valga la pena contar. Una experiencia, un encuentro, un momento cinematográfico.', en: 'Something worth telling. An experience, an encounter, a cinematic moment.', fr: 'Quelque chose qui vaut la peine d\'être raconté. Une expérience, une rencontre, un moment cinématographique.', de: 'Etwas, das es wert ist, erzählt zu werden. Eine Erfahrung, eine Begegnung, ein filmischer Moment.', it: 'Qualcosa che valga la pena raccontare. Un\'esperienza, un incontro, un momento cinematografico.', pt: 'Algo que valha a pena contar. Uma experiência, um encontro, um momento cinematográfico.' }, dimension: 'N' },
      { text: { es: 'Tiempo para entender cómo estoy y qué necesito.', en: 'Time to understand how I\'m doing and what I need.', fr: 'Du temps pour comprendre comment je vais et ce dont j\'ai besoin.', de: 'Zeit zu verstehen, wie es mir geht und was ich brauche.', it: 'Tempo per capire come sto e di cosa ho bisogno.', pt: 'Tempo para entender como estou e o que preciso.' }, dimension: 'A' },
      { text: { es: 'Avanzar conscientemente en lo que más me importa.', en: 'Consciously advance in what matters most to me.', fr: 'Avancer consciemment dans ce qui m\'importe le plus.', de: 'Bewusst in dem vorankommen, was mir am meisten wichtig ist.', it: 'Avanzare consapevolmente in quello che mi importa di più.', pt: 'Avançar conscientemente no que mais me importa.' }, dimension: 'I' },
      { text: { es: 'Un día sin presión donde pueda hacer lo que me surja.', en: 'A pressure-free day where I can do what comes naturally.', fr: 'Une journée sans pression où je peux faire ce qui me vient.', de: 'Ein druckfreier Tag, an dem ich tun kann, was sich ergibt.', it: 'Una giornata senza pressione dove posso fare quello che mi viene.', pt: 'Um dia sem pressão onde posso fazer o que surgir.' }, dimension: 'P' },
    ] },
    { id: 10, situation: { es: '¿Cómo describes tu relación con tu propia historia?', en: 'How do you describe your relationship with your own story?', fr: 'Comment décris-tu ta relation avec ta propre histoire ?', de: 'Wie beschreibst du deine Beziehung zu deiner eigenen Geschichte?', it: 'Come descrivi la tua relazione con la tua storia?', pt: 'Como você descreve sua relação com sua própria história?' }, options: [
      { text: { es: 'La narro. Sé en qué parte estoy y hacia dónde va el arco.', en: 'I narrate it. I know what part I\'m in and where the arc is going.', fr: 'Je la narre. Je sais dans quelle partie je me trouve et vers où va l\'arc.', de: 'Ich erzähle sie. Ich weiß, in welchem Teil ich bin und wohin der Bogen geht.', it: 'La racconto. So in quale parte mi trovo e dove sta andando l\'arco.', pt: 'Eu a narro. Sei em que parte estou e para onde vai o arco.' }, dimension: 'N' },
      { text: { es: 'La entiendo. Sé por qué estoy donde estoy y qué patrones me trajeron aquí.', en: 'I understand it. I know why I\'m where I am and what patterns brought me here.', fr: 'Je la comprends. Je sais pourquoi je suis là où je suis et quels schémas m\'y ont amené.', de: 'Ich verstehe sie. Ich weiß, warum ich dort bin, wo ich bin, und welche Muster mich hierher gebracht haben.', it: 'La capisco. So perché sono dove sono e quali schemi mi hanno portato qui.', pt: 'Entendo. Sei por que estou onde estou e quais padrões me trouxeram até aqui.' }, dimension: 'A' },
      { text: { es: 'La escribo activamente. No espero que las cosas pasen — las construyo.', en: 'I write it actively. I don\'t wait for things to happen — I build them.', fr: 'Je l\'écris activement. Je n\'attends pas que les choses se passent — je les construis.', de: 'Ich schreibe sie aktiv. Ich warte nicht darauf, dass Dinge passieren — ich baue sie.', it: 'La scrivo attivamente. Non aspetto che le cose accadano — le costruisco.', pt: 'A escrevo ativamente. Não espero que as coisas aconteçam — as construo.' }, dimension: 'I' },
      { text: { es: 'La vivo. No pienso tanto en ella como experiencia que se está narrando.', en: 'I live it. I don\'t think as much about it as an experience that\'s being narrated.', fr: 'Je la vis. Je n\'y pense pas autant comme une expérience qui est en train d\'être narrée.', de: 'Ich erlebe sie. Ich denke nicht so viel darüber nach als Erlebnis, das gerade erzählt wird.', it: 'La vivo. Non ci penso tanto come esperienza che si sta narrando.', pt: 'A vivo. Não penso tanto nela como uma experiência que está sendo narrada.' }, dimension: 'P' },
    ] },
  ],
  characters: [
    { name: { es: 'El Protagonista Narrativo', en: 'The Narrative Protagonist', fr: 'Le Protagoniste Narratif', de: 'Der Narrative Protagonist', it: 'Il Protagonista Narrativo', pt: 'O Protagonista Narrativo' }, dimensions: ['N'], photo: '/characters/narrative.jpg', description: { es: 'Vive su vida como una historia con arco, capítulos y propósito.', en: 'Lives their life like a story with arc, chapters, and purpose.', fr: 'Vit sa vie comme une histoire avec un arc, des chapitres et un but.', de: 'Lebt sein/ihr Leben wie eine Geschichte mit Bogen, Kapiteln und Zweck.', it: 'Vive la sua vita come una storia con arco, capitoli e scopo.', pt: 'Vive sua vida como uma história com arco, capítulos e propósito.' }, philosophy: { es: 'Tu vida no es una serie de eventos aleatorios — es una narrativa que estás escribiendo. Eso te da un poder enorme: puedes elegir cómo enmarcar lo que vives y qué papel juegas en ello.', en: 'Your life isn\'t a series of random events — it\'s a narrative you\'re writing. That gives you immense power: you can choose how to frame what you live and what role you play in it.', fr: 'Ta vie n\'est pas une série d\'événements aléatoires — c\'est une narration que tu écris. Ça te donne un pouvoir énorme : tu peux choisir comment encadrer ce que tu vis et quel rôle tu joues.', de: 'Dein Leben ist keine Reihe zufälliger Ereignisse — es ist eine Erzählung, die du schreibst. Das gibt dir eine enorme Macht: Du kannst wählen, wie du das Erlebte rahmst und welche Rolle du darin spielst.', it: 'La tua vita non è una serie di eventi casuali — è una narrativa che stai scrivendo. Questo ti dà un enorme potere: puoi scegliere come inquadrare quello che vivi e quale ruolo giochi in esso.', pt: 'Sua vida não é uma série de eventos aleatórios — é uma narrativa que você está escrevendo. Isso te dá um enorme poder: você pode escolher como enquadrar o que vive e que papel desempenha nela.' } },
    { name: { es: 'El Autoconsciente', en: 'The Self-Aware', fr: 'Le Conscient de Soi', de: 'Der Selbstbewusste', it: 'L\'Autoconsapevole', pt: 'O Autoconsciente' }, dimensions: ['A'], photo: '/characters/self-aware.jpg', description: { es: 'Entiende sus patrones, sus motivaciones y sus puntos ciegos.', en: 'Understands their patterns, motivations, and blind spots.', fr: 'Comprend ses schémas, motivations et angles morts.', de: 'Versteht seine Muster, Motivationen und blinden Flecken.', it: 'Capisce i propri schemi, motivazioni e punti ciechi.', pt: 'Entende seus padrões, motivações e pontos cegos.' }, philosophy: { es: 'Tu superpotencia es verte con claridad. No te sorprendes de tus propias reacciones porque las entiendes. Eso no significa que seas perfecto/a — significa que puedes trabajar con lo que eres en lugar de luchar contra ello.', en: 'Your superpower is seeing yourself clearly. You\'re not surprised by your own reactions because you understand them. That doesn\'t mean you\'re perfect — it means you can work with what you are instead of fighting it.', fr: 'Ton superpouvoir est de te voir clairement. Tu n\'es pas surpris(e) par tes propres réactions parce que tu les comprends. Ça ne veut pas dire que tu es parfait(e) — ça veut dire que tu peux travailler avec ce que tu es plutôt que de le combattre.', de: 'Deine Superkraft ist es, dich klar zu sehen. Du bist nicht von deinen eigenen Reaktionen überrascht, weil du sie verstehst. Das bedeutet nicht, dass du perfekt bist — es bedeutet, dass du mit dem arbeiten kannst, was du bist, anstatt dagegen zu kämpfen.', it: 'Il tuo superpotere è vederti chiaramente. Non sei sorpreso/a dalle tue stesse reazioni perché le capisci. Questo non significa che sei perfetto/a — significa che puoi lavorare con quello che sei invece di combatterlo.', pt: 'Seu superpoder é ver-se com clareza. Você não se surpreende com suas próprias reações porque as entende. Isso não significa que você seja perfeito/a — significa que pode trabalhar com o que é em vez de lutar contra isso.' } },
    { name: { es: 'El Intencional', en: 'The Intentional', fr: 'L\'Intentionnel', de: 'Der Intentionale', it: 'L\'Intenzionale', pt: 'O Intencional' }, dimensions: ['I'], photo: '/characters/intentional.jpg', description: { es: 'Vive con propósito. Sus decisiones son conscientes, no reactivas.', en: 'Lives with purpose. Their decisions are conscious, not reactive.', fr: 'Vit avec un but. Ses décisions sont conscientes, pas réactives.', de: 'Lebt mit Zweck. Seine Entscheidungen sind bewusst, nicht reaktiv.', it: 'Vive con scopo. Le sue decisioni sono consapevoli, non reattive.', pt: 'Vive com propósito. Suas decisões são conscientes, não reativas.' }, philosophy: { es: 'No dejas que la vida simplemente te pase. Tomas decisiones con consciencia de lo que estás construyendo. Eso no significa que todo esté controlado — significa que sabes por qué haces lo que haces.', en: 'You don\'t let life simply happen to you. You make decisions with consciousness of what you\'re building. That doesn\'t mean everything is controlled — it means you know why you do what you do.', fr: 'Tu ne laisses pas simplement la vie se passer. Tu prends des décisions en conscience de ce que tu construis. Ça ne veut pas dire que tout est contrôlé — ça veut dire que tu sais pourquoi tu fais ce que tu fais.', de: 'Du lässt das Leben nicht einfach über dich ergehen. Du triffst Entscheidungen mit dem Bewusstsein dessen, was du aufbaust. Das bedeutet nicht, dass alles kontrolliert ist — es bedeutet, dass du weißt, warum du tust, was du tust.', it: 'Non lasci che la vita ti accada semplicemente. Prendi decisioni con consapevolezza di quello che stai costruendo. Questo non significa che tutto sia controllato — significa che sai perché fai quello che fai.', pt: 'Você não deixa a vida simplesmente acontecer com você. Toma decisões com consciência do que está construindo. Isso não significa que tudo está controlado — significa que você sabe por que faz o que faz.' } },
    { name: { es: 'El Protagonista Total', en: 'The Total Protagonist', fr: 'Le Protagoniste Total', de: 'Der Totale Protagonist', it: 'Il Protagonista Totale', pt: 'O Protagonista Total' }, dimensions: ['N', 'A', 'I'], photo: '/characters/total-protagonist.jpg', description: { es: 'Narra su historia, se entiende a sí mismo/a y vive con propósito. El paquete completo.', en: 'Narrates their story, understands themselves, and lives with purpose. The complete package.', fr: 'Narre son histoire, se comprend lui/elle-même et vit avec un but. Le package complet.', de: 'Erzählt seine Geschichte, versteht sich selbst und lebt mit Zweck. Das komplette Paket.', it: 'Racconta la sua storia, capisce se stesso/a e vive con scopo. Il pacchetto completo.', pt: 'Narra sua história, entende a si mesmo/a e vive com propósito. O pacote completo.' }, philosophy: { es: 'Tienes las tres cosas que hacen a alguien verdaderamente protagonista de su vida: entiendes tu historia, te entiendes a ti mismo/a, y vives con intención. Eso no significa que tengas todo resuelto — significa que estás en el asiento del conductor.', en: 'You have the three things that make someone truly the protagonist of their life: you understand your story, understand yourself, and live with intention. That doesn\'t mean you have everything figured out — it means you\'re in the driver\'s seat.', fr: 'Tu as les trois choses qui font de quelqu\'un vraiment le protagoniste de sa vie : tu comprends ton histoire, tu te comprends toi-même, et tu vis avec intention. Ça ne veut pas dire que tu as tout résolu — ça veut dire que tu es dans le siège du conducteur.', de: 'Du hast die drei Dinge, die jemanden wirklich zum Protagonisten seines Lebens machen: Du verstehst deine Geschichte, verstehst dich selbst und lebst mit Absicht. Das bedeutet nicht, dass du alles gelöst hast — es bedeutet, dass du am Steuer sitzt.', it: 'Hai le tre cose che rendono qualcuno davvero protagonista della propria vita: capisci la tua storia, capisci te stesso/a e vivi con intenzione. Questo non significa che hai tutto risolto — significa che sei al volante.', pt: 'Você tem as três coisas que tornam alguém verdadeiramente protagonista da própria vida: entende sua história, entende a si mesmo/a e vive com intenção. Isso não significa que tem tudo resolvido — significa que está no assento do motorista.' } },
  ],
};

export async function seedMainCharacter(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'main-character' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'main-character',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['lifestyle'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
