import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Qué tipo social eres?', en: 'What social type are you?', fr: 'Quel type social es-tu ?', de: 'Welcher Sozialtyp bist du?', it: 'Che tipo sociale sei?', pt: 'Que tipo social você é?' },
  description: { es: 'Introvertido/a, extrovertido/a, o algo más complejo. Descubre tu verdadero estilo social.', en: 'Introverted, extroverted, or something more complex. Discover your true social style.', fr: 'Introverti(e), extraverti(e), ou quelque chose de plus complexe. Découvre ton véritable style social.', de: 'Introvertiert, extrovertiert oder etwas Komplexeres. Entdecke deinen wahren sozialen Stil.', it: 'Introverso/a, estroverso/a, o qualcosa di più complesso. Scopri il tuo vero stile sociale.', pt: 'Introvertido/a, extrovertido/a, ou algo mais complexo. Descubra seu verdadeiro estilo social.' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { E: 'Extroversión', I: 'Introversión', S: 'Selectividad', C: 'Carisma' },
    en: { E: 'Extroversion', I: 'Introversion', S: 'Selectivity', C: 'Charisma' },
    fr: { E: 'Extraversion', I: 'Introversion', S: 'Sélectivité', C: 'Charisme' },
    de: { E: 'Extraversion', I: 'Introversion', S: 'Selektivität', C: 'Charisma' },
    it: { E: 'Estroversione', I: 'Introversione', S: 'Selettività', C: 'Carisma' },
    pt: { E: 'Extroversão', I: 'Introversão', S: 'Seletividade', C: 'Carisma' },
  },
  questions: [
    { id: 1, situation: { es: 'Tienes un fin de semana libre sin compromisos. ¿Qué es lo primero que piensas?', en: 'You have a free weekend with no commitments. What\'s the first thing you think?', fr: 'Tu as un week-end libre sans engagements. Quelle est la première chose à laquelle tu penses ?', de: 'Du hast ein freies Wochenende ohne Verpflichtungen. Was ist das Erste, woran du denkst?', it: 'Hai un fine settimana libero senza impegni. Qual è la prima cosa a cui pensi?', pt: 'Você tem um fim de semana livre sem compromissos. Qual é a primeira coisa que pensa?' }, options: [
      { text: { es: '¿Quién está disponible? Quiero hacer planes con gente.', en: 'Who\'s available? I want to make plans with people.', fr: 'Qui est disponible ? Je veux faire des plans avec des gens.', de: 'Wer ist verfügbar? Ich möchte Pläne mit Leuten machen.', it: 'Chi è disponibile? Voglio fare piani con la gente.', pt: 'Quem está disponível? Quero fazer planos com pessoas.' }, dimension: 'E' },
      { text: { es: 'Por fin tiempo para mí. Voy a leer, ver series y recargar.', en: 'Finally time for myself. I\'m going to read, watch shows, and recharge.', fr: 'Enfin du temps pour moi. Je vais lire, regarder des séries et me recharger.', de: 'Endlich Zeit für mich. Ich werde lesen, Serien schauen und aufladen.', it: 'Finalmente tempo per me. Leggo, guardo serie e ricarico.', pt: 'Finalmente tempo para mim. Vou ler, ver séries e recarregar.' }, dimension: 'I' },
      { text: { es: 'Voy a ver si alguno de mis tres amigos cercanos quiere hacer algo tranquilo.', en: 'I\'ll see if one of my three close friends wants to do something low-key.', fr: 'Je vais voir si l\'un de mes trois amis proches veut faire quelque chose de tranquille.', de: 'Ich schaue, ob einer meiner drei engen Freunde etwas Ruhiges machen möchte.', it: 'Vedo se uno dei miei tre amici stretti vuole fare qualcosa di tranquillo.', pt: 'Vou ver se algum dos meus três amigos próximos quer fazer algo tranquilo.' }, dimension: 'S' },
      { text: { es: 'Organizo algo. Tengo ganas de reunir a todo mi círculo.', en: 'I organize something. I feel like gathering my whole circle.', fr: 'J\'organise quelque chose. J\'ai envie de rassembler tout mon cercle.', de: 'Ich organisiere etwas. Ich möchte meinen ganzen Kreis zusammenbringen.', it: 'Organizzo qualcosa. Ho voglia di riunire tutto il mio cerchio.', pt: 'Organizo algo. Tenho vontade de reunir todo o meu círculo.' }, dimension: 'C' },
    ] },
    { id: 2, situation: { es: 'Te invitan a una fiesta donde solo conoces al anfitrión. ¿Cómo lo vives?', en: 'You\'re invited to a party where you only know the host. How do you experience it?', fr: 'Tu es invité(e) à une fête où tu connais seulement l\'hôte. Comment le vis-tu ?', de: 'Du bist zu einer Party eingeladen, wo du nur den Gastgeber kennst. Wie erlebst du das?', it: 'Sei invitato/a a una festa dove conosci solo l\'anfitrione. Come lo vivi?', pt: 'Você é convidado/a para uma festa onde só conhece o anfitrião. Como vive isso?' }, options: [
      { text: { es: 'Lo disfruto. Conocer gente nueva es emocionante.', en: 'I enjoy it. Meeting new people is exciting.', fr: 'Je l\'apprécie. Rencontrer de nouvelles personnes est excitant.', de: 'Ich genieße es. Neue Leute kennenzulernen ist aufregend.', it: 'Lo apprezzo. Conoscere nuove persone è emozionante.', pt: 'Curto. Conhecer gente nova é emocionante.' }, dimension: 'E' },
      { text: { es: 'Me estreso. ¿Con quién hablo? ¿Cuándo es aceptable irse?', en: 'I stress out. Who do I talk to? When is it acceptable to leave?', fr: 'Je stresse. Avec qui je parle ? Quand est-il acceptable de partir ?', de: 'Ich stresse mich. Mit wem rede ich? Wann ist es akzeptabel zu gehen?', it: 'Mi stresso. Con chi parlo? Quando è accettabile andarsene?', pt: 'Fico estressado/a. Com quem falo? Quando é aceitável ir embora?' }, dimension: 'I' },
      { text: { es: 'Evalúo si vale la pena antes de ir. Depende de qué tipo de personas habrá.', en: 'I evaluate if it\'s worth going. Depends on what type of people will be there.', fr: 'J\'évalue si ça vaut la peine avant d\'y aller. Ça dépend du type de personnes qui seront là.', de: 'Ich bewerte, ob es sich lohnt, zu gehen. Hängt davon ab, welche Art von Menschen dort sein wird.', it: 'Valuto se vale la pena prima di andarci. Dipende dal tipo di persone che ci saranno.', pt: 'Avalio se vale a pena antes de ir. Depende do tipo de pessoas que estarão lá.' }, dimension: 'S' },
      { text: { es: 'Entro, leo la sala y en 30 minutos ya soy parte del grupo central.', en: 'I walk in, read the room, and in 30 minutes I\'m already part of the central group.', fr: 'J\'entre, je lis la salle et en 30 minutes je fais déjà partie du groupe central.', de: 'Ich trete ein, lese die Situation und bin in 30 Minuten bereits Teil der zentralen Gruppe.', it: 'Entro, leggo la sala e in 30 minuti sono già parte del gruppo centrale.', pt: 'Entro, leio a sala e em 30 minutos já sou parte do grupo central.' }, dimension: 'C' },
    ] },
    { id: 3, situation: { es: 'Después de un día muy social e intenso, ¿cómo te sientes?', en: 'After a very social and intense day, how do you feel?', fr: 'Après une journée très sociale et intense, comment te sens-tu ?', de: 'Nach einem sehr sozialen und intensiven Tag, wie fühlst du dich?', it: 'Dopo una giornata molto sociale e intensa, come ti senti?', pt: 'Depois de um dia muito social e intenso, como você se sente?' }, options: [
      { text: { es: 'Energizado/a. Los días sociales me recargan las pilas.', en: 'Energized. Social days recharge my batteries.', fr: 'Énergisé(e). Les journées sociales me rechargent les piles.', de: 'Energiegeladen. Soziale Tage laden meine Batterien auf.', it: 'Energizzato/a. Le giornate sociali mi ricaricano le pile.', pt: 'Energizado/a. Os dias sociais recarregam minhas baterias.' }, dimension: 'E' },
      { text: { es: 'Agotado/a. Necesito al menos 24 horas de recuperación.', en: 'Exhausted. I need at least 24 hours of recovery.', fr: 'Épuisé(e). J\'ai besoin d\'au moins 24 heures de récupération.', de: 'Erschöpft. Ich brauche mindestens 24 Stunden Erholung.', it: 'Esausto/a. Ho bisogno di almeno 24 ore di recupero.', pt: 'Exausto/a. Preciso de pelo menos 24 horas de recuperação.' }, dimension: 'I' },
      { text: { es: 'Depende de con quién estuve. Con las personas correctas, bien. Con las incorrectas, destruido/a.', en: 'Depends on who I was with. With the right people, fine. With the wrong ones, destroyed.', fr: 'Ça dépend avec qui j\'étais. Avec les bonnes personnes, bien. Avec les mauvaises, détruit(e).', de: 'Hängt davon ab, mit wem ich war. Mit den richtigen Personen, gut. Mit den falschen, erledigt.', it: 'Dipende da con chi stavo. Con le persone giuste, bene. Con quelle sbagliate, distrutto/a.', pt: 'Depende de com quem estive. Com as pessoas certas, bem. Com as erradas, destruído/a.' }, dimension: 'S' },
      { text: { es: 'Satisfecho/a, pero también necesito un momento de silencio para procesar.', en: 'Satisfied, but I also need a moment of silence to process.', fr: 'Satisfait(e), mais j\'ai aussi besoin d\'un moment de silence pour traiter.', de: 'Zufrieden, aber ich brauche auch einen Moment der Stille, um zu verarbeiten.', it: 'Soddisfatto/a, ma ho anche bisogno di un momento di silenzio per elaborare.', pt: 'Satisfeito/a, mas também preciso de um momento de silêncio para processar.' }, dimension: 'C' },
    ] },
    { id: 4, situation: { es: 'En una reunión de trabajo, ¿cómo participas generalmente?', en: 'In a work meeting, how do you generally participate?', fr: 'Dans une réunion de travail, comment participes-tu généralement ?', de: 'In einer Arbeitsbesprechung, wie nimmst du generell teil?', it: 'In una riunione di lavoro, come partecipi generalmente?', pt: 'Em uma reunião de trabalho, como você geralmente participa?' }, options: [
      { text: { es: 'Hablo bastante. Se me ocurren ideas en tiempo real cuando interactúo.', en: 'I speak quite a bit. Ideas come to me in real time when I interact.', fr: 'Je parle beaucoup. Les idées me viennent en temps réel quand j\'interagis.', de: 'Ich spreche ziemlich viel. Ideen kommen mir in Echtzeit, wenn ich interagiere.', it: 'Parlo abbastanza. Le idee mi vengono in tempo reale quando interagisco.', pt: 'Falo bastante. As ideias me vêm em tempo real quando interajo.' }, dimension: 'E' },
      { text: { es: 'Escucho más de lo que hablo. Mis mejores ideas las tengo cuando no estoy en la reunión.', en: 'I listen more than I speak. My best ideas come when I\'m not in the meeting.', fr: 'J\'écoute plus que je ne parle. Mes meilleures idées je les ai quand je ne suis pas dans la réunion.', de: 'Ich höre mehr zu, als ich spreche. Meine besten Ideen habe ich, wenn ich nicht in der Besprechung bin.', it: 'Ascolto più di quanto parlo. Le mie migliori idee le ho quando non sono nella riunione.', pt: 'Ouço mais do que falo. Minhas melhores ideias tenho quando não estou na reunião.' }, dimension: 'I' },
      { text: { es: 'Solo hablo cuando tengo algo valioso que agregar. La calidad sobre la cantidad.', en: 'I only speak when I have something valuable to add. Quality over quantity.', fr: 'Je parle seulement quand j\'ai quelque chose de précieux à ajouter. La qualité sur la quantité.', de: 'Ich spreche nur, wenn ich etwas Wertvolles hinzuzufügen habe. Qualität über Quantität.', it: 'Parlo solo quando ho qualcosa di prezioso da aggiungere. La qualità sulla quantità.', pt: 'Falo apenas quando tenho algo valioso a acrescentar. Qualidade sobre quantidade.' }, dimension: 'S' },
      { text: { es: 'Tomo el hilo y ayudo a dirigir la conversación cuando hay caos.', en: 'I take the thread and help direct the conversation when there\'s chaos.', fr: 'Je prends le fil et aide à diriger la conversation quand il y a du chaos.', de: 'Ich nehme den Faden und helfe, das Gespräch zu lenken, wenn es Chaos gibt.', it: 'Prendo il filo e aiuto a dirigere la conversazione quando c\'è caos.', pt: 'Pego o fio e ajudo a dirigir a conversa quando há caos.' }, dimension: 'C' },
    ] },
    { id: 5, situation: { es: 'Alguien nuevo llega a tu círculo de amigos. ¿Cómo reaccionas?', en: 'Someone new arrives in your friend circle. How do you react?', fr: 'Quelqu\'un de nouveau arrive dans ton cercle d\'amis. Comment réagis-tu ?', de: 'Jemand Neues kommt in deinen Freundeskreis. Wie reagierst du?', it: 'Qualcuno di nuovo arriva nel tuo cerchio di amici. Come reagisci?', pt: 'Alguém novo chega ao seu círculo de amigos. Como você reage?' }, options: [
      { text: { es: 'Lo integro activamente. Me gusta expandir el círculo.', en: 'I actively integrate them. I like expanding the circle.', fr: 'Je l\'intègre activement. J\'aime étendre le cercle.', de: 'Ich integriere ihn/sie aktiv. Ich mag es, den Kreis zu erweitern.', it: 'Lo integro attivamente. Mi piace espandere il cerchio.', pt: 'Integro ativamente. Gosto de expandir o círculo.' }, dimension: 'E' },
      { text: { es: 'Lo observo desde lejos. Necesito tiempo para saber si me cae bien.', en: 'I observe from afar. I need time to know if I like them.', fr: 'Je l\'observe de loin. J\'ai besoin de temps pour savoir si il/elle me plaît.', de: 'Ich beobachte aus der Ferne. Ich brauche Zeit, um zu wissen, ob ich ihn/sie mag.', it: 'Lo osservo da lontano. Ho bisogno di tempo per sapere se mi piace.', pt: 'Observo de longe. Preciso de tempo para saber se gosto.' }, dimension: 'I' },
      { text: { es: 'Lo evalúo discretamente. No todo el mundo encaja y eso está bien.', en: 'I evaluate them discreetly. Not everyone fits and that\'s fine.', fr: 'Je l\'évalue discrètement. Tout le monde ne s\'intègre pas et c\'est bien ainsi.', de: 'Ich bewerte ihn/sie diskret. Nicht jeder passt dazu und das ist in Ordnung.', it: 'Lo valuto discretamente. Non tutti si adattano e va bene così.', pt: 'Avalio discretamente. Nem todo mundo encaixa e tudo bem.' }, dimension: 'S' },
      { text: { es: 'Me presento y le cuento el contexto del grupo. Le doy la bienvenida.', en: 'I introduce myself and tell them the group context. I welcome them.', fr: 'Je me présente et lui explique le contexte du groupe. Je lui souhaite la bienvenue.', de: 'Ich stelle mich vor und erkläre ihm/ihr den Gruppenkontext. Ich heiße ihn/sie willkommen.', it: 'Mi presento e gli racconto il contesto del gruppo. Lo accolgo.', pt: 'Me apresento e conto o contexto do grupo. Dou-lhe as boas-vindas.' }, dimension: 'C' },
    ] },
    { id: 6, situation: { es: 'Tienes que hablar frente a 200 personas sin preparación. ¿Cómo te sientes?', en: 'You have to speak in front of 200 people without preparation. How do you feel?', fr: 'Tu dois parler devant 200 personnes sans préparation. Comment te sens-tu ?', de: 'Du musst vor 200 Menschen ohne Vorbereitung sprechen. Wie fühlst du dich?', it: 'Devi parlare davanti a 200 persone senza preparazione. Come ti senti?', pt: 'Você tem que falar na frente de 200 pessoas sem preparação. Como você se sente?' }, options: [
      { text: { es: 'Nervioso/a pero emocionado/a. Me gusta la adrenalina.', en: 'Nervous but excited. I like the adrenaline.', fr: 'Nerveux/se mais excité(e). J\'aime l\'adrénaline.', de: 'Nervös aber aufgeregt. Ich mag das Adrenalin.', it: 'Nervoso/a ma emozionato/a. Mi piace l\'adrenalina.', pt: 'Nervoso/a mas animado/a. Gosto da adrenalina.' }, dimension: 'E' },
      { text: { es: 'Aterrorizado/a. Esta situación es mi pesadilla específica.', en: 'Terrified. This situation is my specific nightmare.', fr: 'Terrifié(e). Cette situation est mon cauchemar spécifique.', de: 'Erschrocken. Diese Situation ist mein spezifischer Albtraum.', it: 'Terrorizzato/a. Questa situazione è il mio specifico incubo.', pt: 'Aterrorizado/a. Essa situação é meu pesadelo específico.' }, dimension: 'I' },
      { text: { es: 'Mal. No porque me importe el público, sino porque no me gusta hacer cosas sin prepararme.', en: 'Bad. Not because I care about the audience, but because I don\'t like doing things without preparing.', fr: 'Mal. Pas parce que le public m\'importe, mais parce que je n\'aime pas faire des choses sans me préparer.', de: 'Schlecht. Nicht weil mir das Publikum wichtig ist, sondern weil ich es nicht mag, Dinge ohne Vorbereitung zu tun.', it: 'Male. Non perché mi importi il pubblico, ma perché non mi piace fare cose senza prepararmi.', pt: 'Mal. Não porque me importo com o público, mas porque não gosto de fazer coisas sem me preparar.' }, dimension: 'S' },
      { text: { es: 'Lo improviso. Conectar con el público es algo que sé hacer.', en: 'I improvise. Connecting with the audience is something I know how to do.', fr: 'Je l\'improvise. Connecter avec le public est quelque chose que je sais faire.', de: 'Ich improvisiere. Mit dem Publikum zu verbinden ist etwas, das ich kann.', it: 'Lo improvviso. Connettersi con il pubblico è qualcosa che so fare.', pt: 'Improviso. Conectar com o público é algo que sei fazer.' }, dimension: 'C' },
    ] },
    { id: 7, situation: { es: 'Tu amigo/a quiere que lo acompañes a un evento que no te interesa nada.', en: 'Your friend wants you to accompany them to an event that doesn\'t interest you at all.', fr: 'Ton/ta ami(e) veut que tu l\'accompagnes à un événement qui ne t\'intéresse pas du tout.', de: 'Dein Freund/deine Freundin möchte, dass du ihn/sie zu einer Veranstaltung begleitest, die dich überhaupt nicht interessiert.', it: 'Il tuo amico/a vuole che lo accompagni a un evento che non ti interessa per niente.', pt: 'Seu/sua amigo/a quer que o/a acompanhe a um evento que não te interessa nada.' }, options: [
      { text: { es: 'Voy. Tampoco sé qué puede pasar y siempre termino encontrando algo interesante.', en: 'I go. I also don\'t know what can happen and I always end up finding something interesting.', fr: 'J\'y vais. Je ne sais pas non plus ce qui peut se passer et je finis toujours par trouver quelque chose d\'intéressant.', de: 'Ich gehe. Ich weiß auch nicht, was passieren kann, und ich finde immer etwas Interessantes.', it: 'Vado. Non so nemmeno cosa può succedere e finisco sempre per trovare qualcosa di interessante.', pt: 'Vou. Também não sei o que pode acontecer e sempre acabo encontrando algo interessante.' }, dimension: 'E' },
      { text: { es: 'Le digo que no. Si no me interesa, no voy. No tengo energía de sobra.', en: 'I tell them no. If it doesn\'t interest me, I don\'t go. I don\'t have extra energy.', fr: 'Je lui dis non. Si ça ne m\'intéresse pas, je n\'y vais pas. Je n\'ai pas d\'énergie en surplus.', de: 'Ich sage nein. Wenn es mich nicht interessiert, gehe ich nicht. Ich habe keine überschüssige Energie.', it: 'Dico no. Se non mi interessa, non vado. Non ho energia in eccesso.', pt: 'Digo que não. Se não me interessa, não vou. Não tenho energia de sobra.' }, dimension: 'I' },
      { text: { es: 'Le pregunto más sobre el evento antes de decidir. No me comprometo sin información.', en: 'I ask them more about the event before deciding. I don\'t commit without information.', fr: 'Je lui demande plus sur l\'événement avant de décider. Je ne m\'engage pas sans information.', de: 'Ich frage ihn/sie mehr über die Veranstaltung, bevor ich entscheide. Ich verpflichte mich nicht ohne Information.', it: 'Gli chiedo di più sull\'evento prima di decidere. Non mi impegno senza informazioni.', pt: 'Pergunto mais sobre o evento antes de decidir. Não me comprometo sem informação.' }, dimension: 'S' },
      { text: { es: 'Voy y convierto el tiempo en algo disfrutable para los dos.', en: 'I go and turn the time into something enjoyable for both of us.', fr: 'J\'y vais et je transforme le temps en quelque chose d\'agréable pour nous deux.', de: 'Ich gehe und mache aus der Zeit etwas Angenehmes für uns beide.', it: 'Vado e trasformo il tempo in qualcosa di piacevole per tutti e due.', pt: 'Vou e transformo o tempo em algo agradável para nós dois.' }, dimension: 'C' },
    ] },
    { id: 8, situation: { es: 'Describes tu red social ideal.', en: 'Describe your ideal social network.', fr: 'Tu décris ton réseau social idéal.', de: 'Du beschreibst dein ideales soziales Netzwerk.', it: 'Descrivi la tua rete sociale ideale.', pt: 'Descreva sua rede social ideal.' }, options: [
      { text: { es: 'Grande y variada. Muchos conocidos, varios amigos, de diferentes contextos.', en: 'Large and varied. Many acquaintances, several friends, from different contexts.', fr: 'Grande et variée. Beaucoup de connaissances, plusieurs amis, de différents contextes.', de: 'Groß und vielfältig. Viele Bekannte, mehrere Freunde, aus verschiedenen Kontexten.', it: 'Grande e varia. Molti conoscenti, diversi amici, da contesti diversi.', pt: 'Grande e variada. Muitos conhecidos, vários amigos, de diferentes contextos.' }, dimension: 'E' },
      { text: { es: 'Pequeña y profunda. Prefiero tres personas que me conozcan de verdad.', en: 'Small and deep. I prefer three people who really know me.', fr: 'Petite et profonde. Je préfère trois personnes qui me connaissent vraiment.', de: 'Klein und tief. Ich bevorzuge drei Menschen, die mich wirklich kennen.', it: 'Piccola e profonda. Preferisco tre persone che mi conoscono davvero.', pt: 'Pequena e profunda. Prefiro três pessoas que me conheçam de verdade.' }, dimension: 'I' },
      { text: { es: 'Curada. Cada persona en mi círculo está ahí porque hay algo genuino entre nosotros.', en: 'Curated. Every person in my circle is there because there\'s something genuine between us.', fr: 'Sélectionnée. Chaque personne dans mon cercle est là parce qu\'il y a quelque chose de genuins entre nous.', de: 'Kuratiert. Jede Person in meinem Kreis ist dort, weil es etwas Echtes zwischen uns gibt.', it: 'Curata. Ogni persona nel mio cerchio c\'è perché c\'è qualcosa di genuino tra noi.', pt: 'Curada. Cada pessoa no meu círculo está lá porque há algo genuíno entre nós.' }, dimension: 'S' },
      { text: { es: 'Diversa, con personas de mundos distintos que yo ayudé a conectar.', en: 'Diverse, with people from different worlds that I helped connect.', fr: 'Diverse, avec des personnes de mondes différents que j\'ai aidé à connecter.', de: 'Vielfältig, mit Menschen aus verschiedenen Welten, die ich geholfen habe zu verbinden.', it: 'Diversa, con persone di mondi diversi che ho aiutato a connettere.', pt: 'Diversa, com pessoas de mundos diferentes que ajudei a conectar.' }, dimension: 'C' },
    ] },
    { id: 9, situation: { es: 'Un conocido te presenta a alguien importante para tu carrera. Primera conversación.', en: 'An acquaintance introduces you to someone important for your career. First conversation.', fr: 'Une connaissance te présente à quelqu\'un d\'important pour ta carrière. Première conversation.', de: 'Ein Bekannter stellt dich jemandem vor, der für deine Karriere wichtig ist. Erstes Gespräch.', it: 'Un conoscente ti presenta a qualcuno importante per la tua carriera. Prima conversazione.', pt: 'Um conhecido te apresenta a alguém importante para sua carreira. Primeira conversa.' }, options: [
      { text: { es: 'Me lanzo. Cuento lo que hago, pregunto lo que quiero saber. No me cuesta.', en: 'I dive in. I tell what I do, ask what I want to know. It doesn\'t cost me.', fr: 'Je me lance. Je raconte ce que je fais, je demande ce que je veux savoir. Ça ne me coûte pas.', de: 'Ich stürze mich rein. Ich erzähle, was ich tue, frage, was ich wissen möchte. Es kostet mich nichts.', it: 'Mi lancio. Racconto quello che faccio, chiedo quello che voglio sapere. Non mi costa.', pt: 'Me lanço. Conto o que faço, pergunto o que quero saber. Não me custa.' }, dimension: 'E' },
      { text: { es: 'Me pongo un poco tenso/a y me cuesta ser natural.', en: 'I get a bit tense and it\'s hard to be natural.', fr: 'Je deviens un peu tendu(e) et j\'ai du mal à être naturel(le).', de: 'Ich werde etwas angespannt und es fällt mir schwer, natürlich zu sein.', it: 'Divento un po\' teso/a e mi costa essere naturale.', pt: 'Fico um pouco tenso/a e me custa ser natural.' }, dimension: 'I' },
      { text: { es: 'Escucho primero, hablo después. Prefiero entender con quién estoy antes de mostrarme.', en: 'I listen first, speak later. I prefer to understand who I\'m with before showing myself.', fr: 'J\'écoute d\'abord, je parle après. Je préfère comprendre avec qui je suis avant de me montrer.', de: 'Ich höre zuerst zu, spreche danach. Ich ziehe es vor, zu verstehen, mit wem ich bin, bevor ich mich zeige.', it: 'Prima ascolto, dopo parlo. Preferisco capire con chi sono prima di mostrarmi.', pt: 'Ouço primeiro, falo depois. Prefiro entender com quem estou antes de me mostrar.' }, dimension: 'S' },
      { text: { es: 'Lo leo rápido y adapto mi conversación para conectar en lo que a él/ella le interesa.', en: 'I read them quickly and adapt my conversation to connect on what interests them.', fr: 'Je le/la lis rapidement et adapte ma conversation pour se connecter sur ce qui l\'intéresse.', de: 'Ich lese ihn/sie schnell und passe mein Gespräch an, um an dem anzuknüpfen, was ihn/sie interessiert.', it: 'Lo leggo velocemente e adatto la mia conversazione per connettermi su quello che gli interessa.', pt: 'O/a leio rapidamente e adapto minha conversa para conectar no que lhe interessa.' }, dimension: 'C' },
    ] },
    { id: 10, situation: { es: '¿Cuál es tu relación con el silencio cuando estás con otros?', en: 'What is your relationship with silence when you\'re with others?', fr: 'Quelle est ta relation avec le silence quand tu es avec les autres ?', de: 'Wie ist deine Beziehung zur Stille, wenn du mit anderen zusammen bist?', it: 'Qual è il tuo rapporto con il silenzio quando sei con gli altri?', pt: 'Qual é sua relação com o silêncio quando está com outros?' }, options: [
      { text: { es: 'Incómodo. Si hay silencio, lo lleno. Las conversaciones deben fluir.', en: 'Uncomfortable. If there\'s silence, I fill it. Conversations should flow.', fr: 'Inconfortable. S\'il y a du silence, je le remplis. Les conversations doivent couler.', de: 'Unangenehm. Wenn es Stille gibt, fülle ich sie. Gespräche sollten fließen.', it: 'Scomodo. Se c\'è silenzio, lo riempio. Le conversazioni devono scorrere.', pt: 'Desconfortável. Se há silêncio, preencho. As conversas devem fluir.' }, dimension: 'E' },
      { text: { es: 'Lo disfruto. El silencio cómodo es señal de una buena relación.', en: 'I enjoy it. Comfortable silence is a sign of a good relationship.', fr: 'Je l\'apprécie. Le silence confortable est signe d\'une bonne relation.', de: 'Ich genieße es. Bequeme Stille ist ein Zeichen einer guten Beziehung.', it: 'Lo apprezzo. Il silenzio comodo è segno di un buon rapporto.', pt: 'Aprecio. O silêncio confortável é sinal de um bom relacionamento.' }, dimension: 'I' },
      { text: { es: 'Depende de quién. Con las personas correctas, el silencio es perfecto.', en: 'Depends on who. With the right people, silence is perfect.', fr: 'Ça dépend de qui. Avec les bonnes personnes, le silence est parfait.', de: 'Hängt davon ab, wer. Mit den richtigen Menschen ist Stille perfekt.', it: 'Dipende da chi. Con le persone giuste, il silenzio è perfetto.', pt: 'Depende de quem. Com as pessoas certas, o silêncio é perfeito.' }, dimension: 'S' },
      { text: { es: 'Generalmente soy yo quien rompe el silencio, y con algo que mejora la conversación.', en: 'I\'m generally the one who breaks the silence, and with something that improves the conversation.', fr: 'C\'est généralement moi qui brise le silence, et avec quelque chose qui améliore la conversation.', de: 'Im Allgemeinen bin ich derjenige, der die Stille bricht, und mit etwas, das das Gespräch verbessert.', it: 'Di solito sono io a rompere il silenzio, e con qualcosa che migliora la conversazione.', pt: 'Geralmente sou eu quem quebra o silêncio, e com algo que melhora a conversa.' }, dimension: 'C' },
    ] },
  ],
  characters: [
    { name: { es: 'El Extrovertido Puro', en: 'The Pure Extrovert', fr: 'L\'Extraverti Pur', de: 'Der Reine Extravertierte', it: 'L\'Estroverso Puro', pt: 'O Extrovertido Puro' }, dimensions: ['E'], photo: '/characters/extrovert.jpg', description: { es: 'Cargado de energía social. Aprende pensando en voz alta y en compañía.', en: 'Loaded with social energy. Learns by thinking out loud and in company.', fr: 'Chargé d\'énergie sociale. Apprend en pensant à voix haute et en compagnie.', de: 'Mit sozialer Energie geladen. Lernt durch lautes Denken und in Gesellschaft.', it: 'Carico di energia sociale. Impara pensando ad alta voce e in compagnia.', pt: 'Cheio de energia social. Aprende pensando em voz alta e em companhia.' }, philosophy: { es: 'Para ti, la gente es energía. Cada conversación nueva, cada persona desconocida, es una fuente de vitalidad. No es que no puedas estar solo/a — es que no eliges estarlo si hay una alternativa.', en: 'For you, people are energy. Every new conversation, every unknown person, is a source of vitality. It\'s not that you can\'t be alone — it\'s that you don\'t choose to if there\'s an alternative.', fr: 'Pour toi, les gens sont de l\'énergie. Chaque nouvelle conversation, chaque personne inconnue, est une source de vitalité. Ce n\'est pas que tu ne peux pas être seul(e) — c\'est que tu ne choisis pas de l\'être s\'il y a une alternative.', de: 'Für dich sind Menschen Energie. Jedes neue Gespräch, jede unbekannte Person, ist eine Quelle der Vitalität. Es ist nicht so, dass du nicht allein sein kannst — es ist so, dass du es nicht wählst, wenn es eine Alternative gibt.', it: 'Per te, le persone sono energia. Ogni nuova conversazione, ogni persona sconosciuta, è una fonte di vitalità. Non è che non puoi stare da solo/a — è che non scegli di esserlo se c\'è un\'alternativa.', pt: 'Para você, as pessoas são energia. Cada nova conversa, cada pessoa desconhecida, é uma fonte de vitalidade. Não é que você não possa estar sozinho/a — é que não escolhe isso se há uma alternativa.' } },
    { name: { es: 'El Introvertido Profundo', en: 'The Deep Introvert', fr: 'L\'Introverti Profond', de: 'Der Tiefe Introvertierte', it: 'L\'Introverso Profondo', pt: 'O Introvertido Profundo' }, dimensions: ['I'], photo: '/characters/introvert.jpg', description: { es: 'Cargado en la soledad. Prefiere una conversación profunda a diez conversaciones superficiales.', en: 'Recharged in solitude. Prefers one deep conversation to ten superficial ones.', fr: 'Rechargé dans la solitude. Préfère une conversation profonde à dix conversations superficielles.', de: 'Aufgeladen in der Einsamkeit. Bevorzugt ein tiefes Gespräch gegenüber zehn oberflächlichen.', it: 'Ricaricato nella solitudine. Preferisce una conversazione profonda a dieci conversazioni superficiali.', pt: 'Recarregado na solidão. Prefere uma conversa profunda a dez conversas superficiais.' }, philosophy: { es: 'Tu mundo interior es tan rico que el exterior a veces se siente como demasiado ruido. No eres antisocial — eres selectivo/a. La gente que entra en tu mundo recibe algo que pocos tienen: acceso real a quien eres.', en: 'Your inner world is so rich that the outside sometimes feels like too much noise. You\'re not antisocial — you\'re selective. People who enter your world receive something few have: real access to who you are.', fr: 'Ton monde intérieur est si riche que l\'extérieur ressemble parfois à trop de bruit. Tu n\'es pas antisocial(e) — tu es sélectif/ve. Les gens qui entrent dans ton monde reçoivent quelque chose que peu ont : un vrai accès à qui tu es.', de: 'Deine Innenwelt ist so reich, dass die Außenwelt manchmal zu viel Lärm anfühlt. Du bist nicht antisozial — du bist wählerisch. Menschen, die in deine Welt eintreten, erhalten etwas, das wenige haben: echten Zugang zu dem, wer du bist.', it: 'Il tuo mondo interiore è così ricco che l\'esterno a volte sembra troppo rumore. Non sei antisociale — sei selettivo/a. Le persone che entrano nel tuo mondo ricevono qualcosa che pochi hanno: vero accesso a chi sei.', pt: 'Seu mundo interior é tão rico que o exterior às vezes parece muito ruído. Você não é antissocial — é seletivo/a. As pessoas que entram no seu mundo recebem algo que poucos têm: acesso real a quem você é.' } },
    { name: { es: 'El Selectivo Estratégico', en: 'The Strategic Selective', fr: 'Le Sélectif Stratégique', de: 'Der Strategische Selektive', it: 'Il Selettivo Strategico', pt: 'O Seletivo Estratégico' }, dimensions: ['S'], photo: '/characters/selective.jpg', description: { es: 'Ni introvertido ni extrovertido. Simplemente no desperdicia energía.', en: 'Neither introverted nor extroverted. Simply doesn\'t waste energy.', fr: 'Ni introverti ni extraverti. Ne gaspille simplement pas l\'énergie.', de: 'Weder introvertiert noch extrovertiert. Verschwendet einfach keine Energie.', it: 'Né introverso né estroverso. Semplicemente non spreca energia.', pt: 'Nem introvertido nem extrovertido. Simplesmente não desperdiça energia.' }, philosophy: { es: 'Tu energía social es finita y valiosa. La distribuyes con criterio. No eres frío/a — eres eficiente. Las personas que logran pasar tu filtro obtienen toda tu atención y tu lealtad.', en: 'Your social energy is finite and valuable. You distribute it with criteria. You\'re not cold — you\'re efficient. People who manage to pass your filter get all your attention and loyalty.', fr: 'Ton énergie sociale est finie et précieuse. Tu la distribues avec des critères. Tu n\'es pas froid(e) — tu es efficace. Les personnes qui réussissent à passer ton filtre obtiennent toute ton attention et ta loyauté.', de: 'Deine soziale Energie ist endlich und wertvoll. Du verteilst sie mit Kriterien. Du bist nicht kalt — du bist effizient. Menschen, die es schaffen, deinen Filter zu passieren, bekommen deine ganze Aufmerksamkeit und Loyalität.', it: 'La tua energia sociale è finita e preziosa. La distribuisci con criterio. Non sei freddo/a — sei efficiente. Le persone che riescono a passare il tuo filtro ottengono tutta la tua attenzione e lealtà.', pt: 'Sua energia social é finita e valiosa. A distribui com critério. Você não é frio/a — é eficiente. As pessoas que conseguem passar pelo seu filtro obtêm toda a sua atenção e lealdade.' } },
    { name: { es: 'El Carismático Natural', en: 'The Natural Charismatic', fr: 'Le Charismatique Naturel', de: 'Der Natürliche Charismatiker', it: 'Il Carismatico Naturale', pt: 'O Carismático Natural' }, dimensions: ['C'], photo: '/characters/charismatic.jpg', description: { es: 'Hace sentir especial a cada persona en la sala.', en: 'Makes every person in the room feel special.', fr: 'Fait sentir chaque personne dans la salle spéciale.', de: 'Lässt jede Person im Raum sich besonders fühlen.', it: 'Fa sentire speciale ogni persona nella sala.', pt: 'Faz cada pessoa na sala se sentir especial.' }, philosophy: { es: 'Tu superpotencia es que la gente se siente vista cuando está contigo. No por artificios — por una habilidad genuina de prestar atención y hacer que las conversaciones valgan la pena.', en: 'Your superpower is that people feel seen when they\'re with you. Not through artifice — through a genuine ability to pay attention and make conversations worth having.', fr: 'Ton superpouvoir est que les gens se sentent vus quand ils sont avec toi. Pas par des artifices — par une habilité genuins à faire attention et à rendre les conversations valables.', de: 'Deine Superkraft ist, dass sich die Menschen gesehen fühlen, wenn sie bei dir sind. Nicht durch Kunstgriffe — durch eine echte Fähigkeit, aufzupassen und Gespräche es wert zu machen.', it: 'Il tuo superpotere è che le persone si sentono viste quando sono con te. Non attraverso artifici — attraverso una genuina capacità di prestare attenzione e rendere le conversazioni valse la pena.', pt: 'Seu superpoder é que as pessoas se sentem vistas quando estão com você. Não por artifícios — por uma habilidade genuína de prestar atenção e fazer as conversas valerem a pena.' } },
    { name: { es: 'El Ambiverted Energético', en: 'The Energetic Ambivert', fr: 'L\'Amorti Énergétique', de: 'Der Energetische Ambivertierte', it: 'L\'Ambivert Energetico', pt: 'O Ambivertido Energético' }, dimensions: ['E', 'C'], photo: '/characters/ambi-energetic.jpg', description: { es: 'Extrovertido con estilo. Sabe cómo hacer que las situaciones sociales sean memorables.', en: 'Extroverted with style. Knows how to make social situations memorable.', fr: 'Extraverti avec style. Sait comment rendre les situations sociales mémorables.', de: 'Extrovertiert mit Stil. Weiß, wie man soziale Situationen unvergesslich macht.', it: 'Estroverso con stile. Sa come rendere memorabili le situazioni sociali.', pt: 'Extrovertido com estilo. Sabe como tornar as situações sociais memoráveis.' }, philosophy: { es: 'Amas las personas y sabes cómo conectar con ellas. En una sala llena de gente, no eres uno más — eres quien hace que la sala funcione. Tienes energía de sobra y la usas para conectar.', en: 'You love people and know how to connect with them. In a room full of people, you\'re not just another — you\'re the one who makes the room work. You have energy to spare and use it to connect.', fr: 'Tu aimes les gens et tu sais comment te connecter avec eux. Dans une salle pleine de gens, tu n\'es pas un de plus — tu es celui qui fait fonctionner la salle. Tu as de l\'énergie en surplus et tu l\'utilises pour te connecter.', de: 'Du liebst Menschen und weißt, wie man sich mit ihnen verbindet. In einem Raum voller Menschen bist du nicht einer von vielen — du bist derjenige, der den Raum zum Funktionieren bringt. Du hast Energie im Überfluss und nutzt sie, um zu verbinden.', it: 'Ami le persone e sai come connetterti con loro. In una sala piena di gente, non sei uno dei tanti — sei quello che fa funzionare la sala. Hai energia in abbondanza e la usi per connetterti.', pt: 'Você ama as pessoas e sabe como se conectar com elas. Em uma sala cheia de gente, você não é mais um — é quem faz a sala funcionar. Você tem energia de sobra e a usa para conectar.' } },
    { name: { es: 'El Contemplativo Social', en: 'The Social Contemplative', fr: 'Le Contemplatif Social', de: 'Der Soziale Kontemplative', it: 'Il Contemplativo Sociale', pt: 'O Contemplativo Social' }, dimensions: ['I', 'S'], photo: '/characters/contemplative.jpg', description: { es: 'Introvertido selectivo: pocas personas, mucha profundidad.', en: 'Selective introvert: few people, much depth.', fr: 'Introverti sélectif : peu de personnes, beaucoup de profondeur.', de: 'Selektiver Introvertierter: wenige Menschen, viel Tiefe.', it: 'Introverso selettivo: poche persone, molta profondità.', pt: 'Introvertido seletivo: poucas pessoas, muita profundidade.' }, philosophy: { es: 'Prefieres la calidad sobre la cantidad en todo, especialmente en relaciones. No te interesa conocer a todo el mundo — te interesa conocer profundamente a las personas correctas.', en: 'You prefer quality over quantity in everything, especially in relationships. You\'re not interested in knowing everyone — you\'re interested in deeply knowing the right people.', fr: 'Tu préfères la qualité sur la quantité dans tout, surtout dans les relations. Tu ne t\'intéresses pas à connaître tout le monde — tu t\'intéresses à connaître profondément les bonnes personnes.', de: 'Du bevorzugst Qualität über Quantität in allem, besonders in Beziehungen. Du bist nicht daran interessiert, alle zu kennen — du bist daran interessiert, die richtigen Menschen tief zu kennen.', it: 'Preferisci la qualità sulla quantità in tutto, specialmente nelle relazioni. Non ti interessa conoscere tutti — ti interessa conoscere profondamente le persone giuste.', pt: 'Você prefere qualidade sobre quantidade em tudo, especialmente em relacionamentos. Não lhe interessa conhecer todo mundo — lhe interessa conhecer profundamente as pessoas certas.' } },
    { name: { es: 'El Conector Selectivo', en: 'The Selective Connector', fr: 'Le Connecteur Sélectif', de: 'Der Selektive Verbinder', it: 'Il Connettore Selettivo', pt: 'O Conector Seletivo' }, dimensions: ['S', 'C'], photo: '/characters/selective-connector.jpg', description: { es: 'No abre su círculo a cualquiera, pero cuando lo hace, crea conexiones poderosas.', en: 'Doesn\'t open their circle to just anyone, but when they do, creates powerful connections.', fr: 'N\'ouvre pas son cercle à n\'importe qui, mais quand il/elle le fait, crée des connexions puissantes.', de: 'Öffnet seinen Kreis nicht jedem, aber wenn er/sie es tut, entstehen starke Verbindungen.', it: 'Non apre il suo cerchio a chiunque, ma quando lo fa, crea connessioni potenti.', pt: 'Não abre seu círculo para qualquer um, mas quando faz isso, cria conexões poderosas.' }, philosophy: { es: 'Tu carisma no es para todos. Lo cuidas. Cuando decides conectar con alguien, lo haces con toda tu atención y habilidad. Tus amistades son pocas pero excepcionales.', en: 'Your charisma isn\'t for everyone. You take care of it. When you decide to connect with someone, you do it with all your attention and skill. Your friendships are few but exceptional.', fr: 'Ton charisme n\'est pas pour tout le monde. Tu en prends soin. Quand tu décides de te connecter avec quelqu\'un, tu le fais avec toute ton attention et ta compétence. Tes amitiés sont peu nombreuses mais exceptionnelles.', de: 'Dein Charisma ist nicht für alle. Du pflegst es. Wenn du dich entscheidest, mit jemandem in Kontakt zu treten, tust du es mit deiner ganzen Aufmerksamkeit und Fähigkeit. Deine Freundschaften sind wenige, aber außergewöhnlich.', it: 'Il tuo carisma non è per tutti. Lo curi. Quando decidi di connetterti con qualcuno, lo fai con tutta la tua attenzione e abilità. Le tue amicizie sono poche ma eccezionali.', pt: 'Seu carisma não é para todos. Você o cuida. Quando decide se conectar com alguém, faz isso com toda a sua atenção e habilidade. Suas amizades são poucas mas excepcionais.' } },
    { name: { es: 'El Extrovertido Reflexivo', en: 'The Reflective Extrovert', fr: 'L\'Extraverti Réflexif', de: 'Der Reflexive Extravertierte', it: 'L\'Estroverso Riflessivo', pt: 'O Extrovertido Reflexivo' }, dimensions: ['E', 'I'], photo: '/characters/reflective-extrovert.jpg', description: { es: 'Disfruta la gente pero necesita tiempo para procesar.', en: 'Enjoys people but needs time to process.', fr: 'Apprécie les gens mais a besoin de temps pour traiter.', de: 'Genießt Menschen, braucht aber Zeit zum Verarbeiten.', it: 'Apprezza le persone ma ha bisogno di tempo per elaborare.', pt: 'Aprecia as pessoas mas precisa de tempo para processar.' }, philosophy: { es: 'Eres ambas cosas a la vez y en distintas proporciones según el día. Disfrutas intensamente la conexión social y también necesitas tiempo para integrar lo que vives. No es contradicción — es complejidad.', en: 'You\'re both things at once and in different proportions depending on the day. You intensely enjoy social connection and also need time to integrate what you experience. It\'s not a contradiction — it\'s complexity.', fr: 'Tu es les deux choses à la fois et en différentes proportions selon le jour. Tu apprécies intensément la connexion sociale et tu as aussi besoin de temps pour intégrer ce que tu vis. Ce n\'est pas une contradiction — c\'est de la complexité.', de: 'Du bist beides gleichzeitig und in unterschiedlichen Proportionen je nach Tag. Du genießt soziale Verbindung intensiv und brauchst auch Zeit, um das, was du erlebst, zu integrieren. Das ist kein Widerspruch — es ist Komplexität.', it: 'Sei entrambe le cose allo stesso tempo e in proporzioni diverse a seconda del giorno. Apprezzi intensamente la connessione sociale e hai anche bisogno di tempo per integrare quello che vivi. Non è una contraddizione — è complessità.', pt: 'Você é ambas as coisas ao mesmo tempo e em proporções diferentes dependendo do dia. Você aprecia intensamente a conexão social e também precisa de tempo para integrar o que vive. Não é uma contradição — é complexidade.' } },
  ],
};

export async function seedSocial(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'social' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'social',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['social'],
      sortOrder: 2,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
