import type { PrismaClient } from '../../generated/prisma/client.js';

const T = {
  title: { es: '¿Cuánto narcisista hay en ti?', en: 'How much narcissist is in you?', fr: 'Combien y a-t-il de narcissisme en toi ?', de: 'Wie viel Narzissmus steckt in dir?', it: 'Quanto narcisismo c\'è in te?', pt: 'O quanto de narcisismo existe em você?' },
  description: { es: 'Cierto grado de narcisismo es sano. Demasiado destruye relaciones. ¿Dónde estás en el espectro?', en: 'Some degree of narcissism is healthy. Too much destroys relationships. Where are you on the spectrum?', fr: 'Un certain degré de narcissisme est sain. Trop en détruit les relations. Où te situes-tu sur le spectre ?', de: 'Ein gewisses Maß an Narzissmus ist gesund. Zu viel zerstört Beziehungen. Wo bist du im Spektrum?', it: 'Un certo grado di narcisismo è sano. Troppo distrugge le relazioni. Dove sei nello spettro?', pt: 'Certo grau de narcisismo é saudável. Demasiado destrói relacionamentos. Onde você está no espectro?' },
  scenarioLabel: { es: 'Escenario', en: 'Scenario', fr: 'Scénario', de: 'Szenario', it: 'Scenario', pt: 'Cenário' },
  dimensionLabels: {
    es: { G: 'Grandiosidad', V: 'Validación', E: 'Empatía', S: 'Seguridad' },
    en: { G: 'Grandiosity', V: 'Validation', E: 'Empathy', S: 'Security' },
    fr: { G: 'Grandiosité', V: 'Validation', E: 'Empathie', S: 'Sécurité' },
    de: { G: 'Grandiosität', V: 'Validierung', E: 'Empathie', S: 'Sicherheit' },
    it: { G: 'Grandiosità', V: 'Validazione', E: 'Empatia', S: 'Sicurezza' },
    pt: { G: 'Grandiosidade', V: 'Validação', E: 'Empatia', S: 'Segurança' },
  },
  questions: [
    { id: 1, situation: { es: 'Consigues un logro importante. ¿Cómo lo compartes?', en: 'You achieve something important. How do you share it?', fr: 'Tu obtiens une réalisation importante. Comment la partages-tu ?', de: 'Du erreichst etwas Wichtiges. Wie teilst du es mit?', it: 'Ottieni un risultato importante. Come lo condividi?', pt: 'Você conquista algo importante. Como compartilha?' }, options: [
      { text: { es: 'Lo publico en todas mis redes con una historia elaborada sobre mi esfuerzo.', en: 'I post it on all my social media with an elaborate story about my effort.', fr: 'Je le publie sur tous mes réseaux avec une histoire élaborée sur mon effort.', de: 'Ich poste es in all meinen sozialen Netzwerken mit einer ausgearbeiteten Geschichte über meine Anstrengung.', it: 'Lo pubblico su tutti i miei social con una storia elaborata sul mio sforzo.', pt: 'Publico em todas as minhas redes com uma história elaborada sobre meu esforço.' }, dimension: 'G' },
      { text: { es: 'Espero a que alguien me pregunte para contarlo con lujo de detalles.', en: 'I wait for someone to ask so I can tell it in great detail.', fr: 'J\'attends que quelqu\'un demande pour le raconter avec force de détails.', de: 'Ich warte darauf, dass jemand fragt, damit ich es in allen Details erzählen kann.', it: 'Aspetto che qualcuno chieda per raccontarlo con dovizia di dettagli.', pt: 'Espero que alguém pergunte para contar com riqueza de detalhes.' }, dimension: 'V' },
      { text: { es: 'Lo comparto con quienes sé que estarán genuinamente felices por mí.', en: 'I share it with those I know will be genuinely happy for me.', fr: 'Je le partage avec ceux que je sais seront genuinement heureux pour moi.', de: 'Ich teile es mit denjenigen, von denen ich weiß, dass sie sich aufrichtig für mich freuen werden.', it: 'Lo condivido con coloro che so saranno genuinamente felici per me.', pt: 'Compartilho com quem sei que ficará genuinamente feliz por mim.' }, dimension: 'E' },
      { text: { es: 'Me lo guardo. No necesito que otros lo validen para sentirme bien.', en: 'I keep it to myself. I don\'t need others to validate it to feel good.', fr: 'Je le garde pour moi. Je n\'ai pas besoin que les autres le valident pour me sentir bien.', de: 'Ich behalte es für mich. Ich brauche keine anderen, die es validieren, um mich gut zu fühlen.', it: 'Lo tengo per me. Non ho bisogno che gli altri lo validino per sentirmi bene.', pt: 'Guardo para mim. Não preciso que outros validem para me sentir bem.' }, dimension: 'S' },
    ] },
    { id: 2, situation: { es: 'Un amigo tiene un logro similar al tuyo pero más reconocido públicamente. ¿Cómo te sientes?', en: 'A friend has a similar achievement to yours but more publicly recognized. How do you feel?', fr: 'Un ami a une réalisation similaire à la tienne mais plus reconnue publiquement. Comment te sens-tu ?', de: 'Ein Freund hat eine ähnliche Leistung wie du, aber öffentlich besser anerkannt. Wie fühlst du dich?', it: 'Un amico ha un risultato simile al tuo ma più riconosciuto pubblicamente. Come ti senti?', pt: 'Um amigo tem uma conquista similar à sua mas mais reconhecida publicamente. Como você se sente?' }, options: [
      { text: { es: 'Siento que la gente no entiende que el mío fue más difícil y valioso.', en: 'I feel people don\'t understand that mine was more difficult and valuable.', fr: 'Je sens que les gens ne comprennent pas que le mien était plus difficile et précieux.', de: 'Ich fühle, dass die Leute nicht verstehen, dass meins schwieriger und wertvoller war.', it: 'Sento che la gente non capisce che il mio era più difficile e prezioso.', pt: 'Sinto que as pessoas não entendem que o meu foi mais difícil e valioso.' }, dimension: 'G' },
      { text: { es: 'Busco que alguien me diga que el mío también fue impresionante.', en: 'I look for someone to tell me mine was also impressive.', fr: 'Je cherche que quelqu\'un me dise que le mien était aussi impressionnant.', de: 'Ich suche jemanden, der mir sagt, dass meins auch beeindruckend war.', it: 'Cerco che qualcuno mi dica che anche il mio era impressionante.', pt: 'Busco que alguém me diga que o meu também foi impressionante.' }, dimension: 'V' },
      { text: { es: 'Me alegro por él/ella. Los logros de los amigos no disminuyen los míos.', en: 'I\'m happy for them. Friends\' achievements don\'t diminish mine.', fr: 'Je me réjouis pour lui/elle. Les réussites des amis ne diminuent pas les miennes.', de: 'Ich freue mich für ihn/sie. Die Leistungen von Freunden mindern meine nicht.', it: 'Sono felice per lui/lei. I risultati degli amici non diminuiscono i miei.', pt: 'Fico feliz por ele/ela. As conquistas dos amigos não diminuem as minhas.' }, dimension: 'E' },
      { text: { es: 'Me parece bien. Cada quien tiene su momento.', en: 'That\'s fine. Everyone has their moment.', fr: 'Ça me semble bien. Chacun a son moment.', de: 'Das ist gut. Jeder hat seinen Moment.', it: 'Va bene. Ognuno ha il suo momento.', pt: 'Está bem. Cada um tem seu momento.' }, dimension: 'S' },
    ] },
    { id: 3, situation: { es: 'Alguien te critica frente a un grupo. La crítica tiene algo de razón.', en: 'Someone criticizes you in front of a group. The criticism has some truth to it.', fr: 'Quelqu\'un te critique devant un groupe. La critique a une part de vérité.', de: 'Jemand kritisiert dich vor einer Gruppe. Die Kritik hat etwas Wahres an sich.', it: 'Qualcuno ti critica davanti a un gruppo. La critica ha qualcosa di vero.', pt: 'Alguém te critica na frente de um grupo. A crítica tem algum fundamento.' }, options: [
      { text: { es: 'La contradigo con firmeza y busco desacreditar a quien la hizo.', en: 'I firmly contradict it and try to discredit the person who made it.', fr: 'Je la contredis fermement et cherche à discréditer celui qui l\'a faite.', de: 'Ich widerspreche ihr fest und versuche, die Person zu diskreditieren, die sie gemacht hat.', it: 'La contraddico con fermezza e cerco di screditare chi l\'ha fatta.', pt: 'Contradigo com firmeza e busco desacreditar quem a fez.' }, dimension: 'G' },
      { text: { es: 'Me pongo incómodo/a hasta que alguien en el grupo tome mi defensa.', en: 'I get uncomfortable until someone in the group takes my defense.', fr: 'Je me sens mal à l\'aise jusqu\'à ce que quelqu\'un dans le groupe prenne ma défense.', de: 'Ich fühle mich unwohl, bis jemand in der Gruppe meine Verteidigung übernimmt.', it: 'Mi sento a disagio finché qualcuno nel gruppo prende le mie difese.', pt: 'Fico desconfortável até que alguém no grupo tome minha defesa.' }, dimension: 'V' },
      { text: { es: 'La escucho y si tiene razón, lo reconozco. No me matan las críticas.', en: 'I listen and if it\'s right, I acknowledge it. Criticism doesn\'t kill me.', fr: 'Je l\'écoute et si elle a raison, je l\'admets. Les critiques ne me tuent pas.', de: 'Ich höre zu und wenn es stimmt, erkenne ich es an. Kritik tötet mich nicht.', it: 'La ascolto e se ha ragione, lo riconosco. Le critiche non mi uccidono.', pt: 'Escuto e se tem razão, reconheço. Críticas não me matam.' }, dimension: 'E' },
      { text: { es: 'La evalúo fríamente. Si tiene razón, la considero. Si no, la ignoro.', en: 'I evaluate it coldly. If it\'s right, I consider it. If not, I ignore it.', fr: 'Je l\'évalue froidement. Si elle a raison, je la considère. Sinon, je l\'ignore.', de: 'Ich bewerte sie kühl. Wenn sie stimmt, bedenke ich sie. Wenn nicht, ignoriere ich sie.', it: 'La valuto freddamente. Se ha ragione, la considero. Se no, la ignoro.', pt: 'Avalio friamente. Se tem razão, considero. Se não, ignoro.' }, dimension: 'S' },
    ] },
    { id: 4, situation: { es: 'En una conversación grupal, alguien interrumpe tu historia para contar la suya.', en: 'In a group conversation, someone interrupts your story to tell theirs.', fr: 'Dans une conversation de groupe, quelqu\'un interrompt ton histoire pour raconter la sienne.', de: 'In einem Gruppengespräch unterbricht jemand deine Geschichte, um seine zu erzählen.', it: 'In una conversazione di gruppo, qualcuno interrompe la tua storia per raccontare la propria.', pt: 'Em uma conversa em grupo, alguém interrompe sua história para contar a dele/dela.' }, options: [
      { text: { es: 'Me ofendo internamente. Lo que yo iba a decir era claramente más interesante.', en: 'I\'m internally offended. What I was going to say was clearly more interesting.', fr: 'Je suis intérieurement offensé(e). Ce que j\'allais dire était clairement plus intéressant.', de: 'Ich bin innerlich beleidigt. Was ich sagen wollte, war eindeutig interessanter.', it: 'Mi offendo internamente. Quello che stavo per dire era chiaramente più interessante.', pt: 'Me ofendo internamente. O que eu ia dizer era claramente mais interessante.' }, dimension: 'G' },
      { text: { es: 'Busco la forma de retomar el protagonismo de la conversación.', en: 'I look for a way to regain the spotlight in the conversation.', fr: 'Je cherche un moyen de reprendre le rôle principal dans la conversation.', de: 'Ich suche einen Weg, die Hauptrolle im Gespräch zurückzugewinnen.', it: 'Cerco il modo di riprendere il protagonismo della conversazione.', pt: 'Busco a forma de retomar o protagonismo da conversa.' }, dimension: 'V' },
      { text: { es: 'Dejo que termine su historia. Después habrá tiempo para la mía.', en: 'I let them finish their story. There will be time for mine later.', fr: 'Je laisse finir son histoire. Il y aura du temps pour la mienne après.', de: 'Ich lasse sie ihre Geschichte beenden. Es wird Zeit für meine geben.', it: 'La lascio finire la sua storia. Poi ci sarà tempo per la mia.', pt: 'Deixo terminar a história. Depois haverá tempo para a minha.' }, dimension: 'E' },
      { text: { es: 'Me adapto. Las conversaciones no tienen un solo protagonista.', en: 'I adapt. Conversations don\'t have a single protagonist.', fr: 'Je m\'adapte. Les conversations n\'ont pas qu\'un seul protagoniste.', de: 'Ich passe mich an. Gespräche haben nicht nur einen Protagonisten.', it: 'Mi adatto. Le conversazioni non hanno un solo protagonista.', pt: 'Me adapto. Conversas não têm um único protagonista.' }, dimension: 'S' },
    ] },
    { id: 5, situation: { es: 'Tu pareja necesita apoyo emocional por algo que le pasó. Tú también tuviste un día difícil.', en: 'Your partner needs emotional support for something that happened to them. You also had a difficult day.', fr: 'Ton partenaire a besoin de soutien émotionnel pour quelque chose qui lui est arrivé. Toi aussi tu as eu une journée difficile.', de: 'Dein Partner braucht emotionale Unterstützung für etwas, das ihm passiert ist. Du hattest auch einen schwierigen Tag.', it: 'Il tuo partner ha bisogno di supporto emotivo per qualcosa che gli è capitato. Anche tu hai avuto una giornata difficile.', pt: 'Seu parceiro precisa de apoio emocional por algo que aconteceu com ele/ela. Você também teve um dia difícil.' }, options: [
      { text: { es: 'La escucho brevemente y luego redirijo la conversación hacia lo que me pasó a mí.', en: 'I listen briefly and then redirect the conversation to what happened to me.', fr: 'Je l\'écoute brièvement puis redirige la conversation vers ce qui m\'est arrivé.', de: 'Ich höre kurz zu und lenke dann das Gespräch auf das, was mir passiert ist.', it: 'Ascolto brevemente e poi ridireziono la conversazione verso quello che mi è capitato.', pt: 'Ouço brevemente e depois redireciono a conversa para o que me aconteceu.' }, dimension: 'G' },
      { text: { es: 'La apoyo, pero espero que después me pregunte cómo estoy yo también.', en: 'I support them, but I expect them to ask how I\'m doing too afterwards.', fr: 'Je la soutiens, mais j\'espère qu\'elle me demandera comment je vais aussi ensuite.', de: 'Ich unterstütze sie, aber ich erwarte, dass sie mich danach auch fragt, wie es mir geht.', it: 'La supporto, ma mi aspetto che poi mi chieda come sto anch\'io.', pt: 'Apoio, mas espero que depois me pergunte como estou também.' }, dimension: 'V' },
      { text: { es: 'Me olvido de mi día y me enfoco completamente en apoyarla.', en: 'I forget about my day and focus completely on supporting them.', fr: 'J\'oublie ma journée et me concentre complètement pour la soutenir.', de: 'Ich vergesse meinen Tag und konzentriere mich vollständig darauf, sie zu unterstützen.', it: 'Dimentico la mia giornata e mi concentro completamente nel supportarla.', pt: 'Esqueço o meu dia e me concentro completamente em apoiá-lo/a.' }, dimension: 'E' },
      { text: { es: 'La apoyo y después, cuando sea el momento, comparto lo mío también.', en: 'I support them and afterwards, when the time is right, I share mine too.', fr: 'Je la soutiens et ensuite, au bon moment, je partage aussi ce que j\'ai vécu.', de: 'Ich unterstütze sie und teile dann, wenn der Moment kommt, auch mein Erlebnis.', it: 'La supporto e poi, quando è il momento, condivido anche le mie cose.', pt: 'Apoio e depois, quando for o momento, compartilho o meu também.' }, dimension: 'S' },
    ] },
    { id: 6, situation: { es: 'Una persona que no conoces mucho recibe mucho elogio público por algo que considerarías básico.', en: 'Someone you don\'t know very well receives a lot of public praise for something you\'d consider basic.', fr: 'Une personne que tu ne connais pas beaucoup reçoit beaucoup d\'éloges publics pour quelque chose que tu considérerais comme basique.', de: 'Eine Person, die du nicht gut kennst, bekommt viel öffentliches Lob für etwas, das du für grundlegend halten würdest.', it: 'Una persona che non conosci molto riceve molti elogi pubblici per qualcosa che considereresti di base.', pt: 'Uma pessoa que você mal conhece recebe muitos elogios públicos por algo que você consideraria básico.' }, options: [
      { text: { es: 'Pienso que el estándar es muy bajo o que la gente no conoce el trabajo de verdad.', en: 'I think the standard is very low or that people don\'t know real work.', fr: 'Je pense que le standard est très bas ou que les gens ne connaissent pas le vrai travail.', de: 'Ich denke, der Standard ist sehr niedrig oder die Leute kennen keine echte Arbeit.', it: 'Penso che lo standard sia molto basso o che la gente non conosca il vero lavoro.', pt: 'Penso que o padrão é muito baixo ou que as pessoas não conhecem o trabalho de verdade.' }, dimension: 'G' },
      { text: { es: 'Siento que yo podría hacer algo mucho mejor y nadie lo reconocería igual.', en: 'I feel I could do something much better and nobody would recognize it the same way.', fr: 'Je sens que je pourrais faire quelque chose de bien meilleur et personne ne le reconnaîtrait pareil.', de: 'Ich fühle, dass ich etwas viel Besseres tun könnte und niemand es gleichermaßen anerkennen würde.', it: 'Sento che potrei fare qualcosa di molto migliore e nessuno lo riconoscerebbe allo stesso modo.', pt: 'Sinto que poderia fazer algo muito melhor e ninguém reconheceria da mesma forma.' }, dimension: 'V' },
      { text: { es: 'Me alegra que la gente reconozca el trabajo de otros. Buen momento para esa persona.', en: 'I\'m glad people recognize others\' work. Good moment for that person.', fr: 'Je suis content(e) que les gens reconnaissent le travail des autres. Bon moment pour cette personne.', de: 'Ich freue mich, dass die Leute die Arbeit anderer anerkennen. Guter Moment für diese Person.', it: 'Sono contento/a che la gente riconosca il lavoro degli altri. Bel momento per quella persona.', pt: 'Fico feliz que as pessoas reconheçam o trabalho dos outros. Bom momento para essa pessoa.' }, dimension: 'E' },
      { text: { es: 'Me parece bien. No me afecta el reconocimiento ajeno.', en: 'That\'s fine. Others\' recognition doesn\'t affect me.', fr: 'Ça me semble bien. La reconnaissance des autres ne m\'affecte pas.', de: 'Das ist gut. Die Anerkennung anderer betrifft mich nicht.', it: 'Va bene. Il riconoscimento altrui non mi riguarda.', pt: 'Está bem. O reconhecimento alheio não me afeta.' }, dimension: 'S' },
    ] },
    { id: 7, situation: { es: 'Te equivocas claramente en algo frente a otras personas. ¿Qué haces?', en: 'You clearly make a mistake in front of other people. What do you do?', fr: 'Tu te trompes clairement sur quelque chose devant d\'autres personnes. Que fais-tu ?', de: 'Du machst eindeutig einen Fehler vor anderen Menschen. Was tust du?', it: 'Sbagli chiaramente qualcosa davanti ad altre persone. Cosa fai?', pt: 'Você claramente erra algo na frente de outras pessoas. O que você faz?' }, options: [
      { text: { es: 'Busco una explicación que demuestre que no me equivoqué del todo.', en: 'I look for an explanation that shows I wasn\'t entirely wrong.', fr: 'Je cherche une explication qui montre que je n\'avais pas entièrement tort.', de: 'Ich suche eine Erklärung, die zeigt, dass ich nicht vollständig falsch lag.', it: 'Cerco una spiegazione che dimostri che non ho sbagliato del tutto.', pt: 'Busco uma explicação que mostre que não errei de todo.' }, dimension: 'G' },
      { text: { es: 'Me cuesta reconocerlo hasta que alguien más lo valida con amabilidad.', en: 'It\'s hard to acknowledge it until someone else validates it kindly.', fr: 'J\'ai du mal à l\'admettre jusqu\'à ce que quelqu\'un d\'autre le valide avec bienveillance.', de: 'Es fällt mir schwer, es anzuerkennen, bis jemand anderes es freundlich bestätigt.', it: 'Faccio fatica a riconoscerlo finché qualcun altro non lo valida con gentilezza.', pt: 'É difícil reconhecer até que alguém mais valide com gentileza.' }, dimension: 'V' },
      { text: { es: 'Lo reconozco sin drama. Equivocarse es humano y no cambia quién soy.', en: 'I acknowledge it without drama. Making mistakes is human and doesn\'t change who I am.', fr: 'Je l\'admets sans drame. Se tromper est humain et ne change pas qui je suis.', de: 'Ich erkenne es ohne Drama an. Fehler zu machen ist menschlich und ändert nicht, wer ich bin.', it: 'Lo riconosco senza drammi. Sbagliare è umano e non cambia chi sono.', pt: 'Reconheço sem drama. Errar é humano e não muda quem sou.' }, dimension: 'E' },
      { text: { es: 'Lo corrijo y sigo. No pierdo tiempo en esto.', en: 'I correct it and move on. I don\'t waste time on this.', fr: 'Je le corrige et continue. Je ne perds pas de temps là-dessus.', de: 'Ich korrigiere es und mache weiter. Ich verschwende keine Zeit damit.', it: 'Lo correggo e vado avanti. Non perdo tempo in questo.', pt: 'Corrijo e sigo em frente. Não perco tempo nisso.' }, dimension: 'S' },
    ] },
    { id: 8, situation: { es: 'Estás en un grupo y alguien nuevo llama más la atención que tú.', en: 'You\'re in a group and someone new draws more attention than you.', fr: 'Tu es dans un groupe et quelqu\'un de nouveau attire plus l\'attention que toi.', de: 'Du bist in einer Gruppe und jemand Neues zieht mehr Aufmerksamkeit auf sich als du.', it: 'Sei in un gruppo e qualcuno di nuovo attira più attenzione di te.', pt: 'Você está em um grupo e alguém novo chama mais atenção do que você.' }, options: [
      { text: { es: 'Busco la forma de participar más activamente y recuperar la atención del grupo.', en: 'I look for a way to participate more actively and recover the group\'s attention.', fr: 'Je cherche un moyen de participer plus activement et de récupérer l\'attention du groupe.', de: 'Ich suche einen Weg, aktiver zu partizipieren und die Aufmerksamkeit der Gruppe zurückzugewinnen.', it: 'Cerco il modo di partecipare più attivamente e recuperare l\'attenzione del gruppo.', pt: 'Busco uma forma de participar mais ativamente e recuperar a atenção do grupo.' }, dimension: 'G' },
      { text: { es: 'Espero que alguien note que yo también tengo algo valioso que aportar.', en: 'I wait for someone to notice that I also have something valuable to contribute.', fr: 'J\'attends que quelqu\'un remarque que moi aussi j\'ai quelque chose de précieux à apporter.', de: 'Ich warte darauf, dass jemand bemerkt, dass ich auch etwas Wertvolles beizutragen habe.', it: 'Aspetto che qualcuno noti che anch\'io ho qualcosa di prezioso da apportare.', pt: 'Espero que alguém note que eu também tenho algo valioso a contribuir.' }, dimension: 'V' },
      { text: { es: 'Me parece bien. Cada quien tiene sus momentos en un grupo.', en: 'That\'s fine. Everyone has their moments in a group.', fr: 'Ça me semble bien. Chacun a ses moments dans un groupe.', de: 'Das ist gut. Jeder hat seine Momente in einer Gruppe.', it: 'Va bene. Ognuno ha i suoi momenti in un gruppo.', pt: 'Está bem. Cada um tem seus momentos em um grupo.' }, dimension: 'E' },
      { text: { es: 'No me afecta. No salí para ser el centro de atención.', en: 'It doesn\'t affect me. I didn\'t come out to be the center of attention.', fr: 'Ça ne m\'affecte pas. Je ne suis pas sorti pour être le centre d\'attention.', de: 'Das betrifft mich nicht. Ich bin nicht ausgegangen, um im Mittelpunkt der Aufmerksamkeit zu stehen.', it: 'Non mi riguarda. Non sono uscito per essere il centro dell\'attenzione.', pt: 'Não me afeta. Não saí para ser o centro das atenções.' }, dimension: 'S' },
    ] },
    { id: 9, situation: { es: 'Ves que alguien publica algo en redes que tú dijiste antes sin darte crédito.', en: 'You see someone post something on social media that you said before without giving you credit.', fr: 'Tu vois quelqu\'un publier quelque chose sur les réseaux que tu avais dit avant sans te donner crédit.', de: 'Du siehst, dass jemand in sozialen Netzwerken etwas postet, das du zuvor gesagt hast, ohne dir Anerkennung zu geben.', it: 'Vedi che qualcuno pubblica qualcosa sui social che tu hai detto prima senza darti credito.', pt: 'Você vê que alguém publica nas redes algo que você disse antes sem te dar crédito.' }, options: [
      { text: { es: 'Lo señalo públicamente en los comentarios para que quede claro.', en: 'I point it out publicly in the comments so it\'s clear.', fr: 'Je le signale publiquement dans les commentaires pour que ce soit clair.', de: 'Ich weise öffentlich in den Kommentaren darauf hin, damit es klar ist.', it: 'Lo segnalo pubblicamente nei commenti affinché sia chiaro.', pt: 'Aponto publicamente nos comentários para que fique claro.' }, dimension: 'G' },
      { text: { es: 'Lo etiqueto o comento para que mis seguidores sepan que fue mío primero.', en: 'I tag or comment so my followers know it was mine first.', fr: 'Je l\'étiquette ou commente pour que mes abonnés sachent que c\'était le mien en premier.', de: 'Ich markiere oder kommentiere, damit meine Follower wissen, dass es zuerst meins war.', it: 'Lo taggo o commento affinché i miei follower sappiano che era mio per primo.', pt: 'Marco ou comento para que meus seguidores saibam que foi meu primeiro.' }, dimension: 'V' },
      { text: { es: 'Me parece menor. Las ideas viajan solas y eso es parte del juego.', en: 'I consider it minor. Ideas travel on their own and that\'s part of the game.', fr: 'Ça me semble mineur. Les idées voyagent seules et c\'est une part du jeu.', de: 'Das erscheint mir unbedeutend. Ideen reisen allein und das ist Teil des Spiels.', it: 'Mi sembra minore. Le idee viaggiano da sole e questo fa parte del gioco.', pt: 'Me parece menor. As ideias viajam sozinhas e isso faz parte do jogo.' }, dimension: 'E' },
      { text: { es: 'Si era importante, lo reclamo en privado. Si no, no vale el desgaste.', en: 'If it was important, I claim it privately. If not, it\'s not worth the wear.', fr: 'Si c\'était important, je le réclame en privé. Sinon, ça ne vaut pas l\'usure.', de: 'Wenn es wichtig war, fordere ich es privat ein. Wenn nicht, ist es den Aufwand nicht wert.', it: 'Se era importante, lo rivendico in privato. Se no, non vale lo sforzo.', pt: 'Se era importante, reclamo em particular. Se não, não vale o desgaste.' }, dimension: 'S' },
    ] },
    { id: 10, situation: { es: 'Alguien de tu círculo logra algo que tú llevas años intentando sin éxito.', en: 'Someone in your circle achieves something you\'ve been trying for years without success.', fr: 'Quelqu\'un de ton entourage réussit quelque chose que tu essaies depuis des années sans succès.', de: 'Jemand aus deinem Umfeld erreicht etwas, das du jahrelang ohne Erfolg versucht hast.', it: 'Qualcuno del tuo cerchio riesce in qualcosa che tu stai tentando da anni senza successo.', pt: 'Alguém do seu círculo conquista algo que você tenta há anos sem sucesso.' }, options: [
      { text: { es: 'No lo puedo evitar: pienso que yo lo merecía más que él/ella.', en: 'I can\'t help it: I think I deserved it more than they did.', fr: 'Je ne peux pas m\'en empêcher: je pense que je le méritais plus que lui/elle.', de: 'Ich kann es nicht vermeiden: Ich denke, ich hätte es mehr verdient als er/sie.', it: 'Non posso evitarlo: penso che lo meritassi più di lui/lei.', pt: 'Não consigo evitar: acho que eu merecia mais do que ele/ela.' }, dimension: 'G' },
      { text: { es: 'Busco validación de otros sobre mis propios méritos para sentirme mejor.', en: 'I seek validation from others about my own merits to feel better.', fr: 'Je cherche la validation des autres sur mes propres mérites pour me sentir mieux.', de: 'Ich suche die Anerkennung anderer für meine eigenen Verdienste, um mich besser zu fühlen.', it: 'Cerco la validazione degli altri sui miei meriti per sentirmi meglio.', pt: 'Busco validação de outros sobre meus próprios méritos para me sentir melhor.' }, dimension: 'V' },
      { text: { es: 'Me alegra por él/ella y lo uso como inspiración para seguir intentándolo.', en: 'I\'m happy for them and use it as inspiration to keep trying.', fr: 'Je me réjouis pour lui/elle et l\'utilise comme inspiration pour continuer à essayer.', de: 'Ich freue mich für ihn/sie und nutze es als Inspiration, weiter zu versuchen.', it: 'Sono felice per lui/lei e lo uso come ispirazione per continuare a provare.', pt: 'Fico feliz por ele/ela e uso como inspiração para continuar tentando.' }, dimension: 'E' },
      { text: { es: 'Su logro es el suyo. El mío llegará cuando llegue.', en: 'Their achievement is theirs. Mine will come when it comes.', fr: 'Sa réussite est la sienne. La mienne viendra quand elle viendra.', de: 'Seine Leistung gehört ihm. Meine wird kommen, wenn sie kommt.', it: 'Il suo risultato è suo. Il mio arriverà quando arriverà.', pt: 'A conquista dele/dela é dele/dela. A minha virá quando vier.' }, dimension: 'S' },
    ] },
  ],
  characters: [
    { name: { es: 'El Gran Narcisista', en: 'The Grand Narcissist', fr: 'Le Grand Narcissique', de: 'Der Große Narzisst', it: 'Il Grande Narcisista', pt: 'O Grande Narcisista' }, dimensions: ['G'], photo: '/characters/narcissist-grand.jpg', description: { es: 'Grandioso, el centro de su propio universo.', en: 'Grandiose, the center of their own universe.', fr: 'Grandiose, le centre de son propre univers.', de: 'Grandios, Mittelpunkt seines eigenen Universums.', it: 'Grandioso, il centro del proprio universo.', pt: 'Grandioso, o centro do próprio universo.' }, philosophy: { es: 'Crees que eres especial y que el mundo debería reconocerlo más. No es arrogancia — es certeza. El problema es que esa certeza a veces ciega tu capacidad de ver a los demás como iguales.', en: 'You believe you are special and the world should recognize it more. It\'s not arrogance — it\'s certainty. The problem is that certainty sometimes blinds your ability to see others as equals.', fr: 'Tu crois que tu es spécial(e) et que le monde devrait le reconnaître davantage. Ce n\'est pas de l\'arrogance — c\'est de la certitude. Le problème c\'est que cette certitude aveugle parfois ta capacité à voir les autres comme des égaux.', de: 'Du glaubst, dass du besonders bist und die Welt das mehr anerkennen sollte. Es ist keine Arroganz — es ist Gewissheit. Das Problem ist, dass diese Gewissheit manchmal deine Fähigkeit blind macht, andere als Gleiche zu sehen.', it: 'Credi di essere speciale e che il mondo dovrebbe riconoscerlo di più. Non è arroganza — è certezza. Il problema è che quella certezza a volte accieca la tua capacità di vedere gli altri come uguali.', pt: 'Você acredita que é especial e que o mundo deveria reconhecer isso mais. Não é arrogância — é certeza. O problema é que essa certeza às vezes cega sua capacidade de ver os outros como iguais.' } },
    { name: { es: 'El Hambriento de Validación', en: 'The Validation Hungry', fr: 'L\'Affamé de Validation', de: 'Der Validierungshungrige', it: 'L\'Affamato di Validazione', pt: 'O Faminto de Validação' }, dimensions: ['V'], photo: '/characters/validation-hungry.jpg', description: { es: 'Necesita aprobación constante para sentirse completo/a.', en: 'Needs constant approval to feel complete.', fr: 'A besoin d\'approbation constante pour se sentir complet(e).', de: 'Braucht ständige Zustimmung, um sich vollständig zu fühlen.', it: 'Ha bisogno di approvazione costante per sentirsi completo/a.', pt: 'Precisa de aprovação constante para se sentir completo/a.' }, philosophy: { es: 'Tu autoestima tiene un agujero que necesita ser llenado desde afuera. No es que no tengas valor — es que no puedes verlo sin un espejo externo. Cada like, cada elogio, es oxígeno.', en: 'Your self-esteem has a hole that needs to be filled from outside. It\'s not that you have no worth — it\'s that you can\'t see it without an external mirror. Every like, every compliment, is oxygen.', fr: 'Ton estime de soi a un trou qui doit être rempli de l\'extérieur. Ce n\'est pas que tu n\'aies pas de valeur — c\'est que tu ne peux pas la voir sans un miroir externe. Chaque like, chaque éloge, est de l\'oxygène.', de: 'Dein Selbstwertgefühl hat ein Loch, das von außen gefüllt werden muss. Es ist nicht so, dass du keinen Wert hast — du kannst ihn ohne einen äußeren Spiegel nicht sehen. Jeder Like, jedes Lob ist Sauerstoff.', it: 'La tua autostima ha un buco che deve essere riempito dall\'esterno. Non è che non abbia valore — è che non riesci a vederlo senza uno specchio esterno. Ogni like, ogni elogio, è ossigeno.', pt: 'Sua autoestima tem um buraco que precisa ser preenchido de fora. Não é que você não tenha valor — é que não consegue vê-lo sem um espelho externo. Cada like, cada elogio, é oxigênio.' } },
    { name: { es: 'La Persona Equilibrada', en: 'The Balanced Person', fr: 'La Personne Équilibrée', de: 'Die Ausgeglichene Person', it: 'La Persona Equilibrata', pt: 'A Pessoa Equilibrada' }, dimensions: ['E'], photo: '/characters/balanced.jpg', description: { es: 'Sano/a nivel de autoestima combinada con genuina empatía.', en: 'Healthy self-esteem level combined with genuine empathy.', fr: 'Niveau d\'estime de soi sain combiné avec une vraie empathie.', de: 'Gesundes Selbstwertgefühl kombiniert mit echter Empathie.', it: 'Livello sano di autostima combinato con genuina empatia.', pt: 'Nível saudável de autoestima combinado com genuína empatia.' }, philosophy: { es: 'Tienes un sentido estable de tu propio valor que no depende de la validación externa. Puedes alegrarte genuinamente por otros sin sentirte disminuido/a. Eso es más raro de lo que parece.', en: 'You have a stable sense of your own worth that doesn\'t depend on external validation. You can genuinely rejoice for others without feeling diminished. That\'s rarer than it looks.', fr: 'Tu as un sens stable de ta propre valeur qui ne dépend pas de la validation externe. Tu peux te réjouir genuinement pour les autres sans te sentir diminué(e). C\'est plus rare qu\'il n\'y paraît.', de: 'Du hast ein stabiles Gefühl deines eigenen Wertes, das nicht von externer Bestätigung abhängt. Du kannst dich aufrichtig für andere freuen, ohne dich vermindert zu fühlen. Das ist seltener als es scheint.', it: 'Hai un senso stabile del tuo valore che non dipende dalla validazione esterna. Puoi rallegrarti genuinamente per gli altri senza sentirti sminuito/a. Questo è più raro di quanto sembri.', pt: 'Você tem um senso estável do seu próprio valor que não depende de validação externa. Você pode se alegrar genuinamente pelos outros sem se sentir diminuído/a. Isso é mais raro do que parece.' } },
    { name: { es: 'El Seguro Independiente', en: 'The Secure Independent', fr: 'Le Sécurisé Indépendant', de: 'Der Sichere Unabhängige', it: 'Il Sicuro Indipendente', pt: 'O Seguro Independente' }, dimensions: ['S'], photo: '/characters/secure.jpg', description: { es: 'No necesita ser el centro, pero sabe exactamente quién es.', en: 'Doesn\'t need to be the center but knows exactly who they are.', fr: 'N\'a pas besoin d\'être le centre, mais sait exactement qui il/elle est.', de: 'Muss nicht der Mittelpunkt sein, weiß aber genau, wer er/sie ist.', it: 'Non ha bisogno di essere al centro, ma sa esattamente chi è.', pt: 'Não precisa ser o centro, mas sabe exatamente quem é.' }, philosophy: { es: 'Tu identidad no depende de lo que los demás digan o piensen de ti. Te conoces bien, aceptas tus errores sin dramatismo y no necesitas protagonismo para sentirte valioso/a.', en: 'Your identity doesn\'t depend on what others say or think about you. You know yourself well, accept your mistakes without drama, and don\'t need the spotlight to feel valuable.', fr: 'Ton identité ne dépend pas de ce que les autres disent ou pensent de toi. Tu te connais bien, acceptes tes erreurs sans drame et n\'as pas besoin du devant de la scène pour te sentir précieux/se.', de: 'Deine Identität hängt nicht davon ab, was andere über dich sagen oder denken. Du kennst dich gut, akzeptierst deine Fehler ohne Dramatik und brauchst kein Rampenlicht, um dich wertvoll zu fühlen.', it: 'La tua identità non dipende da ciò che gli altri dicono o pensano di te. Ti conosci bene, accetti i tuoi errori senza drammi e non hai bisogno del protagonismo per sentirti prezioso/a.', pt: 'Sua identidade não depende do que os outros dizem ou pensam sobre você. Você se conhece bem, aceita seus erros sem dramatismo e não precisa de protagonismo para se sentir valioso/a.' } },
    { name: { es: 'El Narcisista Frágil', en: 'The Fragile Narcissist', fr: 'Le Narcissique Fragile', de: 'Der Zerbrechliche Narzisst', it: 'Il Narcisista Fragile', pt: 'O Narcisista Frágil' }, dimensions: ['G', 'V'], photo: '/characters/fragile-narcissist.jpg', description: { es: 'Proyecta grandiosidad pero se derrumba sin validación.', en: 'Projects grandiosity but crumbles without validation.', fr: 'Projette de la grandiosité mais s\'effondre sans validation.', de: 'Projiziert Grandiosität, bricht aber ohne Bestätigung zusammen.', it: 'Proietta grandiosità ma crolla senza validazione.', pt: 'Projeta grandiosidade mas desmorona sem validação.' }, philosophy: { es: 'Por fuera pareces seguro/a y superior. Por dentro, una crítica te puede desestabilizar por días. La grandiosidad es tu armadura, pero debajo hay una necesidad de aprobación que nunca termina.', en: 'On the outside you seem secure and superior. Inside, a criticism can destabilize you for days. Grandiosity is your armor, but beneath it is a need for approval that never ends.', fr: 'À l\'extérieur tu sembles sûr(e) et supérieur(e). À l\'intérieur, une critique peut te déstabiliser pendant des jours. La grandiosité est ton armure, mais en dessous il y a un besoin d\'approbation qui ne finit jamais.', de: 'Nach außen hin wirkst du sicher und überlegen. Im Inneren kann eine Kritik dich tagelang destabilisieren. Grandiosität ist deine Rüstung, aber darunter steckt ein Bedürfnis nach Zustimmung, das nie endet.', it: 'All\'esterno sembri sicuro/a e superiore. All\'interno, una critica può destabilizzarti per giorni. La grandiosità è la tua armatura, ma sotto c\'è un bisogno di approvazione che non finisce mai.', pt: 'Por fora você parece seguro/a e superior. Por dentro, uma crítica pode te desestabilizar por dias. A grandiosidade é sua armadura, mas por baixo há uma necessidade de aprovação que nunca termina.' } },
    { name: { es: 'El Narcisista Encubierto', en: 'The Covert Narcissist', fr: 'Le Narcissique Discret', de: 'Der Verdeckte Narzisst', it: 'Il Narcisista Celato', pt: 'O Narcisista Encoberto' }, dimensions: ['G', 'E'], photo: '/characters/covert-narcissist.jpg', description: { es: 'Se presenta como empático pero hace todo girar en torno a sí mismo.', en: 'Presents as empathetic but makes everything revolve around themselves.', fr: 'Se présente comme empathique mais fait tout tourner autour de lui.', de: 'Präsentiert sich als empathisch, lässt aber alles um sich selbst kreisen.', it: 'Si presenta come empatico ma fa girare tutto intorno a sé stesso.', pt: 'Se apresenta como empático mas faz tudo girar em torno de si mesmo.' }, philosophy: { es: 'Eres empático/a en la superficie, pero en el fondo todo termina siendo sobre ti. Ayudas a otros para sentirte especial. Te importan las personas... cuando eso te hace quedar bien.', en: 'You\'re empathetic on the surface, but deep down everything ends up being about you. You help others to feel special. People matter to you... when it makes you look good.', fr: 'Tu es empathique en surface, mais au fond tout finit par être sur toi. Tu aides les autres pour te sentir spécial(e). Les gens te tiennent à cœur... quand ça te fait bien paraître.', de: 'Du bist an der Oberfläche empathisch, aber im Grunde dreht sich am Ende alles um dich. Du hilfst anderen, um dich besonders zu fühlen. Menschen sind dir wichtig... wenn das dich gut aussehen lässt.', it: 'Sei empatico/a in superficie, ma in fondo tutto finisce per essere su di te. Aiuti gli altri per sentirti speciale. Le persone ti importano... quando questo ti fa fare bella figura.', pt: 'Você é empático/a na superfície, mas no fundo tudo acaba sendo sobre você. Você ajuda os outros para se sentir especial. As pessoas importam para você... quando isso te faz parecer bem.' } },
    { name: { es: 'El Validado Empático', en: 'The Empathic Validator', fr: 'Le Validé Empathique', de: 'Der Empathische Bestätiger', it: 'Il Validato Empatico', pt: 'O Empático Validado' }, dimensions: ['V', 'E'], photo: '/characters/empathic-validator.jpg', description: { es: 'Necesita validación pero genuinamente se preocupa por los demás.', en: 'Needs validation but genuinely cares about others.', fr: 'A besoin de validation mais se préoccupe genuinement des autres.', de: 'Braucht Bestätigung, kümmert sich aber aufrichtig um andere.', it: 'Ha bisogno di validazione ma si preoccupa genuinamente degli altri.', pt: 'Precisa de validação mas genuinamente se preocupa com os outros.' }, philosophy: { es: 'Tienes un corazón enorme y también una necesidad de ser visto/a. Cuando ayudas, es real — pero también esperas que te lo reconozcan. Hay una parte tuya que todavía necesita permiso para existir.', en: 'You have a huge heart and also a need to be seen. When you help, it\'s real — but you also expect it to be recognized. There\'s a part of you that still needs permission to exist.', fr: 'Tu as un énorme cœur et aussi un besoin d\'être vu(e). Quand tu aides, c\'est réel — mais tu t\'attends aussi à ce que ce soit reconnu. Il y a une partie de toi qui a encore besoin de permission pour exister.', de: 'Du hast ein riesiges Herz und auch ein Bedürfnis, gesehen zu werden. Wenn du hilfst, ist es real — aber du erwartest auch, dass es anerkannt wird. Es gibt einen Teil von dir, der noch die Erlaubnis braucht, zu existieren.', it: 'Hai un cuore enorme e anche un bisogno di essere visto/a. Quando aiuti, è reale — ma ti aspetti anche che venga riconosciuto. C\'è una parte di te che ha ancora bisogno di permesso per esistere.', pt: 'Você tem um coração enorme e também uma necessidade de ser visto/a. Quando ajuda, é real — mas também espera que seja reconhecido. Há uma parte de você que ainda precisa de permissão para existir.' } },
    { name: { es: 'La Autoestima Real', en: 'Real Self-Esteem', fr: 'La Vraie Estime de Soi', de: 'Echtes Selbstwertgefühl', it: 'La Vera Autostima', pt: 'A Autoestima Real' }, dimensions: ['S', 'E'], photo: '/characters/real-esteem.jpg', description: { es: 'Seguro/a de sí mismo/a y genuinamente presente para los demás.', en: 'Secure in themselves and genuinely present for others.', fr: 'Sûr(e) de soi et genuinement présent(e) pour les autres.', de: 'Selbstsicher und aufrichtig für andere präsent.', it: 'Sicuro/a di sé e genuinamente presente per gli altri.', pt: 'Seguro/a de si mesmo/a e genuinamente presente para os outros.' }, philosophy: { es: 'Tu seguridad interna te libera para estar completamente presente con los demás. No compites con nadie porque no necesitas ganar nada. Simplemente eres, y eso es suficiente.', en: 'Your internal security frees you to be completely present with others. You don\'t compete with anyone because you don\'t need to win anything. You simply are, and that\'s enough.', fr: 'Ta sécurité interne te libère pour être complètement présent(e) avec les autres. Tu ne concurrences personne parce que tu n\'as pas besoin de gagner quoi que ce soit. Tu es simplement, et c\'est suffisant.', de: 'Deine innere Sicherheit befreit dich, vollständig mit anderen präsent zu sein. Du konkurrierst mit niemandem, weil du nichts gewinnen musst. Du bist einfach, und das ist genug.', it: 'La tua sicurezza interna ti libera per essere completamente presente con gli altri. Non gareggi con nessuno perché non hai bisogno di vincere nulla. Sei semplicemente, e questo è sufficiente.', pt: 'Sua segurança interna te libera para estar completamente presente com os outros. Você não compete com ninguém porque não precisa ganhar nada. Você simplesmente é, e isso é suficiente.' } },
  ],
};

export async function seedNarcissist(prisma: PrismaClient, catMap: Record<string, string>) {
  await prisma.quiz.upsert({
    where: { slug: 'narcissist' },
    update: {
      title: T.title, description: T.description, scenarioLabel: T.scenarioLabel,
      dimensionLabels: T.dimensionLabels, questions: T.questions, characters: T.characters,
    },
    create: {
      slug: 'narcissist',
      title: T.title,
      description: T.description,
      scenarioLabel: T.scenarioLabel,
      categoryId: catMap['dark-personality'],
      sortOrder: 3,
      dimensionLabels: T.dimensionLabels,
      questions: T.questions,
      characters: T.characters,
    },
  });
}
