import type { PrismaClient } from '../../generated/prisma/client.js';

export async function seedRacist(prisma: PrismaClient, catMap: Record<string, string>) {
  const data = {
    slug: 'racist',
    title: { es: '¿Eres racista sin saberlo?', en: 'Are you racist without knowing it?', fr: 'Êtes-vous raciste sans le savoir ?', de: 'Bist du rassistisch, ohne es zu wissen?', it: 'Sei razzista senza saperlo?', pt: 'Você é racista sem saber?' },
    description: { es: 'El racismo explícito es fácil de detectar. El implícito vive en los prejuicios que creemos no tener.', en: 'Explicit racism is easy to spot. Implicit racism lives in the biases we think we don\'t have.', fr: 'Le racisme explicite est facile à détecter. Le racisme implicite vit dans les préjugés que nous croyons ne pas avoir.', de: 'Expliziter Rassismus ist leicht zu erkennen. Impliziter Rassismus lebt in den Vorurteilen, von denen wir glauben, sie nicht zu haben.', it: 'Il razzismo esplicito è facile da rilevare. Quello implicito vive nei pregiudizi che crediamo di non avere.', pt: 'O racismo explícito é fácil de detectar. O implícito vive nos preconceitos que achamos não ter.' },
    scenarioLabel: { es: 'Situación', en: 'Situation', fr: 'Situation', de: 'Situation', it: 'Situazione', pt: 'Situação' },
    categoryId: catMap['moral'],
    sortOrder: 1,
    dimensionLabels: {
      es: { P: 'Prejuicio Implícito', C: 'Conciencia Crítica', N: 'Neutralidad Superficial', A: 'Antirracismo Activo' },
      en: { P: 'Implicit Bias', C: 'Critical Awareness', N: 'Surface Neutrality', A: 'Active Anti-Racism' },
      fr: { P: 'Biais Implicite', C: 'Conscience Critique', N: 'Neutralité Superficielle', A: 'Antiracisme Actif' },
      de: { P: 'Implizite Voreingenommenheit', C: 'Kritisches Bewusstsein', N: 'Oberflächliche Neutralität', A: 'Aktiver Antirassismus' },
      it: { P: 'Pregiudizio Implicito', C: 'Consapevolezza Critica', N: 'Neutralità Superficiale', A: 'Antirazzismo Attivo' },
      pt: { P: 'Preconceito Implícito', C: 'Consciência Crítica', N: 'Neutralidade Superficial', A: 'Antirracismo Ativo' },
    },
    questions: [
      {
        id: 1,
        situation: { es: 'Entras a un ascensor de noche y hay una persona de otra raza. ¿Qué sientes?', en: 'You enter an elevator at night and there\'s a person of another race. What do you feel?', fr: 'Vous entrez dans un ascenseur la nuit et il y a une personne d\'une autre race. Que ressentez-vous ?', de: 'Du betrittst nachts einen Aufzug und dort ist eine Person einer anderen Rasse. Was fühlst du?', it: 'Entri in un ascensore di notte e c\'è una persona di un\'altra razza. Cosa provi?', pt: 'Você entra em um elevador à noite e há uma pessoa de outra raça. O que você sente?' },
        options: [
          { text: { es: 'Sin darme cuenta, me pongo ligeramente más alerta.', en: 'Without realizing it, I become slightly more alert.', fr: 'Sans m\'en rendre compte, je deviens légèrement plus vigilant(e).', de: 'Ohne es zu merken, werde ich etwas aufmerksamer.', it: 'Senza rendermene conto, divento leggermente più all\'erta.', pt: 'Sem perceber, fico levemente mais alerta.' }, dimension: 'P' },
          { text: { es: 'Lo noto y me pregunto de dónde viene esa reacción si la tengo.', en: 'I notice it and ask myself where that reaction comes from if I have it.', fr: 'Je le remarque et me demande d\'où vient cette réaction si je l\'ai.', de: 'Ich bemerke es und frage mich, woher diese Reaktion kommt, wenn ich sie habe.', it: 'Lo noto e mi chiedo da dove viene quella reazione se ce l\'ho.', pt: 'Noto e me pergunto de onde vem essa reação, caso a tenha.' }, dimension: 'C' },
          { text: { es: 'No pienso en la raza. Me fijo en otros factores como la hora o la expresión.', en: 'I don\'t think about race. I notice other factors like the time of day or facial expression.', fr: 'Je ne pense pas à la race. Je remarque d\'autres facteurs comme l\'heure ou l\'expression.', de: 'Ich denke nicht an Rasse. Ich achte auf andere Faktoren wie die Uhrzeit oder den Gesichtsausdruck.', it: 'Non penso alla razza. Noto altri fattori come l\'ora o l\'espressione.', pt: 'Não penso na raça. Noto outros fatores como a hora ou a expressão.' }, dimension: 'N' },
          { text: { es: 'No siento nada diferente. Una persona es una persona.', en: 'I feel nothing different. A person is a person.', fr: 'Je ne ressens rien de différent. Une personne est une personne.', de: 'Ich fühle nichts anderes. Ein Mensch ist ein Mensch.', it: 'Non sento nulla di diverso. Una persona è una persona.', pt: 'Não sinto nada diferente. Uma pessoa é uma pessoa.' }, dimension: 'A' },
        ],
      },
      {
        id: 2,
        situation: { es: 'Alguien de otra raza habla mejor español (o tu idioma) de lo que esperabas. ¿Qué piensas?', en: 'Someone of another race speaks your language better than you expected. What do you think?', fr: 'Une personne d\'une autre race parle mieux votre langue que vous ne l\'attendiez. Qu\'en pensez-vous ?', de: 'Jemand einer anderen Rasse spricht deine Sprache besser als erwartet. Was denkst du?', it: 'Una persona di un\'altra razza parla la tua lingua meglio di quanto ti aspettassi. Cosa pensi?', pt: 'Uma pessoa de outra raça fala seu idioma melhor do que você esperava. O que você pensa?' },
        options: [
          { text: { es: '"Qué bien habla" — me sorprende más de lo que debería.', en: '"They speak so well" — it surprises me more than it should.', fr: '"Comme il parle bien" — ça me surprend plus que ça ne devrait.', de: '"Wie gut er/sie spricht" — es überrascht mich mehr als es sollte.', it: '"Che bene parla" — mi sorprende più di quanto dovrebbe.', pt: '"Como fala bem" — me surpreende mais do que deveria.' }, dimension: 'P' },
          { text: { es: 'Noto mi sorpresa y la cuestiono. ¿Por qué esperaba algo diferente?', en: 'I notice my surprise and question it. Why did I expect something different?', fr: 'Je remarque ma surprise et la questionne. Pourquoi m\'attendais-je à quelque chose de différent ?', de: 'Ich bemerke meine Überraschung und hinterfrage sie. Warum habe ich etwas anderes erwartet?', it: 'Noto la mia sorpresa e la metto in discussione. Perché mi aspettavo qualcosa di diverso?', pt: 'Noto minha surpresa e a questiono. Por que eu esperava algo diferente?' }, dimension: 'C' },
          { text: { es: 'Ni lo noto especialmente. Cada persona habla como habla.', en: 'I don\'t particularly notice. Each person speaks however they speak.', fr: 'Je ne le remarque pas particulièrement. Chaque personne parle comme elle parle.', de: 'Ich bemerke es nicht besonders. Jeder spricht so, wie er spricht.', it: 'Non lo noto in particolare. Ogni persona parla come parla.', pt: 'Nem noto especialmente. Cada pessoa fala como fala.' }, dimension: 'N' },
          { text: { es: 'Lo celebro activamente. La diversidad lingüística es increíble.', en: 'I actively celebrate it. Linguistic diversity is incredible.', fr: 'Je le célèbre activement. La diversité linguistique est incroyable.', de: 'Ich feiere es aktiv. Sprachliche Vielfalt ist unglaublich.', it: 'Lo celebro attivamente. La diversità linguistica è incredibile.', pt: 'Celebro ativamente. A diversidade linguística é incrível.' }, dimension: 'A' },
        ],
      },
      {
        id: 3,
        situation: { es: 'Un amigo hace un chiste racista "de broma". ¿Qué haces?', en: 'A friend makes a racist "joke". What do you do?', fr: 'Un ami fait une blague raciste "pour rire". Que faites-vous ?', de: 'Ein Freund macht einen rassistischen "Witz". Was machst du?', it: 'Un amico fa una battuta razzista "per ridere". Cosa fai?', pt: 'Um amigo faz uma piada racista "de brincadeira". O que você faz?' },
        options: [
          { text: { es: 'Me río o no digo nada para no arruinar el ambiente.', en: 'I laugh or say nothing to avoid ruining the mood.', fr: 'Je ris ou ne dis rien pour ne pas gâcher l\'ambiance.', de: 'Ich lache oder sage nichts, um die Stimmung nicht zu verderben.', it: 'Rido o non dico niente per non rovinare il clima.', pt: 'Rio ou não digo nada para não estragar o clima.' }, dimension: 'P' },
          { text: { es: 'Internamente me molesta pero no sé cómo intervenir sin que sea incómodo.', en: 'It bothers me internally but I don\'t know how to intervene without making it awkward.', fr: 'Intérieurement, ça me dérange, mais je ne sais pas comment intervenir sans que ce soit gênant.', de: 'Es stört mich innerlich, aber ich weiß nicht, wie ich eingreifen soll, ohne es unangenehm zu machen.', it: 'Internamente mi disturba ma non so come intervenire senza che sia imbarazzante.', pt: 'Internamente me incomoda, mas não sei como intervir sem gerar constrangimento.' }, dimension: 'C' },
          { text: { es: 'Cambio de tema. No río pero tampoco lo confronto.', en: 'I change the subject. I don\'t laugh but I don\'t confront it either.', fr: 'Je change de sujet. Je ne ris pas, mais je ne confronte pas non plus.', de: 'Ich wechsle das Thema. Ich lache nicht, aber ich konfrontiere auch nicht.', it: 'Cambio argomento. Non rido ma non lo confronto nemmeno.', pt: 'Mudo de assunto. Não rio mas também não confronto.' }, dimension: 'N' },
          { text: { es: 'Le digo directamente que ese tipo de "chiste" no está bien, sin importar el ambiente.', en: 'I tell them directly that that kind of "joke" isn\'t okay, regardless of the mood.', fr: 'Je lui dis directement que ce type de "blague" n\'est pas acceptable, peu importe l\'ambiance.', de: 'Ich sage ihnen direkt, dass diese Art von "Witz" nicht in Ordnung ist, egal wie die Stimmung ist.', it: 'Gli dico direttamente che quel tipo di "battuta" non va bene, indipendentemente dal clima.', pt: 'Digo diretamente que esse tipo de "piada" não está certo, independentemente do clima.' }, dimension: 'A' },
        ],
      },
      {
        id: 4,
        situation: { es: 'Ves un currículum de alguien con nombre extranjero difícil de pronunciar para el puesto que manejas.', en: 'You see a résumé from someone with a foreign name that\'s hard to pronounce for the position you\'re managing.', fr: 'Vous voyez le CV de quelqu\'un avec un nom étranger difficile à prononcer pour le poste que vous gérez.', de: 'Du siehst einen Lebenslauf von jemandem mit einem schwer auszusprechenden ausländischen Namen für die Stelle, die du verwaltest.', it: 'Vedi un curriculum di qualcuno con un nome straniero difficile da pronunciare per il posto che gestisci.', pt: 'Você vê um currículo de alguém com um nome estrangeiro difícil de pronunciar para o cargo que você gerencia.' },
        options: [
          { text: { es: 'Sin pensar mucho, lo ubico mentalmente en una categoría diferente a los nombres locales.', en: 'Without much thought, I mentally place them in a different category than local names.', fr: 'Sans trop y penser, je le classe mentalement dans une catégorie différente des noms locaux.', de: 'Ohne viel nachzudenken, ordne ich sie mental in eine andere Kategorie als lokale Namen ein.', it: 'Senza pensarci molto, lo colloco mentalmente in una categoria diversa dai nomi locali.', pt: 'Sem pensar muito, o coloco mentalmente em uma categoria diferente dos nomes locais.' }, dimension: 'P' },
          { text: { es: 'Me pregunto si tengo sesgos involuntarios en ese tipo de decisión.', en: 'I wonder if I have involuntary biases in that kind of decision.', fr: 'Je me demande si j\'ai des biais involontaires dans ce type de décision.', de: 'Ich frage mich, ob ich unfreiwillige Vorurteile bei dieser Art von Entscheidung habe.', it: 'Mi chiedo se ho pregiudizi involontari in quel tipo di decisione.', pt: 'Me pergunto se tenho preconceitos involuntários nesse tipo de decisão.' }, dimension: 'C' },
          { text: { es: 'Evalúo solo las calificaciones. El nombre no debería importar.', en: 'I evaluate only the qualifications. The name shouldn\'t matter.', fr: 'J\'évalue uniquement les qualifications. Le nom ne devrait pas avoir d\'importance.', de: 'Ich bewerte nur die Qualifikationen. Der Name sollte keine Rolle spielen.', it: 'Valuto solo le qualifiche. Il nome non dovrebbe importare.', pt: 'Avalio apenas as qualificações. O nome não deveria importar.' }, dimension: 'N' },
          { text: { es: 'Sé que existe sesgo en este proceso y activamente lo corrijo.', en: 'I know bias exists in this process and I actively correct for it.', fr: 'Je sais que des biais existent dans ce processus et je les corrige activement.', de: 'Ich weiß, dass in diesem Prozess Vorurteile existieren, und korrigiere sie aktiv.', it: 'So che esistono pregiudizi in questo processo e li correggo attivamente.', pt: 'Sei que existe viés nesse processo e o corrijo ativamente.' }, dimension: 'A' },
        ],
      },
      {
        id: 5,
        situation: { es: 'Un colega de otra raza es promovido antes que tú. ¿Qué piensas primero?', en: 'A colleague of another race is promoted before you. What\'s your first thought?', fr: 'Un collègue d\'une autre race est promu avant vous. À quoi pensez-vous en premier ?', de: 'Ein Kollege einer anderen Rasse wird vor dir befördert. Was denkst du zuerst?', it: 'Un collega di un\'altra razza viene promosso prima di te. Qual è il tuo primo pensiero?', pt: 'Um colega de outra raça é promovido antes de você. O que você pensa primeiro?' },
        options: [
          { text: { es: 'Tengo el impulso de pensar si "las cuotas" tuvieron algo que ver.', en: 'I have the impulse to wonder if "quotas" had something to do with it.', fr: 'J\'ai l\'envie de me demander si les "quotas" ont joué un rôle.', de: 'Ich habe den Impuls zu denken, ob "Quoten" etwas damit zu tun hatten.', it: 'Ho l\'impulso di chiedermi se le "quote" abbiano avuto qualcosa a che fare.', pt: 'Tenho o impulso de pensar se "cotas" tiveram algo a ver.' }, dimension: 'P' },
          { text: { es: 'Noto si ese pensamiento aparece y lo cuestiono.', en: 'I notice if that thought appears and I question it.', fr: 'Je remarque si cette pensée apparaît et je la questionne.', de: 'Ich bemerke, ob dieser Gedanke auftaucht, und hinterfrage ihn.', it: 'Noto se quel pensiero appare e lo metto in discussione.', pt: 'Noto se esse pensamento aparece e o questiono.' }, dimension: 'C' },
          { text: { es: 'Evalúo sus calificaciones y el proceso. Si fue justo, fue justo.', en: 'I evaluate their qualifications and the process. If it was fair, it was fair.', fr: 'J\'évalue ses qualifications et le processus. Si c\'était juste, c\'était juste.', de: 'Ich bewerte ihre Qualifikationen und den Prozess. Wenn es fair war, war es fair.', it: 'Valuto le sue qualifiche e il processo. Se è stato giusto, è stato giusto.', pt: 'Avalio suas qualificações e o processo. Se foi justo, foi justo.' }, dimension: 'N' },
          { text: { es: 'Me alegra. La diversidad en posiciones de liderazgo es buena para todos.', en: 'I\'m glad. Diversity in leadership positions is good for everyone.', fr: 'Je suis content(e). La diversité dans les postes de direction est bonne pour tous.', de: 'Ich freue mich. Vielfalt in Führungspositionen ist gut für alle.', it: 'Sono contento/a. La diversità nelle posizioni di leadership è buona per tutti.', pt: 'Fico feliz. A diversidade em posições de liderança é boa para todos.' }, dimension: 'A' },
        ],
      },
      {
        id: 6,
        situation: { es: 'Alguien describe a un delincuente en las noticias. ¿Qué información mental construyes?', en: 'Someone describes a criminal on the news. What mental image do you construct?', fr: 'Quelqu\'un décrit un criminel dans les informations. Quelle image mentale construisez-vous ?', de: 'Jemand beschreibt einen Kriminellen in den Nachrichten. Welches mentale Bild baust du auf?', it: 'Qualcuno descrive un criminale nelle notizie. Quale immagine mentale costruisci?', pt: 'Alguém descreve um criminoso nas notícias. Que imagem mental você constrói?' },
        options: [
          { text: { es: 'Dependiendo del crimen o la zona, automáticamente imagino una raza específica.', en: 'Depending on the crime or location, I automatically picture a specific race.', fr: 'Selon le crime ou la zone, j\'imagine automatiquement une race spécifique.', de: 'Je nach Verbrechen oder Gegend stelle ich mir automatisch eine bestimmte Rasse vor.', it: 'A seconda del crimine o della zona, immagino automaticamente una razza specifica.', pt: 'Dependendo do crime ou da área, automaticamente imagino uma raça específica.' }, dimension: 'P' },
          { text: { es: 'Noto si hay suposiciones automáticas en mi mente antes de ver la imagen.', en: 'I notice if there are automatic assumptions in my mind before seeing any image.', fr: 'Je remarque s\'il y a des suppositions automatiques dans mon esprit avant de voir l\'image.', de: 'Ich bemerke, ob es automatische Annahmen in meinem Kopf gibt, bevor ich ein Bild sehe.', it: 'Noto se ci sono assunzioni automatiche nella mia mente prima di vedere un\'immagine.', pt: 'Noto se há suposições automáticas na minha mente antes de ver a imagem.' }, dimension: 'C' },
          { text: { es: 'Espero los datos concretos. No asumo nada.', en: 'I wait for concrete data. I don\'t assume anything.', fr: 'J\'attends les données concrètes. Je ne suppose rien.', de: 'Ich warte auf konkrete Daten. Ich nehme nichts an.', it: 'Aspetto i dati concreti. Non assumo nulla.', pt: 'Espero os dados concretos. Não assumo nada.' }, dimension: 'N' },
          { text: { es: 'Soy consciente de cómo los medios construyen estereotipos y lo filtro activamente.', en: 'I\'m aware of how media builds stereotypes and I actively filter for that.', fr: 'Je suis conscient(e) de la façon dont les médias construisent des stéréotypes et je le filtre activement.', de: 'Ich bin mir bewusst, wie Medien Stereotypen aufbauen, und filtere das aktiv.', it: 'Sono consapevole di come i media costruiscano stereotipi e lo filtro attivamente.', pt: 'Estou ciente de como a mídia constrói estereótipos e filtro isso ativamente.' }, dimension: 'A' },
        ],
      },
      {
        id: 7,
        situation: { es: 'Una persona de otra raza hace algo que te molesta. ¿Atribuyes ese comportamiento a...?', en: 'A person of another race does something that bothers you. Do you attribute that behavior to...?', fr: 'Une personne d\'une autre race fait quelque chose qui vous dérange. Attribuez-vous ce comportement à... ?', de: 'Eine Person einer anderen Rasse tut etwas, das dich stört. Führst du dieses Verhalten zurück auf...?', it: 'Una persona di un\'altra razza fa qualcosa che ti infastidisce. Attribuisci quel comportamento a...?', pt: 'Uma pessoa de outra raça faz algo que te incomoda. Você atribui esse comportamento a...?' },
        options: [
          { text: { es: 'En algún nivel, sin quererlo, lo asocio con "cómo son ellos".', en: 'On some level, without meaning to, I associate it with "how they are".', fr: 'À un certain niveau, sans le vouloir, je l\'associe à "comment ils sont".', de: 'Auf irgendeiner Ebene, ohne es zu wollen, assoziiere ich es mit "wie sie eben sind".', it: 'A qualche livello, senza volerlo, lo associo a "come sono loro".', pt: 'Em algum nível, sem querer, associo a "como eles são".' }, dimension: 'P' },
          { text: { es: 'Me pregunto si estoy generalizando cuando no debería.', en: 'I ask myself if I\'m generalizing when I shouldn\'t be.', fr: 'Je me demande si je généralise alors que je ne devrais pas.', de: 'Ich frage mich, ob ich verallgemeinere, obwohl ich es nicht sollte.', it: 'Mi chiedo se sto generalizzando quando non dovrei.', pt: 'Me pergunto se estou generalizando quando não deveria.' }, dimension: 'C' },
          { text: { es: 'A esa persona específica. Los individuos son individuos.', en: 'To that specific person. Individuals are individuals.', fr: 'À cette personne spécifique. Les individus sont des individus.', de: 'Zu dieser spezifischen Person. Individuen sind Individuen.', it: 'A quella persona specifica. Gli individui sono individui.', pt: 'À essa pessoa específica. Indivíduos são indivíduos.' }, dimension: 'N' },
          { text: { es: 'Activamente resisto la generalización. Es una persona, no un grupo.', en: 'I actively resist the generalization. It\'s one person, not a group.', fr: 'Je résiste activement à la généralisation. C\'est une personne, pas un groupe.', de: 'Ich widerstehe aktiv der Verallgemeinerung. Es ist eine Person, keine Gruppe.', it: 'Resisto attivamente alla generalizzazione. È una persona, non un gruppo.', pt: 'Resisto ativamente à generalização. É uma pessoa, não um grupo.' }, dimension: 'A' },
        ],
      },
      {
        id: 8,
        situation: { es: '¿Tienes amistades cercanas con personas de otras razas?', en: 'Do you have close friendships with people of other races?', fr: 'Avez-vous des amitiés proches avec des personnes d\'autres races ?', de: 'Hast du enge Freundschaften mit Menschen anderer Rassen?', it: 'Hai amicizie strette con persone di altre razze?', pt: 'Você tem amizades próximas com pessoas de outras raças?' },
        options: [
          { text: { es: 'Pocas o ninguna, y nunca lo había pensado mucho.', en: 'Few or none, and I\'d never really thought about it.', fr: 'Peu ou aucune, et je n\'y avais jamais vraiment réfléchi.', de: 'Wenige oder keine, und ich hatte darüber nie wirklich nachgedacht.', it: 'Poche o nessuna, e non ci avevo mai pensato molto.', pt: 'Poucas ou nenhuma, e nunca havia pensado muito nisso.' }, dimension: 'P' },
          { text: { es: 'Algunas, pero me pregunto si mis círculos son suficientemente diversos.', en: 'Some, but I wonder if my circles are diverse enough.', fr: 'Quelques-unes, mais je me demande si mes cercles sont suffisamment diversifiés.', de: 'Einige, aber ich frage mich, ob meine Kreise vielfältig genug sind.', it: 'Alcune, ma mi chiedo se i miei circoli siano sufficientemente diversificati.', pt: 'Algumas, mas me pergunto se meus círculos são suficientemente diversos.' }, dimension: 'C' },
          { text: { es: 'Las amistades se dan naturalmente. No pienso en la raza al elegir amigos.', en: 'Friendships happen naturally. I don\'t think about race when choosing friends.', fr: 'Les amitiés se forment naturellement. Je ne pense pas à la race lorsque je choisis mes amis.', de: 'Freundschaften entstehen auf natürliche Weise. Ich denke nicht an Rasse, wenn ich Freunde wähle.', it: 'Le amicizie nascono naturalmente. Non penso alla razza nello scegliere gli amici.', pt: 'As amizades surgem naturalmente. Não penso em raça ao escolher amigos.' }, dimension: 'N' },
          { text: { es: 'Activamente busco diversidad en mis vínculos. Enriquece mi perspectiva.', en: 'I actively seek diversity in my relationships. It enriches my perspective.', fr: 'Je recherche activement la diversité dans mes liens. Ça enrichit ma perspective.', de: 'Ich suche aktiv nach Vielfalt in meinen Beziehungen. Es bereichert meine Perspektive.', it: 'Cerco attivamente la diversità nei miei legami. Arricchisce la mia prospettiva.', pt: 'Busco ativamente diversidade nos meus vínculos. Enriquece minha perspectiva.' }, dimension: 'A' },
        ],
      },
      {
        id: 9,
        situation: { es: 'Ves una pelea en la calle entre personas de razas diferentes. ¿Qué asumes primero?', en: 'You see a street fight between people of different races. What do you assume first?', fr: 'Vous voyez une bagarre dans la rue entre des personnes de différentes races. Qu\'assumez-vous en premier ?', de: 'Du siehst eine Schlägerei auf der Straße zwischen Personen verschiedener Rassen. Was nimmst du zuerst an?', it: 'Vedi una rissa in strada tra persone di razze diverse. Cosa assumi per primo?', pt: 'Você vê uma briga na rua entre pessoas de raças diferentes. O que você assume primeiro?' },
        options: [
          { text: { es: 'Hay un impulso automático a asumir quién fue el agresor basado en las razas.', en: 'There\'s an automatic impulse to assume who the aggressor was based on race.', fr: 'Il y a une impulsion automatique à supposer qui était l\'agresseur en fonction des races.', de: 'Es gibt einen automatischen Impuls anzunehmen, wer der Angreifer war, basierend auf den Rassen.', it: 'C\'è un impulso automatico a supporre chi fosse l\'aggressore in base alle razze.', pt: 'Há um impulso automático de supor quem foi o agressor com base nas raças.' }, dimension: 'P' },
          { text: { es: 'Noto mis suposiciones iniciales y las cuestiono.', en: 'I notice my initial assumptions and question them.', fr: 'Je remarque mes suppositions initiales et les questionne.', de: 'Ich bemerke meine anfänglichen Annahmen und hinterfrage sie.', it: 'Noto le mie supposizioni iniziali e le metto in discussione.', pt: 'Noto minhas suposições iniciais e as questiono.' }, dimension: 'C' },
          { text: { es: 'No asumo nada sin más información. Las peleas tienen contextos.', en: 'I don\'t assume anything without more information. Fights have context.', fr: 'Je ne suppose rien sans plus d\'informations. Les bagarres ont des contextes.', de: 'Ich nehme ohne weitere Informationen nichts an. Kämpfe haben Zusammenhänge.', it: 'Non assumo nulla senza più informazioni. Le risse hanno contesti.', pt: 'Não assumo nada sem mais informações. Brigas têm contextos.' }, dimension: 'N' },
          { text: { es: 'Evalúo qué ayuda puedo ofrecer sin asumir nada sobre los involucrados.', en: 'I evaluate what help I can offer without assuming anything about those involved.', fr: 'J\'évalue l\'aide que je peux offrir sans rien supposer sur les personnes impliquées.', de: 'Ich bewerte, welche Hilfe ich anbieten kann, ohne etwas über die Beteiligten anzunehmen.', it: 'Valuto quale aiuto posso offrire senza assumere nulla sugli individui coinvolti.', pt: 'Avalio que ajuda posso oferecer sem assumir nada sobre os envolvidos.' }, dimension: 'A' },
        ],
      },
      {
        id: 10,
        situation: { es: 'Alguien te dice que tienes "prejuicios implícitos" que no reconoces. ¿Cómo reaccionas?', en: 'Someone tells you that you have "implicit biases" you\'re not aware of. How do you react?', fr: 'Quelqu\'un vous dit que vous avez des "biais implicites" que vous ne reconnaissez pas. Comment réagissez-vous ?', de: 'Jemand sagt dir, dass du "implizite Vorurteile" hast, die du nicht erkennst. Wie reagierst du?', it: 'Qualcuno ti dice che hai "pregiudizi impliciti" che non riconosci. Come reagisci?', pt: 'Alguém te diz que você tem "preconceitos implícitos" que não reconhece. Como você reage?' },
        options: [
          { text: { es: 'Me molesta. No soy racista y no me gusta que me etiqueten así.', en: 'It bothers me. I\'m not racist and I don\'t like being labeled that way.', fr: 'Ça me dérange. Je ne suis pas raciste et je n\'aime pas être étiqueté(e) ainsi.', de: 'Es stört mich. Ich bin kein Rassist und ich mag es nicht, so etikettiert zu werden.', it: 'Mi disturba. Non sono razzista e non mi piace essere etichettato/a così.', pt: 'Me incomoda. Não sou racista e não gosto de ser rotulado assim.' }, dimension: 'P' },
          { text: { es: 'Lo escucho aunque me incomoda. Podría tener razón.', en: 'I listen even if it makes me uncomfortable. They could be right.', fr: 'Je l\'écoute même si ça me met mal à l\'aise. Cette personne pourrait avoir raison.', de: 'Ich höre zu, auch wenn es mich unwohl fühlen lässt. Die Person könnte recht haben.', it: 'Lo ascolto anche se mi mette a disagio. Potrebbe avere ragione.', pt: 'Ouço mesmo que me incomode. Pode ter razão.' }, dimension: 'C' },
          { text: { es: 'Lo considero objetivamente. Todo el mundo tiene sesgos, vale la pena examinarlos.', en: 'I consider it objectively. Everyone has biases and it\'s worth examining them.', fr: 'Je le considère objectivement. Tout le monde a des biais, ça vaut la peine de les examiner.', de: 'Ich betrachte es objektiv. Jeder hat Vorurteile und es lohnt sich, sie zu untersuchen.', it: 'Lo considero obiettivamente. Tutti hanno pregiudizi, vale la pena esaminarli.', pt: 'Considero objetivamente. Todo mundo tem vieses e vale a pena examiná-los.' }, dimension: 'N' },
          { text: { es: 'Lo agradezco. La retroalimentación sobre puntos ciegos es valiosa.', en: 'I appreciate it. Feedback on blind spots is valuable.', fr: 'Je l\'apprécie. Les retours sur les angles morts sont précieux.', de: 'Ich schätze es. Feedback zu blinden Flecken ist wertvoll.', it: 'Lo apprezzo. Il feedback sui punti ciechi è prezioso.', pt: 'Agradeço. O feedback sobre pontos cegos é valioso.' }, dimension: 'A' },
        ],
      },
    ],
    characters: [
      { name: { es: 'El Inconsciente Bienintencionado', en: 'The Well-Meaning Unconscious', fr: 'L\'Inconscient Bien Intentionné', de: 'Der Gutgemeinte Unbewusste', it: 'L\'Inconsapevole Ben Intenzionato', pt: 'O Inconsciente Bem-Intencionado' }, dimensions: ['P'], photo: '/characters/unconscious-bias.jpg', description: { es: 'No se considera racista, pero sus reacciones automáticas cuentan otra historia.', en: 'Doesn\'t consider themselves racist, but their automatic reactions tell a different story.', fr: 'Ne se considère pas raciste, mais ses réactions automatiques racontent une autre histoire.', de: 'Hält sich nicht für rassistisch, aber seine automatischen Reaktionen erzählen eine andere Geschichte.', it: 'Non si considera razzista, ma le sue reazioni automatiche raccontano un\'altra storia.', pt: 'Não se considera racista, mas suas reações automáticas contam outra história.' }, philosophy: { es: 'No tienes malas intenciones. Genuinamente crees en la igualdad. Pero el sistema en el que creciste dejó huellas que operan debajo del nivel de conciencia. Reconocerlas es el primer paso, el más difícil.', en: 'You don\'t have bad intentions. You genuinely believe in equality. But the system you grew up in left marks that operate below the level of consciousness. Recognizing them is the first step — and the hardest.', fr: 'Vous n\'avez pas de mauvaises intentions. Vous croyez sincèrement en l\'égalité. Mais le système dans lequel vous avez grandi a laissé des traces qui opèrent en dessous du niveau de conscience. Les reconnaître est la première étape, la plus difficile.', de: 'Du hast keine schlechten Absichten. Du glaubst wirklich an Gleichheit. Aber das System, in dem du aufgewachsen bist, hat Spuren hinterlassen, die unterhalb der Bewusstseinsschwelle wirken. Sie zu erkennen ist der erste Schritt, der schwierigste.', it: 'Non hai cattive intenzioni. Credi sinceramente nell\'uguaglianza. Ma il sistema in cui sei cresciuto ha lasciato tracce che operano al di sotto del livello di coscienza. Riconoscerle è il primo passo, il più difficile.', pt: 'Você não tem más intenções. Acredita genuinamente na igualdade. Mas o sistema em que cresceu deixou marcas que operam abaixo do nível de consciência. Reconhecê-las é o primeiro passo, o mais difícil.' } },
      { name: { es: 'El Que Está Aprendiendo', en: 'The One Who Is Learning', fr: 'Celui Qui Apprend', de: 'Der Lernende', it: 'Chi Sta Imparando', pt: 'Quem Está Aprendendo' }, dimensions: ['C'], photo: '/characters/learning.jpg', description: { es: 'Ve sus propios sesgos y trabaja activamente en ellos.', en: 'Sees their own biases and actively works on them.', fr: 'Voit ses propres biais et travaille activement dessus.', de: 'Sieht seine eigenen Vorurteile und arbeitet aktiv daran.', it: 'Vede i propri pregiudizi e lavora attivamente su di essi.', pt: 'Vê seus próprios preconceitos e trabalha ativamente neles.' }, philosophy: { es: 'Tienes la humildad de reconocer que tienes puntos ciegos y la valentía de examinarlos. Eso no es fácil. La mayoría prefiere la comodidad de creer que no tiene prejuicios. Tú eliges el camino más honesto.', en: 'You have the humility to acknowledge your blind spots and the courage to examine them. That\'s not easy. Most people prefer the comfort of believing they have no biases. You choose the more honest path.', fr: 'Vous avez l\'humilité de reconnaître vos angles morts et le courage de les examiner. Ce n\'est pas facile. La plupart des gens préfèrent le confort de croire qu\'ils n\'ont pas de préjugés. Vous choisissez le chemin le plus honnête.', de: 'Du hast die Demut, deine blinden Flecken anzuerkennen, und den Mut, sie zu untersuchen. Das ist nicht einfach. Die meisten Menschen bevorzugen den Komfort des Glaubens, keine Vorurteile zu haben. Du wählst den ehrlicheren Weg.', it: 'Hai l\'umiltà di riconoscere i tuoi punti ciechi e il coraggio di esaminarli. Non è facile. La maggior parte delle persone preferisce il comfort di credere di non avere pregiudizi. Tu scegli il percorso più onesto.', pt: 'Você tem a humildade de reconhecer seus pontos cegos e a coragem de examiná-los. Isso não é fácil. A maioria prefere o conforto de acreditar que não tem preconceitos. Você escolhe o caminho mais honesto.' } },
      { name: { es: 'El Neutral Pasivo', en: 'The Passive Neutral', fr: 'Le Neutre Passif', de: 'Der Passive Neutrale', it: 'Il Neutro Passivo', pt: 'O Neutro Passivo' }, dimensions: ['N'], photo: '/characters/passive-neutral.jpg', description: { es: 'No discrimina, pero tampoco actúa contra la discriminación.', en: 'Doesn\'t discriminate, but doesn\'t act against discrimination either.', fr: 'Ne discrimine pas, mais n\'agit pas non plus contre la discrimination.', de: 'Diskriminiert nicht, handelt aber auch nicht gegen Diskriminierung.', it: 'Non discrimina, ma non agisce nemmeno contro la discriminazione.', pt: 'Não discrimina, mas também não age contra a discriminação.' }, philosophy: { es: 'No participas en el problema activamente, pero tampoco eres parte de la solución. La neutralidad en situaciones de injusticia no es neutral — es, en efecto, una posición. Vale la pena pensarlo.', en: 'You don\'t actively participate in the problem, but you\'re not part of the solution either. Neutrality in the face of injustice isn\'t neutral — it is, in effect, a position. Worth thinking about.', fr: 'Vous ne participez pas activement au problème, mais vous ne faites pas non plus partie de la solution. La neutralité face à l\'injustice n\'est pas neutre — c\'est, en fait, une position. Ça vaut la peine d\'y réfléchir.', de: 'Du nimmst nicht aktiv am Problem teil, bist aber auch kein Teil der Lösung. Neutralität angesichts von Ungerechtigkeit ist nicht neutral — sie ist, im Wesentlichen, eine Position. Es lohnt sich, darüber nachzudenken.', it: 'Non partecipi attivamente al problema, ma non fai parte della soluzione neanche. La neutralità di fronte all\'ingiustizia non è neutrale — è, di fatto, una posizione. Vale la pena rifletterci.', pt: 'Você não participa ativamente do problema, mas também não faz parte da solução. A neutralidade diante da injustiça não é neutra — é, de fato, uma posição. Vale a pena pensar nisso.' } },
      { name: { es: 'El Antirracista Activo', en: 'The Active Anti-Racist', fr: 'L\'Antiraciste Actif', de: 'Der Aktive Antirassist', it: 'L\'Antirazzista Attivo', pt: 'O Antirracista Ativo' }, dimensions: ['A'], photo: '/characters/antiracist.jpg', description: { es: 'No basta con no discriminar. Trabaja activamente contra los sistemas de exclusión.', en: 'Not discriminating isn\'t enough. Actively works against systems of exclusion.', fr: 'Ne pas discriminer ne suffit pas. Travaille activement contre les systèmes d\'exclusion.', de: 'Nicht zu diskriminieren reicht nicht. Arbeitet aktiv gegen Ausgrenzungssysteme.', it: 'Non discriminare non basta. Lavora attivamente contro i sistemi di esclusione.', pt: 'Não discriminar não é suficiente. Trabalha ativamente contra os sistemas de exclusão.' }, philosophy: { es: 'Entiendes que el antirracismo no es un estado que se alcanza — es una práctica. No basta con no discriminar; es necesario cuestionar los sistemas, los propios sesgos y actuar cuando otros no lo hacen.', en: 'You understand that anti-racism isn\'t a state to be reached — it\'s a practice. Not discriminating isn\'t enough; it\'s necessary to question systems, one\'s own biases, and act when others don\'t.', fr: 'Vous comprenez que l\'antiracisme n\'est pas un état à atteindre — c\'est une pratique. Ne pas discriminer ne suffit pas ; il est nécessaire de questionner les systèmes, ses propres biais et d\'agir quand les autres ne le font pas.', de: 'Du verstehst, dass Antirassismus kein Zustand ist, der erreicht wird — es ist eine Praxis. Nicht zu diskriminieren reicht nicht; es ist notwendig, Systeme, die eigenen Vorurteile zu hinterfragen und zu handeln, wenn andere es nicht tun.', it: 'Capisci che l\'antirazzismo non è uno stato da raggiungere — è una pratica. Non discriminare non basta; è necessario mettere in discussione i sistemi, i propri pregiudizi e agire quando gli altri non lo fanno.', pt: 'Você entende que o antirracismo não é um estado a ser alcançado — é uma prática. Não discriminar não é suficiente; é necessário questionar os sistemas, os próprios preconceitos e agir quando os outros não agem.' } },
      { name: { es: 'El Consciente en Transición', en: 'The One in Transition', fr: 'Le Conscient en Transition', de: 'Der im Übergang Bewusste', it: 'Il Consapevole in Transizione', pt: 'O Consciente em Transição' }, dimensions: ['P', 'C'], photo: '/characters/transition.jpg', description: { es: 'Tiene sesgos que está empezando a ver y trabajar.', en: 'Has biases they\'re beginning to see and work on.', fr: 'A des biais qu\'il commence à voir et sur lesquels il travaille.', de: 'Hat Vorurteile, die er anfängt zu sehen und zu bearbeiten.', it: 'Ha pregiudizi che sta iniziando a vedere e su cui sta lavorando.', pt: 'Tem preconceitos que está começando a ver e trabalhar.' }, philosophy: { es: 'Estás en el proceso más honesto: reconocer lo que hay y trabajar en cambiarlo. Tus reacciones automáticas a veces te sorprenden. Esa sorpresa es crecimiento.', en: 'You\'re in the most honest process: recognizing what\'s there and working to change it. Your automatic reactions sometimes surprise you. That surprise is growth.', fr: 'Vous êtes dans le processus le plus honnête : reconnaître ce qui est là et travailler à le changer. Vos réactions automatiques vous surprennent parfois. Cette surprise, c\'est de la croissance.', de: 'Du bist im ehrlichsten Prozess: erkennen, was da ist, und daran arbeiten, es zu verändern. Deine automatischen Reaktionen überraschen dich manchmal. Diese Überraschung ist Wachstum.', it: 'Sei nel processo più onesto: riconoscere ciò che c\'è e lavorare per cambiarlo. Le tue reazioni automatiche a volte ti sorprendono. Quella sorpresa è crescita.', pt: 'Você está no processo mais honesto: reconhecer o que existe e trabalhar para mudá-lo. Suas reações automáticas às vezes te surpreendem. Essa surpresa é crescimento.' } },
      { name: { es: 'El Neutral Crítico', en: 'The Critical Neutral', fr: 'Le Neutre Critique', de: 'Der Kritisch Neutrale', it: 'Il Neutro Critico', pt: 'O Neutro Crítico' }, dimensions: ['N', 'C'], photo: '/characters/neutral-critical.jpg', description: { es: 'Trata de ser neutral pero es consciente de sus limitaciones.', en: 'Tries to be neutral but is aware of their limitations.', fr: 'Essaie d\'être neutre mais est conscient(e) de ses limites.', de: 'Versucht neutral zu sein, ist sich aber seiner Grenzen bewusst.', it: 'Cerca di essere neutro ma è consapevole dei propri limiti.', pt: 'Tenta ser neutro, mas está ciente de suas limitações.' }, philosophy: { es: 'Buscas objetividad y al mismo tiempo reconoces que la neutralidad perfecta no existe. Eso es un punto de partida honesto para seguir creciendo.', en: 'You seek objectivity and at the same time recognize that perfect neutrality doesn\'t exist. That\'s an honest starting point for continued growth.', fr: 'Vous recherchez l\'objectivité et reconnaissez en même temps que la neutralité parfaite n\'existe pas. C\'est un point de départ honnête pour continuer à progresser.', de: 'Du strebst nach Objektivität und erkennst gleichzeitig, dass perfekte Neutralität nicht existiert. Das ist ein ehrlicher Ausgangspunkt für weiteres Wachstum.', it: 'Cerchi l\'obiettività e allo stesso tempo riconosci che la neutralità perfetta non esiste. Questo è un punto di partenza onesto per continuare a crescere.', pt: 'Você busca objetividade e ao mesmo tempo reconhece que a neutralidade perfeita não existe. Esse é um ponto de partida honesto para continuar crescendo.' } },
      { name: { es: 'El Consciente Activo', en: 'The Conscious Activist', fr: 'Le Conscient Actif', de: 'Der Bewusst Aktive', it: 'Il Consapevole Attivo', pt: 'O Consciente Ativo' }, dimensions: ['C', 'A'], photo: '/characters/conscious-active.jpg', description: { es: 'Tiene conciencia crítica y la convierte en acción.', en: 'Has critical awareness and turns it into action.', fr: 'A une conscience critique et la transforme en action.', de: 'Hat kritisches Bewusstsein und verwandelt es in Handeln.', it: 'Ha consapevolezza critica e la trasforma in azione.', pt: 'Tem consciência crítica e a converte em ação.' }, philosophy: { es: 'No solo ves los sesgos — los nombras y actúas. Cuando alguien hace un chiste racista, hablas. Cuando un proceso laboral podría ser sesgado, lo señalas. La conciencia sin acción es incompleta.', en: 'You don\'t just see biases — you name them and act. When someone makes a racist joke, you speak up. When a work process could be biased, you point it out. Awareness without action is incomplete.', fr: 'Vous ne faites pas que voir les biais — vous les nommez et agissez. Quand quelqu\'un fait une blague raciste, vous parlez. Quand un processus de travail pourrait être biaisé, vous le signalez. La conscience sans action est incomplète.', de: 'Du siehst nicht nur Vorurteile — du benennst sie und handelst. Wenn jemand einen rassistischen Witz macht, sprichst du. Wenn ein Arbeitsprozess voreingenommen sein könnte, weist du darauf hin. Bewusstsein ohne Handeln ist unvollständig.', it: 'Non solo vedi i pregiudizi — li nomini e agisci. Quando qualcuno fa una battuta razzista, parli. Quando un processo lavorativo potrebbe essere distorto, lo segnali. La consapevolezza senza azione è incompleta.', pt: 'Você não apenas vê os vieses — os nomeia e age. Quando alguém faz uma piada racista, você fala. Quando um processo de trabalho pode ser tendencioso, você aponta. A consciência sem ação é incompleta.' } },
      { name: { es: 'El Aliado Comprometido', en: 'The Committed Ally', fr: 'L\'Allié Engagé', de: 'Der Engagierte Verbündete', it: 'L\'Alleato Impegnato', pt: 'O Aliado Comprometido' }, dimensions: ['N', 'A'], photo: '/characters/committed-ally.jpg', description: { es: 'Busca la equidad activamente aunque no afecte directamente su grupo.', en: 'Actively seeks equity even when it doesn\'t directly affect their group.', fr: 'Recherche activement l\'équité même si ça n\'affecte pas directement son groupe.', de: 'Sucht aktiv nach Gerechtigkeit, auch wenn es seine eigene Gruppe nicht direkt betrifft.', it: 'Cerca attivamente l\'equità anche quando non riguarda direttamente il suo gruppo.', pt: 'Busca a equidade ativamente mesmo quando não afeta diretamente seu grupo.' }, philosophy: { es: 'No eres de los grupos más afectados por el racismo, pero eso no es excusa para no actuar. Entiendes que la justicia es indivisible. Cuando los derechos de alguien son vulnerados, también es tu problema.', en: 'You\'re not from the groups most affected by racism, but that\'s no excuse not to act. You understand that justice is indivisible. When someone\'s rights are violated, it\'s your problem too.', fr: 'Vous n\'êtes pas parmi les groupes les plus touchés par le racisme, mais ce n\'est pas une raison de ne pas agir. Vous comprenez que la justice est indivisible. Quand les droits de quelqu\'un sont bafoués, c\'est aussi votre problème.', de: 'Du gehörst nicht zu den von Rassismus am stärksten betroffenen Gruppen, aber das ist keine Entschuldigung, nicht zu handeln. Du verstehst, dass Gerechtigkeit unteilbar ist. Wenn die Rechte von jemandem verletzt werden, ist es auch dein Problem.', it: 'Non appartieni ai gruppi più colpiti dal razzismo, ma questo non è un motivo per non agire. Capisci che la giustizia è indivisibile. Quando i diritti di qualcuno vengono violati, è anche un tuo problema.', pt: 'Você não é dos grupos mais afetados pelo racismo, mas isso não é desculpa para não agir. Você entende que a justiça é indivisível. Quando os direitos de alguém são violados, também é seu problema.' } },
    ],
  };

  await prisma.quiz.upsert({
    where: { slug: 'racist' },
    update: {
      title: data.title,
      description: data.description,
      scenarioLabel: data.scenarioLabel,
      dimensionLabels: data.dimensionLabels,
      questions: data.questions,
      characters: data.characters,
    },
    create: data,
  });
}
